/* THE KNOWN WORLD — the people of the tale.
   house: a "primary" great-house id for the card's fallback shield (null = none).
   Family links (father/mother/spouse/children/siblings) refer to other entries by
   exact name — and are kept SPOILER-FREE: they show a person's public, first-known
   kin, never a later reveal. blurb never states a character's fate; the gated
   "Alive as of…" line and the death lists carry that. death {s,e} / bookDeath {b,ch}
   exist ONLY to drive that gated status and are never shown in the blurb.
   Group membership (incl. Night's Watch, Kingsguard, factions, and time-gated
   dual houses like Tommen) lives in js/groups.js, not here. */

const CHARACTERS = {
  // ================= House Stark =================
  "Rickard Stark": { house: "stark", born: "Winterfell", children: ["Brandon Stark", "Eddard Stark", "Lyanna Stark", "Benjen Stark"],
    blurb: "Lord of Winterfell and Warden of the North in the years before the tale, remembered for his four children and his southron ambitions.",
    death: { s: 0, e: 0, how: "Died before the story" } },
  "Brandon Stark": { house: "stark", born: "Winterfell", father: "Rickard Stark", siblings: ["Eddard Stark", "Lyanna Stark", "Benjen Stark"],
    blurb: "Ned's wild elder brother, once heir to Winterfell and betrothed to Catelyn Tully; a name spoken of but never seen.",
    death: { s: 0, e: 0, how: "Died before the story" } },
  "Eddard Stark": { house: "stark", born: "Winterfell", father: "Rickard Stark", spouse: "Catelyn Stark", siblings: ["Brandon Stark", "Lyanna Stark", "Benjen Stark"],
    children: ["Robb Stark", "Sansa Stark", "Arya Stark", "Bran Stark", "Rickon Stark", "Jon Snow"],
    blurb: "Lord of Winterfell, Warden of the North, and the most honorable man in the realm — a soldier who wants nothing so much as to go home. Raised his bastard boy alongside his trueborn children.",
    death: { s: 1, e: 9, how: "Beheaded at the Great Sept of Baelor" }, bookDeath: { b: 1, ch: 66, how: "Beheaded at Baelor's sept" } },
  "Catelyn Stark": { house: "stark", born: "Riverrun", father: "Hoster Tully", spouse: "Eddard Stark", siblings: ["Lysa Arryn", "Edmure Tully"],
    children: ["Robb Stark", "Sansa Stark", "Arya Stark", "Bran Stark", "Rickon Stark"],
    blurb: "Born a Tully of Riverrun, Lady of Winterfell by marriage: fierce in defense of her children and never quite at peace with the bastard raised beneath her roof.",
    death: { s: 3, e: 9, how: "Slain at the Red Wedding" }, bookDeath: { b: 3, ch: 52, how: "Killed at the Red Wedding" } },
  "Robb Stark": { house: "stark", born: "Winterfell", father: "Eddard Stark", mother: "Catelyn Stark", siblings: ["Sansa Stark", "Arya Stark", "Bran Stark", "Rickon Stark", "Jon Snow"],
    spouse: "Talisa Stark", bookSpouse: "Jeyne Westerling",
    blurb: "The Stark heir, a boy of fifteen with a direwolf named Grey Wind and his father's sense of duty. Fostered his half-brother Jon and his father's ward Theon like brothers.",
    death: { s: 3, e: 9, how: "Murdered at the Red Wedding" }, bookDeath: { b: 3, ch: 52, how: "Murdered at the Red Wedding" } },
  "Jeyne Westerling": { only: "book", house: "stark", born: "The Crag", spouse: "Robb Stark",
    blurb: "A gentle daughter of a small westerlands house who nursed a wounded young king at the Crag — and became his queen at the cost of a sworn marriage pact. This is the books' telling; the show gave Robb's heart to Talisa of Volantis instead." },
  "Sansa Stark": { house: "stark", born: "Winterfell", father: "Eddard Stark", mother: "Catelyn Stark", siblings: ["Robb Stark", "Arya Stark", "Bran Stark", "Rickon Stark", "Jon Snow"],
    blurb: "The elder Stark daughter, courteous and dreaming of songs and southern knights, betrothed young to a prince. Her direwolf was named Lady." },
  "Arya Stark": { house: "stark", born: "Winterfell", father: "Eddard Stark", mother: "Catelyn Stark", siblings: ["Robb Stark", "Sansa Stark", "Bran Stark", "Rickon Stark", "Jon Snow"],
    blurb: "The younger Stark daughter — wilful, quick, happier with a blade than a needle. She named her direwolf Nymeria, for a warrior queen." },
  "Bran Stark": { house: "stark", born: "Winterfell", father: "Eddard Stark", mother: "Catelyn Stark", siblings: ["Robb Stark", "Sansa Stark", "Arya Stark", "Rickon Stark", "Jon Snow"],
    blurb: "The second Stark son, a fearless climber who dreams of being a knight of the Kingsguard. His direwolf is Summer." },
  "Rickon Stark": { house: "stark", born: "Winterfell", father: "Eddard Stark", mother: "Catelyn Stark", siblings: ["Robb Stark", "Sansa Stark", "Arya Stark", "Bran Stark", "Jon Snow"],
    blurb: "The youngest wolf, a wild little boy barely out of the nursery, with a black direwolf named Shaggydog.",
    death: { s: 6, e: 9, how: "Killed before the Battle of the Bastards" } },
  "Jon Snow": { house: "stark", born: "Winterfell", father: "Eddard Stark", siblings: ["Robb Stark", "Sansa Stark", "Arya Stark", "Bran Stark", "Rickon Stark"],
    blurb: "Ned Stark's bastard son, raised at Winterfell and always a half-step apart from it. Skilled with a blade, hungry to prove himself, and bound for the Wall. His direwolf is the albino Ghost." },
  "Benjen Stark": { house: "stark", born: "Winterfell", father: "Rickard Stark", siblings: ["Brandon Stark", "Eddard Stark", "Lyanna Stark"],
    blurb: "Ned's younger brother, First Ranger of the Night's Watch, who gave up Winterfell for the black cloak and the lands beyond the Wall.",
    death: { s: 7, e: 6, how: "Lost beyond the Wall" } },
  "Lyanna Stark": { house: "stark", born: "Winterfell", father: "Rickard Stark", siblings: ["Brandon Stark", "Eddard Stark", "Benjen Stark"],
    blurb: "Ned's beautiful, headstrong sister, betrothed to Robert Baratheon. Her abduction lit Robert's Rebellion; she died before the tale, and Ned will not speak of how.",
    death: { s: 0, e: 0, how: "Died before the story" } },

  // ================= House Lannister =================
  "Tywin Lannister": { house: "lannister", born: "Casterly Rock", siblings: ["Kevan Lannister"], children: ["Cersei Lannister", "Jaime Lannister", "Tyrion Lannister"],
    blurb: "Lord of Casterly Rock and the most feared man in Westeros: the coldest, richest, most calculating lord of his age, thrice Hand of the King and master of the family that pays its debts.",
    death: { s: 4, e: 10, how: "Shot on his privy by Tyrion" }, bookDeath: { b: 3, ch: 78, how: "A crossbow bolt on the privy" } },
  "Cersei Lannister": { house: "lannister", born: "Casterly Rock", father: "Tywin Lannister", spouse: "Robert Baratheon", siblings: ["Jaime Lannister", "Tyrion Lannister"],
    children: ["Joffrey Baratheon", "Myrcella Baratheon", "Tommen Baratheon"],
    blurb: "Queen to King Robert and daughter of Tywin: proud, clever, and coldly protective of her three golden children. She loves her twin Jaime best of anyone alive.",
    death: { s: 8, e: 5, how: "Died beneath the Red Keep" } },
  "Jaime Lannister": { house: "lannister", born: "Casterly Rock", father: "Tywin Lannister", siblings: ["Cersei Lannister", "Tyrion Lannister"],
    blurb: "The Kingslayer: golden, arrogant, and the finest sword in the Seven Kingdoms, sworn to the Kingsguard at seventeen after cutting down the king he was sworn to protect. Cersei's twin.",
    death: { s: 8, e: 5, how: "Died beneath the Red Keep" } },
  "Tyrion Lannister": { house: "lannister", born: "Casterly Rock", father: "Tywin Lannister", siblings: ["Cersei Lannister", "Jaime Lannister"],
    blurb: "The Imp: a dwarf, and the cleverest of the Lannisters, which his father has never forgiven him. He drinks, he reads, and he knows things — the only weapons his family left him." },
  "Joffrey Baratheon": { house: "lannister", born: "King's Landing", father: "Robert Baratheon", mother: "Cersei Lannister", siblings: ["Myrcella Baratheon", "Tommen Baratheon"],
    blurb: "Crown prince and heir to the Iron Throne, a golden boy of twelve with a cruel streak his mother indulges and his father ignores.",
    death: { s: 4, e: 2, how: "Poisoned at his wedding" }, bookDeath: { b: 3, ch: 61, how: "The Strangler in his wedding wine" } },
  "Tommen Baratheon": { house: "lannister", born: "King's Landing", father: "Robert Baratheon", mother: "Cersei Lannister", siblings: ["Joffrey Baratheon", "Myrcella Baratheon"],
    blurb: "The younger prince, a gentle, plump little boy who loves his kittens and his sister far more than any thought of crowns.",
    death: { s: 6, e: 10, how: "Died when the sept burned" } },
  "Myrcella Baratheon": { house: "lannister", born: "King's Landing", father: "Robert Baratheon", mother: "Cersei Lannister", siblings: ["Joffrey Baratheon", "Tommen Baratheon"],
    blurb: "The princess of the realm, sweet-natured and biddable, the middle of Cersei's three children.",
    death: { s: 5, e: 10, how: "Poisoned in Dorne" } },
  "Kevan Lannister": { house: "lannister", born: "Casterly Rock", siblings: ["Tywin Lannister"], children: ["Lancel Lannister"],
    blurb: "Tywin's steadfast younger brother and right hand, a competent, unambitious soldier who has spent his life in his brother's shadow and never resented it.",
    death: { s: 6, e: 10, how: "Died when the sept burned" }, bookDeath: { b: 5, ch: 73, how: "A crossbow in the night" } },
  "Lancel Lannister": { house: "lannister", born: "Casterly Rock", father: "Kevan Lannister",
    blurb: "Tywin's nephew and King Robert's squire, an eager, pliable young man forever trying to be of use to someone more powerful.",
    death: { s: 6, e: 10, how: "Died when the sept burned" } },

  // ================= House Baratheon =================
  "Robert Baratheon": { house: "baratheon", born: "Storm's End", spouse: "Cersei Lannister", siblings: ["Stannis Baratheon", "Renly Baratheon"],
    children: ["Joffrey Baratheon", "Myrcella Baratheon", "Tommen Baratheon"],
    blurb: "The king who won his throne with a warhammer and has spent the years since eating, drinking, and whoring away the crown's gold — still mourning a Stark girl he never wed.",
    death: { s: 1, e: 7, how: "Gored by a boar" }, bookDeath: { b: 1, ch: 50, how: "Gored on a hunt" } },
  "Stannis Baratheon": { house: "baratheon", born: "Storm's End", spouse: "Selyse Baratheon", siblings: ["Robert Baratheon", "Renly Baratheon"], children: ["Shireen Baratheon"],
    blurb: "Robert's dour middle brother, Lord of Dragonstone: humorless, rigid, and unbending in his sense of what is owed him by right and law.",
    death: { s: 5, e: 10, how: "Fell at Winterfell" } },
  "Renly Baratheon": { house: "baratheon", born: "Storm's End", siblings: ["Robert Baratheon", "Stannis Baratheon"],
    blurb: "The youngest Baratheon brother, Lord of Storm's End: charming, handsome, and beloved at court, with the easy warmth neither of his brothers could manage.",
    death: { s: 2, e: 5, how: "Killed by a shadow" }, bookDeath: { b: 2, ch: 34, how: "A shadow with his brother's face" } },
  "Shireen Baratheon": { house: "baratheon", born: "Dragonstone", father: "Stannis Baratheon", mother: "Selyse Baratheon",
    blurb: "Stannis's only child, a bright, bookish girl scarred by greyscale, who teaches those around her their letters and asks too many good questions.",
    death: { s: 5, e: 9, how: "Burned at Dragonstone's cause" } },
  "Selyse Baratheon": { house: "baratheon", born: "Brightwater Keep", spouse: "Stannis Baratheon", children: ["Shireen Baratheon"],
    blurb: "Stannis's stern, sour queen, wholly given over to the red god's fire and rather less devoted to her scarred daughter.",
    death: { s: 5, e: 10, how: "Died at Winterfell's ruin" } },
  "Gendry": { house: "baratheon", born: "King's Landing",
    blurb: "A bull-strong blacksmith's apprentice from Flea Bottom with a stubborn streak, who has no notion of who his father was — though his black hair and blue eyes tell a story." },

  // ================= House Targaryen =================
  "Aerys II Targaryen": { house: "targaryen", born: "King's Landing", children: ["Rhaegar Targaryen", "Viserys Targaryen", "Daenerys Targaryen"],
    blurb: "The Mad King, last Targaryen to sit the Iron Throne: a burned, paranoid ruin of a king by the end, overthrown in the rebellion that put Robert on the throne.",
    death: { s: 0, e: 0, how: "Died in the Sack of King's Landing, before the story" } },
  "Rhaegar Targaryen": { house: "targaryen", born: "Dragonstone", father: "Aerys II Targaryen", siblings: ["Viserys Targaryen", "Daenerys Targaryen"],
    blurb: "The Mad King's eldest son and heir, a melancholy, book-loved prince and peerless warrior whose abduction of Lyanna Stark set the realm on fire.",
    death: { s: 0, e: 0, how: "Slain at the Trident, before the story" } },
  "Viserys Targaryen": { house: "targaryen", born: "Dragonstone", father: "Aerys II Targaryen", siblings: ["Rhaegar Targaryen", "Daenerys Targaryen"],
    blurb: "The exiled would-be king, last living son of the Mad King, who has dragged his little sister across the Free Cities all their lives, hawking her for an army to take him home.",
    death: { s: 1, e: 6, how: "Given a golden crown" }, bookDeath: { b: 1, ch: 47, how: "A crown of molten gold" } },
  "Daenerys Targaryen": { house: "targaryen", born: "Dragonstone", father: "Aerys II Targaryen", spouse: "Khal Drogo", siblings: ["Rhaegar Targaryen", "Viserys Targaryen"],
    blurb: "The last Targaryen princess, born in exile and sold in marriage by her brother to a Dothraki khal — a frightened girl who begins to discover she is anything but.",
    death: { s: 8, e: 6, how: "Slain in the throne room" } },
  "Khal Drogo": { house: "targaryen", born: "The Dothraki Sea", spouse: "Daenerys Targaryen",
    blurb: "A great khal of the Dothraki, lord of forty thousand riders, who has never lost a fight and never cut his hair. Wed to Daenerys for the price of an army.",
    death: { s: 1, e: 10, how: "A wound gone bad, and a mercy" }, bookDeath: { b: 1, ch: 69, how: "A wound, sorcery, and mercy" } },

  // ================= House Tully =================
  "Hoster Tully": { house: "tully", born: "Riverrun", siblings: ["Brynden Tully"], children: ["Catelyn Stark", "Lysa Arryn", "Edmure Tully"],
    blurb: "Lord of Riverrun and the Riverlands, who married his daughters to the realm's two great Hands and has grown old and ailing in his ancestral seat.",
    death: { s: 3, e: 3, how: "Died of long illness" }, bookDeath: { b: 3, ch: 46, how: "Died abed, given to the river" } },
  "Brynden Tully": { house: "tully", born: "Riverrun", siblings: ["Hoster Tully"],
    blurb: "The Blackfish: Hoster's brother, the finest soldier House Tully ever produced, who quarreled with his lord over an unwanted marriage and never took a wife at all." },
  "Edmure Tully": { house: "tully", born: "Riverrun", father: "Hoster Tully", siblings: ["Catelyn Stark", "Lysa Arryn"],
    blurb: "Hoster's son and heir, brave and warm-hearted and forever a little out of his depth, beloved by the smallfolk of the Riverlands he means to protect." },

  // ================= House Arryn =================
  "Jon Arryn": { house: "arryn", born: "The Eyrie", spouse: "Lysa Arryn", children: ["Robin Arryn"],
    blurb: "The old Lord of the Eyrie and Hand of the King, who fostered Ned Stark and Robert Baratheon as boys and held the realm together for seventeen years. His sudden death opens the tale.",
    death: { s: 1, e: 1, how: "A sudden fever" }, bookDeath: { b: 1, ch: 1, how: "A sudden fever" } },
  "Lysa Arryn": { house: "arryn", born: "Riverrun", father: "Hoster Tully", spouse: "Petyr Baelish", siblings: ["Catelyn Stark", "Edmure Tully"], children: ["Robin Arryn"],
    blurb: "Catelyn's sister, widow of Jon Arryn, shut up in the impregnable Eyrie with her sickly son — nervous, possessive, and not entirely in her right mind.",
    death: { s: 4, e: 7, how: "Fell from the Eyrie" }, bookDeath: { b: 3, ch: 81, how: "Out the Moon Door" } },
  "Robin Arryn": { house: "arryn", born: "The Eyrie", father: "Jon Arryn", mother: "Lysa Arryn",
    blurb: "The little Lord of the Vale, a sickly, coddled boy still at his mother's breast, fond of watching bad men fly out the Moon Door." },
  "Petyr Baelish": { house: null, born: "The Fingers", spouse: "Lysa Arryn",
    blurb: "Littlefinger: a lord of small birth and enormous ambition who rose from nothing to Master of Coin, financing the crown and his own schemes in equal measure. He knew Catelyn Tully as a boy and never forgot her.",
    death: { s: 7, e: 7, how: "Judged and executed at Winterfell (alive in the books)" } },

  // ================= House Greyjoy =================
  "Balon Greyjoy": { house: "greyjoy", born: "Pyke", siblings: ["Euron Greyjoy", "Victarion Greyjoy", "Aeron Greyjoy"], children: ["Yara Greyjoy", "Theon Greyjoy"],
    blurb: "Lord Reaper of Pyke, twice a would-be king, whose failed rebellion nine years past cost him his sons — all but the youngest, given to the Starks as a hostage.",
    death: { s: 6, e: 2, how: "Fell from a bridge" }, bookDeath: { b: 4, ch: 2, how: "Fell from a storm-swept bridge" } },
  "Euron Greyjoy": { house: "greyjoy", born: "Pyke", siblings: ["Balon Greyjoy", "Victarion Greyjoy", "Aeron Greyjoy"],
    blurb: "The Crow's Eye: Balon's exiled brother, a swaggering, black-humored pirate king feared even by his own kin — the show's grinning terror of the seas.",
    bookBlurb: "The Crow's Eye: Balon's exiled brother, blue-lipped from shade-of-the-evening, who claims to have sailed to Valyria itself. A sorcerer-pirate with a dragon-binding horn and crew of mutes, dreaming of far darker crowns than driftwood.",
    death: { s: 8, e: 5, how: "Fell on the beach at King's Landing" } },
  "Victarion Greyjoy": { only: "book", house: "greyjoy", born: "Pyke", siblings: ["Balon Greyjoy", "Euron Greyjoy", "Aeron Greyjoy"],
    blurb: "Balon's brother, Lord Captain of the Iron Fleet: a huge, pious, unimaginative warrior who lives to obey the will of his king and the Drowned God (book only)." },
  "Aeron Greyjoy": { house: "greyjoy", born: "Pyke", siblings: ["Balon Greyjoy", "Euron Greyjoy", "Victarion Greyjoy"],
    blurb: "The Damphair: Balon's youngest brother, once a drunkard, now the sternest priest of the Drowned God on the Iron Islands (book only)." },
  "Yara Greyjoy": { only: "show", house: "greyjoy", born: "Pyke", father: "Balon Greyjoy", siblings: ["Theon Greyjoy"],
    blurb: "Balon's daughter (Asha in the books), a hard-handed reaver and ship's captain who commands ironborn as easily as her father ever did — and everything her brother wishes he could be." },
  "Asha Greyjoy": { only: "book", house: "greyjoy", born: "Pyke", father: "Balon Greyjoy", siblings: ["Theon Greyjoy"],
    blurb: "Balon's daughter and true heir in all but law: a ship's captain with an axe in her belt and a crew that would follow her into the Drowned God's halls. The show renamed her Yara." },
  "Theon Greyjoy": { house: "greyjoy", born: "Pyke", father: "Balon Greyjoy", siblings: ["Yara Greyjoy"],
    blurb: "Balon's last son, raised as Ned Stark's ward and Robb's sworn friend — a cocky, charming young man caught between the family that fathered him and the one that raised him.",
    death: { s: 8, e: 3, how: "Fell defending Bran at Winterfell" } },

  // ================= House Frey =================
  "Walder Frey": { house: "frey", born: "The Twins", children: ["Merrett Frey"],
    blurb: "The Late Lord Frey: near ninety, spiteful, and lord of the only bridge across the Green Fork — with a brood of children and grandchildren beyond counting, and a long memory for slights.",
    death: { s: 6, e: 10, how: "His throat cut at his own table (alive in the books)" } },
  "Merrett Frey": { only: "book", house: "frey", born: "The Twins", father: "Walder Frey",
    blurb: "One of Lord Walder's many undistinguished sons, a soft, unlucky man who never won the spurs or the respect he wanted (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 3, ch: 82, how: "Hanged by the brotherhood" } },

  // ================= House Tyrell =================
  "Olenna Tyrell": { house: "tyrell", born: "The Arbor", children: ["Mace Tyrell"],
    blurb: "The Queen of Thorns: Mace's mother, matriarch of Highgarden, and the sharpest tongue in the Reach — a tiny old woman who runs her house and fears no one at court.",
    death: { s: 7, e: 3, how: "Took poison on her own terms" } },
  "Mace Tyrell": { house: "tyrell", born: "Highgarden", mother: "Olenna Tyrell", children: ["Margaery Tyrell", "Loras Tyrell"],
    blurb: "Lord of Highgarden and Warden of the South, a genial, self-important man who commands the realm's richest lands and does mostly what his mother tells him.",
    death: { s: 6, e: 10, how: "Died when the sept burned" } },
  "Margaery Tyrell": { house: "tyrell", born: "Highgarden", father: "Mace Tyrell", siblings: ["Loras Tyrell"],
    blurb: "Mace's daughter, clever and gracious and quietly ambitious, who understands the winning of a crowd — and a king — better than anyone at court.",
    death: { s: 6, e: 10, how: "Died when the sept burned" } },
  "Loras Tyrell": { house: "tyrell", born: "Highgarden", father: "Mace Tyrell", siblings: ["Margaery Tyrell"],
    blurb: "The Knight of Flowers: Mace's son, the most dazzling young jouster in the Seven Kingdoms, devoted to Renly Baratheon.",
    death: { s: 6, e: 10, how: "Died when the sept burned" } },
  "Willas Tyrell": { only: "book", house: "tyrell", born: "Highgarden", father: "Mace Tyrell", siblings: ["Garlan Tyrell", "Loras Tyrell", "Margaery Tyrell"],
    blurb: "Mace's eldest son and heir to Highgarden, lamed in his first tourney: a gentle, bookish breeder of hawks and horses, wiser than most of his house (book only)." },
  "Garlan Tyrell": { only: "book", house: "tyrell", born: "Highgarden", father: "Mace Tyrell", siblings: ["Willas Tyrell", "Loras Tyrell", "Margaery Tyrell"],
    blurb: "Garlan the Gallant, Mace's second son: a better sword than his famous brother, by his own family's telling, and far too modest to say so (book only)." },

  // ================= House Martell =================
  "Doran Martell": { house: "martell", born: "Sunspear", siblings: ["Oberyn Martell"], children: ["Arianne Martell", "Quentyn Martell", "Trystane Martell"],
    blurb: "The ruling Prince of Dorne: gout-ridden, slow, and endlessly patient, keeping his own counsel in his water gardens while everyone underestimates him.",
    death: { s: 6, e: 1, how: "Slain at Sunspear" } },
  "Oberyn Martell": { house: "martell", born: "Sunspear", siblings: ["Doran Martell"],
    blurb: "The Red Viper: Doran's hot-blooded younger brother — poisoner, duelist, scholar and lover — who has never forgiven the Lannisters for the murder of his sister Elia.",
    death: { s: 4, e: 8, how: "Killed in single combat" }, bookDeath: { b: 3, ch: 71, how: "Killed in trial by combat" } },
  "Ellaria Sand": { house: "martell", born: "Hellholt", spouse: "Oberyn Martell",
    blurb: "Oberyn's paramour, a bastard of House Uller and mother to several of his Sand Snakes — in the show, as ready for vengeance as any of them.",
    bookBlurb: "Oberyn's paramour, a bastard of House Uller and mother to four of his Sand Snakes — who, in the books, is the one voice begging Dorne AGAINST the war of vengeance: she has seen where it ends." },
  "Arianne Martell": { only: "book", house: "martell", born: "Sunspear", father: "Doran Martell", siblings: ["Quentyn Martell", "Trystane Martell"],
    blurb: "Doran's eldest child and heir to Dorne, bold and sensual and impatient with her father's stillness — a princess who means to be reckoned with (book only)." },
  "Quentyn Martell": { only: "book", house: "martell", born: "Sunspear", father: "Doran Martell", siblings: ["Arianne Martell", "Trystane Martell"],
    blurb: "Doran's quiet, dutiful elder son, unremarkable to look at, carrying a secret his father has kept for half a lifetime (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 5, ch: 70, how: "Burned reaching for a dragon" } },
  "Trystane Martell": { house: "martell", born: "Sunspear", father: "Doran Martell", siblings: ["Arianne Martell", "Quentyn Martell"],
    blurb: "Doran's gentle youngest son, betrothed to Princess Myrcella.",
    death: { s: 6, e: 1, how: "Slain aboard ship (alive in the books)" } },
  "Areo Hotah": { house: "martell", born: "Norvos",
    blurb: "Captain of Prince Doran's guard, a Norvoshi bought as a boy and bound by his longaxe and an oath to serve, protect, and obey. He watches, and misses nothing.",
    death: { s: 6, e: 1, how: "Fell at Sunspear (show); watches on in the books" } },
  "Arys Oakheart": { only: "book", house: null, born: "Old Oak",
    blurb: "A knight of the Kingsguard sent south with Princess Myrcella, an honest man out of his depth in the Dornish court (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 4, ch: 22, how: "Cut down in Dorne" } },

  // ================= The Night's Watch =================
  "Jeor Mormont": { house: null, born: "Bear Island", children: ["Jorah Mormont"],
    blurb: "The Old Bear: Lord Commander of the Night's Watch, who set aside Bear Island and his lordship for the black cloak. Gruff, shrewd, and fiercely devoted to his brothers.",
    death: { s: 3, e: 4, how: "Slain at Craster's Keep" }, bookDeath: { b: 3, ch: 34, how: "The mutiny at Craster's Keep" } },
  "Maester Aemon": { house: "targaryen", born: "King's Landing",
    blurb: "The blind old maester of Castle Black, a hundred years in service on the Wall — and, though few now remember it, a son of a Targaryen king who once stood near the throne.",
    death: { s: 5, e: 7, how: "Died of great age" }, bookDeath: { b: 4, ch: 36, how: "Died at sea" } },
  "Alliser Thorne": { house: null, born: "The Crownlands",
    blurb: "Master-at-arms at Castle Black, a bitter, hard-handed old knight who fought for the losing side in the rebellion and has hated soft southron boys ever since.",
    death: { s: 6, e: 3, how: "Hanged at Castle Black" } },
  "Yoren": { house: null, born: "The Riverlands",
    blurb: "A crook-backed wandering crow of the Night's Watch, gruff and foul-mouthed, who ranges the realm gathering recruits for the Wall from its dungeons and gutters.",
    death: { s: 2, e: 3, how: "Killed on the kingsroad" }, bookDeath: { b: 2, ch: 15, how: "Died defending his recruits" } },
  "Grenn": { house: null, born: "The Reach",
    blurb: "A big, slow-witted, good-hearted farmer's son turned brother of the Night's Watch, one of Jon Snow's first friends at the Wall.",
    death: { s: 4, e: 9, how: "Fell holding the gate" } },
  "Pyp": { house: null, born: "The Stormlands",
    blurb: "A quick-tongued former mummer's boy of the Night's Watch, with big ears and a talent for mimicry, sworn to the Wall alongside Jon and Grenn.",
    death: { s: 4, e: 9, how: "Fell in the battle for the Wall" } },
  "Edd Tollett": { house: null, born: "The Vale",
    blurb: "Dolorous Edd: a steward of the Night's Watch with a gift for grim humor and expecting the worst of everything, usually correctly.",
    death: { s: 8, e: 3, how: "Fell in the Long Night" } },
  "Janos Slynt": { house: null, born: "King's Landing",
    blurb: "A butcher's son risen to command of the City Watch of King's Landing, greedy and self-serving, who knows exactly which way to bend.",
    death: { s: 5, e: 3, how: "Beheaded at the Wall" }, bookDeath: { b: 5, ch: 8, how: "Beheaded for refusing an order" } },
  "Qhorin Halfhand": { house: null, born: "The North",
    blurb: "The most respected ranger of the Shadow Tower, a hard and honorable veteran of the lands beyond the Wall who understands the cost of what the Watch does.",
    death: { s: 2, e: 10, how: "Fell beyond the Wall" }, bookDeath: { b: 2, ch: 69, how: "Died beyond the Wall" } },
  "Will of the Night's Watch": { house: null, born: "The Riverlands",
    blurb: "A poacher pardoned into the black, ranging beyond the Wall in the tale's first pages, who sees something in the haunted forest no living man has seen in an age.",
    death: { s: 1, e: 1, how: "Killed beyond the Wall" }, bookDeath: { b: 1, ch: 1, how: "Killed in the haunted forest" } },
  "Ser Waymar Royce": { house: null, born: "Runestone",
    blurb: "A young lordling of the Vale, newly of the Night's Watch and proud of his sable cloak, leading his first ranging beyond the Wall.",
    death: { s: 1, e: 1, how: "Killed beyond the Wall" }, bookDeath: { b: 1, ch: 1, how: "Killed in the haunted forest" } },
  "Gared": { house: null, born: "The North",
    blurb: "A grizzled ranger of forty years' service on the Wall, one of the last men to survive a ranging into the haunted forest.",
    death: { s: 1, e: 1, how: "Beheaded as a deserter" }, bookDeath: { b: 1, ch: 2, how: "Executed at Winterfell" } },
  "Chett": { only: "book", house: null, born: "The Riverlands",
    blurb: "A sullen former leech-tender turned steward of the Night's Watch, nursing grievances against everyone above him (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 3, ch: 1, how: "Killed on the Fist of the First Men" } },

  // ================= The Free Folk =================
  "Mance Rayder": { house: null, born: "Beyond the Wall",
    blurb: "The King-Beyond-the-Wall: once a crow of the Night's Watch, now the man who has done the impossible and united a hundred quarreling wildling peoples under one banner.",
    death: { s: 5, e: 1, how: "Burned before the Wall" }, bookDeath: { b: 5, ch: 11, how: "Burned before the Wall — or so it seemed" } },
  "Ygritte": { house: null, born: "Beyond the Wall",
    blurb: "A free folk spearwife, red-haired and sharp-tongued (kissed by fire, and lucky for it), quick to tell any crow how little he knows.",
    death: { s: 4, e: 9, how: "Fell in the battle for the Wall" }, bookDeath: { b: 3, ch: 56, how: "An arrow beneath the Wall" } },
  "Tormund Giantsbane": { house: null, born: "Beyond the Wall",
    blurb: "A boisterous, boastful free folk war-chief and one of Mance's chief captains, full of tall tales about giants and bears and his own legendary appetites." },
  "Osha": { house: null, born: "Beyond the Wall",
    blurb: "A wildling spearwife taken captive in the wolfswood, shrewd and watchful, who knows more about what stirs beyond the Wall than the southron lords will hear.",
    death: { s: 6, e: 4, how: "Slain at Winterfell" } },
  "Karsi": { only: "show", house: null, born: "Beyond the Wall",
    blurb: "A free folk chieftain and mother of two, respected among the wildlings gathered at Hardhome.",
    death: { s: 5, e: 8, how: "Fell at Hardhome" } },
  "Craster": { house: null, born: "Beyond the Wall",
    blurb: "A savage wildling who lives alone beyond the Wall in a squalid keep, wedding his own daughters and keeping a grudging, uneasy welcome for the Watch.",
    death: { s: 3, e: 4, how: "Slain at his own keep" }, bookDeath: { b: 3, ch: 34, how: "Killed at his own table" } },
  "Gilly": { house: null, born: "Beyond the Wall", father: "Craster",
    blurb: "One of Craster's daughter-wives, a frightened, gentle girl desperate to escape her father's keep before her child is born." },
  "Styr": { house: null, born: "Beyond the Wall",
    blurb: "The Magnar of Thenn, lord of the most disciplined and fearsome of the free folk, who leads a raiding party over the Wall.",
    death: { s: 4, e: 9, how: "Fell at Castle Black" }, bookDeath: { b: 3, ch: 55, how: "Fell in the assault on Castle Black" } },
  "Val": { only: "book", house: null, born: "Beyond the Wall",
    blurb: "A wildling princess of striking beauty, sister to Mance Rayder's late queen, proud and free and unbroken by captivity (book only)." },
  "Wun Wun": { house: null, born: "Beyond the Wall",
    blurb: "Wun Weg Wun Dar Wun, one of the last giants, who comes south with the free folk — a mountain of muscle that speaks the Old Tongue and little else.",
    death: { s: 8, e: 3, how: "Fell at Winterfell" } },

  // ================= The Kingsguard =================
  "Barristan Selmy": { house: null, born: "Harvest Hall",
    blurb: "Ser Barristan the Bold: Lord Commander of the Kingsguard, the greatest living knight of the Seven Kingdoms, who has guarded kings since he was a boy.",
    bookBlurb: "Ser Barristan the Bold: the greatest living knight of Westeros, who crossed the world under a false name to serve the last Targaryen — and in the books stands as her Hand, alive and commanding Meereen.",
    death: { s: 5, e: 4, how: "Fell in Meereen (alive in the books)" } },
  "Meryn Trant": { house: null, born: "The Crownlands",
    blurb: "A knight of the Kingsguard, a joyless brute happy to do the ugly work a cruel king requires and call it duty.",
    death: { s: 5, e: 10, how: "Killed in Braavos" } },
  "Ilyn Payne": { house: null, born: "The Westerlands",
    blurb: "The King's Justice, the royal headsman — a gaunt, silent man whose tongue was torn out by order of the Mad King, so he can never speak of what he does." },

  // ================= The Brotherhood Without Banners =================
  "Beric Dondarrion": { house: null, born: "Blackhaven",
    blurb: "A lord of the Marches sent to bring the king's justice to the Riverlands, who became instead the outlaw leader of the smallfolk's own brotherhood.",
    death: { s: 8, e: 3, how: "Fell in the Long Night" }, bookDeath: { b: 3, ch: 82, how: "Gave his last life at the Trident" } },
  "Thoros of Myr": { house: null, born: "Myr",
    blurb: "A fat, hard-drinking red priest of R'hllor with a fondness for flaming swords, riding with the brotherhood in the war-torn Riverlands.",
    death: { s: 7, e: 6, how: "Died beyond the Wall" } },

  // ================= The court & the road =================
  "Varys": { house: null, born: "Lys",
    blurb: "The Spider: the realm's Master of Whisperers, a soft, bald, perfumed eunuch whose little birds carry him every secret in the Seven Kingdoms. He serves, he says, the realm.",
    death: { s: 8, e: 5, how: "Executed at Dragonstone" } },
  "Grand Maester Pycelle": { house: null, born: "The Westerlands",
    blurb: "The ancient Grand Maester of the Red Keep, who has advised king after king with much bowing and throat-clearing and rather more cunning than he lets show.",
    death: { s: 6, e: 10, how: "Died in the Red Keep" }, bookDeath: { b: 5, ch: 73, how: "Killed by the little birds" } },
  "Qyburn": { house: null, born: "The Reach",
    blurb: "A disgraced former maester stripped of his chain for experiments best not described, now a useful and unsettling servant to those who ask no questions.",
    death: { s: 8, e: 5, how: "Died in the Red Keep" } },
  "Bronn": { house: null, born: "The Riverlands",
    blurb: "A sellsword of quick wit and quicker blade, loyal for exactly as long as the coin holds out — and surprisingly good company besides." },
  "Shae": { house: null, born: "The Free Cities",
    blurb: "A camp follower, clever and sharp-tongued, who becomes something more to a Lannister who ought to know better.",
    death: { s: 4, e: 10, how: "Died in the Tower of the Hand" }, bookDeath: { b: 3, ch: 78, how: "Died in the Hand's chambers" } },
  "Ros": { only: "show", house: null, born: "The North",
    blurb: "A shrewd, ambitious redheaded woman from near Winterfell who works her way from a northern brothel into the trade and intrigues of King's Landing.",
    death: { s: 3, e: 6, how: "Killed in the Red Keep" } },
  "Syrio Forel": { house: null, born: "Braavos",
    blurb: "The First Sword of Braavos, a small, balding, watchful man hired to teach a Stark girl the Braavosi water dance — one blade, one eye, and the god of death to answer.",
    death: { s: 1, e: 5, how: "Last seen holding a door" }, bookDeath: { b: 1, ch: 51, how: "Last seen facing five knights" } },
  "Septa Mordane": { house: null, born: "The south",
    blurb: "The septa who schooled the Stark girls in needlework and courtesy, patient with Sansa and forever exasperated by Arya.",
    death: { s: 1, e: 9, how: "Killed in the purge of the Stark household" }, bookDeath: { b: 1, ch: 68, how: "Killed in the fall of House Stark" } },
  "Mycah, the butcher's boy": { house: null, born: "King's Landing",
    blurb: "A butcher's boy travelling with the king's party, who befriends a Stark girl and plays at swords with her by the river.",
    death: { s: 1, e: 2, how: "Ridden down on the kingsroad" }, bookDeath: { b: 1, ch: 17, how: "Killed on the kingsroad" } },
  "Jory Cassel": { house: null, born: "Winterfell",
    blurb: "Captain of the Stark household guard and nephew to old Ser Rodrik, a steady, loyal swordsman who follows his lord south.",
    death: { s: 1, e: 5, how: "Killed in King's Landing" }, bookDeath: { b: 1, ch: 36, how: "Killed in the street" } },
  "Rodrik Cassel": { house: null, born: "Winterfell",
    blurb: "Winterfell's master-at-arms, a stout old knight with famous white whiskers who trained every Stark child to hold a sword.",
    death: { s: 2, e: 6, how: "Executed at Winterfell" }, bookDeath: { b: 2, ch: 67, how: "Killed in the sack of Winterfell" } },
  "Maester Luwin": { house: null, born: "Oldtown",
    blurb: "The maester of Winterfell, healer, teacher, and counselor to House Stark, who has served the family faithfully for a lifetime.",
    death: { s: 2, e: 10, how: "Killed in the sack of Winterfell" }, bookDeath: { b: 2, ch: 70, how: "Died beneath the heart tree" } },
  "Hodor": { house: null, born: "Winterfell",
    blurb: "A simple, gentle giant of a stableboy in service to House Stark, immensely strong and immensely kind, who can say only one word: 'Hodor.'",
    death: { s: 6, e: 5, how: "Held a door" } },
  "Jojen Reed": { house: null, born: "Greywater Watch", siblings: ["Meera Reed"],
    blurb: "A solemn young crannogman of House Reed, gifted (and burdened) with green dreams that show him things yet to come.",
    death: { s: 4, e: 10, how: "Fell beyond the Wall" } },
  "Meera Reed": { house: null, born: "Greywater Watch", siblings: ["Jojen Reed"],
    blurb: "Jojen's elder sister, a fierce and capable young crannogwoman handy with net and frog-spear, sworn to see her brother's visions through." },
  "Talisa Stark": { only: "show", house: "stark", born: "Volantis", spouse: "Robb Stark",
    blurb: "A healer from far-off Volantis who tends the wounded of both sides on the war's battlefields, and catches the eye of a young king (the show's lady of Robb's heart).",
    death: { s: 3, e: 9, how: "Slain at the Red Wedding" } },
  "Rickard Karstark": { house: null, born: "Karhold", children: ["Torrhen Karstark"],
    blurb: "Lord of Karhold, a proud, grim northern bannerman of distant Stark blood, who marches his sons to war under the direwolf banner.",
    death: { s: 3, e: 5, how: "Beheaded for murder" }, bookDeath: { b: 3, ch: 21, how: "Executed by the King in the North" } },
  "Torrhen Karstark": { house: null, born: "Karhold", father: "Rickard Karstark",
    blurb: "A son of Lord Karstark, a young northern warrior riding in Robb Stark's host.",
    death: { s: 1, e: 10, how: "Fell in the Whispering Wood" }, bookDeath: { b: 1, ch: 64, how: "Fell in the Whispering Wood" } },

  // ================= House Bolton =================
  "Roose Bolton": { house: null, born: "The Dreadfort", children: ["Ramsay Bolton"],
    blurb: "Lord of the Dreadfort, the most powerful of the Stark bannermen: soft-spoken, bloodless, and unreadable, a leech-loving lord whose stillness unsettles everyone around him." ,
    death: { s: 6, e: 2, how: "Slain at Winterfell" } },
  "Ramsay Bolton": { house: null, born: "The Dreadfort", father: "Roose Bolton",
    blurb: "Roose's baseborn son, a grinning, sadistic young hunter with a pack of hounds and a taste for cruelty that even his cold father finds difficult to leash.",
    death: { s: 6, e: 9, how: "Killed at Winterfell" } },

  // ================= House Seaworth =================
  "Davos Seaworth": { house: null, born: "Flea Bottom, King's Landing", children: ["Matthos Seaworth"],
    blurb: "The Onion Knight: a former smuggler raised to knighthood for feeding a starving Storm's End, now the most honest man in Stannis Baratheon's service — and the least comfortable at court. He shortened his own fingers to pay for his crimes." },
  "Matthos Seaworth": { house: null, born: "Cape Wrath", father: "Davos Seaworth",
    blurb: "Davos's eldest son, devout in the red god's new faith and proud to serve aboard his father's ship in Stannis's fleet.",
    death: { s: 2, e: 9, how: "Fell on the Blackwater" }, bookDeath: { b: 2, ch: 58, how: "Lost on the Blackwater" } },

  // ================= House Mormont =================
  "Jorah Mormont": { house: null, born: "Bear Island",
    blurb: "An exiled knight of Bear Island, the disgraced son of the Old Bear, serving as sword and counsel to a young Targaryen princess across the sea — and falling under her spell.",
    death: { s: 8, e: 3, how: "Fell defending his queen" } },
  "Lyanna Mormont": { house: null, born: "Bear Island",
    blurb: "The child Lady of Bear Island, all of ten years old and fiercer than lords five times her age, who suffers no condescension whatsoever.",
    death: { s: 8, e: 3, how: "Fell in the Long Night" } },

  // ================= House Tarly =================
  "Samwell Tarly": { house: null, born: "Horn Hill",
    blurb: "The plump, bookish, self-described craven eldest son of a hard father, packed off to the Night's Watch — where his wits and his reading prove worth more than any sword arm." },

  // ================= House Clegane =================
  "Sandor Clegane": { house: null, born: "Clegane's Keep", siblings: ["Gregor Clegane"],
    blurb: "The Hound: a huge, scarred, foul-tempered warrior sworn to the royal household, who despises knights and their vows — his brother burned the belief out of him young.",
    death: { s: 8, e: 5, how: "Fell with his brother at King's Landing" } },
  "Gregor Clegane": { house: null, born: "Clegane's Keep", siblings: ["Sandor Clegane"],
    blurb: "The Mountain That Rides: Sandor's monstrous elder brother, near eight feet of murderous rage, Tywin Lannister's favorite instrument of terror.",
    death: { s: 8, e: 5, how: "Ended with his brother in the ruin of the Red Keep" } },

  // ================= Beyond the great houses (misc) =================
  "Brienne of Tarth": { house: null, born: "Evenfall Hall",
    blurb: "The Maid of Tarth: a huge, plain, earnest young noblewoman who wants only to be a knight, mocked by men she could best with either hand, and truer than any of them." },
  "Melisandre": { house: null, born: "Asshai",
    blurb: "A red priestess of R'hllor from far-off Asshai, beautiful and unsettling, who reads the future in her fires and has attached her prophecies to Stannis Baratheon.",
    death: { s: 8, e: 3, how: "Ended after the Long Night" } },
  "Missandei": { house: null, born: "Naath",
    blurb: "A young scribe and translator of the peaceable island of Naath, fluent in the tongues of the world, freed from slavery in Astapor.",
    death: { s: 8, e: 4, how: "Executed at King's Landing" } },
  "Daario Naharis": { house: null, born: "Tyrosh",
    blurb: "A flamboyant sellsword captain of the Second Sons, all swagger and blue-dyed beard, who offers his blade — and rather more — to the dragon queen." },
  "Jaqen H'ghar": { house: null, born: "Lorath",
    blurb: "A mysterious, red-and-white-haired prisoner with courtly manners and unsettling eyes, who speaks of himself as 'a man' and pays his debts in the coin of death." },
  "The Waif": { house: null, born: "Braavos",
    blurb: "A pale, ageless acolyte of the House of Black and White, who trains new servants of the Many-Faced God in the arts of the faceless — patiently, mercilessly.",
    death: { s: 6, e: 8, how: "Her face joined the hall" } },
  "The Kindly Man": { only: "book", house: null, born: "Braavos",
    blurb: "The gentle-seeming senior priest of the House of Black and White in Braavos, who tests each novice with a single endless question: who are you? (book only)." },
  "Mirri Maz Duur": { house: null, born: "Lhazar",
    blurb: "A godswife and healer of the Lamb Men, learned in medicine and darker arts, taken as a slave when the Dothraki burned her temple town.",
    death: { s: 1, e: 10, how: "Bound to a funeral pyre" }, bookDeath: { b: 1, ch: 73, how: "Given to the flames" } },
  "Doreah": { house: null, born: "Lys",
    blurb: "A Lysene bed-slave in Daenerys's service, schooled in the arts of the pleasure houses, who teaches her frightened young mistress a kind of power.",
    death: { s: 2, e: 10, how: "Lost in Qarth" }, bookDeath: { b: 2, ch: 13, how: "Died in the red waste" } },
  "Irri": { house: null, born: "The Dothraki Sea",
    blurb: "A Dothraki handmaid to Daenerys, patient and loyal, teaching her khaleesi the ways and the tongue of the horse people.",
    death: { s: 2, e: 5, how: "Killed in Qarth (alive in the books)" } },
  "Hizdahr zo Loraq": { house: null, born: "Meereen",
    blurb: "A smooth-tongued noble of old Meereenese blood, spokesman for the great families under the dragon queen's new order, forever counseling accommodation.",
    death: { s: 5, e: 9, how: "Killed at the fighting pits (imprisoned in the books)" } },
  "Grey Worm": { house: null, born: "The Summer Isles, taken young",
    blurb: "Commander of the Unsullied, the elite eunuch soldiers of Astapor: disciplined past fear or feeling, slowly learning to be a man as well as a weapon." },
  "Xaro Xhoan Daxos": { house: null, born: "Qarth",
    blurb: "One of the Thirteen, the merchant princes of Qarth: a fabulously wealthy trader who welcomes the dragon queen with open arms and a closed fist.",
    death: { s: 2, e: 10, how: "Sealed in his own vault (alive in the books)" } },
  "Illyrio Mopatis": { house: null, born: "Pentos",
    blurb: "A hugely fat, hugely rich magister of Pentos, host and patron to the exiled Targaryens, whose lavish generosity always seems to serve some deeper design." },
  "Kraznys mo Nakloz": { house: null, born: "Astapor",
    blurb: "A Good Master of Astapor, a cruel and casually obscene slaver who breeds and sells the Unsullied by the thousand.",
    death: { s: 3, e: 4, how: "Undone by his own sale" }, bookDeath: { b: 3, ch: 27, how: "Undone by the sale of an army" } },
  "Razdal mo Eraz": { house: null, born: "Yunkai",
    blurb: "A haughty envoy of the slave-city of Yunkai, the Yellow City, sent to buy off the dragon queen with gold and threats." },
  "Yezzan zo Qaggaz": { house: null, born: "Yunkai",
    blurb: "One of the wealthiest and most grotesque slavers of Yunkai, collector of curiosities and freaks, who buys captives for his menagerie (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 5, ch: 52, how: "Taken by the pale mare" } },
  "Qotho": { house: null, born: "The Dothraki Sea",
    blurb: "A bloodrider of Khal Drogo, bound to his khal by blood and oath, distrustful of the khaleesi and her foreign ways.",
    death: { s: 1, e: 10, how: "Fell at Drogo's tent" }, bookDeath: { b: 1, ch: 69, how: "Slain at the khal's tent" } },
  "Rakharo": { house: null, born: "The Dothraki Sea",
    blurb: "A young Dothraki warrior of Drogo's khas, loyal to Daenerys, who stays at her side when greater men abandon her.",
    death: { s: 2, e: 2, how: "His head returned in a saddlebag (alive in the books)" } },
  "Aggo": { house: null, born: "The Dothraki Sea",
    blurb: "A Dothraki archer of Daenerys's khas, one of the three young riders who remain sworn to her after the khalasar scatters." },
  "Jhogo": { house: null, born: "The Dothraki Sea",
    blurb: "A Dothraki outrider of Daenerys's khas, given the whip of a ko, one of her most trusted riders." },

  // ================= The Faith =================
  "The High Sparrow": { house: null, born: "Of the smallfolk",
    blurb: "A humble, barefoot holy man who rises from tending the poor to lead the Faith of the Seven, preaching that even the highborn must answer to the gods.",
    death: { s: 6, e: 10, how: "Died in the Great Sept" } },
  "Septa Unella": { house: null, born: "The Faith",
    blurb: "A stern, implacable septa of the Faith Militant, tireless in her duty of penance and confession, ringing her bell and intoning her single word: shame." },
  "The High Septon": { house: null, born: "King's Landing",
    blurb: "The corpulent, well-fed head of the Faith of the Seven in King's Landing, more at home at a feast than in a fast.",
    death: { s: 2, e: 6, how: "Torn apart by the mob" }, bookDeath: { b: 2, ch: 41, how: "Killed in the bread riots" } },

  // ================= Sellswords & the Golden Company =================
  "Mero": { house: null, born: "Braavos",
    blurb: "The Titan's Bastard: a huge, vicious captain of the Second Sons, a boastful drunk who badly underestimates the dragon queen he's hired to fight.",
    death: { s: 3, e: 8, how: "His head answered Daario's ambition" }, bookDeath: { b: 3, ch: 60, how: "Gutted by Strong Belwas" } },
  "Jon Connington": { only: "book", house: null, born: "Griffin's Roost",
    blurb: "The exiled former Hand of the Mad King, who loved Prince Rhaegar and lost everything in the rebellion, now returned with the Golden Company and a boy to put on the throne (book only)." },
  "Aegon Targaryen": { only: "book", house: "targaryen", born: "In hiding",
    blurb: "A silver-haired youth called Young Griff, raised in secret across the narrow sea and presented to the Golden Company as Rhaegar's living son — heir, they say, to the Iron Throne (book only)." },

  // ================= The Children of the Forest & the Others =================
  "The Three-Eyed Raven": { house: null, born: "Long ago",
    blurb: "An ancient greenseer grown into the roots of a great weirwood beyond the Wall, keeper of all the memory of the world, waiting for the one he has been calling in dreams.",
    death: { s: 6, e: 5, how: "Ended beyond the Wall" } },
  "Leaf": { house: null, born: "Beyond the Wall",
    blurb: "One of the Children of the Forest, the small, ancient, golden-eyed first people of Westeros, keepers of secrets older than the First Men.",
    death: { s: 6, e: 5, how: "Fell defending the cave" } },
  "The Night King": { only: "show", house: null, born: "Made by the Children, in the Dawn Age",
    blurb: "The first and greatest of the White Walkers: a figure of living ice and ancient malice who commands the dead and the endless cold pressing down on the world from beyond the Wall.",
    death: { s: 8, e: 3, how: "Shattered in the Long Night" } },

  // ================= Book-only points of view =================
  "Pate, the Citadel novice": { only: "book", house: null, born: "The Reach",
    blurb: "A slow, unhappy novice of the Citadel in Oldtown, in over his head with a Braavosi stranger and a stolen key (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 4, ch: 1, how: "Died in Oldtown" } },
  "Varamyr Sixskins": { only: "book", house: null, born: "Beyond the Wall",
    blurb: "A powerful, wretched wildling warg who wears the skins of six beasts, one of Mance's skinchangers (book only).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 5, ch: 1, how: "Died in the snows south of the Wall" } },

  // ================= The riverlands road =================
  "Hot Pie": { house: null, born: "King's Landing",
    blurb: "A stout baker's boy swept up in the recruits bound for the Wall, happiest with his hands in dough and no interest at all in adventure." },
  "Lommy Greenhands": { house: null, born: "King's Landing",
    blurb: "A dyer's apprentice with green-stained hands, one of the King's Landing orphans on the road north with Yoren's recruits.",
    death: { s: 2, e: 4, how: "Killed on the road" }, bookDeath: { b: 2, ch: 20, how: "Killed on the march" } },

  // ================= additions: Stark household =================
  "Old Nan": { house: null, born: "Winterfell",
    blurb: "The ancient nursemaid and storyteller of Winterfell, so old none recall her true name, who has told the Stark children their frightening tales for generations." },
  "Vayon Poole": { house: null, born: "Winterfell", children: ["Jeyne Poole"],
    blurb: "The steward of Winterfell, who keeps the castle's accounts and household, and travels south in Lord Stark's service.",
    death: { s: 1, e: 9, how: "Killed in the purge of the Stark household" }, bookDeath: { b: 1, ch: 49, how: "Killed with the Stark men in King's Landing" } },
  "Jeyne Poole": { house: null, born: "Winterfell", father: "Vayon Poole",
    blurb: "The steward's daughter and Sansa Stark's closest childhood friend, who travels with the Starks to the capital (book)." },

  // ================= additions: House Lannister =================
  "Joanna Lannister": { house: "lannister", born: "Casterly Rock", spouse: "Tywin Lannister", children: ["Cersei Lannister", "Jaime Lannister", "Tyrion Lannister"],
    blurb: "Tywin's beloved wife and cousin, the one person said to have ruled the great lord himself; she died bringing his youngest son into the world.",
    death: { s: 0, e: 0, how: "Died before the story" } },
  "Genna Lannister": { only: "book", house: "lannister", born: "Casterly Rock", siblings: ["Tywin Lannister", "Kevan Lannister"],
    blurb: "Tywin's sharp-tongued sister, married off to a Frey, and one of the few who ever dared speak plainly to the Lord of Casterly Rock (book)." },

  // ================= additions: House Baratheon =================
  "Edric Storm": { only: "book", house: "baratheon", born: "Storm's End", father: "Robert Baratheon",
    blurb: "King Robert's one acknowledged bastard, a well-born boy raised at Storm's End, black of hair like all his father's blood (book)." },
  "Mya Stone": { only: "book", house: "baratheon", born: "The Vale", father: "Robert Baratheon",
    blurb: "One of King Robert's baseborn daughters, a sure-footed mule-girl who guides travelers up the mountain paths to the Eyrie (book)." },

  // ================= additions: House Targaryen =================
  "Rhaella Targaryen": { house: "targaryen", born: "King's Landing", spouse: "Aerys II Targaryen", children: ["Rhaegar Targaryen", "Viserys Targaryen", "Daenerys Targaryen"],
    blurb: "The last Targaryen queen, sister and wife to the Mad King, who died giving birth to her daughter on storm-lashed Dragonstone.",
    death: { s: 0, e: 0, how: "Died before the story" } },
  "Rhaenys Targaryen": { house: "targaryen", born: "King's Landing", father: "Rhaegar Targaryen", mother: "Elia Martell",
    blurb: "Rhaegar's little daughter by Elia of Dorne, a small girl who loved her cat, lost in the fall of the Targaryen dynasty.",
    death: { s: 0, e: 0, how: "Died in the Sack of King's Landing, before the story" } },
  "Elia Martell": { house: "martell", born: "Sunspear", spouse: "Rhaegar Targaryen", siblings: ["Doran Martell", "Oberyn Martell"], children: ["Rhaenys Targaryen"],
    blurb: "The gentle, sickly Princess of Dorne, sister to Doran and Oberyn, wed to Prince Rhaegar Targaryen — a wrong her brothers have never forgotten.",
    death: { s: 0, e: 0, how: "Died in the Sack of King's Landing, before the story" } },

  // ================= additions: House Tully / the Vale =================
  "Roslin Frey": { house: "frey", born: "The Twins", father: "Walder Frey", spouse: "Edmure Tully",
    blurb: "One of Lord Walder's many daughters, small, pretty, and gentle-natured, given in marriage to Lord Edmure Tully." },
  "Yohn Royce": { house: null, born: "Runestone",
    blurb: "Bronze Yohn, Lord of Runestone, the most powerful of the Vale lords: a big, blunt, honorable old warrior who wears ancient bronze armor graven with runes." },

  // ================= additions: House Frey =================
  "Lothar Frey": { house: "frey", born: "The Twins", father: "Walder Frey",
    blurb: "Lame Lothar, one of Lord Walder's craftier sons, who does much of his father's negotiating and scheming.",
    death: { s: 7, e: 1, how: "Killed at the Twins" } },
  "Black Walder Rivers": { house: "frey", born: "The Twins",
    blurb: "A grim, dangerous Frey grandson, baseborn and ambitious, feared even among his own enormous, quarrelsome family.",
    death: { s: 7, e: 1, how: "Killed at the Twins" } },
  "Olyvar Frey": { house: "frey", born: "The Twins", father: "Walder Frey",
    blurb: "One of Lord Walder's younger sons, who serves for a time as squire to Robb Stark and thinks well of the young wolf." },
  "Stevron Frey": { only: "book", house: "frey", born: "The Twins", father: "Walder Frey",
    blurb: "Lord Walder's eldest son and long-suffering heir, an old man himself, who has waited most of his life to inherit the Twins (book).",
    death: { s: 0, e: 0, how: "(book only)" }, bookDeath: { b: 2, ch: 40, how: "Died of wounds after Oxcross" } },

  // ================= additions: House Bolton =================
  "Walda Bolton": { house: null, born: "The Twins", father: "Walder Frey", spouse: "Roose Bolton",
    blurb: "Fat Walda, a plump and cheerful Frey girl chosen by Roose Bolton for a bride — for her weight in silver, the story goes.",
    death: { s: 6, e: 2, how: "Killed at Winterfell (alive in the books)" } },
  "Domeric Bolton": { only: "book", house: null, born: "The Dreadfort", father: "Roose Bolton",
    blurb: "Roose Bolton's trueborn son and heir, a quiet, gifted youth and fine harpist and horseman, who died young (book).",
    death: { s: 0, e: 0, how: "Died before the story" } },

  // ================= additions: House Tarly =================
  "Randyll Tarly": { house: null, born: "Horn Hill", spouse: "Melessa Tarly", children: ["Samwell Tarly", "Dickon Tarly", "Talla Tarly"],
    blurb: "Lord of Horn Hill and the finest battlefield commander in the Reach — a cold, iron-hard man ashamed of his bookish eldest son.",
    death: { s: 7, e: 5, how: "Fell after the Reach campaign" } },
  "Melessa Tarly": { house: null, born: "Horn Hill", spouse: "Randyll Tarly", children: ["Samwell Tarly", "Dickon Tarly", "Talla Tarly"],
    blurb: "Lady of Horn Hill, a kind and gentle mother who quietly favors her disgraced eldest son against her husband's contempt." },
  "Dickon Tarly": { house: null, born: "Horn Hill", father: "Randyll Tarly", mother: "Melessa Tarly", siblings: ["Samwell Tarly", "Talla Tarly"],
    blurb: "Samwell's younger brother, everything their father wanted in a son: strong, martial, and heir to Horn Hill in Sam's place.",
    death: { s: 7, e: 5, how: "Fell after the Reach campaign" } },
  "Talla Tarly": { house: null, born: "Horn Hill", father: "Randyll Tarly", mother: "Melessa Tarly", siblings: ["Samwell Tarly", "Dickon Tarly"],
    blurb: "Samwell's sister, a girl of Horn Hill under her father's stern rule (book)." },

  // ================= additions: House Mormont =================
  "Maege Mormont": { only: "book", house: null, born: "Bear Island", siblings: ["Jeor Mormont"], children: ["Dacey Mormont"],
    blurb: "The She-Bear, Jeor's sister and Lady of Bear Island, a fierce mace-wielding warrior-widow with a brood of equally fierce daughters (book)." },
  "Dacey Mormont": { only: "book", house: null, born: "Bear Island", mother: "Maege Mormont",
    blurb: "Maege's eldest daughter, a tall, graceful warrior more at home with a mace than a spindle, who rides with the Young Wolf's host.",
    death: { s: 3, e: 9, how: "Slain at the Red Wedding" }, bookDeath: { b: 3, ch: 52, how: "Killed at the Red Wedding" } },

  // ================= additions: House Martell (Sand Snakes) =================
  "Obara Sand": { house: "martell", born: "Dorne", father: "Oberyn Martell",
    blurb: "The eldest of Oberyn's bastard daughters, the Sand Snakes: hard, angry, and deadly with the spear her father put in her hands as a girl.",
    death: { s: 7, e: 2, how: "Slain at sea" } },
  "Nymeria Sand": { house: "martell", born: "Dorne", father: "Oberyn Martell",
    blurb: "Lady Nym, second of the Sand Snakes: elegant, cool, and lethal, favoring the whip and a hidden blade.",
    death: { s: 7, e: 2, how: "Slain at sea" } },
  "Tyene Sand": { house: "martell", born: "Dorne", father: "Oberyn Martell", mother: "Ellaria Sand",
    blurb: "The sweetest-seeming of the Sand Snakes, daughter of Oberyn and Ellaria, who fights with daggers and poisons and a septa's pious smile.",
    death: { s: 7, e: 3, how: "Lost in King's Landing" } },

  // ================= additions: the Night's Watch =================
  "Bowen Marsh": { house: null, born: "The North",
    blurb: "The Lord Steward of the Night's Watch, called the Old Pomegranate, a careful, cautious man who counts the Wall's stores and worries over every one." },
  "Cotter Pyke": { only: "book", house: null, born: "The Iron Islands",
    blurb: "A baseborn ironborn risen to command Eastwatch-by-the-Sea, a rough, fierce, and able captain of the Night's Watch (book)." },
  "Rast": { house: null, born: "King's Landing",
    blurb: "A brutal former rapist sent to the Wall, one of the meaner recruits Jon and Sam train beside at Castle Black.",
    death: { s: 4, e: 5, how: "Killed at Craster's Keep" } },
  "Karl Tanner": { only: "show", house: null, born: "Flea Bottom, King's Landing",
    blurb: "A cutthroat of King's Landing turned black brother, ringleader of the mutineers who seize Craster's Keep.",
    death: { s: 4, e: 5, how: "Killed at Craster's Keep" } },
  "Olly": { only: "show", house: null, born: "A village beyond the Gift",
    blurb: "A farm boy taken in at Castle Black after wildlings destroyed his village, who becomes Jon Snow's young steward.",
    death: { s: 6, e: 3, how: "Hanged at Castle Black" } },

  // ================= additions: the free folk =================
  "Rattleshirt": { house: null, born: "Beyond the Wall",
    blurb: "The Lord of Bones, a boastful wildling raider armored in the clattering bones of dead men and beasts, loud and vicious in equal measure.",
    death: { s: 5, e: 8, how: "Beaten down before the free folk (a different fate in the books)" }, bookDeath: { b: 5, ch: 11, how: "Burned in a king's skin" } },
  "Orell": { house: null, born: "Beyond the Wall",
    blurb: "A wildling skinchanger who wears the skin of an eagle, scouting the lands south of the Wall for Mance's host.",
    death: { s: 3, e: 9, how: "Killed at the Queenscrown; his eagle flew on" }, bookDeath: { b: 2, ch: 68, how: "Slain in the Skirling Pass" } },

  // ================= additions: the Kingsguard =================
  "Mandon Moore": { house: null, born: "The Vale",
    blurb: "A pale, cold-eyed knight of the Kingsguard with no friends and no fear, whose blank stare unsettles even his brothers in white.",
    death: { s: 2, e: 9, how: "Fell on the Blackwater" }, bookDeath: { b: 2, ch: 61, how: "Drowned on the Blackwater" } },
  "Boros Blount": { house: null, born: "The Crownlands",
    blurb: "A choleric, thickset knight of the Kingsguard, more bully than hero, quick to do a cruel king's bidding." },
  "Balon Swann": { house: null, born: "Stonehelm",
    blurb: "A capable and honorable young knight of the Kingsguard from the stormlands, well-regarded by nearly everyone at court." },

  // ================= additions: the Brotherhood =================
  "Lem Lemoncloak": { house: null, born: "The Riverlands",
    blurb: "A big, gruff outlaw of the Brotherhood Without Banners, known for the tattered yellow cloak that gives him his name." },
  "Anguy": { house: null, born: "The Dornish Marches",
    blurb: "A common-born marcher archer of unmatched skill, who won a king's tourney and threw in with the Brotherhood Without Banners." },
  "Harwin": { house: null, born: "Winterfell",
    blurb: "A guardsman of Winterfell, son of Hullen the master of horse, who served House Stark before the war scattered him to the Brotherhood." },

  // ================= additions: the court & the road =================
  "Podrick Payne": { house: null, born: "The Westerlands",
    blurb: "A shy, tongue-tied young squire of distant Lannister blood, quietly braver and more capable than anyone gives him credit for." },
  "Vardis Egen": { house: null, born: "The Vale",
    blurb: "The captain of House Arryn's household guard, a seasoned knight sworn to Lady Lysa and the little lord of the Eyrie.",
    death: { s: 1, e: 6, how: "Fell in a trial by combat" }, bookDeath: { b: 1, ch: 40, how: "Fell in the Eyrie's trial by combat" } },
  "Tobho Mott": { house: null, born: "Qohor",
    blurb: "A master armorer of King's Landing, trained in the mysteries of Qohor, whose shop turns out the finest steel in the city — and takes on the most promising apprentices." },

  // ================= additions: Essos & the sellswords =================
  "Quaithe": { house: null, born: "Asshai",
    blurb: "A masked shadowbinder from far Asshai-by-the-Shadow, who appears to the dragon queen with cryptic warnings and riddling counsel." },
  "Prendahl na Ghezn": { house: null, born: "Ghiscar",
    blurb: "A hard Ghiscari captain of the Second Sons sellsword company, hired to fight against the dragon queen at Yunkai.",
    death: { s: 3, e: 8, how: "His head answered Daario's ambition" }, bookDeath: { b: 3, ch: 42, how: "His head delivered by Daario" } },
  "Harry Strickland": { house: null, born: "The Free Cities",
    blurb: "Homeless Harry, captain-general of the Golden Company, the largest and most storied of the free companies of Essos — cautious where his forebears were bold (book).",
    death: { s: 8, e: 5, how: "Ridden down before the walls of King's Landing" } },
};

/* honorific / variant names used in episode & chapter texts map to the same entries */
(function () {
  const alias = {
    "Lord Eddard Stark": "Eddard Stark",
    "Robb Stark, King in the North": "Robb Stark",
    "Jon Snow, Lord Commander": "Jon Snow",
    "King Robert": "Robert Baratheon",
    "King Robert I Baratheon": "Robert Baratheon",
    "King Joffrey I Baratheon": "Joffrey Baratheon",
    "King Tommen I Baratheon": "Tommen Baratheon",
    "Daenerys Stormborn of House Targaryen": "Daenerys Targaryen",
    "Lord Tywin Lannister": "Tywin Lannister",
    "Ser Kevan Lannister": "Kevan Lannister",
    "Ser Jorah Mormont": "Jorah Mormont",
    "Lord Commander Jeor Mormont": "Jeor Mormont",
    "Ser Barristan Selmy": "Barristan Selmy",
    "Ser Gregor Clegane": "Gregor Clegane",
    "Ser Rodrik Cassel": "Rodrik Cassel",
    "Ser Ilyn Payne": "Ilyn Payne",
    "Ser Meryn Trant": "Meryn Trant",
    "Melisandre of Asshai": "Melisandre",
    "Missandei of Naath": "Missandei",
    "Prince Oberyn Martell": "Oberyn Martell",
    "Prince Doran Martell": "Doran Martell",
    "Prince Trystane Martell": "Trystane Martell",
    "Prince Quentyn Martell": "Quentyn Martell",
    "Lady Olenna Tyrell": "Olenna Tyrell",
    "Queen Margaery Tyrell": "Margaery Tyrell",
    "Lord Euron Greyjoy": "Euron Greyjoy",
    "Princess Shireen Baratheon": "Shireen Baratheon",
    "Queen Selyse Baratheon": "Selyse Baratheon",
    "Queen Talisa Stark": "Talisa Stark",
    "Varys, Master of Whisperers": "Varys",
    "Lord Hoster Tully": "Hoster Tully",
    "Jon Arryn, Hand of the King": "Jon Arryn",
    "Lord Rickard Karstark": "Rickard Karstark",
    "Maester Aemon Targaryen": "Maester Aemon",
    "Yoren of the Night's Watch": "Yoren",
    "Ramsay Snow": "Ramsay Bolton",
    "Petyr \"Littlefinger\" Baelish": "Petyr Baelish",
    "Brynden \"the Blackfish\" Tully": "Brynden Tully",
  };
  Object.keys(alias).forEach((a) => { if (CHARACTERS[alias[a]]) CHARACTERS[a] = CHARACTERS[alias[a]]; });
  /* expose the honorific -> canonical map so the wiki can redirect a formal-name
     URL (e.g. #char=Lord Eddard Stark) to the single full page (#char=Eddard
     Stark) instead of rendering a short duplicate with no article of its own. */
  window.CHARACTER_ALIASES = alias;
})();
