/* THE KNOWN WORLD — world data, keyed to the ASOIAF map image (5652 × 3682 px).
   Every location below is a labeled dot on the map; x/y are image pixels.
   Story scope: Season One of the show only.

   Row format: [name, x, y, type, region, rank, subtitle, description]
     type:  castle | city | town | ruin | landmark
     rank:  1 = always labeled · 2 = labeled when zoomed in · 3 = close zoom only */

const LOCATION_ROWS = [
  // ---------------- The North & the Wall ----------------
  ["Winterfell", 1207, 745, "castle", "the-north", 1, "Seat of House Stark",
    "The ancient stronghold of the Kings of Winter, built over hot springs ten thousand years ago. Its granite walls have never been taken by storm."],
  ["Castle Black", 1424, 258, "castle", "the-north", 1, "Stronghold of the Night's Watch",
    "The chief fortress of the Night's Watch, a grim huddle of keeps at the foot of the Wall with seven hundred feet of ice at its back."],
  ["The Shadow Tower", 1286, 245, "castle", "the-north", 3, "Western castle of the Watch",
    "Westernmost manned castle of the Night's Watch, guarding the mountain end of the Wall."],
  ["Eastwatch-by-the-Sea", 1546, 255, "castle", "the-north", 3, "Eastern castle of the Watch",
    "The Watch's port castle at the eastern end of the Wall, where its few ships put to sea."],
  ["Craster's Keep", 1351, 187, "landmark", "the-north", 3, "A wildling's hall beyond the Wall",
    "The daubed hall of Craster, a free folk man who keeps his daughters as wives and stays on cold terms with harder things."],
  ["White Tree", 1392, 224, "landmark", "the-north", 3, "Wildling village",
    "A tiny free folk village beyond the Wall, named for the great weirwood at its heart."],
  ["Fist of the First Men", 1252, 128, "ruin", "the-north", 3, "Ancient ringfort",
    "A bare hill crowned by a ringwall of the First Men, older than any song."],
  ["Hardhome", 1585, 115, "ruin", "the-north", 3, "Ruined haven of the free folk",
    "The only thing like a town the free folk ever raised, on the sheltered bay of Storrold's Point — emptied six hundred years ago in a night of fire no one can explain, and shunned ever since."],
  ["Bear Island", 930, 415, "castle", "the-north", 3, "Seat of House Mormont",
    "A cold island of woods and fisherfolk in the Bay of Ice, seat of House Mormont — poor in gold, rich in axes, and stubborn beyond all sense."],
  ["Queenscrown", 1338, 310, "ruin", "the-north", 3, "Abandoned holdfast",
    "A deserted tower in a lake in the New Gift, its gilded merlons remembered in its name."],
  ["Last Hearth", 1494, 495, "castle", "the-north", 2, "Seat of House Umber",
    "Home of the Greatjon and his enormous kin, the last hearth before the Gift and the Wall."],
  ["Karhold", 1726, 559, "castle", "the-north", 2, "Seat of House Karstark",
    "Eastern seat of the Karstarks, kin to the Starks of old. Lord Rickard rides south with Robb this season."],
  ["The Dreadfort", 1522, 692, "castle", "the-north", 2, "Seat of House Bolton",
    "Grim seat of the Boltons, whose banner is a flayed man and whose loyalty is a knife held politely."],
  ["Hornwood", 1463, 828, "castle", "the-north", 3, "Seat of House Hornwood",
    "A modest forest seat between the Dreadfort and White Harbor."],
  ["Torrhen's Square", 999, 865, "castle", "the-north", 3, "Seat of House Tallhart",
    "A square towered keep named for the King Who Knelt."],
  ["Castle Cerwyn", 1202, 874, "castle", "the-north", 3, "Seat of House Cerwyn",
    "Half a day's ride from Winterfell, home of the Starks' nearest bannermen."],
  ["Barrowton", 962, 1047, "town", "the-north", 3, "Town of House Dustin",
    "A wooden town raised around the Great Barrow of the First King, ruled by House Dustin."],
  ["Ramsgate", 1602, 995, "castle", "the-north", 3, "Holdfast of the eastern shore",
    "A small seat on the White Knife's eastern shore, sworn to White Harbor."],
  ["Widow's Watch", 1780, 1016, "castle", "the-north", 3, "Seat of House Flint",
    "A lonely watch upon the easternmost point of the North, staring out over the Shivering Sea."],
  ["White Harbor", 1361, 1059, "city", "the-north", 2, "City of House Manderly",
    "The North's only true city, a clean white port at the mouth of the White Knife, held by House Manderly for the Starks."],
  ["Oldcastle", 1406, 1161, "castle", "the-north", 3, "Seat of House Locke",
    "An old grey seat where the Bite gnaws at the shore."],
  ["Moat Cailin", 1228, 1120, "ruin", "the-north", 2, "Ruined guard of the Neck",
    "Three crumbling towers commanding the causeway through the swamps of the Neck — the ancient lock on the door to the North."],
  ["Flint's Finger", 765, 1242, "castle", "the-north", 3, "Seat of House Flint of the Finger",
    "A stony seat on the cape above Blazewater Bay."],

  // ---------------- The Iron Islands ----------------
  ["Pyke", 743, 1630, "castle", "iron-islands", 1, "Seat of House Greyjoy",
    "A castle of black stone strung across sea-stacks and rope bridges, battered by the Sunset Sea."],
  ["Faircastle", 700, 1839, "castle", "the-westerlands", 3, "Seat of House Farman",
    "The seat of House Farman on Fair Isle, whose shores shelter the western coast."],

  // ---------------- The Riverlands ----------------
  ["The Twins", 1143, 1452, "castle", "the-riverlands", 1, "Seat of House Frey",
    "Two matched castles bridging the Green Fork, whose tolls have made cranky old Walder Frey rich and proud."],
  ["Seagard", 1105, 1529, "castle", "the-riverlands", 2, "Seat of House Mallister",
    "A fortified port raised to guard the coast against ironborn raiders, seat of House Mallister."],
  ["Wendish Town", 1110, 1636, "town", "the-riverlands", 3, "River village",
    "A small riverside town in the Mallister lands — the kind of place armies burn on their way somewhere else."],
  ["Raventree Hall", 1089, 1708, "castle", "the-riverlands", 3, "Seat of House Blackwood",
    "Seat of the old-gods-keeping Blackwoods, forever feuding with the Brackens across the river."],
  ["Riverrun", 1088, 1765, "castle", "the-riverlands", 1, "Seat of House Tully",
    "A three-sided castle at the meeting of the Tumblestone and the Red Fork, ancestral seat of House Tully."],
  ["Stone Hedge", 1178, 1753, "castle", "the-riverlands", 3, "Seat of House Bracken",
    "The Brackens' seat on the Red Fork, across an ancient grudge from Raventree Hall."],
  ["High Heart", 1170, 1809, "landmark", "the-riverlands", 3, "Sacred hill of the First Men",
    "A high bald hill ringed by weirwood stumps, holy to the children of the forest — and said to be haunted still."],
  ["Acorn Hall", 1154, 1829, "castle", "the-riverlands", 3, "Seat of House Smallwood",
    "A snug forest keep in the foothills south of the Trident."],
  ["Harrenhal", 1295, 1807, "castle", "the-riverlands", 1, "The burned giant",
    "The greatest castle ever raised — and a ruin since Aegon's dragons melted its towers. Every house that holds it comes to grief."],
  ["Pinkmaiden", 1068, 1867, "castle", "the-riverlands", 3, "Seat of House Piper",
    "The Pipers' seat on the upper Red Fork."],
  ["Stoney Sept", 1142, 1945, "town", "the-riverlands", 2, "Town of the bells",
    "The town where Robert hid before the Battle of the Bells in his rebellion — its ringing saved his life."],

  // ---------------- The Vale ----------------
  ["The Eyrie", 1587, 1593, "castle", "the-vale", 1, "Seat of House Arryn",
    "A castle of white stone atop the Giant's Lance, reached by a goat path and defended by the sky itself."],
  ["The Bloody Gate", 1514, 1627, "landmark", "the-vale", 3, "Gate of the Vale",
    "The narrow pass where the Knight of the Gate asks who would enter the Vale — and armies die asking."],
  ["Runestone", 1836, 1608, "castle", "the-vale", 3, "Seat of House Royce",
    "Ancient seat of the Royces, whose bronze armor is graven with runes older than the Andals."],
  ["Gulltown", 1800, 1642, "city", "the-vale", 2, "Port city of the Vale",
    "The Vale's harbor city, held by House Grafton for the Arryns."],
  ["Wickendon", 1597, 1791, "castle", "the-crownlands", 3, "Seat of House Waxley",
    "A quiet seat on Crackclaw Point, south of the Vale's mountains."],

  // ---------------- The Westerlands ----------------
  ["Casterly Rock", 740, 1956, "castle", "the-westerlands", 1, "Seat of House Lannister",
    "A fortress carved into a golden rock above the Sunset Sea, seat of the wealthiest house in the Seven Kingdoms."],
  ["Lannisport", 732, 1973, "city", "the-westerlands", 2, "City of the Lannisters",
    "A walled port city in the shadow of the Rock, home of the Lannister fleet."],
  ["The Crag", 776, 1778, "castle", "the-westerlands", 3, "Seat of House Westerling",
    "A half-ruined seat above the sea, rich in honor and poor in gold."],
  ["Ashemark", 848, 1825, "castle", "the-westerlands", 3, "Seat of House Marbrand",
    "The Marbrands' seat at the edge of the western hills."],
  ["Golden Tooth", 948, 1858, "castle", "the-westerlands", 2, "Gate of the Westerlands",
    "The small strong castle that locks the hill road between the Riverlands and the West — the Lannister armies march past it this season."],
  ["Hornvale", 1010, 1897, "castle", "the-westerlands", 3, "Seat of House Brax",
    "A valley seat in the eastern hills of the West."],
  ["Clegane's Keep", 740, 2018, "castle", "the-westerlands", 3, "Keep of House Clegane",
    "The modest towerhouse of the Cleganes — kennelmasters raised to knighthood, whose sons grew anything but modest."],
  ["Deep Den", 975, 1999, "castle", "the-westerlands", 3, "Seat of House Lydden",
    "A den-like seat in the hills along the goldroad."],
  ["Silverhill", 934, 2100, "castle", "the-westerlands", 3, "Seat of House Serrett",
    "A silver-veined hill seat of the Serretts."],
  ["Cornfield", 785, 2118, "castle", "the-westerlands", 3, "Seat of House Swyft",
    "The Swyfts' seat amid the southern fields of the West."],
  ["Crakehall", 660, 2186, "castle", "the-westerlands", 3, "Seat of House Crakehall",
    "Seat of the boar-sigiled Crakehalls, big men with big appetites."],
  ["Feastfires", 601, 1973, "castle", "the-westerlands", 3, "Seat of House Prester",
    "A headland seat looking out over the Sunset Sea."],

  // ---------------- The Crownlands ----------------
  ["King's Landing", 1535, 2057, "city", "the-crownlands", 1, "Capital of the Seven Kingdoms",
    "Aegon's city on Blackwater Bay, half a million souls beneath the Red Keep and the Great Sept of Baelor."],
  ["Maidenpool", 1533, 1860, "town", "the-crownlands", 2, "Town of House Mooton",
    "A port town on the Bay of Crabs where Florian first saw Jonquil bathing, if the songs are true."],
  ["Antlers", 1482, 1913, "castle", "the-crownlands", 3, "Seat of House Buckwell",
    "A modest seat in the hills north of King's Landing."],
  ["Rosby", 1513, 1967, "castle", "the-crownlands", 3, "Seat of House Rosby",
    "A small castle astride the road from Duskendale to the capital."],
  ["Dragonstone", 1758, 1932, "castle", "the-crownlands", 1, "Island seat of the old blood",
    "A brooding fortress of black stone shaped like dragons, raised by Valyrian art on a smoking island."],
  ["Claw Isle", 1830, 1816, "castle", "the-crownlands", 3, "Seat of House Celtigar",
    "Island seat of the Celtigars, old Valyrian blood sworn to Dragonstone."],

  // ---------------- The Reach ----------------
  ["Highgarden", 912, 2457, "castle", "the-reach", 1, "Seat of House Tyrell",
    "A castle of white towers and climbing roses above the Mander, heart of the garden of Westeros."],
  ["Old Oak", 705, 2307, "castle", "the-reach", 3, "Seat of House Oakheart",
    "An ancient seat by the sea road north of Highgarden."],
  ["Red Lake", 845, 2294, "castle", "the-reach", 3, "Seat of House Crane",
    "The Cranes' castle on the shore of its namesake lake."],
  ["Goldengrove", 914, 2297, "castle", "the-reach", 3, "Seat of House Rowan",
    "The Rowans' golden-treed seat in the northern Reach."],
  ["Tumbleton", 1305, 2176, "town", "the-reach", 3, "Town on the Mander",
    "A market town on the upper Mander, remembered for an old dance of dragons."],
  ["Bitterbridge", 1142, 2278, "castle", "the-reach", 3, "Seat of House Caswell",
    "Where the roseroad crosses the Mander over an ancient stone bridge."],
  ["Grassy Vale", 1270, 2283, "castle", "the-reach", 3, "Seat of House Meadows",
    "A green seat at the eastern edge of the Reach."],
  ["Long Table", 1108, 2331, "castle", "the-reach", 3, "Seat of House Merryweather",
    "A seat famed for its groaning boards and generous lords."],
  ["Cider Hall", 1035, 2387, "castle", "the-reach", 3, "Seat of House Fossoway",
    "The apple-sigiled Fossoways' seat at the meeting of the Mander and the Cockleswhent."],
  ["Ashford", 1147, 2421, "castle", "the-reach", 3, "Seat of House Ashford",
    "A castle and market town on the Cockleswhent, once host to a famous tourney."],
  ["Brightwater Keep", 740, 2548, "castle", "the-reach", 3, "Seat of House Florent",
    "Seat of the fox-eared Florents, forever insisting Highgarden should be theirs."],
  ["Bandallon", 640, 2551, "castle", "the-reach", 3, "Seat of House Blackbar",
    "A coastal seat overlooking the Redwyne Straits."],
  ["Honeyholt", 749, 2598, "castle", "the-reach", 3, "Seat of House Beesbury",
    "The Beesburys' seat amid orchards and hives on the Honeywine."],
  ["Horn Hill", 957, 2546, "castle", "the-reach", 2, "Seat of House Tarly",
    "The Tarlys' seat beneath the foothills of the Red Mountains — the home Samwell Tarly was made to renounce at spearpoint."],
  ["Oldtown", 720, 2668, "city", "the-reach", 1, "City of the Citadel",
    "The oldest city in Westeros, where the maesters forge their chains at the Citadel beneath the Hightower's beacon."],
  ["Blackcrown", 629, 2713, "castle", "the-reach", 3, "Seat of House Bulwer",
    "A seat at the western tip of the Reach, south of Oldtown."],
  ["Uplands", 830, 2669, "castle", "the-reach", 3, "Seat of House Mullendore",
    "A hillside seat above the Honeywine's valley."],
  ["Three Towers", 662, 2768, "castle", "the-reach", 3, "Seat of House Costayne",
    "Three joined towers on the Whispering Sound's southern arm."],
  ["Sun House", 810, 2861, "castle", "the-reach", 3, "Seat of House Cuy",
    "A sunny coastal seat on the Reach's southern shore."],

  // ---------------- The Stormlands ----------------
  ["Storm's End", 1654, 2358, "castle", "the-stormlands", 1, "Seat of House Baratheon",
    "A drum-towered castle whose walls have never fallen to storm or siege, ancestral seat of House Baratheon."],
  ["Summerhall", 1440, 2383, "ruin", "the-stormlands", 2, "Burned palace of the dragons",
    "The Targaryens' summer palace, destroyed in a night of fire and grief the realm still whispers about."],
  ["Griffin's Roost", 1608, 2411, "castle", "the-stormlands", 3, "Seat of House Connington",
    "A red-stone seat on a headland shaped like a griffin's beak."],
  ["Rain House", 1840, 2447, "castle", "the-stormlands", 3, "Seat of House Wylde",
    "A rain-lashed castle at the wet edge of Cape Wrath."],
  ["Stonehelm", 1515, 2508, "castle", "the-stormlands", 3, "Seat of House Swann",
    "The Swanns' seat above the Slayne in the Red Watch."],
  ["Mistwood", 1672, 2541, "castle", "the-stormlands", 3, "Seat of House Mertyns",
    "A seat deep in the misty rainwood."],
  ["Blackhaven", 1300, 2508, "castle", "the-stormlands", 3, "Seat of House Dondarrion",
    "The Dondarrions' marcher seat, its banner a purple lightning bolt — carried this season by Ser Beric, sent to arrest the Mountain."],
  ["Haystack Hall", 1635, 2259, "castle", "the-stormlands", 3, "Seat of House Errol",
    "A homely seat amid the fields north of Storm's End."],
  ["Felwood", 1472, 2265, "castle", "the-stormlands", 3, "Seat of House Fell",
    "A woodland keep in the kingswood's shadow."],
  ["Bronzegate", 1630, 2301, "castle", "the-stormlands", 3, "Seat of House Buckler",
    "A bronze-gated castle on the road from King's Landing to Storm's End."],
  ["Evenfall Hall", 1811, 2323, "castle", "the-stormlands", 3, "Seat of House Tarth",
    "Seat of the Tarths on the Sapphire Isle, said to be the loveliest island in the narrow sea."],

  // ---------------- Dorne ----------------
  ["Sunspear", 1798, 2863, "castle", "dorne", 1, "Seat of House Martell",
    "The winding-walled seat of House Martell at the edge of the eastern sea, shaded and slow to anger."],
  ["Nightsong", 1115, 2582, "castle", "the-stormlands", 3, "Seat of House Caron",
    "The marcher seat of the Carons, lords of the nightingales."],
  ["Vulture's Roost", 1294, 2572, "ruin", "dorne", 3, "Ruin in the Red Mountains",
    "An abandoned mountain hold where outlaw 'vulture kings' once nested."],
  ["Wyl", 1361, 2586, "castle", "dorne", 3, "Seat of House Wyl",
    "A marcher seat in the Boneway, old in border blood."],
  ["Kingsgrave", 1169, 2643, "castle", "dorne", 3, "Seat of House Manwoody",
    "A mountain seat named for a king slain at its gates."],
  ["Blackmont", 992, 2687, "castle", "dorne", 3, "Seat of House Blackmont",
    "A western Dornish seat above the Torentine."],
  ["Skyreach", 1163, 2718, "castle", "dorne", 3, "Seat of House Fowler",
    "The Fowlers' eyrie in the Prince's Pass."],
  ["Yronwood", 1328, 2719, "castle", "dorne", 2, "Seat of House Yronwood",
    "Seat of the proudest house in Dorne after the Martells — 'The Bloodroyal', wardens of the Boneway."],
  ["Starfall", 964, 2757, "castle", "dorne", 2, "Seat of House Dayne",
    "The Daynes' seat on the Torentine, home of the sword Dawn and the memory of Ser Arthur, the Sword of the Morning."],
  ["Hellholt", 1199, 2852, "castle", "dorne", 3, "Seat of House Uller",
    "A grim seat on the Brimstone, half of whose lords are said to be mad."],
  ["Sandstone", 1072, 2872, "castle", "dorne", 3, "Seat of House Qorgyle",
    "A sand-scoured seat deep in the Dornish desert."],
  ["The Tor", 1535, 2755, "castle", "dorne", 3, "Seat of House Jordayne",
    "A seaside seat on the Sea of Dorne."],
  ["Ghost Hill", 1764, 2744, "castle", "dorne", 3, "Seat of House Toland",
    "A chalk-white hill seat above the Sea of Dorne."],
  ["Godsgrace", 1571, 2840, "castle", "dorne", 3, "Seat of House Allyrion",
    "A fertile seat at the joining of the Greenblood's branches."],
  ["Vaith", 1422, 2869, "castle", "dorne", 3, "Seat of House Vaith",
    "A river seat amid the red sands."],
  ["Lemonwood", 1723, 2899, "castle", "dorne", 3, "Seat of House Dalt",
    "A lemon-orcharded seat near the mouth of the Greenblood."],
  ["Salt Shore", 1535, 2922, "castle", "dorne", 3, "Seat of House Gargalen",
    "A southern coastal seat on the Summer Sea."],

  // ---------------- Essos: the Free Cities & the Rhoyne ----------------
  ["Braavos", 2201, 1413, "city", "free-cities", 1, "The Secret City",
    "Greatest of the Free Cities, hidden in a fog-bound lagoon behind its Titan, ruled by the Sealord and famed for its water dancers."],
  ["Pentos", 2215, 2070, "city", "free-cities", 1, "Free City of merchant princes",
    "A wealthy Free City of canals and colored domes, where magisters grow rich and keep their daggers hidden."],
  ["Norvos", 2602, 1830, "city", "free-cities", 2, "City of the bearded priests",
    "A hill city of bells and bearded priests above the Noyne."],
  ["Qohor", 2890, 1760, "city", "free-cities", 2, "City of sorcerers",
    "The Free City at the edge of its great forest, famed for dark arts and smiths who can rework Valyrian steel."],
  ["Myr", 2337, 2514, "city", "free-cities", 2, "City of crafts",
    "A Free City famed for lace, lenses, and green-eyed slavers."],
  ["Tyrosh", 2059, 2531, "city", "free-cities", 2, "City of dyes",
    "An island Free City of bright-dyed beards, pear brandy, and hired swords."],
  ["Lys", 2221, 2898, "city", "free-cities", 2, "City of pleasure",
    "An island Free City of perfumed gardens, famed for its pleasure houses and its poisons."],
  ["Selhorys", 2725, 2658, "town", "free-cities", 3, "River town of the Rhoyne",
    "A walled river town on the Rhoyne, tributary to Volantis."],
  ["Valysar", 2741, 2755, "town", "free-cities", 3, "River town of the Rhoyne",
    "A Volantene river town on the great Rhoyne."],
  ["Volon Therys", 2803, 2861, "town", "free-cities", 3, "River town of the Rhoyne",
    "A river town on the lower Rhoyne, under the sway of Volantis."],
  ["Sar Mell", 2802, 2834, "ruin", "free-cities", 3, "Ruin of the Rhoynar",
    "A Rhoynish town broken in the old wars with Valyria."],
  ["Ny Sar", 2616, 2168, "ruin", "free-cities", 3, "Ruin of the Rhoynar",
    "The drowned palace-city of Princess Nymeria's people, at the meeting of Rhoyne and Noyne."],
  ["Volantis", 2838, 2925, "city", "free-cities", 2, "Oldest of the Free Cities",
    "The first daughter of Valyria, sprawled across the mouth of the Rhoyne behind its Black Walls — a city of tiger cloaks and red priests, where slaves outnumber the free five to one."],

  // ---------------- Essos: the Dothraki sea & the east ----------------
  ["Vaes Dothrak", 4754, 1800, "city", "dothraki-sea", 1, "City of the horselords",
    "The Dothraki's only city — no walls, no buildings but stolen monuments, watched over by the Mother of Mountains."],
  ["Village of the Lhazareen", 4282, 2500, "town", "dothraki-sea", 2, "Village of the lamb men",
    "A mud-walled village of the peaceful Lhazareen, herders whom the Dothraki raid for slaves."],
  ["Bayasabhad", 5247, 2688, "city", "dothraki-sea", 3, "City of the Bone Mountains",
    "A far eastern city guarding a pass through the Bones."],
  ["Samyrian", 5199, 2246, "city", "dothraki-sea", 3, "City of the Bone Mountains",
    "An eastern pass-city above the Dothraki sea."],
  ["Qarth", 5283, 3186, "city", "dothraki-sea", 1, "The greatest city that ever was or will be",
    "The queen of cities on the Jade Gates, ringed by triple walls — so its merchants never tire of saying."],

  // ---------------- Essos: Slaver's Bay & old Valyria ----------------
  ["Meereen", 4113, 2612, "city", "slavers-bay", 1, "Great city of Slaver's Bay",
    "The largest of the slave cities, a city of colored brick beneath its Great Pyramid."],
  ["Yunkai", 4035, 2703, "city", "slavers-bay", 2, "The Yellow City",
    "A slaver city of yellow brick, breeder of bed slaves."],
  ["Astapor", 4010, 2940, "city", "slavers-bay", 2, "The Red City",
    "The southernmost of the slave cities, red brick and dust at the mouth of the Worm, where the Good Masters train and sell the Unsullied."],
  ["Old Ghis", 4033, 3257, "ruin", "slavers-bay", 3, "Ruin of the Ghiscari Empire",
    "The mother city of the old empire the dragons of Valyria burned five thousand years ago."],
  ["New Ghis", 4090, 3520, "city", "slavers-bay", 3, "Island city of the Ghiscari",
    "An island city where the old empire's descendants drill iron legions."],
  ["Tolos", 3613, 2828, "city", "slavers-bay", 3, "City of slingers",
    "A slaver city on the Gulf of Grief, famed for its slingers."],
  ["Elyria", 3524, 2860, "city", "slavers-bay", 3, "Island city",
    "An island city of the Gulf of Grief."],
  ["Mantarys", 3448, 2713, "city", "slavers-bay", 3, "City on the demon road",
    "An ill-omened city whose people are said to be born twisted, on the haunted road to Valyria."],
  ["Bhonash", 3804, 2622, "town", "slavers-bay", 3, "Waystation of the east",
    "A dusty town on the caravan roads north of Slaver's Bay."],
  ["Oros", 3416, 3183, "ruin", "slavers-bay", 3, "Dead city of Valyria",
    "A Valyrian city drowned and broken in the Doom."],
  ["Tyria", 3335, 3318, "ruin", "slavers-bay", 3, "Dead city of Valyria",
    "A sister city of old Valyria, lost in the Doom."],
  ["Valyria", 3321, 3423, "ruin", "slavers-bay", 2, "The Doom that came",
    "The shattered heart of the greatest civilization the world has known, where the sea still smokes and demons are said to walk."],

  // ---------------- Rivers, forests & wonders ----------------
  ["The Wall", 1350, 252, "landmark", "the-north", 2, "Seven hundred feet of ice",
    "The great ice wall raised by Bran the Builder eight thousand years ago, stretching a hundred leagues from the Shadow Tower to Eastwatch. Manned by the Night's Watch from its nineteen castles — three still garrisoned — it is the realm's shield against whatever the long night sends south. Old Nan says there are spells woven through the ice."],
  ["The Trident", 1315, 1660, "landmark", "the-riverlands", 2, "The great river of the Riverlands",
    "The greatest river of Westeros, gathered from its three branches — the Red Fork, Green Fork and Blue Fork — and running to the Bay of Crabs. Its Ruby Ford is named for the stones struck from Rhaegar Targaryen's breastplate when Robert's warhammer ended a dynasty there. Every war in the realm's memory has been fought across its crossings."],
  ["The Gods Eye", 1314, 1848, "landmark", "the-riverlands", 3, "The sacred lake",
    "A vast round lake in the heart of the Riverlands, overlooked by the melted towers of Harrenhal. At its center lies the Isle of Faces, where the children of the forest and the First Men swore the Pact that ended their war — the weirwoods there still wear their carved faces, tended, the tales say, by the last green men."],
  ["The Isle of Faces", 1338, 1866, "landmark", "the-riverlands", 3, "Where the Pact was sworn",
    "The holy island in the Gods Eye where the Pact between the First Men and the children of the forest was sealed beneath the carved weirwoods. No one sails there now; the smallfolk say the green men still keep it, antlered and patient, waiting out the centuries."],
  ["The Neck", 1195, 1160, "landmark", "the-north", 3, "The swamp that guards the North",
    "The great bog that pinches Westeros to a narrow, fevered waist — quicksands, lizard-lions and crannogmen who move through the marsh like ghosts. The causeway through it can be held by a handful against a host, which is why every southern king who marched on the North regretted it at Moat Cailin."],
  ["The Kingswood", 1565, 2185, "landmark", "the-crownlands", 3, "The king's hunting wood",
    "The royal forest south of the Blackwater, where kings hunt boar and outlaws once made the Kingswood Brotherhood famous. Robert Baratheon took his last quarry here — or it took him."],
  ["The Wolfswood", 1085, 660, "landmark", "the-north", 3, "The deep wood of the North",
    "The great forest that sprawls northwest of Winterfell toward the Bay of Ice — old pine and sentinel, direwolves in its deeps, and smallfolk who still leave offerings at heart trees."],
  ["The Blackwater Rush", 1445, 2115, "landmark", "the-crownlands", 3, "The river of the capital",
    "The deep, swift river that meets the sea at King's Landing, spanned by no bridge for three hundred miles. Its bay burned green with wildfire the night Stannis Baratheon came for the city and the Imp's chain closed behind his fleet."],
  ["The Mander", 1055, 2355, "landmark", "the-reach", 3, "The slow river of the Reach",
    "The broadest, laziest river in Westeros, watering the endless fields of the Reach from Highgarden down to Oldtown's straits. Its banks feed half the realm — which is why whoever holds the Mander holds the granary of the Seven Kingdoms."],
  ["The Honeywine", 762, 2632, "landmark", "the-reach", 3, "Oldtown's river",
    "The gentle river that flows through Oldtown beneath the Citadel's bridges, its valley famed for orchards, hives and the honey-colored light the maesters write poems about when they should be studying."],
  ["The Mountains of the Moon", 1522, 1455, "landmark", "the-vale", 3, "The wall around the Vale",
    "The grey peaks that make the Vale a fortress and its hill tribes a menace — Stone Crows, Burned Men and Black Ears who bow to no lord and rob every traveler the Bloody Gate doesn't save."],
  ["The Fingers", 1975, 1545, "landmark", "the-vale", 3, "Littlefinger's bleak home",
    "Four stony peninsulas clawing into the narrow sea — sheep pellets, salt wind, and the smallest lordship in the Vale, whose most famous son named himself for it and climbed all the way to the king's council."],
  ["The Stepstones", 2000, 2740, "landmark", "free-cities", 3, "The pirate isles",
    "The broken chain of islands between Dorne and the Disputed Lands — the drowned remnant, maesters say, of the land bridge the First Men crossed. Every age gives them a new crop of pirate kings, and every age some prince has to burn them out."],
  ["The Rhoyne", 2728, 2495, "landmark", "free-cities", 2, "Mother Rhoyne, the great river",
    "The mightiest river in the world, so wide along her lower reaches that a man midstream sees no bank on either side. Her people, the Rhoynar, built wonders on her waters until Valyria's dragons came; Princess Nymeria fled down her length with ten thousand ships and wed her people to Dorne. The Free Cities' barge trade still calls her Mother Rhoyne — and her mists still hide the Sorrows."],
  ["Chroyane, the Sorrows", 2757, 2645, "ruin", "free-cities", 3, "The drowned festival city",
    "Once the Rhoynar's city of song and festival, now a drowned ruin in perpetual fog, its Bridge of Dream broken and its Palace of Sorrow haunted by the grey plague. Rivermen pole past quickly and quietly: the stone men who haunt the Sorrows are dying of greyscale, and their touch shares it."],
  ["The Dothraki Sea", 3400, 1950, "landmark", "dothraki-sea", 2, "The ocean of grass",
    "A thousand leagues of green and gold grass without a hill or a tree, where the khalasars ride and the ghost grass waits, tall as a rider, at the world's edge. The Dothraki say the first man rode out of it on the first horse."],
  ["The Red Waste", 4900, 2870, "landmark", "dothraki-sea", 3, "The desert that eats khalasars",
    "The red desert east of Lhazar — cracked earth, dead cities, poisoned wells. Daenerys led the remnant of Drogo's khalasar across it because every other road belonged to someone who wanted her dragons."],
];

/* Minor Westerosi houses: canonical field colors for the small map banners.
   colors: [field, second tincture] · div: how the shield is divided
   Where a matching drawn shield exists (Wikimedia Commons), img overrides. */
const MINOR_ARMS = {
  "last-hearth":     { house: "House Umber", colors: ["#8a3b2a", "#c9c9c9"], div: "plain", img: "minor/last-hearth.png" },
  "karhold":         { house: "House Karstark", colors: ["#1b1b1b", "#e8e8e8"], div: "plain" },
  "the-dreadfort":   { house: "House Bolton", colors: ["#d8a0a0", "#8f1d2c"], div: "plain", img: "bolton.svg" },
  "hornwood":        { house: "House Hornwood", colors: ["#c9702e", "#5a3a1a"], div: "fess" },
  "torrhens-square": { house: "House Tallhart", colors: ["#7a5c3a", "#3f6b3a"], div: "fess" },
  "castle-cerwyn":   { house: "House Cerwyn", colors: ["#c9c9c9", "#1b1b1b"], div: "plain" },
  "barrowton":       { house: "House Dustin", colors: ["#1b1f24", "#8a6d3b"], div: "fess", img: "minor/barrowton.png" },
  "widows-watch":    { house: "House Flint", colors: ["#3a5f8a", "#c9c9c9"], div: "fess" },
  "white-harbor":    { house: "House Manderly", colors: ["#3d6b6b", "#e8e8e8"], div: "fess" },
  "oldcastle":       { house: "House Locke", colors: ["#5a4a7a", "#c9a15a"], div: "pale" },
  "flints-finger":   { house: "House Flint of the Finger", colors: ["#3a5f8a", "#c9c9c9"], div: "plain" },
  "seagard":         { house: "House Mallister", colors: ["#2d3a6b", "#d8d8d8"], div: "plain" },
  "raventree-hall":  { house: "House Blackwood", colors: ["#1b1b1b", "#e8e8e8"], div: "plain", img: "minor/raventree-hall.png" },
  "stone-hedge":     { house: "House Bracken", colors: ["#c9a15a", "#8f1d2c"], div: "plain", img: "minor/stone-hedge.png" },
  "acorn-hall":      { house: "House Smallwood", colors: ["#e0c060", "#5a3a1a"], div: "fess" },
  "harrenhal":       { house: "House Whent", colors: ["#e0c060", "#1b1b1b"], div: "plain", img: "minor/harrenhal.png" },
  "pinkmaiden":      { house: "House Piper", colors: ["#3a5f8a", "#d8a0b0"], div: "fess", img: "minor/pinkmaiden.png" },
  "runestone":       { house: "House Royce", colors: ["#8a6d3b", "#2b2015"], div: "plain" },
  "gulltown":        { house: "House Grafton", colors: ["#7a7a7a", "#c93a2e"], div: "fess" },
  "wickendon":       { house: "House Waxley", colors: ["#5a7a9c", "#e8e8d0"], div: "fess" },
  "faircastle":      { house: "House Farman", colors: ["#3a5f8a", "#e8e8e8"], div: "pale" },
  "feastfires":      { house: "House Prester", colors: ["#e8e8e8", "#8f1d2c"], div: "fess" },
  "the-crag":        { house: "House Westerling", colors: ["#d8c9a0", "#e8e8e8"], div: "fess" },
  "ashemark":        { house: "House Marbrand", colors: ["#6b6b6b", "#c9702e"], div: "fess", img: "minor/ashemark.png" },
  "golden-tooth":    { house: "House Lefford", colors: ["#e0c060", "#3a5f8a"], div: "fess" },
  "hornvale":        { house: "House Brax", colors: ["#c9c9c9", "#5a3a7a"], div: "plain" },
  "cleganes-keep":   { house: "House Clegane", colors: ["#e0c060", "#1b1b1b"], div: "plain", img: "clegane.svg" },
  "deep-den":        { house: "House Lydden", colors: ["#4a6741", "#e8e8e8"], div: "fess" },
  "silverhill":      { house: "House Serrett", colors: ["#e8e0c0", "#3f6b8a"], div: "fess" },
  "cornfield":       { house: "House Swyft", colors: ["#e0c060", "#2d4a8a"], div: "plain", img: "minor/cornfield.png" },
  "crakehall":       { house: "House Crakehall", colors: ["#7a5c3a", "#e8e8e8"], div: "fess", img: "minor/crakehall.png" },
  "maidenpool":      { house: "House Mooton", colors: ["#e8e8e8", "#c93a2e"], div: "fess", img: "minor/maidenpool.png" },
  "antlers":         { house: "House Buckwell", colors: ["#4a6741", "#c9a15a"], div: "plain" },
  "rosby":           { house: "House Rosby", colors: ["#e8e8e8", "#8f1d2c"], div: "pale", img: "minor/rosby.png" },
  "claw-isle":       { house: "House Celtigar", colors: ["#e8e8e8", "#c93a2e"], div: "plain" },
  "old-oak":         { house: "House Oakheart", colors: ["#e0c060", "#3f6b3a"], div: "fess" },
  "red-lake":        { house: "House Crane", colors: ["#7fa8c9", "#e8e8e8"], div: "fess" },
  "goldengrove":     { house: "House Rowan", colors: ["#c9c9c9", "#c9a15a"], div: "plain", img: "minor/goldengrove.png" },
  "bitterbridge":    { house: "House Caswell", colors: ["#e8e8e8", "#c9a15a"], div: "fess" },
  "grassy-vale":     { house: "House Meadows", colors: ["#6b8f4a", "#e8e8e8"], div: "plain" },
  "long-table":      { house: "House Merryweather", colors: ["#e8e0c0", "#c9702e"], div: "fess" },
  "cider-hall":      { house: "House Fossoway", colors: ["#e0c060", "#c93a2e"], div: "plain" },
  "ashford":         { house: "House Ashford", colors: ["#c9702e", "#e8e8e8"], div: "fess" },
  "brightwater-keep":{ house: "House Florent", colors: ["#e8e8e8", "#c9702e"], div: "plain" },
  "bandallon":       { house: "House Blackbar", colors: ["#c9c9c9", "#1b1b1b"], div: "pale", img: "minor/bandallon.png" },
  "honeyholt":       { house: "House Beesbury", colors: ["#1b1b1b", "#e0c060"], div: "fess" },
  "horn-hill":       { house: "House Tarly", colors: ["#4a6741", "#c93a2e"], div: "plain", img: "tarly.svg" },
  "oldtown":         { house: "House Hightower", colors: ["#e8e8e8", "#c93a2e"], div: "plain", img: "hightower.png" },
  "blackcrown":      { house: "House Bulwer", colors: ["#8f1d2c", "#e8e8e8"], div: "plain" },
  "uplands":         { house: "House Mullendore", colors: ["#e8e8e8", "#1b1b1b"], div: "fess" },
  "three-towers":    { house: "House Costayne", colors: ["#1b1f24", "#c9c9c9"], div: "pale" },
  "sun-house":       { house: "House Cuy", colors: ["#3a5f8a", "#e0c060"], div: "fess" },
  "griffins-roost":  { house: "House Connington", colors: ["#c93a2e", "#e8e8e8"], div: "pale" },
  "rain-house":      { house: "House Wylde", colors: ["#e0c060", "#3d6b6b"], div: "fess", img: "minor/rain-house.png" },
  "stonehelm":       { house: "House Swann", colors: ["#1b1b1b", "#e8e8e8"], div: "pale", img: "minor/stonehelm.png" },
  "mistwood":        { house: "House Mertyns", colors: ["#6b6b6b", "#e8e8e8"], div: "fess" },
  "blackhaven":      { house: "House Dondarrion", colors: ["#1b1b24", "#7a5cc9"], div: "plain" },
  "haystack-hall":   { house: "House Errol", colors: ["#8a5c3a", "#e0c060"], div: "fess" },
  "felwood":         { house: "House Fell", colors: ["#4a6741", "#e8e8e8"], div: "fess" },
  "bronzegate":      { house: "House Buckler", colors: ["#3a5f8a", "#c9a15a"], div: "plain" },
  "evenfall-hall":   { house: "House Tarth", colors: ["#7fa8c9", "#d8a0b0"], div: "quarter" },
  "nightsong":       { house: "House Caron", colors: ["#e0c060", "#1b1b1b"], div: "fess", img: "minor/nightsong.png" },
  "wyl":             { house: "House Wyl", colors: ["#e0c060", "#1b1f24"], div: "plain" },
  "kingsgrave":      { house: "House Manwoody", colors: ["#1b1b1b", "#e8e8e8"], div: "plain", img: "minor/kingsgrave.png" },
  "blackmont":       { house: "House Blackmont", colors: ["#e0c060", "#1b1b1b"], div: "fess", img: "minor/blackmont.png" },
  "skyreach":        { house: "House Fowler", colors: ["#2d4a8a", "#c9c9c9"], div: "plain" },
  "yronwood":        { house: "House Yronwood", colors: ["#d8c9a0", "#1b1f24"], div: "plain" },
  "starfall":        { house: "House Dayne", colors: ["#4a3a7a", "#e8e8e8"], div: "plain" },
  "hellholt":        { house: "House Uller", colors: ["#c93a2e", "#e0c060"], div: "fess" },
  "sandstone":       { house: "House Qorgyle", colors: ["#8f1d2c", "#1b1b1b"], div: "fess", img: "minor/sandstone.png" },
  "the-tor":         { house: "House Jordayne", colors: ["#e0c060", "#5a4c38"], div: "fess", img: "minor/the-tor.png" },
  "ghost-hill":      { house: "House Toland", colors: ["#e0c060", "#3f6b3a"], div: "plain" },
  "godsgrace":       { house: "House Allyrion", colors: ["#8f1d2c", "#c9a15a"], div: "quarter" },
  "vaith":           { house: "House Vaith", colors: ["#d8a0b0", "#1b1f24"], div: "fess" },
  "lemonwood":       { house: "House Dalt", colors: ["#e0c060", "#5a3a7a"], div: "plain", img: "minor/lemonwood.png" },
  "salt-shore":      { house: "House Gargalen", colors: ["#e0c060", "#c93a2e"], div: "fess" },
};

/* Seats whose canon fan-heraldry shield was sourced from Wikimedia Commons
   (assets/sigils/minor/<location-id>.png). All others use the drawn arms. */
const CANON_MINOR_SHIELDS = new Set([
  "karhold", "castle-cerwyn", "torrhens-square", "hornwood", "white-harbor",
  "oldcastle", "widows-watch", "flints-finger", "seagard", "runestone",
  "gulltown", "wickendon", "faircastle", "feastfires", "the-crag",
  "golden-tooth", "deep-den", "claw-isle", "old-oak", "red-lake", "grassy-vale",
  "long-table", "cider-hall", "ashford", "brightwater-keep", "honeyholt",
  "blackcrown", "uplands", "three-towers", "sun-house", "bitterbridge",
  "griffins-roost", "evenfall-hall", "blackhaven", "wyl", "yronwood", "starfall",
]);

/* which locations are the seats shown when House Banners are toggled on */
const HOUSE_SEATS = {
  "winterfell": "stark",
  "casterly-rock": "lannister",
  "storms-end": "baratheon",
  "dragonstone": "targaryen",
  "riverrun": "tully",
  "the-eyrie": "arryn",
  "pyke": "greyjoy",
  "the-twins": "frey",
  "highgarden": "tyrell",
  "sunspear": "martell",
};

/* Season 1 chronicle entries for major places (shown under "This season" in the info panel) */
const SEASON_LORE = {
  "winterfell": "Here the season begins: a deserter's execution, five direwolf pups, a king's visit — and a boy pushed from a tower window for what he saw.",
  "castle-black": "Jon Snow takes the black among thieves and poachers, finds a brother in Samwell Tarly — and a dead man's eyes open blue in the night.",
  "crasters-keep": "The rangings that pass Craster's hall this season bring back only rumors — of villages empty, and of the dead that walk.",
  "the-twins": "Robb's army can only cross the Green Fork here. Catelyn bargains with Lord Walder for the bridge — a bargain paid in promises of marriage.",
  "riverrun": "Catelyn Stark's birthplace. By season's end the northern host camps beneath its walls — and lifts Robb Stark up as King in the North.",
  "harrenhal": "Spoken of at court with a shudder — the cursed prize Lord Whent can barely afford to keep. Its melted towers loom over the God's Eye.",
  "the-eyrie": "Lysa Arryn nurses her son and her grievances here. Tyrion beats the sky cells with his tongue: a trial by combat, and Bronn's sword.",
  "casterly-rock": "Tywin Lannister rules from here in all but name — and when his son is taken hostage, the West empties its barracks.",
  "golden-tooth": "The Lannister host under Ser Jaime pours past the Golden Tooth this season to put the Riverlands to the sword.",
  "kings-landing": "Ned Stark serves as Hand here and pulls one thread too many. It ends on the steps of the Great Sept, with Ice in a stranger's hands.",
  "dragonstone": "The Targaryens' last seat in Westeros, held now by Stannis Baratheon — a name Ned Stark writes in a letter he never gets to send.",
  "storms-end": "Robert's birthright, spoken of at court — while his brother Renly slips out of the capital with a different crown in mind.",
  "highgarden": "Unvisited this season, but its favorite son Ser Loras — the Knight of Flowers — unhorses the Mountain at the Hand's tourney.",
  "oldtown": "Every grey-robed maester at every castle this season — Luwin, Aemon, Pycelle — earned his chain in this city.",
  "horn-hill": "Sam's father gave him a choice beneath these hills: take the black, or have a hunting accident. The Watch got its most loyal steward.",
  "sunspear": "Dorne keeps its distance this season — but the name of Elia Martell, wife of the last dragon prince, is not spoken lightly at court.",
  "blackhaven": "Its lord's banner rides out this season: Ned sends Beric Dondarrion to bring the Mountain to justice — an errand that outlives the man who gave it.",
  "moat-cailin": "Robb Stark's host masses here on its march south, where a handful of men can hold back an army.",
  "white-harbor": "Never shown this season, but its lords answer when Robb Stark calls the banners of the North.",
  "pyke": "Unvisited this season — but Theon Greyjoy has not seen it since the Starks took him as ward and hostage nine years ago.",
  "braavos": "Never visited — but Syrio Forel, First Sword of Braavos, teaches Arya what a girl says to the god of death: not today.",
  "pentos": "Under Illyrio Mopatis's roof, Viserys sells his sister to a khal for the promise of an army. Daenerys's story begins on this shore.",
  "vaes-dothrak": "Daenerys eats the stallion's heart here and the crones proclaim her son. Viserys demands his crown at swordpoint — and gets one of molten gold.",
  "village-of-the-lhazareen": "Drogo's khalasar sacks the lamb men for the ships Viserys was promised. Daenerys claims the godswife Mirri Maz Duur — a healer with her own accounting.",
  "qarth": "Beyond this season's story — but east of the red waste it waits, the greatest city that ever was or will be.",
  "summerhall": "The ruin where the Targaryen dream burned. Old Maester Aemon, who lost his family there, keeps his vigil at the Wall this season.",
  "stoney-sept": "Robert liked to retell it this season at Winterfell: the town whose ringing bells once hid a fugitive stag.",
  "lannisport": "The Lannister fleet rides at anchor here while the lions do their season's fighting on land.",
  "gulltown": "The Vale's port stays quiet — Lysa Arryn keeps her knights home no matter who writes to her.",
  "meereen": "Far beyond this season's horizon, the slave cities go on as they have for a thousand years — for now.",
  "valyria": "The Doom is a story this season — the story Viserys tells to explain the eggs, and the steel, and the name Targaryen.",
};

const WORLD = {
  regions: [
    { id: "the-north", name: "The North",
      description: "The largest of the Seven Kingdoms and the coldest, ruled from Winterfell by House Stark for eight thousand years. Its people are hard, its gods are old, and its memory is long.",
      season: "The season opens here — a deserter beheaded, direwolf pups in the snow, and a king riding north to ask for a Hand." },
    { id: "the-vale", name: "The Vale",
      description: "A green land walled in by the Mountains of the Moon, ruled by House Arryn from the Eyrie. Its knights are famed, and its passes are held by hill tribes who bow to no lord.",
      season: "Lysa Arryn shuts the Bloody Gate to the realm's troubles — until her sister drags Tyrion Lannister up the mountain for judgment." },
    { id: "the-riverlands", name: "The Riverlands",
      description: "Fertile country threaded by the forks of the Trident, seat of House Tully at Riverrun. Every war in Westeros seems to be fought across its fords and crossings.",
      season: "The war begins here in all but name: Tyrion seized at an inn, Lannister raiders burning the river villages, armies marching for the fords." },
    { id: "iron-islands", name: "The Iron Islands",
      description: "Bleak isles in the Sunset Sea whose people reave and pay the iron price, ruled by House Greyjoy from Pyke since their rebellion was broken.",
      season: "Quiet this season — but Theon Greyjoy, ward and hostage of the Starks, carries the kraken's pride wherever he goes." },
    { id: "the-westerlands", name: "The Westerlands",
      description: "Gold-veined hills ruled by House Lannister from Casterly Rock — the richest house in the Seven Kingdoms, and the one to whom the Crown owes the most.",
      season: "Lord Tywin raises his banners the moment his son is taken, and teaches the Riverlands what a lion's wrath costs." },
    { id: "the-crownlands", name: "The Crownlands",
      description: "The king's own lands around Blackwater Bay, ruled directly from the Iron Throne. Dragonstone, the old Targaryen seat, guards the bay's mouth.",
      season: "The heart of the game of thrones: Robert's court, Ned's investigation, Littlefinger's whispers — and the sword that falls at the Sept of Baelor." },
    { id: "the-reach", name: "The Reach",
      description: "The garden of Westeros — the most fertile and populous of the kingdoms, ruled by House Tyrell from Highgarden. Oldtown, seat of the Citadel, is its ancient city.",
      season: "Spoken of at court — the Knight of Flowers dazzles at the Hand's tourney — but the Reach itself stays out of the fighting this season." },
    { id: "the-stormlands", name: "The Stormlands",
      description: "Rain-lashed coasts and oak forests between King's Landing and Dorne, the ancestral lands of House Baratheon at Storm's End.",
      season: "Robert's homeland, held in his name while he drinks and hunts — and his brother Renly eyes a crown of his own." },
    { id: "dorne", name: "Dorne",
      description: "The sun-scorched south beyond the Red Mountains, ruled by House Martell from Sunspear. Dorne bows to the Iron Throne but was never conquered by it.",
      season: "Far from this season's war — though the old wound of Elia Martell's death is not forgotten in the south." },
    { id: "free-cities", name: "The Free Cities",
      description: "Nine merchant cities across the Narrow Sea, daughters of old Valyria — Braavos, Pentos, Myr and their sisters — where exiles scheme and sellswords wait.",
      season: "In Pentos, magister Illyrio hosts the last Targaryens; in Braavos, a certain dancing master learned his trade." },
    { id: "dothraki-sea", name: "The Dothraki Sea & the East",
      description: "An ocean of grass in the heart of Essos, crossed only by the khalasars of the horselords — and beyond it, the red waste and the distant splendor of Qarth.",
      season: "Daenerys Targaryen crosses it as a bought bride and ends the season walking out of a funeral pyre with three living dragons." },
    { id: "slavers-bay", name: "Slaver's Bay & Old Valyria",
      description: "The slave cities of the old Ghiscari coast — Meereen, Yunkai, and their kin — and south of them the smoking ruin of Valyria itself.",
      season: "Beyond this season's story, but the eggs on Daenerys's pyre were laid under Valyria's shadow." },
  ],

  houses: [
    { id: "stark", name: "House Stark", seat: "winterfell", region: "the-north",
      words: "Winter Is Coming", sigil: "Direwolf", colors: ["#c9c9c9", "#20242b"],
      description: "Kings of Winter turned Wardens of the North, the Starks have ruled from Winterfell for eight thousand years — since the Age of Heroes and Bran the Builder. Grey direwolves on white ice, they keep the old gods and the First Men's ways, ruling the largest and coldest of the Seven Kingdoms with a hard, plain northern honor." },
    { id: "lannister", name: "House Lannister", seat: "casterly-rock", region: "the-westerlands",
      words: "Hear Me Roar", sigil: "Lion", colors: ["#e8c368", "#8f1d2c"],
      description: "The richest house in the Seven Kingdoms, lords of Casterly Rock and the gold mines beneath it, whose true motto is said to be 'A Lannister always pays his debts.' A golden lion on crimson, descended from Lann the Clever, they hold the Westerlands and command wealth enough to buy armies, crowns, and kings." },
    { id: "baratheon", name: "House Baratheon", seat: "storms-end", region: "the-stormlands",
      words: "Ours Is the Fury", sigil: "Crowned Stag", colors: ["#caa23a", "#1b1b1b"],
      description: "The youngest of the great houses, sprung from an Orys Baratheon who was rumored a Targaryen's bastard brother, seated at storm-battered Storm's End on the narrow sea. A crowned black stag on gold — strong, proud, and famously stubborn lords of the Stormlands." },
    { id: "targaryen", name: "House Targaryen", seat: "dragonstone", region: "the-crownlands",
      words: "Fire and Blood", sigil: "Three-Headed Dragon", colors: ["#e05c5c", "#1a1a1a"],
      description: "The dragonlords of old Valyria, silver-haired and violet-eyed, who alone survived the Doom and conquered the Seven Kingdoms astride dragons. A three-headed red dragon on black, they ruled from the Iron Throne for near three hundred years before the rebellion cast the last of them into exile across the narrow sea." },
    { id: "tully", name: "House Tully", seat: "riverrun", region: "the-riverlands",
      words: "Family, Duty, Honor", sigil: "Leaping Trout", colors: ["#c9d4e0", "#3a5f8a"],
      description: "Lords of Riverrun and Lords Paramount of the Trident, raised to rule the fertile, much-fought-over Riverlands after Aegon's Conquest. A silver trout leaping on a field of red and blue, the Tullys are known for binding themselves to greater houses through marriage — and for their words, which name what they hold dearest." },
    { id: "arryn", name: "House Arryn", seat: "the-eyrie", region: "the-vale",
      words: "As High as Honor", sigil: "Moon-and-Falcon", colors: ["#dfe8f0", "#5a7a9c"],
      description: "The purest blood of the First Men and the Andal kings, Wardens of the East, enthroned in the Eyrie high in the Mountains of the Moon above the rich and sheltered Vale of Arryn. A white moon-and-falcon on sky blue, their mountain seat is reckoned impregnable, reached only through the Bloody Gate and a chain of castles." },
    { id: "greyjoy", name: "House Greyjoy", seat: "pyke", region: "iron-islands",
      words: "We Do Not Sow", sigil: "Golden Kraken", colors: ["#c9a15a", "#1b1f24"],
      description: "Ironborn lords of Pyke and the bleak Iron Islands, who follow the Drowned God and the Old Way of reaving, taking their wealth and their salt wives at the point of a sword. A golden kraken on black, they hold that 'What is dead may never die,' and bow to the green lands only when they must." },
    { id: "frey", name: "House Frey", seat: "the-twins", region: "the-riverlands",
      words: "We Stand Together", sigil: "The Twin Towers", colors: ["#b8c4d0", "#3d4a5c"],
      description: "Upjumped and enormously numerous, the Freys have held the only bridge across the Green Fork for six hundred years, growing rich on the tolls of the Twins. Two blue towers joined by a bridge on grey, they are bannermen to the Tullys — resented for their new blood and their habit of arriving late to every battle." },
    { id: "tyrell", name: "House Tyrell", seat: "highgarden", region: "the-reach",
      words: "Growing Strong", sigil: "Golden Rose", colors: ["#e8c368", "#3f6b3a"],
      description: "Wardens of the South and Lords of Highgarden, stewards risen to rule the vast, fertile Reach — second only to the Lannisters in wealth and first in men. A golden rose on green, they command the largest armies in the realm and the deepest granaries, and cultivate influence as carefully as their famous gardens." },
    { id: "martell", name: "House Martell", seat: "sunspear", region: "dorne",
      words: "Unbowed, Unbent, Unbroken", sigil: "Spear-Pierced Sun", colors: ["#e8c368", "#b0563a"],
      description: "Princes of Dorne, the last kingdom to bow to the dragons — and only by marriage, never by conquest. A red sun pierced by a golden spear, the Martells rule the hot southern deserts from Sunspear by Rhoynish law and custom, patient, proud, and long of memory." },
  ],

  journeys: [
    { id: "daenerys", character: "Daenerys Targaryen", initial: "D",
      color: "#c25353", summary: "Pentos → the Dothraki Sea · 5 stops",
      stops: [
        { location: "pentos", episode: 1, epTitle: "Winter Is Coming",
          note: "Sold by her brother to Khal Drogo, Daenerys is wed on the shore at sunset — a stranger given to a stranger, with three stone eggs for a wedding gift." },
        { at: [3400, 1950], name: "The Dothraki Sea", episode: 2, epTitle: "The Kingsroad",
          note: "The khalasar rides east into the grass. Blisters, silence, fear — and then, slowly, the first lessons in how a khaleesi commands." },
        { location: "vaes-dothrak", episode: 6, epTitle: "A Golden Crown",
          note: "She eats the stallion's heart and the crones proclaim her son. Viserys demands his crown at swordpoint — and Drogo pours him one of molten gold." },
        { location: "village-of-the-lhazareen", episode: 8, epTitle: "The Pointy End",
          note: "The khalasar sacks a lamb-men village for the ships Drogo promised. Daenerys claims the godswife Mirri Maz Duur — a healer with her own accounting." },
        { at: [4600, 2150], name: "The Funeral Pyre", episode: 10, epTitle: "Fire and Blood",
          note: "Drogo dead, the khalasar scattered, the witch bound to the pyre. Daenerys walks into the fire — and dawn finds her unburnt, with three living dragons." },
      ] },
    { id: "jon", character: "Jon Snow", initial: "J",
      color: "#5b7d9c", summary: "Winterfell → the Wall & beyond · 4 stops",
      stops: [
        { location: "winterfell", episode: 1, epTitle: "Winter Is Coming",
          note: "The bastard of Winterfell chooses the only place a bastard can rise: the Wall. Ghost pads at his side; Arya gets a sword called Needle first." },
        { location: "castle-black", episode: 3, epTitle: "Lord Snow",
          note: "The Watch is not the storied order of the songs — it's thieves and poachers. Jon learns to stop being the best swordsman in the yard and start being a brother." },
        { at: [1452, 205], name: "The Haunted Forest", episode: 7, epTitle: "You Win or You Die",
          note: "Assigned to the stewards and furious about it, Jon says his vows anyway — before a heart tree beyond the Wall, where the old gods can hear." },
        { at: [1470, 310], name: "Castle Black — the long night begins", episode: 9, epTitle: "Baelor",
          note: "A dead ranger's eyes open blue in the dark; Jon's torch saves the Lord Commander. He is given Longclaw — and chooses the Watch over his brother's war." },
      ] },
    { id: "arya", character: "Arya Stark", initial: "A",
      color: "#6b8a5a", summary: "Winterfell → King's Landing → the road north · 4 stops",
      stops: [
        { location: "winterfell", episode: 1, epTitle: "Winter Is Coming",
          note: "Better at sums and swords than sewing. When she leaves Winterfell with her father and sister, Jon's parting gift rides hidden in her baggage: Needle." },
        { at: [1400, 1730], name: "The Crossroads Inn", episode: 2, epTitle: "The Kingsroad",
          note: "A prince's cruelty by the river: Mycah dead, Nymeria driven off with thrown stones to save her life, and Lady executed in her place. Arya never forgets a name." },
        { location: "kings-landing", episode: 5, epTitle: "The Wolf and the Lion",
          note: "Syrio Forel teaches her the water dance — swift as a deer, quiet as a shadow. When the gold cloaks come, his wooden sword buys her escape." },
        { at: [1435, 1860], name: "The Kingsroad, north", episode: 10, epTitle: "Fire and Blood",
          note: "Shorn like a boy and answering to Arry, she marches north in Yoren's recruit column — a wolf hidden among thieves, one name of many on her list." },
      ] },
    { id: "ned", character: "Eddard Stark", initial: "N",
      color: "#a08549", summary: "Winterfell → King's Landing · 3 stops",
      stops: [
        { location: "winterfell", episode: 1, epTitle: "Winter Is Coming",
          note: "His old friend the king rides north with an offer that is a command: be my Hand. The letter about Jon Arryn's death makes refusal impossible." },
        { at: [1400, 1730], name: "The Crossroads Inn", episode: 2, epTitle: "The Kingsroad",
          note: "On the road south the court shows him its teeth: a butcher's boy hunted down, his daughter's wolf put to the sword on a queen's word. He does it himself, as is the old way." },
        { location: "kings-landing", episode: 9, epTitle: "Baelor",
          note: "He pulls the thread of Jon Arryn's death until the whole cloth unravels: the seed is strong. Betrayed, he confesses a lie to save his daughters — and Joffrey wants a head anyway." },
      ] },
    { id: "catelyn", character: "Catelyn Stark", initial: "C",
      color: "#7a6a9c", summary: "Winterfell → the war camps · 6 stops",
      stops: [
        { location: "winterfell", episode: 1, epTitle: "Winter Is Coming",
          note: "Bran falls — and then a killer comes for him in his bed with a Valyrian steel dagger. The dagger has an owner, and Catelyn means to find him." },
        { location: "kings-landing", episode: 3, epTitle: "Lord Snow",
          note: "She rides south in secret, but Littlefinger finds her within hours. The dagger, he says, was his — until he lost it to Tyrion Lannister. The first lie of the war." },
        { at: [1400, 1730], name: "The Crossroads Inn", episode: 4, epTitle: "Cripples, Bastards, and Broken Things",
          note: "Chance seats Tyrion at the same inn. Catelyn calls on her father's bannermen at the surrounding tables — and arrests the Imp in the king's peace." },
        { location: "the-eyrie", episode: 5, epTitle: "The Wolf and the Lion",
          note: "She brings her prisoner up the mountain to her sister's justice, and finds Lysa half-mad, nursing her son and trusting no one." },
        { location: "the-twins", episode: 9, epTitle: "Baelor",
          note: "Robb's army must cross the Green Fork, and only Walder Frey's bridge will serve. Catelyn walks into the Twins alone and buys the crossing with marriage promises." },
        { location: "riverrun", episode: 10, epTitle: "Fire and Blood",
          note: "In the camp beneath her childhood home, the river lords and the northmen raise their swords to her son: the King in the North. Her war is only beginning." },
      ] },
    { id: "tyrion", character: "Tyrion Lannister", initial: "T",
      color: "#b0563a", summary: "Winterfell → the Wall → the war · 6 stops",
      stops: [
        { location: "winterfell", episode: 1, epTitle: "Winter Is Coming",
          note: "He arrives with the royal party, reads everything, and gives Jon Snow the only useful advice a bastard gets: never forget what you are, and it cannot hurt you." },
        { location: "castle-black", episode: 3, epTitle: "Lord Snow",
          note: "He goes north to see the Wall and piss off the edge of the world. He leaves the Watch a promise of architects and men — one of the few promises at court kept." },
        { at: [1400, 1730], name: "The Crossroads Inn", episode: 4, epTitle: "Cripples, Bastards, and Broken Things",
          note: "Riding south, he stops for a bed at the wrong inn. Catelyn Stark rises from a corner table, and half the room draws steel at her word." },
        { location: "the-eyrie", episode: 6, epTitle: "A Golden Crown",
          note: "The sky cells nearly take him, so he talks: a trial by combat, and the sellsword Bronn fights for the coin he sees coming. The Imp walks out the Bloody Gate alive." },
        { at: [1235, 1590], name: "The Green Fork", episode: 9, epTitle: "Baelor",
          note: "Marching in his father's van with hill tribesmen for an army, he is trampled unconscious before the battle starts — and wakes to learn his side won without him." },
        { location: "kings-landing", episode: 10, epTitle: "Fire and Blood",
          note: "Tywin, needing one son back and one crisis managed, sends the son he never wanted: Tyrion will go to court and rule as acting Hand of the King." },
      ] },
    { id: "robb", character: "Robb Stark", initial: "R",
      color: "#8a9bb0", summary: "Winterfell → Riverrun · 5 stops",
      stops: [
        { location: "winterfell", episode: 8, epTitle: "The Pointy End",
          note: "Word comes that his father is taken and his sisters held. The boy who stayed home calls the banners of the North — and the lords come." },
        { location: "moat-cailin", episode: 8, epTitle: "The Pointy End",
          note: "The northern host masses at the old towers of the Neck, where the causeway makes an army thin. South of here there is no turning back." },
        { location: "the-twins", episode: 9, epTitle: "Baelor",
          note: "Walder Frey's bridge or a march of weeks. His mother pays the toll in promises — among them, a Frey daughter for the young wolf himself." },
        { at: [1050, 1780], name: "The Whispering Wood", episode: 9, epTitle: "Baelor",
          note: "He feints with two thousand men on the Green Fork and falls on Jaime Lannister's siege camp with the rest. The Kingslayer wakes in chains." },
        { location: "riverrun", episode: 10, epTitle: "Fire and Blood",
          note: "The lords of the north and the Trident will have no southern king. Swords rise in the firelight: the King in the North! The King in the North!" },
      ] },
  ],
};

/* ---------------- Season One, episode by episode ----------------
   throne: who sits it, which house, who serves as Hand
   people: j = journey id (traceable on the map) · loc = where they are
   power:  house strength 1–10 as of this episode
   deaths: named characters who die IN this episode */

const EPISODES = [
  { n: 1, title: "Winter Is Coming",
    throne: { king: "Robert I Baratheon", house: "baratheon", hand: "Vacant — Jon Arryn is dead" },
    events: [
      "Beyond the Wall, a ranging goes wrong: the White Walkers are seen for the first time in eight thousand years.",
      "Ned Stark executes the deserter who saw them — and his children find five direwolf pups in the snow.",
      "King Robert rides to Winterfell and asks Ned to be his Hand; the letter from Lysa accuses the Lannisters of murder.",
      "In Pentos, Viserys weds his sister Daenerys to Khal Drogo for the promise of an army.",
      "Bran climbs a tower, sees the queen and her brother — and Jaime pushes him from the window.",
    ],
    people: [
      { name: "Eddard Stark", j: "ned", note: "The king's justice, then the king's reluctant Hand." },
      { name: "Catelyn Stark", j: "catelyn", note: "Begs Ned to refuse — the letter changes everything." },
      { name: "Jon Snow", j: "jon", note: "Chooses the Wall, where a bastard's name doesn't matter." },
      { name: "Arya Stark", j: "arya", note: "Better with a bow than her brother, and bored by needlework." },
      { name: "Robb Stark", j: "robb", note: "The heir who stays home when the pack splits." },
      { name: "Tyrion Lannister", j: "tyrion", note: "Reads everything; drinks and knows things." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "Sold to a khal, wed at sunset with three stone eggs." },
      { name: "King Robert", loc: "winterfell", note: "Fat, restless, and haunted by a dead girl's name." },
      { name: "Bran Stark", loc: "winterfell", note: "Climbs too well, sees too much, falls too far." },
      { name: "Khal Drogo", loc: "pentos", note: "A khal of forty thousand riders takes a silver-haired bride." },
    ],
    power: { stark: 8, lannister: 8, baratheon: 9, targaryen: 1, tully: 6, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Jon Arryn, Hand of the King", note: "Poisoned before the season opens — the death that starts it all." },
      { name: "Ser Waymar Royce", note: "Slain by a White Walker beyond the Wall." },
      { name: "Gared of the Night's Watch", note: "Taken by the cold things in the dark." },
      { name: "Will of the Night's Watch", note: "Fled south; beheaded by Ned Stark as a deserter." },
    ] },
  { n: 2, title: "The Kingsroad",
    throne: { king: "Robert I Baratheon", house: "baratheon", hand: "Lord Eddard Stark" },
    events: [
      "The court rides south; Jon and Tyrion turn north for the Wall.",
      "A catspaw comes for the comatose Bran with Valyrian steel — Catelyn and the direwolf Summer stop him.",
      "At the Crossroads, Joffrey's cruelty leaves the butcher's boy dead, Nymeria banished, and Lady executed in her place.",
      "Catelyn resolves to ride south in secret with the assassin's dagger.",
      "On the Dothraki sea, Daenerys begins to find her footing as khaleesi.",
    ],
    people: [
      { name: "Eddard Stark", j: "ned", note: "Puts Lady to the sword himself, as the old way demands." },
      { name: "Arya Stark", j: "arya", note: "Throws stones at her own wolf to save her life." },
      { name: "Catelyn Stark", j: "catelyn", note: "Finds a strand of blond hair in the broken tower." },
      { name: "Jon Snow", j: "jon", note: "Gives Arya a sword named Needle and rides for the Wall." },
      { name: "Tyrion Lannister", j: "tyrion", note: "Slaps a prince, then goes to see the edge of the world." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "Learns that a khaleesi commands — starting in her own tent." },
      { name: "Bran Stark", loc: "winterfell", note: "Sleeps on while a knife comes for him." },
    ],
    power: { stark: 8, lannister: 8, baratheon: 9, targaryen: 2, tully: 6, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [
      { name: "The catspaw assassin", note: "Torn out of his purpose by a direwolf's jaws." },
      { name: "Mycah, the butcher's boy", note: "Ridden down by the Hound on a prince's lie." },
      { name: "Lady, Sansa's direwolf", note: "Executed in Nymeria's place on the queen's demand." },
    ] },
  { n: 3, title: "Lord Snow",
    throne: { king: "Robert I Baratheon", house: "baratheon", hand: "Lord Eddard Stark" },
    events: [
      "Ned reaches King's Landing and finds the crown six million in debt — half of it to Tywin Lannister.",
      "Catelyn arrives in secret; Littlefinger tells her the assassin's dagger belonged to Tyrion Lannister.",
      "At Castle Black, Jon learns the Watch is thieves and poachers — and starts teaching instead of beating them.",
      "Arya begins lessons with Syrio Forel, First Sword of Braavos: not knitting.",
      "Old Nan tells Bran of the Long Night, when the White Walkers came the first time.",
    ],
    people: [
      { name: "Eddard Stark", j: "ned", note: "Sits his first small council and hates every minute." },
      { name: "Catelyn Stark", j: "catelyn", note: "Leaves with a name: Tyrion Lannister." },
      { name: "Jon Snow", j: "jon", note: "The best sword in the yard learns to be a brother." },
      { name: "Arya Stark", j: "arya", note: "First lesson: swift as a deer, quiet as a shadow." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "With child — and suddenly her brother is the beggar." },
      { name: "Tyrion Lannister", j: "tyrion", note: "Pisses off the top of the Wall, as promised." },
    ],
    power: { stark: 7, lannister: 8, baratheon: 9, targaryen: 2, tully: 6, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [] },
  { n: 4, title: "Cripples, Bastards and Broken Things",
    throne: { king: "Robert I Baratheon", house: "baratheon", hand: "Lord Eddard Stark" },
    events: [
      "The Hand's tourney opens; the Mountain's lance finds Ser Hugh of the Vale's throat.",
      "Ned follows Jon Arryn's last steps to an armorer's shop — and Robert's black-haired bastard.",
      "Samwell Tarly arrives at the Wall, and Jon makes the bullies stand down.",
      "Viserys learns he will ride in a khalasar's dust; Daenerys stops flinching.",
      "At the Crossroads Inn, Catelyn calls on her father's bannermen and arrests Tyrion Lannister.",
    ],
    people: [
      { name: "Catelyn Stark", j: "catelyn", note: "\"In the name of Catelyn Stark — seize him.\"" },
      { name: "Tyrion Lannister", j: "tyrion", note: "Stops at the wrong inn on the wrong night." },
      { name: "Eddard Stark", j: "ned", note: "The seed is strong — he just doesn't know it yet." },
      { name: "Jon Snow", j: "jon", note: "Ghost in the dark persuades Rast to be kind to Sam." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "Strikes her brother with a belt and doesn't apologize." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Dreams of tourneys; gets Ser Hugh's blood instead." },
    ],
    power: { stark: 7, lannister: 8, baratheon: 9, targaryen: 2, tully: 6, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Ser Hugh of the Vale", note: "Jon Arryn's former squire, opened at the throat by the Mountain's lance." },
    ] },
  { n: 5, title: "The Wolf and the Lion",
    throne: { king: "Robert I Baratheon", house: "baratheon", hand: "Lord Eddard Stark (resigns)" },
    events: [
      "Word of Tyrion's arrest reaches the capital — the lion and the wolf are at odds in the open now.",
      "Robert orders Daenerys assassinated; Ned refuses and lays down the Hand's badge.",
      "Catelyn climbs to the Eyrie and finds her sister half-mad, her nephew unweaned, her prisoner unwelcome.",
      "Jaime Lannister meets Ned in the street: Jory dies with a dagger through the eye, Ned's leg is spear-struck.",
      "Loras Tyrell whispers a crown into Renly's ear.",
    ],
    people: [
      { name: "Eddard Stark", j: "ned", note: "Throws the Hand's badge at his king rather than kill a girl." },
      { name: "Catelyn Stark", j: "catelyn", note: "Learns the Eyrie's justice is her sister's madness." },
      { name: "Tyrion Lannister", j: "tyrion", note: "Saves Catelyn in the hill-tribe ambush — into a sky cell anyway." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "A death warrant with her name crosses the narrow sea." },
      { name: "King Robert", loc: "kings-landing", note: "Wants a dead girl and can't say why loud enough." },
    ],
    power: { stark: 6, lannister: 8, baratheon: 9, targaryen: 2, tully: 5, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Jory Cassel", note: "Captain of Winterfell's guard, a dagger through the eye from Jaime Lannister." },
      { name: "Heward & Wyl of Winterfell", note: "Stark guardsmen cut down in the same street." },
    ] },
  { n: 6, title: "A Golden Crown",
    throne: { king: "Robert I Baratheon", house: "baratheon", hand: "Lord Eddard Stark (restored)" },
    events: [
      "Robert forces the badge back onto Ned and goes hunting.",
      "Sitting the throne, Ned sends Beric Dondarrion to bring the Mountain's head and summons Tywin to court.",
      "Tyrion demands trial by combat; the sellsword Bronn fights for him and Ser Vardis falls through the Moon Door.",
      "In Vaes Dothrak, Daenerys eats the stallion's heart; the crones name her son the Stallion Who Mounts the World.",
      "Viserys draws a sword in the sacred city — Drogo crowns him in molten gold.",
    ],
    people: [
      { name: "Tyrion Lannister", j: "tyrion", note: "Confesses everything except the crime — and walks free." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "Watches her brother die and does not look away." },
      { name: "Eddard Stark", j: "ned", note: "Reads Baratheon history and finally does the sum: black of hair." },
      { name: "Catelyn Stark", j: "catelyn", note: "Watches her sister's justice fail her family." },
      { name: "Arya Stark", j: "arya", note: "\"Syrio says every hurt is a lesson.\"" },
      { name: "Khal Drogo", loc: "vaes-dothrak", note: "\"A crown for a king.\" Gold, molten, poured." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 8, targaryen: 3, tully: 5, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Ser Vardis Egen", note: "The Eyrie's champion, sent through the Moon Door by Bronn's patience." },
      { name: "Viserys Targaryen", note: "The beggar king got his golden crown at last." },
      { name: "Stiv", note: "Wildling deserter, an arrow through the chest for holding a knife to Bran." },
    ] },
  { n: 7, title: "You Win or You Die",
    throne: { king: "Robert I Baratheon †, then Joffrey I", house: "baratheon", hand: "Eddard Stark, Protector of the Realm — for a day" },
    events: [
      "Ned tells Cersei he knows: her children are Jaime's, none of them Robert's.",
      "A boar opens the king; Robert dictates his will to \"my son\" — Ned writes \"my rightful heir\".",
      "Littlefinger promises the gold cloaks; Renly offers a coup; Ned chooses honor.",
      "In the throne room Cersei tears the will — \"you win or you die\" — and Littlefinger's knife finds Ned's throat.",
      "Beyond the Wall, Jon says his vows before a heart tree; an assassin's wine fails, and Drogo vows to cross the sea.",
    ],
    people: [
      { name: "Eddard Stark", j: "ned", note: "Warns Cersei to run. Mercy is his undoing." },
      { name: "Jon Snow", j: "jon", note: "A steward, not a ranger — until Sam explains what it means." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "A wineseller's poison buys her a khal's war." },
      { name: "King Robert", loc: "kings-landing", note: "Killed by a boar, a skin of wine, and seventeen years of wanting to be elsewhere." },
      { name: "Sansa Stark", loc: "kings-landing", note: "A pawn who doesn't know the game has started." },
    ],
    power: { stark: 5, lannister: 9, baratheon: 6, targaryen: 3, tully: 5, arryn: 4, greyjoy: 3, frey: 4, tyrell: 6, martell: 5 },
    deaths: [
      { name: "King Robert I Baratheon", note: "Gored by a boar while his squire kept the wine coming." },
    ] },
  { n: 8, title: "The Pointy End",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Vacant — the old Hand rots in the black cells" },
    events: [
      "The Stark household is put to the sword; Sansa is taken, Ned chained in the black cells.",
      "Syrio Forel holds the door with a wooden sword; Arya takes Needle and disappears into the city.",
      "Robb calls the banners of the North and marches for the Neck.",
      "A dead ranger rises in Castle Black; Jon's torch saves the Lord Commander.",
      "The khalasar sacks a Lhazareen village for ships; Daenerys claims the godswife Mirri Maz Duur — and Drogo takes a wound.",
    ],
    people: [
      { name: "Robb Stark", j: "robb", note: "\"Then it will be swords for the North.\" The banners answer." },
      { name: "Arya Stark", j: "arya", note: "Her first life taken — a stable boy, the pointy end first." },
      { name: "Jon Snow", j: "jon", note: "Burns a dead man and learns fire is the answer." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "Claims the healers and the women — mercy with a price." },
      { name: "Catelyn Stark", j: "catelyn", note: "Rides for her son's war camp at the Neck." },
      { name: "Tyrion Lannister", j: "tyrion", note: "Talks the hill tribes into an army and marches with his father." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Made to write the letter naming her father traitor." },
      { name: "Khal Drogo", loc: "village-of-the-lhazareen", note: "Vows to cross the black salt sea — and takes a wound keeping his khaleesi's mercy." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 5, targaryen: 4, tully: 4, arryn: 4, greyjoy: 3, frey: 5, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Syrio Forel", note: "First Sword of Braavos, last seen with a broken wooden sword and five armored men. Not today — presumed." },
      { name: "Septa Mordane", note: "Stayed behind so Sansa could run. Her head found the spikes." },
      { name: "Vayon Poole & the Stark household", note: "Put to the sword when the gold cloaks turned." },
    ] },
  { n: 9, title: "Baelor",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Catelyn buys the Twins' crossing from Walder Frey with marriage promises — one of them Robb's.",
      "Robb feints at the Green Fork and falls on Jaime Lannister in the Whispering Wood: the Kingslayer in chains.",
      "Tyrion is trampled by his own hill tribes before the Green Fork battle even starts.",
      "Drogo's wound festers; Daenerys lets Mirri Maz Duur work blood magic as the khalasar recoils.",
      "Ned confesses a lie to save his daughters. Joffrey wants a head anyway — and Ice comes down at the Sept of Baelor.",
    ],
    people: [
      { name: "Eddard Stark", j: "ned", note: "Sees Arya on Baelor's statue, says one last word: \"Baelor.\"" },
      { name: "Robb Stark", j: "robb", note: "Trades two thousand men for a Kingslayer." },
      { name: "Catelyn Stark", j: "catelyn", note: "Walks alone into Walder Frey's hall and wins the war a bridge." },
      { name: "Arya Stark", j: "arya", note: "Yoren pulls her off the statue before the sword falls." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "\"Only death pays for life.\" She doesn't ask whose." },
      { name: "Tyrion Lannister", j: "tyrion", note: "Wakes up after his own battle, victorious and unconscious." },
      { name: "Jon Snow", j: "jon", note: "Given Longclaw — and told his war is here, not south." },
    ],
    power: { stark: 6, lannister: 8, baratheon: 5, targaryen: 3, tully: 5, arryn: 3, greyjoy: 3, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Lord Eddard Stark", note: "The Hand of the King, beheaded with his own greatsword on the steps of the Great Sept." },
      { name: "Qotho", note: "Drogo's bloodrider, dead on Ser Jorah's blade for defying the maegi." },
    ] },
  { n: 10, title: "Fire and Blood",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "The North remembers: the river lords and northmen raise Robb as the King in the North.",
      "Arya, shorn and renamed Arry, slips out of King's Landing in Yoren's recruit column.",
      "Joffrey shows Sansa her father's head on the walls.",
      "Tywin sends Tyrion to court to rule as acting Hand of the King.",
      "Daenerys gives Drogo mercy, binds the maegi to his pyre, and walks into the flames — dawn finds her unburnt, with three dragons.",
    ],
    people: [
      { name: "Robb Stark", j: "robb", note: "\"The King in the North!\" — swords in the firelight at Riverrun." },
      { name: "Daenerys Targaryen", j: "daenerys", note: "The Unburnt. Mother of Dragons. The world is different now." },
      { name: "Arya Stark", j: "arya", note: "A boy called Arry with a list that has just begun." },
      { name: "Tyrion Lannister", j: "tyrion", note: "The son Tywin never wanted, sent to do what no one else can." },
      { name: "Jon Snow", j: "jon", note: "Chooses the Watch over his brother's war — barely." },
      { name: "Catelyn Stark", j: "catelyn", note: "\"We will kill them all.\" First: get the girls back." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Stops being a little bird and starts surviving." },
      { name: "Khal Drogo", loc: "village-of-the-lhazareen", note: "\"When the sun rises in the west…\" A shell, given mercy, given fire." },
    ],
    power: { stark: 7, lannister: 8, baratheon: 5, targaryen: 4, tully: 6, arryn: 3, greyjoy: 3, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Khal Drogo", note: "The great khal, smothered by the hands that loved him — mercy for a living death." },
      { name: "Rhaego", note: "The Stallion Who Mounts the World, born dead and monstrous — the maegi's price." },
      { name: "Mirri Maz Duur", note: "The godswife burned on Drogo's pyre, singing until she wasn't." },
    ] },
];

/* expand rows into location objects */
WORLD.locations = LOCATION_ROWS.map(([name, x, y, type, region, rank, subtitle, description]) => {
  const id = name.toLowerCase().replace(/[''’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const minorArms = MINOR_ARMS[id] ? { ...MINOR_ARMS[id] } : null;
  if (minorArms && CANON_MINOR_SHIELDS.has(id)) minorArms.img = `minor/${id}.png`;
  return {
    id, name, x, y, type, region, rank, subtitle, description,
    lore: SEASON_LORE[id] || null,
    house: HOUSE_SEATS[id] || null,
    minorArms,
  };
});
