/* THE KNOWN WORLD - character portraits (in-costume show stills, square-cropped).
   Keys are the exact display names used in episode/book people lists, journeys,
   and house rosters; several honorific aliases point at the same file. */
const PEOPLE_IMGS = {
  // ---- House Stark ----
  "Eddard Stark": "eddard-stark.jpg",
  "Lord Eddard Stark": "eddard-stark.jpg",
  "Catelyn Stark": "catelyn-stark.jpg",
  "Robb Stark": "robb-stark.jpg",
  "Robb Stark, King in the North": "robb-stark.jpg",
  "Sansa Stark": "sansa-stark.jpg",
  "Arya Stark": "arya-stark.jpg",
  "Bran Stark": "bran-stark.jpg",
  "Rickon Stark": "rickon-stark.jpg",
  "Jon Snow": "jon-snow.jpg",
  "Jon Snow, Lord Commander": "jon-snow.jpg",
  "Benjen Stark": "benjen-stark.jpg",
  "Lyanna Stark": "lyanna-stark.jpg",
  "Rickard Stark": "rickard-stark.jpg",

  // ---- House Lannister ----
  "Tywin Lannister": "tywin-lannister.jpg",
  "Lord Tywin Lannister": "tywin-lannister.jpg",
  "Cersei Lannister": "cersei-lannister.jpg",
  "Jaime Lannister": "jaime-lannister.jpg",
  "Tyrion Lannister": "tyrion-lannister.jpg",
  "Joffrey Baratheon": "joffrey-baratheon.jpg",
  "King Joffrey I Baratheon": "joffrey-baratheon.jpg",
  "Tommen Baratheon": "tommen-baratheon.jpg",
  "King Tommen I Baratheon": "tommen-baratheon.jpg",
  "Myrcella Baratheon": "myrcella-baratheon.jpg",
  "Lancel Lannister": "lancel-lannister.jpg",
  "Kevan Lannister": "kevan-lannister.jpg",
  "Ser Kevan Lannister": "kevan-lannister.jpg",

  // ---- House Baratheon ----
  "Robert Baratheon": "robert-baratheon.jpg",
  "King Robert": "robert-baratheon.jpg",
  "King Robert I Baratheon": "robert-baratheon.jpg",
  "Stannis Baratheon": "stannis-baratheon.jpg",
  "Renly Baratheon": "renly-baratheon.jpg",
  "Shireen Baratheon": "shireen-baratheon.jpg",
  "Princess Shireen Baratheon": "shireen-baratheon.jpg",
  "Selyse Baratheon": "selyse-baratheon.jpg",
  "Queen Selyse Baratheon": "selyse-baratheon.jpg",
  "Gendry": "gendry.jpg",

  // ---- House Targaryen ----
  "Daenerys Targaryen": "daenerys-targaryen.jpg",
  "Daenerys Stormborn of House Targaryen": "daenerys-targaryen.jpg",
  "Viserys Targaryen": "viserys-targaryen.jpg",
  "Rhaegar Targaryen": "rhaegar-targaryen.jpg",
  "Aerys II Targaryen": "aerys-targaryen.jpg",
  "Khal Drogo": "khal-drogo.jpg",

  // ---- Tully / Arryn ----
  "Hoster Tully": "hoster-tully.jpg",
  "Lord Hoster Tully": "hoster-tully.jpg",
  "Brynden Tully": "brynden-tully.jpg",
  "Brynden \"the Blackfish\" Tully": "brynden-tully.jpg",
  "Edmure Tully": "edmure-tully.jpg",
  "Lysa Arryn": "lysa-arryn.jpg",
  "Jon Arryn": "jon-arryn.jpg",
  "Jon Arryn, Hand of the King": "jon-arryn.jpg",
  "Robin Arryn": "robin-arryn.jpg",
  "Petyr Baelish": "petyr-baelish.jpg",
  "Petyr \"Littlefinger\" Baelish": "petyr-baelish.jpg",

  // ---- Greyjoy / Frey / Bolton ----
  "Balon Greyjoy": "balon-greyjoy.jpg",
  "Euron Greyjoy": "euron-greyjoy.jpg",
  "Lord Euron Greyjoy": "euron-greyjoy.jpg",
  "Yara Greyjoy": "yara-greyjoy.jpg",
  "Theon Greyjoy": "theon-greyjoy.jpg",
  "Walder Frey": "walder-frey.jpg",
  "Ramsay Bolton": "ramsay-bolton.jpg",
  "Ramsay Snow": "ramsay-bolton.jpg",
  "Roose Bolton": "roose-bolton.jpg",

  // ---- Tyrell / Martell ----
  "Olenna Tyrell": "olenna-tyrell.jpg",
  "Lady Olenna Tyrell": "olenna-tyrell.jpg",
  "Mace Tyrell": "mace-tyrell.jpg",
  "Margaery Tyrell": "margaery-tyrell.jpg",
  "Queen Margaery Tyrell": "margaery-tyrell.jpg",
  "Loras Tyrell": "loras-tyrell.jpg",
  "Doran Martell": "doran-martell.jpg",
  "Prince Doran Martell": "doran-martell.jpg",
  "Oberyn Martell": "oberyn-martell.jpg",
  "Prince Oberyn Martell": "oberyn-martell.jpg",
  "Ellaria Sand": "ellaria-sand.jpg",
  "Trystane Martell": "trystane-martell.jpg",
  "Prince Trystane Martell": "trystane-martell.jpg",

  // ---- The court, the road, and the Watch ----
  "Sandor Clegane": "sandor-clegane.jpg",
  "Gregor Clegane": "gregor-clegane.jpg",
  "Ser Gregor Clegane": "gregor-clegane.jpg",
  "Brienne of Tarth": "brienne-of-tarth.jpg",
  "Davos Seaworth": "davos-seaworth.jpg",
  "Melisandre": "melisandre.jpg",
  "Melisandre of Asshai": "melisandre.jpg",
  "Samwell Tarly": "samwell-tarly.jpg",
  "Jorah Mormont": "jorah-mormont.jpg",
  "Ser Jorah Mormont": "jorah-mormont.jpg",
  "Jeor Mormont": "jeor-mormont.jpg",
  "Lord Commander Jeor Mormont": "jeor-mormont.jpg",
  "Barristan Selmy": "barristan-selmy.jpg",
  "Ser Barristan Selmy": "barristan-selmy.jpg",
  "Lyanna Mormont": "lyanna-mormont.jpg",
  "Missandei": "missandei.jpg",
  "Missandei of Naath": "missandei.jpg",
  "Varys": "varys.jpg",
  "Varys, Master of Whisperers": "varys.jpg",
  "Bronn": "bronn.jpg",
  "Shae": "shae.jpg",
  "Ros": "ros.jpg",
  "Qyburn": "qyburn.jpg",
  "Grand Maester Pycelle": "pycelle.jpg",
  "Syrio Forel": "syrio-forel.jpg",
  "Janos Slynt": "janos-slynt.jpg",
  "Septa Mordane": "septa-mordane.jpg",
  "Jory Cassel": "jory-cassel.jpg",
  "Ser Rodrik Cassel": "rodrik-cassel.jpg",
  "Maester Luwin": "maester-luwin.jpg",
  "Osha": "osha.jpg",
  "Jojen Reed": "jojen-reed.jpg",
  "Hodor": "hodor.jpg",
  "Talisa Stark": "talisa-stark.jpg",
  "Queen Talisa Stark": "talisa-stark.jpg",
  "Rickard Karstark": "rickard-karstark.jpg",
  "Lord Rickard Karstark": "rickard-karstark.jpg",
  "Beric Dondarrion": "beric-dondarrion.jpg",
  "Thoros of Myr": "thoros-of-myr.jpg",
  "The High Sparrow": "high-sparrow.jpg",
  "The Waif": "the-waif.jpg",
  "The Three-Eyed Raven": "three-eyed-raven.jpg",
  "Mycah, the butcher's boy": "mycah.jpg",

  // ---- The Wall and beyond ----
  "Alliser Thorne": "alliser-thorne.jpg",
  "Yoren of the Night's Watch": "yoren.jpg",
  "Maester Aemon Targaryen": "maester-aemon.jpg",
  "Grenn": "grenn.jpg",
  "Pyp": "pyp.jpg",
  "Edd Tollett": "edd-tollett.jpg",
  "Qhorin Halfhand": "qhorin-halfhand.jpg",
  "Craster": "craster.jpg",
  "Mance Rayder": "mance-rayder.jpg",
  "Ygritte": "ygritte.jpg",
  "Tormund Giantsbane": "tormund-giantsbane.jpg",
  "Karsi": "karsi.jpg",
  "The Night King": "night-king.jpg",

  // ---- Essos ----
  "Mirri Maz Duur": "mirri-maz-duur.jpg",
  "Doreah": "doreah.jpg",
  "Irri": "irri.jpg",
  "Hizdahr zo Loraq": "hizdahr-zo-loraq.jpg",
  "Daario Naharis": "daario-naharis.jpg",
  "Jaqen H'ghar": "jaqen-hghar.jpg",

  // ---- short-form and book-name aliases ----
  "Yoren": "yoren.jpg",
  "Rodrik Cassel": "rodrik-cassel.jpg",
  "Asha Greyjoy": "yara-greyjoy.jpg",

  // ---- factions & new members ----
  "Maester Aemon": "maester-aemon.jpg",
  "Grey Worm": "grey-worm.jpg",
  "Meera Reed": "meera-reed.jpg",
  "Matthos Seaworth": "matthos-seaworth.jpg",
  "Meryn Trant": "meryn-trant.jpg",
  "Xaro Xhoan Daxos": "xaro.jpg",
  "Illyrio Mopatis": "illyrio.jpg",
  "Kraznys mo Nakloz": "kraznys.jpg",
  "Razdal mo Eraz": "razdal.jpg",
  "Qotho": "qotho.jpg",
  "Rakharo": "rakharo.jpg",
  "Jhogo": "jhogo.jpg",
  "Septa Unella": "unella.jpg",
  "The High Septon": "high-septon.jpg",
  "Mero": "mero.jpg",
  "Leaf": "leaf.jpg",
  "Gilly": "gilly.jpg",
  "Styr": "styr.jpg",
  "Wun Wun": "wun-wun.jpg",
  "Aegon Targaryen": "young-griff.jpg",

  // ---- family members & notable additions ----
  "Rhaella Targaryen": "rhaella-targaryen.jpg",
  "Roslin Frey": "roslin-frey.jpg",
  "Yohn Royce": "yohn-royce.jpg",
  "Lothar Frey": "lothar-frey.jpg",
  "Black Walder Rivers": "black-walder.jpg",
  "Walda Bolton": "walda-bolton.jpg",
  "Randyll Tarly": "randyll-tarly.jpg",
  "Melessa Tarly": "melessa-tarly.jpg",
  "Dickon Tarly": "dickon-tarly.jpg",
  "Talla Tarly": "talla-tarly.jpg",
  "Maege Mormont": "maege-mormont.jpg",
  "Obara Sand": "obara-sand.jpg",
  "Nymeria Sand": "nymeria-sand.jpg",
  "Tyene Sand": "tyene-sand.jpg",
  "Bowen Marsh": "bowen-marsh.jpg",
  "Rast": "rast.jpg",
  "Karl Tanner": "karl-tanner.jpg",
  "Olly": "olly.jpg",
  "Rattleshirt": "rattleshirt.jpg",
  "Orell": "orell.jpg",
  "Mandon Moore": "mandon-moore.jpg",
  "Boros Blount": "boros-blount.jpg",
  "Lem Lemoncloak": "lem-lemoncloak.jpg",
  "Anguy": "anguy.jpg",
  "Podrick Payne": "podrick-payne.jpg",
  "Vardis Egen": "vardis-egen.jpg",
  "Tobho Mott": "tobho-mott.jpg",
  "Quaithe": "quaithe.jpg",
  "Prendahl na Ghezn": "prendahl.jpg",
  "Old Nan": "old-nan.jpg",
  "Jeyne Poole": "jeyne-poole.jpg",
  "Vayon Poole": "vayon-poole.jpg",

  // ---- prologue folk, the road, and Dorne ----
  "Maester Cressen": "maester-cressen.jpg",
  "Aeron Greyjoy": "aeron-greyjoy.jpg",
  "Areo Hotah": "areo-hotah.jpg",
  "Will of the Night's Watch": "will-nights-watch.jpg",
  "Ser Waymar Royce": "waymar-royce.jpg",
  "Gared": "gared.jpg",
  "Ilyn Payne": "ilyn-payne.jpg",
  "Hot Pie": "hot-pie.jpg",
  "Lommy Greenhands": "lommy.jpg",

  // ---- fetched from the wiki: show faces & book-character art ----
  "Torrhen Karstark": "torrhen-karstark.jpg",
  "Yezzan zo Qaggaz": "yezzan-zo-qaggaz.jpg",
  "Harry Strickland": "harry-strickland.jpg",
  "Victarion Greyjoy": "victarion-greyjoy.jpg",
  "Arys Oakheart": "arys-oakheart.jpg",
  "Stevron Frey": "stevron-frey.jpg",
  "Pate, the Citadel novice": "pate-novice.jpg",
};
