/* THE KNOWN WORLD — Seasons Two through Eight, episode by episode.
   Same format as Season One's EPISODES (js/data.js). Journey traces (j:) exist
   only for Season One; later seasons anchor people to map locations instead. */

const SEASONS_LATER = [

// ==================== SEASON TWO ====================
{ n: 2, name: "Season Two", episodes: [
  { n: 1, title: "The North Remembers",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "A red comet burns over the world; every claimant reads it as their own.",
      "Tyrion arrives at court with a mandate from his father — and a smirk for his sister.",
      "Stannis Baratheon proclaims his claim and burns the Seven on Dragonstone's shore for the red god.",
      "Robb sends peace terms Joffrey will never take; Cersei orders Robert's bastards butchered in the city.",
      "In the red waste, Dany's tiny khalasar starves around three growing dragons.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "kings-landing", note: "The only Lannister in the city who read a book about ruling." },
      { name: "Stannis Baratheon", loc: "dragonstone", note: "The rightful heir, with the charm of a ledger." },
      { name: "Robb Stark", loc: "riverrun", note: "Three victories, no crown recognized." },
      { name: "Daenerys Targaryen", loc: "qarth", note: "Leads her people through the red waste toward distant lights." },
      { name: "Jon Snow", loc: "crasters-keep", note: "The great ranging shelters with a man who marries his daughters." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Learns that a small council seat is not a throne." },
    ],
    power: { stark: 7, lannister: 8, baratheon: 7, targaryen: 2, tully: 5, arryn: 3, greyjoy: 3, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Maester Cressen", note: "Poisoned his own cup to take Melisandre with him. She drank first, and smiled." },
      { name: "Robert's bastards", note: "Infants and boys put to the knife across King's Landing on the queen's word." },
    ] },
  { n: 2, title: "The Night Lands",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Theon Greyjoy comes home to Pyke and finds his father unimpressed and his sister commanding ships.",
      "Tyrion removes Janos Slynt from the gold cloaks and gives them to Bronn.",
      "Arya, marching north with Yoren's recruits, shares the road with a caged man named Jaqen H'ghar.",
      "Davos recruits the pirate Salladhor Saan to Stannis's cause.",
      "A rider's head comes back in a bag: the khalasar's outriders meet the wrong khal.",
    ],
    people: [
      { name: "Theon Greyjoy", loc: "pyke", note: "Nine years a ward; his father sees only a Stark in iron clothes." },
      { name: "Arya Stark", loc: "harrenhal", note: "A boy called Arry on the kingsroad, with three names owed to her." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Cleans the gold cloaks with a smile and a demotion." },
      { name: "Yara Greyjoy", loc: "pyke", note: "Commands thirty ships; her brother commanded a horse here." },
      { name: "Daenerys Targaryen", loc: "qarth", note: "The red waste takes its toll in horses and riders." },
    ],
    power: { stark: 7, lannister: 8, baratheon: 7, targaryen: 2, tully: 5, arryn: 3, greyjoy: 4, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Rakharo", note: "Dany's bloodrider, his head returned in a saddlebag by a rival khal." },
    ] },
  { n: 3, title: "What Is Dead May Never Die",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Balon Greyjoy chooses crowns over kin: the ironborn will reave the North, and Theon must pick a family.",
      "Catelyn treats with Renly's hundred thousand at his tourney camp — and meets Brienne of Tarth.",
      "Tyrion tests the small council with three marriage rumors and catches Pycelle as the leak.",
      "Yoren dies defending his recruits; Arya, Gendry and Hot Pie are dragged to Harrenhal as prisoners.",
    ],
    people: [
      { name: "Theon Greyjoy", loc: "pyke", note: "Burns the letter that would have warned Robb. What is dead may never die." },
      { name: "Catelyn Stark", loc: "storms-end", note: "Watches a summer king play at war in painted armor." },
      { name: "Brienne of Tarth", loc: "storms-end", note: "Wins a place in Renly's Kingsguard with a sword's argument." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Three secrets, three councillors, one leak." },
      { name: "Arya Stark", loc: "harrenhal", note: "The Mountain's men pick a prisoner to die each day." },
    ],
    power: { stark: 7, lannister: 8, baratheon: 7, targaryen: 2, tully: 5, arryn: 3, greyjoy: 5, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Yoren of the Night's Watch", note: "Died as he lived: refusing to hand anyone over." },
      { name: "Lommy Greenhands", note: "A recruit who couldn't walk; Polliver put Needle through his throat." },
    ] },
  { n: 4, title: "Garden of Bones",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Robb wins at Oxcross; the West bleeds and Tywin falls back to Harrenhal.",
      "Joffrey has Sansa beaten before the court until Tyrion stops it.",
      "Renly and Stannis parley and part as enemies; Davos rows Melisandre into a cave beneath Storm's End.",
      "The shadow she births there has a face Davos knows.",
      "Daenerys reaches the gates of Qarth and bluffs her way past the Thirteen.",
    ],
    people: [
      { name: "Robb Stark", loc: "casterly-rock", note: "Wins every battle; meets a field nurse named Talisa among the wounded." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Learns court courtesy is armor, and armor can be stripped." },
      { name: "Stannis Baratheon", loc: "storms-end", note: "Offers his brother one night to reconsider. One." },
      { name: "Davos Seaworth", loc: "storms-end", note: "Rows a shadow ashore and loses a piece of his soul doing it." },
      { name: "Daenerys Targaryen", loc: "qarth", note: "The greatest city that ever was opens — a crack." },
      { name: "Arya Stark", loc: "harrenhal", note: "A prayer of names, whispered nightly: Joffrey. Cersei. Ilyn Payne." },
    ],
    power: { stark: 8, lannister: 7, baratheon: 7, targaryen: 3, tully: 5, arryn: 3, greyjoy: 5, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "The Tickler", note: "Harrenhal's questioner — a nameless death from a boy's hands, mourned by no one." },
    ] },
  { n: 5, title: "The Ghost of Harrenhal",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "The shadow kills Renly in his own tent; his hundred thousand scatter to Stannis and Highgarden.",
      "Brienne, blamed and hunted, swears her sword to Catelyn Stark.",
      "Tyrion discovers the alchemists' wildfire stockpile — and takes it for himself.",
      "Theon sails to raid the Stony Shore, and thinks bigger: Winterfell is barely garrisoned.",
      "Jaqen H'ghar owes three deaths; Arya spends the first on the Tickler.",
    ],
    people: [
      { name: "Brienne of Tarth", loc: "storms-end", note: "Watched a shadow with her king's face kill him." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Enough wildfire to burn a fleet — or a city." },
      { name: "Theon Greyjoy", loc: "moat-cailin", note: "A raid on fishing villages becomes a plan to take a castle." },
      { name: "Arya Stark", loc: "harrenhal", note: "A man owes three. She has a list far longer." },
      { name: "Daenerys Targaryen", loc: "qarth", note: "Xaro offers half his wealth for a wedding; Jorah offers truth." },
    ],
    power: { stark: 8, lannister: 7, baratheon: 6, targaryen: 3, tully: 5, arryn: 3, greyjoy: 5, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Renly Baratheon", note: "A king killed by a shadow with his brother's face, in front of his own guard." },
    ] },
  { n: 6, title: "The Old Gods and the New",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Theon takes Winterfell with twenty men and beheads Ser Rodrik with four strokes.",
      "A bread riot nearly takes the king; the High Septon is torn apart; Sansa is saved by the Hound.",
      "Beyond the Wall, Jon is ordered to execute a wildling woman named Ygritte — and can't.",
      "Bran and Rickon vanish from Winterfell with Osha and Hodor.",
      "In Qarth, Dany's dragons are stolen and the Thirteen bleed for it.",
    ],
    people: [
      { name: "Theon Greyjoy", loc: "winterfell", note: "Took his home's home. It will cost him everything he had left." },
      { name: "Jon Snow", loc: "fist-of-the-first-men", note: "One prisoner, one sunset, and he's lost in wildling country." },
      { name: "Sansa Stark", loc: "kings-landing", note: "The mob wanted the wolf girl. The Hound wanted otherwise." },
      { name: "Bran Stark", loc: "winterfell", note: "Gone into the dark with a giant and a wildling." },
      { name: "Daenerys Targaryen", loc: "qarth", note: "\"Where are my dragons?!\"" },
    ],
    power: { stark: 7, lannister: 7, baratheon: 6, targaryen: 2, tully: 5, arryn: 3, greyjoy: 6, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Ser Rodrik Cassel", note: "Master-at-arms of Winterfell, hacked apart by the boy he trained." },
      { name: "Irri", note: "Dany's handmaid, strangled in the theft of the dragons." },
      { name: "The High Septon", note: "Torn to pieces by the starving city he blessed." },
    ] },
  { n: 7, title: "A Man Without Honor",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Jaime murders his own cousin in a cell for one chance at escape — and is dragged back.",
      "Theon hunts the missing Stark boys and hangs two burned farm boys from Winterfell's walls.",
      "Ygritte talks circles around her captor until the ambush is hers, not his.",
      "In Qarth, Pyat Pree kills the Thirteen and names Xaro king; the dragons are in the House of the Undying.",
      "Sansa flowers; Cersei offers her the only honest lesson she has: love no one but your children.",
    ],
    people: [
      { name: "Jaime Lannister", loc: "riverrun", note: "A man without honor, by his own accounting." },
      { name: "Theon Greyjoy", loc: "winterfell", note: "Two small bodies, burned past knowing. Better to be cruel than weak." },
      { name: "Jon Snow", loc: "fist-of-the-first-men", note: "Captured by the free folk he was hunting." },
      { name: "Ygritte", loc: "fist-of-the-first-men", note: "\"You know nothing, Jon Snow.\"" },
      { name: "Daenerys Targaryen", loc: "qarth", note: "A warlock's invitation: come to the House of the Undying." },
    ],
    power: { stark: 7, lannister: 7, baratheon: 6, targaryen: 2, tully: 5, arryn: 3, greyjoy: 6, frey: 6, tyrell: 6, martell: 5 },
    deaths: [
      { name: "Alton Lannister", note: "Killed by his cousin Jaime for the width of a cell door." },
      { name: "Torrhen Karstark", note: "Robb's guard, killed in Jaime's escape — his father will want a debt paid." },
      { name: "The Thirteen of Qarth", note: "Throats cut in council by Pyat Pree's copies." },
    ] },
  { n: 8, title: "The Prince of Winterfell",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Yara comes for Theon with ironborn sense: the castle is indefensible, come home. He refuses.",
      "Stannis's fleet sails; Tyrion and Bronn count wildfire jars and chain links.",
      "Robb learns his mother freed the Kingslayer and puts her under guard; Brienne rows Jaime south.",
      "Arya spends her last death buying an exit: Jaqen empties Harrenhal's gate instead.",
      "Bran and Rickon never left: they're in the crypts below Theon's feet.",
    ],
    people: [
      { name: "Theon Greyjoy", loc: "winterfell", note: "A prince of a burned castle and twenty unhappy men." },
      { name: "Catelyn Stark", loc: "riverrun", note: "Traded the Kingslayer for a hope of her daughters." },
      { name: "Brienne of Tarth", loc: "riverrun", note: "One prisoner, one oath, one very long river." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Reads siege histories while the fleet closes." },
      { name: "Arya Stark", loc: "harrenhal", note: "A man keeps his word: walk out the front gate." },
    ],
    power: { stark: 7, lannister: 7, baratheon: 6, targaryen: 2, tully: 5, arryn: 3, greyjoy: 5, frey: 6, tyrell: 6, martell: 5 },
    deaths: [] },
  { n: 9, title: "Blackwater",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Tyrion Lannister, acting Hand" },
    events: [
      "Stannis's fleet enters the bay; one empty ship meets it, leaking wildfire.",
      "The bay burns green; Davos's ship shatters; his son is in the fire.",
      "Joffrey quits the walls; Tyrion leads the sortie himself — \"those are brave men knocking at our door.\"",
      "A Kingsguard's sword opens Tyrion's face at his own gate.",
      "Tywin and the Tyrell host take the field: the day belongs to the lion and the rose.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Saved the city; woke up scarred, demoted, and unthanked." },
      { name: "Stannis Baratheon", loc: "kings-landing", note: "Dragged from the walls still swinging." },
      { name: "Davos Seaworth", loc: "kings-landing", note: "The bay took his ship and his boy in one green breath." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Keeps the women singing while the queen drinks truths." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Sat the throne with poison in hand and her son on her knee." },
    ],
    power: { stark: 7, lannister: 9, baratheon: 4, targaryen: 2, tully: 5, arryn: 3, greyjoy: 5, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Matthos Seaworth", note: "Davos's son, taken by the wildfire he thought his god commanded." },
      { name: "Ser Mandon Moore", note: "Kingsguard, tried to kill Tyrion in the battle's smoke; Podrick's spear answered." },
    ] },
  { n: 10, title: "Valar Morghulis",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Tywin is named Hand and savior; Margaery Tyrell replaces Sansa as the king's betrothed.",
      "Theon's own men sack him; Winterfell burns behind them; Maester Luwin dies at the heart tree.",
      "Brienne and Jaime go south; Robb marries Talisa and breaks his word to Walder Frey.",
      "In the House of the Undying, Dany sees a ruined throne room and an empty Wall — and burns the warlock.",
      "The great ranging finds the army of the dead marching on the Fist of the First Men.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "qarth", note: "Dracarys. The vault of Qarth pays for its own greed." },
      { name: "Robb Stark", loc: "riverrun", note: "Marries for love; the toll on the bridge goes unpaid." },
      { name: "Theon Greyjoy", loc: "winterfell", note: "Rallied his men with a speech; they answered with a sack over his head." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Freed from Joffrey — into Littlefinger's orbit." },
      { name: "Jon Snow", loc: "fist-of-the-first-men", note: "Kills the Halfhand to buy a wildling's welcome." },
      { name: "Samwell Tarly", loc: "fist-of-the-first-men", note: "Three horn blasts. There is no fourth." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 4, targaryen: 3, tully: 5, arryn: 3, greyjoy: 4, frey: 4, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Maester Luwin", note: "Speared by ironborn at the heart tree; asked Osha for a quick mercy." },
      { name: "Qhorin Halfhand", note: "Made Jon kill him so the Watch would have a man inside." },
      { name: "Pyat Pree & Xaro Xhoan Daxos", note: "The warlock burned by three small dragons; the merchant sealed in his own empty vault." },
      { name: "Doreah", note: "Sealed in the vault beside the king she chose." },
    ] },
] },

// ==================== SEASON THREE ====================
{ n: 3, name: "Season Three", episodes: [
  { n: 1, title: "Valar Dohaeris",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "The survivors of the Fist stagger back to Craster's; Sam saw the dead — the Watch must warn the realm.",
      "Jon is brought before Mance Rayder and lies his way into the free folk.",
      "Tywin refuses Tyrion Casterly Rock in the cruelest speech a father ever gave.",
      "Margaery Tyrell feeds orphans in Flea Bottom and the city notices the difference.",
      "In Astapor, Dany inspects the Unsullied while a warlock's child nearly kills her.",
    ],
    people: [
      { name: "Jon Snow", loc: "the-wall", note: "Kneels to the King-Beyond-the-Wall with a story that must hold." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Asks for his birthright; is told he is an ill-made, spiteful creature." },
      { name: "Daenerys Targaryen", loc: "old-ghis", note: "An army that feels no pain, for a price she won't name yet." },
      { name: "Davos Seaworth", loc: "dragonstone", note: "Survives the bay to find his king in a red woman's shadow." },
      { name: "Margaery Tyrell", loc: "kings-landing", note: "Wins the capital one orphanage at a time." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 3, targaryen: 3, tully: 5, arryn: 3, greyjoy: 4, frey: 4, tyrell: 7, martell: 5 },
    deaths: [] },
  { n: 2, title: "Dark Wings, Dark Words",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Bran meets Jojen and Meera Reed, and learns the word for what he is: warg.",
      "Arya's band is picked up by the Brotherhood Without Banners — and the Hound names her.",
      "Brienne and Jaime cross swords on a bridge and lose to Locke's men.",
      "Sansa tells the Tyrells the truth about Joffrey: he is a monster.",
    ],
    people: [
      { name: "Bran Stark", loc: "winterfell", note: "The three-eyed raven has a name now, and a direction: north." },
      { name: "Arya Stark", loc: "riverrun", note: "Outed by the Hound in a cave full of outlaws." },
      { name: "Jaime Lannister", loc: "harrenhal", note: "Fought a woman to a standstill; chained beside her by nightfall." },
      { name: "Sansa Stark", loc: "kings-landing", note: "One honest sentence, spoken to the only people who asked." },
      { name: "Margaery Tyrell", loc: "kings-landing", note: "Handles a monster the way his mother never learned." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 3, targaryen: 3, tully: 5, arryn: 3, greyjoy: 4, frey: 4, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Hoster Tully", note: "Lord of Riverrun, dead of age as war filled his rivers." },
    ] },
  { n: 3, title: "Walk of Punishment",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Riverrun sends Lord Hoster down the river burning; Edmure can't hit the boat.",
      "Robb's uncle Brynden takes command of the Tully host in all but name.",
      "Tywin makes Tyrion master of coin — a punishment dressed as promotion.",
      "Dany offers a dragon for eight thousand Unsullied; Jorah and Barristan protest in unison.",
      "Locke tires of Jaime's talking and takes his sword hand off at the wrist.",
    ],
    people: [
      { name: "Jaime Lannister", loc: "harrenhal", note: "Saved Brienne with a lie; paid for it with a hand." },
      { name: "Daenerys Targaryen", loc: "old-ghis", note: "A dragon is not a slave. But the slavers don't know that yet." },
      { name: "Edmure Tully", loc: "riverrun", note: "Four arrows, three misses, one uncle out of patience." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Inherits ledgers that say the crown is drowning in debt." },
      { name: "Brienne of Tarth", loc: "harrenhal", note: "Survives the night because a Lannister lied for her." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 3, targaryen: 4, tully: 5, arryn: 3, greyjoy: 4, frey: 4, tyrell: 7, martell: 5 },
    deaths: [] },
  { n: 4, title: "And Now His Watch Is Ended",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "At Craster's, the Watch turns on itself: mutineers kill their host and their Lord Commander.",
      "Varys reveals what was in the box the sorcerer sent him — and who is in his crate now.",
      "The Tyrells plot Sansa's marriage to Loras; Littlefinger's ship for her waits anyway.",
      "In Astapor: 'Dracarys.' The Unsullied are hers, the masters are ash, and the whip is on the ground.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "old-ghis", note: "Bought an army with a dragon, then took the dragon back." },
      { name: "Samwell Tarly", loc: "crasters-keep", note: "Runs into the night with Gilly and her newborn son." },
      { name: "Varys", loc: "kings-landing", note: "Patience measured in decades, revenge measured in crates." },
      { name: "Margaery Tyrell", loc: "kings-landing", note: "Teaches Joffrey to wave at the crowd she bought for him." },
      { name: "Theon Greyjoy", loc: "the-dreadfort", note: "Led in circles by a smiling boy back to the same cross." },
    ],
    power: { stark: 6, lannister: 9, baratheon: 3, targaryen: 6, tully: 5, arryn: 3, greyjoy: 4, frey: 4, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Lord Commander Jeor Mormont", note: "Stabbed in the back by his own sworn brothers at Craster's Keep." },
      { name: "Craster", note: "A guest-right death for the man who fed his sons to the cold." },
      { name: "Kraznys mo Nakloz & the Good Masters", note: "Astapor's slavers, unmade by the army they sold and the dragon they thought they'd bought." },
    ] },
  { n: 5, title: "Kissed by Fire",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "The Hound fights Beric Dondarrion's flaming sword — and Beric dies. Then gets up. Again.",
      "Jon and Ygritte find a cave; his vows lose a clause.",
      "Rickard Karstark murders two Lannister squires in their cells; Robb takes his head and half his army.",
      "Jaime, feverish in a bath, tells Brienne why the Mad King's blood is on his white cloak.",
      "Tywin arranges two weddings: Sansa for Tyrion, Loras for Cersei. No one at that table is happy.",
    ],
    people: [
      { name: "Robb Stark", loc: "riverrun", note: "Justice cost him the Karstarks; only one bridge can save the campaign." },
      { name: "Jaime Lannister", loc: "harrenhal", note: "\"By what right does the wolf judge the lion?\"" },
      { name: "Jon Snow", loc: "the-wall", note: "Kissed by fire, in a cave he'll wish he never left." },
      { name: "Arya Stark", loc: "stoney-sept", note: "Watches a dead man rise for the sixth time." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Learns his wedding is a battlefield his father chose." },
    ],
    power: { stark: 5, lannister: 9, baratheon: 3, targaryen: 6, tully: 5, arryn: 3, greyjoy: 4, frey: 4, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Willem & Martyn Lannister", note: "Boy squires, murdered in their cells by Lord Karstark's grief." },
      { name: "Lord Rickard Karstark", note: "Beheaded by the king he cursed — who lost the war doing the right thing." },
    ] },
  { n: 6, title: "The Climb",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Jon and the free folk climb the Wall; the ice sheds climbers like flies.",
      "Walder Frey's price arrives at Riverrun: an apology, Harrenhal, and Edmure at the altar.",
      "Littlefinger wins the Vale-sized game with Varys and ships Ros to Joffrey's crossbow.",
      "\"Chaos is a ladder.\"",
    ],
    people: [
      { name: "Jon Snow", loc: "the-wall", note: "Seven hundred feet of ice; the top is worth the fall." },
      { name: "Ygritte", loc: "the-wall", note: "Knows his cloak is still black — and climbs with him anyway." },
      { name: "Robb Stark", loc: "riverrun", note: "The Freys will have their wedding after all. Edmure pays the toll." },
      { name: "Petyr Baelish", loc: "kings-landing", note: "The ladder is all there is." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Watches her ship to safety sail without her." },
    ],
    power: { stark: 5, lannister: 9, baratheon: 3, targaryen: 6, tully: 5, arryn: 3, greyjoy: 4, frey: 5, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Ros", note: "Sold by Littlefinger to a king who wanted a moving target." },
    ] },
  { n: 7, title: "The Bear and the Maiden Fair",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Dany reaches Yunkai and raises the stakes: free every slave, or be the first city she breaks.",
      "Jaime, freed for King's Landing, turns his escort around for Brienne — and jumps into a bear pit with no hand.",
      "Robb's queen is pregnant; the North marches for the Twins and a wedding.",
      "Theon learns what his smiling keeper actually wants from him. Everything.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "yunkai", note: "The Yellow City's envoy leaves without his gold and without his slaves." },
      { name: "Jaime Lannister", loc: "harrenhal", note: "One-handed, unarmored, between a bear and a maiden fair." },
      { name: "Brienne of Tarth", loc: "harrenhal", note: "A tourney sword against a bear; help arrives all the same." },
      { name: "Robb Stark", loc: "riverrun", note: "A son on the way and one wedding between him and home." },
      { name: "Melisandre", loc: "dragonstone", note: "Sails a king's blood up the coast: a bastard named Gendry." },
    ],
    power: { stark: 5, lannister: 9, baratheon: 3, targaryen: 6, tully: 5, arryn: 3, greyjoy: 4, frey: 5, tyrell: 7, martell: 5 },
    deaths: [] },
  { n: 8, title: "Second Sons",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Yunkai hires the Second Sons; their captains debate killing Dany; one of them delivers his officers' heads instead.",
      "Sansa Stark weds Tyrion Lannister; Joffrey removes the groom's stool; the bedding does not happen.",
      "Melisandre leeches king's blood from Gendry over three names: Robb Stark. Balon Greyjoy. Joffrey Baratheon.",
      "Sam kills a White Walker with a dragonglass dagger and doesn't stop running to think about it.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "yunkai", note: "Gains a sellsword captain with flexible loyalties: Daario Naharis." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Threatens to geld his king at his own wedding feast. Worth it." },
      { name: "Sansa Stark", loc: "kings-landing", note: "A Lannister cloak on her shoulders she never asked for." },
      { name: "Samwell Tarly", loc: "the-wall", note: "Sam the Slayer, though no one will believe it." },
      { name: "Stannis Baratheon", loc: "dragonstone", note: "Three leeches in a fire, three kings named." },
    ],
    power: { stark: 5, lannister: 9, baratheon: 3, targaryen: 7, tully: 5, arryn: 3, greyjoy: 4, frey: 5, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Mero, the Titan's Bastard", note: "Captain of the Second Sons, his head brought to Dany as a courting gift." },
    ] },
  { n: 9, title: "The Rains of Castamere",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "The Twins host a wedding; Walder Frey serves bread and salt; the doors close.",
      "The band plays the Rains of Castamere, and the Freys and Boltons do the Lannisters' work.",
      "Talisa, Robb, Catelyn, Grey Wind — the King in the North falls with his kingdom.",
      "Arya arrives minutes too late; the Hound carries her from the slaughter.",
      "Bran wargs Hodor at the Gift while Jon breaks from the wildlings below.",
    ],
    people: [
      { name: "Robb Stark", loc: "the-twins", note: "\"Mother.\" The last word of the King in the North." },
      { name: "Catelyn Stark", loc: "the-twins", note: "One hostage, one plea, one scream — then silence." },
      { name: "Arya Stark", loc: "the-twins", note: "Close enough to hear the music change." },
      { name: "Jon Snow", loc: "queenscrown", note: "Refuses the last test; flees to the Wall full of arrows." },
      { name: "Bran Stark", loc: "queenscrown", note: "Enters Hodor's mind to still him — a thing no one has done." },
    ],
    power: { stark: 2, lannister: 9, baratheon: 3, targaryen: 7, tully: 3, arryn: 3, greyjoy: 4, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Robb Stark, King in the North", note: "Crossbow bolts and Roose Bolton's knife: \"The Lannisters send their regards.\"" },
      { name: "Queen Talisa Stark", note: "Stabbed first, and where it would hurt Robb most." },
      { name: "Catelyn Stark", note: "Her throat cut at her son's wedding feast, one grief too late." },
      { name: "Grey Wind", note: "Robb's direwolf, shot in a pen — his head sewn to his king's body." },
      { name: "Joyeuse Erenford & the northern host", note: "The blood of the Red Wedding runs far past the named." },
    ] },
  { n: 10, title: "Mhysa",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Roose Bolton is Warden of the North; Walder Frey washes his hands and his floors.",
      "The smiling boy has a name — Ramsay Snow — and Theon has a new one: Reek.",
      "Joffrey crows about serving Robb's head at his wedding; Tywin sends him to bed without supper.",
      "Sam gives Bran dragonglass and watches him go under the Wall, north.",
      "Yunkai's freedmen call Dany Mhysa — Mother — and carry her on their hands.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "yunkai", note: "Not a queen to them yet. Something more dangerous: a mother." },
      { name: "Arya Stark", loc: "the-twins", note: "Her first man dead for mocking her mother's corpse. Valar morghulis." },
      { name: "Jon Snow", loc: "castle-black", note: "Three arrows from the woman he loved; home is the Wall now." },
      { name: "Theon Greyjoy", loc: "the-dreadfort", note: "Reek. It rhymes with weak." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "\"The north will never forget.\" He's the only one who understands that." },
    ],
    power: { stark: 2, lannister: 9, baratheon: 3, targaryen: 7, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [] },
] },

// ==================== SEASON FOUR ====================
{ n: 4, name: "Season Four", episodes: [
  { n: 1, title: "Two Swords",
    throne: { king: "Joffrey I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Ice, Ned Stark's greatsword, is melted down into two Lannister blades.",
      "Prince Oberyn Martell arrives for the royal wedding with a grudge older than the king.",
      "Jaime returns one-handed to a sister who finds him changed and a father who finds him useless.",
      "Arya takes Needle back from Polliver, and crosses the first name off in person.",
    ],
    people: [
      { name: "Oberyn Martell", loc: "kings-landing", note: "\"The Lannisters aren't the only ones who pay their debts.\"" },
      { name: "Arya Stark", loc: "crossroads-inn", note: "Reclaims Needle the way it was taken: through a throat." },
      { name: "Jaime Lannister", loc: "kings-landing", note: "A golden hand and no place that fits the man attached to it." },
      { name: "Daenerys Targaryen", loc: "yunkai", note: "Marches on Meereen past a mile-markers of crucified children." },
      { name: "Jon Snow", loc: "castle-black", note: "On trial for oath-breaking; saved by telling the whole truth." },
    ],
    power: { stark: 2, lannister: 9, baratheon: 3, targaryen: 7, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Polliver", note: "Killed with the sword he stole, exactly the way he used it on Lommy." },
    ] },
  { n: 2, title: "The Lion and the Rose",
    throne: { king: "Joffrey I Baratheon †, then Tommen I", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "The royal wedding: dwarf jousters, a pie, and a king who humiliates his uncle one last time.",
      "Joffrey drinks, chokes, and dies purple in his mother's arms.",
      "Cersei points at Tyrion; the wine bearer is arrested on the spot.",
      "Sansa vanishes from the feast on Ser Dontos's arm.",
      "At the Dreadfort, Ramsay hunts a girl with hounds and shows his father what's left of Theon.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Handed the cup; wearing the chains by nightfall." },
      { name: "Sansa Stark", loc: "kings-landing", note: "Free of the lion's den at the worst possible moment." },
      { name: "Margaery Tyrell", loc: "kings-landing", note: "Queen for the length of a feast." },
      { name: "Ramsay Snow", loc: "the-dreadfort", note: "A bastard with his father's coldness and none of his restraint." },
      { name: "Olenna Tyrell", loc: "kings-landing", note: "Adjusts a necklace, tuts at violence, misses nothing." },
    ],
    power: { stark: 2, lannister: 9, baratheon: 3, targaryen: 7, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "King Joffrey I Baratheon", note: "Poisoned at his own wedding feast — the Strangler, in a cup poured by fate and Olenna Tyrell." },
      { name: "Ser Dontos Hollard", note: "Silenced with three bolts once his ferrying was done." },
    ] },
  { n: 3, title: "Breaker of Chains",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Littlefinger spirits Sansa to sea; the necklace stone was the poison all along.",
      "Tywin begins schooling Tommen on what makes a good king — beside Joffrey's corpse.",
      "The Hound robs a farmer who sheltered them; Arya adds it to a different kind of list.",
      "Meereen sends a champion; Daario opens him like a wine skin, and Dany catapults broken chains over the walls.",
    ],
    people: [
      { name: "Sansa Stark", loc: "the-eyrie", note: "Saved by the man who profits most from saving her." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Speaks to the slaves of Meereen, not their masters." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "In a cell for the one murder in Westeros he didn't do." },
      { name: "Arya Stark", loc: "riverrun", note: "Learns the Hound's philosophy: dead men don't need silver." },
      { name: "Samwell Tarly", loc: "castle-black", note: "Moves Gilly to Mole's Town and regrets it immediately." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 3, targaryen: 7, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [] },
  { n: 4, title: "Oathkeeper",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Meereen rises from within; the Great Masters are nailed up as answer to the children on the road.",
      "Jaime gives Brienne his Valyrian sword and a quest: find Sansa, keep her safe. She names it Oathkeeper.",
      "The Night's Watch mutineers at Craster's drink from the Old Bear's skull; Bran's party stumbles into them.",
      "Beyond it all, a White Walker carries Craster's last son to a cold altar — and blue eyes open.",
    ],
    people: [
      { name: "Brienne of Tarth", loc: "kings-landing", note: "Rides out with a Valyrian blade, new armor, and Podrick Payne." },
      { name: "Jaime Lannister", loc: "kings-landing", note: "Keeps one oath by proxy: the Stark girls." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Answers crucifixion with crucifixion; mercy loses the vote." },
      { name: "Bran Stark", loc: "crasters-keep", note: "Caught by mutineers with his secret one warg away." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Grief distilled into a single demand: her brother's head." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 3, targaryen: 8, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "The Great Masters of Meereen", note: "One hundred and sixty-three, nailed along their own harbor promenade." },
    ] },
  { n: 5, title: "First of His Name",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Tommen is crowned; Margaery starts on husband number three; Cersei plays nice with everyone she hates.",
      "Lysa Arryn marries Littlefinger within the hour of his arrival — and shrieks the truth of Jon Arryn's murder.",
      "Dany learns Astapor and Yunkai have fallen back to old ways, and decides to stay: a queen rules.",
      "Jon storms Craster's Keep; Locke dies with a snapped neck; Bran wargs Hodor for the second time and slips away north.",
    ],
    people: [
      { name: "Sansa Stark", loc: "the-eyrie", note: "Her aunt's welcome curdles between the soup and the sweets." },
      { name: "Petyr Baelish", loc: "the-eyrie", note: "The whole war, it turns out, started with his lie and Lysa's letter." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "\"I will do what queens do. I will rule.\"" },
      { name: "Jon Snow", loc: "crasters-keep", note: "Burns the keep and buries the Watch's shame." },
      { name: "Bran Stark", loc: "crasters-keep", note: "So close to Jon he could call out — and can't afford to." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 3, targaryen: 8, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Karl Fogg & the mutineers", note: "The self-styled Lord of Craster's Keep, a sword through the back of the skull." },
      { name: "Locke", note: "Bolton's hand-taker, his neck snapped by a stableboy who wasn't a stableboy." },
    ] },
  { n: 6, title: "The Laws of Gods and Men",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Stannis and Davos ask the Iron Bank for gold; the ledger votes Stannis.",
      "Yara raids the Dreadfort for Theon and finds Reek in a kennel who won't come.",
      "Tyrion's trial is theater with a script; Shae's testimony is the cruelest line.",
      "\"I demand a trial by combat.\" The dwarf declines the script.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "kings-landing", note: "\"I wish I had enough poison for the whole pack of you.\"" },
      { name: "Yara Greyjoy", loc: "the-dreadfort", note: "Came for a brother; left without one. \"My brother is dead.\"" },
      { name: "Stannis Baratheon", loc: "braavos", note: "The Iron Bank backs grim arithmetic over golden promises." },
      { name: "Davos Seaworth", loc: "braavos", note: "Four missing fingertips make his best argument." },
      { name: "Ramsay Snow", loc: "the-dreadfort", note: "His hounds and his creature hold off thirty ironborn." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 4, targaryen: 8, tully: 2, arryn: 3, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [] },
  { n: 7, title: "Mockingbird",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Cersei names her champion: Ser Gregor Clegane. The Mountain.",
      "Jaime can't fight, Bronn won't die for free — and Oberyn Martell volunteers, for reasons carved in Elia's name.",
      "The Hound takes a bite for a dying farmer's mercy; Arya finishes it cleanly.",
      "Lysa sees a kiss in the snow and holds Sansa over the Moon Door; Littlefinger holds Lysa over it longer.",
    ],
    people: [
      { name: "Oberyn Martell", loc: "kings-landing", note: "\"I will be your champion.\" The viper picks the fight he came for." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Laughs in his cell: fate sent him a Dornishman." },
      { name: "Sansa Stark", loc: "the-eyrie", note: "Six hundred feet of open air beneath her aunt's grip." },
      { name: "Petyr Baelish", loc: "the-eyrie", note: "\"Only Cat.\" And the Moon Door swallows a jealous heart." },
      { name: "Arya Stark", loc: "stoney-sept", note: "Learns where the heart is, and uses the lesson within the hour." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 4, targaryen: 8, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 7, martell: 5 },
    deaths: [
      { name: "Lysa Arryn", note: "Sent through her own Moon Door by the man she killed her husband for." },
    ] },
  { n: 8, title: "The Mountain and the Viper",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Mole's Town falls to the wildlings; Ygritte spares Gilly and the babe.",
      "Ser Barristan hands Jorah a royal pardon signed by Robert Baratheon: the spying is out; Dany exiles him.",
      "Sansa lies for Littlefinger at the inquest — and descends the Eyrie's stairs a different creature.",
      "The Viper dances, wins, demands a confession — and the Mountain's thumbs answer for Elia Martell.",
    ],
    people: [
      { name: "Oberyn Martell", loc: "kings-landing", note: "\"Say her name!\" He needed the words more than the win." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "His life rode on a man who wouldn't step back." },
      { name: "Sansa Stark", loc: "the-eyrie", note: "Dyes her hair dark and stops waiting to be rescued." },
      { name: "Jorah Mormont", loc: "meereen", note: "One old parchment undoes years of penance." },
      { name: "Ramsay Snow", loc: "moat-cailin", note: "Takes Moat Cailin with Reek's borrowed face — and earns the name Bolton." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 4, targaryen: 8, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 7, martell: 4 },
    deaths: [
      { name: "Prince Oberyn Martell", note: "The Red Viper of Dorne, his skull burst by the Mountain's hands a breath after victory." },
    ] },
  { n: 9, title: "The Watchers on the Wall",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister" },
    events: [
      "Mance's hundred thousand hit the Wall from both sides in one night.",
      "Giants and mammoths breach the outer gate; six brothers hold the inner tunnel and die keeping it.",
      "Slynt hides; Jon takes command; the scythe clears the climbers off the ice.",
      "Ygritte dies in Jon's arms with the only true thing either ever said: you know nothing.",
      "Dawn: the Watch stands, barely. Jon walks north alone to kill Mance Rayder.",
    ],
    people: [
      { name: "Jon Snow", loc: "castle-black", note: "Commands the Wall the night it almost fell." },
      { name: "Ygritte", loc: "castle-black", note: "Dies kissed by fire, in the wrong castle, in the right arms." },
      { name: "Samwell Tarly", loc: "castle-black", note: "Kills a Thenn and finds his courage isn't missing after all." },
      { name: "Alliser Thorne", loc: "castle-black", note: "Wrong about everything except how to hold a gate." },
      { name: "Tormund Giantsbane", loc: "castle-black", note: "Taken alive, still shouting." },
    ],
    power: { stark: 2, lannister: 8, baratheon: 4, targaryen: 8, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 7, martell: 4 },
    deaths: [
      { name: "Ygritte", note: "An arrow from the boy Olly — her bow still trained on Jon Snow." },
      { name: "Grenn", note: "Held the inner gate against a giant with five brothers, reciting their vows." },
      { name: "Pyp", note: "An arrow through the throat, dying surprised in Sam's arms." },
      { name: "Styr, Magnar of Thenn", note: "A hammer buried in his skull by Jon Snow." },
      { name: "Mag the Mighty", note: "Last of the giant kings, dead in the tunnel with Grenn's dead hands on him." },
    ] },
  { n: 10, title: "The Children",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Lord Tywin Lannister †" },
    events: [
      "Stannis's cavalry breaks the wildling camp; Mance yields; the debt to the realm is paid at the Wall.",
      "Bran reaches the heart tree; Jojen dies at its roots; the Three-Eyed Raven waits below.",
      "Dany chains Rhaegal and Viserion after Drogon burns a child; the mother locks up her children.",
      "Brienne and the Hound fight over Arya; Arya leaves him begging for mercy she won't give — and sails for Braavos.",
      "Tyrion, freed by Jaime, finds Shae in his father's bed and Tywin on his privy. The crossbow speaks twice.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "kings-landing", note: "\"I am your son. I have always been your son.\" Then the bolt." },
      { name: "Arya Stark", loc: "braavos", note: "\"Valar morghulis.\" The coin buys a ship north to a new god." },
      { name: "Stannis Baratheon", loc: "castle-black", note: "The only king who answered the Watch's call." },
      { name: "Bran Stark", loc: "crasters-keep", note: "\"You will never walk again. But you will fly.\"" },
      { name: "Daenerys Targaryen", loc: "meereen", note: "The catacombs close on two dragons crying for their mother." },
    ],
    power: { stark: 3, lannister: 7, baratheon: 5, targaryen: 7, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 7, martell: 4 },
    deaths: [
      { name: "Lord Tywin Lannister", note: "Hand of the King, shot on his privy by the son he sentenced to die." },
      { name: "Shae", note: "Strangled with the golden chain she wore in another man's bed." },
      { name: "Jojen Reed", note: "Stabbed by a wight at the very door of the Three-Eyed Raven." },
      { name: "Sandor Clegane", note: "Broken by Brienne and left begging for death on a stony bluff — presumed." },
    ] },
] },

// ==================== SEASON FIVE ====================
{ n: 5, name: "Season Five", episodes: [
  { n: 1, title: "The Wars to Come",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant — the lion's council is leaderless" },
    events: [
      "Tywin lies in the sept; Cersei's childhood prophecy — younger, more beautiful, three children, gold shrouds — lies with him.",
      "Tyrion arrives in Pentos in a crate; Varys offers him a queen worth serving.",
      "In Meereen, the Sons of the Harpy begin murdering from the shadows.",
      "Stannis offers Mance Rayder his life for a knee; Mance chooses the fire, and Jon's arrow ends it early.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "pentos", note: "Drinks his way across the sea toward a reason to live." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "The valonqar prophecy has her counting brothers." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Gold masks in the alleys; her city stabs from behind." },
      { name: "Jon Snow", loc: "castle-black", note: "One arrow of mercy that Stannis reads as defiance." },
      { name: "Varys", loc: "pentos", note: "\"A ruler who is loved... you'll never make one out of Cersei.\"" },
    ],
    power: { stark: 3, lannister: 6, baratheon: 5, targaryen: 7, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 6, martell: 4 },
    deaths: [
      { name: "Mance Rayder", note: "The King-Beyond-the-Wall, burned by Stannis — spared the worst by Jon's arrow." },
      { name: "White Rat", note: "An Unsullied, first blood of the Sons of the Harpy." },
    ] },
  { n: 2, title: "The House of Black and White",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Arya reaches Braavos and a door of ebony and weirwood that won't open — until it does, on a familiar face.",
      "Brienne finds Sansa at an inn with Littlefinger; her oath is refused a second time.",
      "Dorne mourns Oberyn; Ellaria wants war on children; Doran wants proof and patience.",
      "Dany executes a freedman for murdering a captive Harpy — and Meereen hisses at its queen.",
    ],
    people: [
      { name: "Arya Stark", loc: "braavos", note: "\"Valar dohaeris.\" Jaqen's face was never Jaqen's." },
      { name: "Brienne of Tarth", loc: "the-eyrie", note: "Two Stark girls, two refusals — the oath holds anyway." },
      { name: "Sansa Stark", loc: "moat-cailin", note: "Chooses the devil who talks over the stranger who swears." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Justice for all turns out to please no one." },
      { name: "Jaime Lannister", loc: "kings-landing", note: "A secret mission to Dorne, with Bronn as the entire army." },
    ],
    power: { stark: 3, lannister: 6, baratheon: 5, targaryen: 7, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 6, martell: 4 },
    deaths: [
      { name: "Mossador", note: "Freedman of Meereen, beheaded by the queen he loved for a murder he called justice." },
    ] },
  { n: 3, title: "High Sparrow",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Tommen weds Margaery; the new queen sweetly suggests his mother might prefer Casterly Rock.",
      "Cersei meets the High Sparrow in a soup kitchen and mistakes a fanatic for a tool.",
      "Littlefinger's plan lands: Sansa Stark will marry Ramsay Bolton, in Winterfell.",
      "Jon Snow, elected Lord Commander, gives Janos Slynt one order — and then the sword.",
    ],
    people: [
      { name: "Sansa Stark", loc: "winterfell", note: "Home again, as a bride in the house of her family's butchers." },
      { name: "Jon Snow", loc: "castle-black", note: "First command met with defiance; defiance met with Longclaw." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Arms the Faith to spite a girl; hands a zealot a sword." },
      { name: "Arya Stark", loc: "braavos", note: "Sweeps floors while Needle sleeps under the stones." },
      { name: "Petyr Baelish", loc: "winterfell", note: "Sells Sansa north the way he sells everything: smiling." },
    ],
    power: { stark: 3, lannister: 6, baratheon: 5, targaryen: 7, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 6, martell: 4 },
    deaths: [
      { name: "Janos Slynt", note: "\"I'm afraid. I've always been afraid.\" Too late, at the block of the bastard he mocked." },
    ] },
  { n: 4, title: "Sons of the Harpy",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "The Faith Militant is reborn; Loras Tyrell is seized for his sins; Tommen bounces off the steps of the sept.",
      "Melisandre tempts Jon; Stannis explains greyscale to Shireen the only way he can: I fought for you.",
      "Jaime and Bronn wade ashore in Dorne; the Sand Snakes vote for war with a burial.",
      "The Harpies ambush the Unsullied in the tunnels; Grey Worm falls wounded; Barristan the Bold falls forever.",
    ],
    people: [
      { name: "Barristan Selmy", loc: "meereen", note: "The Bold, dying as he lived: outnumbered and unyielding." },
      { name: "Margaery Tyrell", loc: "kings-landing", note: "Her brother in a cell; her husband too gentle to open it." },
      { name: "Jaime Lannister", loc: "sunspear", note: "In Dorne with one hand and one friend, for his 'niece'." },
      { name: "Stannis Baratheon", loc: "castle-black", note: "The stone doctors said to give up on Shireen. He didn't." },
      { name: "Ellaria Sand", loc: "sunspear", note: "Wants a war Doran won't give her; recruits Oberyn's daughters." },
    ],
    power: { stark: 3, lannister: 5, baratheon: 5, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 5, martell: 4 },
    deaths: [
      { name: "Ser Barristan Selmy", note: "Barristan the Bold, cut down by masked cowards in a Meereenese alley." },
    ] },
  { n: 5, title: "Kill the Boy",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Dany feeds a Master to her dragons on suspicion — then reopens the fighting pits and offers marriage to Hizdahr.",
      "Jon makes the hardest call of his command: the free folk come south of the Wall.",
      "Stannis marches from Castle Black for Winterfell, family and red woman in train.",
      "Tyrion and Jorah sail through ruined Valyria, past stone men — and one grabs the dwarf.",
    ],
    people: [
      { name: "Jon Snow", loc: "castle-black", note: "\"Kill the boy, and let the man be born.\" — Maester Aemon" },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Fear and marriage, tried in the same week." },
      { name: "Tyrion Lannister", loc: "valyria", note: "Quotes poetry through the Doom until the stone men drop." },
      { name: "Jorah Mormont", loc: "valyria", note: "Pulls Tyrion from the water; hides a grey patch on his wrist." },
      { name: "Sansa Stark", loc: "winterfell", note: "Ramsay's kindness is a knife shown slowly." },
    ],
    power: { stark: 3, lannister: 5, baratheon: 5, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 5, martell: 4 },
    deaths: [] },
  { n: 6, title: "Unbowed, Unbent, Unbroken",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Arya passes her first test in the House of Black and White and is given a face-lined cellar instead of answers.",
      "Jaime and the Sand Snakes reach Myrcella at the same moment; Areo Hotah's axe ends the scuffle.",
      "Olenna Tyrell returns for her grandchildren; the Sparrow quotes scripture back at her.",
      "Sansa's wedding night in Winterfell — Ramsay makes Theon watch. The North's walls hear it.",
    ],
    people: [
      { name: "Sansa Stark", loc: "winterfell", note: "Unbowed and unbroken will have to wait. She survives." },
      { name: "Arya Stark", loc: "braavos", note: "A girl gives a dying child water and mercy in the same cup." },
      { name: "Olenna Tyrell", loc: "kings-landing", note: "For once, the Queen of Thorns meets a man with nothing to buy." },
      { name: "Jaime Lannister", loc: "sunspear", note: "A rescue that arrests itself in the Water Gardens." },
      { name: "Tyrion Lannister", loc: "old-ghis", note: "Sold with Jorah to slavers; talks his way to the fighting pits." },
    ],
    power: { stark: 3, lannister: 5, baratheon: 5, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 4 },
    deaths: [] },
  { n: 7, title: "The Gift",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Jon rides for Hardhome; Maester Aemon dies at the Wall with Egg's name on his lips.",
      "Sansa begs Theon to light the signal candle; he carries the plea to Ramsay instead.",
      "Jorah's 'gift' to the queen in a Meereen pit is Tyrion Lannister, alive and bowing.",
      "Littlefinger hands Olenna a weapon, and Cersei walks into the sept as a guest — and stays as a prisoner.",
    ],
    people: [
      { name: "Tyrion Lannister", loc: "meereen", note: "\"I am the gift.\" The two cleverest exiles in the world finally meet." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Visits Margaery's cell to gloat; leaves in one of her own." },
      { name: "Sansa Stark", loc: "winterfell", note: "One candle in the broken tower — and the wrong man holding it." },
      { name: "Jon Snow", loc: "eastwatch-by-the-sea", note: "Sails for a fishing village full of the last free folk alive." },
      { name: "Olenna Tyrell", loc: "kings-landing", note: "Learns the sparrow serves neither gold nor thorns." },
    ],
    power: { stark: 3, lannister: 4, baratheon: 5, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 4 },
    deaths: [
      { name: "Maester Aemon Targaryen", note: "One hundred and two years old, the last dragon at the Wall, dreaming of his brother Egg." },
    ] },
  { n: 8, title: "Hardhome",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Dany takes Tyrion as advisor and sends Jorah away a second time.",
      "Arya becomes Lana of the oysters, cataloguing a thin man for the Many-Faced God.",
      "At Hardhome, five thousand free folk board boats — until the storm of the dead arrives.",
      "Jon kills a White Walker with Longclaw; the Night King raises the fallen with two slow arms.",
    ],
    people: [
      { name: "Jon Snow", loc: "hardhome", note: "Valyrian steel works. It's the only good news of the day." },
      { name: "Tormund Giantsbane", loc: "hardhome", note: "Beats the Lord of Bones to death with his own staff; the free folk listen." },
      { name: "Karsi", loc: "hardhome", note: "A chieftain who put her daughters on the boat first." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "\"I'm not going to stop the wheel. I'm going to break the wheel.\"" },
      { name: "Tyrion Lannister", loc: "meereen", note: "Advises a queen he just met to spare the man who kidnapped him." },
    ],
    power: { stark: 3, lannister: 4, baratheon: 5, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 4 },
    deaths: [
      { name: "Karsi", note: "Free folk chieftain, pulled down by dead children she couldn't raise a blade against — and raised herself." },
      { name: "The Lord of Bones", note: "Rattleshirt, beaten to death for calling Tormund a traitor." },
      { name: "Loboda", note: "Thenn warleader, dead holding the gate for the dragonglass no one saved." },
    ] },
  { n: 9, title: "The Dance of Dragons",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Ramsay's twenty men burn Stannis's camp; the march to Winterfell strands in snow and hunger.",
      "Stannis burns Shireen. The princess who taught men to read screams her father's name.",
      "Arya sees Meryn Trant in Braavos and abandons the thin man for an older prayer.",
      "In Daznak's Pit the Harpies spring their trap — and Drogon answers his mother's scream. She flies.",
    ],
    people: [
      { name: "Stannis Baratheon", loc: "winterfell", note: "Sacrificed the only person who loved him for a melted snowdrift." },
      { name: "Shireen Baratheon", loc: "winterfell", note: "\"I want to help.\" She never knew with what." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Leaves the pit on dragonback — the first Targaryen to fly in a century." },
      { name: "Arya Stark", loc: "braavos", note: "A name from her list walks into her city." },
      { name: "Doran Martell", loc: "sunspear", note: "Peace bought with a marriage pact and one bent knee." },
    ],
    power: { stark: 3, lannister: 4, baratheon: 4, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 4 },
    deaths: [
      { name: "Princess Shireen Baratheon", note: "Burned alive by her father's ambition and Melisandre's fire." },
      { name: "Hizdahr zo Loraq", note: "Dany's Meereenese fiancé, knifed in the pit by the Harpies he may not have led." },
    ] },
  { n: 10, title: "Mother's Mercy",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Vacant" },
    events: [
      "Stannis's host deserts; Brienne finally gets her sentence — and Ramsay's men get the field.",
      "Sansa and Theon jump from Winterfell's walls into the snow, hand in hand.",
      "Arya takes Meryn Trant's eyes and life; the Faceless Men take her sight for it.",
      "Cersei confesses, is shorn, and walks the city naked to the bells of 'Shame'.",
      "\"For the Watch.\" Olly's knife is the last of many; Jon Snow bleeds out in the snow.",
    ],
    people: [
      { name: "Jon Snow", loc: "castle-black", note: "Traitor's daggers from brothers he saved at Hardhome." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "A mile of stones, filth, and a name chanted like a bell." },
      { name: "Sansa Stark", loc: "winterfell", note: "The jump is not the frightening part anymore." },
      { name: "Arya Stark", loc: "braavos", note: "A girl took a life that wasn't hers to take. A girl is blind." },
      { name: "Daenerys Targaryen", loc: "vaes-dothrak", note: "Drogon's rest stop ends in a khalasar's circle." },
    ],
    power: { stark: 3, lannister: 5, baratheon: 1, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 4 },
    deaths: [
      { name: "Stannis Baratheon", note: "The rightful heir, executed by Brienne of Tarth against a tree, for Renly." },
      { name: "Queen Selyse Baratheon", note: "Hanged herself in the ruin of her daughter's pyre." },
      { name: "Ser Meryn Trant", note: "Blinded and bled by a girl whose dancing master he killed." },
      { name: "Myranda", note: "Ramsay's kennel-love, pushed from the walls by Theon's first free act." },
      { name: "Jon Snow, Lord Commander", note: "Stabbed by his own officers under a sign that read 'traitor'. For a time." },
    ] },
] },

// ==================== SEASON SIX ====================
{ n: 6, name: "Season Six", episodes: [
  { n: 1, title: "The Red Woman",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "Davos and the loyal few bar a door with Jon's body behind it; Ghost keeps watch.",
      "Sansa and Theon are run down in the snow — until Brienne's oath is finally accepted.",
      "In Dorne, Ellaria and the Sand Snakes murder Prince Doran, Areo Hotah, and Trystane: Dorne goes to war.",
      "Melisandre, alone, unclasps her necklace — and centuries look back from the mirror.",
    ],
    people: [
      { name: "Davos Seaworth", loc: "castle-black", note: "Holds a dead man's room against living traitors." },
      { name: "Brienne of Tarth", loc: "winterfell", note: "\"I swear that I shall always keep her secrets...\" Accepted, at last." },
      { name: "Sansa Stark", loc: "winterfell", note: "Says the oath's answer through frozen tears." },
      { name: "Ellaria Sand", loc: "sunspear", note: "\"Weak men will never rule Dorne again.\"" },
      { name: "Daenerys Targaryen", loc: "vaes-dothrak", note: "Marched to the city of the horselords as a khal's widow." },
    ],
    power: { stark: 3, lannister: 5, baratheon: 1, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 3 },
    deaths: [
      { name: "Prince Doran Martell", note: "Stabbed by Ellaria in his own gardens, his guards standing down." },
      { name: "Areo Hotah", note: "The captain of the guard, a knife in the back from a Sand Snake." },
      { name: "Prince Trystane Martell", note: "Killed by his cousins aboard ship — the Martell line all but ended." },
    ] },
  { n: 2, title: "Home",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "Bran, training with the Three-Eyed Raven, walks in a Winterfell where Hodor was Wylis and could speak.",
      "The wildlings take Castle Black without a fight; the mutineers go to the cells.",
      "Balon Greyjoy meets his brother Euron on a rope bridge in a storm — and only one walks off.",
      "Melisandre, faithless, tries one old spell. Ghost stirs. Jon Snow breathes.",
    ],
    people: [
      { name: "Jon Snow", loc: "castle-black", note: "Gasps awake on the table, remembering nothing after the knives." },
      { name: "Melisandre", loc: "castle-black", note: "Washed a corpse and whispered a prayer she no longer believed." },
      { name: "Bran Stark", loc: "winterfell", note: "The past is a place he can visit now. It will cost him." },
      { name: "Ramsay Bolton", loc: "winterfell", note: "A stepmother, a baby brother, and hungry hounds: heirs resolved." },
      { name: "Euron Greyjoy", loc: "pyke", note: "\"I am the storm, brother.\"" },
    ],
    power: { stark: 3, lannister: 5, baratheon: 1, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 3 },
    deaths: [
      { name: "Balon Greyjoy", note: "Last of the five kings, thrown from his own bridge by the brother he exiled." },
      { name: "Roose Bolton", note: "Warden of the North, hugged onto his bastard's dagger — as he taught him." },
      { name: "Walda Frey & her newborn son", note: "Fed to Ramsay's hounds within the hour of the boy's birth." },
    ] },
  { n: 3, title: "Oathbreaker",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "Jon hangs the four mutineers — Olly last — then lays down his cloak: \"My watch is ended.\"",
      "Bran watches young Ned at the Tower of Joy and hears his father lie about how the fight was won.",
      "Umbers deliver a gift to Ramsay: Osha, Rickon Stark, and the head of his direwolf.",
      "Arya, blind and beaten, finally answers \"a girl has no name\" like she means it — and drinks from the fountain.",
    ],
    people: [
      { name: "Jon Snow", loc: "castle-black", note: "His death released him from his vows. The letter of the law, kept." },
      { name: "Bran Stark", loc: "starfall", note: "\"Your father wasn't there.\" The past talks back." },
      { name: "Arya Stark", loc: "braavos", note: "Sight returned, on the day she stopped needing it." },
      { name: "Rickon Stark", loc: "winterfell", note: "The youngest wolf, handed to the cruelest master." },
      { name: "Daenerys Targaryen", loc: "vaes-dothrak", note: "Sentenced to the temple of the dosh khaleen — pending trial." },
    ],
    power: { stark: 3, lannister: 5, baratheon: 1, targaryen: 6, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 3 },
    deaths: [
      { name: "Shaggydog", note: "Rickon's direwolf, his head the Umbers' token of loyalty to Bolton." },
      { name: "Alliser Thorne, Olly & the mutineers", note: "Hanged at Castle Black by the man they murdered." },
    ] },
  { n: 4, title: "Book of the Stranger",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "Sansa reaches Castle Black: the first Stark reunion since Winterfell burned.",
      "Ramsay's letter demands Sansa and threatens Rickon; Jon reads it and stops saying no.",
      "Littlefinger returns to the Vale and aims its knights north.",
      "In Vaes Dothrak the khals debate Dany's fate; she burns the temple with them in it and walks out unburnt. Again.",
    ],
    people: [
      { name: "Sansa Stark", loc: "castle-black", note: "\"Where will we go?\" \"Home.\"" },
      { name: "Jon Snow", loc: "castle-black", note: "Tired of fighting — until his little brother becomes the stake." },
      { name: "Daenerys Targaryen", loc: "vaes-dothrak", note: "Every khal at once, and the door barred from outside." },
      { name: "Theon Greyjoy", loc: "pyke", note: "Comes home to back his sister's claim, not his own." },
      { name: "Tyrion Lannister", loc: "meereen", note: "Buys seven years' peace from the Masters; the freedmen call it betrayal." },
    ],
    power: { stark: 4, lannister: 5, baratheon: 1, targaryen: 7, tully: 2, arryn: 4, greyjoy: 3, frey: 6, tyrell: 4, martell: 3 },
    deaths: [
      { name: "Khal Moro and the great khals", note: "Burned in their own temple by the Unburnt; the khalasars knelt by dawn." },
      { name: "Osha", note: "The wildling who saved two Stark boys, a knife from Ramsay mid-sentence." },
    ] },
  { n: 5, title: "The Door",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "Sansa faces Littlefinger and names what his marriage bargain cost her.",
      "The kingsmoot crowns Euron; Yara and Theon steal the best ships of the Iron Fleet the same night.",
      "Bran, unsupervised, is touched by the Night King in a vision — and the cave's wards fail.",
      "The dead pour in. Summer dies, the Raven dies, Leaf dies — and Hodor holds the door as a boy's whole life collapses into one word.",
    ],
    people: [
      { name: "Bran Stark", loc: "crasters-keep", note: "Learned the price of the past: it can reach forward." },
      { name: "Hodor", loc: "crasters-keep", note: "Wylis, holding one door across forty years." },
      { name: "Sansa Stark", loc: "castle-black", note: "Made Littlefinger say out loud what he sold her into." },
      { name: "Yara Greyjoy", loc: "pyke", note: "Lost a crown by a shout; stole a fleet by dawn." },
      { name: "Euron Greyjoy", loc: "pyke", note: "Crowned dripping wet, planning a marriage with dragons in it." },
    ],
    power: { stark: 4, lannister: 5, baratheon: 1, targaryen: 7, tully: 2, arryn: 4, greyjoy: 4, frey: 6, tyrell: 4, martell: 3 },
    deaths: [
      { name: "Hodor", note: "Hold the door. Hold the door. Hodor." },
      { name: "Summer", note: "Bran's direwolf, dying so his boy could be dragged into the dark." },
      { name: "The Three-Eyed Raven", note: "A thousand years of watching, ended by an ice sword." },
      { name: "Leaf & the children of the forest", note: "The makers of the Night King, unmade by their making." },
    ] },
  { n: 6, title: "Blood of My Blood",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "A dead man in the woods saves Bran and Meera: uncle Benjen, half-wight, half-Watch.",
      "Sam takes Gilly to Horn Hill, meets his father's contempt, and leaves with the family sword.",
      "Margaery converts the crown to the Faith; Tommen fuses crown and church; Jaime is shipped to Riverrun.",
      "Arya saves the actress she was sent to kill; the Waif is given her death warrant.",
    ],
    people: [
      { name: "Samwell Tarly", loc: "horn-hill", note: "Took Heartsbane off the wall. His father can come and get it." },
      { name: "Arya Stark", loc: "braavos", note: "A girl is Arya Stark of Winterfell, and she is going home." },
      { name: "Benjen Stark", loc: "crasters-keep", note: "The First Ranger, back from the dead — mostly." },
      { name: "Margaery Tyrell", loc: "kings-landing", note: "Barefoot penitence as performance; the Sparrow can't tell." },
      { name: "Daenerys Targaryen", loc: "vaes-dothrak", note: "A hundred thousand riders, and a dragon overhead: the speech writes itself." },
    ],
    power: { stark: 4, lannister: 5, baratheon: 1, targaryen: 8, tully: 2, arryn: 4, greyjoy: 4, frey: 6, tyrell: 5, martell: 3 },
    deaths: [] },
  { n: 7, title: "The Broken Man",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "The Hound lives, swinging an axe for a septon's little commune — until the Brotherhood's rogues visit.",
      "Jon, Sansa and Davos recruit the North: Mormont's ten-year-old Lady Lyanna pledges her sixty-two.",
      "Jaime arrives at Riverrun to find the Blackfish holding it and Freys embarrassing themselves.",
      "Arya books passage home — and the Waif's knife finds her belly on a bridge.",
    ],
    people: [
      { name: "Sandor Clegane", loc: "stoney-sept", note: "Buried the only man who ever talked to him like a person." },
      { name: "Lyanna Mormont", loc: "winterfell", note: "Sixty-two soldiers, one unimpressed stare, zero patience." },
      { name: "Jaime Lannister", loc: "riverrun", note: "Parleys with the Blackfish and loses on style points." },
      { name: "Arya Stark", loc: "braavos", note: "Stabbed, swimming, bleeding out in a city of assassins." },
      { name: "Jon Snow", loc: "the-dreadfort", note: "Counting swords: the Boltons still have more." },
    ],
    power: { stark: 4, lannister: 5, baratheon: 1, targaryen: 8, tully: 3, arryn: 4, greyjoy: 4, frey: 5, tyrell: 5, martell: 3 },
    deaths: [
      { name: "Septon Ray", note: "The Hound's septon, hanged by rogue Brothers with his own words in his mouth." },
    ] },
  { n: 8, title: "No One",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "The Hound reclaims his axe two heads at a time; the Brotherhood offers him soup and a cause.",
      "Cersei chooses violence; the Mountain de-heads a Faith Militant; Tommen abolishes trial by combat.",
      "Jaime frees Edmure to take Riverrun bloodlessly; the Blackfish dies sword in hand, offstage and unbowed.",
      "The Waif hunts Arya through Braavos — into a dark cellar where a blind girl trained. Valar morghulis; a girl goes home.",
    ],
    people: [
      { name: "Arya Stark", loc: "braavos", note: "A girl is Arya Stark of Winterfell, and the House of Black and White lets her go." },
      { name: "Jaime Lannister", loc: "riverrun", note: "Took the unbreakable castle with a threat and a rowboat." },
      { name: "Brienne of Tarth", loc: "riverrun", note: "Failed to move the Blackfish; kept the sword and the mission." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Her trial's teeth pulled: no champion, no Mountain, no chance." },
      { name: "Tyrion Lannister", loc: "meereen", note: "The Masters' fleet arrives mid-toast; peace was rented, not bought." },
    ],
    power: { stark: 4, lannister: 5, baratheon: 1, targaryen: 8, tully: 2, arryn: 4, greyjoy: 4, frey: 5, tyrell: 5, martell: 3 },
    deaths: [
      { name: "Brynden \"Blackfish\" Tully", note: "Refused to yield his family's castle twice; died defending it sword in hand." },
      { name: "Lady Crane", note: "The actress who sheltered Arya, the Waif's parting cruelty." },
      { name: "The Waif", note: "Sent to kill a girl in the dark — where the blind girl had every advantage." },
      { name: "Lem Lemoncloak & the rogue Brothers", note: "Hanged by the Hound and the Brotherhood, two by axe-argument." },
    ] },
  { n: 9, title: "Battle of the Bastards",
    throne: { king: "Tommen I Baratheon", house: "baratheon", hand: "Ser Kevan Lannister" },
    events: [
      "Meereen: the Masters' fleet burns under three dragons; the siege ends in ash and terms.",
      "Yara and Theon reach Dany first: a hundred ships for an independent Iron Islands and no more reaving.",
      "Ramsay baits Jon with Rickon and a game of arrows; the trap closes exactly as Sansa warned.",
      "The Vale knights break the encirclement; Wun Wun breaks the gate; Sansa feeds Ramsay to his own hounds.",
    ],
    people: [
      { name: "Jon Snow", loc: "winterfell", note: "Buried alive under his own army and clawed back to the light." },
      { name: "Sansa Stark", loc: "winterfell", note: "Won the battle with a letter Jon never asked about." },
      { name: "Ramsay Bolton", loc: "winterfell", note: "\"My hounds will never harm me.\" Seven days unfed." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Three dragons over a burning bay; the Masters' terms invert." },
      { name: "Yara Greyjoy", loc: "meereen", note: "Two queens shake on a new world." },
    ],
    power: { stark: 6, lannister: 5, baratheon: 1, targaryen: 9, tully: 2, arryn: 5, greyjoy: 4, frey: 5, tyrell: 5, martell: 3 },
    deaths: [
      { name: "Rickon Stark", note: "The youngest wolf, an arrow in the back twenty yards from his brother." },
      { name: "Wun Wun", note: "The last giant south of the Wall, dying full of arrows with the gate behind him." },
      { name: "Ramsay Bolton", note: "Beaten by the bastard he mocked, eaten by the hounds he starved." },
    ] },
  { n: 10, title: "The Winds of Winter",
    throne: { king: "Tommen I Baratheon †, then Cersei I", house: "lannister", hand: "Qyburn (as Hand in all but name)" },
    events: [
      "The Great Sept of Baelor goes up in green fire with the Faith, the Tyrells, and Cersei's trial inside.",
      "Tommen steps from a window; the last of the prophecy's gold shrouds is used.",
      "Arya serves Walder Frey his sons in a pie, then his own throat.",
      "Bran sees the Tower of Joy's end: a boy named Aegon, a sister's promise. Lyanna's son wears Stark colors now.",
      "The North proclaims Jon the King in the North; Cersei takes the Iron Throne; Dany's armada finally sails west.",
    ],
    people: [
      { name: "Cersei Lannister", loc: "kings-landing", note: "Everything she feared to lose is gone; only the throne is left, so she takes it." },
      { name: "Arya Stark", loc: "the-twins", note: "\"The last thing you're ever going to see is a Stark smiling down at you.\"" },
      { name: "Jon Snow", loc: "winterfell", note: "The White Wolf, raised by acclamation he never sought." },
      { name: "Daenerys Targaryen", loc: "meereen", note: "Tyrion pinned as Hand; the horizon finally points home." },
      { name: "Bran Stark", loc: "the-wall", note: "Knows the realm's greatest secret and can tell no one yet." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 0, targaryen: 9, tully: 2, arryn: 5, greyjoy: 4, frey: 3, tyrell: 3, martell: 3 },
    deaths: [
      { name: "King Tommen I Baratheon", note: "The gentlest king, out a window after the sept took his queen and his faith." },
      { name: "Queen Margaery Tyrell", note: "Saw the trap before anyone; the Sparrow wouldn't open the doors." },
      { name: "The High Sparrow", note: "Vaporized mid-sermon by a cache of Aerys's wildfire." },
      { name: "Loras & Mace Tyrell", note: "The rose's heir and its lord, gone in the same green flash." },
      { name: "Ser Kevan Lannister & Grand Maester Pycelle", note: "The old regime, finished by wildfire and little birds." },
      { name: "Lancel Lannister", note: "Followed a candle into the dark and couldn't crawl fast enough." },
      { name: "Walder Frey", note: "His throat cut by a serving girl wearing someone else's face." },
      { name: "Lothar Frey & Black Walder", note: "Baked into the pie their father complimented." },
    ] },
] },

// ==================== SEASON SEVEN ====================
{ n: 7, name: "Season Seven", episodes: [
  { n: 1, title: "Dragonstone",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "A feast at the Twins: Walder Frey toasts his men with poisoned wine — worn by Arya Stark.",
      "Jon rules a wary North; Sansa argues for punishing turncloak houses; he refuses to punish children.",
      "Euron Greyjoy offers Cersei his fleet and promises a priceless gift.",
      "Daenerys Targaryen steps ashore at Dragonstone, touches the sand, and says: \"Shall we begin?\"",
    ],
    people: [
      { name: "Arya Stark", loc: "the-twins", note: "\"Winter came for House Frey.\"" },
      { name: "Daenerys Targaryen", loc: "dragonstone", note: "Home, one hundred and fifty years of exile later." },
      { name: "Jon Snow", loc: "winterfell", note: "Every quarrel with Sansa is fought in Littlefinger's hearing." },
      { name: "Cersei Lannister", loc: "kings-landing", note: "Paints the map of Westeros on a floor and stands on it alone." },
      { name: "Sandor Clegane", loc: "riverrun", note: "Buries the farmer he robbed, and mumbles half a prayer." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 9, tully: 2, arryn: 5, greyjoy: 4, frey: 1, tyrell: 3, martell: 3 },
    deaths: [
      { name: "The male line of House Frey", note: "Every Frey who mattered, in one toast: 'leave one wolf alive and the sheep are never safe.'" },
    ] },
  { n: 2, title: "Stormborn",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "Dany's war council divides the war: Dorne and Highgarden strangle King's Landing; the Unsullied take Casterly Rock.",
      "Sam risks his chains to cut the greyscale from Ser Jorah in a locked cell.",
      "Arya turns north at the crossroads — Winterfell, not King's Landing — and meets Nymeria's pack in the wood.",
      "Euron's fleet ambushes Yara's in the night: two Sand Snakes die, Ellaria and Yara are taken, Theon jumps.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "dragonstone", note: "\"Are you a sheep? No. You're a dragon. Be a dragon.\" — Olenna" },
      { name: "Arya Stark", loc: "crossroads-inn", note: "\"That's not you.\" She lets the wolf go, and goes home." },
      { name: "Samwell Tarly", loc: "oldtown", note: "Peels a knight like an onion because he knew his father." },
      { name: "Theon Greyjoy", loc: "pyke", note: "The sea took Reek back the moment the axes came out." },
      { name: "Euron Greyjoy", loc: "kings-landing", note: "Delivers his priceless gift with a rope and a grin." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 8, tully: 2, arryn: 5, greyjoy: 4, frey: 1, tyrell: 3, martell: 2 },
    deaths: [
      { name: "Obara & Nymeria Sand", note: "Killed with their own weapons on the deck of their burning fleet." },
    ] },
  { n: 3, title: "The Queen's Justice",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "Ice meets fire: Jon Snow stands before Daenerys and will not kneel — but leaves with dragonglass.",
      "Euron parades Ellaria and Tyene through the capital; Cersei repays a poisoned kiss in kind.",
      "The Unsullied take Casterly Rock and find it hollow — the Lannister army is at Highgarden.",
      "Olenna Tyrell drinks Jaime's painless poison and confesses to Joffrey with her last breath.",
    ],
    people: [
      { name: "Jon Snow", loc: "dragonstone", note: "\"I am not a king. I'm not a lord. I'm a shepherd of a dead army's warning.\"" },
      { name: "Daenerys Targaryen", loc: "dragonstone", note: "Two crowns in one room and neither will bend first." },
      { name: "Olenna Tyrell", loc: "highgarden", note: "\"Tell Cersei. I want her to know it was me.\"" },
      { name: "Cersei Lannister", loc: "kings-landing", note: "A kiss for a kiss: Tyene dies as Myrcella did." },
      { name: "Bran Stark", loc: "winterfell", note: "Home — but what came back isn't quite Bran." },
    ],
    power: { stark: 6, lannister: 8, baratheon: 1, targaryen: 7, tully: 2, arryn: 5, greyjoy: 4, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Lady Olenna Tyrell", note: "The Queen of Thorns, out-lived her house and chose her own exit — with one last thorn." },
      { name: "Tyene Sand", note: "Poisoned by Cersei with the Long Farewell, her mother chained to watch." },
    ] },
  { n: 4, title: "The Spoils of War",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "Arya comes home to Winterfell; the reunion is warm, the sparring with Brienne is warmer.",
      "Bran gives Littlefinger's own dagger a history lesson: \"Chaos is a ladder.\"",
      "Dany stops playing clever wars: Drogon and the Dothraki fall on the Lannister loot train.",
      "The Reach's gold is safe behind the walls — but the field becomes ash, and Jaime charges a dragon.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "kings-landing", note: "\"Dracarys\" at scale: the first Field of Fire in three hundred years." },
      { name: "Jaime Lannister", loc: "kings-landing", note: "One spear, one dragon, one lake — saved by Bronn's tackle." },
      { name: "Arya Stark", loc: "winterfell", note: "Duels Brienne to a smiling draw. \"Who taught you that?\" \"No one.\"" },
      { name: "Bran Stark", loc: "winterfell", note: "Hands Arya the Valyrian dagger meant to kill him." },
      { name: "Bronn", loc: "kings-landing", note: "Fires the scorpion, hits the dragon, saves the Kingslayer, keeps nothing." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 8, tully: 2, arryn: 5, greyjoy: 4, frey: 1, tyrell: 0, martell: 2 },
    deaths: [] },
  { n: 5, title: "Eastwatch",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "Dany offers the loot train survivors knees or death; the Tarlys choose fire, father and son.",
      "Jorah returns cured; Gendry returns rowed; Jon plans madness: capture a wight to convince two queens.",
      "Gilly reads past a footnote that unmarries Rhaegar Targaryen — and no one at the table hears it.",
      "The suicide squad walks out of Eastwatch's tunnel: a king, a smuggler, a hound, a brotherhood, and a bastard smith.",
    ],
    people: [
      { name: "Jon Snow", loc: "eastwatch-by-the-sea", note: "North again, hunting one dead man among a hundred thousand." },
      { name: "Daenerys Targaryen", loc: "dragonstone", note: "Two Tarlys refuse the knee; the dragon doesn't ask twice." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Smuggled into his sister's city to sell an armistice." },
      { name: "Gendry", loc: "kings-landing", note: "Still rowing — and swinging a warhammer like his father." },
      { name: "Samwell Tarly", loc: "oldtown", note: "Leaves the Citadel with its books and without its blessing." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 8, tully: 2, arryn: 5, greyjoy: 4, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Lord Randyll & Dickon Tarly", note: "Refused the foreign queen's knee together; burned together." },
    ] },
  { n: 6, title: "Beyond the Wall",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "The wight hunt catches its prize — and the army of the dead catches the hunters on a frozen lake.",
      "A raven flies; three dragons answer; the ice holds long enough for a rescue.",
      "The Night King's spear takes Viserion from the sky.",
      "Jon bends the knee from a sickbed; chains drag a dead dragon from the lake, and blue eyes open.",
    ],
    people: [
      { name: "Jon Snow", loc: "eastwatch-by-the-sea", note: "Pulled from the frozen lake by a half-dead uncle's last ride." },
      { name: "Daenerys Targaryen", loc: "eastwatch-by-the-sea", note: "Flew beyond the Wall for a man who won't stop being right." },
      { name: "Sandor Clegane", loc: "eastwatch-by-the-sea", note: "Carries the wight in a crate and grudges every mile." },
      { name: "Arya Stark", loc: "winterfell", note: "Littlefinger's planted letter does its slow poison between sisters." },
      { name: "Benjen Stark", loc: "eastwatch-by-the-sea", note: "One horse, one nephew, no room for both." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 7, tully: 2, arryn: 5, greyjoy: 4, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Viserion", note: "A dragon of the blood, speared from a winter sky — and raised with eyes of blue." },
      { name: "Thoros of Myr", note: "The red priest who beat death six times for Beric, claimed by a frozen bear." },
      { name: "Benjen Stark", note: "The First Ranger's last ride, buying Jon the horse he gave away." },
    ] },
  { n: 7, title: "The Dragon and the Wolf",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "The dragonpit summit: a screaming wight makes the argument; Cersei pledges her armies — and lies.",
      "Jaime learns the pledge is a lie and rides north alone as the first snow falls on King's Landing.",
      "In Winterfell's hall, the letter-trap springs backward: Sansa sentences, Arya executes, Littlefinger begs.",
      "Sam and Bran do the arithmetic: Aegon Targaryen, trueborn — as the boat cabin door closes.",
      "At Eastwatch, the dead reach the Wall — and a blue-eyed dragon melts it into the sea.",
    ],
    people: [
      { name: "Cersei Lannister", loc: "kings-landing", note: "Promised the living her armies; ordered them home before the door shut." },
      { name: "Jaime Lannister", loc: "kings-landing", note: "Rode away from her at last, one glove over a golden hand." },
      { name: "Sansa Stark", loc: "winterfell", note: "\"You are guilty, Lord Baelish. How do you answer these charges?\"" },
      { name: "Arya Stark", loc: "winterfell", note: "The Valyrian dagger comes back to its buyer's throat." },
      { name: "Theon Greyjoy", loc: "dragonstone", note: "Beaten until he remembers who he is; sails to save his sister." },
    ],
    power: { stark: 7, lannister: 7, baratheon: 1, targaryen: 7, tully: 2, arryn: 5, greyjoy: 3, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Petyr \"Littlefinger\" Baelish", note: "The man who started the whole game, out-played in a hall he thought he owned." },
    ] },
] },

// ==================== SEASON EIGHT ====================
{ n: 8, name: "Season Eight", episodes: [
  { n: 1, title: "Winterfell",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "Daenerys and Jon ride into a Winterfell that doesn't cheer; the North counts her armies and her dragons coldly.",
      "Sam learns his father and brother burned — from the queen who burned them; then he tells Jon who he really is.",
      "Jaime arrives alone and meets Bran's waiting stare in the courtyard.",
      "At Last Hearth, the dead leave the Umber boy pinned in a spiral: the Night King is south of the Wall.",
    ],
    people: [
      { name: "Jon Snow", loc: "winterfell", note: "Rides a dragon, learns his name is Aegon, loses his footing in one day." },
      { name: "Daenerys Targaryen", loc: "winterfell", note: "\"Your sister doesn't like me.\" The North agrees with her sister." },
      { name: "Samwell Tarly", loc: "winterfell", note: "Tells the hardest truth in the crypts, by candlelight." },
      { name: "Arya Stark", loc: "winterfell", note: "Reunions: Jon, Gendry, the Hound — a list of a different kind." },
      { name: "Jaime Lannister", loc: "winterfell", note: "One knight against the army he promised and didn't bring." },
    ],
    power: { stark: 7, lannister: 7, baratheon: 1, targaryen: 7, tully: 2, arryn: 5, greyjoy: 3, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Lord Ned Umber", note: "The little lord of Last Hearth, left as the Night King's message." },
    ] },
  { n: 2, title: "A Knight of the Seven Kingdoms",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "Jaime stands trial in Winterfell's hall; Brienne's word outweighs two queens' grudges.",
      "The plan is set: Bran waits in the godswood as bait, the living hold the walls.",
      "One last night: songs by the fire, wine, Podrick singing — and Jaime knights Brienne of Tarth.",
      "Jon tells Daenerys the truth in the crypts as the horns blow three times.",
    ],
    people: [
      { name: "Brienne of Tarth", loc: "winterfell", note: "Arise, Ser Brienne of Tarth, a knight of the Seven Kingdoms." },
      { name: "Jaime Lannister", loc: "winterfell", note: "Does the one knighting that ever mattered to him." },
      { name: "Arya Stark", loc: "winterfell", note: "Spends the last night her own way: no regrets, no waiting." },
      { name: "Tyrion Lannister", loc: "winterfell", note: "\"I think we might live.\" The fire disagrees quietly." },
      { name: "Theon Greyjoy", loc: "winterfell", note: "Asks to guard Bran: the godswood, the bait, the debt." },
    ],
    power: { stark: 7, lannister: 7, baratheon: 1, targaryen: 7, tully: 2, arryn: 5, greyjoy: 3, frey: 1, tyrell: 0, martell: 2 },
    deaths: [] },
  { n: 3, title: "The Long Night",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "The Dothraki charge with flaming arakhs — and the fire goes out in the dark, all of it.",
      "The dead crest the walls like a tide; Melisandre lights the trench with her last great work.",
      "Bran waits under the heart tree; Theon Greyjoy dies a Stark's death defending him.",
      "The Night King smiles at dragonfire, walks to Bran — and Arya Stark comes out of the dark.",
      "The dagger drops from one hand to the other. Winter shatters.",
    ],
    people: [
      { name: "Arya Stark", loc: "winterfell", note: "\"What do we say to the god of death?\" Not today." },
      { name: "Theon Greyjoy", loc: "winterfell", note: "\"Theon. You're a good man. Thank you.\" Then he charged." },
      { name: "Jorah Mormont", loc: "winterfell", note: "Fell shielding his queen, sword in hand, at last content." },
      { name: "Melisandre", loc: "winterfell", note: "Lit the trenches, fulfilled her purpose, walked into the dawn and dust." },
      { name: "Lyanna Mormont", loc: "winterfell", note: "Killed a giant as it killed her: sixty pounds of the North's whole heart." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 6, tully: 2, arryn: 5, greyjoy: 3, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "The Night King", note: "Shattered by a Valyrian dagger and a girl who walks like a cat — his whole army with him." },
      { name: "Theon Greyjoy", note: "Died a Greyjoy and a Stark both, one spear-length short of the heart tree." },
      { name: "Ser Jorah Mormont", note: "The exile who came home to die between his queen and the dead." },
      { name: "Lyanna Mormont", note: "The little bear, giant-slain and giant-slaying." },
      { name: "Edd Tollett", note: "Dolorous Edd, the last Lord Commander of the old Watch, saving Sam one final time." },
      { name: "Beric Dondarrion", note: "Brought back nineteen times for one purpose: a hallway, a door, Arya alive." },
      { name: "Melisandre of Asshai", note: "The red woman, her necklace unclasped by choice in the morning snow." },
    ] },
  { n: 4, title: "The Last of the Starks",
    throne: { king: "Cersei I Lannister", house: "lannister", hand: "Qyburn, Hand of the Queen" },
    events: [
      "The dead are burned; the living feast badly — every toast curdles into politics.",
      "Jon tells his sisters the truth under the heart tree; Sansa tells Tyrion by the battlements.",
      "Euron's scorpions ambush the fleet off Dragonstone: Rhaegal falls into the sea.",
      "Missandei of Naath dies in chains on the walls of King's Landing, with one word: Dracarys.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "dragonstone", note: "Loses a dragon, a best friend, and the room's love — in one episode." },
      { name: "Missandei", loc: "kings-landing", note: "Born free, died chained, last word a command." },
      { name: "Sansa Stark", loc: "winterfell", note: "Keeps one promise four minutes. The secret starts to move." },
      { name: "Jaime Lannister", loc: "winterfell", note: "Rides south in the night: \"She's hateful. And so am I.\"" },
      { name: "Bronn", loc: "winterfell", note: "Negotiates Highgarden at crossbow-point, mid-war, on account." },
    ],
    power: { stark: 6, lannister: 7, baratheon: 1, targaryen: 5, tully: 2, arryn: 5, greyjoy: 3, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Rhaegal", note: "Speared thrice from Euron's hidden fleet, dead before the water took him." },
      { name: "Missandei of Naath", note: "Beheaded on the city walls as two queens watched each other." },
    ] },
  { n: 5, title: "The Bells",
    throne: { king: "Cersei I Lannister (deposed)", house: "lannister", hand: "Qyburn, Hand of the Queen †" },
    events: [
      "Varys chooses the realm one last time; the dragon chooses fire.",
      "The Iron Fleet, the scorpions, the Golden Company: all of it burns in an hour.",
      "The bells ring surrender — and Daenerys flies past them into the streets.",
      "Jaime and Cersei die under the Red Keep; the Hound and the Mountain die in the fire above it.",
      "Arya crawls out of the ash grey and alive, on a pale horse.",
    ],
    people: [
      { name: "Daenerys Targaryen", loc: "kings-landing", note: "The bells rang. She heard something else." },
      { name: "Jon Snow", loc: "kings-landing", note: "Watches his queen's fire eat a surrendered city." },
      { name: "Arya Stark", loc: "kings-landing", note: "Came for one name; left saving anyone she could." },
      { name: "Sandor Clegane", loc: "kings-landing", note: "\"Go home, girl.\" The last kindness of the Hound." },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Freed his brother, killed his king's peace, broke his own heart." },
    ],
    power: { stark: 6, lannister: 2, baratheon: 1, targaryen: 8, tully: 2, arryn: 5, greyjoy: 2, frey: 1, tyrell: 0, martell: 2 },
    deaths: [
      { name: "Varys, Master of Whisperers", note: "Burned for treason — the treason of being right too early." },
      { name: "Lord Euron Greyjoy", note: "Died killing a king's brother, grinning: \"I'm the man who killed Jaime Lannister.\" He wasn't." },
      { name: "Qyburn", note: "Dismissed head-first into rubble by the monster he made." },
      { name: "Sandor & Gregor Clegane", note: "The Cleganebowl: brother takes brother into the fire below." },
      { name: "Jaime & Cersei Lannister", note: "Together at the end, under the falling keep — nothing else in the world." },
    ] },
  { n: 6, title: "The Iron Throne",
    throne: { king: "Brandon I Stark, the Broken — chosen by council", house: "stark", hand: "Tyrion Lannister" },
    events: [
      "Ash falls like snow; Daenerys addresses her armies with the whole world still to 'liberate'.",
      "Tyrion resigns as Hand into custody; Jon follows love and duty to the throne room one last time.",
      "A kiss, a knife, and Drogon melts the Iron Throne rather than the man — then carries her east.",
      "The lords choose Bran the Broken; Sansa takes the North out; Jon takes the black that no longer exists.",
      "A small council argues about brothels and grammar. The wheel is, for now, a table.",
    ],
    people: [
      { name: "Jon Snow", loc: "castle-black", note: "Queenslayer, kingsblood, exile — riding north with the free folk, where he was always going." },
      { name: "Sansa Stark", loc: "winterfell", note: "Queen in the North, crowned in the hall she survived." },
      { name: "Arya Stark", loc: "braavos", note: "West of Westeros — where all the maps stop." },
      { name: "Bran Stark", loc: "kings-landing", note: "\"Why do you think I came all this way?\"" },
      { name: "Tyrion Lannister", loc: "kings-landing", note: "Hand to the fourth monarch he's served: maybe this one will stick." },
      { name: "Brienne of Tarth", loc: "kings-landing", note: "Lord Commander; finishes a certain white book's page properly." },
    ],
    power: { stark: 9, lannister: 3, baratheon: 2, targaryen: 1, tully: 4, arryn: 5, greyjoy: 3, frey: 1, tyrell: 0, martell: 3 },
    deaths: [
      { name: "Daenerys Stormborn of House Targaryen", note: "First of Her Name, Breaker of Chains — killed by the man she loved, mourned by a dragon." },
    ] },
] },
];
