/* GAME OF THRONES WIKI — hand-written long-form articles ("The fuller tale").
   Keys: a character's exact name, "house:<id>", or "loc:<id>".
   Values: an array of paragraphs (original text — never copied from any wiki).
   Add entries freely; every key automatically appears on its wiki page. */

const WIKI_EXTRA = {

  // ================= characters =================
  "Jon Snow": [
    "Raised at Winterfell as Ned Stark's bastard, Jon grows up at the edge of everything — inside the family and outside it, trained beside the heir but seated below the salt. It makes him watchful, prickly about honor, and quicker than his brothers to notice the people the world overlooks. The Wall seems like the answer: the one place in Westeros where a bastard's name is left at the gate. What he finds there is not the storied brotherhood of the songs but thieves, poachers and old men holding seven hundred feet of ice against the dark — and, to his own surprise, a home.",
    "His rise is a study in unwanted authority. He becomes the Old Bear's steward instead of a ranger and learns that leading is mostly paperwork and grief; he goes over the Wall as a spy and comes back with a broken heart and an education in the free folk's humanity. Every command he takes, he takes reluctantly, and every mercy he shows — most of all opening the gate to the wildlings — costs him with his own men. The Watch teaches him the lesson that shapes everything after: doing the right thing and being loved for it are different careers.",
    "By the war's end Jon has been a lord commander, a king, a queen's man and a kinslayer of sorts, and the revelation of his true name — Aegon Targaryen, son of Rhaegar and Lyanna — changes everyone's calculations except his own. He never wanted the chair the realm kept trying to seat him in. His story closes where it began, at the Wall and beyond it, with the free folk who never cared what his name was. Of all the tale's endings, his is the most like its beginning — which is either a tragedy or the only happy ending on offer, depending on the day you ask him.",
  ],
  "Daenerys Targaryen": [
    "Daenerys begins the story as a commodity: the last Targaryen daughter, sold by her brother to a Dothraki khal for the promise of an army. Everything that follows is her refusing, step by step, to be a thing that is traded. She learns command in Drogo's khalasar, walks into her husband's funeral pyre with three petrified eggs, and walks out unburnt with the first dragons the world has seen in a century and a half — the moment the entire story tilts on its axis.",
    "Her march through Slaver's Bay makes her legend and states her thesis: that power should answer to the powerless. Astapor's Unsullied, Yunkai's freedmen and Meereen's pyramids each teach the same hard course — breaking chains is a morning's work; building what comes after is a life's. She lingers in Meereen precisely because she takes ruling seriously, and the queue of advisers, suitors and enemies she accumulates there is the realm's first warning that Westeros will not simply be handed to her.",
    "In Westeros she gives more than any claimant ever gave — her fleets, her allies, a dragon, and the war against the dead take everything — and receives suspicion in return, in a country that loves her rival and fears her name. The bells of King's Landing ring surrender, and she burns the city anyway: the tale's most argued-over hour, seeded from the first season in every 'blood of the dragon' promise and every counselor who taught her that fear works where love fails. She dies in the throne room, killed by the man she loved, beside the chair that consumed her family whole. Her dragon melts the throne rather than share her fate — the last word in an argument three hundred years old.",
  ],
  "Tyrion Lannister": [
    "Born to the realm's richest and coldest house, Tyrion pays for his mother's death in childbirth every day of his father's life. Denied the soldier's body his family reveres, he arms himself with the only weapons left on the shelf — books, jokes and an unsentimental eye for how power actually works. He drinks and he knows things, and beneath the performance sits the tale's most consistent sympathy for cripples, bastards and broken things: he builds Bran a saddle before he has any reason to be kind.",
    "His masterpiece is the defense of King's Landing. As acting Hand he runs the city with wildfire, a chain and no credit, saving the capital at the Blackwater and waking up demoted, scarred and written out of the songs. The injustice of it — reliably doing the indispensable thing and being hated for it — hardens into the trial for Joffrey's murder, where his family's contempt finally gets a courtroom. His escape, by way of a crossbow and his father's privy, is the blackest and most honest moment the Lannisters ever share.",
    "In exile he bets his cleverness on Daenerys, and the last act tests whether wisdom can steer power. It mostly cannot: his queen outruns his counsel, his mercies misfire, and the wisest man in Westeros ends the war as its most spectacular failure — which he says himself, resigning his pin. The lords choose the next king on the strength of a speech Tyrion gives as a prisoner, and he is sentenced, with perfect irony, to the job he is best at and never wanted: Hand of the King, cleaning up after power, forever.",
  ],
  "Arya Stark": [
    "Arya is the Stark who never fit the picture: better with a bow than her brothers, allergic to needlework, collector of the names of the overlooked. Her father indulges her with a fencing master, and Syrio Forel's water dance — swift as a deer, quiet as a shadow — becomes the frame of her whole life. When the world breaks on the steps of Baelor's sept, she is in the crowd, watching. The list she starts reciting that night is a child's prayer with teeth.",
    "Her road is the war's underside: a recruit column, Harrenhal's terrors, an outlaw band, the Hound as unlikely guardian and tutor. Each stop strips something away and sharpens what remains, until Braavos and the House of Black and White offer the final trade — all of herself, in exchange for the power to be no one. She takes the training and refuses the bargain: the Faceless Men teach her everything except how to stop being Arya Stark, and Needle, hidden in the rocks rather than surrendered, wins that argument for her.",
    "She comes home a legend wearing a girl's face — the Freys learn first, the Night King last. The dagger-drop in the godswood at Winterfell is the tale's single most consequential act of violence, and the story hands it to its smallest soldier. Afterward, with the list dead or forgiven and the pack safe, she does the most Arya thing imaginable: she declines every ending on the map and sails west of Westeros, where the maps stop. Not a lady, not a killer, not no one — an explorer.",
  ],
  "Sansa Stark": [
    "Sansa begins as the realm's best student of a curriculum that turns out to be a lie: songs, courtesy, tourneys and gallant princes. Her betrothal to Joffrey delivers her into the truth at the worst possible address, and the execution of her father — begged for, bargained over, watched from a platform — ends her childhood in a single stroke. What looks like passivity in the seasons that follow is actually apprenticeship: in a city where everyone is armed, her weapon is a perfect curtsy and a memorized smile.",
    "She survives the capital's every regime — Joffrey's cruelty, Cersei's tutelage in cynicism, a forced Lannister marriage — and each survival adds a tool. Littlefinger's escape offers rescue at the price of becoming his creature; the Vale teaches her how lies are administered; Ramsay Bolton's Winterfell is the last and worst classroom. Her testimony at his kennels, delivered without raising her voice, is the coldest sentence passed in the entire tale, and no one who watched her arc calls it undeserved.",
    "The last movement belongs to her. She feeds the Vale's knights into the Battle of the Bastards at the exact right hour, out-plays Littlefinger to his death in the hall he schemed to own, and holds the North's independence out of the war's wreckage when every other crown is melted or buried. Queen in the North, crowned in the castle she survived — the girl who wanted to marry a king, corrected by experience into the person the kings should have been.",
  ],
  "Cersei Lannister": [
    "Cersei's tragedy is stated in her own family's arithmetic: she is Tywin Lannister's firstborn and his equal in will, and none of it counts because she is a daughter. Sold to Robert Baratheon to seal a rebellion, she spends a marriage being compared to a dead woman and develops the tale's most fortified heart. What love survives goes entirely to her twin and her children — and the prophecy that promised her three golden shrouds sits under every scene she plays.",
    "Her statecraft is a hammer in a room of scalpels. She is genuinely fearless and genuinely shrewd about people's appetites, but every solution she reaches for doubles the problem: arming the Faith to spite the Tyrells hands the city to fanatics; her walk of atonement manufactures the humiliation she spent a lifetime avoiding; and her answer — burning the Great Sept with the entire court inside — wins her the throne at the cost of her last child. She is crowned in a black gown in an empty hall, having defeated everyone, including every reason she wanted to win.",
    "As queen she plays the last war coldly and almost brilliantly — sitting out the fight against the dead, buying the Golden Company, betting that her enemies will bleed each other white. It nearly works. But her reign was always a dare flung at fate, and fate accepts: the dragon comes, the walls fall, and she dies in the dark beneath the Red Keep in Jaime's arms — the one person who never needed her to be anything but Cersei. The realm remembers a monster; the truth is more uncomfortable — a first-rate mind spent its whole life being told the game was not for her, and decided to break the board.",
  ],
  "Jaime Lannister": [
    "For seventeen years Jaime Lannister is the realm's shorthand for broken oaths: the Kingslayer, the white knight who opened his king's throat. He wears the contempt with a smirk because the truth is worse company — that killing Aerys, seconds before the Mad King burned half a million people, was the finest thing he ever did, and the realm made it his shame. The tale meets him at his worst, pushing a child from a tower for the love that defines and disfigures him.",
    "Losing his sword hand to a Bolton axe costs him his identity and buys back his soul. The road with Brienne of Tarth — the bath at Harrenhal where the Kingslayer finally tells the story, the bear pit he jumps back into — rebuilds him around something other than Cersei and swordsmanship. He keeps oaths now with a convert's stubbornness: sending Brienne after the Stark girls with a Valyrian sword named, at last, Oathkeeper.",
    "His ending is the tale's bitterest argument about whether people change. He rides north alone to keep his pledge against the dead, knights Brienne in the last night's firelight — and then rides south again, because the answer he gives is that the addict goes back. He dies under the Red Keep holding the sister he could never leave, the golden man of the golden house, buried by the family's own ruin. Half the audience calls it a betrayal of his arc; the other half calls it the arc, completed. Both keep arguing, which is how you know it was written true.",
  ],
  "Eddard Stark": [
    "Ned Stark carries the old North in a southern age: the man who passes the sentence swings the sword, guest right is holy, and a word given is a debt owed. He fought one war out of duty and came home with a sister's deathbed promise and a bastard son whose true name he tells no one — the single lie of an honest man's life, kept so well it bends the entire story around it.",
    "Robert's offer of the Handship is a summons Ned cannot honorably refuse and cannot possibly survive. In King's Landing he does exactly what he was brought to do — he finds the truth of Jon Arryn's death and the royal children's parentage — and then handles it like a northman: he warns Cersei to run before he tells the king. Mercy, in that city, is a resignation letter. Betrayed by the council he trusted and the gold cloaks he paid, he ends in the black cells, where Varys makes the case that pride is a luxury fathers cannot afford.",
    "His confession on the steps of the Great Sept — a lie sworn to save his daughters — is the greatest sacrifice in the tale: a man who valued honor above everything spending it, publicly, as ransom. Joffrey takes his head anyway, and the shock of it announced what kind of story this would be. Every war that follows marches out of that moment, and every Stark child's arc is an answer to his: the realm killed the most honorable man in it, and the North remembered.",
  ],

  // ================= houses =================
  "house:stark": [
    "The Starks are the oldest institution in Westeros that still works. Kings of Winter for eight thousand years and Wardens of the North after the dragons came, they rule from Winterfell by a compact older than heraldry: the North is hard, the Starks are harder, and when the snows come the Stark in Winterfell feeds his own. Their words are the tale's thesis — not a boast like the southern mottoes, but a weather report and a warning.",
    "The story destroys them methodically — Ned on the sept steps, Robb and Catelyn at the Twins, Winterfell burned and traded between traitors — and then demonstrates why eight thousand years is not an accident. The children scatter into wolves: a king's ward turned assassin, a hostage turned queen, a broken boy turned the realm's memory, a bastard turned the realm's shield. When the pack reassembles, everything their enemies built is gone, and the realm's last three crowned heads are all, one way or another, Starks of Winterfell.",
  ],
  "house:lannister": [
    "The Lannisters mint the story's currency — literally, from the gold under Casterly Rock, and figuratively, in the phrase every debtor in the realm knows better than their prayers. Tywin rebuilt the house from his father's laughingstock into the power behind the throne, and the price was a family run like a bank: heirs as assets, marriages as mergers, love as an accounting error. Hear Me Roar is the official motto; a Lannister always pays his debts is the true one, and the tale spends eight seasons itemizing the invoice.",
    "No house wins more or keeps less. They hold the throne through three kings without ever quite sitting it legitimately, and every triumph is self-poisoned: the Red Wedding buys a rebellion's end and damns their name; the Blackwater saves the capital for a boy who dies at his own wedding; the sept's destruction crowns Cersei over an empty court. The Rock's gold runs dry the same season its army finally marches. In the end the debt collector calls at their own door — of Tywin's brilliant, gilded children, one dies under the keep, one beside her, and the survivor spends his life in service to other people's kings.",
  ],
  "house:targaryen": [
    "Alone of the great houses, the Targaryens are foreign to Westeros — the last dragonlords of Valyria, camped on Dragonstone when the Doom took everything else. Aegon and his sisters conquered six of seven kingdoms with three dragons and ruled for near three centuries by a simple asymmetry: everyone else's army walked. Fire and Blood is not a motto so much as a terms-of-service agreement, and the realm signed under duress.",
    "The house's history is a coin toss between brilliance and madness, flipped every generation — Jaehaerys the wise, Aegon the dragon-riding conqueror, and across from them the kings who burned men alive and dreamed prophecy until it ate them. The dragons died, then the dynasty: Robert's warhammer at the Trident ended the line's rule, and the tale opens with the inheritance reduced to two exiles and three stone eggs. That the story's two great protagonists both turn out to be Targaryens — the exiled queen and the hidden heir — is the coin flipping one final time, both faces at once.",
  ],

  // ================= places =================
  "loc:the-rhoyne": [
    "The Rhoyne is less a river than a civilization's spine. Rising in the Hills of Norvos and gathering seven great tributaries — the Noyne, the Qhoyne, the Lhorulu, the Selhoru and their sisters — she runs the length of western Essos and meets the sea at Volantis so wide that boatmen mid-channel see no shore at all. To the people she raised, the Rhoynar, she was Mother Rhoyne: their cities of song rose on her banks, their water wizards worked her currents, and their prince Garin the Great led a quarter of a million spears against Valyria when the dragonlords came for her daughters.",
    "Valyria won, as Valyria always won, and the Mother's children paid the price of pride: Chroyane, the festival city, became the drowned, fog-bound Sorrows where the stone men now waste with greyscale — the plague Garin is said to have called up from the waters as his curse. Rather than kneel, Princess Nymeria gathered the survivors into ten thousand ships and sailed the length of the known world to Dorne, where her people's laws, names and stubbornness live on. The books give the river its due in Tyrion's journey downstream — the mists, the ruins, the turtle the rivermen call the Old Man of the River — one of the great travelogues of the saga.",
  ],
  "loc:the-wall": [
    "The Wall is the largest structure ever raised by men — or by men with help, for the tales say giants set the foundations and the children of the forest wove spells through the ice. Seven hundred feet high, a hundred leagues long, it has stood for eight thousand years against a threat the realm long ago stopped believing in, guarded by an order the realm long ago stopped honoring. Nineteen castles punctuate its length; in the tale's time, three are manned, by fewer swords than a middling lord commands.",
    "The genius of the Wall is that it is a border between stories: south of it, the game of thrones; north of it, the reason the game is trivial. Every character who passes through its gates is reordered by the crossing — Jon most of all, but also Tyrion, who came to piss off the edge of the world and left it strangely serious. When the Night King's dragon finally brings a section down at Eastwatch, the sound is the tale's two stories crashing into one.",
  ],
  "loc:winterfell": [
    "Winterfell is the argument that a castle can be a character. Built over hot springs whose warmth runs through its walls, it is the seat of House Stark, the memory-palace of the North, and the tale's fixed point: the story begins in its courtyard with a deserter's execution and ends with a Stark queen crowned in its hall. Its crypts hold the Kings of Winter in dark rows, iron swords across their knees to keep the vengeful spirits in — and it is down among those tombs that the story's greatest secret, R plus L, sleeps beside Lyanna's statue.",
    "The castle's fall and resurrection track the family's. Taken by Theon with twenty men and burned by Ramsay's, held by Boltons wearing its name like a stolen cloak, it is won back at the Battle of the Bastards and becomes, at the end, the hinge of the living world — the fortress where the Long Night is fought and finished in its godswood. Bran the Builder is said to have raised both Winterfell and the Wall; the tale ends with one of his line on the throne of the south and another queen in his castle, which the old kings in the crypts would probably consider the books balanced.",
  ],
  "loc:kings-landing": [
    "Aegon the Conqueror landed on three hills at the mouth of the Blackwater and built his capital where his boots first touched Westeros. Three centuries on, King's Landing is half a million souls stacked between the Red Keep, the Great Sept and Flea Bottom's pot-shops — the realm's largest city, worst smell and most dangerous address. Power lives here the way rot lives in wood: the throne room holds the chair, but the city's real business is done in council chambers, brothels and the black cells beneath the keep.",
    "The tale uses the city as its scale for catastrophe. Ned loses his head on the steps of Baelor's sept; the Blackwater burns green; the Faith militant chains a queen; the sept itself vanishes in a bloom of wildfire — and each disaster is only rehearsal. When Daenerys finally brings fire and blood to Aegon's city, the bells ringing surrender as the streets burn, the capital pays at last for every bargain struck inside its walls. The story's final quiet joke: after all of it, the realm is governed from the same address, by a small council arguing about brothels and grammar.",
  ],
};
