/* ============================================================================
   THE IRON LADDER — THE WORLD.

   Two tables and nothing else: REALMS (the great divisions of the world, which
   is what you pick first) and PLACES (where inside one you actually stand).

   A REALM has `links` — the realms you can reach overland from it. Travel
   between two linked realms takes a season and costs coin; travel to an
   unlinked realm needs a ship and a port. That adjacency is the whole map: it
   means a hundred and forty places need nine lines of geography between them
   instead of a hundred and forty adjacency lists, and the world still feels
   like a place you cross rather than a menu you jump around.

   A PLACE carries `tags`, and tags are how the event deck finds it. An event
   that wants a harbour asks for `port`; one that wants somewhere lawless asks
   for `wild`. Adding a place to the world therefore adds it to every event
   already written for its kind, with no edit to the deck at all. Keep the
   vocabulary below closed — a typo'd tag is an event that silently never fires:

     settlement   city town village
     holding      castle keep tower ruin
     nature       wild forest mountain desert marsh island
     water        port sea river
     society      court market holy poor rich slave free crime
     weather      cold hot
     special      wall prison warcamp

   `birth: false` marks somewhere nobody is born — a ruin, a battlefield, a
   sept on a rock. It stays reachable by travel.
   ========================================================================== */

window.IL_WORLD = {

  /* ------------------------------------------------------------- REALMS --- */
  realms: [
    { id: "north", name: "The North", short: "North", seat: "Winterfell",
      side: "westeros", links: ["riverlands", "vale", "beyond-the-wall", "iron-islands"],
      blurb: "A third of the continent and barely a tenth of its people. Cold, old, poor in coin and long in memory, and the last place where the old gods still hold the woods.",
      traits: ["Hardy", "Poor in coin", "Long memories"] },

    { id: "beyond-the-wall", name: "Beyond the Wall", short: "Beyond", seat: "no seat at all",
      side: "westeros", links: ["north"],
      blurb: "Free folk, ice and the largest forest in the world. There are no lords here, no laws and no taxes — which is what everyone north of the Wall will tell you before they tell you anything else.",
      traits: ["No lords", "Killing cold", "Kneel to nobody"] },

    { id: "riverlands", name: "The Riverlands", short: "Riverlands", seat: "Riverrun",
      side: "westeros", links: ["north", "vale", "westerlands", "crownlands", "reach", "iron-islands"],
      blurb: "The crossroads of the realm, which is a polite way of saying every army in three centuries has marched through somebody's barley here.",
      traits: ["Well travelled", "Raided often", "Rich soil"] },

    { id: "vale", name: "The Vale of Arryn", short: "Vale", seat: "The Eyrie",
      side: "westeros", links: ["north", "riverlands", "crownlands"],
      blurb: "Mountains that keep out armies and new ideas with equal success. Proud, sheltered, and always the last to arrive at a war.",
      traits: ["Sheltered", "Proud", "Slow to move"] },

    { id: "iron-islands", name: "The Iron Islands", short: "Iron Islands", seat: "Pyke",
      side: "westeros", links: ["north", "riverlands", "westerlands"],
      blurb: "Salt, stone, and no soil worth the name. What is not taken is not owned; every child can sail before they can plough, because there is nothing here to plough.",
      traits: ["Seafaring", "Reaving", "Little land"] },

    { id: "westerlands", name: "The Westerlands", short: "Westerlands", seat: "Casterly Rock",
      side: "westeros", links: ["riverlands", "reach", "iron-islands"],
      blurb: "Gold under the hills and a great deal of it above ground too. The most expensive place in the world in which to make an enemy.",
      traits: ["Coin", "Watched closely", "Unforgiving"] },

    { id: "crownlands", name: "The Crownlands", short: "Crownlands", seat: "King's Landing",
      side: "westeros", links: ["riverlands", "vale", "reach", "stormlands"],
      blurb: "Half a million people in a city built for far fewer, and the throne sitting in the middle of it. Everything in the realm happens here first, and usually twice.",
      traits: ["Connected", "Crowded", "Dangerous"] },

    { id: "reach", name: "The Reach", short: "Reach", seat: "Highgarden",
      side: "westeros", links: ["westerlands", "riverlands", "crownlands", "stormlands", "dorne"],
      blurb: "The granary and the tourney ground of the world, where knighthood is taken seriously and so is dinner.",
      traits: ["Fed well", "Ceremonious", "Chivalrous"] },

    { id: "stormlands", name: "The Stormlands", short: "Stormlands", seat: "Storm's End",
      side: "westeros", links: ["crownlands", "reach", "dorne"],
      blurb: "Weather that kills, and a people who take it personally. Hard coasts, hard drinking, and the oldest grudges in the south.",
      traits: ["Stubborn", "Storm-battered", "Loyal"] },

    { id: "dorne", name: "Dorne", short: "Dorne", seat: "Sunspear",
      side: "westeros", links: ["reach", "stormlands"],
      blurb: "Sand, mountains and a separate set of laws — including who may inherit, which here is simply the eldest, whatever they happen to be.",
      traits: ["Own laws", "Unconquered", "Merciless sun"] },

    { id: "free-cities", name: "The Free Cities", short: "Free Cities", seat: "no single seat",
      side: "essos", links: ["dothraki-sea", "slavers-bay"],
      blurb: "Nine cities that were Valyria's colonies and are now its heirs, quarrelling with each other in nine dialects and lending money to everybody.",
      traits: ["Coin and banks", "No kings", "Sellswords"] },

    { id: "dothraki-sea", name: "The Dothraki Sea", short: "Dothraki Sea", seat: "Vaes Dothrak",
      side: "essos", links: ["free-cities", "slavers-bay", "the-east"],
      blurb: "A grass ocean the size of Westeros, ruled by whoever is presently riding across it. There is one city, and no man may draw a blade inside it.",
      traits: ["Horse and open sky", "No walls", "Strength alone"] },

    { id: "slavers-bay", name: "Slaver's Bay", short: "Slaver's Bay", seat: "Meereen",
      side: "essos", links: ["free-cities", "dothraki-sea", "the-east"],
      blurb: "Three great brick cities built on one trade, wearing the ruins of Old Ghis like a borrowed crown.",
      traits: ["Chains", "Fighting pits", "Old cruelty"] },

    { id: "summer-isles", name: "The Summer Isles", short: "Summer Isles", seat: "Tall Trees Town",
      side: "essos", links: [],
      blurb: "Warm green islands south of everything, with the best archers, the best ships and the least interest in anybody else's wars.",
      traits: ["Golden bows", "Swan ships", "Far from the game"] },

    { id: "the-east", name: "The Further East", short: "The East", seat: "Qarth",
      side: "essos", links: ["dothraki-sea", "slavers-bay"],
      blurb: "Past the bones of the world: Qarth's three walls, the Shadow, and a thousand leagues that no map in Westeros gets right.",
      traits: ["Warlocks", "Spice and silk", "Very far from home"] },
  ],

  /* -------------------------------------------------------------- PLACES --- */
  places: [

    /* ============================ THE NORTH ============================== */
    { id: "winterfell", realm: "north", name: "Winterfell", kind: "castle",
      tags: ["castle", "court", "town", "cold"],
      blurb: "Hot springs run through the walls of a castle that has stood eight thousand years, and the crypts beneath it are longer than the halls above." },
    { id: "wintertown", realm: "north", name: "Wintertown", kind: "town",
      tags: ["town", "poor", "market", "cold"],
      blurb: "The village under Winterfell's walls: empty in summer, packed to the eaves the moment the snows come." },
    { id: "white-harbor", realm: "north", name: "White Harbor", kind: "city",
      tags: ["city", "port", "market", "rich", "holy", "cold"],
      blurb: "The North's only city and its only proper harbour — southron manners, southron septs, and every coin that comes north comes through here." },
    { id: "barrowton", realm: "north", name: "Barrowton", kind: "town",
      tags: ["town", "market", "cold"],
      blurb: "A walled market town built around the Great Barrow, where the First King is supposed to lie and nobody has ever dug to check." },
    { id: "deepwood-motte", realm: "north", name: "Deepwood Motte", kind: "castle",
      tags: ["castle", "forest", "port", "cold"],
      blurb: "A wooden keep on a hill in the wolfswood, close enough to the sea that ironborn sails are a seasonal problem." },
    { id: "karhold", realm: "north", name: "Karhold", kind: "castle",
      tags: ["castle", "cold", "poor"],
      blurb: "A grim square keep in the far north-east, held by men who count grudges the way other houses count cattle." },
    { id: "last-hearth", realm: "north", name: "Last Hearth", kind: "castle",
      tags: ["castle", "cold", "forest"],
      blurb: "The northernmost seat of any lord in the Seven Kingdoms, with fires that are never allowed to go out." },
    { id: "dreadfort", realm: "north", name: "The Dreadfort", kind: "castle",
      tags: ["castle", "cold", "prison"],
      blurb: "Thick red walls, a great many towers, and a set of dungeons the rest of the North has agreed not to discuss." },
    { id: "moat-cailin", realm: "north", name: "Moat Cailin", kind: "ruin",
      tags: ["ruin", "marsh", "cold"], birth: false,
      blurb: "Three towers left of twenty, sunk in a bog that has swallowed every southern army ever sent up the causeway." },
    { id: "bear-island", realm: "north", name: "Bear Island", kind: "castle",
      tags: ["castle", "island", "sea", "cold", "poor"],
      blurb: "A cold rock in the Bay of Ice where the women are taught the axe because the men are so often away." },
    { id: "torrhens-square", realm: "north", name: "Torrhen's Square", kind: "castle",
      tags: ["castle", "cold"],
      blurb: "A blocky holdfast in the plain west of Winterfell, unremarkable except for how often it is besieged." },
    { id: "hornwood", realm: "north", name: "Hornwood", kind: "castle",
      tags: ["castle", "forest", "cold"],
      blurb: "A modest keep on the edge of the wolfswood, rich in timber and short on heirs." },
    { id: "widows-watch", realm: "north", name: "Widow's Watch", kind: "castle",
      tags: ["castle", "sea", "cold"],
      blurb: "A cliff-top seat staring out over the Bite, named for a woman who watched for a sail that never came." },
    { id: "rills", realm: "north", name: "The Rills", kind: "village",
      tags: ["village", "poor", "cold"],
      blurb: "Rolling streams and thin pasture in the west, where a family's whole wealth walks about on four legs." },
    { id: "skagos", realm: "north", name: "Skagos", kind: "village",
      tags: ["island", "wild", "cold", "poor"],
      blurb: "An island of stone and unicorns off the eastern shore, whose people the mainland accuses of eating men. The mainland may be right." },
    { id: "castle-black", realm: "north", name: "Castle Black", kind: "castle",
      tags: ["castle", "wall", "cold", "poor"],
      blurb: "Seven hundred feet of ice at your back, an oath you cannot leave, and about a tenth of the men the walls were built for." },
    { id: "eastwatch", realm: "north", name: "Eastwatch-by-the-Sea", kind: "castle",
      tags: ["castle", "wall", "port", "sea", "cold"],
      blurb: "The Watch's harbour at the eastern end of the Wall, where sailors from half the world unload things nobody asks about." },
    { id: "shadow-tower", realm: "north", name: "The Shadow Tower", kind: "castle",
      tags: ["castle", "wall", "mountain", "cold"],
      blurb: "The western end of the Wall, in the shadow of the mountains, where the passes have to be watched by men who can climb." },
    { id: "moles-town", realm: "north", name: "Mole's Town", kind: "village",
      tags: ["village", "poor", "crime", "cold"],
      blurb: "A village that is mostly underground, half a day south of the Wall, and known for exactly one business." },

    /* ======================= BEYOND THE WALL ============================= */
    { id: "crasters-keep", realm: "beyond-the-wall", name: "Craster's Keep", kind: "keep",
      tags: ["keep", "wild", "cold", "poor"],
      blurb: "A longhouse behind a mud wall, kept by a man who marries his own daughters and gives his sons to something in the woods." },
    { id: "hardhome", realm: "beyond-the-wall", name: "Hardhome", kind: "town",
      tags: ["town", "port", "sea", "wild", "cold"],
      blurb: "The only thing the free folk ever built that resembled a town. Six hundred years ago it burned in a night, and the ruins are still not quiet." },
    { id: "whitetree", realm: "beyond-the-wall", name: "Whitetree", kind: "village",
      tags: ["village", "forest", "holy", "wild", "cold"],
      blurb: "A dozen huts around a weirwood so vast its mouth could swallow a sheep, and the ashes in that mouth are not sheep." },
    { id: "haunted-forest", realm: "beyond-the-wall", name: "The Haunted Forest", kind: "wild",
      tags: ["forest", "wild", "cold"], birth: false,
      blurb: "A wood the size of a kingdom, with no road through it and a long tradition of people entering it in numbers and leaving in fewer." },
    { id: "frostfangs", realm: "beyond-the-wall", name: "The Frostfangs", kind: "mountain",
      tags: ["mountain", "wild", "cold"], birth: false,
      blurb: "Cruel, cold, inhospitable mountains where nothing grows and the wind never stops for long enough to be noticed." },
    { id: "milkwater", realm: "beyond-the-wall", name: "The Milkwater", kind: "village",
      tags: ["river", "wild", "cold", "warcamp"],
      blurb: "A pale glacial river the free folk follow south, and lately the mustering ground of everyone who intends to follow it." },
    { id: "thenn", realm: "beyond-the-wall", name: "The Vale of Thenn", kind: "village",
      tags: ["village", "mountain", "wild", "cold"],
      blurb: "The one place beyond the Wall with bronze, laws and a man they call a lord — which the rest of the free folk find hilarious and slightly frightening." },
    { id: "fist", realm: "beyond-the-wall", name: "The Fist of the First Men", kind: "ruin",
      tags: ["ruin", "mountain", "wild", "cold", "warcamp"], birth: false,
      blurb: "A ring-wall on a bare hill, built before the Andals came, still the best defensive ground for two hundred leagues." },

    /* ========================= THE RIVERLANDS ============================ */
    { id: "riverrun", realm: "riverlands", name: "Riverrun", kind: "castle",
      tags: ["castle", "court", "river", "rich"],
      blurb: "A triangle of red sandstone between two rivers, with a ditch on the third side that can be flooded into a moat in an hour." },
    { id: "harrenhal", realm: "riverlands", name: "Harrenhal", kind: "ruin",
      tags: ["ruin", "castle", "prison"],
      blurb: "The largest castle ever raised in Westeros, melted at the top, cursed by common agreement, and far too big for anyone to hold or heat." },
    { id: "the-twins", realm: "riverlands", name: "The Twins", kind: "castle",
      tags: ["castle", "river", "rich"],
      blurb: "Two castles and a bridge — the only bridge for hundreds of miles, which has made one grasping family very rich and very hated." },
    { id: "maidenpool", realm: "riverlands", name: "Maidenpool", kind: "town",
      tags: ["town", "port", "sea", "market"],
      blurb: "A walled harbour town on the Bay of Crabs, named for a pool a legendary queen is said to have bathed in." },
    { id: "saltpans", realm: "riverlands", name: "Saltpans", kind: "town",
      tags: ["town", "port", "sea", "poor"],
      blurb: "A small salt-making port with a small castle whose lord keeps his gate shut and his garrison inside it." },
    { id: "stoney-sept", realm: "riverlands", name: "Stoney Sept", kind: "town",
      tags: ["town", "holy", "market"],
      blurb: "A walled town of a dozen septs and one very famous alley, where a rebellion once turned on whether one man could be found in time." },
    { id: "crossroads-inn", realm: "riverlands", name: "The Crossroads Inn", kind: "village",
      tags: ["village", "market", "crime"],
      blurb: "Where the kingsroad meets the river road: every traveller in Westeros passes through, and so does every rumour." },
    { id: "seagard", realm: "riverlands", name: "Seagard", kind: "castle",
      tags: ["castle", "port", "sea"],
      blurb: "Built to watch for ironborn sails, with a bell tower rung so rarely that hearing it means running." },
    { id: "darry", realm: "riverlands", name: "Darry", kind: "castle",
      tags: ["castle", "poor"],
      blurb: "A modest holding much fought over, whose villages have been burned and rebuilt so often the peasants keep the timber ready." },
    { id: "raventree-hall", realm: "riverlands", name: "Raventree Hall", kind: "castle",
      tags: ["castle", "holy"],
      blurb: "A dead white weirwood stands in the yard, and the ravens that once nested in it still come back every dusk to scream at it." },
    { id: "stone-hedge", realm: "riverlands", name: "Stone Hedge", kind: "castle",
      tags: ["castle"],
      blurb: "Seat of a house that has feuded with its neighbours for a thousand years over a quarrel nobody can now reconstruct." },
    { id: "fairmarket", realm: "riverlands", name: "Fairmarket", kind: "town",
      tags: ["town", "market", "river", "poor"],
      blurb: "A river town of no walls and much trade, which is a fine arrangement in peace and a catastrophe otherwise." },
    { id: "gods-eye", realm: "riverlands", name: "The Isle of Faces", kind: "wild",
      tags: ["island", "holy", "forest", "wild"], birth: false,
      blurb: "An island of carved weirwoods in the middle of a great lake, kept by green men nobody has met and everybody describes." },

    /* ============================= THE VALE ============================== */
    { id: "eyrie", realm: "vale", name: "The Eyrie", kind: "castle",
      tags: ["castle", "court", "mountain", "cold", "prison"],
      blurb: "Seven white towers on a shoulder of the Giant's Lance, reachable only by mule, and impossible to take by anyone who has tried." },
    { id: "gates-of-the-moon", realm: "vale", name: "The Gates of the Moon", kind: "castle",
      tags: ["castle", "mountain"],
      blurb: "The Eyrie's winter seat at the foot of the mountain, where everyone actually lives for half the year." },
    { id: "gulltown", realm: "vale", name: "Gulltown", kind: "city",
      tags: ["city", "port", "sea", "market", "rich"],
      blurb: "The Vale's only city and its window on the world — which the Vale's lords regard with deep suspicion and constant use." },
    { id: "runestone", realm: "vale", name: "Runestone", kind: "castle",
      tags: ["castle", "sea", "holy"],
      blurb: "Ancient bronze-armoured seat of the First Men's blood in the Vale, covered in runes nobody living can read." },
    { id: "redfort", realm: "vale", name: "The Redfort", kind: "castle",
      tags: ["castle", "mountain"],
      blurb: "A red stone castle in the eastern hills, whose lord is a byword for a certain sort of grim old-fashioned honour." },
    { id: "heart-home", realm: "vale", name: "Heart's Home", kind: "castle",
      tags: ["castle"],
      blurb: "A comfortable, well-run seat whose lord is famously, cheerfully unwilling to commit to anything." },
    { id: "bloody-gate", realm: "vale", name: "The Bloody Gate", kind: "keep",
      tags: ["keep", "mountain", "warcamp"],
      blurb: "The only road into the Vale, narrowed to a defile between two watchtowers. No army has ever come through it uninvited." },
    { id: "mountains-of-the-moon", realm: "vale", name: "The Mountains of the Moon", kind: "wild",
      tags: ["mountain", "wild", "crime", "cold"],
      blurb: "Clans up here have been robbing the high road for three thousand years, and have never once been driven out of it." },
    { id: "sisterton", realm: "vale", name: "Sisterton", kind: "town",
      tags: ["town", "port", "sea", "crime", "poor"],
      blurb: "A damp smuggler's town on the Three Sisters, where the harbour master's chief skill is not noticing things." },
    { id: "longbow-hall", realm: "vale", name: "Longbow Hall", kind: "castle",
      tags: ["castle", "mountain"],
      blurb: "A high seat in the mountains whose garrison is drawn largely from men who grew up hunting in them." },

    /* ========================= THE IRON ISLANDS ========================== */
    { id: "pyke", realm: "iron-islands", name: "Pyke", kind: "castle",
      tags: ["castle", "court", "sea", "island"],
      blurb: "A castle on three stone stacks joined by rope bridges, slowly falling into the sea, which its lords consider fitting." },
    { id: "lordsport", realm: "iron-islands", name: "Lordsport", kind: "town",
      tags: ["town", "port", "sea", "market", "island"],
      blurb: "The islands' busiest harbour, rebuilt after every failed rebellion, currently on its third set of walls." },
    { id: "ten-towers", realm: "iron-islands", name: "Ten Towers", kind: "castle",
      tags: ["castle", "sea", "island", "rich"],
      blurb: "Ten towers raised in ten styles by ten different generations, on the richest and most civilised of the islands." },
    { id: "old-wyk", realm: "iron-islands", name: "Old Wyk", kind: "village",
      tags: ["island", "holy", "sea", "poor"],
      blurb: "The holiest of the islands, where the ribs of a sea dragon stand on a hill and kings have been chosen beneath them." },
    { id: "hammerhorn", realm: "iron-islands", name: "Hammerhorn", kind: "castle",
      tags: ["castle", "island", "poor"],
      blurb: "A grim seat carved into a hill on Great Wyk, whose lord is the closest thing the islands have to an honest man." },
    { id: "blacktyde", realm: "iron-islands", name: "Blacktyde", kind: "castle",
      tags: ["castle", "island", "sea"],
      blurb: "A small island seat whose lord has read books in the green lands, which his neighbours consider a moral failing." },
    { id: "orkmont", realm: "iron-islands", name: "Orkmont", kind: "village",
      tags: ["island", "poor", "sea"],
      blurb: "Once the seat of kings, now a played-out island of mines and hard little villages." },

    /* ========================= THE WESTERLANDS ========================== */
    { id: "casterly-rock", realm: "westerlands", name: "Casterly Rock", kind: "castle",
      tags: ["castle", "court", "rich", "sea", "mountain"],
      blurb: "A mountain hollowed into a fortress for three miles, with gold still coming out of the bottom of it after three thousand years." },
    { id: "lannisport", realm: "westerlands", name: "Lannisport", kind: "city",
      tags: ["city", "port", "sea", "market", "rich"],
      blurb: "The third city of the realm, tidy, wealthy and built entirely in the shadow of the Rock, in every sense." },
    { id: "golden-tooth", realm: "westerlands", name: "The Golden Tooth", kind: "castle",
      tags: ["castle", "mountain", "rich", "warcamp"],
      blurb: "The fortress guarding the only good pass east, and the mines beneath it are the reason anyone wants the pass." },
    { id: "crakehall", realm: "westerlands", name: "Crakehall", kind: "castle",
      tags: ["castle", "forest"],
      blurb: "A great blocky castle of three huge towers, in country famous for boar and for men who hunt them badly." },
    { id: "castamere", realm: "westerlands", name: "Castamere", kind: "ruin",
      tags: ["ruin", "mountain"], birth: false,
      blurb: "Flooded mine-workings and a drowned hall. There is a song about what happened here, and everyone in the west knows all the words." },
    { id: "ashemark", realm: "westerlands", name: "Ashemark", kind: "castle",
      tags: ["castle", "mountain"],
      blurb: "A stern grey seat in the hills, held by a house that has been quietly resentful of the Rock for two hundred years." },
    { id: "silverhill", realm: "westerlands", name: "Silverhill", kind: "castle",
      tags: ["castle", "rich"],
      blurb: "Rich fields, a silver mine that ran out generations back, and a name the family refuses to change." },
    { id: "deep-den", realm: "westerlands", name: "Deep Den", kind: "castle",
      tags: ["castle", "mountain", "crime"],
      blurb: "A castle sunk into a hillside guarding the gold road, mostly against bandits it half suspects it employs." },
    { id: "kayce", realm: "westerlands", name: "Kayce", kind: "town",
      tags: ["town", "port", "sea", "market"],
      blurb: "A busy little western port whose lord answers to nobody but the Rock, and is reminded of it often." },

    /* ========================== THE CROWNLANDS ========================== */
    { id: "red-keep", realm: "crownlands", name: "The Red Keep", kind: "castle",
      tags: ["castle", "court", "rich", "prison", "city"],
      blurb: "Seven drum-towers on Aegon's High Hill, with the Iron Throne in the middle and the black cells underneath." },
    { id: "flea-bottom", realm: "crownlands", name: "Flea Bottom", kind: "city",
      tags: ["city", "poor", "crime", "market"],
      blurb: "The bottom of King's Landing in every sense: pot-shops, alleys named for what runs down them, and more people than anyone has counted." },
    { id: "street-of-steel", realm: "crownlands", name: "The Street of Steel", kind: "city",
      tags: ["city", "market", "rich"],
      blurb: "Every armourer in the capital on one hill — the higher up you buy, the better the steel and the worse the price." },
    { id: "kings-landing-docks", realm: "crownlands", name: "The River Gate", kind: "city",
      tags: ["city", "port", "market", "crime"],
      blurb: "Mud Gate, fish market, and every ship that comes up the Blackwater. Also called the Mud Gate, mostly by people standing in it." },
    { id: "great-sept", realm: "crownlands", name: "The Great Sept", kind: "keep",
      tags: ["holy", "city", "rich"],
      blurb: "Marble and crystal on Visenya's Hill, where the Faith crowns kings and, when the mood takes it, judges them." },
    { id: "dragonstone", realm: "crownlands", name: "Dragonstone", kind: "castle",
      tags: ["castle", "island", "sea", "port"],
      blurb: "A Valyrian fortress of fused black stone shaped like dragons, on a smoking island nobody would otherwise live on." },
    { id: "duskendale", realm: "crownlands", name: "Duskendale", kind: "town",
      tags: ["town", "port", "sea", "market"],
      blurb: "An old walled port that was the realm's busiest before King's Landing existed, and has been sulking about it since." },
    { id: "rosby", realm: "crownlands", name: "Rosby", kind: "castle",
      tags: ["castle", "rich"],
      blurb: "A small holdfast a day north of the city, valuable chiefly for being a day north of the city." },
    { id: "stokeworth", realm: "crownlands", name: "Stokeworth", kind: "castle",
      tags: ["castle", "rich"],
      blurb: "Fat fields, a modest castle, and an heir problem that half the court has an opinion about." },
    { id: "kingswood", realm: "crownlands", name: "The Kingswood", kind: "wild",
      tags: ["forest", "wild", "crime"], birth: false,
      blurb: "The king's hunting forest, and periodically somebody else's: outlaw bands here have twice become famous enough to need armies." },
    { id: "rooks-rest", realm: "crownlands", name: "Rook's Rest", kind: "castle",
      tags: ["castle", "sea"],
      blurb: "A quiet coastal seat with a very loud history, where a field outside the walls is still called the Burning." },
    { id: "driftmark", realm: "crownlands", name: "Driftmark", kind: "castle",
      tags: ["castle", "island", "port", "sea", "rich"],
      blurb: "High Tide and Spicetown: the seat of the realm's greatest seafaring house, richer than most kingdoms and lower in rank than all of them." },

    /* ============================ THE REACH ============================= */
    { id: "highgarden", realm: "reach", name: "Highgarden", kind: "castle",
      tags: ["castle", "court", "rich", "river"],
      blurb: "Three concentric white walls, terraced gardens and a briar labyrinth, all of it designed to be looked at." },
    { id: "oldtown", realm: "reach", name: "Oldtown", kind: "city",
      tags: ["city", "port", "sea", "market", "holy", "rich"],
      blurb: "The oldest city in Westeros: the Citadel, the Starry Sept, and a lighthouse four hundred feet tall that has never gone out." },
    { id: "citadel", realm: "reach", name: "The Citadel", kind: "keep",
      tags: ["holy", "city", "rich"],
      blurb: "Where maesters are made, one link at a time, in a warren of halls that has quietly outlasted every dynasty it has served." },
    { id: "bitterbridge", realm: "reach", name: "Bitterbridge", kind: "town",
      tags: ["town", "market", "river", "warcamp"],
      blurb: "A market town at the only crossing of the Mander for many leagues, which means every host that goes anywhere camps here." },
    { id: "horn-hill", realm: "reach", name: "Horn Hill", kind: "castle",
      tags: ["castle", "forest"],
      blurb: "Seat of the finest soldier in the Reach, who is a great deal better at war than at fatherhood." },
    { id: "old-oak", realm: "reach", name: "Old Oak", kind: "castle",
      tags: ["castle", "forest"],
      blurb: "An ancient seat on the northern march, watching the road the ironborn used to come down." },
    { id: "ashford", realm: "reach", name: "Ashford", kind: "town",
      tags: ["town", "market", "river"],
      blurb: "A small town on the Cockleswhent, famous out of all proportion for a tourney held here long ago." },
    { id: "brightwater", realm: "reach", name: "Brightwater Keep", kind: "castle",
      tags: ["castle", "rich"],
      blurb: "A wealthy seat held by an ambitious house that would very much like Highgarden and says so only at home." },
    { id: "arbor", realm: "reach", name: "The Arbor", kind: "town",
      tags: ["island", "port", "sea", "rich", "market"],
      blurb: "An island of vineyards and the largest fleet in the south, producing the only wine anyone in King's Landing admits to drinking." },
    { id: "goldengrove", realm: "reach", name: "Goldengrove", kind: "castle",
      tags: ["castle", "forest", "rich"],
      blurb: "Rich orchards and a hall that smells of apples eleven months of the year." },

    /* ========================== THE STORMLANDS ========================== */
    { id: "storms-end", realm: "stormlands", name: "Storm's End", kind: "castle",
      tags: ["castle", "court", "sea"],
      blurb: "One vast drum tower and a wall forty feet thick at its thinnest, which has never fallen to storm or siege." },
    { id: "bronzegate", realm: "stormlands", name: "Bronzegate", kind: "castle",
      tags: ["castle", "forest"],
      blurb: "A castle with bronze-bound gates and a house that has held the pass since the Storm Kings." },
    { id: "nightsong", realm: "stormlands", name: "Nightsong", kind: "castle",
      tags: ["castle", "mountain", "holy"],
      blurb: "A marcher seat in the Dornish hills whose lords have been fighting the same border war for three centuries." },
    { id: "blackhaven", realm: "stormlands", name: "Blackhaven", kind: "castle",
      tags: ["castle", "mountain", "warcamp"],
      blurb: "Black basalt walls in the Dornish Marches, held by a family who take the word 'marcher' as a job description." },
    { id: "evenfall", realm: "stormlands", name: "Evenfall Hall", kind: "castle",
      tags: ["castle", "island", "sea"],
      blurb: "On Tarth, the Sapphire Isle — named not for gems but for the colour of the water, to the disappointment of many raiders." },
    { id: "griffins-roost", realm: "stormlands", name: "Griffin's Roost", kind: "castle",
      tags: ["castle", "sea"],
      blurb: "A castle on a headland above the sea, approached by a causeway that can be swept by archers along its whole length." },
    { id: "summerhall", realm: "stormlands", name: "Summerhall", kind: "ruin",
      tags: ["ruin", "forest"], birth: false,
      blurb: "A pleasure palace burned in a single night with a king and half his family inside. Nobody has rebuilt it, and nobody quite says why." },
    { id: "weeping-town", realm: "stormlands", name: "The Weeping Town", kind: "town",
      tags: ["town", "port", "sea", "poor"],
      blurb: "A grey little port on the southern coast that has been sacked by Dornish raiders more times than its septon can count." },
    { id: "mistwood", realm: "stormlands", name: "Mistwood", kind: "castle",
      tags: ["castle", "forest", "sea"],
      blurb: "A damp seat in the rainwood, where the trees drip even when it is not raining, which is rarely." },

    /* ============================== DORNE ============================== */
    { id: "sunspear", realm: "dorne", name: "Sunspear", kind: "castle",
      tags: ["castle", "court", "hot", "desert"],
      blurb: "Three towers and a shadow city, a maze of a seat that grew rather than was built, and the only capital the Dornish have ever needed." },
    { id: "shadow-city", realm: "dorne", name: "The Shadow City", kind: "town",
      tags: ["town", "market", "poor", "hot"],
      blurb: "The warren of mud-brick under Sunspear's walls: bazaars, brothels, and a great deal of business the Martells prefer not to see." },
    { id: "planky-town", realm: "dorne", name: "Planky Town", kind: "town",
      tags: ["town", "port", "sea", "market", "river", "hot"],
      blurb: "A floating town of lashed-together boats at the mouth of the Greenblood, where the orphans of the river trade with the world." },
    { id: "yronwood", realm: "dorne", name: "Yronwood", kind: "castle",
      tags: ["castle", "mountain", "hot"],
      blurb: "The greatest Dornish seat after Sunspear, held by the Bloodroyal, who has never entirely forgiven the Martells for winning." },
    { id: "starfall", realm: "dorne", name: "Starfall", kind: "castle",
      tags: ["castle", "sea", "river", "holy"],
      blurb: "A pale castle at the mouth of the Torentine, where a sword of fallen-star metal is kept and very rarely drawn." },
    { id: "hellholt", realm: "dorne", name: "Hellholt", kind: "castle",
      tags: ["castle", "desert", "hot"],
      blurb: "A castle in the deep sand with a reputation for poison, in a family with a reputation for using it." },
    { id: "sandstone", realm: "dorne", name: "Sandstone", kind: "castle",
      tags: ["castle", "desert", "hot"],
      blurb: "Pale domes in the red waste of the Dornish desert, where water is counted more carefully than gold." },
    { id: "vaith", realm: "dorne", name: "Vaith", kind: "castle",
      tags: ["castle", "river", "desert", "hot"],
      blurb: "A small holding at the fork of a river that is dry more often than it is wet." },
    { id: "kingsgrave", realm: "dorne", name: "Kingsgrave", kind: "castle",
      tags: ["castle", "mountain", "hot"],
      blurb: "A mountain seat named for a king who was buried here by the people who killed him." },
    { id: "boneway", realm: "dorne", name: "The Boneway", kind: "wild",
      tags: ["mountain", "wild", "hot", "warcamp"], birth: false,
      blurb: "One of two passes into Dorne, littered with the bones the name promises, most of them belonging to invaders." },

    /* ========================= THE FREE CITIES ========================== */
    { id: "braavos", realm: "free-cities", name: "Braavos", kind: "city",
      tags: ["city", "port", "sea", "market", "rich", "free"],
      blurb: "A hundred islands in a lagoon, founded by escaped slaves, ruled by a Sealord, and holding the debts of half the world." },
    { id: "ragmans-harbor", realm: "free-cities", name: "Ragman's Harbor", kind: "city",
      tags: ["city", "port", "poor", "crime", "market"],
      blurb: "The Braavosi harbour for everyone else's ships: mummers, sailors, and the cheapest lodgings in the city." },
    { id: "house-black-white", realm: "free-cities", name: "The House of Black and White", kind: "keep",
      tags: ["holy", "city", "crime"], birth: false,
      blurb: "A temple of black and white weirwood on a Braavosi hill, where a certain kind of prayer is answered by a certain kind of servant." },
    { id: "iron-bank", realm: "free-cities", name: "The Iron Bank", kind: "keep",
      tags: ["city", "rich", "market"], birth: false,
      blurb: "Not a place so much as a sentence everyone finishes the same way: the Iron Bank will have its due." },
    { id: "pentos", realm: "free-cities", name: "Pentos", kind: "city",
      tags: ["city", "port", "sea", "market", "rich", "free"],
      blurb: "Square brick towers and fat magisters, a city that buys its peace from Braavos and pretends it chose to." },
    { id: "myr", realm: "free-cities", name: "Myr", kind: "city",
      tags: ["city", "port", "sea", "market", "rich", "slave"],
      blurb: "Glass, lace and lenses — the finest craftsmen in the world, and a great many of them are somebody's property." },
    { id: "lys", realm: "free-cities", name: "Lys", kind: "city",
      tags: ["city", "port", "sea", "rich", "slave", "hot"],
      blurb: "A warm island city of pillow houses and poisoners, where beauty is a crop and both trades are entirely respectable." },
    { id: "tyrosh", realm: "free-cities", name: "Tyrosh", kind: "city",
      tags: ["city", "port", "sea", "market", "crime", "slave"],
      blurb: "A brawling dye-stained rock in the Stepstones, home to the loudest sellsword market on the narrow sea." },
    { id: "volantis", realm: "free-cities", name: "Volantis", kind: "city",
      tags: ["city", "port", "sea", "river", "market", "slave", "holy", "hot"],
      blurb: "The first daughter of Valyria: a black wall a free man may not stand upon, and five slaves for every one of him." },
    { id: "norvos", realm: "free-cities", name: "Norvos", kind: "city",
      tags: ["city", "river", "holy", "cold"],
      blurb: "High city and low city, joined by stone steps, ruled by bearded priests and their axemen and by nobody else at all." },
    { id: "qohor", realm: "free-cities", name: "Qohor", kind: "city",
      tags: ["city", "forest", "market", "holy", "slave"],
      blurb: "The city of sorcerers on the edge of a black forest, where they still know how to fold Valyrian steel and will not say how." },
    { id: "lorath", realm: "free-cities", name: "Lorath", kind: "city",
      tags: ["city", "island", "port", "sea", "poor", "cold"],
      blurb: "The poorest and least-visited of the nine, on cold northern islands, with a labyrinth nobody built and everybody avoids." },
    { id: "disputed-lands", realm: "free-cities", name: "The Disputed Lands", kind: "wild",
      tags: ["wild", "warcamp", "hot"], birth: false,
      blurb: "The ground Myr, Lys and Tyrosh have been fighting over for centuries — the best place in the world to be paid to fight, and the worst to farm." },

    /* ======================== THE DOTHRAKI SEA ========================== */
    { id: "vaes-dothrak", realm: "dothraki-sea", name: "Vaes Dothrak", kind: "city",
      tags: ["city", "market", "holy", "free"],
      blurb: "A city with no walls, big enough to hold every khalasar at once and empty nearly all the time. To draw a blade here is death." },
    { id: "khalasar", realm: "dothraki-sea", name: "A khalasar on the move", kind: "warcamp",
      tags: ["warcamp", "wild", "free"],
      blurb: "Forty thousand riders, their horses, their herds and their captives, moving across the grass as one enormous slow animal." },
    { id: "womb-of-the-world", realm: "dothraki-sea", name: "The Womb of the World", kind: "wild",
      tags: ["holy", "wild"], birth: false,
      blurb: "The lake at the heart of the grass, where the first man is said to have ridden out of the water on the first horse." },
    { id: "lhazar", realm: "dothraki-sea", name: "Lhazar", kind: "village",
      tags: ["village", "poor", "wild", "hot"],
      blurb: "Lamb men and their herds south of the grass, raided so regularly that raiding them barely counts as war." },
    { id: "ny-sar", realm: "dothraki-sea", name: "Ny Sar", kind: "ruin",
      tags: ["ruin", "river", "wild"], birth: false,
      blurb: "One of the drowned Rhoynish cities, its fountains still standing in a river that runs through the empty streets." },

    /* ========================== SLAVER'S BAY =========================== */
    { id: "astapor", realm: "slavers-bay", name: "Astapor", kind: "city",
      tags: ["city", "port", "sea", "slave", "market", "hot"],
      blurb: "Red brick and dust, and the only place in the world that makes Unsullied — a process the Good Masters will describe over dinner." },
    { id: "yunkai", realm: "slavers-bay", name: "Yunkai", kind: "city",
      tags: ["city", "port", "sea", "slave", "market", "rich", "hot"],
      blurb: "The Yellow City, which trains bed slaves rather than soldiers and considers itself the more refined for it." },
    { id: "meereen", realm: "slavers-bay", name: "Meereen", kind: "city",
      tags: ["city", "port", "sea", "slave", "market", "rich", "hot", "court"],
      blurb: "The greatest of the three, with a pyramid eight hundred feet high and a fighting pit that seats twenty thousand." },
    { id: "fighting-pits", realm: "slavers-bay", name: "The Fighting Pits", kind: "keep",
      tags: ["slave", "city", "market", "hot"], birth: false,
      blurb: "Daznak's, Ghrazz's and a dozen smaller — where men, women and beasts are matched for money in front of a roaring city." },
    { id: "new-ghis", realm: "slavers-bay", name: "New Ghis", kind: "city",
      tags: ["city", "island", "port", "sea", "slave", "hot"],
      blurb: "An island city that drills its legions in the old Ghiscari manner and has never quite got over the fall of the old empire." },
    { id: "mantarys", realm: "slavers-bay", name: "Mantarys", kind: "city",
      tags: ["city", "wild", "hot", "poor"],
      blurb: "A city of monsters on the demon road, where the Doom got close enough to leave marks on the children." },

    /* ========================= THE SUMMER ISLES ======================== */
    /* The `island` tag is what makes a hull necessary — see needsSea() in
       engine.js. Every place in this realm needs it or the game will happily
       let a man walk to the Summer Isles from Volantis. */
    { id: "tall-trees-town", realm: "summer-isles", name: "Tall Trees Town", kind: "city",
      tags: ["city", "island", "port", "sea", "market", "rich", "hot", "free"],
      blurb: "Capital of Walano and the great harbour of the isles, where swan ships load spice, gold and feathers for the whole world." },
    { id: "lotus-point", realm: "summer-isles", name: "Lotus Point", kind: "town",
      tags: ["town", "island", "port", "sea", "holy", "hot"],
      blurb: "A green harbour town famous for its temples, its archers and its extremely firm views on unnecessary war." },
    { id: "last-lament", realm: "summer-isles", name: "Last Lament", kind: "village",
      tags: ["village", "island", "sea", "holy", "hot"],
      blurb: "Where the dead are mourned for a full year, and the mourning is louder and more musical than anything in Westeros." },

    /* ======================== THE FURTHER EAST ========================= */
    { id: "qarth", realm: "the-east", name: "Qarth", kind: "city",
      tags: ["city", "port", "sea", "market", "rich", "hot", "holy"],
      blurb: "Three walls carved with battles, marvels and things nobody will explain, and merchants who consider themselves the centre of creation." },
    { id: "house-undying", realm: "the-east", name: "The House of the Undying", kind: "keep",
      tags: ["holy", "city", "hot"], birth: false,
      blurb: "A long grey building with no windows, where the warlocks drink shade-of-the-evening and outlive their own usefulness." },
    { id: "red-waste", realm: "the-east", name: "The Red Waste", kind: "wild",
      tags: ["desert", "wild", "hot"], birth: false,
      blurb: "A dead land east of the grass where the wells are poisoned and the cities are bones." },
    { id: "asshai", realm: "the-east", name: "Asshai-by-the-Shadow", kind: "city",
      tags: ["city", "port", "sea", "holy", "wild"],
      blurb: "A city of oily black stone at the end of the world, where nothing grows, no child is born, and everyone wears a mask." },
    { id: "yi-ti", realm: "the-east", name: "Yin, in Yi Ti", kind: "city",
      tags: ["city", "port", "market", "rich", "hot"],
      blurb: "A golden empire so far east that Westeros is a rumour there, currently in possession of somewhere between one and four emperors." },
    { id: "ibben", realm: "the-east", name: "Port of Ibben", kind: "city",
      tags: ["city", "island", "port", "sea", "cold", "poor"],
      blurb: "A sooty whaling city in the cold north of Essos, whose short, thickset people build the ugliest and sturdiest ships afloat." },
  ],
};
