/* GoT wiki — A Feast for Crows, chapter-by-chapter. Original prose. */
Object.assign(WIKI_EXTRA, {
  "chapter:4-1": {
    paras: [
      "The book opens nowhere near a throne. A maester named Alleras and the drunk archmaester Pate stand watch over Oldtown's rooftops for a comet, and through them the reader gets its first glimpse of the Citadel as an institution — a place of forging chains, hoarding secrets and arguing about the ravens' true purpose, run by old men who distrust magic even as glass candles start burning in locked rooms. A second Pate, a poor novice who has failed his exams and hates every fat, comfortable maester above him, meets a stranger in a tavern who offers a fortune — a golden dragon coin — for a stolen Citadel key and a night with a girl too pretty for the price. He takes the bait and dies for it, throat opened, the coin left cooling in his own mouth as the stranger walks off wearing a face that is not quite the one it started with.",
      "The chapter is stitched from a single night's worth of overlapping vantage points — Pate's fatal bargain, the older novice Alleras tracking the comet's omens across the rooftops with a friend, and the doomed boy's own dawning, too-late realization that the price of his stolen key was never going to be a coin. The stranger who pays him is sketched only in fragments — a face that seems to shift in torchlight, a voice too pleasant for the errand — and readers who have already met the Faceless Men through Arya's Braavosi chapters will recognize the method a full book before Oldtown's own maesters ever think to look for it.",
      "It is a strange, sideways door into a book that will spend forty-five more chapters almost entirely in the south, and that is the point: A Feast for Crows announces from its first page that this is a story about institutions outliving the people who run them — the Citadel, the Faith, the ironborn's driftwood crown, the Iron Throne itself — and about faceless things wearing familiar skins. No one in King's Landing will hear about a dead novice in Oldtown, and the reader is meant to file the name Pate away and forget it, which is exactly the trick the chapter is built to pull.",
    ],
  },
  "chapter:4-2": {
    paras: [
      "Aeron Greyjoy, once the least devout of Balon's brothers, has become the Damphair — a priest of the Drowned God who drowns his converts half to death and calls it baptism. He surfaces from his wandering ministry to hard news: his brother Balon is dead, blown from a rope bridge in a storm at Pyke, and the succession is a vacuum the ambitious will race to fill. Aeron distrusts every candidate on offer, especially the brother he has not seen in years, and falls back on the oldest law the ironborn have — not inheritance but the kingsmoot, an ancient assembly of captains and ship's crews who will shout a king into being on Old Wyk, the way it was done before the Iron Islands ever bent the knee to a mainland crown.",
      "The chapter reintroduces the ironborn as a culture unto themselves — reaving, drowning, praying to a god who demands salt water instead of sanctuary — and sets up the book's second major plot engine alongside King's Landing's court politics. Balon's death (confirmed here, having happened just off-page) leaves three legitimate claimants circling: Aeron's zealotry rules him out as a candidate but not as a kingmaker, and his summons for a kingsmoot is the ironborn's answer to a succession crisis that the rest of Westeros would have settled with a simple, bloody line of inheritance.",
    ],
  },
  "chapter:4-3": {
    paras: [
      "Areo Hotah, Prince Doran Martell's Norvoshi captain of guards, watches Sunspear absorb the shock of Oberyn Martell's death in King's Landing — killed, skull crushed, by the Mountain in trial by combat, with Tyrion Lannister's guilt still unavenged in Dornish eyes. The Sand Snakes, Oberyn's eight bastard daughters by as many mothers, arrive furious and united in exactly one demand: blood, now, for their father. Doran, prematurely old and crippled by gout, does the opposite of what Dorne expects of him — he has three of the eldest Sand Snakes confined rather than armed, and endures their contempt and his own household's suspicion that grief has made him a coward.",
      "This is the reader's introduction to Doran as a character defined entirely by the gap between what he shows and what he plans — a gap so wide that even his own family reads it as weakness. Hotah's outsider perspective, watching without fully understanding, lets the chapter plant Dorne as a court playing a much longer, much stranger game than open war, while making clear that the anger in Sunspear is real and combustible regardless of what its prince intends to do with it.",
    ],
  },
  "chapter:4-4": {
    paras: [
      "Cersei's first chapter of her own book opens over her father's corpse — Tywin Lannister lying in state in the Great Sept with painted glass eyes and a stench the embalmers cannot quite mask, dead by his own son's crossbow bolt though the official story blames an unnamed assassin. Cersei watches the mourners file past and takes hold of the regency for her boy-king Tommen with both hands, savoring a power she has wanted her whole life and never quite been allowed. Woven through the grief and the funeral logistics is Maggy the Frog's old prophecy, unspooling in memory: three children dead in gold shrouds, a queen younger and more beautiful to cast her down, and a valonqar — a little brother — whose hands will close around her throat.",
      "The chapter establishes the engine that will drive Cersei's entire arc: real power, finally hers, filtered through a mind that trusts no one and reads every ally as a future betrayer. Tywin's death (having occurred at the close of the previous book) leaves a vacuum Cersei is determined to fill on her own terms rather than share with Jaime or any council of steady hands, and the prophecy that has haunted her since childhood is reintroduced here as the lens — increasingly paranoid, increasingly self-fulfilling — through which she will interpret every threat, real or imagined, for the rest of the book.",
    ],
  },
  "chapter:4-5": {
    paras: [
      "Brienne of Tarth rides the Duskendale road with Podrick Payne, wielding Oathkeeper, the Valyrian steel blade Jaime gave her along with a vow: find Sansa Stark and Arya Stark, and keep them safe. She interrogates everyone she passes — innkeeps, septons, drovers — after a highborn girl of three-and-ten with auburn hair, and gets nothing but blank looks, rumor and the general devastation of a riverlands scoured flat by years of war. The search is less a plot than a texture: starving villages, broken bridges, orphaned children, the wreckage the War of the Five Kings left behind once the armies moved on.",
      "This chapter sets Brienne's questline in motion as the book's spine — a knight-errant's quest structure laid directly over a devastated countryside, so that every failed lead doubles as a tour of what five kings' worth of war actually cost the people who never held a crown. Her literal-mindedness about her vow (a highborn maid of three-and-ten, auburn hair, exactly) will be both her integrity and her blind spot for the rest of the book, since the girl she is describing is not the girl she will eventually need to find.",
    ],
  },
  "chapter:4-6": {
    paras: [
      "Jon Snow, now Lord Commander at Castle Black, gives Samwell Tarly an order dressed as an honor: sail south with Maester Aemon, with Gilly, and with the infant everyone believes is Gilly's son by Craster — though the reader knows, even if the wider Watch does not, that the babe in question is not quite what he seems. Sam is bound, ultimately, for Oldtown and the Citadel, to earn a maester's chain and become the trained mind Castle Black desperately lacks. He accepts with his usual mix of terror and loyalty, aware that Jon is protecting him from a war he is unsuited to fight and sending him toward a different, quieter kind of usefulness.",
      "The chapter is a hinge for two of the book's throughlines at once: it launches Sam's long sea voyage toward the Citadel prologue's mystery, and it quietly seeds one of the series' most consequential swaps — the identity of the child traveling under Gilly's name — without spelling it out. Jon's authority here is still fresh and untested, a Lord Commander making hard calls about who serves the Watch best where, a theme the reader has already watched cost him popularity among his brothers.",
    ],
  },
  "chapter:4-7": {
    paras: [
      "Arya Stark arrives in Braavos with nothing but a coin, a name — Jaqen H'ghar's parting gift, valar morghulis — and a list of enemies she recites like a prayer. The Titan of Braavos straddles the harbor, immense and alien, and Arya's arrival in the free city is rendered as culture shock: canals instead of roads, a language she does not speak, a girl utterly friendless in the most theatrical city in the known world. She finds her way, eventually, to a plain building with a door of ebony and weirwood, presents the coin, and speaks the password — valar dohaeris, all men must serve — and is taken in by the House of Black and White, the temple of the many-faced god of death.",
      "This chapter formally opens Arya's apprenticeship among the Faceless Men, a religious order built entirely around the idea that death is a gift and identity a costume to be shed. It reframes her entire arc — assassin's list, sword skill, the survival instincts hammered into her since Ned's execution — as training she was already halfway through before she ever knew the school existed. The House's servants who greet her (kindly, opaque, unnamed) establish the order's central bargain immediately: everything is available here, at the price of everything she is.",
    ],
  },
  "chapter:4-8": {
    paras: [
      "Cersei's second chapter shows her regency in action, and it is not encouraging. She fills the small council with men chosen for their pliability rather than their competence — flatterers, debtors, relatives she can lean on — reasoning that a council of weak men cannot conspire against her the way Tywin's strong ones might have. She dismisses warnings, overrules Jaime's caution, and privately congratulates herself on ruling more wisely than her father ever did, mistaking the absence of open opposition for the presence of a plan.",
      "The chapter is a portrait of a woman finally handed the power she always believed was rightfully hers, discovering — or rather, refusing to discover — that competence and confidence are not the same thing. Every choice she makes here (Harys Swyft, Aurane Waters, Qyburn's quiet rise as the council's pet alchemist-turned-something-worse) is a small brick in a structure that will collapse spectacularly by the book's end. Cersei believes she is building a fortress; the reader can already see it is a house of cards stacked by someone with no architect's eye.",
    ],
  },
  "chapter:4-9": {
    paras: [
      "Jaime Lannister keeps vigil over his father's rotting corpse in the sept, sword hand gone, identity in freefall, watching mourners file past a man he both feared and, in his own complicated way, respected. Cersei corners him with a request that should be simple — take the Handship, rule beside her as they always imagined a Lannister regency might work — and Jaime refuses. He has sworn to the Kingsguard, he tells her, and he means to actually be what the white cloak claims he is for the first time in his life, guarding the king rather than running the kingdom from behind him.",
      "It is a small scene with enormous consequences: the first real fracture between the twins who have spent the whole series as functionally one person in two bodies. Jaime's refusal is not spite — it's the first visible fruit of his road with Brienne, his growing discomfort with being merely Cersei's sword and voice. Cersei reads it as betrayal, or worse, rejection, and the chapter plants the seed of the estrangement that will define both of their arcs through the rest of the book, as each sibling starts making decisions the other would never have sanctioned.",
    ],
  },
  "chapter:4-10": {
    paras: [
      "Brienne's search widens: at Rosby and along the roads beyond it, she picks up an unwanted traveling companion in Podrick Payne, the loyal, tongue-tied squire who attached himself to Tyrion during the Blackwater and has nowhere else to go. She distrusts him, feeds him anyway, and finds herself reluctantly responsible for a second person's survival on top of her own quest. A lead surfaces pointing her toward Crackclaw Point, a wild, lawless stretch of coast, guided by a local hunter called Nimble Dick Crabb who promises knowledge of the region's hidden corners in exchange for coin and company.",
      "The chapter deepens Brienne's arc from lone knight-errant into reluctant leader of a small, mismatched party, and it is the first hint that this quest will not stay simple — Crackclaw Point has a reputation, and Nimble Dick's confidence reads, even here, like the kind that gets people killed. Podrick's attachment to her is played for quiet comedy and quiet pathos at once: a boy who has already lost one protector clinging to whichever knight will have him, and Brienne slowly, unwillingly, becoming someone worth clinging to.",
    ],
  },
  "chapter:4-11": {
    paras: [
      "High in the Eyrie, Sansa Stark — living under Littlefinger's invented identity as his bastard daughter Alayne Stone — spends her days managing Robert Arryn, her sickly, terrified young cousin, who screams for the Moon Door whenever he is crossed and needs constant, exhausting soothing to function at all. Below them, trouble is brewing that Alayne cannot fully see: the Lords Declarant, a faction of Vale nobles, are gathering to challenge Petyr Baelish's guardianship of Sweetrobin, suspicious of how convenient Lysa Arryn's death at the Moon Door was, and armed with a ballad — composed by the surviving singer Marillion, who was made to take the fall for Lysa's murder — that hints at more than the official story admits.",
      "The chapter is a masterclass in dramatic irony: the reader, unlike the Lords Declarant, knows exactly how Lysa died and at whose hand, which makes every step of Littlefinger's approaching political crisis feel like a fuse burning toward a room only Sansa fully understands the danger of. Sansa's competence as Alayne — patient, watchful, endlessly diplomatic with a boy who could have her thrown out a door on a whim — is the chapter's real subject: she is becoming, in exile and disguise, exactly the kind of political operator the Eyrie's regency actually needs.",
    ],
  },
  "chapter:4-12": {
    paras: [
      "Asha Greyjoy — introduced here by her book name, called Yara in the show — musters her uncles and captains at Ten Towers ahead of the kingsmoot, building a coalition to press her own claim to the Seastone Chair. She argues her case with wit, sea-salt bluntness and an axe she is plainly willing to use, positioning herself as Balon's only child who ever actually loved the Iron Islands rather than merely wanting to rule them. Her uncles Victarion and Euron loom as rival claimants even before the assembly convenes — Euron mostly absent and mysterious, having been gone from the Iron Islands for years on reaving voyages no one can fully account for.",
      "This chapter is Asha's formal introduction as a political actor rather than merely Theon's more capable sister, and it frames the kingsmoot to come as a genuine contest rather than a formality. Her claim is unprecedented — the ironborn have never crowned a woman — and the chapter makes clear she knows it, campaigning not on tradition but on competence and blood loyalty to a homeland her rivals have spent their strength on: Euron on distant plunder, Victarion on obedience to a brother now dead.",
    ],
  },
  "chapter:4-13": {
    paras: [
      "Lady Taena of Myr, a Tyrell-aligned lady of the court, insinuates herself into Cersei's confidence, whispering encouragement laced with poison — flattering the queen's judgment, stoking her suspicions of Margaery, and positioning herself as the one truly loyal friend in a court of schemers. Cersei, flattered and lonely in the specific way of someone who has just seized power and cannot yet trust anyone who might want to take it back, elevates the low-born Kettleblack brothers to key positions of trust, while her small council quietly shrinks as the competent men drift away or are pushed out. Margaery, still married to Tommen and radiating public charm, becomes an object of daily, escalating suspicion in Cersei's mind.",
      "The chapter tightens Cersei's isolation from anyone who might actually check her judgment — Taena is not a co-conspirator so much as an enabler, agreeing with whatever Cersei already wants to believe. The Kettleblacks' rise plants the specific instrument (Osney Kettleblack, chiefly) that Cersei will later use in her scheme against Margaery, while the steady erosion of steady voices around her — the very thing she engineered in her second chapter — starts to look less like consolidation of power and more like a woman sealing herself into a room with only flatterers for company.",
    ],
  },
  "chapter:4-14": {
    paras: [
      "In Sunspear, Ser Arys Oakheart of the Kingsguard — sworn to guard Myrcella Baratheon, sent to Dorne as a hostage-cum-fostered princess years earlier — is slowly, deliberately talked out of his white cloak's loyalties by Arianne Martell, Doran's daughter and heir. Arianne is beautiful, clever and furious at her father's apparent passivity since Oberyn's death, and she recruits Arys not through simple seduction but through a genuine political argument: crown Myrcella under Dornish law, which allows female inheritance by right of birth order rather than favoring sons, and let Dorne rise in her name against a Lannister-Baratheon regime Arianne believes has wronged her house.",
      "The chapter is the formal launch of Arianne's queenmaker plot — one of the book's central schemes, and one built on a real structural fact about Dorne that the rest of Westeros keeps forgetting: Dornish succession does not prefer sons over daughters. Arys's seduction is played with real sympathy for a good, lonely knight talked into treason by a woman who genuinely believes her cause is just, which makes the scheme feel less like villainy and more like the logical extension of a house that has spent the whole series watching its rightful claims get overridden by other kingdoms' rules.",
    ],
  },
  "chapter:4-15": {
    paras: [
      "Brienne's party reaches the Whispers on Crackclaw Point, following Nimble Dick's lead — and finds only the aftermath of the Brave Companions, the mercenary company known as the Bloody Mummers, who have already been through and left ruin behind them. In the fighting that follows, Brienne kills three men, including the fool called Shagwell, one of the Mummers' most sadistic members, dispatched without ceremony or humor despite his name. Afterward she is violently, physically sick — not from fear, but from the plain animal weight of having killed people, however much they deserved it.",
      "This chapter is important less for the plot advance — Nimble Dick's lead dries up, another dead end in the search for Sansa — than for what it says about Brienne as a fighter: unlike the swaggering killers she keeps encountering, violence costs her something every time, and the book takes care to show the bill coming due immediately, in her own body, rather than letting a kill scene pass as simple triumph. It's a deliberate contrast with how combat gets glamorized elsewhere in the story, and it keeps Brienne's moral seriousness — one of her defining traits — visibly intact even as her body count climbs.",
    ],
  },
  "chapter:4-16": {
    paras: [
      "Aboard the Cinnamon Wind, Sam's sea voyage toward Oldtown continues to be an ordeal rather than an adventure — storms batter the small ship, seasickness and cramped misery dominate the days, and Maester Aemon, ancient and blind, visibly weakens with every league of salt water put between him and the Wall he served for most of a century. Gilly tends both Aemon and the baby with a competence Sam keeps failing to match, while Sam himself frets, apologizes, and generally proves that his appointment to this mission was about protecting him more than trusting him.",
      "The chapter is transitional in the way sea-voyage chapters often are — measuring out distance and attrition rather than incident — but it is doing real work underneath: Aemon's decline is now visibly a countdown, not a background detail, and the reader is being prepared for a death that the voyage's slow, grinding hardship makes feel inevitable rather than sudden. Sam's ongoing inadequacy against real danger, contrasted with his genuine tenderness toward Gilly and the child, keeps reinforcing exactly what kind of use the Citadel — and not a sword — is meant to make of him.",
    ],
  },
  "chapter:4-17": {
    paras: [
      "By night, Jaime spars with Ser Ilyn Payne, the mute former headsman turned Kingsguard brother — practice with a partner incapable of mocking his ruined swordarm aloud, which is precisely why Jaime seeks him out. By day he watches Cersei govern from the sidelines, forced into silence by his own refusal of the Handship, biting down on objections to decisions he thinks are reckless because he has ceded any formal claim to a say in them. The distance between the twins widens with each council meeting he sits through and says nothing in.",
      "The training sessions function as the chapter's real subject: Jaime relearning how to be dangerous with his off hand, which is also, unmistakably, Jaime relearning who he is without the identity — Kingslayer, finest swordsman in Westeros — that defined him for two decades. His forced political silence, meanwhile, is presented as its own kind of self-punishment, a man watching a slow-motion mistake unfold and choosing principle over intervention, even as the cost of that choice compounds visibly with every chapter Cersei is left unchecked.",
    ],
  },
  "chapter:4-18": {
    paras: [
      "Maggy the Frog's prophecy resurfaces in full in Cersei's memory and dreams — the woods witch's tent from her childhood, the promise of three golden-shrouded children, a younger and more beautiful queen to take everything from her, and the valonqar whose hands will close about her throat. Cersei, increasingly convinced that Margaery is the queen the prophecy warned her about, starts treating ordinary court rivalry as an existential, prophesied threat, coloring every decision that follows with a fear she cannot voice to anyone without admitting how much stock she puts in an old woman's curse.",
      "This chapter functions as connective tissue for Cersei's psychology rather than plot event — a return to the well the book opened with, deepened now that two of the three children (in the reader's knowledge, if not yet confirmed on the page) are already lost. It cements the prophecy as the true engine of Cersei's paranoia for the rest of the book: not simple cruelty or lust for power, but a woman trying to out-maneuver a fate she believes has already been written, and making it worse with every move.",
    ],
  },
  "chapter:4-19": {
    paras: [
      "Victarion Greyjoy, the Iron Fleet's grim and literal-minded captain, arrives at Old Wyk for the kingsmoot among more longships than the Iron Islands have gathered in living memory. The assembled captains weigh their choices — Asha's wit and popularity against Victarion's raw martial reputation — a contest that seems settled and predictable right up until a strange sail appears on the horizon, marked with a red eye, that changes the calculus for everyone watching it approach.",
      "The chapter sets the board for the kingsmoot proper: two credible, known claimants each with real support, and the ominous late arrival of a third whose reputation (reaver, kinslayer, sorcerer by rumor) precedes him by years. Victarion's simplicity — a warrior who believes in strength as the only legitimate argument — is established here specifically so his later manipulation by his brother Euron lands as tragedy rather than surprise: he is exactly the kind of honest, blunt man a clever liar finds easiest to use.",
    ],
  },
  "chapter:4-20": {
    paras: [
      "The kingsmoot convenes on Nagga's hill, within the rib-cage-like driftwood halls said to be built from a sea dragon's bones, and the succession is decided in open assembly. Asha offers the captains peace and prosperity; Victarion offers strength and continuity. Then Euron Crow's Eye steps forward and offers something neither rival can match — dragons, or the promise of them, and a horn he claims was salvaged from the smoking ruins of Valyria itself, capable of binding dragons to his will. The ironborn, hungry for glory beyond raiding fishing villages, choose Euron's madness over his niece's sense and his brother's steadiness.",
      "Euron's pitch works because he tells the assembled captains exactly what they want to hear in exactly the ironborn's own register: not peace, which Asha offers and which reads to men raised on reaving as surrender by another name, and not mere strength, which Victarion offers and which only promises more of the same grinding raids the islands have run for generations, but conquest without precedent — a horn pulled from Valyria's ashes, magic strong enough, he swears, to bind living dragons to an ironborn's will, and a fleet aimed not at fishing villages but at an empire. He invokes the Grey King's old paradise with Nagga's bones arched over his head as he speaks, and the theater is not incidental — Euron understands, better than either rival claimant, that a kingsmoot is a performance as much as it is a vote.",
      "This is one of the book's three pivotal chapters, and it reorders the entire Iron Islands plot at a stroke: Euron Greyjoy — absent, mysterious, reputed a kinslayer and worse — becomes King of the Iron Islands by force of rhetoric and a horn no one present can verify. Asha loses cleanly and honorably; Victarion is publicly outmaneuvered by his own brother and immediately reassigned to Euron's service rather than rewarded for his loyalty to their dead brother's memory. The chapter plants dragons as an ironborn ambition for the first time — Euron intends to sail for Daenerys, horn in hand — and turns what looked like a succession squabble into a plot with implications for the entire continent.",
    ],
  },
  "chapter:4-21": {
    paras: [
      "Brienne's road brings her to Maidenpool, held by Lord Randyll Tarly — Sam's father, though Brienne has no cause to know or care about the connection — who dispenses the king's justice with an iron hand and open contempt for a woman traveling armed and armored like a knight. Amid the harsh legal theater of Tarly's court, Brienne genuinely acquires a squire for the first time — young Podrick's role solidifies into something more formal — and picks up a new lead, a septon's road heading west, toward yet another rumor of a highborn girl matching Sansa's description.",
      "The chapter uses Randyll Tarly as a mirror for everything wrong with how Westeros treats women who choose the sword: he is competent, just by his own narrow lights, and utterly incapable of seeing Brienne as anything but an aberration to be mocked or dismissed. It's a bracing contrast to Jaime's growing respect for her, deepening the book's throughline about how differently men read the same woman depending on whether they've actually watched her fight and keep faith.",
    ],
  },
  "chapter:4-22": {
    paras: [
      "Arianne Martell's queenmaker plot reaches its bloody climax on the Greenblood: she spirits Myrcella Baratheon out of Sunspear intending to crown her under Dornish law, but the plan is betrayed and intercepted. Gerold Dayne — Darkstar, a dangerous and unpredictable Dornish knight — attacks the party with a blade, and Areo Hotah's longaxe answers in the chaos, but not before Ser Arys Oakheart, Myrcella's sworn Kingsguard protector and Arianne's own recruited lover, dies defending her — and Myrcella herself loses an ear to Darkstar's blade in the melee.",
      "This chapter is the queenmaker plot's violent collapse, and it's built to feel like a punishment for good intentions poorly executed: Arianne's scheme, however politically sound on paper, gets a good man killed and a child maimed, and reveals that she does not actually control the Dornish factions she thought she was activating — Darkstar answers to no one's plan but his own. Ser Arys Oakheart, the honorable knight introduced falling for a cause he believed in, dies for a plot his princess never fully leveled with him about, closing his arc as one of the book's genuine, avoidable tragedies.",
    ],
  },
  "chapter:4-23": {
    paras: [
      "In Braavos, Arya — now going by Cat of the Canals, apprenticed to a kindly fishmonger's stall as much as to the House of Black and White — sells cockles, runs errands, and quietly gathers information the way she has been trained to since Syrio Forel's lessons a lifetime ago. Word reaches her of a deserter from the Night's Watch, Dareon, singing for coin and silks in the Happy Port, having abandoned his vows and his brothers to live comfortably in a foreign city. Arya — acting, it's implied, at least partly under the House's sanction as practice — kills him.",
      "The chapter marks Arya's first confirmed kill as a Faceless Men trainee (as opposed to killings from earlier in the war, done for pure survival), and it's chosen carefully: Dareon is not an innocent by the story's own moral logic — he swore an oath to the realm's defense and chose comfort over duty while his brothers starved and died at the Wall — which lets the book use him to test whether Arya can kill dispassionately, for the god, rather than personally, for her list. She can. That distinction is exactly what the House of Black and White is trying to train into her, and exactly what she will keep fighting against for the rest of her arc.",
    ],
  },
  "chapter:4-24": {
    paras: [
      "Under her Alayne Stone identity, Sansa watches the Lords Declarant arrive at the Gates of the Moon to formally challenge Petyr Baelish's guardianship of Robert Arryn and, implicitly, his account of how Lysa Arryn died. Littlefinger meets the threat with characteristic guile rather than force: he buys off Lyn Corbray, one of the more dangerous and mercenary lords among the Declarants, with the promise of a single, carefully planted treason charge against a rival, and the coalition against him scatters under a mixture of bribery, courtesy and misdirection before it can ever consolidate into real danger.",
      "The chapter is a showcase for Littlefinger's specific genius — not brute force, which he has none of, but the ability to read exactly which lever moves which man, and to buy loyalty at a price cheaper than its apparent value. Sansa, watching this unfold from close quarters as Alayne, is getting a graduate education in precisely this kind of statecraft, absorbing lessons she will put to very different use once she is done being anyone's pawn — the chapter functions as much as her tutorial as it does Littlefinger's victory lap.",
    ],
  },
  "chapter:4-25": {
    paras: [
      "Facing a crown deep in debt to the Faith of the Seven — loans Aerys and Robert both took out and never repaid — Cersei strikes what she believes is a masterstroke: she restores the Faith Militant, the religious knightly orders long banned by royal decree, in exchange for forgiveness of the crown's debts. In the same stroke, she allows a barefoot, unassuming cleric known only as the High Sparrow to be raised to High Septon by acclamation of the poor and devout, believing a humble zealot will be easier to manage than the corrupt, worldly septons who held the position before him.",
      "This is one of the book's most consequential decisions and one of its clearest examples of Cersei solving an immediate problem by creating a much larger one down the line: she has just re-armed a militant religious order that answered to no crown for over a century before its ban, and handed enormous moral authority to a man whose humility, the chapter makes clear even in its own moment, is not the same thing as harmlessness. Every disaster that befalls Cersei in the book's back half traces its root to this single trade.",
    ],
  },
  "chapter:4-26": {
    paras: [
      "Septon Meribald, a wandering holy man of real decency, guides Brienne's party along the road to the Quiet Isle, delivering along the way his famous meditation on broken men — soldiers stripped by war of home, purpose and mercy, turned by violence into something less than what they were. At the Quiet Isle itself, silent brothers dig graves and tend the sick without speaking a word, bound by vows of total silence — and among them Brienne notices one gravedigger, limping, unusually large, whose bearing nags at her without quite resolving into recognition.",
      "Meribald's speech on broken men is one of the book's most quoted passages precisely because it reframes the entire War of the Five Kings from ground level — not kings and claims, but the wreckage those claims left walking the roads, dangerous and pitiable in equal measure. The silent gravedigger is a deliberately planted mystery, dropped without confirmation or comment, that attentive readers will connect to a supposedly dead man from an earlier book — the chapter trusts its audience to notice what it refuses to say outright.",
    ],
  },
  "chapter:4-27": {
    paras: [
      "In Braavos, Sam's simmering resentment of Dareon boils over into an actual brawl — a fight about duty, desertion and the vows both of them supposedly swore, fought with fists rather than words for once. Bloodied and humiliated, Sam returns to find Maester Aemon suddenly, briefly awake and lucid, asking urgent questions about dragons — and about a name that catches in Sam's throat to hear a blind, dying old man say with such longing: Daenerys.",
      "The scene is a quiet gut-punch disguised as a minor domestic squabble: Sam's physical fight with Dareon (whom the reader, thanks to Arya's earlier chapter, may already suspect is a dead man walking) is almost comic in its clumsiness, but it's staged directly against Aemon's sudden, lucid fixation on Daenerys — the last Targaryen maester's dying preoccupation with the last Targaryen queen he will never meet. It's the clearest signal yet that Aemon's storyline is racing toward its end, and that whatever peace he finds will be bound up entirely in that name.",
    ],
  },
  "chapter:4-28": {
    paras: [
      "Jaime rides into the riverlands without his sword hand and without an army worth the name, tasked with bringing the king's peace to a region gutted by years of war between four separate crowns' worth of armies. He sets Harrenhal in order, hangs the remnants of the Goat's marauding garrison, and discovers — to his own quiet surprise — that words, letters and reputation can accomplish what he used to assume only a blade could. Castle after castle folds not because he threatens them with force he no longer credibly commands, but because the Kingslayer's name still means something, even wielded left-handed and half-believed.",
      "This chapter marks Jaime's real transformation into a political actor rather than a sword — the arc Brienne's influence and his missing hand together forced on him, now bearing fruit in the field. It's also a study in reputation as its own kind of weapon: Jaime is discovering that the fear his old identity generates can be repurposed toward genuinely constructive ends, cleaning up a war-torn region his father's policies helped create, even as he privately wonders how much of the old Kingslayer he's still trading on to get it done.",
    ],
  },
  "chapter:4-29": {
    paras: [
      "Lady Taena's whispered poison in Cersei's ear finally produces its intended fruit: Cersei begins actively engineering Margaery's downfall, using the frightened Blue Bard — a singer with damaging knowledge or testimony to offer — and the ambitious, malleable Osney Kettleblack as the instruments of a trap she is quietly proud of designing. She frames the whole scheme to herself as brilliant statecraft, the kind of ruthless maneuvering her father would have approved of, without registering how thoroughly it depends on people she barely controls telling exactly the story she wants them to tell.",
      "The chapter shows Cersei's plotting at its most active and, from the reader's vantage, its most reckless — she is building a trap using tools (a frightened singer, an ambitious social climber, a fanatic High Sparrow she personally armed) that have no particular loyalty to her once the scheme is set in motion. Every piece she is placing on the board here will, within a few more chapters, turn and point directly back at her; the chapter is essentially the queen loading a weapon she has not thought through who else it might hit.",
    ],
  },
  "chapter:4-30": {
    paras: [
      "On the Shield Islands, newly crowned Euron Greyjoy hands out spoils and lordships to his favored captains with the casual generosity of a man who has just won everything he wanted, taking other men's holdings by conquest and reassigning them like party favors. Victarion, his brother and rival at the kingsmoot, is given a mission dressed as an honor and shaped like exile: command of the Iron Fleet, and an errand to the very edge of the known world — sail east, find Daenerys Targaryen, and bring the dragon queen home as Euron's bride, wielding Euron's own gifted horn to bind her dragons along the way.",
      "The chapter reveals the shape of Euron's real ambition — not merely ruling the Iron Islands but reaching for the entire world's board, using his own brother as an unwitting pawn sent halfway across the earth. Victarion, simple and dutiful, accepts the mission at face value, unaware — as the reader increasingly is not — that Euron's gifts (the horn, the mission, even his own new wife given to him before departure) come with strings his straightforward mind is not equipped to see.",
    ],
  },
  "chapter:4-31": {
    paras: [
      "Jaime arrives at Riverrun to find it under siege from three directions at once — by banners, by starvation, by patience — with the Blackfish, Brynden Tully, still defiant on the walls despite being hopelessly outnumbered, and the Freys, who hold Edmure Tully hostage, wringing their hands anxiously over how to end the standoff without losing their prize. Jaime, arriving with royal authority and a reputation that precedes him, has to manage not just the siege itself but the fractious, cowardly Frey commanders who have spent months failing to take a castle that should have fallen by now.",
      "The chapter sets up the siege of Riverrun as Jaime's next test of his new, word-over-sword approach to soldiering — a puzzle he intends to solve through negotiation and threat rather than the assault the Freys have proven incapable of successfully mounting themselves. The Blackfish's stubborn defiance, meanwhile, is established as the one obstacle in the riverlands that reputation alone may not be enough to move — a proud, competent old soldier who has no illusions left to lose.",
    ],
  },
  "chapter:4-32": {
    paras: [
      "At a crossroads inn, Brienne and her small party find shelter alongside a group of war orphans and a broken, damaged man among them — and violence finds them there too. Rorge, one of the vicious criminals released from King's Landing's black cells earlier in the war, arrives wearing the stolen helm of the Hound, hunting for exactly the kind of vulnerable prey the inn's orphans represent. In the fighting, young Gendry — Robert Baratheon's blacksmith bastard, unexpectedly present — drives a spear through the cannibalistic killer Biter, but not before Biter's teeth have already torn into Brienne's face, leaving her permanently, brutally scarred.",
      "The 'broken man' sheltering among the orphans is left more felt than described — big, silent, moving like a soldier despite his wounds — an echo, deliberate or not, of Septon Meribald's sermon on broken men delivered several chapters earlier, as much as it is a specific character the text stays coy about naming outright. Rorge, still wearing the Hound's stolen helm from a run of terrorizing the countryside, and Biter, feral and cannibalistic even by the standards of the war's worst survivors, are exactly the wreckage that sermon described — men the fighting broke past any peace's ability to mend. Their attack on a room of orphans and one wounded stranger is opportunism, not strategy: the last scraps of the Brave Companions, still hunting whatever looks weakest within reach.",
      "This is one of the book's pivotal chapters, closing out two of the war's ugliest loose threads (Rorge and Biter, remnants of the Brave Companions and King's Landing's freed criminals) in a burst of sudden, costly violence. Brienne survives, but the scarring is not incidental set dressing — it's the physical mark the book leaves on a character whose entire life has already been defined by other people's judgments about her looks, ensuring the wound will follow her, and the reader's sense of her, for the remainder of her arc.",
    ],
  },
  "chapter:4-33": {
    paras: [
      "Cersei's trap finally closes: the Blue Bard, worn down after three nights of questioning by the Faith Militant, breaks and gives the testimony Cersei engineered him to give. Margaery Tyrell and her cousins are seized by the Faith on charges that mix real and manufactured sins together, and Cersei toasts her own cleverness in private, utterly convinced she has just removed her greatest rival from the board with none of her own fingerprints visible on the blade.",
      "The chapter is Cersei's apparent triumph, staged with maximum irony for a reader who already suspects the High Sparrow answers to no one, least of all the woman who armed him. Margaery's arrest reads, in the moment, as total victory — but everything about how it was achieved (through the Faith's own investigative and moral authority, which Cersei personally restored a few chapters earlier) is quietly setting up the machinery that the queen has no way of switching off once it turns its attention toward her.",
    ],
  },
  "chapter:4-34": {
    paras: [
      "Jaime ends the siege of Riverrun not with an assault but with a threat he privately prays he will never have to make good on: he tells the defenders that unless the castle yields, Edmure Tully's unborn child — Edmure himself a Frey hostage, forced into a marriage that produced the pregnancy — will be flung over the walls by trebuchet. Faced with the horror of it, Riverrun yields. But in the confusion of the surrender, the Blackfish slips away entirely, escaping the castle and vanishing from the story's reach rather than being captured or killed.",
      "The chapter is a study in the uses and costs of reputation-as-weapon: Jaime's bluff (and it is very possibly a bluff, though he never has to find out) succeeds precisely because his name carries enough weight that no one dares call it. It ends the siege bloodlessly by the letter, while leaving Jaime visibly disturbed by what he was willing to threaten to get there — a moral compromise that sits uneasily against the more honorable version of himself he's been trying to build since losing his hand. The Blackfish's escape denies everyone a tidy ending and leaves one of the riverlands' most dangerous old soldiers loose and unaccounted for.",
    ],
  },
  "chapter:4-35": {
    paras: [
      "In the House of Black and White, Arya's nightly ritual of confession continues — each night she must recite who she truly is: Arya of House Stark, with Needle hidden beneath a stone rather than surrendered to the House along with everything else she's been asked to give up. After Dareon's death is discovered and its author suspected, the kindly man who serves as her principal teacher gives her a cup of warm milk that is not what it appears to be — and Arya wakes to find herself blind.",
      "This is a brutal, deliberately ambiguous punishment: the novel never states outright whether the blinding is retribution for Arya's unsanctioned killing of Dareon, a test of her commitment to becoming no one, or simply the House's method of stripping away the last vestige of self-interest a novice clings to. What's unambiguous is the cost — Arya's refusal to fully surrender her identity (Needle under a stone, her name still hers in the dark) has just been answered with the loss of her sight, the sharpest possible statement that the Faceless Men's bargain is not negotiable.",
    ],
  },
  "chapter:4-36": {
    paras: [
      "Aboard the Cinnamon Wind, still en route toward Oldtown, Maester Aemon Targaryen dies at sea at one hundred and two years old — the last of his line for a hundred years, having outlived Targaryen kings, the dynasty's fall, and his own decades of self-imposed exile at the Wall. He dies laughing, murmuring a fragment of old prophecy about a dragon having three heads, and reminiscing about a childhood memory of dreaming he had grown old — a small, private joke that only he and the reader can fully appreciate, since dreaming of old age was, for Aemon, once the most fantastical outcome imaginable.",
      "Aemon's death closes one of the series' quietest, most dignified character arcs: a man born a prince who chose the Night's Watch and a maester's chain over a throne he never wanted, watching his family consume itself from a thousand leagues away for most of his life. His last words — the dragon must have three heads — are the clearest piece of Targaryen prophecy the books ever hand the reader directly, and his death leaves Sam solely responsible for the child and for whatever mission the old man's final urgency about Daenerys implied.",
    ],
  },
  "chapter:4-37": {
    paras: [
      "Cersei visits Margaery in her cell beneath the Great Sept, ostensibly bearing charity and comfort, actually savoring every second of her rival's imprisonment with a thin veneer of politeness stretched over open gloating. Meanwhile, Osney Kettleblack is dispatched to confess a fabricated adultery with Margaery to the High Sparrow — a lie meant to seal the queen's guilt beyond doubt. But the High Sparrow, unassuming and barefoot as he is, proves to have sharper eyes for a false confession than any of the actual septons Cersei is used to manipulating.",
      "The chapter is where Cersei's plan first starts to show hairline cracks under its own weight — Osney's confession is meant to be the final nail, but the High Sparrow's scrutiny (patient, humble, genuinely devout in a way Cersei has no framework for understanding, let alone countering) suggests he is investigating rather than simply accepting convenient testimony. Cersei's cell visit to gloat, meanwhile, reads as exactly the kind of unnecessary risk-taking that will keep compounding against her — a woman so certain of her own victory that she cannot resist savoring it before it's actually secure.",
    ],
  },
  "chapter:4-38": {
    paras: [
      "The Brotherhood Without Banners — once a company of loyal irregulars, turned by years of war into highwaymen and hangmen who dispense their own rough justice on empty roads — brings Brienne and Podrick before their leader in a hidden cave. She sits hooded in the dark, a scar gaping so wide across her throat that no voice comes out of it, only a rasp the outlaws translate for her, and they call her Lady Stoneheart. Brienne knows her the moment the torchlight catches her face: Catelyn Stark, drowned at the Red Wedding and pulled from the Green Fork days later, brought back changed and wrong by Lord Beric Dondarrion's borrowed, dwindling life rather than by anything like mercy. Stoneheart takes Oathkeeper into her ruined hands, and the Valyrian steel — reforged, unbeknownst to her, from her own husband's blade — tells her exactly whose sword this now is.",
      "The chapter detonates one of the book's most argued reveals: the North's grief did not end at the Twins, it simply changed shape into something that no longer recognizes mercy, kinship, or even its own children by sight. Stoneheart's price for sparing Brienne is not gratitude for the search but a blood debt — bring back Jaime Lannister's head, or hang alongside whatever other 'traitors' the brotherhood has strung up in the trees nearby. It is a trap built entirely out of the very vow Brienne has spent the whole book keeping, now turned against the man who gave her the sword to keep it with, and it lights the fuse for the ambush still waiting at Pennytree.",
    ],
  },
  "chapter:4-39": {
    paras: [
      "Jaime's slow circuit of the riverlands continues, castle after castle folding back into the king's peace with more ink spent than iron — but the chapter's real weight lands in a private conversation with his aunt Genna Lannister, Tywin's sister, newly widowed by the war's arithmetic. Genna does not flatter him. She tells Jaime, gently and without cruelty, that of Tywin's three children it was Tyrion — mocked, disowned, blamed for Joanna's death every day of his life — who was truly their father's son: ruthless, brilliant, unforgiving of weakness, capable of building or burning a house down to its foundations. Jaime, the golden knight who spent a lifetime performing the role of heir, never actually wanted Casterly Rock, and Genna says so plainly, watching to see whether it lands.",
      "It lands. The chapter recontextualizes the entire Lannister family dynamic mere chapters after the reader has watched Tyrion put a crossbow bolt through Tywin's chest — Genna's verdict suggests Tywin's fatal misjudgment of his own children was no incidental cruelty but a blind spot as deep as any in the book, mistaking the son who looked like him for the son who actually thought like him. For Jaime, already unmoored from the Kingslayer identity that used to explain him to himself, it is one more plank pulled out from under a life built on being Tywin's heir — a role, Genna implies, he was only ever cast in, and never suited for.",
    ],
  },
  "chapter:4-40": {
    paras: [
      "Osney Kettleblack's false confession goes wrong in the worst possible direction: he confesses to too much, too convincingly, and the High Sparrow — now suspicious rather than satisfied — has him scourged to extract the truth beneath the lie. Under the lash, what Osney actually screams is not what Cersei scripted for him; it sends the Faith's attention swinging directly toward the queen herself, the very net she built to catch Margaery beginning to close around its own architect.",
      "This is the chapter where the trap Cersei spent so many pages congratulating herself on fully reveals its true design: not a weapon she controls, but a machine that runs on evidence and confession regardless of whose interests that evidence serves. Osney's torture-extracted testimony is the first concrete thread connecting Cersei to sins of her own — adultery, conspiracy, the paternity of her children by extension — and the High Sparrow, having been handed genuine grounds for suspicion, is not the kind of instrument that stops once it starts moving.",
    ],
  },
  "chapter:4-41": {
    paras: [
      "In her tower cell, Arianne Martell — held under comfortable, courteous captivity since the queenmaker plot's collapse — finally learns the true shape of her father's strategy from Doran himself. His apparent passivity since Oberyn's death was never weakness but a long fuse: Dorne has spent years quietly binding itself to the Targaryen cause, Arianne's brother Quentyn has already sailed east on a secret mission to Daenerys that Arianne knew nothing about, and Doran's private watchword for the whole enterprise is fire and blood — the old Targaryen words, repurposed as Dorne's own long-simmering promise of vengeance.",
      "The chapter is the book's major reveal about Dorne, recontextualizing every previous scene of Doran's apparent caution as, instead, patient, multi-generational planning that his own daughter was deliberately kept ignorant of, precisely because her queenmaker scheme (however well-intentioned) threatened to detonate his real plan prematurely. It reframes Dorne from a wounded, vengeful kingdom sniping at Lannisters into a genuine great-power player angling for a Targaryen alliance the rest of Westeros hasn't even noticed forming.",
    ],
  },
  "chapter:4-42": {
    paras: [
      "As winter approaches, the Eyrie empties down the mountain, its household relocating for the season, and amid the logistics Littlefinger reveals his next long-range maneuver to Sansa: he intends to marry Alayne Stone to Harrold Hardyng — Harry the Heir, next in line to the Vale should young Robert Arryn die — binding her, under her false identity, into the Vale's own succession. And beneath that plan sits another, unspoken one: that one day, once the pieces are in place, the Vale's knights might be turned toward restoring not Alayne Stone but Sansa Stark to power in the North.",
      "The chapter is Littlefinger laying out, for the first time explicitly, just how far ahead he is thinking — using Sansa's disguise not merely as protective cover but as the raw material for an entirely new political marriage and a long-term bid to put actual military force (the Vale's knights) behind a Stark restoration he intends to personally broker and control. It's the clearest statement yet of Littlefinger's ultimate design: not simply protecting Sansa, but building her, piece by piece, into the instrument of his own ambitions.",
    ],
  },
  "chapter:4-43": {
    paras: [
      "Brienne's quest reaches its most harrowing point yet: captured by outlaws, she and Podrick are strung up to hang, the rope already biting into her throat, when she is offered a reprieve — her life, in exchange for a betrayal the text never fully specifies. The chapter, and the book itself, ends on Brienne swinging at the rope's end, having shouted a single word in answer to the offer — a word the reader is deliberately not permitted to hear.",
      "This chapter is one of the book's most notorious cliffhangers, an intentional, unresolved gap that would not be answered on the page until the following novel. Structurally, it's the culmination of everything Brienne's arc in this book has been building toward — her literal-minded devotion to a vow, tested now against her own survival — and the choice to withhold the single word she shouts is the book's boldest bet that readers will trust her integrity enough to sit with the uncertainty rather than assume the worst.",
    ],
  },
  "chapter:4-44": {
    paras: [
      "The machinery Cersei built with her own hands finally closes on her. Accused by her own catspaw — Osney Kettleblack's scourged, garbled confession naming her alongside every sin the Faith cares to punish — she is taken from the Red Keep by the Faith Militant she personally re-armed, and marched down into a cell beneath the Great Sept, stripped of guards, title and the small council she stocked with men too weak to help her now. She paces. She writes letters — to Jaime, to anyone who might still owe her enough to move quickly — and sends them out into a city that is, for the first time in her life, in absolutely no hurry to answer a Lannister's summons.",
      "The cell itself becomes the chapter's real subject: cold stone, a single window too high to reach, the specific indignity of a woman who has spent the whole book insisting she rules better than any man discovering exactly how much of her power lived in other people's fear rather than in anything she actually controlled. The High Sparrow visits, unhurried and unmoved by rank, and makes plain that a trial is coming — not the theater of a council chamber, but the Faith's own justice, which does not bend for gold or blood.",
      "This is the book's clearest act of poetic justice, delivered without a trace of the mercy Cersei withheld from everyone she ever outmaneuvered. Every choice that built her isolation arrives at once — the flatterers promoted over competent men, the estrangement from Jaime after his refusal of the Handship, Tyrion long gone and blamed for everything, the Faith Militant restored for leverage over Margaery and now turned wholesale on its own architect — and there is, genuinely, no one left positioned or willing to intervene. Cersei mistook control for security across her whole regency; this chapter is the bill for that mistake, presented in full.",
    ],
  },
  "chapter:4-45": {
    paras: [
      "At Pennytree, a rider arrives through pouring rain bearing a half-eaten, greyscale-ravaged face and a message crafted to sound like salvation: Brienne, the rider claims, has found the girl at last — Sansa — just a day's ride away, and Jaime must come immediately, and alone. The offer is transparently, ominously suspicious, dangling exactly the resolution Jaime has spent the book half-dreading and half-hoping for, wrapped around instructions no careful man should follow.",
      "The chapter sets a trap whose bait is calibrated with real precision: Jaime's genuine, complicated loyalty to a vow he made to a dying Catelyn Stark, his growing respect for Brienne, and his need to believe something in this rotten war can still be resolved honestly, all pulling him toward a summons that every reasonable instinct says is a lie. Coming right after Brienne's own unresolved hanging and Lady Stoneheart's blood price on Jaime's head, it deliberately scrambles the reader's sense of what's actually waiting for him at the end of that ride — hope and dread arriving in the same letter.",
    ],
  },
  "chapter:4-46": {
    paras: [
      "Sam reaches Oldtown and the Citadel at last, the long, storm-battered voyage of the Cinnamon Wind behind him, Aemon buried at sea, Gilly and the babe settled safely nearby. He is granted an audience with Archmaester Marwyn — bearish, unorthodox, one of the few men in the Citadel who takes glass candles and prophecy as seriously as ravens and arithmetic — and pours out everything he has seen: the wights, the Others, Coldhands leading Bran's party through dead villages, a Wall that may not hold forever. Marwyn listens without the polite disbelief Sam braced for; he has his own portents to report, glass candles burning in locked rooms after centuries of dormancy, a sign he reads as confirmation that something old in the world is waking up whether the Citadel's comfortable skeptics credit it or not.",
      "In the chaos of arrival — trunks, ravens, a maester's bureaucracy utterly indifferent to what Sam has just survived to reach it — a novice steps forward to help him settle in, and gives his name easily, kindly, as Pate. It is offered and accepted as the most ordinary courtesy in the world.",
      "It should not be. The book's very first chapter closed on a nameless stranger murdering the real Pate in an Oldtown alley and walking off wearing his face — a scene forty-five chapters and several hundred pages behind the reader by now, easy to have half-forgotten amid kingsmoots and queens. A Feast for Crows ends by handing that thread back without comment: Sam, grateful and exhausted, has just been personally welcomed through the gates of an institution built to hoard the realm's secrets by something that is very likely not a novice at all. Nothing else is resolved either — not Brienne's rope, not Cersei's coming trial, not the identity wearing Pate's smile — because this half of the story was written to run beside A Dance with Dragons rather than to conclude before it, and the book's last move is to remind the reader, one final time, that faces in this story are rarely load-bearing.",
    ],
  },
});
