/* GoT wiki long-form archive — the hours retold, S1–S8. Original prose. */
Object.assign(WIKI_EXTRA, {

  // ==================== SEASON ONE ====================
  "episode:1-1": {
    paras: [
      "The whole saga is stated in the first five minutes and then deliberately forgotten for years: three rangers ride out through a tunnel of ice, find a wildling camp arranged into an ominous pattern, and meet something that has not been seen in eight thousand years. The survivor flees south — and the story promptly executes him for desertion, because the realm has better things to worry about. That beheading in the Winterfell snow is the pilot’s thesis. Ned Stark swings the sword himself, tells his sons the man died bravely, and rides home past a dead direwolf with an antler in its throat. The omens are laid out like place settings; nobody at the table reads them.",
      "What the hour is actually about is a family being pried apart by an offer it cannot refuse. Robert Baratheon arrives with the whole rotten south in his train — a queen who despises him, a Kingslayer, an imp who reads — and asks his oldest friend to come rule the realm with him, because ruling is the one thing Robert never wanted to do. Lysa’s letter accusing the Lannisters of murdering the last Hand turns a request into a duty. Across the sea, meanwhile, the story’s other engine starts turning: Viserys Targaryen sells his sister to a Dothraki warlord for the promise of an army, and Daenerys stands in her wedding silks like a woman at her own funeral, three stone eggs among the gifts.",
      "And then the ending — still one of television’s great cold slaps. Bran climbs a broken tower because he climbs everything, sees the queen with her brother, and Jaime Lannister, with an apology that isn’t one, pushes a ten-year-old out a window. “The things I do for love” closes the hour like a door slamming. In one stroke the show declares its rules: children are not safe, love is the most dangerous motive in the world, and the audience’s sympathy will be handed to people who do unforgivable things. Winter is coming, the Starks keep saying. Nobody, including them, has any idea what that means yet.",
    ],
  },
  "episode:1-2": {
    paras: [
      "An hour of departures, all of them down roads that will not be untraveled. The court rides south with Sansa dreaming of queenship and Arya fencing with breadsticks; Jon and Tyrion turn north toward the Wall, the bastard and the dwarf finding a wary kinship in being their families’ spare parts. Jon’s farewell gifts frame everything — a sword for Arya, slim enough for her hand, named Needle as a joke on the ladylike arts she hates. Behind them all, Bran sleeps on while a hired knife comes for him with Valyrian steel, and Catelyn learns what a mother’s hands and a direwolf’s jaws can do. The dagger that fails to kill her son becomes the reason she rides south in secret — carrying, though she cannot know it, the war in her saddlebag.",
      "The episode’s dark heart is on the kingsroad, where a butcher’s boy plays at swords with Arya and a prince’s wounded vanity becomes a body count. Joffrey lies, Sansa equivocates, and the machinery of power does the rest: Nymeria driven off with thrown stones, the innocent Lady executed in her place because a queen demanded a wolf and any wolf would do. Ned swings the sword himself — the old way, wasted on a new kind of injustice. It is the hour where the Stark children’s illusions start dying in order of age, and where Daenerys, half a world away, begins the opposite journey: learning in Drogo’s tent that even a sold bride can decide what happens next.",
    ],
  },
  "episode:1-3": {
    paras: [
      "Everyone arrives where they were going, and everywhere turns out to be worse than advertised. Ned reaches King’s Landing to find the crown six million in debt — half of it to the father of the queen — and a small council where the whisperer, the moneylender and the old maester all smile with too many teeth. At Castle Black, Jon expects the storied brotherhood of the songs and gets thieves, rapers and grey old men holding seven hundred feet of ice; his sulk about it lasts precisely until Tyrion points out that sneering at broken men is a luxury for boys raised in castles. The episode is a matched pair of disillusionments — the realm’s two great institutions, throne and Watch, both running on fumes and reputation.",
      "The quiet scenes carry the freight. Catelyn, smuggled into a brothel by Littlefinger, leaves the capital with a name for the dagger — Tyrion Lannister — which happens to be a lie that will start a war. Old Nan tells a broken boy about the Long Night, when the White Walkers came the first time, and the show files the story away in plain sight. And in a sunlit room, a Braavosi fencing master takes a small girl through her first lesson while her father watches, smiling — until the wooden swords start sounding, to Ned’s ears, like steel. Syrio’s water dance is the one gift Ned gives that outlives everything: swift as a deer, quiet as a shadow, and not knitting.",
    ],
  },
  "episode:1-4": {
    paras: [
      "The title is Tyrion’s phrase, and the hour is built around it: a catalogue of the people the realm was not designed for. Tyrion, passing through Winterfell, hands Bran the drawing of a saddle a cripple can ride — kindness from the family that crippled him, which nobody knows yet but Bran’s dreams. Sam Tarly arrives at the Wall, fat, frightened, and disowned with a hunting-accident threat, and Jon quietly makes the bullies stand down — the first time Jon leads anything. Meanwhile the Hand’s tourney opens with the Mountain putting a lance through a young knight’s throat, and Sansa learns that the pageantry she loves has blood just under the paint.",
      "Underneath the pageant, two investigations converge. Ned follows Jon Arryn’s last steps to an armorer’s shop and a black-haired apprentice with Robert’s jaw — the dead Hand was counting the king’s bastards, and someone killed him for the arithmetic. And at a crossroads inn, Catelyn Stark rises from a table, calls on her father’s bannermen by name and pedigree, and arrests Tyrion Lannister for a crime he did not commit. It is a magnificent scene and a catastrophic decision: the wrong dwarf, seized on a liar’s evidence, and every sword in the room answers her. The war that will eat the Starks starts here, at dinner, on bad information.",
    ],
  },
  "episode:1-5": {
    paras: [
      "The wolf and the lion stop circling. Word of Tyrion’s arrest reaches the capital, and the feud goes public in the worst place possible — the small council, where Robert orders the assassination of a pregnant girl across the sea and Ned discovers the limits of friendship with a king. He lays the Hand’s badge on the table rather than sign a child’s death warrant, which is honorable, and also leaves him a private citizen in a city where the queen’s family wants him dead — a distinction Jaime Lannister demonstrates in the street within the day, with Jory dead on a dagger and Ned’s leg opened by a spear. Honor, the episode keeps noting, is not armor.",
      "The map widens tellingly. Catelyn hauls her prisoner up the Eyrie’s goat tracks to her sister’s hall, where justice turns out to be a breastfeeding six-year-old shouting about making the little man fly — the Vale is not a refuge but a locked ward. In a garden in King’s Landing, Loras Tyrell whispers to Renly that a fourth-born pretty boy might make a fine king, and the seed of a second war goes in the ground. And in the season’s best two-hander, Robert and Cersei sit alone with their wine and conduct an autopsy on their marriage — seventeen years, one dead girl’s name between them, and the closest thing to honesty either has spoken in the capital. It changes nothing, which is the point.",
    ],
  },
  "episode:1-6": {
    paras: [
      "Two thrones, two trials, and a crown that isn’t gold at all. In King’s Landing, Ned sits the Iron Throne as Hand while Robert hunts, hears what the Mountain’s raiders did in the riverlands, and — in full view of the court — sends Beric Dondarrion to bring the king’s justice and summons Tywin Lannister to answer for his dog. It is exactly the sort of thing the office exists to do, and exactly the sort of thing one does not do to Tywin Lannister. In the Vale, meanwhile, Tyrion talks his way out of a sky cell by demanding trial by combat, and a sellsword named Bronn wins it by declining to be chivalrous: Ser Vardis, in his fine armor, goes through the Moon Door, and Bronn’s answer to the scandalized court — he didn’t fight with honor, no; the dead man did — is the whole series in one exchange.",
      "The title belongs to Essos. In Vaes Dothrak, Daenerys eats a raw stallion’s heart in front of the crones and keeps it down; her son is proclaimed the Stallion Who Mounts the World while Viserys watches from the crowd and understands, finally, that the khalasar follows her. His response — a drawn sword in the sacred city, a hand on his sister’s belly, a demand for the crown he was promised — earns him Drogo’s idea of a coronation: molten gold, poured over the head of a man everyone has stopped being afraid of. Dany watches without flinching and pronounces the verdict: he was no dragon, because fire cannot kill a dragon. It is the first time she says something like that. It will not be the last.",
    ],
  },
  "episode:1-7": {
    paras: [
      "Cersei names the game in a garden, and the hour spends its whole length proving her right. Ned, holding proof that her children are Jaime’s, does the most Ned thing imaginable: he tells her what he knows and gives her time to run — mercy extended to the one player who will never return it. Then a boar opens the king on his hunt, and the clock starts. Robert dictates a will naming Ned protector of the realm until “my son” comes of age; Ned, writing, quietly amends it to “my rightful heir,” a correction that is both entirely honest and entirely useless, because paper is only power when someone with swords agrees it is.",
      "Everyone offers Ned a way to win. Renly offers a coup by night with a hundred swords; Littlefinger offers the gold cloaks and a brokered peace with the boy on the throne; Ned refuses both, because one is treason and the other is dishonor, and walks into the throne room with Robert’s will in his hand. Cersei tears it in half and Littlefinger’s knife arrives at Ned’s throat with an apology — he did warn him not to trust him. Meanwhile the story’s other futures lock in: Jon swears his vows before a heart tree and learns stewarding may be a promotion in disguise, and in Essos a wineseller’s clumsy poison attempt turns Drogo’s vague westward ambitions into a khal’s blood-vow. You win or you die, she said. The board is now exactly that simple.",
    ],
  },
  "episode:1-8": {
    paras: [
      "The trap has closed; this hour is about what falls out when it does. The Stark household in King’s Landing is put to the sword down to the stable boys, Sansa is taken to be a hostage with a title, and Ned goes into the black cells. The episode’s one perfect scene is a dancing lesson interrupted: Syrio Forel, First Sword of Braavos, holding a doorway against five armored men with a wooden sword so that a small girl can run. What do we say to the god of death — the line enters the story here, and Arya carries it out of the room along with Needle and her first kill, a stable boy who grabbed the wrong child. She goes into the city’s underbelly; the show will not let her out for years.",
      "Everywhere else, the war stands up and stretches. Robb calls the banners at Winterfell and discovers — hosting grizzled lords who mock his age until a direwolf takes two of Greatjon Umber’s fingers — that command is a performance you must not flub even once. Tywin marches; Tyrion talks the hill tribes into an army with promises of other people’s silver. At Castle Black a dead ranger opens his blue eyes in the night, and Jon learns what fire is for — the Watch’s war announcing itself while everyone faces south. And in a Lhazareen village, Daenerys spends her new authority stopping rapes and claiming healers, a mercy that buys her a maegi, and costs Drogo a scratch. Just a scratch.",
    ],
  },
  "episode:1-9": {
    paras: [
      "The hour that taught the audience the rules were real. Its architecture is a series of bargains: Catelyn walks alone into Walder Frey’s hall and buys a bridge with marriage promises, including one with Robb’s name on it — the toll no one thinks twice about paying. Robb spends two thousand men on a feint at the Green Fork and falls on Jaime Lannister’s host in the Whispering Wood instead, trading blood for the single most valuable prisoner in the war. Even Daenerys is bargaining, letting Mirri Maz Duur work blood magic on the dying Drogo over the khalasar’s religious horror — only death pays for life, the maegi says, and Dany does not ask the only question that matters, which is whose.",
      "And then there is Ned’s bargain, the one the whole season has been arranging. In the black cells Varys lays it out with surgical gentleness: pride is a luxury, and Sansa’s life is the price of it. So the most honorable man in Westeros stands on the steps of the Great Sept of Baelor and spends his honor in public — confessing to a treason he did not commit, naming Joffrey the rightful king, buying his daughters’ safety with the only currency he has left. The show shoots it from inside the crowd, at Arya’s height, clinging to a statue’s plinth. Ned sees her there. His last word is to Yoren — “Baelor” — pointing the Night’s Watchman at the child on the statue. Even dying, he is managing the evacuation.",
      "Joffrey wants a head, and no adult in his court can stop the sentence in time. The sword comes down on the man whose face is on all the posters, nine episodes into the first season, and television changed a little that day: the story had demonstrated that its moral center was not load-bearing, that goodness confers no plot armor, and that the camera would look away only at the last second — to birds, to Arya’s face buried in Yoren’s chest. Every war of the next seven seasons marches out of this scene. So do all the Stark children, each carrying a different shard of their father: his justice, his stubbornness, his silence, his North.",
    ],
  },
  "episode:1-10": {
    paras: [
      "Aftermath as overture. The finale opens on the sword that fell — blood on Ice, Arya smuggled through the panicking crowd, Sansa made to look at her father’s head on a spike and learning, in the same minute, to hide everything behind her face. The realm reorganizes itself around the wound: Tywin, absorbing that the war is now unwinnable by ordinary means, sends the son he despises to court to rule as acting Hand, on the theory that Tyrion is the only Lannister who cannot be flattered or frightened. And at Riverrun, the river lords and the northmen answer the question of which southern king to back by refusing the premise: the Greatjon’s roar — why should they rule us? — ends with swords in the firelight and Robb Stark raised as King in the North, an old crown remembered after three hundred years.",
      "The episode is generous with quieter turns. Arya, shorn and renamed Arry, disappears into Yoren’s recruit column with a stolen sword and a short list of names. Jon tries to desert for his brother’s war and is fetched back by his friends reciting the vow at him in the dark — the Watch’s claim on him made personal rather than legal. And Catelyn, allowed one scream in the woods, comes back with her grief packed away and a to-do list: we will kill them all, but first, the girls. The show’s women absorb this hour’s losses standing up.",
      "Then the pyre. Daenerys, widowed by her own bargain, gives Drogo mercy with a pillow, straps the maegi to the wood, and answers every counselor who says the eggs will not hatch by walking into the fire wearing nothing she needs. What dawn finds is the series’ great image: an unburnt girl in the ashes with three living dragons on her, and a khalasar of the leftover and the lame kneeling in a circle. The season began with dead things waking in the ice; it ends with impossible things hatching in the fire. The world now has dragons in it again, and every power calculation made in every hall of Westeros is quietly, comprehensively wrong.",
    ],
  },

  // ==================== SEASON TWO ====================
  "episode:2-1": {
    paras: [
      "A red comet drags itself across the sky and everyone reads it as a personal endorsement — Lannister crimson, Stark vengeance, dragon’s breath — which is the season in miniature: five kings, one omen, and no referee. The premiere’s real business is introducing the man who thinks arithmetic settles it. On a beach at Dragonstone, Stannis Baratheon burns the Seven and watches a red priestess pull a flaming sword from the fire; then he dictates a letter to every corner of the realm announcing what Ned Stark died knowing — Joffrey is no Baratheon — and haggles over a single word of it. Not my beloved brother, he corrects. He was not beloved of me. That is Stannis: the rightful heir, with the charm of a ledger and the persistence of one too.",
      "In the capital, Tyrion arrives whistling to take up the Handship his father assigned him, greets his sister with cheerful malice, and begins the season’s most entertaining project: running a kingdom for a king who should be in a cell. The cruelty he is there to manage announces itself immediately — Cersei’s order (or Joffrey’s; the show lets the guilt smear) sends gold cloaks to butcher Robert’s bastards in the city, babies included, a purge that sharpens the stakes of every secret Ned died for. Far east, the counterweight: Daenerys leads a starving remnant through the red waste, her three dragons too small to feed anyone, learning the gap between the mother of dragons and a queen of anything. The comet, whatever it means, feeds no one either.",
    ],
  },
  "episode:2-2": {
    paras: [
      "The night lands of the title belong to the drowned god, and the hour’s best material is Theon Greyjoy sailing home to claim his inheritance and discovering he has none. Nine years a Stark ward have made him a stranger on Pyke: his father reads his fine clothes as a costume, his sister lets him flirt with her on horseback before introducing herself, and the ironborn measure a man by what he pays the iron price for, not what he was given. Theon came home expecting to command the fleet that helps Robb; he finds a father planning to reave the North instead, and a choice being assembled around him that he is exactly the wrong man to make well.",
      "Elsewhere the season’s pieces slide into their grooves. Tyrion, discovering that Janos Slynt sold Ned Stark and butchered a baby at his post, ships him to the Wall over dinner and hands the gold cloaks to Bronn — anticorruption by way of a more reliable cutthroat. Arya shares the kingsroad with Yoren’s recruits and trades wary words with a courteous caged man named Jaqen H’ghar, a politeness that will echo for seasons. Davos recruits a pirate for Stannis with honest smuggler’s pragmatism, and in the red waste a riderless horse returns carrying Rakharo’s head in a saddlebag — the khalasars’ answer to a khaleesi with no khal. Power, the episode keeps repeating, is what others believe you can do to them; half the cast is running on credit.",
    ],
  },
  "episode:2-3": {
    paras: [
      "What is dead may never die, the drowned priest intones, and Theon Greyjoy rises from the water baptized into a family that does not want him. The episode hands him the season’s cruelest choice with total clarity: a letter to Robb would save the brother he grew up with and damn the father he just recovered. He holds it over a candle and watches his old life burn — a small, quiet, entirely self-inflicted catastrophe, and the show’s most patient tragedy begins in earnest. On Pyke they pay the iron price; Theon pays in the only currency he has, which is other people’s trust.",
      "The other threads sharpen by contrast. Catelyn arrives at Renly’s camp to find a hundred thousand men playing at war between tourneys — summer knights, she notes, and winter is coming — and the hour introduces Brienne of Tarth by having her beat Loras Tyrell in front of everyone and ask only for a place in the Kingsguard. In the capital, Tyrion runs a leak-detection sting worthy of a spymaster: three marriage rumors, three councillors, three different brides, and Pycelle’s beard pays for the betrayal. And on the kingsroad, Yoren dies as he lived — refusing to hand anyone over — while the survivors of his recruit column, Arya among them, are dragged toward Harrenhal in chains. The old protections are burning off the story one by one.",
    ],
  },
  "episode:2-4": {
    paras: [
      "The garden of bones is Harrenhal, where the Mountain’s men pick a prisoner each evening and the questions asked are beside the point; Arya files it all away and starts whispering names into the dark like a prayer. The episode is a study of power at its ugliest octave. Joffrey has Sansa stripped and beaten before the throne because her brother keeps winning battles — Robb takes Oxcross this same hour, falling on the Lannister west like weather — and it is Tyrion who stops it, with the observation that the Mad King also did as he liked. The lesson Sansa is learning, one bruise at a time, is that courtesy is armor and armor is all she has.",
      "The war of the five kings meets its first impossibility on a beach at the Stormlands’ edge, where Renly and Stannis parley in the language of brothers who never liked each other. Renly has the numbers, the charm and the fruit; Stannis has the bloodline, the grievance and one night’s grace on offer. Neither blinks, so the red woman settles it: Davos rows Melisandre into a cave beneath Storm’s End and watches her birth a thing of shadow with a face he knows. It is the moment the war stops being a contest of armies. Away east, Daenerys reaches the gates of Qarth with her starving column and bluffs the Thirteen into opening the greatest city that ever was — a phrase, she will learn, that the Qartheen apply themselves.",
    ],
  },
  "episode:2-5": {
    paras: [
      "The shadow does its work in the first minutes: Renly Baratheon, the war’s presumptive winner, dies in his own tent in front of Catelyn and Brienne, and a hundred thousand swords go looking for a new king. The rest of the hour is the scramble. The storm lords bend to Stannis; the Tyrells ride for Highgarden with Littlefinger murmuring in their wake; and Brienne, blamed for the murder she watched, swears her sword to Catelyn Stark on the road — the beginning of the story’s most stubbornly honored oath. Renly’s death is the season’s pivot, and nobody swung a sword for it: the show’s wars keep being decided by things that do not appear on the muster rolls.",
      "In King’s Landing, Tyrion follows a rumor into the guts of the city and finds the alchemists’ guild sitting on thousands of jars of wildfire — the substance with which the Mad King meant to burn the capital — and does the responsible thing, which is to confiscate the stockpile for himself. At Harrenhal, Arya, now cupbearer to Tywin Lannister of all people, spends the first of Jaqen’s three owed deaths on the Tickler, and the torturer is found with his neck broken and no one to blame. And off the Stony Shore, Theon, stung by his crew’s contempt, stops thinking like a raider and starts thinking like a Stark ward who knows exactly which castle is barely garrisoned. The plan is clever. That is the tragedy.",
    ],
  },
  "episode:2-6": {
    paras: [
      "The old gods and the new both take a beating. Theon takes Winterfell with twenty men and a night ladder, and the price of playing prince comes due by breakfast: Ser Rodrik, the old master-at-arms who trained him, spits in his face, and ironborn pride demands a sentence Theon is not equipped to carry out. Four strokes to take a head — the man who taught him the sword watching him botch it. In King’s Landing the new gods’ city turns on its anointed: a bread riot nearly takes the king, the High Septon is torn to pieces by the faithful, and Sansa is dragged from her horse and saved from the mob by the Hound, who does not want thanking. Crowns, the hour observes, are hats; hunger does not salute.",
      "The quieter betrayals matter more. Beyond the Wall, Jon is handed a captured wildling to execute and cannot do it — Ygritte talks, and keeps talking, and by nightfall the prisoner is the one setting the pace. Bran and Rickon vanish out of captured Winterfell with Osha and Hodor, into the dark with the direwolves. And in Qarth the season’s eastern plot finally bares its teeth: Dany’s dragons are stolen, her people murdered in the halls of her host, and her scream — where are my dragons — is the sound of the story reminding her that the only power she has ever really held has scales. The title’s gods, old and new, answer no prayers this week; everyone is on their own.",
    ],
  },
  "episode:2-7": {
    paras: [
      "The title is Jaime Lannister’s self-assessment, delivered from a stockade after he has murdered his own cousin for a half-chance at escape — and the hour keeps turning the phrase over like a coin. Honor, in this episode, is mostly the story people tell about the things they were going to do anyway. Theon, humiliated by two missing Stark boys, rides out with hounds and comes back with two small charred bodies to hang from Winterfell’s walls — better to be cruel than weak, he tells himself, having chosen a third option worse than either. The reveal that the bodies are the miller’s boys is withheld; the show lets the audience sit with the worst version, because Theon has to live in it either way.",
      "The captives run the table. Ygritte spends the hour as Jon’s prisoner in name and his interrogator in practice, needling him about vows, freedom and everything under his cloak, until the ambush closes and the roles reverse — you know nothing, Jon Snow, now established as both taunt and diagnosis. In Qarth, Pyat Pree demonstrates the difference between wealth and power by murdering the Thirteen in open council and inviting Dany to the House of the Undying, where her dragons wait. And in the capital, Cersei — rattled by her son and her siege — gives Sansa the only honest tutorial she will ever offer: love no one but your children. In an episode full of men explaining honor, the queen’s cynicism lands as the closest thing to truth on offer.",
    ],
  },
  "episode:2-8": {
    paras: [
      "The held breath before the green fire. Stannis’s fleet is at sea, and King’s Landing prepares in its characteristic way: Joffrey plans heroics, Cersei plans hostages, and Tyrion counts wildfire jars and chain links with Bronn, conducting the defense of the city out of a workshop and a brothel. The episode’s craft is in the countdown — every scene in the capital is timed against the sails on the horizon, and the only man doing his job is the one the city will never thank.",
      "The rest of the map is a study in prices. Yara arrives at Winterfell with ironborn sense — the castle is indefensible, the sea is home, come away — and Theon refuses, because coming away would mean the boys died for nothing, which they did. Robb, learning his mother has freed the Kingslayer on her own authority to ransom the girls, puts Catelyn under guard while Brienne rows Jaime downriver on the war’s least promising diplomatic mission. Arya spends Jaqen’s last owed death not on a name but on an exit, and walks out Harrenhal’s front gate past dead guards — a man keeps his word, precisely. And beneath Winterfell, the episode plays its gentlest card: Bran and Rickon never fled at all, and are hiding in the crypts below Theon’s feet, closer to home than anyone dares be.",
    ],
  },
  "episode:2-9": {
    paras: [
      "The show’s first great experiment in staying put: one night, one battle, one city, no cutaways to the wider war. Stannis’s fleet rows into Blackwater Bay expecting a naval engagement and meets instead a single unmanned ship, riding low, leaking something green. Bronn’s fire arrow turns the bay into a lake of burning jade — wildfire, the Mad King’s toy, deployed by his old Hand’s least-loved son — and Davos Seaworth’s ship comes apart around him with his boy aboard. It is one of television’s great pyrotechnic images, and the show is careful about what it costs: the screaming men in the green light are the same smallfolk every king claims to fight for.",
      "Stannis, being Stannis, wades ashore anyway. The battle becomes a grinding escalade — ladders, gates, a battering ram — and the city’s defense keeps falling to the wrong people. Joffrey quits the walls when his mother sends for him; the Hound, unmade by the fire that ruined his face, delivers his resignation to the king’s face and walks out of the war. It is Tyrion, the dwarf the city mocks, who rallies the garrison with the least heroic speech ever given — those are brave men knocking at our door; let’s go kill them — and leads the sortie through the sally port himself. His reward arrives mid-battle from his own side: a Kingsguard sword across the face, and the darkness. Meanwhile, in Maegor’s Holdfast, Cersei conducts a masterclass in gallows realism, drinking wine and teaching Sansa what falls to women when cities do, with Ser Ilyn standing by for the last mercy.",
      "The ending is cavalry out of the dawn: Tywin Lannister and the Tyrell host taking Stannis’s army in the rear, Loras in Renly’s armor for the legend of it, Stannis dragged from the walls still swinging. The day belongs to the lion and the rose — a phrase the realm will learn to say with a shudder — and the episode closes on the war’s great injustice being minted in real time: Tywin rides his horse into the throne room to be named savior of the city, while the man who actually saved it wakes up scarred, demoted and written out of the songs. Blackwater set the template every later battle episode would chase: geography you can follow, stakes you can name, and victory indistinguishable, at street level, from catastrophe.",
    ],
  },
  "episode:2-10": {
    paras: [
      "The season closes by handing out the prizes to the wrong people, which by now is house style. Tywin is named Hand and savior; Littlefinger gets Harrenhal for brokering the Tyrell alliance; Margaery gets a king swapped in for a betrothal, and Sansa — discarded, delighted, and immediately warned by Littlefinger that being unclaimed in that court is not freedom. In the north the bill comes due at Winterfell: Theon rallies his twenty men with the finest speech of his life and is sacked mid-sentence by his own crew, who have arithmetic where he has feelings. The castle burns behind them. Maester Luwin, speared at the heart tree, spends his last breath telling Osha to take the boys north, to Jon — the old teacher managing the syllabus to the end.",
      "The finale’s two visions aim the whole series. In the House of the Undying, Daenerys walks through a throne room open to falling snow — or ash — and a gate in a wall of ice, declines both illusions for the sound of her children crying, and burns the warlock who caged them; the vault of Qarth pays her passage west. And on the Fist of the First Men, three horn blasts find Sam in the snow. The great ranging’s answer marches past him in the storm: the army of the dead, ranked and led, with the Night’s Watch camped directly in its path. Five kings have spent the season contesting a throne. The finale’s last shot is the audit: none of their wars matter, and only one man in the realm is close enough to see why — hiding behind a rock, too frightened to move.",
    ],
  },

  // ==================== SEASON THREE ====================
  "episode:3-1": {
    paras: [
      "Valar dohaeris — all men must serve — and the premiere is a tour of service and its humiliations. The survivors of the Fist stagger back to Craster’s with the news that ends the world, if anyone would hear it; Mormont’s orders to Sam are blunt: the Watch must reach the Wall alive, because a warning that dies in the snow is no warning at all. South of the ice, Jon is marched through the free folk’s camp — giants, cookfires, a people rather than a horde — and lies his way into Mance Rayder’s service with the one truth that sells it: he saw where Craster’s sons go, and the Watch looked away. The lie works because it is barely a lie.",
      "The hour’s centerpiece is a chair and a father. Tyrion, scarred and demoted, comes to Tywin to ask for what is his by every law of the realm — Casterly Rock — and receives instead the most complete demolition a parent ever performed on a child: the next whore caught in his bed hangs, and the Rock will go to him never. It is a speech about inheritance that explains three seasons of Lannister behavior in four minutes. Counterweights arrive elsewhere: Margaery Tyrell stops her litter in Flea Bottom to feed orphans, conquering the capital with soup while Cersei watches from a window, and in Astapor Daenerys inspects an army that feels no pain, priced in a currency — cruelty — she has not yet agreed to pay. All men must serve; the question the season asks is whom.",
    ],
  },
  "episode:3-2": {
    paras: [
      "Dark wings, dark words: the news is bad everywhere, and the roads are worse. This is the season’s traveling episode, and its gift is pairing people who should never share a fire. Arya’s little band is scooped up by the Brotherhood Without Banners — outlaws with manners — and her cover survives until a captive Hound looks up and names her in front of everyone, the past arriving like a bill. Bran, fleeing north, meets a boy in the woods who has dreamed his dreams: Jojen Reed gives Bran the word for what he is — warg — and with it the first hint that the crippled Stark is not the story’s leftover but its strangest weapon.",
      "The episode’s sharpest edge is on a bridge in the riverlands, where Brienne and her prisoner finally cross swords and Jaime, half-starved and chained, still nearly takes her — until she beats him down with the patience of a woman who has been underestimated her whole life. Locke’s men arrive before the lesson settles, and both of them belong to the Boltons now. In the capital, Sansa is invited to tea by the Tyrells and, coaxed by kindness — a substance she has not encountered in two years — tells the truth out loud for once: Joffrey is a monster. It is the most dangerous sentence she knows, spoken to the only people who asked, and Olenna Tyrell receives it like a woman confirming a market report.",
    ],
  },
  "episode:3-3": {
    paras: [
      "An episode about competence and its absence, arranged as a comedy until the last thirty seconds. It opens at Riverrun with a funeral: Lord Hoster Tully sent down the river burning — except that Edmure cannot hit the boat with a fire arrow in front of the assembled North, and his uncle the Blackfish shoulders him aside, makes the shot without watching it land, and establishes the Tully chain of command in one gesture. In King’s Landing the joke is drier: Tywin makes Tyrion master of coin, a promotion into other men’s ruin, and Tyrion discovers that Littlefinger’s famous financial genius consists of borrowing millions from Tywin Lannister and the Iron Bank of Braavos. The crown is not rich; it is merely fashionable.",
      "In Astapor, Daenerys makes the season’s boldest trade: all eight thousand Unsullied, plus the boys in training, for one dragon — and Jorah and Barristan protest in unison, which is how the audience knows to pay attention rather than worry. And then the road: Jaime, marched through the dark by Locke’s men, spends his charm buying Brienne’s safety from rape with talk of sapphires, and then overplays the only card he has ever needed — his father’s name. Locke, a small man handed a large opportunity, explains the new order of things with a cleaver. The hand that made Jaime Lannister the finest sword in Westeros lands in the mud, and the season’s great reclamation project begins with a scream and a smash cut to a jaunty tavern song.",
    ],
  },
  "episode:3-4": {
    paras: [
      "The Watch eats itself. At Craster’s Keep, starving men bury Bannen — dead of a wound the ranging’s host would not feed — and the arithmetic of resentment finally carries the room: Craster dies at his own board, guest right shattered, and when the Old Bear commands his brothers to stand down, Rast’s knife answers for the mutineers. Jeor Mormont, who held the Watch together with gristle and habit for a generation, dies on the floor of a wildling’s hovel, strangling his killer, while Sam runs into the night with Gilly and her newborn — the one thing Craster valued, carried off by the one man Craster despised.",
      "The rest of the hour belongs to two monologues and a single word. Varys, gossiping with Tyrion about revenge, opens a crate to show him the sorcerer who cut him as a boy — patience measured in decades, delivered with tea. And in Astapor, the season plays its ace: Daenerys hands over Drogon, takes the whip that commands eight thousand Unsullied, and reveals — in fluent Valyrian, to the slaver who has spent three episodes describing her anatomy in it — that a dragon is not a slave. Dracarys. The Unsullied level Astapor’s masters, the freed army chooses to follow her, and the show mints its single most replayed sequence: the moment Daenerys Targaryen stops being a claimant with dragons and becomes a cause. The episode title, meanwhile, belongs to the Old Bear. His watch is ended; his war is just arriving.",
    ],
  },
  "episode:3-5": {
    paras: [
      "Fire runs through the hour like a signature. It opens in a hollow hill with the Hound on trial before the Brotherhood, facing Beric Dondarrion and a sword that lights like a torch — the one thing Sandor Clegane fears, swung by a man who cannot stay dead. The Hound wins, because the gods of this story are not sentimental, and Beric dies his sixth death and gets up again, diminished — each return, Thoros admits, leaves a little less of him. Meanwhile Jon Snow, in a cave north of the Wall, breaks the vow everyone breaks and keeps the one that matters; kissed by fire, Ygritte says of her own red hair, lucky — and for one stolen hour the show lets two people be happy, which regular viewers correctly read as a storm warning.",
      "The episode’s true center is a bathtub at Harrenhal, where a feverish Jaime Lannister finally tells someone the story he has carried for seventeen years: the Mad King, the caches of wildfire under the city, burn them all — and the choice between his oath and half a million lives. By what right does the wolf judge the lion, he asks, and faints into Brienne’s arms, and the realm’s shorthand for broken honor becomes, for the audience at least, its most misjudged man. The counterexample arrives at Riverrun: Rickard Karstark butchers two Lannister boy hostages in their cells, and Robb — honorable exactly like his father, and exactly as expensively — takes his head over every adviser’s protest. Justice costs him half his army by morning. Doing the right thing, the season keeps repeating, is a bill, not a reward.",
    ],
  },
  "episode:3-6": {
    paras: [
      "The Wall gives the episode its spine and its title: Jon, Ygritte and the free folk go up seven hundred feet of ice that sheds climbers like a dog shaking off water, and the hour keeps returning to them — small figures on a white face, roped to people they cannot entirely trust. When a sheet of ice takes half the party into the void and Orell cuts the rope rather than haul two crows’ weight, the message is tidy: on the climb, everyone is expendable to somebody. The summit earns the season’s one unguarded image — two people above the world, kissing where the maps end.",
      "Down in the warm country, the ladders are made of people. Walder Frey’s price for the bridge Robb needs arrives itemized: an apology in person, Harrenhal in hand, and Edmure Tully at the altar — the Freys collecting on the marriage Robb broke, one Tully down. And in King’s Landing, the episode delivers the series’ thesis statement through Littlefinger, purring over the throne room: chaos isn’t a pit, chaos is a ladder. The speech plays over Ros — sold to Joffrey’s crossbow for informing to Varys — and Sansa weeping on a dock as her ship to safety sails without her. The realm, Littlefinger explains, is a lie people agree to climb. The episode agrees with him, and asks the audience to notice who falls off.",
    ],
  },
  "episode:3-7": {
    paras: [
      "The old song the title borrows is about a bear and a maiden fair, and the episode builds to the literal version: a pit at Harrenhal, a bear the size of a cart horse, and Brienne of Tarth in a dress with a tourney sword — Locke’s idea of an evening’s entertainment. Jaime Lannister, freed, cleaned and pointed toward King’s Landing with his apologies in hand, gets one day down the road before the arithmetic of what he owes turns him around. He jumps into the pit one-handed and unarmored, puts himself between the bear and the maiden, and the pair of them are hauled out by men who cannot afford to lose him. It is the hinge of his whole story: the Kingslayer went back.",
      "Around that center, the season tightens its screws. Daenerys reaches Yunkai and raises her price from passage to everything — every slave freed, or the city breaks — discovering the appetite that conquest feeds. Robb’s camp learns Talisa is pregnant, a small sunlit scene the show hands the audience like a keepsake before the Twins. Melisandre sails up the coast with her purchase, telling Gendry the name of the father he never met. And in a nameless dungeon, the boy playing games with Theon Greyjoy stops pretending to be a rescuer. What his keeper wants from him is not information, and not ransom. It is everything, taken slowly.",
    ],
  },
  "episode:3-8": {
    paras: [
      "Second sons everywhere: the sellsword company of the title, camped outside Yunkai; Tyrion, the Rock’s unwanted spare, standing under a cloak-pinning at his own wedding; even Sam, disowned by Horn Hill, alone in the snow with somebody else’s baby. The wedding is the hour’s set piece — Sansa Stark married to Tyrion Lannister under Tywin’s stage management, Joffrey removing the groom’s stool so the bride must kneel for the cloak, and the groom, drunk past diplomacy, threatening to geld his king with a table knife at the feast. Tyrion plays the fool to walk it back; the fool’s act is the only thing in the room protecting either of them. The bedding does not happen. In that marriage, mercy is the only consummation on offer.",
      "East and north, the episode sharpens two blades. Outside Yunkai, the Second Sons debate murdering Daenerys and send their handsomest captain to do it; Daario Naharis arrives in her tent with his officers’ heads in a bag instead — loyalty, sellsword style, delivered as courtship. On Dragonstone, Melisandre leeches king’s blood from Gendry, and Stannis names three usurpers into the fire: Robb Stark, Balon Greyjoy, Joffrey Baratheon — a scene the season will spend its remaining episodes cashing. And in the snow beyond the Wall, a White Walker comes for Gilly’s son, and Samwell Tarly — fat, frightened, and the only man present — puts a dragonglass dagger into it and watches it shatter. Sam the Slayer, the brothers will mock. He is the first man in eight thousand years to kill one. Nobody believes him, which is the Watch all over.",
    ],
  },
  "episode:3-9": {
    paras: [
      "The wedding at the Twins is the trap the whole season has been baiting, and the episode’s cruelty is in how gently it springs. Walder Frey serves bread and salt — guest right, the oldest law in Westeros — and Robb’s party relaxes by degrees: Edmure’s bride is unexpectedly lovely, the wine flows, Catelyn softens, Talisa and Robb murmur about naming the baby Eddard. The show spends half the hour teaching the audience to exhale. Then the doors close, and the band in the gallery begins to play a song that is not a wedding tune. Catelyn hears it first — the Rains of Castamere, the Lannisters’ hymn about what happens to houses that cross them — and the look on Michelle Fairley’s face does the next ten seconds of storytelling before a single blade shows.",
      "The slaughter is staged as hospitality inverted: crossbows from the minstrels’ gallery, knives from serving men, Talisa stabbed first and where it will hurt Robb most. Catelyn, wounded, plays her last card — Walder Frey’s young wife under her knife, a hostage for a son’s life — and learns the exact worth of a hostage to a man who can always marry again. Roose Bolton delivers the Lannisters’ regards with a blade, Robb dies with his mother’s name in his mouth, and Catelyn’s throat is cut standing in the wreckage of every plan she made to protect her children. Outside, the Stark host is butchered in its camp and Grey Wind is shot in a pen; Arya, arrived minutes too late with the Hound, is carried from the gates unconscious — spared the sight, not the knowledge.",
      "The Red Wedding broke television the way Baelor broke it, but deeper: Baelor killed a man; this killed a cause. The King in the North, his queen, his heir, his mother and his army are erased between courses, not on a battlefield but at a table, under the one protection the entire culture agrees is sacred. That is the point the episode is careful to make — the Freys and Boltons have not just murdered guests, they have broken the compact that makes the realm livable, and the revulsion that follows is not squeamishness but theology. The North’s war ends here. What the North does with the memory becomes, in time, its own story — but that night there is only the music, the doors, and silence where a kingdom used to be.",
    ],
  },
  "episode:3-10": {
    paras: [
      "The finale opens in the ashes of the Twins and refuses to look away: the Stark host burned in its camp, Frey men jeering, and the King in the North paraded with his direwolf’s head sewn where his own should be. Arya, watching from the Hound’s saddle, hears a soldier boast of the sewing and takes her first grown life over it — a knife from nowhere, valar morghulis, and the Hound tidying up after her with something close to respect. The kill is small and the moment enormous: the list is no longer a prayer. Elsewhere the ledger of the wedding is settled in daylight — Roose Bolton is Warden of the North, Walder Frey has his floors scrubbed, and Tywin, over dinner, explains to a horrified small council that a wedding was cheaper than a war, which has the disadvantage of being true.",
      "The episode spends its back half naming things. The smiling boy who has spent a season unmaking Theon Greyjoy introduces himself properly — Ramsay Snow, the Bolton bastard — and christens his creature Reek; on Pyke, Balon shrugs at his son’s severed piece, and it is Yara who commandeers a ship to go get what remains of her brother. At Castle Black, Sam gives Bran the last of his dragonglass and watches him pass under the Wall going the wrong direction — the only man alive who knows what waits up there, letting a boy walk into it because the boy says he must. And in the season’s final image Daenerys, outside Yunkai, waits to learn what she has conquered and is answered by a city’s worth of freedmen chanting a word that is not queen: mhysa. Mother. The crowd lifts her like a relic. It is a triumph shot exactly like a warning.",
    ],
  },

  // ==================== SEASON FOUR ====================
  "episode:4-1": {
    paras: [
      "The cold open is a metallurgy lesson: Ice, the ancestral greatsword of House Stark, melted down in Tywin’s forge and recast as two Lannister blades while the Rains of Castamere plays like a victory lap. Everything the season will do is in that image — the North dismembered into trophies, and even the trophies restless. One blade goes to Jaime, home at last with a stump and a new haircut, who discovers that the family he lost a hand getting back to has no use for a one-handed Kingslayer: his father calls him crippled, his sister has grown cold, and the golden hand Qyburn fits him is the episode’s best joke about ornamental men.",
      "The hour’s new arrival changes the capital’s weather. Prince Oberyn Martell of Dorne turns up early for the royal wedding and is found in Littlefinger’s brothel doing exactly as he pleases, until a Lannister song in the next room turns the charm to ice: his sister Elia, her children, the Mountain — a grudge recited like a genealogy. The Lannisters, he tells Tyrion pleasantly, are not the only ones who pay their debts. And on a road in the riverlands, the season’s other collection begins: Arya and the Hound stop at an inn where Polliver is drinking, the man who stole Needle and killed Lommy with it. She takes the sword back the way it was taken — slowly, through the throat, reciting his own words to him — and rides out with her own horse and something colder than satisfaction. The Hound watches her the way one watches weather turn.",
    ],
  },
  "episode:4-2": {
    paras: [
      "The Purple Wedding is the rare Westerosi celebration where the worst person in the room is also the victim, and the episode makes the audience wait for it in the most uncomfortable way possible: by letting Joffrey be Joffrey at length, with the realm’s dignitaries pinned smiling to their seats. The feast is a gauntlet of cruelties aimed mostly at Tyrion — a war of the five kings re-enacted by dwarfs, wine poured on his head, the cupbearer’s job as public leash — and the hour’s tension is not whether something will happen but how much humiliation the story will bank first. Around the edges, the show seeds the room with motives like a drawing-room mystery: Olenna fussing at Sansa’s necklace, Varys warning, Oberyn fencing with Tywin in gorgeous double-speak.",
      "Then the pie. Joffrey drinks, coughs, claws at his throat, and dies purple and terrified in his mother’s arms — a king poisoned at his own wedding in front of a thousand witnesses, none of whom saw anything. Cersei’s grief goes straight to verdict: her finger finds Tyrion, standing over the corpse holding the emptied cup, and the episode snaps shut on his arrest. The staging is meticulous about what the audience does and does not see; on rewatch the mechanism is all there — the necklace, the stone missing, the cup’s travels — but first time through, the show gets exactly what it wants: relief, horror at the relief, and a frame around the one Lannister innocent of this particular crime.",
      "Structurally, the episode is Baelor’s dark twin: once again a king’s caprice was the board’s most unpredictable piece, and once again the story removes it — but where Ned’s death opened a war, Joffrey’s opens a trial, and the trial will do what trials do in this story, which is measure everything except guilt. Off in the North, the hour makes sure no one mistakes the death for the end of cruelty: at the Dreadfort, Ramsay hunts a girl through the woods with hounds for sport and shows his visiting father what is left of Theon Greyjoy — proof that the realm’s supply of monstrous sons did not die with the king. The wedding got the headlines. The kennel is the forecast.",
    ],
  },
  "episode:4-3": {
    paras: [
      "The bells are still ringing for Joffrey when the scramble starts. Sansa is rowed out of the city mid-chaos by Ser Dontos, the fool she once saved — and delivered to a waiting ship where Littlefinger pays off his ferryman with three crossbow bolts and explains, with professional pride, that the necklace Sansa wore to the wedding was the murder weapon. She has been an accessory since she dressed that morning. In the sept, Tywin conducts a job interview over Joffrey’s corpse, quizzing Tommen on what killed each bad king in history while the boy’s mother grieves three feet away — wisdom, the old lion concludes, meaning: listen to me. The dynasty does not pause for its dead.",
      "The episode’s title belongs to Meereen, where Daenerys arrives before the walls and the city sends out a champion to insult her; Daario opens him with a thrown knife and a bow, and Dany’s answer to the jeering battlements is catapults — barrels bursting on the stones, spilling the broken slave collars of every city behind her. It is siegecraft as propaganda, and it works. In the middle distance, the hour banks quieter troubles: the Hound robs the farmer who sheltered them because the man will not survive winter anyway — Arya adding it to a private ledger — and at Dragonstone, Davos, jolted by a book about Braavos, hits on the idea of borrowing the Iron Bank’s patience. The realm’s wars, the episode keeps noticing, are funded, ferried and fed by people who never appear on the banners.",
    ],
  },
  "episode:4-4": {
    paras: [
      "An episode named for a sword, organized around what oaths are worth. Jaime — freshly returned, publicly useless, and privately reassembling himself — gives Brienne the Valyrian blade his father forged from Ned Stark’s greatsword, plus armor, plus Podrick, and a commission that is really a conscience: find Sansa Stark, keep her safe. Brienne names the sword Oathkeeper, which is either irony or repair depending on the light — Stark steel, Lannister guilt, and the two most oath-burdened people in the realm dividing one promise between them. It is the season’s cleanest transaction: for once, something of value goes to someone who deserves it.",
      "The rest of the hour is oath-breaking in ascending order. In Meereen, Daenerys answers the crucified children of the road with a hundred and sixty-three crucified masters and calls it justice while Barristan urges mercy — the first time her arithmetic openly frightens her own council. At Craster’s Keep, the Watch’s mutineers drink from the Old Bear’s skull, having broken every vow the order owns, and Bran’s party blunders into their hands. And in the far north, the episode quietly detonates its biggest reveal: a White Walker carries Craster’s last son to an altar of ice, and a crowned figure lays a nail of a finger on the child’s cheek — blue eyes opening on a transformation the books had only whispered about. The dead are not just rising; they are being made. Somebody, it turns out, has been keeping the oldest bargain in the story all along.",
    ],
  },
  "episode:4-5": {
    paras: [
      "Tommen is crowned — first of his name, gentlest of his line — and the episode immediately shows the realm reorganizing around the vacancy where fear used to be. Margaery works the boy-king with a smile calibrated to the millimeter; Cersei, in the hour’s slyest scenes, plays gracious with Margaery, Tywin and Oberyn in turn, extracting sympathy for the trial while the audience watches her sharpen every conversation into a shiv aimed at Tyrion. Tywin, candid for once, admits the mines of the Westerlands ran dry three years ago — the richest house in the realm is living on reputation and Braavosi credit, which explains more about Lannister policy than any speech about legacy.",
      "The Vale delivers the season’s true bombshell over soup. Lysa Arryn, married to Littlefinger within an hour of his arrival, shrieks her jealous devotion — and in the shrieking confirms what she did for him: the poisoning of Jon Arryn, her own husband, and the letter to Catelyn blaming the Lannisters. The entire war — Ned’s ride south, the dagger, everything — was authored by Petyr Baelish before the first episode began, and the story hands the revelation not to a court but to a nervous bride in an echoing hall. Meanwhile Jon storms Craster’s Keep and burns the Watch’s shame to the ground; Bran, hiding a warg’s reach away from the brother he cannot risk meeting, wargs Hodor to snap Locke’s neck and slips away north. Two Starks pass in the night, close enough to call out. The story is not done using either of them, so neither does.",
    ],
  },
  "episode:4-6": {
    paras: [
      "The laws of gods and men, weighed and found negotiable. The episode opens in Braavos, inside the Iron Bank at last — Stannis and Davos across a very long table from Tycho Nestoris, learning that the rightful heir of Westeros rates below a solvent one. It is Davos who saves the meeting, four shortened fingertips on the table as collateral of character: his king pays his debts, in full, personally. The bank votes with the ledger. At the Dreadfort, Yara Greyjoy’s raid reaches her brother’s kennel and founders on something worse than Ramsay’s knives — Reek, cowering from rescue, biting the hand that came for him. My brother is dead, she tells her crew, and it is diagnosis, not eulogy.",
      "The back half is the trial of Tyrion Lannister, and it is theater with a script: Meryn Trant, Pycelle and Varys recite curated truths; Cersei conducts; Tywin presides with the verdict pre-signed. The ambush is Shae — the one witness who knew him — reading out their intimacies twisted into evidence, and something in Tyrion audibly breaks. What follows is the series’ single greatest courtroom scene: he confesses, not to the murder, but to being a dwarf, on trial for it his whole life; tells the court he wishes he had let Stannis burn them all; and torches the script with the only move left — I demand a trial by combat. Tywin’s face is the punchline: the machine built to crush his son has just been handed back to the gods, and the gods, in this city, take bribes.",
    ],
  },
  "episode:4-7": {
    paras: [
      "An episode about champions — who fights for whom, and what it costs to have someone in your corner. Cersei resolves the trial’s arithmetic by naming Ser Gregor Clegane, and the show reintroduces the Mountain disemboweling prisoners for exercise. In his cell, Tyrion holds auditions: Jaime cannot fight with his left hand, and Bronn — in the pair’s bittersweet last scene of the season — declines with the honesty that made him likable: he likes Tyrion, but he likes himself more. When has anyone risked everything for him, Bronn asks, and the answer walks in wearing Martell colors. Oberyn Martell volunteers to be Tyrion’s champion for reasons that have nothing to do with Tyrion: the Mountain killed his sister, and the Crown has finally arranged for the two of them to meet legally.",
      "The title’s mockingbird is Littlefinger, and the Vale pays out his long game in the snow. Sansa, building Winterfell out of drifts in the Eyrie’s garden, gets a kiss she did not ask for; Lysa sees it, and the episode ends with the season’s most vertiginous domestic scene — Sansa held over the Moon Door by her own aunt, then Lysa held over it by her own husband. Only Cat, he tells her, and lets go. Elsewhere the Hound, bitten and refusing fire to cauterize it, tells Arya the true story of his burns — a brother, a brazier, a father’s lie — and lets her clean the wound: trust, from a man who has none to spare. Champions everywhere; the trick, the hour suggests, is surviving yours.",
    ],
  },
  "episode:4-8": {
    paras: [
      "The duel the season promised, staged in sunlight with the whole capital watching. Oberyn Martell fights the way he talks — spinning, showboating, gorgeous — and the spear does its work: the Mountain armored and enormous, cut down by degrees, flat on his back with Dornish steel in his chest. It should end there. But Oberyn did not come for a verdict; he came for a confession, and he circles the dying giant demanding the words — say her name, say you killed her, tell me who gave the order — because a win that leaves Tywin unindicted is no win at all. Elia Martell’s name in the arena air is worth more to him than Tyrion’s life or his own, and the Mountain, granted one last moment of lucidity, gives him both answers and death: a sweep of the leg, thumbs in his eyes, the confession roared as a boast while he crushes the prince’s skull with his hands.",
      "It is the show’s cruelest structural joke — a trial by combat decided after the combat was over, a champion killed by his own need for the truth — and the episode is honest about the cost radiating outward: Ellaria’s scream, Tyrion condemned to death by his father from the box, and in Dorne, though the season only gestures at it, a war being conceived. Around the arena the hour arranges its quieter judgments. Sansa, at the Eyrie’s inquest, lies for Littlefinger with a performance that saves him and banks him — then descends the stairs transformed, a girl done waiting for rescuers. Jorah Mormont’s old sin surfaces in Meereen by way of a royal pardon with Robert’s signature, and Daenerys exiles the man who loves her most rather than hear the case for forgiveness.",
      "The title’s pairing is exact: the Mountain and the Viper, force and finesse, and the episode’s verdict is that finesse dies when it stops to gloat — but also that force wins nothing either, since Gregor Clegane leaves the arena poisoned on the spear’s edge, a detail the capital will learn slowly and regret at leisure. Moments before the duel, the show files its saddest scene almost as an aside: Grey Wind’s— no, this hour it is the Hound and Arya arriving at the Bloody Gate to ransom her to an aunt three days dead, and Arya laughing — actually laughing — at the sheer, exhausted comedy of her luck. The gods of this story have a sense of humor. It is not a kind one.",
    ],
  },
  "episode:4-9": {
    paras: [
      "Like Blackwater before it, the hour stays at one castle for one night — but this time the audience has lived at Castle Black for four seasons, and every corridor has a name attached. Mance Rayder’s horde comes at the Wall from both sides at once: giants and mammoths at the gate, Tormund and the Thenns swarming the undefended southern approach through Mole’s Town’s ashes. The episode is a masterclass in geography — the winch cage, the tunnel, the top of the Wall and the yard below run as parallel theaters — and in institutional truth: Ser Alliser Thorne, wrong about everything all season, turns out to be exactly the man you want on the wall-walk, roaring at his brothers to fight until Tormund’s axe finds him. When Janos Slynt’s nerve breaks, command falls to Jon Snow by simple gravity: he is the one still giving orders.",
      "The deaths are the Watch’s own household gods. Grenn holds the inner tunnel against a giant king with five brothers, all of them reciting the vow as the darkness comes on — the oath as a thing men say to keep their feet planted. Pyp dies surprised in Sam’s arms. And Ygritte, arrow nocked with Jon in her sights, hesitates the half-second that defines her, and takes a shaft from Olly, the boy whose village her raiders burned. She dies in Jon’s arms mid-battle, with the only sentence either of them ever fully meant: you know nothing, Jon Snow. The show grants them their cave for one line, then takes it away. Kissed by fire, buried in snow.",
      "Dawn finds the Watch standing — barely, temporarily, and knowing it. The scythe has cleared the climbers, the tunnel has held, but Mance has a hundred thousand and the Watch has fewer than a hundred left who can fight; tonight was a probe, not the war. So the episode ends on the season’s starkest decision: Jon hands Longclaw to Sam — no point taking a sword where he is going — and walks out the northern gate alone, unarmored, to kill Mance Rayder in his own camp or die trying. The gate grinds shut behind him and the shot holds on the tunnel’s dark mouth: one man, walking into an army, because the arithmetic works no other way. For once, the show lets a battle episode end not with victory or defeat, but with a door closing.",
    ],
  },
  "episode:4-10": {
    paras: [
      "The children of the title are everywhere once you start counting: the children of the forest, the children men raise, and the children they ruin. The finale opens by resolving Jon’s suicide walk with cavalry — Stannis Baratheon, of all people, breaking the wildling camp with the only army that answered the Watch’s letters, the Iron Bank’s gold spent where the realm’s conscience should have been. Mance yields rather than let his people bleed; Jon, asked what Ned Stark would do with the prisoner, answers honestly, and the season’s northern war ends not in slaughter but in custody. Beyond the Wall, Bran’s party reaches the heart tree at terrible cost — Jojen dies at its roots — and beneath it a man grown into the wood makes the series’ strangest promise: Bran will never walk again, but he will fly.",
      "In the Vale’s foothills, the show stages the fight it spent two seasons arranging: Brienne of Tarth and Sandor Clegane, two of the realm’s best, brawling over which of them gets to protect a girl who wants neither. It is ugly, magnificent and pointless — while they fight, Arya slips away, and when she finds the Hound broken at the bottom of the bluff, she conducts the season’s coldest transaction: he begs, argues, and finally taunts her toward mercy, and she takes his silver and leaves him to the rocks. Whether it is vengeance or the only mercy she has left, the show declines to say. She spends his coin on a ship, gives the captain a different coin and two words — valar morghulis — and sails for Braavos, the last shot of the season carrying her toward the house with the black-and-white door.",
      "And in King’s Landing, the Lannister family drama arrives at its privy. Jaime frees his brother; Tyrion, detouring through the Tower of the Hand, finds Shae in his father’s bed and strangles her with the chain she wears, then takes a crossbow to find Tywin enthroned in the smallest room of the keep. Their last conversation is the family in miniature — Tywin still negotiating, still certain, still saying whore — and the bolt Tyrion puts in him is punctuation the whole series has been withholding. The great lion of Lannister dies on a toilet, killed by the son he sentenced, and the bells that ring are for more than a Hand: the realm’s indispensable man is gone, and every ambition he was sitting on stands up at once. Tyrion goes into a crate, and east.",
    ],
  },
});
