/* GoT wiki long-form archive — the hours retold, S5–S8. Original prose. */
Object.assign(WIKI_EXTRA, {

  // ==================== SEASON FIVE ====================
  "episode:5-1": {
    paras: [
      "The season opens by reopening a wound nobody asked to see stitched shut: a girl-queen’s flashback, a hedge witch’s hut, and a prophecy — younger and more beautiful queen will cast you down, gold their shrouds — planted in Cersei Lannister a lifetime before it had anywhere to land. Tywin lies in the sept below, and with him goes the only discipline the Lannister machine ever answered to. What the flashback really explains is not fate but character: a girl told her whole life was a countdown grew into a woman who now counts brothers, wondering which of them the valonqar clause means. Across the sea, Tyrion arrives in Pentos folded into a crate, drunk on grief and cheap wine, and Varys offers him the one thing exile hasn’t: a queen worth being useful to.",
      "Everywhere else the season states its premise — three seats of power and no one steady enough to hold any of them. At the Wall, Stannis gives Mance Rayder the mercy of a choice and the King-Beyond-the-Wall chooses the pyre over the knee, and it is Jon Snow’s arrow, not Stannis’s judgment, that ends it kindly. In Meereen, masked killers start murdering freedmen and soldiers alike in the dark — the Sons of the Harpy, the season’s slow bleed, announcing that liberation and government are different jobs. The hour’s throughline is vacancy: a dead Hand, an untested queen, a broken king-in-exile, a season that will spend itself finding out what fills the gaps power leaves behind.",
    ],
  },
  "episode:5-2": {
    paras: [
      "A door of ebony and weirwood, carved with a thousand faces, and Arya Stark stands in front of it starving and unimpressed — Braavos does not care that she crossed an ocean to get here. When it finally opens, on the face of the man she knew as Jaqen H’ghar wearing a face that is and isn’t his own, the House of Black and White reveals its terms: not sanctuary, but a school with a curriculum that starts by taking away the one thing she has left, her name. It is the season’s cleanest image for what all its plots are secretly about — the price of becoming what you need to be.",
      "The rest of the map pays out old debts unevenly. Brienne finds Sansa on the road with Littlefinger and offers her sword a second time; Sansa, half out of grief and half out of a hard new pragmatism, refuses her again, choosing the man with a plan over the woman with only an oath. In Dorne, Oberyn’s death has curdled into two factions rather than one grief — Ellaria wants Lannister blood, Doran wants patience Dorne can no longer afford — and the split will cost the region its independence from the war for good. In Meereen, Daenerys metes out equal justice to a freedman who murdered a Harpy in vengeance, and discovers that a queen who treats mercy as a rule rather than a relationship pleases absolutely no one.",
    ],
  },
  "episode:5-3": {
    paras: [
      "Cersei’s worst decisions have always looked like her cleverest ones in the moment, and the hour’s title belongs to her masterpiece of self-sabotage: recruiting a barefoot zealot and his Faith Militant to humble Margaery Tyrell, mistaking a fanatic for a tool she can put down when she’s finished with it. The High Sparrow speaks the language of humility and means every word, which makes him the one person in King’s Landing immune to Cersei’s usual currencies — flattery, fear, family name — and the queen mother hands him an army because she cannot imagine losing an argument to a man in rags. It is the funniest and most expensive misjudgment of her life, and the show lets her walk out of the soup kitchen looking pleased with herself.",
      "North, the machinery Littlefinger built in season four finally delivers its cargo: Sansa Stark returns to Winterfell as Ramsay Bolton’s intended bride, walking back into the home her family lost to marry into the house that took it, smiling for an audience of Boltons because Littlefinger has taught her that survival wears a pleasant face. At Castle Black, Jon Snow is elected Lord Commander by a margin no one is thrilled about, and his first real order — sparing no one, not even the officer who despises him, for a crime the order can’t forgive — costs Janos Slynt his head and buys Jon exactly the authority a hard first day is supposed to buy: obedience without affection.",
    ],
  },
  "episode:5-4": {
    paras: [
      "The Faith Militant, armed and unshackled, discovers what teeth feel like: Loras Tyrell is dragged off for his private life and Tommen, the gentlest king the show has offered, discovers that a crown confers no actual power over men who answer to a higher and angrier authority — he bounces off the sept’s doors like a boy locked out of his own house. It is the season’s bluntest lesson about institutions: the ones you arm to fight your enemies rarely stay pointed only at them. In Dorne, Jaime and Bronn wade ashore on a rescue mission that is really an apology in disguise, while the Sand Snakes conduct their war council over Oberyn’s grave, voting for vengeance the old-fashioned way — with spears rather than patience.",
      "The hour’s two tenderest scenes sit uneasily beside its cruelest. Stannis, asked by his daughter about the greyscale that scarred her, gives Shireen the only kind of love he has ever known how to offer — not comfort, but honesty, and the plain, furious statement that he fought for her life when doctors had given up on it. It is as close as the show lets him come to warmth, which makes what the season eventually asks of him almost unbearable in hindsight. In Meereen, the Sons of the Harpy finally draw blood that matters: an ambush in the tunnels wounds Grey Worm and kills Barristan Selmy, the last knight of the old Kingsguard, cut down not in some legendary last stand but jumped in an alley by masked cowards — a death the show refuses to dignify with music, because that is the whole point of it.",
    ],
  },
  "episode:5-5": {
    paras: [
      "Maester Aemon’s advice to Jon — kill the boy, and let the man be born — gives the hour its title and its argument, and Jon spends the episode proving he heard it: he opens the Wall to the free folk his brothers hate, gambling his command on the wager that living enemies beat dead recruits for the war actually coming. It is the least popular decision a Lord Commander has made in the show’s run, and the show is careful to make clear it is also the correct one. South, Stannis marches on Winterfell with his wife, his daughter and his red priestess in tow, converting a military campaign into a pilgrimage — a choice about to prove the difference between the two is not academic.",
      "In Meereen, Daenerys tries to rule the way her advisors keep telling her a queen should — feeding a slaving Master to her dragons on suspicion alone, then offering marriage to a Meereenese nobleman to buy the peace her armies can’t — and neither gesture looks like the woman who broke chains in Astapor; it looks like a monarch running out of easy answers. And in the ruins of Valyria, Tyrion and Jorah drift past the Doom’s petrified stone men reciting poetry to keep their nerve, until one of the plague-ridden wretches grabs the dwarf by the wrist — a quiet, horrible reminder that in this world the past is never actually past, just sleeping in the water.",
    ],
  },
  "episode:5-6": {
    paras: [
      "Arya’s first true test at the House of Black and White comes disguised as a kindness: a dying girl asks for water, and the assassin’s apprentice gives her both water and mercy in the same cup, only to be told that neither belonged to her to give. The lesson is the season’s cruelest one about identity — that becoming no one means surrendering the very impulses that make Arya Stark worth following — and the show trusts the audience to feel the wrongness of the trade even as the House insists it is generosity. At Winterfell, the marriage the realm has been dreading arrives at last, and the show stages Ramsay’s wedding-night cruelty with Theon forced to watch — not for spectacle, but to complete the season’s bleakest circle: the boy who broke Winterfell made to witness what breaking a person, entirely and on purpose, actually costs.",
      "Elsewhere the hour distributes smaller reckonings. In Dorne, the rescue mission that has spent an episode building toward violence resolves itself almost apologetically — Myrcella and Trystane’s betrothal survives, Areo Hotah’s axe settles what words couldn’t, and the whole subplot exhales rather than detonates. Olenna Tyrell returns to King’s Landing to buy her grandchildren’s freedom and meets, for once, an opponent with nothing she can purchase — the High Sparrow answers her threats with scripture, and the Queen of Thorns leaves the sept for the first time in her life without having won. And far east, Tyrion and Jorah are sold into slavery and marched toward Meereen’s fighting pits, the dwarf talking his way toward relevance the only way he knows how, one step ahead of the sword.",
    ],
  },
  "episode:5-7": {
    paras: [
      "The Wall loses its oldest resident this hour: Maester Aemon dies murmuring his brother’s childhood name — Egg — a hundred and two years of Targaryen history closing out in a small room, unwitnessed by the throne it might have changed everything to claim. Jon rides for Hardhome in his absence, gambling the Watch’s last credibility on a fishing village of strangers who have spent their lives being told the men in black cloaks are the enemy. Back at Winterfell, Sansa’s single chance at rescue depends on Theon lighting a signal candle in a broken tower — and the show makes the betrayal land harder by making it understandable: Reek has been so thoroughly unmade that loyalty to his own survival outweighs loyalty to a girl he once knew as a friend, and he carries her plea straight to Ramsay instead.",
      "In Meereen, Jorah’s last gambit pays off in the strangest currency the show has offered a queen: not gold, not an army, but Tyrion Lannister, delivered into the fighting pits and bowing with the driest joke he has — I am the gift. It is the meeting the season has been engineering for years, two of the world’s cleverest exiles finally in the same room. And in King’s Landing, Littlefinger’s slow-motion demolition of Cersei reaches its punchline: he hands Olenna a weapon disguised as gossip, and Cersei, visiting Margaery’s cell to gloat, walks out of the sept in chains of her own — the season’s recurring joke about the High Sparrow finally landing on the woman who built his army for him.",
    ],
  },
  "episode:5-8": {
    paras: [
      "The chessboard resets before the hour turns north: Daenerys formally takes Tyrion as an advisor and sends Jorah away for a second, harder exile, while in Braavos Arya settles deeper into her cover as Lana the oyster girl, cataloguing a thin man for the Many-Faced God with the patient cruelty of someone learning to enjoy the work. Both scenes are throat-clearing for what the episode actually came to do, and the show knows it — every other plotline gets exactly enough runway to remind the audience it still exists before the hour turns its full attention north, to a fishing village called Hardhome and the largest gathering of the free folk left alive.",
      "What Jon finds there is not the horde the Seven Kingdoms fear but a people — cookfires, quarreling chieftains, giants stooping through doorways built for men — and the diplomacy plays out in miniature all its own tragedy: too many souls, too few boats, and Tormund’s brute charisma the only thing standing between an alliance and a riot. The show lingers on faces the audience has known for thirty seconds, because it needs the horror that follows to cost something. Karsi, a mother who puts her daughters on the first boat and stays to fight, becomes the episode’s conscience in the space of a single scene.",
      "Then the storm arrives, and Hardhome becomes the show’s first unambiguous demonstration that the thing beyond the Wall is not folklore. The dead come out of the treeline in a wall of white eyes and grasping hands, and the Night King, watching from a rise with the patience of something that has outlasted every human timescale, raises the newly slaughtered with two slow lifts of his arms — an army built in real time out of the very people it just killed. Jon’s Valyrian steel proves dragonglass wasn’t a fluke, cutting down a White Walker in a shower of ice, but the good news is dwarfed by the arithmetic: for every wildling saved on a boat, a hundred rise on the shore behind them. It is the episode that changes what kind of show this is — the war of five kings was always going to end; this is the one nobody in Westeros has figured out how to.",
    ],
  },
  "episode:5-9": {
    paras: [
      "Stannis Baratheon’s march on Winterfell was always a wager against the season, and the hour opens with the bill coming due: twenty of Ramsay’s riders slip past his pickets in the night and burn his baggage train to ash, leaving the self-declared king stranded in the snow with a starving host and no way forward or back. It is the least glamorous kind of military disaster — not a battle lost but a campaign strangled by weather and logistics — and it strips Stannis down to the one resource he has always trusted more than food or men: his certainty that the red god wants him on the throne.",
      "What that certainty costs is the hour’s darkest passage and one of the show’s most argued-over scenes. Melisandre convinces Stannis that Shireen’s king’s blood can melt the snow the way Renly’s and Robb’s and Joffrey’s once seemed to end their claims, and the show refuses to look away from what follows — a father walking his daughter to the pyre while she screams his name, believing until the very last second that this, too, is a kind of duty. It is the point at which Stannis stops being a rigid but honorable man and becomes something the audience cannot forgive, and the show is exact about making sure no music, no framing, softens the murder into anything other than what it is.",
      "Half a world away, in the golden light of Daznak’s Pit, the season stages its other extreme — wonder instead of horror, arriving in the same hour as a corrective. The Sons of the Harpy spring their ambush during the fighting-pit games, cutting down soldiers and nobles alike in a locked arena, and just as the trap closes on Daenerys herself, Drogon answers a mother’s scream for the first time since Astapor, landing in a burst of fire and carrying her up and out over the rooftops of Meereen — the first Targaryen to fly in a hundred years, escaping a massacre on the same night her rival immolates a child for the exact opposite reason. The episode’s cruelty and its awe are not opposites; they are the same coin, the season’s recurring argument about what fire and blood actually buy.",
    ],
  },
  "episode:5-10": {
    paras: [
      "Winter finishes what the burning started. Stannis’s host deserts him overnight — soldiers do not forgive what he did to buy good weather — and Brienne of Tarth finds him alone against a tree with nothing left to command, and delivers, at last, the sentence she swore years ago in a tent at Storm’s End for a king she loved and lost to a shadow with his own brother’s face. It is one of the season’s few deaths that plays as satisfaction rather than tragedy, an oath honored on schedule after two seasons of patient waiting, and the show grants it almost no ceremony — a sword, a nod, and the snow closing back over the story of a rightful heir undone by his own certainty.",
      "In King’s Landing, the season’s cruelest engine of comeuppance finishes its work on the queen who built it: Cersei confesses to a fraction of her sins, is shorn in a cell, and walks the mile from the sept to the Red Keep naked, pelted with filth while the city she has spent years terrorizing chants Shame at her like a bell tolling. The sequence is filmed with an unflinching, almost clinical patience — the camera studies Cersei’s face as much as the crowd’s cruelty — because the show wants the audience to feel two contradictory things at once: that she has earned every step, and that watching a person broken in public, regardless of who they are, is its own kind of horror. At Winterfell, in the episode’s gentler mirror image, Sansa and Theon choose the jump off the battlements into the snow together rather than one more night under Ramsay’s roof — a small, cold, hopeful ending stitched into the same hour as Cersei’s public ruin.",
      "The season closes on two falls that are really the same fall told twice. Arya, given Meryn Trant at last, takes his eyes and his life in a Braavosi brothel — vengeance she was explicitly forbidden — and the Many-Faced God’s house answers by taking her sight, the price for stealing a debt that belonged to no one. And at Castle Black, Jon Snow’s mercy toward the free folk, the very choice that made him a leader worth following, gets him a dagger from a boy he saved and then blades from officers who never forgave him for it — For the Watch, they say, and Olly’s knife goes in last and worst. The season began by asking what fills a vacuum of power; it ends by demonstrating that doing the right thing, in this story, has never once been the same as doing the safe one — a lesson every major character in the finale learns at exactly the same, unbearable moment.",
    ],
  },

  // ==================== SEASON SIX ====================
  "episode:6-1": {
    paras: [
      "The season opens holding its breath over a body. Davos and a handful of loyalists barricade themselves in a room at Castle Black with Jon Snow’s corpse behind them and Ghost pacing the door, and the hour is careful not to promise anything — this is grief administered as siege, men defending a dead man’s privacy from the officers who killed him rather than defending a cause. At Winterfell’s edge, Sansa and Theon’s flight through the snow runs out of road exactly when it needs to, and Brienne of Tarth’s oath — sworn twice and refused twice across two seasons — is finally accepted, not with ceremony but with a girl too exhausted to keep saying no to help.",
      "Dorne pays for its coup in the same hour it staged it. Ellaria Sand and the Sand Snakes murder Prince Doran, his loyal captain Areo Hotah, and Trystane Martell in quick, graceless succession, seizing a house whose entire political value depended on the patience they’ve just discarded — a promise of chaos as governance that the season will spend little further time on, because the show has already made its point: violent men and women who overthrow careful rulers rarely turn out to be careful rulers themselves. And in a chamber at Dragonstone, Melisandre unclasps the ruby at her throat in private for the first time, and the mirror answers with centuries where a young woman’s face should be — the season’s first hint that faith, in this world, may be a much stranger and older trade than anyone watching has assumed.",
    ],
  },
  "episode:6-2": {
    paras: [
      "Bran’s education under the Three-Eyed Raven takes him somewhere the season has been circling for years: a younger, whole Winterfell, where a stableboy named Wylis speaks in full sentences and answers to nothing like the name the world will later give him. It is a small, devastating preview of a larger reveal the season is not ready to cash yet, and the show lets the visit sit unexplained, a mystery stacked on a mystery. At Castle Black, the wildlings simply walk the mutineers’ garrison down without a fight — Tormund and Wun Wun make a persuasive argument out of numbers alone — and the men who murdered their Lord Commander are marched to the cells to wait for a judge who, unbeknownst to them, may not stay dead.",
      "On Pyke, the Iron Islands settle an old grudge the way they settle everything — with iron. Balon Greyjoy meets the brother he exiled on a rope bridge in a gale, and only one man walks off it; Euron Greyjoy returns from his long absence claiming the storm itself as kinship, and the show gives him exactly one entrance to establish he is the season’s strangest and most dangerous new player. And at Castle Black, Melisandre — faithless, out of options, trying a spell she does not believe will work — washes a dead man’s body and prays without conviction, and Ghost stirs, and Jon Snow gasps back into a story that was not supposed to have room for him anymore. The show underplays the miracle almost to a fault: no triumphant music, just a man breathing air that shouldn’t be his to breathe.",
    ],
  },
  "episode:6-3": {
    paras: [
      "Jon Snow’s return comes with an immediate, brutal piece of housekeeping: he hangs the mutineers who murdered him, Olly last of all, and then does something none of his predecessors ever managed — walks away from the job entirely. Death released him from his vows, he reasons, with the precise, lawyerly logic of a man who has just been given the rarest gift in Westeros and intends to use it; my watch is ended lands as both liberation and a quiet renunciation of everything the Watch asked of him. Beyond the Wall, Bran’s visions carry him to the Tower of Joy for the first time, watching a younger Ned Stark tell a story about how a fight was won that the vision itself is already contradicting — the show’s most patient long game finally showing its hand, one careful frame at a time.",
      "At Winterfell, the Umbers arrive bearing gifts calculated to prove loyalty to the wrong side: Osha the wildling, a captured Rickon Stark, and the head of his direwolf, handed over to Ramsay Bolton as tribute — the last free Stark child delivered, without ceremony, into the household that broke his family. In Braavos, Arya’s long punishment ends the moment she stops needing an ending: beaten and blind for weeks, she finally answers a girl has no name and means it completely, and the fountain water she drinks afterward restores her sight on precisely the day the show has decided she no longer requires it to prove anything.",
    ],
  },
  "episode:6-4": {
    paras: [
      "The season’s first genuine reunion arrives without fanfare: Sansa Stark reaches Castle Black and finds her half-brother alive against every reasonable expectation, the first time two Stark children have stood in the same room since Winterfell burned. What follows is not a triumphant homecoming so much as two survivors comparing wounds — Sansa is done running, Jon is tired of fighting other people’s wars, and Ramsay’s letter, demanding her return and threatening Rickon’s life in the same breath, is what finally moves Jon from reluctance to resolve. Littlefinger, meanwhile, slides back into the Vale unbothered by any of it and aims Robin Arryn’s knights north, setting up an intervention no one at Castle Black knows is coming.",
      "In Vaes Dothrak, Daenerys turns a death sentence into a coronation. Sentenced to the temple of the dosh khaleen for the crime of widowhood, she instead locks the khals in with the burning braziers and walks out of the flames unburnt for the second time in her life, and the surviving Dothraki — faced with a choice between a dead god and a living one — kneel by morning. It is the show’s cleanest demonstration of how Daenerys actually accumulates power: not by asking, but by making refusal look like a worse bet than surrender. On Pyke, Theon returns from his long ordeal not to reclaim a crown of his own but to kneel for his sister’s, the season’s quietest and most complete character reversal, finally putting someone else’s survival ahead of his own ambition.",
    ],
  },
  "episode:6-5": {
    paras: [
      "Sansa spends her return to the North settling a score she has been carrying since her wedding, confronting Littlefinger with the plain cost of the bargain he sold her into — not gratitude for the rescue but an accounting of what the rescue required first. On Pyke, the kingsmoot crowns Euron Greyjoy over his niece by acclaim and violence in equal measure, and Yara and Theon, refusing to serve under an uncle who murdered their father, answer the vote by stealing the best ships of the Iron Fleet in the dead of night — a coup answered by a heist, in the ironborn style.",
      "Beneath a weirwood far north, Bran’s education finally outstrips its own safety net: left alone for a moment too long, he reaches for the Night King in a vision and the Night King reaches back, and the cave’s ancient wards fail all at once. What follows is the show at its bluntest about cost — Summer dies buying seconds, the Three-Eyed Raven dies after a thousand years of watching, the last of the children of the forest dies undoing what her own kind once made — and at the center of the collapse, Hodor holds a door against the entire onslaught while a vision from decades earlier reveals, in a single devastating stroke, exactly why he has only ever been able to say that one word. Hold the door, warped by a boy’s desperate warg across time into a single collapsing syllable, is the show’s cruelest use of its own magic: a tragedy engineered, unknowingly, by the person it destroys.",
    ],
  },
  "episode:6-6": {
    paras: [
      "A dead man saves the living in the woods beyond the Wall — Benjen Stark, the First Ranger everyone assumed lost to the same dark that made the Night King’s army, returns half-wight and half-Watch, carrying Bran and Meera to safety with a foot in both worlds. At Horn Hill, Samwell Tarly brings Gilly home to the family that disowned him, receives his father’s contempt in the same voice and same room as before, and quietly walks out with Heartsbane, the Tarly ancestral sword — a small act of theft that plays as the largest act of self-respect Sam has managed in five seasons.",
      "In King’s Landing, Margaery converts the crown itself to the Faith’s cause, engineering a fusion of throne and sept that briefly looks like it might save both her family and her husband’s reign — a performance of penitence so precise the High Sparrow, for once, cannot tell where the acting stops. In Braavos, Arya is sent to kill an actress and instead saves her, refusing the Many-Faced God’s indifference to a life that has nothing to do with her old list — a decision that earns her the Waif’s death warrant and, not incidentally, proves the House never actually managed to erase Arya Stark of Winterfell. And at Vaes Dothrak, Daenerys addresses a hundred thousand riders with a dragon circling overhead, and the show barely needs the speech — the image does the work of finally making her invasion of Westeros look inevitable rather than aspirational.",
    ],
  },
  "episode:6-7": {
    paras: [
      "Sandor Clegane, presumed dead since a hillside beating two seasons back, turns up very much alive and swinging an axe for a peaceable little religious commune — a Hound gentled, however briefly, by a septon who talks to him like a person rather than a monster. The show gives him just enough of that fragile peace to make its destruction, when rogue members of the Brotherhood Without Banners arrive and take what isn’t theirs, land as a real loss rather than a plot beat. North, the recruitment drive for Jon and Sansa’s war finds its most memorable ally in Lyanna Mormont, ten years old and utterly unimpressed by grown men’s speeches, who pledges her house’s sixty-two soldiers with the flattest, most withering stare the season offers.",
      "At Riverrun, Jaime Lannister arrives to find the castle held not by loyal Freys but by the Blackfish, and discovers that his gift for diplomacy has limits when the man across the table has nothing left to lose and no patience for Lannister charm. And in Braavos, Arya’s attempt to finally book passage home ends on a bridge with the Waif’s knife in her stomach — the season’s cruelest cliffhanger, closing on a girl bleeding into a canal in a city built on the idea that identity is negotiable and death is a service anyone can order.",
    ],
  },
  "episode:6-8": {
    paras: [
      "The Hound gets his reckoning in installments this hour, working through the men who destroyed his commune two at a time with an axe and very little conversation, while the Brotherhood Without Banners offers him something rarer than revenge: a cause to point the violence toward. In King’s Landing, Cersei answers the Faith Militant’s growing power with the only argument she trusts, sending the Mountain to remove a septon’s head in front of witnesses, and Tommen — horrified, and finally decisive about something — abolishes trial by combat altogether, quietly and permanently taking away his mother’s last legal escape hatch from the charges waiting for her.",
      "At Riverrun, Jaime solves the siege the way he solves most things now, with a threat instead of a battle — releasing Edmure Tully to reclaim his own castle bloodlessly, while the Blackfish dies offstage, sword in hand, exactly as stubborn in death as he was in every scene he was given. And in Braavos, the season’s longest-running mystery finally resolves in a dark cellar: the Waif hunts a supposedly blind, supposedly broken girl through the House of Black and White’s tunnels, only to discover — far too late — that Arya spent her blindness training for precisely this. A girl is Arya Stark of Winterfell, she tells the man behind the many faces, and this time the House lets her leave rather than argue the point.",
    ],
  },
  "episode:6-9": {
    paras: [
      "Meereen resolves first, almost as a formality: Daenerys’s three dragons burn the Masters’ fleet to the waterline in a matter of minutes, ending a siege that has dragged across two seasons in an afternoon, and Yara and Theon arrive to offer her a hundred ships in exchange for an independent Iron Islands — a deal struck between two queens who recognize, in each other, the same appetite for something better than what they were handed. It is a tidy, satisfying resolution deliberately front-loaded so the hour’s real business, six thousand miles away, can have the whole rest of its runtime.",
      "That business is Ramsay Bolton’s trap at Winterfell, and the episode is unsparing about what it costs to fall for one: Rickon Stark, freed and told to run in a straight line, is shot down twenty yards from his brother in a game designed purely to bait Jon into a reckless charge — and it works. What follows is the show’s most physically punishing sequence, a shield wall closing in on itself until Jon Snow is buried alive beneath his own men, clawing for air in a mass of the dying, saved from suffocation by nothing more than the accident of the pile’s geometry. It is battle filmed as claustrophobia rather than spectacle, and it is deliberately, almost unbearably close to Jon’s death — the show daring the audience to believe the resurrection might not stick after all.",
      "The rescue, when it comes, arrives on two fronts the show has been quietly setting up for an episode Jon himself didn’t ask for: Sansa’s gamble on Littlefinger’s Vale knights pays off in a cavalry charge that breaks the encirclement, and Wun Wun the giant dies taking Winterfell’s gate down with his bare hands. Sansa’s closing act — feeding Ramsay Bolton to the hounds he starved and adored — plays less as cruelty than as a verdict rendered by the one person with full standing to render it, and the show holds on her small, terrible smile rather than the violence itself. Battle of the Bastards earns its reputation less for scale than for precision: every death in it, named and unnamed, is a direct consequence of a specific choice someone made, which is rarer in this genre than it should be.",
    ],
  },
  "episode:6-10": {
    paras: [
      "Cersei Lannister’s response to a trial she cannot win by any legal means is the season’s — arguably the series’ — most devastating single act: the Great Sept of Baelor, packed with the Faith, the Tyrells, and every enemy who came to watch her humiliated, goes up in a green conflagration of wildfire she has been quietly stockpiling since Tyrion first found it years earlier. The sequence is a horror set piece disguised as a coronation, methodical about who dies and in what order — Margaery, Loras, Mace Tyrell, the High Sparrow himself mid-sermon — and its aftermath is worse: Tommen, the one Baratheon child gentle enough to survive his family, steps quietly from a window rather than live in the wreckage his mother made of everything he loved.",
      "Elsewhere the season settles its remaining debts with the same finality. At the Twins, Arya Stark serves Walder Frey a pie made of his own sons before opening his throat — a promise kept from two seasons back, delivered with a flourish the show has clearly been saving. In Winterfell’s hall, the North proclaims Jon Snow King in the North by acclaim, an old ritual repeating itself on a new Stark almost despite him. And beneath the Tower of Joy, Bran’s visions finally complete themselves: a dying Lyanna Stark, a promise extracted, a baby renamed and hidden in plain sight as a bastard — the show confirming, with no fanfare beyond a single quiet shot, the parentage the books have been arguing about for twenty years.",
      "The finale closes by resetting every board on the map at once. Cersei, having destroyed the one institution powerful enough to check her, takes the Iron Throne over the ashes of everyone she loved and everyone who opposed her, sitting alone in a hall built for a family now reduced to her. Daenerys, her queenly apprenticeship in Meereen finally behind her, names Tyrion her Hand and turns her armada west at last, three seasons of preparation collapsing into a single shot of sails filling with wind. The Winds of Winter is a finale that behaves like a culmination and a beginning simultaneously — it spends five years of accumulated plot in ninety minutes and somehow leaves the board more dangerous than it found it, which is the mark of a show that has finally stopped setting pieces down gently.",
    ],
  },

  // ==================== SEASON SEVEN ====================
  "episode:7-1": {
    paras: [
      "The premiere opens on an act of housekeeping the previous finale promised and delivers with real relish: Arya Stark, wearing Walder Frey’s own face, toasts the assembled men of House Frey and watches them drink poison meant, in spirit if not letter, for every guest who ever trusted that family’s hospitality — winter came for House Frey, she tells the one woman she spares, and the show lets the line do a season and a half of narrative cleanup in under five minutes. At Winterfell, the new King in the North discovers that ruling is mostly disagreement: Sansa argues for punishing the children of houses that turned against the Starks, Jon refuses on the same principle his father died defending, and Littlefinger watches every private argument from the doorway, cataloguing which sister to work on next.",
      "The hour’s real business, though, is arrival. Euron Greyjoy sails into King’s Landing offering Cersei his fleet and a vague, ominous promise of a gift worth more than ships, while across the narrow sea Daenerys Targaryen finally sets foot on Westerosi soil for the first time in her life, walking the halls of Dragonstone past maps and thrones her family abandoned a hundred and fifty years earlier. Shall we begin, she says to an empty room, and the show underplays the moment on purpose — no crowd, no cheering, just a woman alone in an ancestral home she has never actually lived in, opening the final movement of the war.",
    ],
  },
  "episode:7-2": {
    paras: [
      "Dany’s Dragonstone war council splits her invasion three ways at once — Dorne and Highgarden to squeeze King’s Landing’s supply lines, Grey Worm’s Unsullied to take Casterly Rock — and Olenna Tyrell, characteristically, tells her the plan is too clever by half: be a dragon, not a sheep. It is advice the season will spend the rest of its run proving painfully correct. In a locked cell at the Citadel, Samwell Tarly risks his own imprisonment to cut greyscale from Jorah Mormont’s arm with a blade and sheer nerve, a small act of mercy that will matter more, later, than either man can know yet.",
      "Arya, riding toward King’s Landing and her list, turns north instead at a crossroads — toward Winterfell, toward the family she has spent six seasons assuming was gone — and meets Nymeria, her own direwolf, grown huge and wild in the years since she drove her off to save her life. That’s not you anymore, Arya tells her, and lets her go, choosing home over vengeance in the same breath, and the scene plays as a small mercy toward herself as much as toward the wolf. At sea, Euron’s fleet ambushes Yara and Theon’s in the dark: two of the Sand Snakes are killed outright, Ellaria and Yara are taken captive, and Theon — frozen by the same paralysis that has haunted him since the Dreadfort — jumps overboard rather than fight, a failure the show is careful not to excuse even as it understands exactly where it comes from.",
    ],
  },
  "episode:7-3": {
    paras: [
      "Ice finally meets fire in a room at Dragonstone, and the meeting is a stalemate dressed up as diplomacy: Jon Snow will not bend the knee to a queen he has just met, no matter how good her claim or how badly the North needs her dragons, and Daenerys will not simply hand a stranger the one thing every claimant in Westeros has fought and died for. He leaves with dragonglass and nothing resolved, which the show treats as its own kind of progress — two people learning to trust each other in the only currency either has to spare. In King’s Landing, Euron parades Ellaria and Tyene Sand through the streets as trophies, and Cersei repays the Sand Snakes’ murder of Myrcella with a slow, exact cruelty of her own devising, poisoning Tyene with the same kiss that killed her daughter while forcing Ellaria to watch, chained, unable to look away.",
      "The season’s military optimism curdles fast: the Unsullied take Casterly Rock only to find it strategically worthless, the Lannister army long since marched elsewhere, and while Grey Worm’s men celebrate an empty victory, Jaime Lannister’s forces are busy taking Highgarden, the Tyrell breadbasket Dany actually needed. Olenna Tyrell, cornered and doomed either way, drinks Jaime’s offer of a painless poison and spends her very last breath handing him one more piece of information than he wanted — the confession that she, not Tyrion, murdered Joffrey — a final thorn planted with the same dry, unhurried relish she has brought to every scene the show has given her.",
    ],
  },
  "episode:7-4": {
    paras: [
      "Winterfell gets its warmest hour of the entire final stretch before the war swallows it whole. Arya Stark comes home at last, to a family she assumed scattered or dead, and the reunion with Bran plays quiet and strange — he is not quite the brother she remembers — while her sparring match with Brienne of Tarth turns into the season’s single lightest scene, two of the show’s most formidable women testing each other to a smiling draw. In the same hall, Bran hands Arya the Valyrian steel dagger that was once sent to kill him, and delivers, almost as an aside, the line that has quietly organized six seasons of scheming: chaos is a ladder — Littlefinger’s own words, recited back at him by a boy who now sees everything.",
      "Then the hour turns south and becomes something else entirely. Daenerys, tired of losing a clever war on paper, decides to fight an ugly one in person: she and the Dothraki fall on the Lannister supply train returning from Highgarden, and the resulting Loot Train Attack is the show’s first full demonstration of what a dragon actually does to an army with no answer for one — screaming horses, men on fire mid-stride, siege wagons flattened like kindling. It is spectacle, but the show refuses to let it stay only spectacle; the camera keeps finding individual soldiers, burning or trampled, men who signed up for a war and got an extinction event instead.",
      "At the center of the carnage is Jaime Lannister, watching his army annihilated and doing the one reckless, almost suicidal thing his whole life has trained him against: charging a dragon alone with a spear, aiming for the woman on its back rather than the beast itself. Bronn’s scorpion bolt saves him from Drogon’s fire at the very last second, and the two of them go under the lake’s surface together, saved from immolation only to nearly drown instead — a soldier’s bargain, traded across an episode that spends its first half establishing a family reunited and its second half demonstrating, in the bluntest possible terms, exactly how outmatched the family Arya just came home to still is.",
    ],
  },
  "episode:7-5": {
    paras: [
      "Daenerys, having just proven what her dragons can do, offers the loot train’s survivors a simple choice — kneel or burn — and Randyll and Dickon Tarly refuse together, father and son choosing death over a foreign queen’s claim, and Drogon does not hesitate twice. It is one of the show’s starker demonstrations that Dany’s mercy has limits, and the hour treats the burning with a coldness that feels deliberate: this is not Hardhome’s horror or the loot train’s chaos, but a queen making an example, calmly, in front of witnesses she wants to remember it.",
      "The episode’s real momentum, though, is toward the Wall and beyond it: Jorah returns cured of greyscale, Gendry rows himself back into the story after four seasons at an oar, and Jon Snow proposes the single most reckless plan the show has offered a protagonist — walk beyond the Wall, capture a wight, and drag proof of the dead back to two skeptical queens who otherwise have no reason to stop fighting each other. At Oldtown, Gilly reads past a marriage annulment buried in a maester’s footnote — Rhaegar Targaryen, unmarried to Elia in the eyes of the septon who performed a second ceremony — and no one at the table, deep in an argument about family history, actually hears what she just said. The suicide squad that walks out of Eastwatch’s tunnel at the hour’s end — a king, a smuggler, a hound, an outlaw brotherhood, and a bastard blacksmith — is, on paper, the worst-planned mission in the show’s history, and everyone involved knows it.",
    ],
  },
  "episode:7-6": {
    paras: [
      "The expedition beyond the Wall gets exactly what it came for almost immediately — a single wight, separated from its pack and dragged down alive — and almost nothing else goes to plan from there. The hour is a study in a war party that has badly underestimated its own visibility: the noise of the capture draws the very army they meant to prove exists, and Jon’s small company finds itself stranded on a rock in the middle of a frozen lake, surrounded on every side by more of the dead than any living person has ever seen assembled in one place.",
      "What follows is the show testing its own internal logic in real time — a standoff where every option is bad and the clock is measured in ice thickness rather than minutes. Gendry’s desperate run back to Eastwatch to send a raven, and the raven’s impossible speed reaching Dragonstone in time for three dragons to arrive, asks the audience to accept a compression of distance the show has generally been careful about — a real strain on the story’s own geography that critics and fans alike flagged hard, even as the rescue itself, dragonfire scattering the dead across a frozen lake at night, remains one of the show’s most purely thrilling images.",
      "The rescue costs exactly what a rescue against an army with a champion should cost: the Night King, unbothered by dragonfire in a way nothing in the story has been before, hurls an ice spear and brings Viserion down out of the sky — the first dragon lost since Dany hatched them, killed not in battle but almost contemptuously, a demonstration rather than a fight. Jon himself is saved only by a half-dead Benjen Stark’s last ride, sacrificing the one horse available so his nephew can escape. And the coda, weeks later, is the season’s bleakest image: chains dragging a drowned dragon’s corpse up out of the lake, and blue eyes opening where none should be — the Wall’s oldest protection about to be answered by a weapon built specifically to end it.",
    ],
  },
  "episode:7-7": {
    paras: [
      "The dragonpit summit is the season finale’s first great set piece and its strangest: two queens, a king who won’t call himself one, and the Lannister siblings who ruined each other, gathered under the ruins of the throne’s old dragon-keeping cages to be persuaded by a screaming, snarling wight that the real war has nothing to do with any of their claims. Euron Greyjoy provides the comic menace, Cersei provides the reasonable-sounding lie — an armistice, her armies pledged against the dead — and Tyrion, brokering the whole affair, believes her exactly as much as the show wants the audience to, which is to say not at all.",
      "The lie unravels fastest for the person closest to it: Jaime Lannister, learning in private that Cersei intends to keep her armies in King’s Landing rather than march them north, rides away from her — and from the capital, and from every year of loyalty the show has spent complicating — as the first snow of the coming winter starts falling on the city behind him. At Winterfell, Sansa and Arya spring the trap Littlefinger spent the whole series building, except in reverse: Sansa reads the charges, Arya holds the Valyrian dagger that was once meant for Bran, and the man who started the entire war with a lie about a knife and a dwarf finally runs out of words that work on the people in front of him.",
      "Two revelations land in the same hour, one quiet and one enormous. In a rocking ship’s cabin, Jon and Daenerys, ignorant of the parentage a maester and a broken boy have just confirmed at Winterfell, become lovers precisely as Bran and Sam finish piecing together that Jon is not a bastard at all but Aegon Targaryen, the trueborn son of Rhaegar and Lyanna — a secret the show plants with excruciating, deliberate irony. And at Eastwatch-by-the-Sea, the Wall’s oldest defense fails in seconds: a blue-eyed, undead Viserion breathes fire where no dragon ever has, and eight thousand years of ice comes down into the sea in a single shot, ending the season on the exact image its every episode has been building toward — the wall between stories, finally, gone.",
    ],
  },
  // ==================== SEASON EIGHT ====================
  "episode:8-1": {
    paras: [
      "Daenerys and Jon ride into a Winterfell that does not cheer for them, and the season’s opening hour is honest about the cost of the alliance the last one ended on: the North sees a foreign queen, foreign soldiers, and two dragons overhead, and does the arithmetic on what an army that size actually eats. Sam, arriving from Oldtown with the season’s cruelest piece of news, learns that his father and brother were burned for refusing to kneel — burned, in fact, by the very queen now standing in his family’s ancestral hall — and then, in the crypts, by candlelight, gives Jon the truth about his parentage in the gentlest, most devastating way the show has delivered exposition all series.",
      "Jaime Lannister arrives alone, having ridden the length of the continent on the promise he made and broke and is now trying to keep for real, and finds Bran Stark waiting in the courtyard with a stare that needs no words to remind him exactly what he did to that boy years and one bad war ago. Farther north, at Last Hearth, the advance scouts of Jon’s army find the young Lord Umber pinned to a wall in a spiral of severed limbs — not a battle, but a signature, the Night King’s calling card left for the living to interpret exactly as intended: he is coming, and he is already south of where anyone thought he could be.",
    ],
  },
  "episode:8-2": {
    paras: [
      "Jaime Lannister’s reception at Winterfell is the trial the show has been building toward since he pushed a boy out a window in its very first hour, and it resolves not through his own testimony but through Brienne of Tarth’s — her word, earned across six seasons of watching him try to become someone worth vouching for, outweighs two queens’ inherited grudges and buys him a place fighting for the family he once helped destroy. The plan for the battle to come is set with grim simplicity: Bran will wait in the godswood as bait for the army that wants him specifically, while everyone else holds the walls around him.",
      "What the hour actually wants to give its characters, though, is one last ordinary night before an extraordinary one. There is wine, and Podrick’s surprisingly lovely singing, and small confessions traded around a fire by people who may not get another chance to make them — and in its quietest, most purely joyful scene, Jaime Lannister does the one knighting that has ever meant anything to him, kneeling to raise Brienne of Tarth to a rank the world has denied her for no reason beyond her sex. In the crypts, Jon finally tells Daenerys the truth Sam gave him — his real name, his better claim — and watches, in real time, a woman he loves start doing the same arithmetic everyone else in the castle has already finished. The horns sound three times before dawn. The bait is set; the night that follows is the one the whole series has been walking toward.",
    ],
  },
  "episode:8-3": {
    paras: [
      "The Battle of Winterfell begins with a tactical gamble that turns almost immediately into the season’s bleakest image: the Dothraki charge out with flaming arakhs held high, a wall of fire meant to announce Westerosi steel to an enemy that has never faced cavalry — and the flames simply go out, one by one, swallowed by darkness and distance, until there is nothing left on the horizon but silence where a charge used to be. It is a battle the show chooses to stage mostly as an absence of light rather than a spectacle of it, an aesthetic choice that drew real argument from viewers straining to follow the action on smaller screens — but the disorientation is, in its way, the entire point: nobody at Winterfell can see this enemy coming until it is already among them.",
      "What follows is siege warfare stripped down to its most primal terms — a trench meant to hold the dead back lit at the last possible second by Melisandre, buying the living minutes rather than hours, while the castle’s walls are overrun by a tide that does not tire, does not negotiate, and does not stop coming. The hour moves between theaters with a controlled dread: the crypts, meant to be the safest place in Winterfell, prove instead to be exactly where the dead are made, as the corpses interred there for centuries rise from within the one shelter everyone assumed was solid ground. Across the battlements and the yard, familiar faces fall in ones and twos, each death staged with just enough space to register before the next wave arrives.",
      "The entire war for the living funnels, in the end, down to a single tree in a single godswood. Theon Greyjoy, spending the last of a life defined by betrayal and half-measures, dies charging the Night King alone to buy Bran a few more seconds — a Stark death in every way that matters, delivered by a Greyjoy who spent nine seasons trying to earn the right to it. And when the Night King reaches the heart tree unopposed, certain of his victory, Arya Stark comes out of the dark behind him with the dagger her brother once gave her, catching the blade tossed hand to hand in a single motion that ends eight seasons of prophecy, dread, and slow-motion mythology in under three seconds. The Long Night resolves the show’s oldest, most cosmic threat a full three episodes before the finale — a structural choice as audacious and as debated as anything the series ever attempted, gambling that the human war left standing would prove the more interesting one to finish.",
    ],
  },
  "episode:8-4": {
    paras: [
      "Winterfell buries its dead and then, almost indecently fast, gets back to arguing about politics — the victory feast curdles within minutes, every toast a thin disguise for the succession question nobody has actually resolved: whose army, whose dragons, whose throne, now that the thing they were all supposedly fighting for is settled. Jon tells his sisters the truth about his birth beneath the heart tree that just witnessed a war fought partly to protect him, and Sansa, unable to hold the secret the way Jon asked her to, passes it to Tyrion within the hour — the first domino in a chain the season will spend its remaining episodes toppling.",
      "The war against the living reasserts itself with brutal, deliberate cruelty. Euron Greyjoy’s hidden fleet ambushes Daenerys’s ships off Dragonstone with scorpion bolts built specifically to kill dragons, and Rhaegal — wounded again and again before anyone below decks even understands what is happening — falls burning into the sea, the second of Dany’s children lost to a weapon designed in direct response to what she is. On the walls of King’s Landing, Cersei’s answer to the alliance’s ultimatum is theater staged for maximum cruelty: Missandei of Naath, born a slave and freed by the woman she serves, is beheaded in chains in full view of the queen who loves her, her final word not a plea but a command — Dracarys — a woman spending her last breath handing her queen permission for exactly the fury the finale will not let go unanswered.",
    ],
  },
  "episode:8-5": {
    paras: [
      "The Bells opens with the war’s last strategic obstacles cleared away almost contemptuously fast: Varys, having spent the entire series choosing the realm over any single ruler, makes that choice a final time against the queen he has served and is burned for treason before the episode is a third over — a quiet, procedural execution for a character who spent eight seasons working in shadows and dies, fittingly, without much spectacle at all. What follows is worse for being so brief: the Iron Fleet, the scorpions mounted along the walls, the Golden Company marching in gold and scarlet — every material advantage Cersei spent the season assembling burns or breaks in under an hour, and Daenerys, having lost a dragon, a best friend, and an army of allies in quick succession over the preceding episodes, finds herself standing over an undefended city with absolutely nothing left to stop her.",
      "And then the bells ring — the ancient signal of surrender, the sound the whole war has supposedly been fighting to hear — and Daenerys Targaryen flies past them anyway. It is the single most contested creative decision the show ever made, and the episode is unambiguous about staging it as a choice rather than an accident: a woman who has spent the series absorbing one betrayal after another, watching every gentler instinct cost her something irreplaceable, finally deciding that fear, not love, is the only currency this city has ever actually respected. Whether the turn is the tragic, inevitable payoff of six seasons of counselors teaching her that lesson, or a hairpin swerve the writing hadn’t fully earned in the time it gave itself, remains the single most argued question in the show’s history — and the episode itself does not flinch from either reading.",
      "What burns is not soldiers but a city, and the hour spends its second half making sure the audience cannot mistake the difference: smallfolk fleeing through streets that are burning regardless of which side they were on, a mother and child among the ash. Underneath the Red Keep, Jaime and Cersei Lannister die together in each other’s arms as the ceiling comes down — the twins who started the whole series with an act of violence toward a child, ending it holding onto nothing but each other. Above the rubble, the Hound gives Arya Stark the last mercy he has to offer — go home, girl — and sends her away from the vengeance he has spent his life pursuing, before dragging his brother, the Mountain, into the flames with him in the closest thing the show ever staged to a private reckoning between two men the story otherwise had no more use for. Arya crawls out of the ash on a pale horse, alive by inches, having come to King’s Landing for one name on a list and leaving having tried, in the end, to save strangers instead.",
    ],
  },
  "episode:8-6": {
    paras: [
      "Ash falls over King’s Landing like a second, worse winter, and the finale opens with Daenerys addressing her army amid the ruins of the city she just burned — liberation rhetoric delivered over rubble and corpses, a speech that asks her soldiers, and by extension the audience, to keep believing the cause justifies the cost. Tyrion Lannister, finding his own brother’s body in the wreckage of the Red Keep, resigns the Hand’s pin he has worn through four monarchs and is arrested for treason, the season’s last major character finally admitting, out loud, that his cleverness never actually steered the woman he served toward anything resembling mercy.",
      "What follows is the quietest, least ceremonial regicide the show has ever staged: Jon Snow, love and duty pulling in opposite directions for the last time, walks into the ruined throne room, tells Daenerys what she has become, and kisses her before putting a knife into the woman he loves and the queen he cannot, in conscience, kneel to. Drogon’s response is the episode’s one moment of pure, wordless imagery doing more work than any line of dialogue could — the dragon melts the Iron Throne itself rather than the man who killed his mother, an act of grief and judgment aimed squarely at the object three hundred years of Targaryen and pretender ambition were built around, before lifting her body and flying east, out of the story, out of the reach of anyone who might try to use even her corpse as a symbol.",
      "The lords of Westeros, gathered to decide what comes next, settle on the least likely candidate in the room — Bran the Broken, chosen not for lineage or ambition but for the simple, oddly persuasive fact that he wants nothing the throne can give him, with Tyrion talked back into service as his Hand for one monarch more. Sansa Stark, refusing to fold the North back into a kingdom that has never once protected it, wins her people’s independence in the same council where Bran wins the rest of the continent. Arya sails west of the map entirely, toward whatever exists past every chart Westeros has ever drawn, and Jon Snow — pardoned into exile rather than executed, too dangerous to keep and too beloved to kill — rides back out through the gates of Castle Black with the free folk who never cared what his name was, closing the series precisely where its very first scene began: at the Wall, and beyond it, with people the rest of the realm has always preferred to forget.",
    ],
  },
});
