/* GoT wiki long-form archive — the great houses & orders. Original prose. */
Object.assign(WIKI_EXTRA, {

  // ================= the great houses =================
  "house:stark": {
    paras: [
      "The Starks trace themselves back past written record to Bran the Builder in the Age of Heroes, and past him again into legend the Starks themselves no longer bother to defend or deny. What is certain is older than the Andals, older than the Seven: eight thousand winters of Kings of Winter ruling from Winterfell, a line that fought giants and the children of the forest to a standstill and then, uniquely among the First Men, made peace instead of war. That peace is why the Starks alone kept the old gods when the Andals came south with their new one, and why a heart tree still weeps in Winterfell's godswood while every other great house prays to statues.",
      "Winterfell itself explains the family better than any genealogy. Built over hot springs that run warm water through its walls, it lets a Stark host a hall in furs while snow buries the yard outside — a castle that turned the North's cruelty into comfort rather than pretending to escape it. The crypts beneath hold every King of Winter in stone, swords laid over their laps to keep old vengeance sleeping, and it is down among those tombs, unremarked for a generation, that the story keeps its best-hidden secret. From Winterfell the Starks hold the largest of the Seven Kingdoms — bigger than the other six combined, mostly empty, entirely theirs — through bannermen bound by a harder currency than affection: the Umbers, Karstarks, Mormonts and Boltons obey because the alternative is worse than obedience.",
      "What holds across every generation is a specific, undecorated code. A Stark passes sentence himself and swings the sword himself, because a lord who cannot look his victim in the eye has no business owning the axe. Guests are fed and safe under a Stark roof regardless of the grudge outside it. None of this is boasted about — the southern houses keep lion and stag and rose for their sigils and roar accordingly, while the Starks fly a direwolf on plain ice-white, an animal that hunts in silence and dies for its pack without asking permission first. Words of House Stark are not a promise of glory. Winter Is Coming is a weather report that happens to double as a warning: prepare now, because charm will not save you later.",
      "Robert's Rebellion is fought in the Starks' name before it is fought for anyone's throne — Rickard and Brandon Stark burned and strangled in King's Landing for a son's supposed insult, and Eddard Stark rides south a boy and comes home a lord with a war behind him and a secret he will keep for the rest of his life. That secret, and the honor that makes him keep it, cost him everything a generation later: the sept steps, the false confession, the axe he refused to swing on his own daughters' behalf. What follows is close to extermination — Robb and Catelyn butchered at a wedding meant to buy peace, Winterfell burned twice over by men wearing borrowed names, the pack scattered to the corners of the map as prisoners, wards, fugitives and outlaws with nothing left of home but a memory.",
      "The rebuilding is the part the family's whole history had been rehearsing for. Every child who survives comes back changed and useful in a way the North needs precisely because they left — a queen's confidante, an assassin, a seer who remembers everything, a commander who has fought both living armies and dead ones. Winterfell is retaken at a bastard's cost and a sister's arithmetic, held through the Long Night in the same godswood where its secrets were buried, and by the story's end the North's independence is bought back by the very family whose extinction the war had seemed determined to finish. Eight thousand years is not a boast the Starks make. It is the answer to the question of why they were still there to win.",
    ],
    vs: [
      "The tellings part ways hardest at the finish. The show closes the Stark account neatly and fast — Sansa crowned an independent Queen in the North within a single season of the war's end, Bran installed on the Iron Throne itself, Jon exiled north to the Watch and beyond it to the free folk, every thread visibly tied. The books, still marching through the War of the Five Kings' long aftermath as of the last published volume, have not caught up to any of it: the Others remain largely unengaged, Jon's fate hangs on an unresolved cliffhanger of his own, Arya's road home is unwritten, and an entire subplot the show skipped — a captive steward's daughter passed off as Arya Stark to the Boltons, and Catelyn's grim second life as the vengeful, wordless Lady Stoneheart — still waits in the wings of a story that has not decided how, or whether, to resolve them.",
    ],
  },

  "house:lannister": {
    paras: [
      "Every great house has an origin myth; the Lannisters' happens to be a swindle. Lann the Clever is said to have talked the Casterlys out of their own Rock by cunning rather than conquest — the founding con of a house that would spend three thousand years turning cleverness and gold into the only currency that outlasts armies. By the story's own time the family motto everyone actually uses isn't Hear Me Roar, stamped on their banners beside a golden lion, but a saying with real teeth: a Lannister always pays his debts. It is offered as a boast and lands as a threat, and the house spends the entire tale making sure both readings stay true.",
      "The mines beneath Casterly Rock make the Lannisters the wealthiest house in Westeros, and Tywin Lannister spent his life converting that wealth into something closer to gravity — a pull every other house eventually orbits, whether they mean to or not. He inherited a laughingstock and rebuilt it by annihilating the Reynes and Tarbecks so completely that the realm still sings about it a generation later, then spent two decades as Hand of the King propping up a mad monarch's reign with unpaid, unloved competence. His children were raised less as family than as instruments — Jaime the sword, Cersei the crown, Tyrion the debt he refused to acknowledge — and the house's later triumphs and catastrophes both trace back to a father who mistook obedience for love and never noticed the difference.",
      "No house in the story wins more battles and keeps less. The Red Wedding ends a war and poisons a name for a generation; the Blackwater saves a capital for a king who does not survive his own wedding feast; the wildfire that destroys the Great Sept crowns a queen over a court that no longer exists to be ruled. Every Lannister victory in this tale is a loan against a future the family keeps forgetting it will have to repay — and the gold in the Rock's mines runs dry the very season the debts come due, which is either the story's cruelest joke or its most honest piece of accounting.",
      "The children carry three different answers to the same inheritance. Jaime spends the tale trying to become a man his sworn vows can respect rather than the Kingslayer his reputation made him; Cersei spends it proving that a mind as sharp as her father's, denied a legitimate outlet by an accident of birth, will build its own throne out of whatever is lying around — fire, spite, and a crown too heavy for the head that finally wears it; Tyrion, denied his family's love from the hour his mother died bearing him, becomes the one Lannister capable of genuine loyalty to someone outside his own name, which both saves him and exiles him from it. By the war's end, of Tywin's three gilded children, two die beneath the ruin of the house that made them and one survives to spend his cleverness in service of somebody else's crown — the family motto, settled at last, and not in the family's favor.",
      "The lion sigil was never subtle, and neither was the house it represented: the Lannisters do not hide their appetite for power behind modesty the way the Starks do, or behind courtesy the way the Tyrells do. They simply state the price and expect the realm to pay it. That the realm, in the end, is the one collecting is the whole tragedy compressed into a single coin.",
    ],
    vs: [
      "Both tellings agree on the ledger, but the books itemize the receipts the show never had time to show. Tywin's brutal handling of Tyrion's first marriage — the true fate of Tysha, the crofter's daughter Tyrion loved and lost, and the lie Tywin told him about her for a lifetime — is a wound the novels dwell in at length and the show largely elides, which softens exactly the detail that makes Tyrion's final act against his father land as inevitable rather than sudden. The books also give Cersei her own point-of-view chapters from partway through the saga, an interior of prophecy, paranoia and self-flattery no camera could fully replicate; the show, needing a coherent final antagonist, streamlines her into something colder and more competent than the woman on the page, who is at least as often her own worst enemy as anyone else's.",
    ],
  },

  "house:baratheon": {
    paras: [
      "The Baratheons are the youngest of the great houses and the proudest of it, which tells you most of what you need to know about them. Orys Baratheon — rumored, never confirmed, to be a Targaryen king's bastard half-brother — took Storm's End from the last Storm King in Aegon's conquest, killed him in single combat, and married his daughter to knit the old Durrandon blood into the new arrangement. He kept the fallen house's words for his own, Ours Is the Fury, and the crowned black stag on gold has stood for exactly that ever since: a house that answers challenge with temper, and rarely loses the argument by half-measures.",
      "Storm's End itself is the house's whole character built in stone — a fortress that has never fallen to siege or storm in a thousand years of both, curtain walls a hundred feet thick weathering the worst the Narrow Sea can throw at them. It bred lords who treated stubbornness as a virtue rather than a flaw, and nowhere is that clearer than in the rebellion that put a Baratheon on the Iron Throne for the first time: Robert Baratheon, fostered at the Eyrie alongside Eddard Stark and Jon Arryn, went to war less for a crown than for a grievance — the abduction, as he saw it, of the woman he loved — and turned a doomed uprising into a dynasty by killing Rhaegar Targaryen in single combat at the Trident. He never much liked the throne he won; he liked winning it.",
      "The house's rot set in exactly where its unity was thinnest: three brothers who agreed on nothing but their own right to rule. Robert drank and hunted and mortgaged the realm's finances rather than govern it; Stannis, the middle son, treated duty as a debt owed regardless of cost, correct in law and beloved by almost no one, not even his own family; Renly, youngest and most charming, built a crown out of popularity and an army he never had to earn the hard way. When Robert died leaving no legitimate heir — his queen's children were never his to begin with — the house did not descend into succession, it fractured into civil war, brother arrayed against brother's memory as much as against each other.",
      "None of the three lines that mattered survived to inherit what Robert won. Stannis burned his own daughter on a pyre for a victory that never came and died with his cause; Renly fell to a horror out of the fire and the shadows before ever striking a blow; Robert's throne passed to children who were never Baratheons at all, born of his queen and her brother, and the crown he had bled for a generation earlier ended up worn by exactly the dynasty his rebellion had been fought to end. By the war's final reckoning the direct line is extinguished entirely — a bastard son legitimized too late to matter, a scattering of baseborn children with no claim the realm will honor, and a storm-battered seat with no storm lord left to hold it.",
    ],
    vs: [
      "Stannis's ending is the single largest outstanding question the published books have left hanging. The show resolves him with total finality — his army broken outside Winterfell, cut down by Brienne of Tarth in the snow with Renly's murder still between them. George R. R. Martin's own novels stop his story mid-battle, wounded and surrounded, in a chapter deliberately titled to leave the outcome ambiguous; readers have argued for a decade over whether he lives, and the author has confirmed the ambiguity was intentional. It is the rare case where the show did not adapt an ending so much as write one the books have pointedly declined to supply.",
    ],
  },

  "house:targaryen": {
    paras: [
      "Every other great house in Westeros is native to it; the Targaryens are not, and the whole of their history is the story of that difference never quite resolving. Dragonlords of Valyria, they moved their seat to lonely Dragonstone a century before the Doom swallowed the rest of their homeland whole — a stroke of caution or prophecy, depending which Targaryen you ask, that left them the last dragonriders alive when everything else Valyrian became ash and legend. Aegon the Conqueror crossed the narrow sea with two sisters, three dragons, and an army too small to matter against six kingdoms that dwarfed it — and won anyway, because none of those kingdoms had ever had to fight something that could burn an army from the sky. Fire and Blood is not phrased as a boast so much as a description of the terms.",
      "What three centuries of Targaryen rule actually produced was less a golden age than an unbroken coin flip between brilliance and ruin, landing differently every generation. Aegon the Conqueror unified a continent by the sword and then, notably, stopped conquering when Dorne's deserts and spears made the cost too high — restraint being the one Targaryen habit that never seemed to run in the blood as strongly as its opposite. Jaehaerys the Old ruled fifty-five years of the closest thing Westeros ever had to lasting peace; his descendants set the bar for its opposite, burning rivals alive for imagined crimes, hearing prophecy in a screaming wind, and mistaking their own certainty for their ancestors' fire. The valyrian steel and stone eggs the family kept as heirlooms were not decoration. They were a reminder, generation after generation, of a power the family had once earned and only sometimes still deserved.",
      "The dragons died out first, starved of purpose and inbreeding both, and the dynasty followed less than two centuries later. Robert Baratheon's rebellion did not need to defeat an empire so much as topple what the empire had already hollowed itself into — a mad king muttering about wildfire, a golden-haired heir the realm no longer trusted, and a war that ended at the Trident with a war hammer and a chest full of red rubies. What was left of House Targaryen afterward fit inside a single hunted family: a boy who called himself a beggar king, a girl not yet born, and three fossilized dragon eggs that every sane person in Westeros assumed were merely rocks.",
      "That the tale's two central figures both turn out to be Targaryens — one raised as the last exile, one raised believing himself no Targaryen at all — is the family's oldest joke landing one final time. Both are shaped by exile and both are shaped by fire, and where the coin lands for each of them says less about their blood than about what they choose to do with the same inheritance. The three-headed dragon on black was always a family crest built for plurality — three heads, one banner — and by the story's end it has been carried, worn, hatched from and finally set down by more claimants than any single Targaryen king ever ruled alone.",
    ],
    vs: [
      "The show compresses three centuries of Targaryen history into implication and dialogue — Robert's Rebellion, the Mad King's burnings, even Aegon's conquest are told rather than shown, background the audience is trusted to infer. Fire & Blood, Martin's standalone Targaryen history, gives the dynasty's earlier centuries — the Dance of the Dragons, the Doom's long shadow, the slow extinction of the dragons themselves — a depth and specificity the main saga has not yet caught up to on the page, effectively meaning the books now contain more documented Targaryen history than either telling has dramatized in full. The house's living story, meanwhile, remains genuinely unfinished in print: Daenerys's arc in the published novels has not yet reached Westeros at all, let alone King's Landing, leaving the show's ending — however final it looked on screen — unconfirmed by the only author with the authority to write it.",
    ],
  },

  "house:tully": {
    paras: [
      "Where the Starks and the Baratheons won their thrones by the sword, the Tullys won theirs by good timing and a well-placed bow. Edmyn Tully was among the very first riverlords to bend the knee when Aegon's dragons crossed the narrow sea, sparing the Trident the slaughter other kingdoms endured for their resistance, and Aegon rewarded the wager by raising the Tullys from mere lords of Riverrun to Lords Paramount over a river country that had never had a single ruling house before. It made them new money by Westerosi standards and permanently suspect to prouder neighbors — the Riverlands' bannermen swear fealty to a family whose whole claim to seniority is a single well-timed act of loyalty, not a thousand years of conquest.",
      "Riverrun sits at the fork of the Tumblestone and the Red Fork, defended less by walls than by geography — a castle that can flood its own approaches at need, in a country with no mountains, deserts or coastline to hide behind. Rivers run through the Riverlands and armies run along rivers, which has made the Tullys' lands the most fought-over ground in Westeros for every war the realm has managed to have, theirs or otherwise. Their answer to a country with no natural defenses was never to build higher walls; it was to marry outward as far and as often as possible, until Tully blood ran through half the great houses of the realm and an attack on any one of them risked becoming, by marriage, a family matter.",
      "That strategy is also the family's motto made policy: Family, Duty, Honor, in that specific order, a hierarchy Hoster Tully enforced on his own children with the same rigor he applied to treaties. Catelyn went north to marry a Stark, Lysa east to marry an Arryn, and both matches bought Riverrun the swords it needed for Robert's Rebellion — a wedding-day alliance that helped end one dynasty and, a generation later, drag the Tullys' own into a war that very nearly finished them. The silver trout on red and blue was built to represent abundance and constancy; it has spent most of the story's timeline representing a family perpetually paying interest on its own marriages.",
      "The Red Wedding is the bill arriving all at once. Catelyn dies at a wedding meant to honor a Tully-brokered peace, in a hall flying colors her own family had vouched for; Riverrun itself changes hands between Freys and Lannisters and Tullys again before the war ends, and the family that built its whole survival strategy on alliance discovers, at the worst possible moment, exactly how little an alliance is worth once the men who swore it are dead. What is left afterward is not extinction but attrition — a castle held by a stubborn old soldier out of pure spite, a reluctant heir doing penance he never earned, and a house that outlives the disaster mostly by being too small and too poor to be worth finishing off.",
    ],
    vs: [
      "The two tellings diverge sharply on how the last defiant Tully leaves the story. The show has Brynden Tully — the Blackfish — die fighting in the halls of Riverrun after its garrison surrenders around him, sword in hand, the ending his whole career seemed to be pointing toward. The published books decline to grant him that closure: when Riverrun's garrison yields, the Blackfish is simply not among the prisoners, having slipped out beneath a water gate and vanished into the riverlands entirely. As of the last published volume he remains unaccounted for — the rare character whose fate the show settled with a death scene the books have pointedly left open.",
    ],
  },

  "house:arryn": {
    paras: [
      "No army has ever taken the Vale of Arryn by force, and House Arryn has spent the better part of a thousand years making sure that record stays intact without having to test it very often. Descended from the Andal kings who first crossed the narrow sea and settled the mountain valley behind the Bloody Gate, the Arryns held their own kingdom for centuries before Aegon's dragons arrived — and when they did arrive, the reigning Arryn queen chose to bend the knee rather than test dragonfire against a mountain pass, a decision that let the family keep its ancient seat, its ancient pride, and its complete lack of practice at losing wars.",
      "The Eyrie itself is less a castle than an argument: a keep built where nothing should be able to reach it, seven thousand feet up a mountain, accessible only by a narrow mule track past waycastles named for what happens to the unwary, or by the Bloody Gate at the valley's mouth, a chokepoint so absolute that a handful of defenders have turned back armies there for centuries. The Eyrie's moon door — a sheer drop from the throne room straight down the mountainside — has functioned as informal Vale justice since before anyone thought to write the custom down, execution and metaphor collapsed into a single hole in the floor. As High as Honor is the house's motto, and the Eyrie is the rare seat in Westeros where that is a literal description as much as a boast.",
      "For most of the story the Vale's great strength doubles as its great absence: mountain and gate that have kept every invader out have also kept the Arryns comfortably apart from every war the rest of Westeros insists on having. Jon Arryn's death as Hand of the King is the spark that lights the whole tale — a quiet, honorable man poisoned for asking the wrong question about a queen's children — but the house he left behind retreats rather than avenges him, as his widow Lysa withdraws the Vale's armies from Robert's Rebellion's sequel entirely and raises her sickly son Robert alone, at altitude, terrified of every window in the castle he will one day rule.",
      "What follows is a slow hostile takeover disguised as a marriage of convenience. A minor lordling once fostered at Riverrun as an act of charity, and never quite forgiven for reaching above his station there, arrives in the Vale as Lysa's new husband and Sweetrobin's new Lord Protector, and inside a single season the ancient, unconquered, isolationist house that never lost a war finds itself effectively run by a man who never won one honestly in his life. The falcon and moon still fly over the Eyrie. Who is actually flying them has become, by the story's midpoint, an open and dangerous question.",
    ],
    vs: [
      "The books extend the Vale's political crisis far past where the show leaves it. Petyr Baelish's scheme runs much longer and much more elaborately on the page — Sansa Stark spends an entire extended stretch of the novels disguised as his baseborn daughter, Alayne Stone, while Baelish maneuvers to marry her to Harry Hardyng, Robert Arryn's own heir presumptive, and a faction of Vale lords called the Lords Declarant begin quietly organizing against him, suspicious of how conveniently Lysa died and how thoroughly a landless outsider now controls their liege lord's upbringing. None of that machinery survives into the show, which resolves the Vale in a single compressed season and sends Sansa home to Winterfell long before the books' equivalent plot has finished — or even fully revealed — itself.",
    ],
  },

  "house:greyjoy": {
    paras: [
      "The Iron Islands worship a different god and keep a different law than the rest of Westeros, and House Greyjoy governs both by right of an origin story that predates even the Andals: the Grey King of legend is said to have slain a sea dragon and ruled the waves wearing its bones as a crown, and every Greyjoy since has understood kingship as something wrested from the sea rather than granted by it. The Drowned God demands drowning and rebirth rather than blessing, ironborn priests intone that what is dead may never die, and the old way of the islands — reaving, raiding, taking wives and wealth at the point of an axe rather than growing or trading for them — survived Aegon's conquest more or less intact, because there was little on the Iron Islands worth a dragon's trouble to burn.",
      "Balon Greyjoy tested that independence directly, twice. His rebellion against the newly crowned Robert Baratheon ended in the kind of defeat the ironborn rarely suffer — the Iron Fleet burned, his sons dead or hostage, his crown surrendered in all but name — and Theon Greyjoy, the surviving son, was carried off to Winterfell as a ward who was also, unmistakably, a prisoner. Balon tried again decades later, this time simply to seize what he could while the rest of the realm tore itself apart in the War of the Five Kings, on the ironborn's oldest working theory of strategy: better to take by iron what you cannot win by gold, especially while everyone else is looking elsewhere.",
      "That second rebellion is where the house's real tragedy plays out, and it plays out inside one man. Theon, raised half a Stark in all but name and never trusted as either Stark or Greyjoy by the people who mattered, seizes Winterfell in his father's name to prove an ironborn loyalty he does not actually feel, loses it just as fast, and pays for the attempt with a captivity and torture that strips away his name entirely before what is left of him — called Reek, taught to answer to nothing else — claws back enough of himself to help the very Stark family he betrayed. It is the bleakest character arc the story tells, and also, against most expectation, one of its genuine redemptions.",
      "What comes after Balon's death is a contest for the driftwood crown as old and violent as the islands themselves — a kingsmoot, the ironborn's ancient method for choosing a king by acclamation rather than inheritance, called and contested between Balon's daughter Yara, who wants alliance and survival, and his brother Euron, a pirate lord returned from voyages no one else survived, who wants conquest and does not much care what it costs the islands to get it. The house's fate splits along that same line by the story's end: a chastened, more modest independence under the family member who wanted to keep her people alive, purchased at the cost of the chaos the other one very nearly cost them everything to unleash.",
    ],
    vs: [
      "Euron Greyjoy is one of the widest gaps between the two tellings. The show's Euron is a chatty, charismatic loose cannon, prone to speeches and court intrigue, who woos Cersei Lannister in King's Landing and dies in single combat with Jaime. Book Euron is something closer to a legend the other characters are afraid to say out loud — mostly offstage, rumored to have sailed past the edges of every map, said to have cut out his own crew's tongues so his plans could never be repeated, wielding a Valyrian steel horn called Dragonbinder that supposedly can bind dragons at the cost of the blower's life. His brother Victarion's entire subplot — a voyage across Slaver's Bay to court Daenerys Targaryen for himself, horn in tow — has no equivalent in the show at all, an entire ironborn storyline the adaptation simply never adapted.",
    ],
  },

  "house:frey": {
    paras: [
      "Six hundred years of controlling the only bridge across the Green Fork of the Trident made House Frey rich in the one way that mattered most in the Riverlands: everyone who wanted to cross the river without swimming it owed the Freys a toll, a favor, or both. It also made them permanently unwelcome at the tables of older blood. The Twins is a castle built explicitly to be a chokepoint rather than a home, twin towers joined by a bridge, and the family that holds it has spent centuries being useful to its neighbors and resented by them in roughly equal measure — new money in a country that never forgets who used to be poor.",
      "Walder Frey ran that inheritance the only way he knew how: by outliving nearly everyone and marrying eight times, accumulating a brood so enormous that no other house in Westeros could match it for sheer numbers, and holding every marriage as a debt the other party would eventually be made to pay. His bannermen obligation to House Tully brought his sons to Robb Stark's war reluctantly and late — late enough that Late Walder Frey became less an insult than an accepted fact about the man — and when Robb Stark broke a marriage pact made in Walder's hall to marry for love instead of alliance, Walder did not simply hold a grudge. He waited for the precise moment repayment would hurt the most.",
      "The Red Wedding is the single worst violation of guest right the story ever stages, and it is entirely the Freys' architecture: a wedding feast, sacred hospitality invoked and then weaponized, music cutting off as a signal, a king and his mother and half his army slaughtered under a roof that was supposed to make them safe. It wins the war for the Lannisters and Boltons and it costs the Freys something no gold ever buys back — every house in the Seven Kingdoms now understands exactly what Frey hospitality is worth, and treats the name accordingly for the rest of the tale.",
      "What survives the betrayal does not survive its consequences for long. The family that grew powerful by being everywhere, marrying everyone, and mattering to every alliance in the Riverlands discovers, once its name is poison, that numbers are no protection against an enemy patient enough to come for them one place setting at a time. House Frey's story ends the way it began — around a dinner table — except this time the Freys are the ones who trusted the wrong host.",
    ],
    vs: [
      "The show resolves the Freys' reckoning fast and total: Arya Stark, having taken a Frey woman's face, serves Walder Frey his own sons baked into a pie, kills him, and later poisons the assembled remainder of the family at a single feast, ending House Frey in the span of two seasons. The published books have not reached anything like that ending — Walder Frey is still alive as of the last volume, the family is fracturing from within over who inherits after his eventual death, and Riverrun's second siege leaves several Frey commanders and a captive Edmure Tully still very much in play. Where the show gave the Freys a clean, singular vengeance, the books are still tracking a slower, messier unraveling with no confirmed ending in sight.",
    ],
  },

  "house:tyrell": {
    paras: [
      "The Tyrells' whole claim to Highgarden rests on an inheritance other, older houses never quite forgave them for. Stewards to House Gardener, the ancient Kings of the Reach, the Tyrells took the castle and the title when the last Gardener king died fighting for the Targaryens at the Field of Fire — a great house's fortune inherited by the family that had merely managed its household, while the Florents and Hightowers and Oakhearts, older blood by any measure the Reach cared about, watched a family of glorified caretakers become their liege lords overnight. Growing Highgarden, Reach nobility never entirely stopped viewing the Tyrells as upjumped stewards playing dress-up in a Gardener king's castle.",
      "What the Tyrells lacked in ancient pedigree they made up for with the single largest granary and the single largest army in the Seven Kingdoms, and Olenna Tyrell — the Queen of Thorns, sharp-tongued even by the standards of a family known for cultivated manners over blunt swords — turned that leverage into the sharpest political instrument in King's Landing without ever picking up a weapon herself. The golden rose on green looks decorative next to a lion or a dragon; the house behind it understood, better than almost anyone else at court, that granaries and marriage contracts win wars just as reliably as armies do, usually with fewer funerals along the way.",
      "The War of the Five Kings finds the Tyrells doing what the Tyrells do best: reading the room and switching horses at exactly the right moment. Margaery is betrothed first to Renly Baratheon for his claim and his charm, then — the instant that claim dies with him — remarried into the winning side, first to Joffrey, then to Tommen, each match managed by Olenna with the patience of a woman who has outlived every king she has ever needed to flatter. It works spectacularly, for a while: Highgarden's grain saves King's Landing from starvation, its army saves the city from Stannis's fleet at the Blackwater, and a Tyrell queen sits the throne beside a Lannister king who does whatever she and her grandmother suggest.",
      "The house's undoing comes from the exact instrument Cersei borrowed to destroy it — the Faith Militant, armed and unleashed specifically to break Tyrell influence over the throne, which promptly turns on its sponsor as readily as its intended target. Margaery is jailed, tried, humiliated in the streets alongside a queen who thought she was above such things; and when Cersei finally answers the threat of trial with an ocean of wildfire beneath the Great Sept of Baelor, the explosion that follows does not spare the Tyrells who came to watch. Olenna alone survives it, briefly, long enough to hand Jaime Lannister a confession — the truth of Joffrey's poisoning, delivered with her family already in ashes and nothing left to lose — and to drink the poison that finishes Highgarden's siege on her own terms rather than her enemies'. By the war's end the golden rose has no one left to fly it.",
    ],
    vs: [
      "This is arguably the single widest divergence for any great house in the saga, simply because of pacing: the show writes House Tyrell's entire destruction — the Faith Militant crisis, the sept's detonation, Olenna's poisoning of Joffrey confessed and avenged, Highgarden besieged and looted by Jaime Lannister — inside about two seasons. The published books have not remotely caught up; the Faith Militant conflict is still unfolding as of the last volume, the Great Sept has not been destroyed on the page, Margaery's trial has not concluded, and Olenna Tyrell is alive and scheming with the Reach's full strength still behind her. Readers of the books have, in effect, watched an entire great house rise and fall on screen that the novels have not yet finished introducing.",
    ],
  },

  "house:martell": {
    paras: [
      "Dorne is the one kingdom Aegon's dragons never conquered, and House Martell has built its entire identity around that fact ever since. When Nymeria, a Rhoynish warrior-queen fleeing Valyria's wars in the east, burned her ten thousand ships rather than let her people be used as a weapon again, she led them to the deserts of Dorne and married Lord Mors Martell to seal the union — bringing Rhoynish law with her into a kingdom the rest of Westeros had assumed would simply adopt Andal custom like everyone else. It didn't. Partible inheritance regardless of a child's sex, open acknowledgment of paramours and baseborn children, women who could rule, fight, and inherit on the same terms as men — Dorne kept its Rhoynish law under a Martell sun, and stayed visibly, deliberately different from the six kingdoms around it.",
      "That difference is also why Dorne survived what no other kingdom did. Aegon's own sister Rhaenys flew Meraxes into the Dornish deserts expecting the same swift capitulation the rest of Westeros gave the Targaryens, and Dorne answered not with pitched battle but with heat, sand, and guerrilla patience — hiding, striking, vanishing, until dragons found nothing to burn and armies found nothing to conquer. Dorne did not bend the knee to House Targaryen for generations, and when it finally joined the realm it did so by marriage rather than surrender, under King Daeron the Second — the only great addition to the Seven Kingdoms that dragonfire never actually purchased. Unbowed, Unbent, Unbroken is not an idle motto in Dorne. It is a description of the only successful resistance in the Targaryen conquest's whole history.",
      "The Red Viper carries that inheritance personally into the war generations later. Oberyn Martell, Prince Doran's fiery younger brother, arrives in King's Landing for Tyrion's trial with one purpose clear to everyone who has ever heard his family history: vengeance for his sister Elia, raped and murdered along with her children during the Sack of King's Landing, a crime the rest of the realm treated as regrettable collateral and Dorne never once forgot. His trial by combat against the man who killed her — fought with poison, pride, and a speech that names her murderer to his face before the killing blow lands — ends in the single most devastating reversal of fortune the tale ever stages, and Dorne's grief curdles, in its aftermath, from patience into open rage.",
      "What follows in Dorne is a house divided against its own instincts. Prince Doran, who has spent decades playing a long, quiet game the rest of the realm mistook for weakness, finds his throne and his family's patience overtaken by relatives who want blood paid for blood immediately rather than on his careful schedule — his own niece and his dead brother's paramour among them. The kingdom that never bent to a dragon nearly breaks itself instead, from within, over exactly how much of its old grief it is willing to spend on new vengeance.",
    ],
    vs: [
      "Dorne is by consensus the most heavily altered storyline in the entire adaptation. The show compresses Dorne's slow-burning political tension into a single truncated arc — Ellaria Sand and the Sand Snakes poisoning Myrcella and seizing power in a palace coup, Doran and Trystane Martell killed off within an episode — that was widely regarded even at the time as the series' weakest stretch. The books have taken a far slower, more layered route that the show never adapted at all: Arianne Martell's secret plot to crown Myrcella queen of Dorne against her father's wishes, Doran's long-planned alliance with a mercenary company and a claimant to the Iron Throne raised in Essos, and a Dornish endgame that, as of the last published volume, has barely begun to reveal its actual shape.",
    ],
  },

  // ================= orders & lesser houses =================
  "group:nights-watch": {
    paras: [
      "The Watch is older than every kingdom it now serves — raised, by its own legend, eight thousand years ago in the aftermath of the Long Night, when the first Others came south and the first men who fought them off swore to keep watching for their return. What remains by the story's opening is a shadow of that founding: nineteen castles along the Wall's hundred leagues, sixteen of them abandoned and crumbling, manned by a garrison a fraction the size the Wall was built to hold. The Watch takes murderers, poachers, debtors and highborn embarrassments in equal measure, promises them a clean slate in exchange for the rest of their lives, and asks them to guard against a threat the rest of the realm stopped believing in generations before any of them were born.",
      "Its structure divides the brothers into three orders — rangers who patrol beyond the Wall, builders who maintain it, stewards who keep the castles running — under a Lord Commander elected for life by the assembled black brothers. The oath itself is the Watch's real scripture, recited by every recruit before a weirwood or a sept depending on which gods they still keep: no lands, no titles, no wives, no children, a man who takes the black surrenders every claim on the world he leaves behind and becomes, in the oath's own words, the shield that guards the realms of men. Whether the realm still deserves that shield, or even remembers it exists, is a question the Watch has stopped asking out loud.",
      "The tale finds the order at its lowest ebb and makes it matter again almost by accident. Jon Snow arrives a highborn bastard among criminals and rises, over his own frequent objections, from steward to ranger to Lord Commander, dragging an institution that had forgotten its purpose back toward remembering it — recognizing the free folk beyond the Wall as potential allies rather than permanent enemies, at exactly the moment the dead start walking again in numbers no nineteen ruined castles could hope to repel alone. It costs him nearly everything: brothers who see mercy toward wildlings as betrayal of eight thousand years of enmity do what the order's harshest traditionalists have always reserved for oathbreakers, real or perceived.",
      "What the Watch means, underneath its politics, is a standing argument that some dangers are bigger than the ones currently occupying the throne room. Every character who crosses the Wall in either direction gets reordered by the experience, because south of it the realm is fighting over a chair, and north of it the realm is not fighting at all — it simply has not yet noticed there is something worth fighting. The Watch's whole tragedy is that it was right the entire time it was being ignored.",
    ],
    vs: [
      "The mutiny that nearly ends Jon Snow's story plays out in both tellings, but the books surround it with a deeper, uglier internal politics the show largely compresses away — Ser Alliser Thorne's faction is only one current among several, and the resentment that finally boils over involves grievances about wildling settlement, Melisandre's growing influence at Castle Black, and years of accumulated slights the novels take their time laying out chapter by chapter. The books also give Craster's Keep and its horrifying arrangement with the Others — sons traded away to whatever comes calling in the night, in exchange for the Watch's tolerance of a rapist and abuser on its northern border — considerably more space and moral weight than the show's compressed version affords it.",
    ],
  },

  "group:kingsguard": {
    paras: [
      "Aegon the Conqueror modeled the Kingsguard on the sworn swords of Valyria's old dragonlords: seven knights in white cloaks and white armor, sworn for life to protect the king's body with their own, forbidden lands, titles, or families of their own that might one day compete with the crown for their loyalty. It is framed as the highest honor a knight in Westeros can receive, and functions, often enough, as the heaviest chain — a Kingsguard cannot refuse an order from the king he serves, whatever that order happens to be, which turns the White Book recording each knight's deeds into as much a ledger of complicity as of glory.",
      "That tension defines the order's most famous member long before the story proper begins. Ser Arthur Dayne and his brothers in white guarded a tower in Dorne on the Mad King's orders during Robert's Rebellion, a stand so absolute that even the men who eventually killed them are said to have respected it — knights who never questioned an order even when the war they were fighting for had already been lost. Jaime Lannister inherited that same code and broke it in the opposite direction, killing the king he had sworn to protect to save a city from being burned alive, and spent the rest of his life wearing the name Kingslayer for an act the realm never bothered to understand as mercy.",
      "By the story's own present, the order has decayed alongside the throne it guards — Barristan Selmy, its most decorated living knight, dismissed without ceremony by a boy king who wants a favorite in his place rather than the realm's finest sword; the white cloaks increasingly filled with men more loyal to whoever controls the throne than to any code the position was built on. What the Kingsguard is supposed to mean and what it has been reduced to protecting come apart in full view, and nearly every character who wears the cloak spends some part of their story reckoning with that gap.",
    ],
    vs: [
      "The novels give the order's mythic backbone — the stand at the Tower of Joy, the White Book's centuries of recorded oaths and deeds, the specific reasoning behind Kingsguard vows and their occasional violent contradictions — far more page space and lore than the show's mostly visual, mostly implied treatment. Jaime's memories of Ser Arthur Dayne and the other white knights of Aerys's reign run considerably deeper in the books, coloring his own sense of what the cloak is supposed to mean against what he actually did with it.",
    ],
  },

  "group:free-folk": {
    paras: [
      "South of the Wall they are called wildlings, a word every free folk person hears as an insult; north of it they simply call themselves free, descendants of the First Men who never bent the knee to any Stark, any Andal king, or anyone else who ever asked. What looks to Westeros like a single lawless mass is actually a patchwork of very different peoples — raiders who live by the sword, cave dwellers who paint their skin and worship things older than the Others, ice-river clans, and giants who ride mammoths and remember when there were more of them. What unites the free folk is not a government but a refusal: no king rules them who was not strong enough to make every clan chief kneel first, and most of them never have been.",
      "Mance Rayder is the exception that makes the rule visible — a former Watch brother who managed to unite a hundred quarreling peoples under one banner for the first time in living memory, not through conquest but through the plainest argument any of them had ever heard: the true enemy is coming, and it does not care whose particular clan gets to it first. The King-Beyond-the-Wall's march south to the Wall is not an invasion so much as an evacuation with an army attached, tens of thousands of free folk trying to get south of the ice before what is coming for them arrives.",
      "Jon Snow's arc runs directly through this collision, and the story's harshest test of his honor is whether he can see the free folk as people worth saving rather than enemies worth fighting. Opening the Wall's gates to let them through — over the furious objection of Watch brothers who have spent their whole lives taught that wildlings are the enemy — becomes the single act that both saves thousands of lives and gets him killed by his own men for the betrayal it looks like from the wrong angle. It is the story's clearest statement that old hatreds and present survival do not always point the same direction, and that choosing survival costs exactly as much as the old hatreds warned it would.",
    ],
    vs: [
      "The books render free folk culture in considerably more texture than the show's condensed version — more named clans, more distinct customs, a richer sense of the many peoples Mance actually had to unite rather than a single generalized wildling identity. The two tellings also diverge sharply on Mance's own fate: the show has Melisandre burn him at the stake before Castle Black's gates, with Jon delivering a mercy-killing arrow to end his suffering. In the books, Mance survives via a swapped identity with another man executed in his place, and continues operating covertly under an assumed name — a major divergence the show never adapted, leaving Mance Rayder alive on the page well past the point of his on-screen death.",
    ],
  },

  "group:brotherhood": {
    paras: [
      "The Brotherhood Without Banners began as Eddard Stark's men, dispatched south to bring Gregor Clegane to justice for atrocities against Riverlands smallfolk — and then Ned lost his head before they could return, and a company of soldiers with no lord left to report to had to decide what they were for. What they became was something the Seven Kingdoms had no other name for: an outlaw band loyal to no crown and no house, funded by nothing, fighting for the specific and unglamorous cause of smallfolk caught between armies that had stopped noticing they existed.",
      "Beric Dondarrion leads them at first, kept alive past any reasonable expiration by a red priest's fire magic — resurrected again and again by Thoros of Myr's prayers to the Lord of Light, each return costing him a little more of who he used to be, until there is barely enough Beric left to spend. The brotherhood's justice is rough and occasionally indistinguishable from the banditry it claims to oppose, holding trials in the woods for lords and smugglers alike and hanging whoever the fire god's flame seems to condemn, which is not always the same thing as whoever actually deserves it.",
      "Their most famous transaction is also their most damning: selling a blacksmith's apprentice named Gendry to a red priestess for gold, a decision the brotherhood justifies as funding the only war that matters and that reads, to nearly everyone watching, as exactly the kind of exploitation of the powerless they were originally formed to prevent. It is the clearest sign that an order built to protect people caught between armies can drift, slowly and without anyone quite deciding to let it happen, into becoming one more thing the smallfolk need protecting from.",
    ],
    vs: [
      "The books take the brotherhood somewhere the show never follows. Catelyn Stark's body, recovered from the river after the Red Wedding, is revived by Beric Dondarrion's dwindling fire magic — passed to her at the cost of what remains of his own life — and what rises is not quite Catelyn anymore: a silent, vengeful figure known as Lady Stoneheart, who takes command of the brotherhood and turns its rough justice into something considerably darker, hunting down everyone even distantly complicit in the Red Wedding for summary execution. It is one of the most significant cuts the show ever made, quietly removing an entire late-book storyline and, with it, the brotherhood's grimmest chapter.",
    ],
  },

  "group:faith": {
    paras: [
      "The Faith of the Seven arrived in Westeros with the Andals and outlasted every kingdom they conquered, worshipping one god with seven aspects — Father, Mother, Warrior, Smith, Maiden, Crone, Stranger — rather than seven separate deities, a theology precise enough that septons spend entire careers explaining the distinction to skeptical northmen who kept the old gods instead. Its great sept in King's Landing, raised on Visenya's Hill, made the capital the Faith's spiritual seat as much as the crown's political one, and for most of the realm's history the two authorities coexisted by mostly staying out of each other's business.",
      "That arrangement had a violent precedent the story's present mostly forgets: the Faith once fielded its own armed orders, the Warrior's Sons and the Poor Fellows, a militant wing willing to make war on kings it judged unrighteous, until Maegor the Cruel crushed the movement and stripped the Faith of the right to bear arms at all. For a hundred and fifty years afterward, the Faith Militant existed only as history — until Cersei Lannister, looking for a weapon to use against a rival house, personally restores its arms and its charter, on the theory that a barefoot fanatic in her debt will make a more biddable weapon than any soldier she could hire.",
      "The theory fails spectacularly and in exactly the direction anyone paying attention should have predicted. The High Sparrow, once armed, recognizes no debt to the queen who armed him, and the movement he leads — drawn from war refugees and the pious poor who have watched the great houses tear the realm apart for a crown — turns its restored authority on the nobility indiscriminately, Cersei very much included. Her own walk of atonement, stripped and shorn and marched through a city she once ruled while a septa tolls a bell behind her, is the precise humiliation she had engineered for someone else, redirected back at its architect with the Faith's blessing.",
    ],
    vs: [
      "The published books have not yet reached the Faith Militant crisis's resolution — Cersei's trial by the Faith is still pending as of the last volume, the Great Sept of Baelor has not been destroyed, and the movement's theological roots in Andal history and the earlier Faith-versus-Crown wars under Maegor the Cruel receive considerably more grounding on the page than the show's more compressed treatment allows. Where the show resolves the entire conflict in wildfire within two seasons, the books are still building toward a confrontation whose shape and outcome remain unwritten.",
    ],
  },

  "group:dothraki": {
    paras: [
      "The Dothraki claim the grass sea at the heart of Essos as their whole civilization, an ocean of open plain that has broken every attempt by the Free Cities to conquer or convert it. They build nothing permanent, keep no walls, and consider stone cities a kind of self-imposed captivity — a khalasar's home is wherever its horses currently stand, and its wealth is measured in bells braided into a warrior's hair, one for every enemy killed, a walking ledger of victories that never needs to be written down.",
      "Authority runs entirely through the khal, a warlord who leads by proven strength and holds his khalasar together for exactly as long as he keeps winning; a khal who is captured, crippled, or beaten loses his khalasar as surely as he loses the fight, because Dothraki loyalty is earned continuously rather than inherited. Vaes Dothrak, the one permanent structure the culture tolerates, functions as sacred neutral ground where no blood may be spilled and every khalasar is welcome — and it is there that widowed khaleesis retire to the Dosh Khaleen, a council of aged former queens whose visions and blessings the Dothraki treat as prophecy older than any single khal's ambitions.",
      "Daenerys Targaryen's marriage into this world begins as a transaction — a khal's bride purchased for an army her brother will never actually command — and ends with her doing something no widowed khaleesi had ever managed before: walking into her husband's funeral pyre and out again unburnt, dragons hatching in the flames, and uniting scattered khalasars under her own authority rather than retiring to Vaes Dothrak as custom demanded. It is the single moment the story tilts fully in her favor, and it works specifically because it breaks a Dothraki rule that had never been broken before.",
    ],
    vs: [
      "The books render Dothraki custom with considerably more anthropological texture than the show has time for — taboos against selling captives, rules around mercy and captivity, prophecies about a promised stallion who will one day mount the world and unite every khalasar under a single banner, a legend the novels tie explicitly to Daenerys's own son and, by extension, to her. Much of that prophetic framework, and the wider cultural detail supporting it, is compressed or dropped entirely in the show's leaner adaptation.",
    ],
  },

  "group:unsullied": {
    paras: [
      "Astapor built the Unsullied to be the most reliable infantry in the world, and reliability, in Astapor's slave markets, is achieved by removing everything that might compete with obedience — bought as children, castrated, and drilled through a training regimen designed to strip away fear, pain, hunger, and want alike, until what remains is a soldier who will hold a line without breaking for any reason a normal army might. They fight with matching spiked bronze caps and short stabbing swords, in ranks so disciplined that onlookers across Essos consider them less an army than a machine.",
      "Daenerys Targaryen's purchase of the entire Unsullied garrison at Astapor is not, on its face, different from any other slave transaction in the city's history — until she frees every one of them on the spot and asks them to choose, for the first time in their lives, whether to fight for her willingly. The gesture becomes her signature: an army built on the total erasure of choice, handed its choice back, and choosing her anyway. Grey Worm rises from their ranks to command them and becomes, in the process, one of the story's clearest examples of a person rebuilding an identity the world had deliberately tried to erase.",
      "What the Unsullied carry into the rest of the war is a discipline no other infantry in either story can match, and a silence that unnerves nearly everyone who fights beside them — they do not boast, do not loot, do not break ranks even when a battle turns against them, because the training that stripped away their fear stripped away the impulses that make ordinary soldiers unreliable along with it. Grey Worm's own halting, hard-won romance with Missandei is the clearest sign of how much humanity survived the process anyway, a tenderness the masters of Astapor never intended their soldiers to have room left for.",
    ],
    vs: [
      "The books describe the Unsullied's training with a bleaker specificity the show mostly implies rather than shows outright — each recruit forced to strangle an infant slave to prove complete obedience before earning the spiked cap, and the culture of emotional blankness the training instills examined at greater length, including the discomfort other characters feel around soldiers who seem to have had ordinary human want trained out of them entirely. The show gestures at the same brutality without dwelling in its full detail.",
    ],
  },

  "group:slavers-bay": {
    paras: [
      "Astapor, Yunkai, and Meereen are what remains of the old Ghiscari empire, a civilization Valyria burned to rubble in a war so total that its language survives mostly as slang in the mouths of the slavers who inherited its coastline. What they inherited along with the ruins was an economy built entirely on human bondage — Good Masters, Wise Masters, Great Masters, whichever city's honorific applies, ruling on the theory that some people are born to be owned and the arrangement is simply how the world works, a theory none of them have ever had seriously challenged before.",
      "Daenerys Targaryen's march through the bay is less a campaign than a demolition, city by city, of that theory: Astapor's Unsullied bought and freed in the same transaction, Yunkai's slave-soldiers turned loose in the streets, Meereen's pyramids stormed and its slaving aristocracy publicly answerable, for once, to the people whose labor built the city they lived in. Meereen becomes the harpy's city precisely because the masters keep fighting back under that banner even after their formal defeat — the Sons of the Harpy waging an insurgency that makes plain how much easier breaking chains is than building whatever comes after.",
      "That difficulty is the region's real subject: Daenerys stays in Meereen far longer than any triumphant liberation narrative would predict, precisely because she takes the responsibility of what follows liberation seriously, reopening the fighting pits as a political compromise, marrying a Meereenese nobleman to stabilize a city on the edge of civil war, discovering that a queen who frees slaves still has to govern the society she freed them into. It is the tale's most sustained argument that revolution and government are different jobs, and that being right about the first does not guarantee competence at the second.",
    ],
    vs: [
      "The books spend considerably more time on Meereen's internal politics than the show, which compresses the region's factional maneuvering and eventually skips it almost entirely. Where the show moves Daenerys toward Westeros relatively quickly, the novels keep her occupied for volumes with Yunkish alliances, Volantene religious politics, and a subplot following Tyrion's own long journey through the slave cities that has no real screen equivalent — an entire stretch of the saga's geography and politics the adaptation ultimately chose to leave largely unexplored.",
    ],
  },

  "group:sellswords": {
    paras: [
      "The Free Cities of Essos run on mercenary companies the way Westeros runs on sworn houses — bands of swords for hire with names like the Second Sons, the Windblown, and the Company of the Cat, loyal to whichever paymaster is currently solvent and prepared to switch sides the moment the coin does. Coin Before Crown is not a formal motto so much as an accurate summary: a sellsword company's contract is its only real oath, and the companies that survive are the ones canny enough to break a contract before it breaks them.",
      "The Golden Company stands apart from the rest by reputation alone — founded generations earlier by exiled supporters of a defeated Targaryen rival claimant, it has never broken a contract in its entire recorded history, a boast most other free companies cannot make and one the Golden Company treats as more valuable than any single payday. Ten thousand strong with war elephants in its train, it is the largest and most disciplined mercenary force in Essos, and precisely because it never breaks its word, whoever manages to hire it is buying something rarer in that world than swords: certainty.",
      "Bronn represents the sellsword tradition's Westerosi cousin — a common-born blade who fights for whoever pays best and says so without apology, first for Tyrion Lannister, later for whoever outbids the last employer, treating loyalty as a market rather than a virtue and surviving, largely because of that honesty, considerably longer than most of the highborn characters who look down on him for it.",
    ],
    vs: [
      "The Golden Company's ultimate allegiance is one of the more consequential divergences in the entire saga. In the show, Cersei Lannister hires the company directly to bolster her defense of King's Landing against Daenerys. In the books, the company's contract lies elsewhere entirely — with a young man calling himself Aegon Targaryen, raised in Essos and believed by many to be the son of Rhaegar Targaryen thought killed in infancy, whose planned invasion of Westeros with the Golden Company at his back is a major unresolved storyline the show cut in its entirety, along with the claimant himself.",
    ],
  },

  "group:faceless-men": {
    paras: [
      "The House of Black and White in Braavos serves the Many-Faced God, a theology built on the observation that every culture's death-deity — the Stranger, the Black Goat, the Lion of Night, a dozen other names in a dozen other tongues — is secretly the same god wearing different masks, and that death itself, properly understood, is a mercy rather than a punishment. Its priesthood, the Faceless Men, extend that logic into their trade: they kill for hire, but only ever as a gift freely given, and the order's most sacred rule is that a Faceless Man never kills for personal reasons, only as an instrument of a god who does not play favorites.",
      "Becoming one requires surrendering exactly what the god's theology asks of everyone eventually: identity itself. Trainees drink from a pool that steals memory and voice for a night, wear the actual harvested faces of the dead kept in the House's silent hall, and are asked, over and over, to become no one — a vessel with no name, no want, no self left to interfere with the god's business. It is presented less as villainy than as a genuinely coherent spiritual practice, one that happens to produce the most feared assassins in the known world as a side effect of its theology rather than its primary purpose.",
      "Arya Stark's apprenticeship there is the story's most direct collision between that philosophy and a character built entirely around the opposite instinct — a list of names she refuses to stop reciting, a sword she hides rather than surrenders, a self she has fought her entire arc to keep even while everyone around her insists that keeping it is the whole problem. She takes the training and rejects the bargain, walking out with skills the Faceless Men never intended to arm a girl who was never going to become no one no matter how many faces she wore.",
    ],
    vs: [
      "The books devote considerably more space to the Many-Faced God's theology and the House of Black and White's internal culture than the show, including the deliberate ambiguity over whether the Kindly Man and Jaqen H'ghar — presented separately at points in the text — might in fact be the same Faceless Man wearing different faces, a puzzle the show largely resolves by simply treating them as one recurring character. Arya's training in the novels also runs considerably longer and darker, including an extended period of self-inflicted blindness as punishment for using her skills for personal vengeance, a consequence the show compresses or skips.",
    ],
  },

  "group:old-ones": {
    paras: [
      "Before the First Men, before the Andals, before any king any house remembers, Westeros belonged to the children of the forest — a small, ancient people who carved faces into weirwood trees and could see through their eyes across vast distances, greenseers whose memory the weirwood network still holds in the story's present, waiting for someone patient enough to listen. Their war with the invading First Men ended not in conquest but in the Pact, sworn on the Isle of Faces, dividing Westeros between the two peoples for four thousand years of uneasy, mostly-kept peace — a treaty older than every subsequent war the story bothers to name.",
      "Opposite the children stand the Others, ancient and nearly wordless enemies who wake once an age to bring the Long Night down on whoever is unprepared for it, walking in ice and cold with the dead marching behind them. What the two powers actually are — how old, what they want, whether either is simply misunderstood rather than evil — remains one of the saga's most carefully guarded mysteries, doled out in fragments through Bran Stark's visions and old wives' tales half the realm has stopped believing.",
      "Bran's own arc runs directly into this older, colder history: trained by the last greenseer to see through the weirwoods and remember what the world forgot, he becomes the story's living bridge to everything that predates the great houses' quarrels entirely, memory itself made into a character with a body and a name. That the Long Night's final battle is fought and, in one telling, finished in Winterfell's own godswood — the exact place where the North's old gods have always been kept — is not coincidence so much as the story admitting, at last, which conflict was the real one all along.",
    ],
    vs: [
      "The show supplies an explicit origin for the Night King — created by the children of the forest from a captured First Man, transformed with a shard of dragonglass through the heart, as a desperate weapon against human invaders that escaped their control. The published books have offered no such confirmed origin for the Others as a species or for any singular leader among them; their nature remains deliberately unresolved on the page, one of the largest open mysteries the novels have yet to address, which the show chose to answer decisively rather than leave hanging.",
    ],
  },

  "group:bolton": {
    paras: [
      "House Bolton's flayed man sigil is not decoration — it is a boast the family has never bothered to soften. Lords of the Dreadfort since long before the Starks unified the North, the Boltons ruled as rival kings in their own right during the Age of Heroes, flaying Stark enemies alive as both punishment and message, and the old, half-joking northern threat that a Bolton still keeps a few flayed men's skins hanging in the Dreadfort's undercrofts has outlived any actual proof either way, which suits the family fine. Their submission to Stark rule ended a war between kingdoms; it never fully ended the rivalry underneath it.",
      "Roose Bolton carries that old cold-bloodedness forward as a personality rather than a policy — soft-spoken, leech-loving, a man who lets other people raise their voices while he calculates. He serves in Robb Stark's war as a loyal-seeming bannerman for exactly as long as loyalty serves him, then arranges the Red Wedding's northern half in exchange for Warden of the North and Winterfell itself, betrayal delivered with the same flat, unhurried tone he uses for everything else.",
      "His son Ramsay is a different register of cruelty entirely — theatrical, sadistic, delighted by suffering for its own sake rather than as a tool, legitimized late and never quite trusted by the father whose name he was given. His occupation of Winterfell turns House Stark's own seat into a torture chamber, and it is precisely that excess, rather than any inherited Bolton restraint, that finally costs the family everything: the North's other houses, watching a captured Stark girl and a broken hostage endure what Ramsay considers sport, choose the Bolton enemies over the Bolton lords the instant a viable alternative appears.",
    ],
    vs: [
      "The published books have not yet staged anything like the show's decisive Battle of the Bastards — Stannis Baratheon's own northern campaign against the Boltons, largely compressed or skipped in the show, is still an active, unresolved storyline on the page. The books also preserve a notorious unsolved mystery the show simply bypassed: the Pink Letter, an unsigned, blood-sealed threat purportedly from Ramsay Bolton that arrives at the Wall demanding Jon Snow's surrender of hostages he does not actually hold — its authenticity and authorship still debated by readers, with no on-page confirmation either way.",
    ],
  },

  "group:clegane": {
    paras: [
      "House Clegane's entire nobility is three generations old, built on a single act: a kennelmaster's son who saved Lord Tytos Lannister from a lion with his bare hands and a knife, and was knighted and landed for it. It made the Cleganes minor lords rather than mere servants, sworn swords of the westerlands answering directly to Casterly Rock — and it produced, within two generations, two brothers whose reputations could not have less resemble the loyal courage the house was founded on.",
      "Gregor Clegane is less a character than a force of nature the story keeps pointed at other people — enormous, nearly wordless, employed by Tywin Lannister precisely because he asks no questions about what he is ordered to do, up to and including the murder of a prince's wife and children during the Sack of King's Landing, an act the realm spent the rest of the story trying and failing to hold anyone accountable for. His brother Sandor grew up in his shadow and under his hand, literally — his own face burned by Gregor as a boy for touching a toy that wasn't his, a mutilation that shapes every scar-conscious, fire-fearing thing about the man he becomes.",
      "Sandor's arc runs in the opposite direction from his brother's entirely: hired muscle for the crown who gradually discovers, mostly through an unlikely partnership guarding Arya Stark across a burning countryside, that his contempt for chivalry's empty rituals was never quite the same thing as contempt for people. He ends the story fighting not for a lord or a coin but against the one person on earth he has the least complicated feelings about — his own brother, in a duel neither of them was ever going to walk away from unchanged.",
    ],
    vs: [
      "The show resolves the Clegane brothers' rivalry with total finality — the two of them destroying each other in single combat, Sandor dragging Gregor's reanimated corpse into a burning castle rather than let it stand. The books have left Sandor Clegane's own fate deliberately ambiguous: last seen gravely wounded and presumed dead by other characters, with strong textual hints — never confirmed — that he may have survived as a silent, penitent gravedigger on the Quiet Isle, a fan theory the books have pointedly declined to either confirm or deny, unlike the show's unambiguous ending for both brothers.",
    ],
  },

  "group:mormont": {
    paras: [
      "Bear Island sits cold and rocky and half-forgotten in the northern sea, and House Mormont has held it for so long by being exactly as tough as the land requires, with no particular deference to which sex is doing the toughening. Mormont women fight, sail, and rule Bear Island as readily as Mormont men, a fact the rest of the North treats as an eccentricity and Bear Island itself treats as simply how the place has always worked — Here We Stand is the motto, and it has never specified who, precisely, is standing.",
      "Jeor Mormont commands the Night's Watch as its Lord Commander when the story opens, an old soldier trying to hold together an order that has forgotten why it exists, while his son Jorah's disgrace — selling poachers into slavery to pay off debts, then fleeing across the narrow sea rather than face justice for it — hangs over the family's name until Jorah spends the rest of his life trying to earn it back in service to a queen he loves hopelessly and can never quite tell.",
      "The house's fiercest member turns out to be its smallest. Lyanna Mormont, still a child when she inherits Bear Island's lordship, faces down grown lords twice her age with a directness that embarrasses grander houses into remembering their own courage, and dies, when the moment finally comes, exactly the way Here We Stand promises she would — standing, facing something enormous, refusing to run.",
    ],
    vs: [
      "Lyanna Mormont barely exists in the published books beyond a name on a page — the show built her entire personality, her scene-stealing confrontations with adult lords, and her eventual death in battle almost from scratch, one of the more significant original creations the adaptation added to material the novels had only sketched in outline. Readers of the books meeting her for the first time through the show were, in a real sense, meeting a character the novels have not yet written.",
    ],
  },

  "group:tarly": {
    paras: [
      "House Tarly holds Horn Hill in the Reach and, more importantly to the family itself, holds Heartsbane — one of the realm's precious few remaining Valyrian steel blades, an heirloom Randyll Tarly treats as more sacred than any of his actual children. First in Battle is the house's motto and Randyll's entire personal religion: a soldier of genuine, terrifying competence who has never lost a battle he commanded, and who cannot forgive his eldest son for being everything he considers weakness given human shape.",
      "Samwell Tarly's exile to the Night's Watch is not framed by his father as punishment so much as correction — a fat, bookish, cowardly heir, in Randyll's estimation, replaced by a more suitable younger brother, sent to a frozen wall at the edge of the world with the explicit understanding that he is never to return and never to have a claim on Horn Hill again. It is one of the story's quieter cruelties, a father discarding a living son as casually as recalling a bad investment.",
      "What Randyll never anticipates is that the Wall would make Sam more useful to the realm's actual survival than Horn Hill ever could have. Sam's journey to the Citadel to train as a maester puts him, eventually, in the one archive with the records capable of unraveling the realm's greatest hidden secret — a scholar's victory his father would never have recognized as victory at all, achieved entirely through the qualities Randyll spent a lifetime despising in him.",
    ],
    vs: [
      "The show gives Randyll and Dickon Tarly a swift, brutal end — both burned alive by Daenerys's dragon after refusing to bend the knee following the Lannister defeat at Highgarden, a scene with no direct counterpart in the published books, where both men remain alive as of the last volume. Sam's research at the Citadel likewise moves considerably faster on screen than on the page, where his slow, methodical progress through the archives — and his discovery of Jon Snow's true parentage — has not yet reached the same conclusion the show dramatizes.",
    ],
  },

  "group:karstark": {
    paras: [
      "House Karstark began as a branch of House Stark itself — founded, the story goes, by a younger son of Winterfell generations back who was granted lands in the North's bleak eastern reaches rather than a claim on the seat he'd never inherit. Karhold has flown the black sunburst on white ever since, distant enough kin to the Starks that the family has never stopped considering itself Stark by blood first and bannerman second, an ambiguity that matters more than either side likes to admit once war forces the question.",
      "Rickard Karstark's grief becomes the fault line that cracks Robb Stark's northern alliance from within. Two of his sons die at the Whispering Wood fighting Jaime Lannister's forces, and when Rickard finds a pair of young Lannister hostages in the camp and murders them in blind retaliation, Robb is left with an impossible choice between the law he has sworn to uphold and the bannerman whose grief, however criminal its outlet, he understands completely. Robb executes him himself, the same way his father would have — and loses the Karstark levies at the exact moment the war can least afford it, one honest sentence pried loose from the alliance that might have saved the Starks from what came at the Twins.",
      "What the execution costs Robb is not merely swords but a lesson about kinship the North does not easily forgive being ignored: the Karstarks are Stark blood by their own founding legend, and killing one of them for avenging his sons reads, to the bannermen watching, less like impartial justice than like a king choosing hostages over his own cousins. The half of the Karstark host that marches home in disgust rather than stay under Robb's banner is a smaller wound than the Red Wedding, but it opens well before that wedding, and it never fully closes.",
    ],
    vs: [
      "The books extend House Karstark's story well past Rickard's execution in a subplot the show has no room for: his daughter Alys Karstark, facing a forced marriage designed to seize her inheritance out from under her, flees to the Wall for protection and ultimately marries a wildling chieftain, Sigorn of the Thenns, in a match Jon Snow brokers to bind the Karstark lands to an ally rather than an enemy. It is an entire late-book strand of Northern politics — succession, coerced marriage, an unlikely wildling alliance — that never makes it to the screen.",
    ],
  },

  "group:seaworth": {
    paras: [
      "Davos Seaworth is the rare lord in this story who was not born one. A Flea Bottom smuggler who broke the siege of Storm's End by running onions and salted fish past a blockade that had starved the garrison to the edge of surrender, he earned his knighthood from a grateful Stannis Baratheon and his family's arms — a black ship on a pale field, an onion for its sigil — the same night Stannis shortened four of his fingers as penalty for a smuggler's life of crime the new knight never pretended he hadn't lived. Davos wears the mutilated hand as proudly as the title; both are honestly earned.",
      "What makes him remarkable is not the rags-to-lordship story so much as what he does with the seat at the table it buys him: alone among Stannis's counselors, Davos says the things a low birth is supposed to disqualify a man from saying, arguing against Melisandre's fire magic on plain moral grounds when highborn advisers hold their tongues, and refusing, at real personal cost, to let a king he genuinely loves sacrifice a daughter to a god Davos has never trusted. He loses standing, position and nearly his life for that honesty more than once, and never once trades it away.",
      "His loyalty outlives the king he served it to. After Stannis's cause collapses, Davos carries what he learned about plain speaking and low-born competence into service first at the Wall and then in King's Landing, becoming one of the few characters in the saga whose entire arc is a straight, undiverted line — a man who started with nothing but a boat and his own good sense, and never once needed anything more than that to matter.",
    ],
    vs: [
      "The books send Davos on an entire diplomatic subplot the show skips almost entirely: after the Blackwater, he sails north to White Harbor to negotiate, at Stannis's direction, with the shrewd and cautious Lord Wyman Manderly for the North's support — a lengthy sequence of political maneuvering, hidden loyalties, and one memorably grim banquet that has no screen equivalent, since the show moves Davos to the Wall and into Jon Snow's story considerably faster than the novels do.",
    ],
  },

  "group:baelish": {
    paras: [
      "House Baelish holds a single stony tower on the Fingers, a strip of land so minor that most of Westeros could not place it on a map, and would have stayed that unremarkable if Petyr Baelish had shown the slightest interest in staying home. Fostered at Riverrun as a boy alongside Catelyn and Lysa Tully, he fell in love with Catelyn, fought a duel he had no business winning against Brandon Stark for the right to court her, and was sent home in disgrace — a humiliation he never once, by any account, actually let go of.",
      "What Littlefinger builds afterward is not a house so much as a debt network with a smile attached: master of coin under Robert Baratheon, brothel owner, moneylender to half the great houses in the realm, a man who understood before almost anyone else that owning what powerful people owe is a subtler throne than any actual crown. His own stated philosophy — that chaos is not a pit but a ladder, and that only those willing to climb through the fall ever reach anything worth having — is less cynicism than an honest description of his entire career.",
      "His pursuit of Sansa Stark across the war's second half is the closest thing the story gives to Littlefinger's true endgame revealed: rescuing her from King's Landing to make her his ward, engineering the Vale's Lord Protectorship through Lysa's murder, and grooming her, patiently and with real tenderness mixed into the manipulation, to eventually rule beside him or in his place. It very nearly works, undone finally not by a rival lord's counter-scheme but by the two Stark sisters he spent years trying to separate, comparing notes and reaching the same verdict about him at the same time.",
    ],
    vs: [
      "The books stretch Littlefinger's Vale scheme across a far longer, more elaborate arc than the show's compressed version. Sansa spends an extended stretch of the novels living as Alayne Stone, his supposed baseborn daughter, while Baelish maneuvers to marry her to Harry Hardyng, heir presumptive to the Vale, and a faction of Vale lords grows increasingly suspicious of Lysa's death and Baelish's total control over young Robert Arryn. None of that extended masquerade survives into the show, which resolves the Vale and Baelish's ambitions in a fraction of the time — and with a far more definitive ending than the still-unfolding book version has reached.",
    ],
  },

  "group:reed": {
    paras: [
      "The crannogmen of Greywater Watch are the North's most private people, marsh-dwellers of the Neck who use the region's bogs, fogs and the shifting foundations of their own moving castle as a defense no siege engine has ever managed to overcome. House Reed has sworn to Winterfell for generations without ever quite integrating into the North's wider political life the way the Umbers or Karstarks have — a small, watchful, uncanny house that keeps its own counsel and turns out, when it finally matters, to have been keeping the North's deepest secret the whole time.",
      "Howland Reed's most consequential act happened decades before the story opens and is only ever discussed in fragments: present at the Tower of Joy alongside Eddard Stark during Robert's Rebellion's final act, he is one of a vanishingly small number of people who actually know the truth of what happened there and why Ned kept the secret he did for the rest of his life. He appears in the present story hardly at all, sending his children Jojen and Meera north in his place — a house whose greatest contribution to the tale is a silence kept faithfully for longer than most alliances survive.",
      "Jojen and Meera carry a different, stranger gift into Bran Stark's story: Jojen's greendreams, prophetic visions the Reeds have always possessed in some measure, guide Bran toward the training that will make him the next greenseer, while Meera's fierce, exhausted protectiveness of her brother and Bran both carries them through a journey beyond the Wall that costs the family dearly and asks for no thanks in return.",
    ],
    vs: [
      "The books tease a considerably larger role for Howland Reed's own youth than the show ever dramatizes — a recurring theory among readers, seeded through hints rather than confirmation, holds that Reed witnessed or participated in a mysterious tournament incident at Harrenhal involving a masked knight defending smallfolk honor, an episode some believe connects directly to Lyanna Stark and the secret at the heart of Jon Snow's parentage. The show adapts none of this ambiguity, leaving Howland Reed's full history one of the more actively debated mysteries the published novels have not yet resolved.",
    ],
  },

  "group:tarth": {
    paras: [
      "House Tarth holds the Sapphire Isle off the stormlands coast, an old and honorable line long since past its wealthiest days, better known by the story's present for the singular daughter it produced than for anything else about its history. Brienne of Tarth grew up unusually tall, unusually plain by the court's own cruel standards, and unusually determined to be a knight in a world with no formal path for a woman to become one — mocked at tourneys, proposed to as a joke, and dismissed by nearly everyone she meets until they actually watch her fight.",
      "Her career is a long series of oaths kept at real cost. Sworn first to Renly Baratheon and unable to save him from the shadow that kills him, she carries that failure into an oath to Catelyn Stark to protect her daughters, a promise Catelyn's own death does nothing to release her from — and Brienne spends years honoring it anyway, escorting an unlikely, one-handed companion across a burning countryside, fighting a bear pit barehanded rather than break faith, and eventually finding and protecting the Stark daughters she was never quite able to locate when it would have been easy.",
      "What Brienne represents, more than any single deed, is the story's argument that chivalry's old language — honor, service, the sworn word — can still mean something even when the world that invented it has mostly stopped believing its own rules. She ends the tale as living proof of the argument: knighted at last, in the old way, by the very oathbreaker she spent years distrusting, and recognized, finally, by an institution that spent her whole life insisting she could never belong to it.",
    ],
    vs: [
      "The books leave Brienne's fate on a genuine cliffhanger the show resolves completely. Her final published chapter ends mid-action, captured by Lady Stoneheart's brotherhood and apparently forced to choose whether to bring Jaime Lannister to be hanged for oathbreaking — the chapter closes on a single shouted word, deliberately ambiguous, and readers have argued for years over what she actually decided. The show, having cut the Stoneheart storyline entirely, instead gives Brienne a clean, decisive arc: survival, a knighthood earned in full view, and an ending as the Kingsguard's Lord Commander in all but name, recording Jaime's deeds honestly in the White Book rather than being forced to end them.",
    ],
  },

});
