/* GoT wiki long-form archive — places of Essos. Original prose. */
Object.assign(WIKI_EXTRA, {

  // ================= the Free Cities =================

  "loc:braavos": {
    paras: [
      "Braavos is the city slaves built to hide in. When Valyria’s ships swept the seas for rowers and miners, one fleet of captives rose, killed their masters, and sailed not for home — every home was watched — but for the end of the map: a fog-bound lagoon at the top of the narrow sea where the dragonlords would never think to look. There they raised a city of a hundred islets stitched together by bridges and canals, and kept its very existence secret for a century, trading through intermediaries while the mightiest empire in the world never learned it had misplaced several thousand of its possessions. Every other Free City is a daughter of Valyria; Braavos calls itself the bastard child, and wears the name with a bravo’s grin.",
      "The secret is long out, and the city now announces itself with the least subtle landmark on earth: the Titan, a fortress in the shape of a striding warrior, so vast that ships pass between its legs and its roar marks the hours. Beyond it lie the Purple Harbor for Braavosi keels and the Ragman’s Harbor for everyone else, the Sealord’s palace with its menagerie, the temples of every god the founders carried into exile — the Moonsingers foremost, for it was their prophecy that led the fleet to the lagoon — and the damp alleys where bravos in flamboyant slashed finery duel over the honor of courtesans whose barges outshine the Sealord’s. Because the founders had all worn chains, the city’s first law endures: no slave may set foot in Braavos. It is the one Free City where the adjective is not a joke.",
      "Two Braavosi institutions bend the whole story from a distance. The Iron Bank, grown from a hoard the founders locked in an iron mine, is the power that wars run on — thrones borrow, thrones repay, and when a throne will not, the Iron Bank funds its replacement, a policy the Lannisters discover the way debtors usually discover things. And in a windowless temple on an island in the lagoon stands the House of Black and White, home of the Faceless Men, an order older than the city itself — begun, the tale goes, among the slaves of Valyria’s mines, where the first of them learned that the gift of death was the only mercy on offer and decided to distribute it more fairly. Their services cost more than gold; what they sell is the most reliable commodity in the world.",
      "The city reaches into the tale before anyone sails there. Syrio Forel, First Sword of Braavos, teaches Arya Stark the water dance in a King’s Landing ballroom, and his catechism — what do we say to the god of death? — outlives him by the length of the entire story. It is to Braavos that Arya flees with an iron coin and two words of Valyrian, and the House of Black and White gives her the tale’s strangest apprenticeship: washing corpses, learning the lying game, going blind and getting her eyes back, serving an order that asks for all of herself when all of herself is precisely the thing she came to lose. The books linger longer in the streets — she is Cat of the Canals selling cockles from a barrow, and a singer who deserted the Night’s Watch learns that Braavos is a bad city for oathbreakers — but both tellings arrive at the same heresy: the Faceless Men teach Arya Stark everything except how to be no one.",
      "Braavos matters to the tale as its great counterexample. Every other city in the story was built by conquest and runs on someone’s servitude; the secret city was built by the conquered and runs on contracts, and it has quietly outlasted the empire that hunted its founders. Even Daenerys’s oldest memory belongs to it — in the books, the house with the red door and the lemon tree outside her window, the only place she was ever a child, stands in Braavos. The city of escaped slaves gave the last Targaryen her image of home; the story does not underline the irony, which is how you know it is intended.",
    ],
    vs: [
      "The show sails Stannis and Davos to Braavos to petition the Iron Bank in person — a scene invented to put faces on the ledger. In the books the bank comes to them: the envoy Tycho Nestoris appears at the Wall, having crossed half a war to collect on the Iron Throne’s debts, and ends up bankrolling Stannis’s northern campaign in a snowstorm. Arya’s apprenticeship is also rearranged — the show builds her exit around Lady Crane’s theater troupe and a long knife-duel with the Waif, while the books spread the training across more identities, more small errands, and considerably more corpse-washing, with her final test still unwritten.",
    ],
  },

  "loc:pentos": {
    paras: [
      "Pentos spreads along its bay in tiers of colored domes and slim brick towers, a merchant city that perfumes its air, waters its gardens, and prefers never to fight anyone it can pay. It is ruled, nominally, by a prince chosen by the magisters — a splendid figure who opens each new year by deflowering the maidens of field and sea, and whose other constitutional duty is starker: if a crop fails or a war is lost, the magisters cut his throat and choose a fresh prince. Real power stays with the forty-odd families who elect him, men like Illyrio Mopatis who measure their standing in warehouses. Defeated in old wars with Braavos, Pentos signed away its slaves and its warships; the magisters keep both anyway, calling the one “free bondsmen” and the other “merchant convoys,” and everyone agrees not to check.",
      "The whole saga opens under a Pentoshi roof. It is in Illyrio’s manse that Viserys Targaryen sells his sister to Khal Drogo for the promise of an army, and on the terrace above the bay that Daenerys — thirteen in the books, mercifully older on screen — is dressed, appraised and traded. Her wedding on the plain outside the walls delivers the story its three petrified dragon eggs, a gift of Illyrio’s whose generosity has never quite added up: the magister gives away a kingdom’s ransom the way other men tip a groom, and readers have been auditing his motives ever since.",
      "The city is the tale’s favorite back door. Varys ships Tyrion out of King’s Landing in a crate and decants him in Illyrio’s manse, where the dwarf drinks his grief among another man’s riches before turning east toward Daenerys — and in the books that turn runs through the story’s largest buried conspiracy. Illyrio and Varys, it emerges, have spent years grooming a hidden claimant: a blue-haired boy on a river barge called Young Griff, raised to believe he is Rhaegar’s son Aegon, saved from the Sack as an infant. Whether the boy is what his handlers claim is one of the novels’ open wounds; either way, the cheesemonger of Pentos has been playing a far longer game than the one Daenerys was sold into.",
      "Pentos is where the story keeps its ledger of beginnings. Daenerys leaves it a chattel and spends the rest of the tale refusing to be one; Tyrion leaves it a self-described drunken murderer and arrives at the other end of Essos a queen’s Hand. The city itself never changes at all — which is rather the point. The magisters’ Pentos, comfortable, complicit and endlessly for sale, is the world the story’s travelers are all, in their different ways, trying to leave.",
    ],
    vs: [
      "The show keeps Pentos as a waypoint and cuts its deepest secret: there is no Young Griff, no Golden Company plot hatched over Illyrio’s table, and the magister himself dwindles to a cameo. Tyrion’s road east is correspondingly shortened — on screen Varys simply carts him to Volantis, while in the books he leaves Pentos down the Rhoyne in the company of the conspiracy itself, sharing a barge with a hidden prince he is not supposed to recognize.",
    ],
  },

  "loc:norvos": {
    paras: [
      "Norvos stands in two pieces on the hills above the Noyne — a walled upper city where the bearded priests keep their fortress-temple, and a lower city of docks and bear pits by the river, joined by a great stair. The priests rule in the name of a god whose true name is never spoken; they alone wear beards in the city, their axes are wedded to them in a rite as binding as marriage, and their tattooed guards are said to be trained from childhood to want nothing else. Life runs to the voices of the city’s three bells — deep Noom, proud Narrah, silvery Nyel — whose peals tell Norvoshi when to rise, work, pray and sleep, a city timed like a monastery and armed like a garrison.",
      "The tale touches Norvos through its exiles. Areo Hotah, captain of Prince Doran’s guards in far Dorne, carries a Norvoshi longaxe and a Norvoshi patience through the books, and his memories give the city its texture — the bells, the bears dancing down the steps, the winters when the Noyne froze. He came south in the train of Mellario of Norvos, the merchant’s daughter Doran wed for love and lost by degrees to Westerosi custom; she went home, and her homesickness runs quietly under half the Dornish plot. Norvos itself never enters the war — but the story is careful to note that even the game of thrones is played, in places, by men keeping time to someone else’s bells.",
    ],
  },

  "loc:qohor": {
    paras: [
      "Qohor sits at the western edge of the vast forest that bears its name, a dark-stoned city grown rich on timber, furs and the caravan trade — the last civilized stop before the long road east to Vaes Dothrak. Its reputation runs darker than its ledgers. The city worships the Black Goat, whose altars take blood daily — calves and horses on ordinary days, condemned men on holy ones — and its name is a byword across Essos for sorcery, necromancy and arts best not enumerated. What is certain is the skill of its forges: the smiths of Qohor alone remember how to rework Valyrian steel without ruining it, a craft they guard so jealously that men whisper the secret involves the Black Goat’s favorite currency. Tobho Mott, the master armorer of King’s Landing who reforges Ice into two Lannister blades, learned his trade there — the Qohorik arts, it turns out, reach even into the story’s most bitter inheritance.",
      "Qohor’s great hour belongs to history, and the story retells it every time the Unsullied are sold. Four centuries past, with its own cavalry annihilated, the city hired three thousand Unsullied to face a khalasar fifty thousand strong. Eighteen times the Dothraki charged; eighteen times they broke on the spears; and when barely six hundred eunuchs still stood among the heaped horses, the surviving riders cut off their braids and threw them at the victors’ feet before turning away. The Three Thousand of Qohor are the sales pitch Daenerys hears in Astapor — proof of what obedience perfected can do, offered by men who never mention what it costs to manufacture.",
    ],
  },

  "loc:myr": {
    paras: [
      "Myr faces the Sea of Myrth behind high walls, a city of workshops where the finest hands in the world make lace worth its weight in gold, carpets, patterned glass and the ground lenses — Myrish eyes — that let maesters study the stars and admirals count enemy sails. The craftsmen are famous; so is the fact that most of them are property. Green-eyed Myrmen deal in slaves as briskly as in lace, and the city’s prosperity rests, like most prosperity in Essos, on people who never see the profits. Between Myr, Lys and Tyrosh lie the Disputed Lands, a wasteland with a self-explanatory name where the three cities have warred for centuries in every combination, hiring free companies to bleed for fields that no war has ever actually settled. Half the sellswords in the story learned their trade in those quarrels.",
      "Myr seeps into the tale through its exports and its exiles. Thoros of Myr, a red priest sent west to convert a king and rather more successful at tourney melees and wine, becomes the unlikeliest holy man in Westeros when his rote funeral prayer starts raising Beric Dondarrion from the dead. Myrish lace trims the story’s finery, Myrish lenses sit in the story’s towers, and Myrish firepots and crossbows turn up wherever men are paying for an edge — the city fights in every war of the age without ever sending an army, which the magisters of Myr would consider the whole art of statecraft.",
    ],
  },

  "loc:tyrosh": {
    paras: [
      "Tyrosh crowds its rocky island off the Stepstones behind fortifications the Archon keeps in good repair, for the city began as a Valyrian military outpost and never lost the habit of armament — it merely learned to sell it. Tyroshi love loud color the way Braavosi love black: a sea snail of the surrounding waters yields dyes of every impossible shade, and merchants and sellswords alike wear forked beards in green, pink and blue. The city trades in dye, pear brandy, ornate armor and, above all, hired violence; its position athwart the Stepstones makes it broker to every pirate, smuggler and free company in the narrow sea, and Tyroshi captains fill mercenary rolls from the Disputed Lands to Slaver’s Bay. Daario Naharis, the flamboyant captain who fights his way into Daenerys’s service and rather further, is the city’s type specimen — blue hair, gilded swagger, negotiable loyalties expensively sold.",
      "History remembers Tyrosh as the place the Ninepenny Kings made their throne. A generation before the tale, a band of pirates, sellswords and the last Blackfyre pretender seized the city and the Stepstones as a first step toward Westeros, and the Iron Throne sent an army to burn them out — the war where a young Barristan Selmy cut down Maelys the Monstrous and ended the male line of the Blackfyres. It is the recurring fate of Tyrosh to host other people’s ambitions: everything in the city is for sale, including, periodically, the city.",
    ],
  },

  "loc:lys": {
    paras: [
      "Lys the Lovely drowses on its islands in the warm southern sea, all perfumed gardens and colonnaded bathhouses, founded by Valyrians as a retreat for the Freehold’s wealthy and never quite done being one. The old blood runs purest here — pale skin, silver-gold hair, eyes of purple and blue — and the city has made its inheritance its industry: the pleasure houses of Lys are famed across two continents, their most beautiful slaves bred, the traders say, like prize horses, and sold for the price of manors. Lysene worship centers on a love goddess whose service and the city’s commerce are not easily told apart. It is a soft city with a hard ledger — everything lovely in Lys is owned.",
      "Its other export is quieter. Lysene alchemists brew the tears of Lys, a poison without color, taste or trace that dissolves the bowels and reads as a natural death — and it is a dose of the tears, administered to Jon Arryn, that kills the Hand of the King and sets the entire story moving. The city seeds the tale with its children, too: Varys, the realm’s master of whisperers, was born a slave in Lys before a sorcerer’s knife and his own genius remade him, and the merry pirate Salladhor Saan, self-styled prince of the narrow sea, lends Stannis his fleet at Blackwater and Davos his friendship at a price. Pleasure, poison and intelligence — Lys deals in everything that works best unseen.",
    ],
  },

  "loc:selhorys": {
    paras: [
      "Selhorys is a “town” only by the arithmetic of Volantis, which owns it: a walled river port on the east bank of the Rhoyne, garrisoned against Dothraki raiders, its stone quays busy with the barge trade — larger, the books note with some amusement, than most cities of Westeros, and still ranked beneath the notice of the Black Walls. It is the first place the story’s travelers feel the east tilting toward Daenerys: in Tyrion’s voyage downriver, a red priest preaches to rapt crowds on the riverfront that a savior queen has come to remake the world, and soldiers bound for the slave wars fill the wine sinks with rumor of dragons.",
      "It is in Selhorys that the dwarf’s luck turns. Slipping ashore against orders, Tyrion drinks, gambles and talks his way through a brothel — and walks out over the shoulder of Ser Jorah Mormont, an exile hunting a pardon with a Lannister for a gift. The abduction bends both men’s roads toward Volantis, the slavers and, eventually, the queen herself; the town goes back to its barges, unaware it has hosted a hinge of the story.",
    ],
  },

  "loc:valysar": {
    paras: [
      "Valysar is one of the beads on the Volantene string — a river town on the great Rhoyne between Selhorys and Volon Therys, living by the barge trade, the fisheries and the tribute it owes the triarchs downstream. The Shy Maid poles past it in Tyrion’s long voyage south, one more huddle of quays and orchards under the vast river sky; the books grant it no adventure, which is its own kind of portrait. Towns like Valysar are what empire looks like from below — taxed by a city they will never enter, guarded against horselords they hope never to see, and feeding everyone’s wars with grain and rivermen while the story’s dragons pass far overhead.",
    ],
  },

  "loc:volon-therys": {
    paras: [
      "Volon Therys spreads along the west bank of the lower Rhoyne, last of the Volantene river towns before the great city itself — a crossing place of ferries, fish markets and garrison walls where the river runs already miles wide. Like its sisters it belongs to Volantis and history mostly forgets it; the books do not. It is beneath the walls of Volon Therys that the Shy Maid’s long voyage ends and the tale’s buried conspiracy surfaces in daylight: the Golden Company, greatest and most expensive of the free companies, stands mustered on the plain — ten thousand men, their elephants, and the gilded skulls of their dead captains — waiting for a hidden prince.",
      "In the camp there, Jon Connington and the boy called Young Griff make the choice that redirects the whole eastern war: with Daenerys mired in Meereen and half a world away, the company will not sail to her — she will be brought the war instead. They strike for Westeros directly, an invasion the show never films, launched from a river town most maps do not trouble to name. The Rhoyne has carried a great many armies; Volon Therys is where it launches the strangest one.",
    ],
  },

  "loc:sar-mell": {
    paras: [
      "Sar Mell was Rhoynish once — a river city of the people who called the great stream Mother, facing across the water toward what is now Volantene ground. It died in the old wars, when the young Freehold’s colonies pressed the river folk and the quarrel grew from raids to ruin; the tales say it was the sack of Sar Mell that helped light the final war, the one Prince Garin led a quarter of a million spears to lose. What remains is broken stone among the reeds, passed by every barge on the lower river and boarded by none. The Rhoyne’s banks are strewn with such places — the fine print of Valyria’s victories, still legible a thousand years on.",
    ],
  },

  "loc:ny-sar": {
    paras: [
      "Ny Sar was the Mother City — Princess Nymeria’s own seat, raised where the Noyne meets the Rhoyne and the joined waters spread so wide they seem a moving sea. The Rhoynar built as their river taught them, in fountains, water gardens and pale domes, and Ny Sar was their marvel: a palace city of song whose princes kept the peace of the upper river for a thousand years. Valyria ended all of it. When the dragons had broken Garin’s great host downstream, the river cities emptied before the fire could arrive, and it was from these quays that Nymeria launched the legend — ten thousand ships, laden with a civilization’s survivors, down the Mother and across the world to Dorne.",
      "The ruins keep their dignity. Tyrion’s barge glides through drowned Ny Sar in the books, past broken domes and shattered spires wound in moss and flowers, while the Rhoynish orphans who crew the Shy Maid sing softly to Mother Rhoyne of her lost children. Nothing in the tale mourns Valyria; a great deal of it, quietly, mourns the Rhoyne. Ny Sar is where that grief keeps its architecture.",
    ],
  },

  "loc:volantis": {
    paras: [
      "Volantis is the oldest of the Free Cities and never lets anyone forget it: the first daughter of Valyria, sprawled across the Rhoyne’s mouth where the river is too wide to bridge except once — the Long Bridge, a road of shops, temples and displayed criminals striding the water on massive piers. At the city’s heart stands a ring of fused black dragonstone, seamless and two hundred feet high: the Black Walls, raised by the Freehold itself, within which only those who can trace their blood to old Valyria may dwell. Outside them seethes the real city — harbors, fish markets, sweltering streets, and the elephants that do its hauling — where slaves outnumber the free five to one and every slave’s face is tattooed with his function: flames for the red temple’s servants, wheels for drivers, tears for the whores. Volantis does not hide what it is; it itemizes it.",
      "The city is governed by three triarchs, elected each year by the freeborn in a ten-day festival of bribery and speeches, and its politics have worn two party names since the Century of Blood: tigers, the old warrior faction that tried to reconquer Valyria’s empire after the Doom, and elephants, the merchants who took over when the tigers had lost fleets, armies and every ally from Pentos to Braavos. The elephants have won nearly every election for three hundred years — a fact the story files away, because the tigers are still there, still voting, and a war against a slave-freeing dragon queen is exactly the argument they have waited three centuries to win.",
      "In the books, Volantis is where the east catches fire. Tyrion and his captor Jorah arrive to find a city coming quietly to the boil: the red temple of R’hllor — greatest in the world, its priests preaching to thousands — has declared Daenerys the savior reborn, and its slave congregations listen with dangerous attention. The widow of the waterfront, a freedwoman who rules the docks from a wine-shop table, sends the travelers on with a message for the queen: tell her we are waiting. When the triarchs dispatch their fleet to help crush Meereen, the books let the reader do the arithmetic — a slave city sending slave-rowed ships to fight the breaker of chains, with red priests aboard and rebellion belowdecks. Volantis is the war’s biggest wager, still unresolved when the published story pauses.",
      "The show pays the city a briefer call — Tyrion and Varys cross the Long Bridge among the crowds, hear a red priestess preach the dragon queen to a rapt slave audience, and Tyrion is snatched from a brothel by Jorah before the city can show them more. Even trimmed, the scene carries the essential fact: Volantis is where Daenerys is a religion before she is a rumor. The oldest daughter of Valyria, praying for the last one — the story never says it aloud, but it builds the whole east on it.",
    ],
    vs: [
      "The show folds the books’ entire river journey into Volantis: Tyrion’s abduction happens there instead of in Selhorys, the red priestess absorbs the role of the high priest Benerro, and the widow of the waterfront, the tiger–elephant politics and the Volantene war fleet never appear. Book Volantis is a powder keg the story deliberately leaves smoking; show Volantis is a vivid stopover on the way to Meereen.",
    ],
  },

  // ================= the Dothraki sea & the east =================

  "loc:vaes-dothrak": {
    paras: [
      "Vaes Dothrak is the only city of a people who despise cities, and it is built accordingly: no walls, no gates, no streets in any ordered sense — a vast sprawl of grass palaces, horse-hide tents and open sky beneath the Mother of Mountains, entered between two colossal bronze stallions whose hooves meet in an arch. Along its godsway stand the stolen gods of every people the khalasars have ever broken, monuments dragged across a continent as trophies. The Dothraki raze cities; this one they keep, because prophecy says the khal of khals, the Stallion Who Mounts the World, will one day be proclaimed here. Under the Mother of Mountains no blade may be drawn and no free man’s blood spilled, which does not make the city safe — merely inventive.",
      "The city is ruled, insofar as it is ruled, by the dosh khaleen: the widows of dead khals, who read omens in smoke and burning grass and speak for the Dothraki past. Between raids, the khalasars come to Vaes Dothrak to trade — its market is the one ground where the caravans of the far east and the merchants of the west meet under truce — and to lay their plunder before the crones. Every khaleesi is bound to the place twice: she must come there to eat the raw stallion’s heart before the dosh khaleen while they prophesy over her unborn child, and when her khal dies, custom demands she return and live out her days among the widows. The city is the promise and the prison folded into one address.",
      "Daenerys’s time there delivers the story two of its founding scenes. She eats the stallion’s heart and keeps it down, and the crones proclaim her son the Stallion Who Mounts the World — a prophecy the story then spends years bending toward a daughter instead. And it is in the sacred city that her brother finally forces the issue, drunk, sword drawn where no blade may be, demanding his crown with steel at his sister’s belly. Drogo’s solution honors the letter of the law with molten gold, and Daenerys watches without looking away: no blade, no drop of blood spilled, and the last obstacle between her and her own story removed by the very customs meant to bind her.",
      "The show sends her back. A widowed khaleesi twice over by the sixth season, Daenerys is hauled to Vaes Dothrak to join the dosh khaleen as tradition requires — and instead locks the gathered khals in the temple, tips the braziers, and walks out of the fire unburnt for the second time in her life, taking every khalasar on the grass as her own. The city built to hold widowed queens becomes the place a widow claims the whole horde; the books, which leave her at the edge of the grass sea with a khalasar closing in as the published story pauses, seem to be steering toward the same appointment by a darker road.",
    ],
    vs: [
      "The second visit is the show’s invention — a screen answer to a book question still open. In the novels, Daenerys ends the fifth volume alone on the Dothraki sea with Drogon, the ashes of Meereen’s peace behind her and Khal Jhaqo’s riders arriving; her return to Vaes Dothrak and the judgment of the dosh khaleen is where the story is plainly headed, but how it goes remains unwritten. The temple fire, the burning of the khals and the wholesale winning of the horde are television’s bold guess at that chapter.",
    ],
  },

  "loc:village-of-the-lhazareen": {
    paras: [
      "The Lhazareen keep sheep on the dry lands south of the grass sea, worship the Great Shepherd who counts every soul his flock, and do not fight — a theology the Dothraki have priced precisely. The horselords call them the lamb men, raid them for slaves the way other men shear wool, and consider the arrangement part of the natural order. Their villages are mud-walled and low, their god gentle, their history a ledger of other people’s harvests. The story visits exactly one such village, and what happens there outweighs half the battles in the tale.",
      "Drogo’s khalasar falls on the village to take slaves for Slaver’s Bay — the promised crown must be bought in ships, and ships are bought with people. Riding through the aftermath, Daenerys does the first queenly thing of her life and the first that costs her: she claims the raped women as her own, among them Mirri Maz Duur, a godswife schooled in healing far beyond her village. When a raider’s wound festers and Drogo begins to die, Daenerys turns to Mirri’s deeper arts, and the godswife names the only price of the bloodmagic that follows: only death pays for life. The tent, the shadows, the songs — and the bill, itemized with a healer’s care: the khal returned as a breathing shell, the son in Daenerys’s womb taken in trade, the khalasar scattered to new khals by morning.",
      "Daenerys asks why, and Mirri Maz Duur’s answer is the coldest arithmetic in the story — saved for what, she asks, when her temple was burned and her flock butchered before the savior rode by. Daenerys binds her to the pyre even so, and walks into the fire with her three eggs; the dragons hatch out of a village woman’s execution as much as out of any miracle. The tale never lets the trade fade: every chain Daenerys breaks afterward is partly an argument with the godswife of Lhazar, and the question of what a liberator owes the people her liberation arrives too late to save is asked here first, in mud walls, by the story’s smallest and most unyielding prophet.",
    ],
  },

  "loc:bayasabhad": {
    paras: [
      "Bayasabhad stands at the western mouth of a pass through the Bones, the greatest mountain range in the known world, and lives by the oldest business in geography: everything crossing between east and west pays at the gate. With its sister cities it is a remnant of the Patrimony of Hyrkoon, an ancient realm the deserts ate, and travelers’ accounts insist on its strangest inheritance — the city is defended by warrior women, springing from the old Hyrkoon teaching that only those who give life should be permitted to take it. Its walls have turned back khalasars that never troubled to learn its name properly; the caravans pay, the passes hold, and the far east begins.",
      "For the story, Bayasabhad is horizon. It appears in the tale the way it appears to the characters — a name in a trader’s mouth in the market of Vaes Dothrak, proof that the world keeps going long after the map’s ambitions stop. The saga’s wars never reach the Bones; the city’s role is to stand at the edge of the telling and suggest, quietly, how much world there is that no throne in the story has ever ruled.",
    ],
  },

  "loc:samyrian": {
    paras: [
      "Samyrian is another of the great pass-cities of the Bones, holding its gate through the mountains north of Bayasabhad — the same Hyrkoon inheritance, the same massive walls, the same reported garrisons of women with spear and bow keeping a toll road that predates every kingdom in the story. Between the Dothraki sea and the fabled lands beyond the mountains, the pass-cities are the turnstiles of the world: silk, spice, jade and rumor come west through their gates, and the west sends back gold, wool and the occasional overconfident khalasar. The tale leaves Samyrian untouched at the edge of the map, one of the names that make the world feel wider than the war — which, for a story fought over a single iron chair, is a useful thing to keep on the horizon.",
    ],
  },

  "loc:qarth": {
    paras: [
      "Qarth calls itself the greatest city that ever was or will be, and has the address to argue it: astride the straits the Qartheen name the Jade Gates, between the Summer Sea and the Jade Sea, so that the trade of half the world pays its harbor dues. Three great walls ring it — sandstone, then grey stone, then black, each carved with reliefs of beasts, of war, and finally of lovemaking — and within them rise fountained palaces, arcades scented with spice, and merchants who weep ornamental tears at a hard bargain. Milk-pale Qartheen aristocrats, the Pureborn, rule from the Hall of a Thousand Thrones; beneath them jostle the great merchant combines — the Thirteen, the Ancient Guild of Spicers, the Tourmaline Brotherhood — and beneath everyone, as ever in the east, the slaves who carry the palanquins. Qarth is what wealth looks like when it has had three thousand years to decorate.",
      "The city keeps stranger tenants. In the House of the Undying, a windowless grey ruin, dwell the warlocks of Qarth, blue-lipped from the shade-of-the-evening they drink, masters of an art that everyone agrees has dwindled — until dragons return to the world and the warlocks begin, unsettlingly, to matter again. The Sorrowful Men, a guild of assassins who apologize gently before they kill, take commissions in the shadows of the same arcades. Qarth’s glittering surface and its occult understory are the same market: everything in the city is for sale, and the priciest goods do not appear in the stalls.",
      "Daenerys comes to Qarth out of the Red Waste with a starving remnant and three small dragons, and the city teaches her what her miracle is worth to other people. The merchant prince Xaro Xhoan Daxos feasts her and angles for dragons — by marriage in one telling, by subtler contracts in the other — the Pureborn refuse her ships with exquisite regret, and the warlock Pyat Pree draws her toward the House of the Undying, where the dust of the city’s magic wants her fire for itself. In the books she walks in willingly and is shown the saga’s densest reel of prophecy — three fires, three mounts, three treasons, the blue-eyed king with no shadow, the mummer’s dragon — before the Undying Ones try to feed, and Drogon burns the house down around her. She leaves the city richer in warnings than in ships, which turns out to be the Qartheen exchange rate.",
      "Qarth’s function in the tale is the gilded mirror. Slaver’s Bay will show Daenerys the world’s cruelty raw; Qarth shows it lacquered — a civilization that will applaud her, host her, appraise her, and lift nothing to help her, because dragons are an asset class and a khaleesi with no army is a curiosity. She arrives calling herself a queen and leaves understanding that no one in the east will give her a throne; the fleet she finally takes westward she will have to buy, break or burn her way to. Every liberator needs one city to teach her that admiration is not aid. Qarth volunteers.",
    ],
    vs: [
      "The tellings diverge sharply inside the walls. The show invents the theft of the dragons and the coup of the Thirteen — chained dragons in the tower, Pyat Pree’s duplicates, Xaro’s famously empty vault, and Daenerys sealing Xaro and Doreah inside it. In the books nothing is stolen: Daenerys visits the House of the Undying by invitation, receives her prophecies, and burns it from within; Xaro is a subtler figure who wants a dragon as a gift and, refused, reappears at Meereen seasons of plot later to declare Qarth’s war. The warlocks, half-comic on screen, remain at large in the novels — a fragment of them pursues her east in the hold of a Qartheen ship, an unsettled account the show simply closes.",
    ],
  },

  // ================= Slaver's Bay & old Valyria =================

  "loc:meereen": {
    paras: [
      "Meereen is the largest of the slave cities and the loudest argument for their world: a sprawl of many-colored brick at the mouth of the Skahazadhan, crowned by stepped pyramids in which the Great Masters live like minor gods — the Great Pyramid alone rises eight hundred feet, with a bronze harpy screaming from its summit. The harpy is Ghis’s old emblem, and Meereen is old Ghis’s proudest heir: a culture of tokars and filed teeth, of fighting pits where slaves die for applause, and of a trade in human beings so foundational that the city cannot imagine itself without it. When Daenerys marches up the coast road, the Great Masters nail a slave child to a milepost every mile, arms pointing her way — a hundred and sixty-three signposts announcing exactly what the city thinks of liberators.",
      "The city falls to cunning rather than siege: a way in through the sewers, arms passed to the slaves within, and a rising that opens the gates from the inside. Daenerys answers the mileposts with a symmetry that will follow her name forever — a hundred and sixty-three Great Masters crucified in the plazas, justice by mirror — and then does the thing no conqueror in the story has done before her: she stays. Astapor taught her that a freed city abandoned is merely a city waiting for new masters. So the queen sits in the Great Pyramid, and the tale turns from the easy arithmetic of conquest to the long division of ruling.",
      "What she rules is an insurgency with a city attached. The Sons of the Harpy murder her freedmen in the night; the old families smile in her court and bank on her failure; the fighting pits demand reopening, and the city’s peace is finally priced at a wedding — Hizdahr zo Loraq, nobility’s smoothest invoice. In the books the vise is crueler still: Yunkai’s coalition camps outside the walls with sellsword companies and siege engines, the pale mare — the flux — rides into the city with the refugees, and the peace curdles toward a battle the published story has only begun. Both tellings converge at Daznak’s Pit, where the games’ blood-noise draws Drogon out of the sky, and Daenerys climbs onto her dragon’s back and leaves her own compromise burning on the sand.",
      "The books mark time in her absence with the story’s strangest queue: half the east sails for Meereen at once. Victarion Greyjoy brings the Iron Fleet and a stolen horn that allegedly binds dragons; Quentyn Martell arrives with a marriage pact a generation old and pays for his try at a dragon with his life; Tyrion reaches the siege lines in a sellsword company; and Ser Barristan, ruling as Hand in the queen’s absence, readies the city for the Battle of Fire. The show compresses the convergence to its essentials — Tyrion governs, bargains with the masters, and is rescued from his own diplomacy when Daenerys returns to burn the slavers’ fleet in the bay and take their ships for Westeros.",
      "Meereen is the tale’s test case, and it is honest about the results. Daenerys wins every battle in Slaver’s Bay and nearly loses the peace in a single city, because breaking chains is a morning’s work and building what comes after is a life’s. The queue of suitors, advisers and enemies her pyramid accumulates is the story in miniature: everyone wants the dragon, no one wants the homework. When she finally sails, she leaves the city its freedom and its uncertainty in equal measure — the most truthful ending the story could give a revolution.",
    ],
    vs: [
      "Meereen is where the show’s compression cuts deepest. Ser Barristan dies in a Harpy ambush on screen; in the books he lives to rule the city as Hand and lead it to war. Victarion’s fleet, Quentyn’s doomed embassy, the pale mare, the Windblown and the whole assembling Battle of Fire are book material the show replaces with a single naval assault. Even the marriage differs — book Daenerys actually weds Hizdahr and endures the politics of the match, while the show leaves him a betrothed corpse at Daznak’s. Screen Meereen resolves in a season what the novels have deliberately left as their greatest unfinished siege.",
    ],
  },

  "loc:yunkai": {
    paras: [
      "Yunkai, the Yellow City, rises in tiers of yellow brick that its masters find golden, and specializes in the slave trade’s most intimate cruelty: it breeds and trains bed slaves, schooling children in the seven sighs and the sixteen seats of pleasure and selling refinement by the pound. Its Wise Masters wear tokars, file their teeth, and are wise chiefly in the sense that they prefer paying others to fight — when Daenerys marches north from Astapor, Yunkai’s defense is a hired free company and a pair of gilded envoys with chests of gold and insults dressed as flattery. She takes the gold, turns the sellswords by way of a captain named Daario Naharis, and storms the camps by night; the city opens its gates without a proper siege.",
      "What follows outside the walls is the story’s most argued-over image. The freed slaves pour out to meet her calling her mhysa — mother — and lift her over the crowd; the show frames it as a golden apotheosis, the books let a reader taste the unease under the word. Either way, Yunkai is Daenerys’s education in the limits of a light touch: she frees the city and moves on, and the Wise Masters, unbroken and unsupervised, simply restock. Within a season they are the paymasters of the counter-revolution — hiring companies like the Windblown, whose ranks in the books conceal a Dornish prince traveling under a false name, raising coalition armies, and pressing the siege of Meereen with slave-catching back in business behind them.",
      "Yunkai matters because it is the argument Astapor and Meereen sit between. Astapor shows what happens when a freed city is left to wolves; Yunkai shows what happens when the masters are left their gold. The Yellow City never wins a battle in the entire tale and nearly wins the war anyway — through patience, hired spears and the world’s general willingness to let slavers be slavers so long as the goods keep moving. When the story wants to say that evil is less a fortress than a market, it points at Yunkai.",
    ],
    vs: [
      "The books split Yunkai’s hired swords into two companies — the Stormcrows, whose captains Daario beheads to bring his men over, and the Second Sons under the vile Mero — while the show folds them into a single Second Sons with Daario delivering one head instead of two. The later war differs more: the novels give Yunkai’s coalition the Windblown, the Tattered Prince and a grinding siege of Meereen the published story has not finished, where the show reduces the Yellow City’s revenge to a fleet that burns in one afternoon.",
    ],
  },

  "loc:astapor": {
    paras: [
      "Astapor is red brick and red dust at the mouth of the Worm, a hot, declining city that the other slavers’ towns sneer at — and the home of the one commodity no one sneers at. In its fighting yards the Good Masters manufacture the Unsullied: boys cut young, trained past pain, past fear, past name — each recruit’s final examination, the books specify, is the purchase of a newborn from its mother’s arms and its killing before her, with a silver coin paid to the owner for the loss. The result is the finest infantry in the world, obedient as the dead, and Astapor’s Plaza of Pride displays them for buyers beneath a bronze harpy while masters like Kraznys mo Nakloz detail the product in Valyrian, confident the silver-haired barbarian girl cannot understand a word.",
      "The sale is the story’s cleanest trap. Daenerys offers a dragon for every Unsullied in the city, endures Kraznys’s obscenities through the diplomatic filter of a young slave translator named Missandei, and takes possession of eight thousand spears — then reveals, in flawless Valyrian, that a dragon is not a slave. Drogon’s first word of command, dracarys, turns the Plaza of Pride into the masters’ pyre; the Unsullied, freed on the spot and asked to fight as free men, choose her to a man. It is the tale’s most satisfying morning, which is precisely why the story appends an afternoon.",
      "Daenerys marches on and Astapor demonstrates what a beheaded tyranny grows back. The council she leaves — a healer, a scholar, a priest — is overthrown within the year by a butcher named Cleon, who crowns himself, cuts boys to make new Unsullied, and drags the city into war with Yunkai. In the books the sequel is grimmer still: siege, famine, plague, a butchered Butcher King, and refugees streaming toward Meereen carrying the pale mare with them — the red city reduced to a warning that reaches Daenerys as a disease. Astapor is the question mark the story pins to every liberation that follows: chains can be burned in a day; what was done to the people who wore them cannot.",
    ],
  },

  "loc:old-ghis": {
    paras: [
      "Old Ghis was an empire when Valyria was a rumor of shepherds among volcanoes. The harpy city built the world’s first great war machine — the lockstep legions, freeborn soldiers with tall shields and iron discipline whose memory the Unsullied are bred to counterfeit — and planted colonies around the bay that still bears its business model’s name. Then the Freehold rose, and the two powers fought five wars. Ghis won none of them. Legions, courage and empire proved to be answers to every military problem except dragons; the fifth war ended with the mother city burned to ash, her walls thrown down, her fields sown with salt and sulfur, and her people yoked into the very trade they had practiced on others.",
      "What survives is instructive: nothing of Ghis but the habit. The old tongue is dead — the slaver cities speak a mongrel Valyrian with Ghiscari pretensions — yet Astapor, Yunkai and Meereen paint the harpy on their gates, file their teeth, and intone that brick and blood built Ghis five thousand years on, a civilization reduced to the cosplay of its own conquerors’ victims. The ruin itself sits south of the bay, unvisited by the story and unneeded by it: every pyramid Daenerys storms is Old Ghis’s echo, and the empire’s true monument is the trade she comes to burn.",
    ],
  },

  "loc:new-ghis": {
    paras: [
      "New Ghis holds its island south of Slaver’s Bay and takes the old empire more literally than its cousins: alone among the Ghiscari cities it drills iron legions in the ancient fashion — freeborn spearmen in lockstep, not bought Unsullied or hired companies — as if five thousand years and a few dragons were a temporary setback. The books give the legions their audition: when the slavers’ world closes ranks against Daenerys, New Ghis ships thousands of legionaries to the siege of Meereen, the largest honest army in the coalition of hirelings and tokar-wearing amateurs camped before the walls. Whether the old lockstep fares better against dragons the second time is a question the published story leaves poised — but the city itself is the bay’s driest joke: the empire Valyria erased, patiently reenacting itself on an island, waiting out the millennia for a rematch.",
    ],
  },

  "loc:tolos": {
    paras: [
      "Tolos sits on the Gulf of Grief northwest of the bay proper, a modest slaving city with one immodest export: the slingers of Tolos are reckoned the finest in the world, whipping lead bullets farther and harder than most bows shoot, and free companies pay well for them. Perched between Valyria’s haunted hinterland and Slaver’s Bay’s wars, the city has made neutrality a craft — in the books it is among the powers Daenerys’s envoys court in the great diplomatic scramble around Meereen, polite to the dragon queen and to her enemies alike. Tolos survives the way small cities near large ruins learn to: by being useful to everyone and worth conquering to no one.",
    ],
  },

  "loc:elyria": {
    paras: [
      "Elyria keeps to its island in the Gulf of Grief, close enough to the smoking ruin of Valyria that its sailors watch the horizon glow on foul nights, far enough to have outlived the Doom that killed the mainland cities. It is a quiet name on the story’s map — a trading city of the old Valyrian fringe, minding its harbors between Tolos and the demon-haunted coast, touched by the tale only as a port of call in the diplomacy swirling around Daenerys’s war. Its distinction is simply endurance: when the gods dealt out catastrophe to the Freehold’s daughters, Elyria drew water instead of fire, and an island turned out to be the best inheritance of all.",
    ],
  },

  "loc:mantarys": {
    paras: [
      "Mantarys stands inland on the demon road, the old Valyrian highway that runs from Volantis to Meereen through the Lands of the Long Summer — a road so ill-reputed that sane travelers add months of sailing to avoid it. The city’s own reputation matches its address: its people are said to be born twisted, monstrous more often than chance allows, as if the Doom’s poison had settled in the soil and the bloodlines both. Whatever the truth of the tales, Mantarys endures where the cities nearer Valyria died, trading warily along a road that eats caravans.",
      "The story brushes it at arm’s length. In the books it is numbered among the powers courted in the war around Meereen — even a city of ill omen has spears to promise — and in the tale’s imagination it serves a darker purpose: proof that Valyria’s fall did not end Valyria’s reach. The Freehold’s roads outlived its dragons, and something in the land they cross remembers. Mantarys is what living downstream of an apocalypse looks like, three centuries on.",
    ],
  },

  "loc:bhonash": {
    paras: [
      "Bhonash is a waystation — a dusty town on the caravan roads that skirt Slaver’s Bay’s hinterland, where the routes from the Rhoyne country and the demon road’s northern reaches meet the trade running toward Meereen and the grass sea. No songs are made about such places, which is rather their function: wells, walls, stables, a market that deals in everything the great cities need moved and nothing they would admit to wanting, and rumor — the true currency of the east — changing hands at every fire. When dragons return to the world, towns like Bhonash hear of it weeks before most kings do. The story’s wars pass it by; the news of them never does.",
    ],
  },

  "loc:oros": {
    paras: [
      "Oros was one of the great cities of the Valyrian peninsula, and it died with its civilization in a single day. When the Fourteen Flames burst, the cataclysm that shattered the Freehold broke the land itself, and Oros went down into fire and water with its towers, its wonders and whatever of its people could not outrun the sky. What remains sits on the ragged coast of the Doom-lands, drowned and broken, visited by no honest ship — the waters around old Valyria are called the Smoking Sea, and sailors hold that men who look on that coast do not come home. Oros has no story anymore; it is part of Valyria’s, a proper noun in the world’s great cautionary tale, one of the names recited when maesters count what the Doom unmade.",
    ],
  },

  "loc:tyria": {
    paras: [
      "Tyria was Oros’s sister in glory and is its sister in ruin — a city of the Valyrian heartland, lost in the hours of the Doom when the peninsula’s fourteen volcanoes opened at once and the proudest civilization the world has known was subtracted from it. The books name Tyria among the cities the catastrophe took, and the naming is nearly all that survives: its walls are under the Smoking Sea’s hazards now, its arts and archives ash, its people a statistic four centuries old. The tale keeps such names deliberately. Valyria the idea — the steel, the roads, the dragon blood — lives all through the story; Tyria is the reminder of the price on the other side of the ledger, a whole city reduced to an entry in the world’s memory of one bad day.",
    ],
  },

  "loc:valyria": {
    paras: [
      "Valyria began with shepherds who found dragons lairing in a chain of volcanoes called the Fourteen Flames, and ended as the greatest civilization the world has known. The Freehold — no king, but forty rival families of dragonlords sharing power — broke the empire of Old Ghis in five wars, shattered the Rhoynar, planted the Free Cities as colonies, and ruled from a capital of impossible architecture where towers were grown from fused stone and sphinxes watched the roads. Its arts have never been equaled since: the dragon-roads straight as spears, the seamless black fortresses, and the spell-forged steel that holds an edge forever — every Valyrian blade in the story, Ice and Longclaw and Oathkeeper and the rest, is salvage from this one drowned forge.",
      "The Doom came four hundred years before the tale, and no one knows why. In the space of hours the Fourteen Flames burst apart, the earth split, the sea rushed in, and every dragonlord, dragon and library in the heartland was burned, drowned or buried — an empire deleted in an afternoon. The peninsula shattered into a scatter of smoking islands amid waters men call the Smoking Sea, where the ruins still glow on dark nights and demons are said to walk; sailors hold that the Doom still rules Valyria, and the proverb that a man who looks on that coast does not come home keeps most of them honest. Of the forty dragonlord families, one survived: the Targaryens, removed to Dragonstone twelve years earlier on the strength of a daughter’s prophetic dream, which is why the story exists at all.",
      "The ruin exerts a pull the story keeps measuring. Gerion Lannister sailed for Valyria to recover his house’s lost blade and never returned; Euron Greyjoy claims to have walked the smoking ruins and lived, and his sorceries invite belief; the maesters quietly note that every attempt to chart the Smoking Sea ends the same way. The show alone actually takes the audience in: Tyrion and Jorah drift through the drowned colossi in the fifth season, reciting a rhyme about the Doom, when the stone men fall on them from the ruins and Jorah takes the touch of greyscale — and above the broken towers, in the story’s most eloquent image, Drogon flies over the wreck of the civilization that made his kind an instrument of empire.",
      "Valyria is the tale’s deep floor — the fact under every other fact. The Iron Throne’s dynasty, the swords the plots turn on, the dragons that reorder every battlefield, even the high tongue of the east: all of it is salvage from the Doom. The story sets its entire game of thrones in the shadow of a power beside which all its kings are provincial, then shows that power as a smoking hole in the map. Every character who dreams of empire is dreaming, whether they know it or not, of Valyria — and Valyria is the story’s standing answer about how empires end.",
    ],
    vs: [
      "The show’s voyage through Valyria is its own invention twice over: in the books no one sails the Smoking Sea and expects to live — Tyrion and Jorah go by the Rhoyne and the open sea — and the stone men who attack them belong not to Valyria but to the Sorrows, the drowned Rhoynish ruin half a continent away. The transplant folds two hauntings into one and hands Jorah the greyscale that, in the novels, strikes Jon Connington — a character the show cut entirely. What the screen gains is the sight of the ruins themselves, something the published books have only ever approached in rumor.",
    ],
  },

  // ================= rivers, roads & wastes =================

  "loc:the-stepstones": {
    paras: [
      "The Stepstones are the wreckage of a bridge between continents. The maesters teach that a land span — the Arm of Dorne — once joined Westeros to Essos, and that the First Men walked it into their new world before it was shattered; the singers say the children of the forest broke it with the hammer of the waters to stop them. What remains is a strewn chain of rocky islands between Dorne and the Disputed Lands, commanding the sea lanes of the narrow sea — which is to say, commanding tolls, which is to say, pirates. Every generation grows its own crop of island kings, and every generation some power has to burn them out; the islands have been claimed by half the Free Cities and held by none of them for long.",
      "History keeps returning to the chain. Here Daemon Targaryen and the Sea Snake fought their grinding private war against the Triarchy in the dragon-kings’ golden age, and here, a generation before the tale, the Band of Nine crowned the last Blackfyre pretender — the War of the Ninepenny Kings, where young Barristan Selmy killed Maelys the Monstrous and closed a rebellion’s bloodline. In the story’s own day the Stepstones belong to the trade’s quieter professionals: smugglers like Davos Seaworth learned their channels by moonlight, and the Lysene pirate prince Salladhor Saan runs them as a family business. Wherever the map pinches, the same trades flourish; the Stepstones are the pinch given a name.",
    ],
  },

  "loc:the-rhoyne": {
    paras: [
      "The Rhoyne is the greatest river in the world, and the world built accordingly. Rising in the hills north of Norvos, gathering tributary after tributary — Noyne and Qhoyne, Lhorulu and Selhoru — she runs the length of western Essos and reaches the sea at Volantis so wide that a man midstream sees no bank in any direction. To the people she raised she was not scenery but a goddess: the Rhoynar built cities of song and fountains on her waters, worshipped Mother Rhoyne, and their water wizards worked her currents and mists in ways the world has not seen since. For a thousand years the river was a civilization — until her daughters caught the eye of the young dragon empire to the south.",
      "The wars with Valyria destroyed the Rhoynar by degrees and then all at once. Prince Garin the Great led a quarter of a million spears against the Freehold, won his battles, and drew three hundred dragons down on his host; the river cities emptied, Chroyane drowned under its curse, and Princess Nymeria gathered the survivors into ten thousand ships and sailed the length of the known world to Dorne, where her people’s laws and stubbornness outlive their river to this day. The Rhoyne herself became a thoroughfare through her own ruins — Volantene river towns on her banks, barge trade on her waters, and the drowned palaces of Ny Sar and the fog-bound Sorrows standing in her stream like unswept graves.",
      "The books give the river the saga’s great travelogue. Tyrion descends her aboard the Shy Maid in the company of a hidden prince and his exiled protector, through mists and ruins and river-lore — the dwarf turtles and the huge Old Man of the River, the Rhoynish orphans singing to the Mother, the shrouded Sorrows where the stone men wait — a voyage that carries half the eastern plot and nearly all its atmosphere. The show never films a mile of it, which makes the Rhoyne the largest thing on the map that screen-only audiences have never seen: the drowned mother of a lost civilization, still carrying the story’s traffic through the middle of the world.",
    ],
    vs: [
      "The river is a casualty of adaptation. The show sends Tyrion from Pentos to Volantis with the journey elided, cutting the Shy Maid, the Rhoynish crew, Young Griff’s conspiracy and the Sorrows in one stroke; Jorah absorbs the greyscale that the river’s stone men deal to Jon Connington in the books, and the encounter is relocated to Valyria. Readers rank the Rhoyne voyage among the novels’ finest stretches; viewers get its plot resolved in a kidnapping and a sea lane.",
    ],
  },

  "loc:chroyane-the-sorrows": {
    paras: [
      "Chroyane was the festival city — the loveliest of the Rhoynar’s river daughters, a place of music, revels and the great span they called the Bridge of Dream. It was Prince Garin’s city, and its fall was its prince’s: when his quarter-million spears had been broken by Valyria’s dragons, the conquerors hung Garin in a golden cage on his own walls to watch his people die. The tale says he called on Mother Rhoyne for vengeance, and the river answered — rising in fog and flood to drown the city, and sending among the victors a curse that turns men to stone by inches. Chroyane has been the Sorrows ever since: a ruin standing in perpetual grey mist, its bridge broken, its palace haunted, the fog itself held to carry the greyscale.",
      "The stone men live there now — the disease’s last stage given shelter, exiled from every port to waste among the ruins, their minds going as their flesh calcifies. Rivermen pole past the Sorrows fast and silent, for the stone men’s touch shares their sentence. In the books the Shy Maid threads the fog beneath the Bridge of Dream and the story collects its toll: stone men drop from the span, Tyrion is dragged under the black water and pulled back from it, and Jon Connington, saving him, takes the grey death into his hand and tells no one — a secret ticking under the whole invasion he leads. Garin’s curse, a thousand years patient, reaches into the story’s present and marks it.",
    ],
    vs: [
      "The show keeps the stone men and discards their address: the attack is moved from the fog-bound Sorrows to the ruins of Valyria, and Jorah Mormont takes the greyscale in place of the excised Jon Connington — his cure at the Citadel replacing the slow doom the books leave uncured. Chroyane itself, curse, bridge and all, never appears on screen; the drowned festival city remains a books-only haunting.",
    ],
  },

  "loc:the-dothraki-sea": {
    paras: [
      "The Dothraki sea is an ocean with no water in it — a thousand leagues of grass, green in spring and gold in drought, rolling unbroken from the Rhoyne country to the Bones without a tree, a hill or a wall to interrupt the horizon. Its people take their name from it and their worldview besides: the khalasars ride it as fleets ride water, following the grazing and the plunder, and the Dothraki hold that the first man rode out of this grass on the first horse. At its uttermost edges, the tales place the ghost grass — pale blades tall as a rider that glow in the dark and will, the crones say, one day cover the world and end it. A people whose sea whispers apocalypse at its shores can be forgiven a certain fatalism.",
      "The grass sea runs on tribute and terror. Cities that pay the khals in gifts are spared; cities that do not become the grass’s new margin — the Century of Blood after Valyria’s fall let the horselords break half the civilizations bordering the sea, and the Free Cities have bribed them ever since, calling the bribes gifts and the arrangement peace. Across this world Daenerys makes her first journey, sold into it as a khal’s bride and remade by it: she learns its tongue, eats the stallion’s heart, buries her husband and her son in its earth, and walks out of a fire at its heart with dragons. The grass sea is the story’s first teacher of its hardest course — power is taken astride, not inherited.",
      "The story keeps returning her to the grass. In the books her last written chapter strands her alone on the sea with a half-wild Drogon, sick and stripped of everything but her name, as Khal Jhaqo’s riders find her — the wheel come round to where she began. The show plays the same return louder: taken by Khal Moro’s khalasar, marched to Vaes Dothrak, and out of the temple fire with every khalasar on the grass at her back. Either way the meaning holds. Westeros gave Daenerys her claim; the Dothraki sea, twice, gives her an army.",
    ],
  },

  "loc:the-red-waste": {
    paras: [
      "The Red Waste is the desert that eats khalasars: a scald of cracked red earth east of Lhazar where the wells are poisoned when they exist at all, and the ruins of dead cities stand as the only proof anyone ever thought better of the place. Daenerys crosses it because the map leaves her nothing else — widowed, her khalasar reduced to a remnant of the old and the sick, every kinder road belongs to rival khals who would take her dragons and her freedom in either order. So she leads her people into the red comet’s path and the waste takes its fee in lives; in the books her handmaid Doreah dies of the crossing there, a debt the show defers so Qarth can collect it more cruelly.",
      "The books grant the desert one mercy: Vaes Tolorro, a dead city of white bones and standing walls with sweet water in its wells, where the remnant shelters while riders go out in three directions to find the living world — and it is the third who returns with envoys from Qarth, drawn by the rumor of dragons. The show compresses the salvation to the city’s gates, but the crossing means the same in both tellings. The Red Waste is where Daenerys’s following is burned down to the people who would follow her anywhere, and where she learns the queenship that precedes thrones: keep your people alive, and they are yours.",
    ],
  },

});
