/* GoT wiki long-form archive — Trident, Vale & the Iron Islands. Original prose; keys match js/characters.js. */
Object.assign(WIKI_EXTRA, {

  // ================= House Tully =================
  "Hoster Tully": {
    paras: [
      "Family, Duty, Honor — Hoster Tully spent a lifetime arranging the riverlands around those three words, in that order. Lord of Riverrun in the last years of Targaryen rule, he governed a country with no mountains, no deserts and no walls: rivers run through it and armies run along rivers, so the Tullys have always survived by being everyone’s friend or everyone’s road. Hoster’s answer was marriage. His daughter Catelyn went north to the Starks, his daughter Lysa east to the Arryns, and the price of both matches was Riverrun’s swords for Robert’s Rebellion — a wedding-day treaty that helped pull down a three-hundred-year dynasty.",
      "He was a shrewd, proud, fundamentally warm man who could be granite where duty was concerned. When his brother Brynden refused the marriage picked out for him, Hoster quarreled with him for decades rather than yield the point. When his ward Petyr Baelish — a minor lordling fostered at Riverrun as a courtesy — reached above his station toward Catelyn, Hoster shipped the boy home and considered the matter closed. It wasn’t, of course. Half the tale’s catastrophes trace back to decisions made in Hoster’s hall by a lord doing exactly what lords were supposed to do.",
      "By the time the story opens he is already failing, eaten from within by a sickness no maester can turn, and the great war of his lifetime is fought across his rivers while he lies abed above it. Riverrun fills with his grandson’s banners; a king is proclaimed in his hall; the Kingslayer is held in his dungeon — and the Lord of Riverrun drifts in and out of milk of the poppy, mistaking his daughter for the dead and the dead for the living. The books give these bedside scenes to Catelyn, and they are among the quietest, saddest chapters in the saga: a strong man’s long subtraction, one memory at a time.",
      "His meaning in the tale is the old order itself. Hoster played the game the way it had been played for a thousand years — daughters as treaties, wards as investments, tolls and bridges and balance — and every bargain he struck honestly became kindling for the fire that came after. The Frey marriage pact, the Arryn alliance, the fostered boy with the mockingbird pin: he built the machine in good faith, and lived just long enough to hear it begin to grind.",
    ],
    vs: [
      "Show viewers never meet Hoster alive: he exists as a funeral — one episode, one boat, one bow passed from nephew to great-uncle. The books keep him dying across two volumes, and give him one of the series’ buried tragedies: in his fever he mutters the word “Tansy,” an apology forty years old, for the moon tea he forced on an unmarried, pregnant Lysa and the choices he made for her afterward. That guilt reframes the entire Arryn storyline — much of what Lysa becomes was manufactured at Riverrun, by a father certain he was doing his duty.",
    ],
    fate: [
      "In the show he dies of his long illness offscreen between seasons, and the third episode of the third season is his farewell: Riverrun gives its lord to the river in the old way, his body sent down the water in a burning boat. Edmure’s flaming arrows fall short again and again until the Blackfish takes the bow from his hands, and the scene doubles as a portrait of the family he left — the earnest heir who cannot quite manage, and the old soldier who does not stay to watch the shaft land.",
      "The books tell it much the same, a chapter or two deeper: he dies abed at Riverrun in A Storm of Swords with Catelyn near, after months of poppy-dulled twilight, and the funeral boat goes down the river trailing fire while his sworn men watch from the walls. Both tellings agree on the essential mercy — of all the lords of the Trident, Hoster Tully alone was allowed to die of nothing worse than time.",
    ],
  },

  "Brynden Tully": {
    paras: [
      "Every family has one relative who declines to be arranged, and House Tully’s was Brynden. When his brother Hoster pressed a Redwyne marriage on him one time too many and called him the black goat of the Tully flock, Brynden — a Tully, whose sigil is a fish — corrected the heraldry and wore the insult forever after: the Blackfish, a black trout on his arms and a closed door on the subject of wives. He left Riverrun rather than submit, and the brothers barely spoke for the better part of two decades.",
      "He was, by common consent, the finest soldier his house ever produced. He won his reputation young in the War of the Ninepenny Kings, and spent his self-imposed exile in the Vale in service to House Arryn, where the books make him Knight of the Gate — commander of the Bloody Gate, the mountain door through which no army has ever forced its way. It says something about the man that the Vale, the most defensible country in Westeros, put its one indispensable chokepoint in the keeping of a foreigner.",
      "When the war comes he goes to his great-nephew, and Robb Stark’s improbable unbeaten streak owes as much to the Blackfish as to any wolf dream. He commands the outriders — the eyes of the army — and it is his screening and scouting that let Robb appear where no Lannister expects him, at the Whispering Wood and after. He is also the closest thing the young king has to a grandfather in the field: blunt counsel, no flattery, and a standing willingness to tell a king he is being a fool, which Robb gets from no one else after Catelyn is set aside.",
      "The Red Wedding kills nearly everyone he loves and misses him — in the show by minutes, a step outside at the right moment; in the books entirely, because he had been left behind to hold Riverrun. Either way the result is the same: the last Tully in arms, holding the last Tully castle, with a dead king to mourn and no intention whatsoever of yielding to the people responsible. The Freys demand Riverrun; the Blackfish keeps it, feeds it, and settles in to outlast them out of spite as much as strategy.",
      "His siege is the old world’s last argument. Jaime Lannister comes to end it and gets a parley across the drawbridge that has become quietly famous — the Kingslayer offering terms, and an old man in fish-scale armor declining to pretend that any of it is honorable. Brynden Tully never breaks an oath, never takes the convenient road, and never wins anything by it; he is what Ned Stark might have been with thirty more years and no children to protect, and the tale keeps him around precisely to show what that costs.",
    ],
    vs: [
      "The two tellings split at the Twins. Show-Brynden attends the Red Wedding and survives it by stepping out to find a tree — a black joke the episode plays completely straight — while book-Brynden was never there, having stayed to hold Riverrun as Robb’s warden. The endings diverge just as sharply: the show closes his story at the fall of Riverrun, while the book siege ends with the Blackfish slipping the net entirely, swimming out beneath the Water Gate and vanishing into the riverlands. In the published books he is still at large — an unaccounted-for Tully with a sword, which several characters have cause to find worrying.",
    ],
    fate: [
      "In the show, the siege of Riverrun ends when Jaime threatens Edmure’s infant son and sends Edmure into the castle to order its surrender as its lawful lord. The garrison obeys; the Blackfish will not. He hurries Brienne and Podrick to a boat, refuses her plea to come north to Sansa — he has a castle to die in, he says, more or less — and is cut down fighting, offscreen, sword in hand in the halls where he was born. The show grants him the death he would have picked from a catalogue.",
      "The books stage the same siege with a different last move: when Edmure yields the castle, the Blackfish is simply not among the prisoners. He escapes by the river that named his house and disappears. As of the published books he is alive, whereabouts unknown — the rare character whose show death has no book counterpart at all, only an empty cell and a furious Frey garrison.",
    ],
  },

  "Edmure Tully": {
    paras: [
      "Edmure Tully has the misfortune to be a decent man in a story that keeps mistaking decency for weakness. Hoster’s only son, heir to Riverrun, he grows up between a formidable father and two formidable sisters, warm-hearted, brave enough, and forever half a step behind events. What distinguishes him from nearly every other lord in the tale is where his instincts point: when the war comes to the Trident, Edmure opens his lands and his gates to the smallfolk fleeing it. Other lords count spears; Edmure counts mouths, and considers them his.",
      "His war record is the tale’s cruelest joke about good intentions. Charged with holding Riverrun while Robb strikes into the west, he sees the Mountain’s raiders coming, fights them off at the fords — the show stages it as the Battle of the Stone Mill — and returns proud of the first Tully victory of the war. Robb’s face tells him the truth: he was supposed to lose ground, not hold it. The king had been baiting Tywin west into a trap, and Edmure’s gallant, bloody, successful defense sprang it early and saved the man who would sign his family’s death warrant. He did everything right, in the only battle where right was wrong.",
      "The marriage that follows is his apology and his family’s ransom. Robb broke his own pact with the Freys, so Edmure is handed the bill: wed a girl he has never seen, at the Twins, to mend the alliance. Roslin turns out to be lovely and kind — Lord Walder’s one genuine mercy, deployed as anesthetic — and Edmure is escorted to the bedding while the Rains of Castamere start up in the hall. He survives the Red Wedding precisely because he was its pretext: a groom is worth more alive, as a hostage, than dead.",
      "The years in a Frey cell hollow him into the tale’s portrait of survivor’s shame. His son is born to a father in chains; his one appearance of consequence comes at the second siege of Riverrun, where Jaime Lannister quietly explains what will happen to everyone Edmure loves unless the castle opens its gates. Edmure walks his uncle’s drawbridge alone and orders the surrender — the correct choice, the merciful choice, and the one that costs the Blackfish everything — and the story declines to tell us whether to forgive him, because he has never once forgiven himself.",
      "He gets one last scene, and it is entirely Edmure: at the great council in the Dragonpit he rises, smooths his coat, and begins a speech offering himself for the throne — experience, statecraft, the wisdom of hard years — until his niece Sansa tells him, kindly, to sit. He sits. The lords choose someone else. He goes home to Riverrun, to Roslin and his son, alive at the end of a story that killed nearly everyone stronger, prouder and cleverer than he is. There is a moral in that, and Edmure — give him this — would be the first to laugh at it.",
    ],
    vs: [
      "The books are somewhat kinder to his generalship and considerably harder on his ending. Book-Edmure’s battle of the fords is a genuine feat of arms — Tywin’s host thrown back at every crossing — undone only by the trap nobody told him about; several readers have noted that if Robb had shared his plans with his own castellan, the war might have gone otherwise. After yielding Riverrun in the books, Edmure is not freed but transferred: he is last seen being carted off toward Casterly Rock, a permanent guest of the Lannisters, with Jeyne Westerling traveling under the same guard. No Dragonpit speech awaits him in the published books — just the long road west, and a Frey wife and son still at the Twins.",
    ],
  },

  // ================= House Arryn =================
  "Jon Arryn": {
    paras: [
      "The whole tale begins with an old man refusing to commit a murder. Jon Arryn, Lord of the Eyrie and Defender of the Vale, had fostered two boys at his mountain seat — Eddard Stark and Robert Baratheon — and when the Mad King demanded their heads, Jon raised his banners instead. Robert’s Rebellion is named for the man who won its battles, but it was declared by the man who would not hand over his wards; every crown, war and grave that follows descends from that refusal. His house words are As High as Honor, and he is one of the few characters in the story who simply meant them.",
      "He then spent seventeen years as Hand of the King doing the hardest work in Westeros: governing on behalf of a man who would not. Robert hunted, feasted, whored and spent; Jon Arryn balanced, borrowed, soothed and stitched, holding together a peace that existed mostly because he kept renewing it by hand. The price of the rebellion had included his own marriage — Lysa Tully, a girl younger than his memories, wed for Riverrun’s swords — and the match brought him little warmth and a string of griefs before it produced one frail son, born when his father was already old.",
      "His last season of life was spent asking a dangerous question. Something set him digging through the crown’s pedigrees — a fat book of lineages, visits to Robert’s scattered baseborn children, quiet conferences with Stannis Baratheon — and the answer he assembled was the realm’s most explosive fact: the black-haired bastards were Robert’s, and the golden-haired heirs were not. His final reported words, “the seed is strong,” were the finding read aloud with his last breath.",
      "Jon Arryn is the rare character whose importance is entirely posthumous and entirely central. His death is the story’s first domino: it summons Ned south, it puts Lysa’s poisonous letter on the road to Winterfell, it leaves the realm without its one honest broker at the exact moment the truth he found begins to surface. The tale opens with his funeral rites already said — and then spends years teaching everyone, too late, what the old man had been holding up.",
    ],
    vs: [
      "Both tellings agree on the essentials; the books simply furnish the investigation. There Jon Arryn works in tandem with Stannis, and the trail is strewn with corroborating detail the show trims: the suspiciously new-made knight Ser Hugh of the Vale, his former squire, who dies conveniently on the Mountain’s lance at the Hand’s own memorial tourney; and Grand Maester Pycelle’s later confession that he deliberately let the Hand’s sickness run its course, sending away the healer who might have saved him, because a dying man’s secrets die with him. The show gives you the corpse in the first hour; the books give you the autopsy across four volumes.",
    ],
    fate: [
      "He died fast for a healthy man — a burning fever that ate him in days, in both tellings, with his wife at his bedside and his last strength spent on four words about seed. The realm was told it was natural. Winterfell was told, by Lysa’s smuggled letter, that it was the Lannisters. Both were lies, and the second was the more effective: Ned Stark rode south to catch his friend’s killers and walked into the machine that killed him.",
      "The truth surfaces at the Moon Door years later, in the show and the books alike: Lysa herself poisoned her husband with the Tears of Lys, at the urging of Petyr Baelish, who then dictated the letter blaming the Lannisters. Jon Arryn was murdered by his own wife for the love of a man who wanted a war — not because of what he knew, though what he knew was fatal, but as the opening move of Littlefinger’s long game. The books add Pycelle’s cold assist, withholding care once the fever took hold. The most honorable man of his generation died of other people’s ambitions, three separate ways at once.",
    ],
  },

  "Lysa Arryn": {
    paras: [
      "Lysa Tully grew up at Riverrun as the second daughter — second in age, second in beauty, second in her father’s calculations, and second in the heart of the boy she loved. Petyr Baelish, the minor ward with the quick tongue, wanted Catelyn; Lysa wanted Petyr; and out of that simple, unrequited geometry the story eventually builds two wars. She gave herself to him, loved him without reservation or return, and never in her life recovered from the discovery that love is not a thing you can earn by wanting it hardest.",
      "What her family did next made her. The books lay it out plainly: when Lysa was found to be carrying Petyr’s child, Lord Hoster forced moon tea on her — the drug called tansy — and then married her, damaged goods discreetly repackaged, to a widower older than her father. The Arryn marriage was duty in its purest form: Jon needed Riverrun’s swords, Hoster needed the stain covered, and nobody needed Lysa to consent to anything. Years of stillbirths and miscarriages followed in a cold mountain castle, until one frail boy finally lived — and Lysa, who had lost every other thing she ever held, gripped him hard enough to bruise.",
      "Widowhood turned her strange in ways the Vale learned to tiptoe around. She fled the capital with her son the moment her husband was dead, shut the Eyrie’s gates, and refused every summons of the war — no swords for her nephew Robb, none for anyone, the Vale’s knights rusting in the mountains while the riverlands burned. Visitors found a nervous, imperious woman nursing a boy well past nursery age, holding court from a weirwood throne beside a hole in the floor. Tyrion Lannister, delivered to her by Catelyn, got the full experience: a sky cell, a farce of a trial, and the Moon Door yawning under a sellsword’s duel.",
      "Then Petyr Baelish came back, and Lysa got, at last, exactly what she had always wanted — which is the cruelest thing the story ever does to her. She married him in indecent haste, giddy as the girl she never got to be, unable to see that she had been a tool of his for years: the poison, the letter, the war itself had all been played through her willing hands. Her reward was to watch her new husband look at her niece Sansa the way he had once looked at her sister.",
      "Lysa matters because the story’s great secret runs through her twice. Hers were the hands that killed the Hand of the King and hers the pen that blamed the Lannisters — the two acts that set every army marching — and she committed both for a man incapable of loving her back. She is the tale’s saddest study in what the marriage market does to the people it trades: not a villain born, but a girl bartered, drugged, and shelved until the damage compounded into something dangerous. Her sister got the songs. Lysa got the Moon Door.",
    ],
    vs: [
      "The bones of her story match across the tellings, but the books supply the childhood that explains her — the tansy, the forced marriage, the aborted child, all confessed in her final raving at the Moon Door — where the show sketches the obsession and lets the history stay dim. The aftermath differs too: in the books Littlefinger frames the singer Marillion for her death and extracts a confession, while the show has him talk his way past the Vale lords with Sansa’s tearful, calculated testimony as his shield. Book-Lysa is also a shade more dangerous — her jealousy of Sansa turns physical at the Moon Door itself, snow swirling into the hall while she screams the whole conspiracy aloud.",
    ],
    fate: [
      "She dies at the Moon Door she loved to feed. In the show it comes moments after she has watched Petyr kiss Sansa in the snow: she drags her niece to the open door, raving, until Petyr talks her gently back — and then tells her he has only ever loved one woman, her sister, and pushes her through. In the books the scene runs the same course at greater length, Lysa confessing the poisoning of Jon Arryn and the lying letter in front of the one witness who matters, before Petyr pries her fingers loose with a single word — “only Cat” — and lets the sky have her.",
      "Either way, the man she killed for was the man who killed her, and her death is the story’s first full confession: everything the realm believed about the war’s beginning was authored by the two people standing at that door. Only Sansa hears it, which is the point — from that moment the girl knows exactly what her protector is.",
    ],
  },

  "Robin Arryn": {
    paras: [
      "The Lord of the Eyrie is six years old, breastfed, and enthusiastic about executions — that is the realm’s introduction to Robin Arryn, and it is not an unfair one. Born late to an old father and a smothering mother, sickly from the start and given to shaking fits, Robin grows up as the most protected child in Westeros in every sense: a mountain fortress no army has ever taken, a mother who never lets him out of arm’s reach, and a hole in the floor of his hall through which bad men are made to fly for his entertainment. He is what happens when a child’s every want is granted and every strength is postponed.",
      "Power, for Robin, is a thing other people exercise in his name while being careful of his moods. His mother rules the Vale around him; after her death, Littlefinger rules it through him, palming the boy’s trust with gifts and endearments while the Vale lords grind their teeth. The show then does something almost optimistic with him: Yohn Royce takes him to Runestone to be fostered — to learn, at last, to hold a sword and sit a horse badly rather than not at all — and it is Robin, flattered and steered by Littlefinger, who nods the Knights of the Vale north to the battle that saves Winterfell. The boy who could not leave his mother’s lap tips the largest battle in the North without ever leaving the Vale.",
      "By the tale’s end he appears at the great council in the Dragonpit, grown, composed, and startlingly presentable — a lord among lords, given a vote in choosing a king. The books, further back in time, keep him smaller and in far more danger: sickly little Robert Arryn, called Sweetrobin by the cousin he doesn’t know is a Stark, dosed with sweetsleep to still his shaking fits by a maester who knows every dose shortens the road, while Littlefinger cultivates the boy’s heir with visible patience. In both tellings his meaning is the same: the Vale’s neutrality, its armies and its impregnability all hang on the health of one fragile child — and everyone at his court has done that arithmetic.",
    ],
    vs: [
      "The show gives Robin an arc — coddled wreck to fostered lordling to poised young council-voter — while the books hold him at the edge of a knife. There his fits are managed with sweetsleep, a drug that kills by accumulation; his named heir, Harrold Hardyng, is being groomed and married forward by Littlefinger with unmistakable intent; and his one protector of consequence is a girl called Alayne Stone whose real name he never learns. The book reader is invited to doubt the boy will see manhood; the show viewer watches him outlive the man who was measuring his coffin.",
    ],
  },

  "Yohn Royce": {
    paras: [
      "House Royce of Runestone is older than the Andals, and Bronze Yohn dresses the part: over his mail he wears a suit of bronze plate thousands of years old, graven with the runes of the First Men that are said to ward its wearer from harm. The man inside the armor is of a piece with it — big, blunt, proud, honorable to the point of inconvenience, and the most powerful bannerman the Arryns have. In a story where cleverness is the winning suit, Yohn Royce plays honesty every hand, and keeps his seat at the table anyway.",
      "The tale taxes his house early and often, mostly offstage. His youngest son Waymar took the black and rode into the haunted forest as a proud young ranger — the very first scene of the entire story is Waymar Royce meeting the Others in the snow. Another son, Robar, rides south in the books to wear Renly’s rainbow cloak and dies for it. Bronze Yohn spends the saga as a father whose sons keep leaving Runestone for other people’s stories and not coming back, which may explain the gruff protectiveness he develops toward other people’s children.",
      "In the show he is the Vale’s conscience and Littlefinger’s least manageable problem. He distrusts the mockingbird from their first scene, says so in open council with a directness that nearly gets him killed, and swallows his pride to serve the Arryn boy regardless — taking Robin to Runestone to make something of him, leading the Knights of the Vale north when Littlefinger’s schemes finally point in a useful direction. He fights at the Battle of the Bastards, stands through the Long Night, and ends the story where he has quietly been for three seasons: at Sansa Stark’s shoulder, the old bronze constant of her rise to a crown.",
      "The books give him a grander, sadder role: leader of the Lords Declarant, the confederation of Vale lords who band together to pry Sweetrobin out of Littlefinger’s custody. It is the honest man’s coup, conducted honestly — declarations, parleys, ultimatums — and Littlefinger dismantles it with a year’s grace, a bought sellsword scare and a handful of favors, because Bronze Yohn insists on fighting a duel of honor against a man playing an entirely different game. He is the tale’s standing demonstration that integrity without cunning holds castles, not capitals — and that it outlasts cunning anyway, more often than the clever expect.",
    ],
    vs: [
      "Show and book Royce are the same man at different altitudes. The show makes him Sansa’s gruff marshal and gives him the on-screen victories; the books make him the great lord of the Vale’s opposition, whose Lords Declarant storyline — six proud banners against one smiling upstart — is among the threads the adaptation cut entirely. The books also draw the family lines the show leaves unspoken: the doomed ranger of the saga’s first page is Bronze Yohn’s own son, which means the story’s very first casualty was a Royce of Runestone, and his father never learns how it happened.",
    ],
  },

  // ================= House Greyjoy =================
  "Balon Greyjoy": {
    paras: [
      "Balon Greyjoy ruled a kingdom of rock and salt spray and was certain it was the better part of the world. Lord Reaper of Pyke, head of a house whose words are We Do Not Sow, he was raised on the Old Way — the creed that iron men pay the iron price, taking what they own with axe and boarding-hook rather than coin — and he took it not as nostalgia but as policy. Lean, hard, humorless, flint all the way through: of the four sons of Quellon Greyjoy who survive into the tale, Balon is the one with the crown, the grievance, and the least imagination.",
      "Nine years before the story opens he wagered everything on the Old Way and lost. Judging Robert’s new-won throne to be weak, Balon crowned himself King of the Iron Islands and rebelled; the war made his brother Euron’s cunning and Victarion’s axe briefly famous, burned the Lannister fleet in its harbor, and then collapsed — the Iron Fleet smashed off Fair Isle, Pyke stormed, two of Balon’s three sons dead in the fighting. Robert let him live and keep his lordship. The price was his last boy: Theon, carried off to Winterfell as Eddard Stark’s ward and hostage. Balon spent the next decade on his sea-tower nursing the arithmetic of that humiliation.",
      "When the story brings Theon home with an offer of alliance from Robb Stark — a crown for the Iron Islands in exchange for ships against the Lannisters — Balon delivers one of the tale’s coldest homecomings. He sneers at his son’s bought finery, mocks the gold chain paid for with coin instead of blood, and makes it clear that the boy standing before him is a Stark creature in Greyjoy skin. He will not be handed a crown by a wolf pup, he says; he will pay the iron price. Then he takes the crown anyway and strikes not south at the Lannisters but north — at the undefended coast of the family that raised his son.",
      "As strategy it is almost perfectly self-defeating, and the tale knows it. The North’s coasts can be raided but never held; the ironborn seize Moat Cailin, Deepwood Motte and — through Theon’s freelancing — Winterfell itself, and gain from all of it nothing but the undying hatred of the mainland and the ruin of Balon’s own son. His daughter sees it clearly; his captains see it; Balon sails on regardless, because the point was never conquest. The point was to be a king again, and to owe it to no one.",
      "His meaning in the story is the dead hand of the past. Balon commands men to be what their grandfathers were, in a world that has moved on; he demands a son’s loyalty while despising everything the boy had to become to survive; and every Greyjoy in the tale is bent around the shape of his approval — Theon breaks chasing it, Yara hardens earning it, and his brothers inherit the wreckage of it. Twice a king, never a conqueror: the driftwood crown fit him exactly.",
    ],
    vs: [
      "The tellings agree on the man and differ on the murder. The show puts his death on screen and in the family: a confrontation on a rope bridge in a storm with the exiled brother he banished, ending with Balon thrown to the sea. The books stage the same fall with no witness at all — the old king crossing his swaying bridges in a gale as he always did, found broken on the rocks days before Euron’s Silence just happens to sail into Lordsport — and let the ironborn do the math themselves. Aeron believes his brother arranged it; readers have gone further, noting how conveniently death travels ahead of the Crow’s Eye. The show spends the ambiguity to buy a scene; the books keep it, and it curdles the whole kingsmoot.",
    ],
    fate: [
      "In the show, Balon meets a hooded figure on one of Pyke’s rope bridges in the middle of a storm and finds his brother Euron under the hood — the brother he exiled, come home smiling. Balon tells him to get off his islands; Euron mocks the old man’s failed rebellions, announces himself as the storm, and hurls him from the bridge into the sea their god lives in. The kingsmoot that follows crowns the killer.",
      "In the books he simply falls — a frayed rope bridge, a howling gale, a body washed up bloated and broken two days later — and the timing does the accusing: the Silence, crewed by mutes and captained by his banished brother, appears the very next day. No one saw anything. On the Iron Islands, where the Drowned God takes whom he pleases, hardly anyone believes it was the god. Either way the throne of salt and rock is empty, and every terrible thing the Greyjoys do afterward pours through the gap he leaves.",
    ],
  },

  "Euron Greyjoy": {
    paras: [
      "Euron Greyjoy arrives late in the tale and instantly reorganizes it around himself, which is exactly how he would want it described. Third of the Greyjoy brothers, banished by Balon years before the story starts for a crime against Victarion’s wife, he spent his exile as the most feared reaver in the known world — and comes home within a day of his brother’s convenient death, all smiles, to ask what the fuss is about. Where Balon was flint, Euron is quicksilver: charming, blasphemous, theatrical, and empty in a way that men mistake for depth until it is far too late to matter.",
      "The show’s Euron announces himself on a rope bridge in a storm, killing his brother mid-sentence, and campaigns for the driftwood crown on a platform of remarkable frankness: yes, he did it, and what has anyone else here ever finished? He wins the kingsmoot over Yara and Theon by promising to build a thousand ships and marry the dragon queen, then discovers his niece and nephew have stolen his best fleet overnight. His response sets his tempo for the rest of the series — build more, sail faster, and fall on his enemies precisely where they feel safest.",
      "What follows is the most efficient villain streak of the late seasons. He shatters Yara’s fleet in a night action lit by burning ships, kills two Sand Snakes with their own weapons, and drags his niece to King’s Landing as a gift for Cersei — a queen he courts with the cheerful persistence of a man who has decided the Iron Throne is a marriage away. He ferries the Golden Company across the Narrow Sea, ambushes Daenerys from behind a rock shadow and shoots Rhaegal out of the sky with a scorpion bolt, and beds the queen he serves. If the show’s Euron has a creed, he states it plainly enough: he wants everything, mostly because taking it from other people is the only thing that entertains him.",
      "The books’ Euron is another order of being entirely. The Crow’s Eye, they call him: a blue-lipped drinker of shade-of-the-evening, one eye covered by a patch no man asks about, captain of a red ship called Silence crewed entirely by men whose tongues he has torn out. He claims to have sailed the Smoking Sea and walked the ruins of Valyria; he keeps Valyrian armor, captive warlocks, and a cracked dragon horn taller than a man, won — he says — from the ashes of the Doom. Where show-Euron wants a throne, book-Euron talks like a man who has seen something behind the world and means to introduce everyone to it.",
      "His book campaign is conquest as dark theater. At the kingsmoot beneath Nagga’s ribs he trumps every claim with plunder and blasphemy, has the hellhorn blown until its blower dies of it, and promises the ironborn nothing less than dragons and the world entire. Crowned, he binds the captains with gifts and salt wives, sends Victarion east to fetch Daenerys — a wooing he fully expects to end in betrayal, his brother’s or his own — and hurls the Iron Fleet at the Reach, stripping the Shield Islands and setting his eye on Oldtown, where the Citadel keeps its glass candles and its secrets. The sample chapters ahead of the next book go darker still: priests lashed to prows, visions of a kraken-crowned god on a throne of skulls, a man preparing not a battle but a ritual.",
      "Between the two versions, Euron is the tale’s best argument that adaptation is interpretation. The show sharpened him into a killer with a fleet; the books grow him toward something like an apocalypse with a sense of humor. What both agree on is the essential vacancy at his center — brother, god, queen, crown, none of it is the point. The point is that nothing has ever been able to tell Euron Greyjoy no and make it stick, and he has organized his entire life around keeping it that way.",
    ],
    vs: [
      "No character diverges more between page and screen. The show’s Euron is a leather-clad corsair with quips — a knowing, almost modern rogue whose ambitions run to fleets, crowns and Cersei’s bed. The books’ Euron is a sorcerer-king in embryo: the shade-of-the-evening, the Valyrian plunder, the dragonbinder horn, the mute crew, the hints of an eldritch design behind the piracy — none of it survived the adaptation. Even his election differs in texture: the show’s kingsmoot is a brisk shoreline vote among three speakers, while the books stage a great assembly on Old Wyk beneath the bones of Nagga, claimants and priests and the horn’s scream, with Aeron’s whole faith arrayed against the Crow’s Eye and failing.",
      "Their endings part company completely. Show-Euron dies on the beach beneath the falling Red Keep; book-Euron, alive and ascendant in the published volumes, has just baited the fleets of Oldtown into battle while he readies something worse. Readers waiting on The Winds of Winter regard him, with reason, as the books’ most dangerous living man south of the Wall.",
    ],
    fate: [
      "The show kills him with the same swagger he lived by. Thrown into the sea when Daenerys annihilates his fleet in Blackwater Bay, he washes ashore beneath the collapsing Red Keep just in time to find Jaime Lannister hurrying to reach Cersei — and attacks him for the pure sport of it, grinning through a duel amid the falling ash. He deals Jaime mortal wounds; Jaime drives a sword through his belly and leaves him. Euron dies alone on the sand, delighted with himself to the last, crowing that he is the man who killed Jaime Lannister. He wasn’t — Jaime dies of a falling city, holding his sister — but Euron never let truth spoil a good story.",
      "In the published books he is alive, crowned, victorious and accelerating — no death scene awaits him yet, only the battle off Oldtown and whatever the horn and the visions are for. Whatever end Martin has planned, readers broadly agree the beach brawl was written for a much smaller man.",
    ],
  },

  "Victarion Greyjoy": {
    paras: [
      "Victarion Greyjoy is the strongest man in his family and the least equipped to notice what his family is. Lord Captain of the Iron Fleet, master of the Iron Victory, he is a tower of plate and piety who has organized his entire existence around obedience — to Balon, to the Drowned God, to the Old Way — because obedience spares a slow man the agony of deciding. He fought through the Greyjoy Rebellion with distinction, burned the Lannister fleet at anchor in Lannisport, and asked for nothing afterward but to keep sailing where his king pointed. Among the tale’s point-of-view characters he is unique: a genuinely dangerous man with almost no interior resources whatsoever.",
      "The wound at his center bears his brother’s fingerprints. Years before the story, Euron seduced — by Euron’s telling — Victarion’s wife and left her carrying his child; Victarion, bound by the ironborn’s one inviolable law against kinslaying, could not touch him. So he beat the woman to death with his own hands instead, wept over it after, and has carried both the grief and the unspendable hatred ever since. Balon’s exile of Euron was as much for Victarion’s sake as anyone’s. When the Crow’s Eye sails home over Balon’s fresh corpse, Victarion is the one man on the islands who fully understands what has come back — and still cannot lift a hand against him.",
      "At the kingsmoot on Old Wyk he makes his claim — sound, dull, dutiful, exactly like him — and watches his brother buy the crown with plunder and a hellish horn. What follows is the tale’s bleakest comedy of servitude: the new king hands Victarion the Iron Fleet and an errand, sail to Slaver’s Bay and win Daenerys Targaryen as Euron’s bride. Victarion accepts, and somewhere in the long miles east resolves on his one act of rebellion in a lifetime of service — he will take the dragon queen for himself, horn and all, and let the Crow’s Eye choke on it.",
      "The voyage remakes him into something stranger than he was. Storms scatter his fleet; a festering sword-wound in his hand is healed — transformed — by the red priest Moqorro, leaving the arm charred black and smoking, stronger than before; and the captain who set out serving one god arrives hedging his bets between two, giving the Drowned God his due and R’hllor his burnings. The published books leave him at the mouth of Slaver’s Bay with the dragon horn aboard and the battle of Meereen forming ahead — an unimaginative man sailing an occult weapon toward a dragon queen, on an errand of betrayal he thinks of as justice. Nothing about that sentence ends quietly, and readers have been waiting years to find out how loudly it doesn’t.",
    ],
    vs: [
      "Victarion never existed on screen — the show has no third Greyjoy brother, and his functions were split among the survivors: the fleet command and the eastern expedition went, in altered form, to Euron, while the kingsmoot lost its dullest and most honest claimant. What the adaptation loses with him is deliberate: his chapters are the books’ study of the ironborn as they see themselves — pious, wronged, magnificent — written from inside a skull with no irony in it, while every reader sees the manipulation he cannot. Cut him and the ironborn become a fleet; keep him and they are a religion with ships.",
    ],
  },

  "Aeron Greyjoy": {
    paras: [
      "The youngest of Balon’s brothers was, in his first life, the least of them: Aeron the drunk, Aeron of the japes, a wineskin with a man attached, famous the length of the islands for nothing anyone would put on a grave marker. The Greyjoy Rebellion ended that man off Fair Isle, where his ship went down and the sea took him. What the sea gave back was somebody else. Reborn on the shore — drowned, in the ironborn manner of speaking, and returned — he gave himself wholly to the Drowned God, and the wastrel became the Damphair: seaweed-haired, salt-soaked, clad in roughspun, the sternest holy man the Iron Islands have produced in generations.",
      "His ministry is the Old Way with the bark still on it. He walks the shores of the islands drowning men in the cold surf and pumping the life back into them, dispensing the faith’s central promise — what is dead may never die, but rises again, harder and stronger — with a waterskin of seawater at his hip in place of the wine. The smallfolk and the drowned men love him; the lords find him useful and uncomfortable in equal measure; and Aeron, who once feared nothing because he noticed nothing, now fears exactly one thing in the world, and it sails a red ship.",
      "His brother Balon’s fall makes Aeron briefly the most powerful man on the islands, and he spends that power on one great gamble: reviving the kingsmoot, the drowned-out ancient custom by which the ironborn chose their kings on the holy shore of Old Wyk. His purpose is transparent — anyone but Euron, the godless brother whose step on a stair was the sound of Aeron’s childhood terrors — and the gamble fails spectacularly. The Crow’s Eye comes to the moot with plunder, promises and a horn out of Valyria, and the assembly Aeron summoned to stop him hands him the driftwood crown instead.",
      "After the moot the Damphair disappears from the page — gone to raise the faithful against the godless king, the islands assume — and the show barely needed him at all: he appears to re-drown Theon on the shore of Pyke in the early seasons, and later to preside over the beachside kingsmoot and pronounce the drowned blessing over the brother he could not prevent. In both tellings his significance is the same and easy to miss: Aeron is the ironborn’s conscience, the one man who believes every word of the creed the others merely exploit — and the tale’s quiet warning about what happens to true believers when something older and hungrier than their god comes home.",
    ],
    vs: [
      "On screen Aeron is two scenes and a liturgy; on the page he is a point of view, and the difference is the whole ironborn religion. His chapters open the islands’ story in the fourth book — the drownings, the creed, the moot politics, the dread of the rusted hinge that marks his memories of Euron — and they are the closest the saga comes to writing from inside a faith. A chapter released ahead of The Winds of Winter carries him further into the dark, a prisoner of his brother’s ship and his brother’s visions, and readers who have seen it tend to speak of it in the tone people reserve for things they wish they could unread.",
    ],
  },

  "Yara Greyjoy": {
    paras: [
      "The first time the story shows us Yara Greyjoy, she is a stranger at the Lordsport docks offering a cocky young lordling a ride to the castle — and letting Theon fumble at her the whole way up, saying nothing, because the joke is better the longer it runs. In Balon’s hall the punchline lands: the woman he pawed is his own sister, and while he was learning table manners at Winterfell she was learning to captain ships, command reavers and hold their father’s attention. One scene, and the show has drawn the whole family: the heir who left, the daughter who stayed, and the old man who long ago decided which of them counted.",
      "She is everything the ironborn say they respect, inconveniently packaged. When Balon strikes at the North it is Yara who gets the real command — thirty longships against Deepwood Motte, taken clean — while her brother is thrown a fishing village and a sneer. She leads from the deck, keeps her crews by competence rather than blood-right, and delivers the tale’s hardest-headed loyalty: she sails to the Dreadfort with fifty of her best to pull Theon out of Ramsay’s kennels, and when the wreckage that answers to the name Reek refuses to leave, she looks at it and tells her men her brother is dead. It is cruel, accurate for the moment, and exactly what a captain says to stop good men dying for a ghost.",
      "Her father’s death puts the driftwood crown within reach, and at the kingsmoot she claims it — the first woman ever to stand for it, with Theon, restored to something like himself, standing witness for her instead of for his own claim. Their uncle Euron takes the crown anyway, with bluster and a confessed murder, and Yara does the arithmetic of surviving him in about a minute: she and Theon steal the best ships of the Iron Fleet that same night and sail for the one power in the world that might outbid a madman.",
      "The alliance she strikes with Daenerys Targaryen is a small landmark in the tale — two women, both bypassed heirs of violent houses, dealing fleet-for-crown across a map table without a marriage in sight. Yara’s price for the Iron Islands’ independence is steep in the other direction: the reaving stops, the Old Way dies, her people become sailors instead of thieves. She pays for the pact quickly — Euron falls on her fleet in the night, kills her allies, and drags her to King’s Landing lashed to his prow — and endures her uncle’s captivity until the brother she once wrote off as dead boards a ship under fire and cuts her loose. The nod she gives Theon afterward carries more weight than most of the story’s speeches.",
      "She spends the last war retaking the Iron Islands in Daenerys’s name, holding them ready as a refuge that is never needed, and comes to the Dragonpit council still loyal to her dead queen — pointedly unenthusiastic about pardoning the men who killed her. She leaves as she began: ruling Pyke, the first woman to hold it in her own right, her family reduced to a name she carries alone. The books tell her story under another name, Asha, and give it different roads — but on either page she is the answer to the Greyjoy question nobody at the kingsmoot wanted to hear: the best man for the driftwood crown was never a man.",
    ],
    vs: [
      "The rename is the famous difference — Asha of the books became Yara on screen, reportedly to keep casual viewers from tangling her with the wildling Osha — but the divergence runs deeper than a syllable. Book-Asha never allies with Daenerys, never falls into Euron’s hands, and never sails a rescue to the Dreadfort; her war takes her from a failed kingsmoot bid to capture by Stannis Baratheon in the northern snows, a storyline the show never touches. The show’s Yara gets the fleets, the pacts and the endgame; her book counterpart gets the interiority — and readers wanting the fuller portrait should read her under her own entry, and her own name.",
    ],
  },

  "Asha Greyjoy": {
    paras: [
      "Asha Greyjoy — Yara, if you met her on television — grew up on Pyke as the child who stayed, and made staying into a career her father could not ignore. With her brothers dead in the rebellion and Theon hostage in the North’s keeping, Balon raised his daughter to the work sons do: ships, salt, steel. By the time the story reaches the islands she captains the Black Wind, dresses as she pleases, carries an axe at one hip and dirks at the other — her husband and her suckling babes, she calls them, to the horror of properly married ladies — and commands the loyalty of crews who would follow her over the world’s edge because she has never once given them a stupid order.",
      "Her introduction in the books is one of the saga’s great cold-blooded jokes. Theon, homeward bound and full of himself, meets a shipwright’s pretty wife called Esgred on the Lordsport road and spends the ride to Pyke flirting outrageously and boasting of his prospects — only to watch “Esgred” stroll into their father’s hall and take her seat as his sister. She let him talk. She always lets people talk; it is the cheapest intelligence-gathering there is, and Asha has never paid the gold price for anything she could have free.",
      "In her father’s war she is the competence the strategy doesn’t deserve. She takes Deepwood Motte and — unlike her brother at Winterfell — holds it, garrisons it, and grasps the truth she later carries to the kingsmoot: the ironborn can raid the North forever and rule it never. Her claim at the moot beneath Nagga’s ribs is built on exactly that heresy — peace, trade, land the ironborn can actually keep — and the captains cheer her nerve, laugh at her sense, and crown her uncle Euron’s promises of dragons instead. Wit, in her experience, loses to spectacle roughly always.",
      "Euron’s crown makes the islands unsafe for her, a point he makes with characteristic humor by marrying her off in absentia to a fat ancient of a lord, with a seal standing proxy at the wedding. Asha declines to be a prize — she slips home to Deepwood Motte and her diminished crews, and is holding it still when Stannis Baratheon comes down out of the hills with his clansmen and takes the wood, her men, and her. The march on Winterfell that follows is told partly through her eyes: the snows, the burnings, the king who will not turn back — and at its end, the reunion that breaks her harder than capture did, with the flinching, white-haired thing the Boltons made of her little brother.",
      "As the published books leave her, she is Stannis’s prisoner and something closer to his counselor, camped in the snow before Winterfell with Theon beside her and the battle unfought. Her meaning in the saga has held steady from her first chapter: Asha is the argument the Iron Islands keep refusing to hear — that the Old Way is a suicide pact with better songs — and the tale’s driest demonstration that being right is not a power. The show sailed her under the name Yara into alliances and rescues the books never staged; the books keep Asha where Martin seems to want her, in the cold, clear-eyed, still alive, still outvoted.",
    ],
    vs: [
      "Asha’s book road and Yara’s show road part ways almost completely after the kingsmoot. The books send her not to Daenerys but into Stannis Baratheon’s hands at Deepwood Motte, then on the death-march toward Winterfell as prisoner and point-of-view — snowbound chapters the show never adapted, including her forced proxy marriage and her reunion with the ruin of Theon in the enemy camp. The show’s counterpart storylines — the Targaryen pact, Euron’s prow, the brother’s rescue — have no book equivalent at all. She is also, in the books, half a Harlaw: her mother’s kin at Ten Towers, above all her uncle Rodrik the Reader and his famous library, give her a hinterland of allies and irony the screen never had time to visit.",
    ],
  },

  "Theon Greyjoy": {
    paras: [
      "Theon Greyjoy spends the whole tale being asked the one question he cannot answer: whose son are you? Taken from Pyke at ten as the price of his father’s failed rebellion, he grows up at Winterfell as ward and hostage both — raised beside Robb Stark as near enough a brother, trained and fed and half-trusted by a family that would, in the last resort, have had to kill him. It breeds a very particular boy: cocky where he is unsure, smirking where he is hurt, desperate to be claimed by someone and owned by no one. The tragedy that follows is not that Theon has no loyalty; it is that he has two, and the war makes him choose.",
      "He chooses badly in the most human way imaginable. Sent — at his own urging — as Robb’s envoy to Pyke, he arrives home dreaming of the prodigal’s welcome and is met instead with his father’s contempt: the mockery of his mainland finery, the gold-price sneer, the sister who has already taken his place. Somewhere between that hall and the shore, Theon burns Robb’s letter of alliance. It is the pivot of his life, and the books render it with terrible clarity: he does not betray the Starks out of hatred, but because his father’s scorn hurts worse than his brother’s trust holds, and a boy who has never been claimed will do anything for the man who finally might.",
      "Winterfell is his attempt to be a Greyjoy, performed for an audience that is not watching. Given a raider’s errand against fishing villages, he improvises the war’s most audacious small operation instead — the taking of Winterfell with a skeleton crew — and discovers within days that seizing a castle and holding one are different professions. Bran and Rickon slip his grasp; the hunt fails; and rather than admit it, Theon has two miller’s boys killed and burned and hung up as Stark princes. It is the crime the story never lets him outrun, and he knows it before anyone else does: the smoke has barely cleared before he stops sleeping.",
      "What the Boltons do to him afterward turns the tale’s cockiest boy into its deepest study of survival. Flayed finger by finger, broken by fear and false rescue, he is remade as Reek — a name he clings to because remembering Theon is what gets him hurt — and paraded as a tool against the very ironborn who might have saved him, talking Moat Cailin’s garrison into a surrender that ends on flaying frames. The show and books agree on the shape of the horror and split on the girl at the center of it: on screen it is Sansa Stark whose hand he takes on the snowy battlements when they jump; on the page it is Jeyne Poole, a steward’s daughter married north under a stolen name, and saving her is the first thing Theon has done in years for someone other than fear.",
      "The road back is slow and the show walks it at length: to Pyke and a kingsmoot where he sets aside his own claim to stand for his sister; to Daenerys’s cause; to the sea fight where Euron’s boarding axes find him and he goes over the side rather than die fighting — the failure that finally teaches him what his fear is for. Jon Snow gives him the absolution the whole story has been withholding, that he need not choose, that he is a Greyjoy and a Stark both. Theon spends it immediately: he boards his uncle’s flagship under fire and cuts his sister free, and brings his handful of ironborn to Winterfell — the castle he stole — to hold its godswood in the Long Night.",
      "That is where his meaning comes to rest. Theon is the tale’s longest, costliest redemption: not a villain forgiven, but an identity rebuilt from rubble, in a story that insists the rebuilding is possible and prices it honestly. The boy who burned the letter, the man who called himself Reek, and the ironborn captain standing guard over Bran Stark in the weirwood’s red light are all one person — and by the end, for the first time in his life, he knows it.",
    ],
    vs: [
      "The broad arc — betrayal, ruin, Reek, redemption — is shared, but the books tell the middle from inside his skull, and those chapters are among the most harrowing things Martin has written: the counting of fingers, the reflex of the false name, the slow theft of a self. The rescue plot differs materially — Jeyne Poole, not Sansa, is the bride he saves, smuggled off the battlements with the help of Mance Rayder’s spearwives — and so does the destination: book-Theon and his sister end the published volumes in Stannis Baratheon’s snowbound camp, his fate unwritten. Everything the show gave him afterward — the kingsmoot, the sea battles, the godswood — awaits whatever version the remaining books intend. In the published books, he is still alive.",
    ],
    fate: [
      "The show gives him the death the whole arc was aimed at. In the Long Night he holds Winterfell’s godswood with a handful of men, the last line before Bran, and empties his quiver into the dead until the Night King himself walks into the firelight. Bran gives him the only payment left worth having — “Theon. You’re a good man. Thank you.” — and Theon charges alone, spear leveled, at a being that has killed everything ever sent against it. The Night King snaps the spear aside and drives it through him. He dies in the castle he betrayed, defending the family he wronged, moments before Arya ends the creature that killed him.",
      "No book counterpart exists yet: in the published volumes Theon has just been delivered out of Winterfell alive — shattered, frost-bitten, but himself again — and waits with Asha in Stannis’s camp for a battle Martin has not yet printed. Alive in the published books, with the hardest part of his story, by any telling, already behind him.",
    ],
  },

  // ================= House Frey =================
  "Walder Frey": {
    paras: [
      "House Frey grew rich the way a tollbooth does, and Walder Frey never pretended otherwise. His family’s twin castles straddle the only bridge over the Green Fork for hundreds of leagues, and for six centuries the Freys have charged the realm for the privilege of crossing — a fortune built not on valor or ancient blood but on location, which is precisely why the old houses of the riverlands smile behind their hands at them. Walder, lord of the crossing for longer than most men live, heard every one of those smiles and forgot none of them.",
      "By the time the story reaches the Twins he is past ninety, wed to his eighth wife — a girl younger than some of his great-grandchildren — and presiding over a brood so numerous that visitors are tested on their names as a courtesy he enjoys watching them fail. He is lecherous, miserly, gleefully rude, and possessed of the one virtue the war rewards: patience. They call him the Late Lord Frey for the way his host arrived at the Trident only once Robert’s Rebellion was safely decided, and the name is meant as an insult. Walder wears it as a method.",
      "The war of the five kings makes his bridge briefly the most valuable real estate in Westeros, and he sells the crossing to Robb Stark for the highest price he has ever commanded: a royal marriage into House Frey, negotiated by Catelyn Stark under duress of geography. When Robb breaks the pact for love — marrying another with the Frey girl unchosen — he does not merely insult an old man; he confirms every snub Walder Frey has swallowed for ninety years, and hands him license, as Walder reckons license, for anything.",
      "What Walder does with that license is the atrocity by which the entire saga is measured. The Red Wedding is not a battle that got out of hand; it is hospitality weaponized — bread and salt eaten, the guest right invoked, and then the doors barred and the musicians reaching for crossbows. A king, his mother, his bannermen and his cause are butchered at Walder’s own tables, by arrangement with Roose Bolton and the blessing of Tywin Lannister, while the old man watches from the dais with a cup in his hand. He breaks the oldest law in Westeros deliberately, almost pedantically — because breaking it is the only demonstration of consequence a despised house has left.",
      "The reward curdles exactly as the realm’s stories say it must. The Freys get titles, and become the most hated name from Dorne to the Wall; their guests henceforth eat nothing at the Twins, and everyone knows why. The show’s later seasons render Walder’s decline with acid economy — his garrison loses Riverrun to a handful of Tullys, his sons blunder, and Jaime Lannister, his supposed ally, asks him to his face what use the Lannisters have for a man everyone despises if he cannot even hold what was bought with all that blood. Walder has no answer. There has never been an answer; there was only the bridge.",
      "He matters because the tale believes in guest right the way it believes in winter, and Walder Frey is the proof it offers. Old Nan’s tale of the Rat Cook — cursed not for murder but for killing a guest beneath his roof — hangs over the Twins from the moment the doors close, and the story spends its remaining volumes and seasons demonstrating, with growing interest, that some debts are collected even from men too old, too rich and too well-bridged to fear anything. The Freys’ name becomes a curse in their own lifetime, which is, perhaps, the one outcome Lord Walder never priced in.",
    ],
    vs: [
      "The Red Wedding is nearly identical in both tellings; the divergence is what the story does with him afterward. The show gives Walder two seasons of decline and an ending at Arya Stark’s hands; in the published books he is alive at the Twins — old, guarded, and watching his house die around the edges. The books distribute the vengeance instead: Freys hang from riverland trees wherever the Brotherhood rides under its new leadership, and at White Harbor three Frey envoys vanish before Wyman Manderly serves his famous pies at a wedding feast while a singer plays the Rat Cook — the books’ broad wink at the same justice the show made literal. Book-canon also gave Riverrun itself to a Frey, Walder’s son-in-law Emmon, an occupation the show replaced with a botched siege.",
    ],
    fate: [
      "The show kills him twice, in a sense, and Arya Stark is both deaths. In the sixth season’s finale a serving girl lays a meat pie before him and waits while he pokes at it, asking after his sons Lothar and Black Walder; she tells him they are already here — baked into the pie he has been eating — then peels off a face he does not recognize, tells him the last thing he will ever see is a Stark smiling down at him, and opens his throat the way his men opened her mother’s.",
      "The second death is the house’s. Weeks later, “Lord Walder” — Arya behind his face — summons every Frey male of consequence to the Twins, toasts their great deeds with poisoned wine, and watches the hall fall down around her while the wives, spared deliberately, look on. Her exit line does the accounting: the North remembers. In the published books, none of this has happened — Walder Frey still lives, though between Lady Stoneheart’s nooses and Manderly’s kitchens, the books make it clear the interest on his debt is compounding.",
    ],
  },

  "Merrett Frey": {
    paras: [
      "Somewhere in the middle of Lord Walder’s endless brood sits Merrett Frey, and “middle” is the story of his life. As a boy he squired at Crakehall alongside a young Jaime Lannister and dreamed the standard dreams — knighthood, tourneys, a name of his own — and the world declined every application. Captured by the outlaws of the Kingswood Brotherhood and ransomed home with a brand for a souvenir, his health and hopes wrecked young, he came back to the Twins with nothing to show but a talent for being overlooked, and settled into the long anticlimax his family had waiting for him.",
      "Grown, he is the Frey the other Freys tell jokes about: soft, heavy, fond of the cup well past fondness, married to a patient Darry wife and father to daughters the family gossips about. His assignment at the Red Wedding measures his standing precisely — while his kin sharpen knives, Merrett’s task is to drink the Greatjon Umber under the table so the North’s strongest man will be too sodden to fight. He performs it faithfully and miserably, cup for cup with a giant, and earns thereby his little share of the most infamous crime of the age: not a killer, merely the man who made a killing easier.",
      "His importance is structural, and it is the books’ blackest joke that he never learns it. Martin hands this negligible man the epilogue of A Storm of Swords — the only chapter he will ever narrate — and uses Merrett’s tired, put-upon eyes to deliver the volume’s final, freezing revelation. The saga’s great atrocity is answered not through a lord or a knight but through the Frey nobody rated: a man who spent his life certain he didn’t matter, chosen by the story to matter exactly once.",
    ],
    vs: [
      "Merrett exists only on the page — the show never names him, folding the Frey rank and file into an anonymous mass for Arya’s vengeance to sweep away wholesale. In the books he is the instrument of a different reckoning entirely: his epilogue chapter is the reader’s first sight of what the Brotherhood Without Banners has become, and of who now leads it — a reveal the show reassigned, in much-diminished form, to no one. The two tellings thus punish the Freys through opposite doors: the show with a daughter’s knife, the books with a mother’s rope.",
    ],
    fate: [
      "He dies on a hanging tree at Oldstones, in the epilogue of A Storm of Swords. Sent — because no one better would go — to ransom his young kinsman Petyr Pimple from outlaws, Merrett arrives with the gold and finds the Brotherhood Without Banners has already hanged the boy. They take the ransom anyway, and hang Merrett too, on the testimony of a hooded woman he is brought to face: a gaunt figure in a torn gown, her throat opened in a wound that matches the one the Freys gave Catelyn Stark at his family’s wedding feast. He protests, truthfully, that he killed no one — he only got a man drunk. For the thing that was Catelyn, it is enough. The chapter, and the book, end with the rope. He never appears in the show at all.",
    ],
  },

  "Roslin Frey": {
    paras: [
      "Out of Lord Walder’s crowded nursery of daughters and granddaughters, Roslin is the one the old man keeps in reserve — small, pretty, gentle-mannered, everything the Frey name is not — and when the moment comes he deploys her precisely. Robb Stark arrives at the Twins braced to see his uncle chained to some pinch-faced stranger as punishment for the broken pact; instead Edmure Tully is presented with a lovely, soft-spoken bride, and the Stark party relaxes. That is what Roslin is for. Her father spent her beauty the way he spends everything: as bait.",
      "The books make her role quietly heartbreaking, because Roslin knows. She weeps through her own wedding — steadily, helplessly, in a way the guests read as maiden’s nerves — because she alone at the altar knows what the music will turn into, and can warn no one. The marriage that begins that night is nonetheless, by every account, a real one: she and Edmure, two gentle people used as instruments by monsters, find genuine affection in the wreckage, and she carries his child while her husband sits in a Frey cell — a Tully heir conceived at the Red Wedding, which is the saga’s way with hope.",
      "She survives both tellings, a footnote to an atrocity she never chose, and ends the show’s story reunited with a freed Edmure at Riverrun — the one Frey the story permits a quiet ending, chiefly because she was as much a hostage of her father’s scheme as any Stark at the feast.",
    ],
    vs: [
      "The show keeps her wedding scenes nearly beat-for-beat but drops her knowledge of the plot — screen-Roslin is simply a sweet girl at the center of a horror, while book-Roslin’s tears are the tell no one reads in time. The books also keep her on the page after the massacre: pregnant at the Twins, praying for a daughter, by her own account, because a son would make her too useful to her family. It is a single line, and it carries the whole weight of being born a Frey.",
    ],
  },

  "Lothar Frey": {
    paras: [
      "They call him Lame Lothar for the twisted leg he has carried since childhood, and House Frey being what it is, the nickname doubles as a job description: barred from the tourney yard, Lothar grew a career out of wits instead, and became the son Lord Walder actually uses. He is the Twins’ steward and fixer, the smooth, courteous instrument sent wherever his father needs charm laid over calculation — most fatefully to Riverrun, where it is Lothar who delivers the olive branch of Roslin’s marriage and escorts the Stark party home to the wedding.",
      "The Red Wedding is, in an administrative sense, his masterpiece. The books credit Lame Lothar with the planning — the seating, the tents, the disposition of who dies where — an atrocity organized with the same courteous thoroughness he brings to a guest list, which is exactly what makes him the most quietly chilling Frey on the page. The show goes further and puts steel in his hand: it is Lothar who begins the massacre itself, stabbing Robb Stark’s pregnant queen where she stands. Between the two versions he is the whole crime in miniature — the smiler at the door, and the knife behind it.",
      "He is the tale’s reminder that atrocities need clerks. Black Walder frightens people and Lord Walder commands them, but somebody drew the map of the hall, and the story is careful to tell us it was the polite one with the limp.",
    ],
    vs: [
      "Book-Lothar never draws a blade on the page — his violence is entirely organizational, which arguably makes it worse — and he is alive in the published books, still stewarding the Twins. The show hands him Talisa’s murder, the single most brutal act of its most brutal scene, and then a poisoned cup: his screen death has no book counterpart at all.",
    ],
    fate: [
      "In the show he dies at his father’s table, which is to say at Arya Stark’s. Summoned with every Frey man of note to toast the family’s triumphs, Lothar drinks the wine “Lord Walder” pours — Arya, wearing the old man’s face, who had already baked Lothar into the pie she served the real Walder weeks before, in the show’s grisliest piece of double-billing. The books have collected no such debt from him yet: Lame Lothar lives, alive in the published books, with the Brotherhood’s nooses working their way up the family tree.",
    ],
  },

  "Black Walder Rivers": {
    paras: [
      "In a family the size of a small army, you need a modifier to be remembered, and Walder-called-Black earned his: the darkest-tempered of the old lord’s sprawling line, a hard-handed, cold-eyed man whom even Freys take care not to cross. The show marks him baseborn — a Rivers, carrying the bastard name — and uses him as the family’s blunt instrument, half of the double act with smooth Lame Lothar: one brother to phrase the offer, the other to stand behind it looking like the consequences.",
      "His place in the tale’s memory was fixed in a single moment at the Red Wedding. When the slaughter is done and Catelyn Stark stands alone amid her son’s dead, throat bared, mad with grief, it is Black Walder in the show who steps up behind her and draws the knife across — the last cut of the massacre, delivered without a word. Other men planned the wedding; Black Walder is the one the audience remembers ending it.",
      "The books keep him nastier and subtler: trueborn there, a great-grandson high in the line of succession, feared within the family less for his blade than his appetites — rumor gives him a habit of his kinsmen’s wives — and positioned, as the war grinds on and the heirs ahead of him die badly, uncomfortably close to the Twins themselves. He is the Frey the other Freys whisper about, which in that family is a genuine distinction.",
    ],
    vs: [
      "The two tellings disagree about his very birth: the show’s baseborn “Rivers” is, on the page, trueborn Black Walder Frey, son of Ser Ryman and great-grandson of the old lord. They disagree about the famous killing too — in the books it is Raymund Frey, a different kinsman entirely, who cuts Catelyn’s throat, a deed the show moved to Black Walder to concentrate the audience’s hatred. And they disagree about his ending: the books leave him alive, dangerous, and rising through a thinning succession as the Brotherhood hangs his relatives one by one — including his own father.",
    ],
    fate: [
      "The show settles his account alongside his brother’s: gathered to the Twins for the great toast, he drinks with the rest of the male line and dies choking in the hall where Catelyn Stark bled — poisoned by the girl whose mother’s throat he cut, wearing his own lord’s face. In the published books he is alive, and if anything more prominent than ever; whatever the novels intend for Black Walder, the rope-and-wine accounting of the screen has not yet reached him.",
    ],
  },

  "Olyvar Frey": {
    paras: [
      "Every rule needs its exception, and Olyvar is House Frey’s: proof the Twins could produce a decent man, roughly once a generation. One of Lord Walder’s younger sons, he is attached to Robb Stark as squire under the bridge-toll pact, and does something no one anticipated — he comes to genuinely love his king. He serves well through the war’s victories, tends Robb’s gear and Robb’s moods, and speaks of him afterward, the books note, with unembarrassed loyalty, in a family where sincerity is regarded as a developmental defect.",
      "The broken marriage pact tests every Frey’s allegiance and Olyvar passes in the only direction his family would count as failure: he wants to stay. When the Freys quit Robb’s cause in fury, Olyvar has to be pried from the king’s service by his own kin, and the books are pointed about the sequel — he is nowhere at the Red Wedding, kept deliberately away, because his father’s planners knew exactly which son could not be trusted near a warning-shaped opportunity. Robb asks after him at the feast; the old man serves up an excuse. It is the single most damning detail in the hall: the Freys themselves catalogued their one honest man and scheduled around him.",
    ],
    vs: [
      "The page and screen agree on the outline of the loyal squire, but only the books underline his absence from the massacre — a quiet exoneration Martin plants a full book in advance. The show never resolves him at all on screen, and this archive’s show chronology sweeps him into the Twins’ final reckoning with the rest of the male line; the books, pointedly, keep his hands clean and his heart on record: the one Frey who mourned the Young Wolf.",
    ],
    fate: [
      "By the show’s ledger he dies as anonymously as he lived: one cup among dozens raised when “Lord Walder” toasts the men of House Frey, and one body among dozens on the floor when the wine does its work — the family’s guilt collected wholesale, without an audit of the innocent. The books tell it otherwise: Olyvar Frey lives, absent from his family’s crime by his family’s own arrangement, which makes the show’s indiscriminate justice, in his one small case, no justice at all. Alive in the published books.",
    ],
  },

  "Stevron Frey": {
    paras: [
      "Stevron Frey held the least enviable job in Westeros: heir to a man who would not die. Firstborn of Lord Walder’s firstborn marriage, he waited on the succession for some sixty years — long enough to grow old himself, with grandchildren grown and his father still counting coppers and wives at the high table. The wait shaped him into something the Twins rarely produce: a patient, courteous, essentially reasonable man, the smiling diplomat of the family, forever smoothing what his father’s tongue tore.",
      "The war gives him a final act in Robb Stark’s camp, where he rides as the pact’s senior Frey and speaks, characteristically, for caution — his is the voice in the king’s councils urging that victories be banked and peace be weighed while the winning is good. It is sound advice from a man who spent a lifetime watching patience outperform pride, and the young king’s cause might have ended better had anyone taken it.",
    ],
    vs: [
      "Stevron never appears in the show, which needed only one old Frey and kept the worst one. His absence flattens a book irony the adaptation had no room for: the succession at the Twins, that endless queue of scheming heirs, exists because the decent man at its head died waiting — and every Frey behind him was worse than the last.",
    ],
    fate: [
      "He dies in A Clash of Kings of wounds taken at the battle of Oxcross, lingering three days in the west before slipping away — the heir of the Twins, dead a continent from the bridge he waited sixty years to inherit. His father’s recorded reaction is pure Walder Frey: less grief than vexation, a grumble that the boy spent a lifetime waiting for him to die and then had the effrontery to go first. His death hands the heirship down a queue of grandsons — Ryman, Edwyn, Black Walder — each a measurable step down in decency, with consequences the riverlands would soon learn to count. Book only; the show never names him.",
    ],
  },

  // ================= The road & the Brotherhood =================
  "Hot Pie": {
    paras: [
      "Hot Pie enters the story as a Flea Bottom baker’s boy playing at menace — swaggering around Yoren’s recruit column with a stolen nickname’s worth of toughness, bullying the small until the small turns out to be Arya Stark with a wooden sword and a temper. The beating she gives him settles the pecking order and, in the roundabout way of children, founds a friendship: Hot Pie, Arya and Lommy become the column’s unlikely little pack, three lowborn city kids walking north toward a Wall none of them will ever see.",
      "The road teaches everyone in this story what they are, and what Hot Pie is turns out to be a baker — seriously, stubbornly, almost heroically a baker. Through ambush, capture and the horrors of Harrenhal he survives on unobtrusiveness and finds his one place of power in the kitchens; when escape drags him back onto the road with Arya and Gendry, he is the first of the three to recognize that adventure is a thing happening to him against his will. The Brotherhood Without Banners offers the exit: the inn at the crossroads needs a baker, the outlaws like his bread, and Hot Pie — to Arya’s disbelief — chooses flour over war. As farewells go, his is the tale’s gentlest: a loaf baked in the shape of a wolf, for the friend who is one.",
      "The choice looks like smallness and plays out as wisdom. The inn becomes his fixed point while the war spins every mightier character to ruin — he feeds travelers, improves his recipes (the wolf-loaf he presses on Brienne, with intelligence about Arya attached, is a marked advance on the original), and functions as the road’s unofficial news exchange. It is Hot Pie, serving pie and gossip in equal portions, who tells a passing Arya that the Boltons are dead and Jon Snow holds Winterfell — the plain, friendly sentence that turns her off the road to King’s Landing and toward home, family and the North’s salvation. Not bad for a boy whose ambitions ended at brown butter.",
      "He may be the tale’s only true innocent to pass through its very worst places — Harrenhal under the Mountain, the war-torn Trident — and come out the far side unbent, uncorrupted and gainfully employed. The story loves its broken things; Hot Pie is its quiet proof that knowing your size, your trade and your friends is a kind of armor no one in the great game ever thinks to wear.",
    ],
    vs: [
      "The books leave him behind earlier and for good: the Brotherhood deposits him at a riverlands inn as a baker’s helper, and he exits Arya’s story with his wolf-shaped bread, resurfacing only when Brienne’s travels bring her to the crossroads and a proud young baker whose work has gotten good. The show, fonder of him than the plot strictly required, engineers two reunions — the loaf for Brienne, and the season-seven supper where his news redirects Arya north — and grants him what the books have not yet confirmed: survival all the way to the story’s end, feeding people at the same crossroads while the armies pass.",
    ],
  },

  "Lommy Greenhands": {
    paras: [
      "Lommy comes to the story pre-dyed: an apprentice from the dye-works of King’s Landing whose hands are stained green to the elbow, which the orphans of Yoren’s recruit column convert instantly into a name. He is one of the gutter-swept — an orphan bound for the Wall not out of vocation but because the city had nowhere else to put him — and he compensates the way small boys in rough company do, by needling anyone smaller. Arya, traveling as the boy “Arry,” gets the worst of his tongue, including the nickname Lumpyhead, until her wooden sword renegotiates their relationship.",
      "On the long march he settles into the little pack at the column’s tail — Lommy, Hot Pie, Arya, and quiet Weasel — where his contribution is a philosophy of survival stated with a boy’s certainty: when soldiers come, you yield. Fighting is for knights and fools; sensible people put up their hands and say the words. It is the creed of every small person the war rolls over, offered by the smallest person in the column, and the story lets him voice it without mockery, because the story knows exactly what the war does to the people with no other option.",
      "He is kept minor on purpose — a boy with a joke name and one idea, sketched in a handful of scenes — because his function in the tale is to stand for the thousands like him: the swept-up, marched-off, unconsulted children of the realm’s wars, remembered by the great only when a girl who knew him starts keeping a list.",
    ],
    vs: [
      "The tellings differ only in the hand that fails him: the ambush on Yoren’s column, the leg wound, and the fatal question are common to both, but the show gives the moment to Polliver and the books to Raff the Sweetling, two of the Mountain’s men cut from the same rotten cloth. The choice matters later, because Arya’s memory is long in both directions — the show settles the account in the inn scene where she reclaims Needle from Polliver, and a sample chapter released ahead of The Winds of Winter strongly suggests the books intend the same arithmetic for Raff, right down to the borrowed words.",
    ],
    fate: [
      "He dies on the march, helpless, and the manner of it is engineered to be unbearable. Lamed in the leg during the ambush that kills Yoren, Lommy cannot walk; when the Mountain’s men sweep up the survivors, he does exactly what his creed prescribes — yields, and asks to be carried. In the show Polliver asks whether he can walk, hears that he cannot, and drives Needle — Arya’s own stolen sword — through his throat as the efficient alternative. In the books it is Raff the Sweetling, and the exchange is crueler still: told the boy must be carried, Raff answers “carry him, is it,” and carries the spear to him instead. Either way a child dies for the crime of a wounded leg, and Arya is watching. Polliver later returns Needle point-first at the crossroads inn; Raff’s name stays on a list that has never yet gone uncollected.",
    ],
  },

  "Lem Lemoncloak": {
    paras: [
      "Nobody in the Brotherhood Without Banners knows Lem’s right name, and Lem has arranged things that way. What the band knows is the cloak — a great ragged wool thing dyed lemon-yellow, long past its best decade, which he will neither wash nor replace and which has named him as surely as any sept ever christened a lord. Under it stands a big, broken-nosed, gruff slab of a man with a soldier’s bearing and a border-country burr, who deflects every question about his past with a grunt and is plainly, to anyone paying attention, somebody who used to be somebody else.",
      "Within the outlaw band he is the sergeant to Thoros’s chaplain and Beric’s saint: the practical, unsentimental enforcer who keeps watch, keeps order, and keeps prisoners from getting ideas. The books run Arya’s riverlands odyssey through his custody — it is Lem as much as anyone who hauls her back when she bolts, catches her kicks and her curses, and delivers her to the hollow hill for the Brotherhood’s strange justice. He is not kind, and not cruel: he is what a cause looks like at the rank where the work gets done.",
      "The band changes masters, and Lem changes with it. In the later books, under a new and colder leadership, the Brotherhood’s justice curdles into vengeance — trials giving way to nooses, mostly Frey-shaped — and Lem rides at the front of that turn, having claimed for himself the snarling houndshead helm that once belonged to Sandor Clegane. The yellow cloak under the Hound’s helm becomes one of the books’ eeriest silhouettes: the decent-enough sergeant of a good man’s war, repurposed, piece by piece, as the hangman of a dead woman’s grief.",
    ],
    vs: [
      "The book Lem deepens by the volume — his custody of Arya, the houndshead helm, and his grim role in the hangings that stalk the Freys through the riverlands, including the noose offered to Brienne of Tarth — and readers have spent years trading theories about the man under the cloak. The show kept the name, the cloak and little else: its Lem is a coarse bit-player in the Brotherhood who reappears among the renegades that butcher Ray’s peaceable flock — the massacre that pulls the Hound back into the war — and answers to Beric and the rope for it. Two mediums, two Lems, and the yellow cloak the only thing they’d recognize in each other.",
    ],
  },

  "Anguy": {
    paras: [
      "Anguy comes out of the Dornish Marches, that stony border country whose smallfolk are raised on the longbow the way other children are raised on prayers, and at the Hand’s tourney in King’s Landing he does the thing the songs promise and the odds forbid: a nameless commoner outshoots every knight and fancy archer in the field and walks off with a purse of ten thousand gold dragons. The books append the perfect footnote — he ran through the entire fortune in a matter of months, on drink and boots and companionship, and was back to owning a bow and a good eye when the war found him and swept him into Beric Dondarrion’s luckless company.",
      "With the Brotherhood Without Banners he is the indispensable specialist: the bowman who feeds the band, screens its marches and settles arguments from farther away than the other side can answer. The show gives him its fondest scenes — trading shots and pointers with Arya, teaching her in a sentence the whole marcher creed of instinct over aim — and its most uncomfortable one, when he stands by as the Brotherhood sells Gendry to the red priestess, the moment the band’s roguish charm first shows its price tag. He vanishes from the screen thereafter, unremarked; the books keep him riding with the outlaws through the riverlands’ long ruin. Alive in both tellings, so far as either says — a small, cheerful argument that the realm’s best archer was never a knight at all.",
    ],
    vs: [
      "The show’s Anguy is a warm supporting turn who simply stops appearing after the third season — no death, no farewell, just the adaptation misplacing him. The books keep him in the band through its darkening turn, one more good-humored man attached to a cause that has stopped being good-humored, and readers tracking the Brotherhood’s later grim work are left to wonder how the tourney champion sits with the rope-work. The purse-squandering backstory is book-only, and worth keeping: it is the entire character in one anecdote.",
    ],
  },

  "Harwin": {
    paras: [
      "Harwin is Winterfell-born and Winterfell-made: son of Hullen, the castle’s master of horse, raised among the stables and the guardsmen, one of the household faces the Stark children knew before they knew their letters. When Eddard Stark rode south to be Hand, Harwin rode in his tail — and when Lord Eddard dispatched a hundred men under Beric Dondarrion to bring the Mountain to justice for his raiding, Harwin was among them. The errand outlived the government that ordered it: ambushed, broken and hunted, its survivors stayed in the field, and the Stark guardsman became, without ever exactly deciding to, an outlaw of the Brotherhood Without Banners.",
      "The books give him the reunion the show never stages. When the Brotherhood scoops a ragged captive off the roads and hauls her to the hollow hill, it is Harwin who looks past the dirt and the boy’s clothes and knows her — Arya, his lord’s daughter, whom he once led around the yard on her first pony. For a stretch of the riverlands he becomes her keeper and the closest thing to home she has touched since her father died; and it falls to him to explain, gently, what the Brotherhood now is — men sworn first to a lord and a king, both dead, who found that the realm and its smallfolk still needed defending after every banner above them had burned. No one in the tale states the story’s case for the common people more plainly, and he does it in a cave, to a child, wearing another man’s war for a cloak.",
    ],
    vs: [
      "The show cut him entirely — its Brotherhood springs up without the Winterfell thread, and Arya passes through their hands unrecognized by any old friend, which loses a quietly devastating book beat: that even at her lowest she was one familiar face from rescue, and the war’s machinery carried her past it anyway. In the published books Harwin rides with the Brotherhood still, deep in its grim later turn, his ultimate loyalties — to the band, or to the Stark girl he knew — one of the riverlands’ many unsettled accounts.",
    ],
  },

  "Pate, the Citadel novice": {
    paras: [
      "The Citadel of Oldtown mints the realm’s knowledge, and Pate is its least promising coin: a slow, kindly, unhappy novice pushing thirty years against examinations he keeps failing, whose actual employment is tending the senile Archmaester Walgrave — feeding him, cleaning him, minding his beloved white ravens, and holding, not incidentally, the old man’s keys. Even his name is a joke at his expense: every fool tale in Westeros stars a pig boy called Pate, and the novices never let him forget it. What he has instead of prospects is a girl — Rosey, a tavern maid at the Quill and Tankard, whose maidenhood her mistress has priced at a golden dragon, a sum a failed novice will not honestly see in a lifetime.",
      "Into that arithmetic steps a stranger the story calls only the alchemist: a hooded, soft-spoken man who claims his art can change gold — and offers Pate exactly one golden dragon for exactly one thing, a certain iron key from the collection Pate minds. The bargain is the oldest in literature, dressed in Citadel gray: a small theft, a large want, and a buyer who knows precisely what a desperate man’s conscience weighs. Pate makes his choice at the riverside inn, coin against key, telling himself the story every such man tells — that no great harm can come of so small a thing.",
      "His purpose in the saga is to open its fourth volume and its newest front: the prologue that announces the war after the war will be fought over knowledge — the Citadel’s locked doors, its glass candles burning where glass candles should not burn, and the interest that the world’s most dangerous people have begun to take in what the maesters keep. Pate is the small, ordinary door through which all of that walks in.",
    ],
    vs: [
      "Pate is book-only, and so is his entire mystery — the show’s visit to Oldtown, with Sam’s bedpans and chained library, borrows the setting but none of the conspiracy. On the page, the tale’s eeriest thread runs straight through him: the alchemist’s glimpsed features match the face Jaqen H’ghar wore when he left Arya at Harrenhal, and at the fourth book’s end a novice called Pate — walking, smiling, unmistakably not the boy who died — makes friendly introduction to Samwell Tarly at the Citadel’s door. The Faceless Men have enrolled, the books quietly tell us, and only the reader knows.",
    ],
    fate: [
      "He dies in the prologue of A Feast for Crows, minutes after the worst bargain of his life. The alchemist pays him his golden dragon for Archmaester Walgrave’s iron key; Pate, giddy with the enormity of it, bites the coin as men do — and is dead before he has gone far, folding into the Oldtown street with the gold still in his fist, the taste of something wrong the last thing his slow, honest mind records. Whether the poison rode the coin or the parting is left for readers to argue; what is not left in doubt is the sequel, for by the volume’s end someone is walking the Citadel wearing Pate’s face and Pate’s name, keys and secrets within easy reach. He never appears in the show.",
    ],
  },
});
