/* House of the Dragon wiki — the hours retold, S1–S2. Original prose. */
Object.assign(WIKI_EXTRA, {

  // ==================== SEASON ONE ====================
  "episode:1-1": {
    paras: [
      "The premiere spends its first minutes on a decision the rest of the show never escapes: an old king's Great Council weighing his granddaughter Rhaenys against his grandson Viserys, and choosing the man — not for the strength of his claim but for the simple, unspoken conviction that the realm will not kneel to a queen. Rhaenys becomes the Queen Who Never Was in a single sentence, and the show files the ruling away as settled law. Everything that follows is the realm discovering it settled nothing.",
      "The hour's engine is grief. Viserys, a genuinely kind man happiest with his model of Old Valyria, is handed the one choice no maester should offer: his wife Aemma's life or the son cut from her in a bloody birthing bed. He takes the son, and the son lives a day. Out of that ruin comes the decision that defines the Dance before the Dance has a name — Viserys passes over his own brother and names his daughter heir, telling her the secret every Targaryen king carries: a dream of a Song of Ice and Fire, a promise dressed up as a prophecy to justify a thing the realm was not ready to allow.",
      "Around that choice the pieces set themselves. Daemon toasts his dead infant nephew as 'the heir for a day' and is exiled for it, the rogue prince too dangerous to keep and too Targaryen to unmake. Otto Hightower sends his daughter Alicent to comfort the widowed king in his chambers, a courtesy with a queen's crown hidden inside it. And the lords of the realm kneel to swear an oath to Rhaenyra — an oath given in a hall, under a king's eye, that will prove to weigh exactly as much as the man who demanded it, and no more.",
    ],
  },
  "episode:1-2": {
    paras: [
      "An hour about a chair sitting empty and everyone in the realm quietly measuring themselves against it. Daemon, sulking on Dragonstone, seizes the island with his gold cloaks and steals a dragon's egg — the one meant for the cradle of the son Viserys just buried — less because he wants it than because he wants his brother to come and take it back. What arrives instead is a bridge full of drawn steel and a fifteen-year-old princess landing Syrax between the swords, ending the standoff by daring her uncle to kill her in front of a dragon. It is the first time the show lets Rhaenyra be the most dangerous person in a room, and it will not be the last.",
      "The episode's real damage is done in a council chamber and a garden. The Sea Snake offers his twelve-year-old daughter Laena as the new queen, a match that would bind the realm's fire to its fleet and give the crown the sea power it is about to badly need. Viserys chooses Alicent Hightower instead — companionship over strategy, the girl who reads to him over the alliance that might have saved him — and Corlys Velaryon leaves court cold, twice insulted. The Stepstones burn in the background, the Crabfeeder nailing Westerosi sailors to posts while the crown does nothing, and a spurned Sea Snake brings his ships to Daemon to fight a war the king refused to.",
    ],
  },
  "episode:1-3": {
    paras: [
      "Three years on, the crack has become a fault line, and the hour stages it as a hunt. Aegon, Alicent's firstborn son, has his second nameday in the kingswood, and half the court arranges itself to hint that here — a boy, a Targaryen boy — is the heir the realm actually wants. Viserys drinks through it, cornered by his own decision, while Rhaenyra rides out furious, kills a boar in the dark with her own spear, and watches a white hart, the old omen of kingship, walk out of the wood uncrowned. The episode keeps offering signs and letting everyone read them wrong.",
      "In the Stepstones the other war grinds toward its ugly resolution. The crown finally sends the aid it has withheld for years, and the shame of needing rescue drives Daemon to beat the messenger bloody with his own helm before doing the one thing no one can rescue him from. He rows toward the Crabfeeder's line under a peace banner, feigns surrender, and turns it into a slaughter — walking out of the caves dragging half of Craghas Drahar behind him, a three-year stalemate broken by a single unforgivable lie. It is Daemon distilled: the victory is total, the method is dishonorable, and the realm loves him more for it, not less.",
    ],
  },
  "episode:1-4": {
    paras: [
      "Daemon comes home a king — 'King of the Narrow Sea,' crowned in driftwood by his own army — and lays the crown at his brother's feet, keeping the grievance and giving back the title, the most Daemon gesture the season offers. What he does next is harder to hand back. Tired of watching suitors count her castles, Rhaenyra lets her uncle show her the city instead: Flea Bottom, a mummer's farce mocking her own succession, and finally a pleasure house, where a night begins that Daemon cannot finish and Rhaenyra, later, with Ser Criston Cole, does.",
      "The hour is about how a single night becomes a weapon in the right hands. Otto Hightower brings the king a whisperer's account of his daughter and his brother, and Viserys — refusing to hear it — finally sees whose ambition the Hand has been serving all along, and strips Otto of his badge. It should be a victory for Rhaenyra. Instead the episode closes on the quieter cost: a princess swearing her innocence on her dead mother's memory, and then drinking the moon tea her father sends anyway, because a queen-in-waiting's word, it turns out, is not enough even for the man who named her heir.",
    ],
  },
  "episode:1-5": {
    paras: [
      "A wedding hour, and everything about it is funereal. It opens with a murder disguised as an accident — Daemon calling on the wife he never wanted at Runestone, and Lady Rhea Royce dead in the dirt with the stone that finished her in her husband's hand — and it ends with a betrothal feast turned abattoir. In between, Viserys sails to Driftmark to mend the realm's two dragon houses, promising Rhaenyra to Laenor Velaryon and their someday-sons to the throne, and the two young people, each in love elsewhere, strike the only honest bargain in the room: a marriage of duty with the door left open.",
      "The episode's title is the Hightower words, and the episode's last image explains them. Ser Criston Cole, refused as a paramour and unstrung by the vows he has already broken, beats Laenor's lover Ser Joffrey Lonmouth to death on the feast-hall floor while the court watches its future curdle. And Alicent arrives late, deliberately, in a gown of Hightower green — the color Oldtown's beacon burns when it calls its banners to war. She says nothing. She doesn't need to. The two women who were once each other's only friend are now the two poles of a realm, and the whole hall reads the dress correctly.",
    ],
  },
  "episode:1-6": {
    paras: [
      "The show jumps a decade and recasts its leads, and the gap does exactly what it should: the friends are now entrenched enemies, and no one can quite remember a time before the war of whispers. Rhaenyra births her third son and carries him, still bloody, the length of the castle because the queen commanded a look — and the look is the point, because every one of the princess's Velaryon sons has brown hair and a common face, and the court has a name ready for the father. Alicent stops whispering it and starts saying it, and the cold war becomes a campaign of small, deniable cuts.",
      "Grief and calculation braid together across the hour. In Pentos, Laena Velaryon's second labor fails the way Aemma's did, and she refuses the ending on offer — walking to Vhagar and commanding her own pyre rather than dying in a bed. In King's Landing, Larys Strong solves his queen's problems and his own ambitions in one fire, burning his father the Hand and his brother Harwin alive at Harrenhal so that a debt is created that only he can be paid for. Rhaenyra, finally seeing the court for the machine it has become, gathers her family and removes them to Dragonstone — a retreat that reads, correctly, as a mustering.",
    ],
  },
  "episode:1-7": {
    paras: [
      "Every dragon and every grievance in the realm gathers on one island for Laena's funeral, and the hour uses the gathering to detonate the war's first real wound. In the dark, Aemond — the family's dragonless embarrassment — climbs onto Vhagar herself, the oldest and vastest living thing in the world, and the great beast answers a ten-year-old's nerve. The claiming shifts the realm's balance in a night, and it costs him an eye when Laena's and Rhaenyra's children fall on him in the yard and Lucerys, cornered, slashes at his face. Aemond names the trade a bargain — an eye for a dragon — and means it.",
      "The adults make the children's brawl into a line no one can walk back. Alicent demands an eye for an eye, and when the king refuses her, she takes the blade from his own belt and opens Rhaenyra's arm reaching for Luke — a queen drawing royal blood in the king's hall, with the king's own dagger. Viserys, who heard Aemond call the boys bastards, rules only that the matter never be spoken of again, mistaking silence for peace one last time. The hour closes on a Valyrian wedding on Dragonstone's shore, Rhaenyra and Daemon married over a burned body dressed in Laenor's clothes — while Laenor himself, spared by the one mercy the show grants that the histories do not, rows for Essos alive and free.",
    ],
  },
  "episode:1-8": {
    paras: [
      "Six years on, the season's gentlest and most devastating hour turns on a dying man's last exercise of will. Corlys lies wounded in the Stepstones and his brother Vaemond sails to court to claim Driftmark over the 'strong boys,' forcing the succession question into the throne room while Rhaenyra and Daemon return to a Red Keep run by Otto and Alicent, its king kept swimming in milk of the poppy. Into that room Viserys drags himself — half a face gone, half a body failing — to sit the Iron Throne one final time and hold the line for his daughter, the reign's single unanswerable act of majesty.",
      "Vaemond names Rhaenyra a whore and her sons bastards before the throne, and Daemon takes his head off mid-sentence — 'he can keep his tongue.' But the hour's real turn is quieter and crueler. At a last family supper the two halves of the house manage, for one evening, something like grace. Then Viserys, in the dark, mistakes Alicent for Rhaenyra and murmurs of Aegon's dream and the prince that was promised — the prophecy he told his heir in the premiere — into the one pair of ears certain to hear a son's name in it. He dies with 'my love' on his lips and a misunderstanding loose in the realm that no one will ever correct.",
    ],
  },
  "episode:1-9": {
    paras: [
      "The king is dead and only the greens know it, and the penultimate hour is a coup conducted in a sealed castle before the body is cold. Otto Hightower's council — planning this for twenty years — moves to crown Aegon, and when old Lord Beesbury alone says the word 'treason,' Ser Criston Cole opens his throat on the council table, the Dance's first death paid before the war is even declared. The horror of the episode is administrative: a peace ending not with a battle but with a quorum, men who have known each other for decades agreeing to steal a crown between breakfast and supper.",
      "The trouble is that the heir they mean to crown does not want it. Aegon is hunted through Flea Bottom like a stray, found hiding from his own coronation and dragged to the Dragonpit to be crowned before a mob with the Conqueror's crown and blade. And Rhaenys — locked up, courted for her dragon, escaping through the same crowds herded to watch — chooses the hour's defining act: bursting Meleys through the pit floor with the entire green court at her mercy, and then not burning them. It is the war's great road not taken, restraint offered by the one person with every reason to withhold it, and the show lets it hang there as the last mercy anyone will get.",
    ],
  },
  "episode:1-10": {
    paras: [
      "The finale is about a queen refusing to be a rebel. Word of the usurpation reaches Dragonstone and the shock throws Rhaenyra into an early, killing labor; she buries a daughter, Visenya, the same day her crown is stolen, two thefts in one afternoon. A stolen circlet arrives with Ser Erryk, and Daemon sets her father's crown on her head on the shore — but the woman crowned spends the hour holding her own war back, answering Otto's peace terms with a monarch's discipline rather than a widow's fury, insisting on envoys where Daemon wants dragons.",
      "The painted table counts the odds — the Vale, the North, the riverlands to win, thirteen dragons against the greens' four — and Rhaenyra keeps choosing statecraft anyway, sending her sons out as messengers and not warriors. Jacaerys flies north for the mountain and the snow; Lucerys flies to Storm's End, where Vhagar is already waiting. Above Shipbreaker Bay, Aemond's old game stops being a game: Vhagar takes Arrax and Lucerys both, whether her rider meant murder or only meant to frighten a boy. The season's last shot is Rhaenyra's face receiving the news, and the restraint she has held all hour going out of it. The peace her father died keeping dies with her son.",
    ],
  },

  // ==================== SEASON TWO ====================
  "episode:2-1": {
    paras: [
      "The season opens by widening the board and then narrowing it to a single, unforgivable room. In the North, Jacaerys treats with Cregan Stark on the Wall itself and comes away with the Pact of Ice and Fire — the North remembers its oath, and a boy who won a kingdom with honesty rides home to find honesty is not the currency the war will be settled in. Rhaenyra, meanwhile, combs the wrack of Shipbreaker Bay for whatever Vhagar left of her son, and breaks a whole hour of silent grief with four words that set the season's course: 'I want Aemond Targaryen.'",
      "What she gets instead is the war's true beginning. Corlys's blockade closes the Gullet and King's Landing starts to feel the first pinch of hunger, but the hour's engine is Daemon, who hires two ratcatchers the histories will remember only as Blood and Cheese and sends them into the Red Keep for 'a son for a son' — without specifying enough. Unable to find Aemond, they take the head of Helaena's small boy Jaehaerys while his mother watches and is made to choose. It is the crudest scene either telling of the Dance offers, and it does exactly what it must: the green court's grief now matches the black's, and there is no floor left beneath the war.",
    ],
  },
  "episode:2-2": {
    paras: [
      "Grief becomes statecraft in the opening minutes, as Otto Hightower turns a murdered child's funeral into a slow procession through the streets — a dead prince paraded so that 'Rhaenyra the Cruel' can be planted on every crier's lips. It is the shrewdest thing anyone in King's Landing does all season, and it is wasted, because the king it serves has no patience for chess. Aegon, raging past his grandsire's counsel, strips Otto of the Hand's badge for the second time in the old man's life and gives it to Ser Criston Cole, trading a schemer for a soldier at the precise moment the war needs a schemer.",
      "The hour's two halves rhyme: a city answering murder with more murder, and a family answering it with itself. Aegon hangs every ratcatcher in King's Landing, guilty and innocent alike, on the walls — twenty fathers for one prince. And on Dragonstone the war's saddest single act plays out, as Ser Arryk Cargyll is sent wearing his twin's face to kill the black queen, only to meet Ser Erryk at her door. Twin kills twin in Rhaenyra's own hall, and Erryk, having killed the brother he loved for the queen he chose, falls on his own sword for the shame of it — the Dance in miniature, a house turning its own two halves into corpses.",
    ],
  },
  "episode:2-3": {
    paras: [
      "The war stops being a matter of dragons and courts and becomes, for an hour, a matter of old grudges wearing new crowns. In the riverlands the Blackwoods and Brackens turn a quarrel of stones into the Battle of the Burning Mill, and the show is careful to note that the first real bloodshed of the Dance is fought over dragons by boys who have none — nine hundred years of neighborly hatred finally given a banner to march under. Daemon flies Caraxes to Harrenhal and takes the greatest castle in Westeros without a blow, Ser Simon Strong yielding it with supper, but the castle will prove a harder thing to hold than to enter.",
      "The hour's heart is a conversation almost no one else knows happened. Rhaenyra slips into King's Landing in a septa's robes and asks Alicent, face to face in the sept, whether the war is truly past stopping. It is — and the tragedy the scene reveals is that Alicent now knows the truth: the dying Viserys was murmuring of a prophecy, the prince that was promised, and never named her Aegon at all. She hears the misunderstanding for what it was, far too late to unmake it, and lets the war continue anyway, because too many people have died already for the truth to be worth anything but more grief.",
    ],
  },
  "episode:2-4": {
    paras: [
      "The season's centerpiece, and the first time the Dance shows the realm what a dragon actually costs. Daemon rots in a ghost-ridden Harrenhal, dosed by Alys Rivers's draughts and dreaming his way through everyone he has broken, while Criston Cole marches a green host cross-country — taking Duskendale and beheading Lord Darklyn for keeping the oath he swore to Rhaenyra — and lays a trap at Rook's Rest baited specifically to draw down a dragon. It works better than anyone planned. Rhaenys answers on Meleys; Aegon, half-drunk and desperate to feel like a king, rides unannounced into his own battle on Sunfyre; and Aemond, waiting on Vhagar, burns king and enemy alike in a single pass.",
      "The hour belongs to the Queen Who Never Was. With Sunfyre and Aegon falling broken into the wood and Vhagar's vast bulk between her and the sky, Rhaenys has a clear window to flee and turns Meleys back into the ancient dragon's teeth instead. She dies the death she chose over every softer ending on offer, and she does not die cheaply — Meleys wounds Sunfyre badly enough to eventually kill him and burns Aegon half to ruin, taking the greens' king out of the war's middle stretch. The best monarch the Dance never crowned falls at a small castle nobody remembers the name of, and the war's arithmetic changes in the smoke she leaves behind.",
    ],
  },
  "episode:2-5": {
    paras: [
      "An hour about who inherits a war when its king can no longer wear it. Aegon lives — barely — burned, broken, and drowned in milk of the poppy, and the green council quietly passes the rule not to his mother but to Aemond, handing the realm to the one hand in the family most certain to burn it. Alicent, who spent twenty years building the greens' power, is passed over by her own council for the son she can least restrain, and the show lets the irony sit: the woman who started the war to protect her children is now governed by the child she made.",
      "The realm learns a lesson it can't unlearn. Meleys's severed head is dragged through King's Landing as a trophy meant to reassure, and the smallfolk read it exactly backward — proof that dragons die, that the gods on the wing are meat like anything else — and begin slipping out of a city they no longer believe is safe. On Driftmark, Corlys is made Rhaenyra's Hand and is met at his own docks by Alyn of Hull, the sailor who pulled him from the waves and is owed more than wages, a quiet reckoning with the blood the Sea Snake never dared to claim. And in the riverlands, Daemon sinks deeper into Harrenhal's dreams while the lords wait for him to wake into the commander they need.",
    ],
  },
  "episode:2-6": {
    paras: [
      "The season's argument comes into focus: the war will be won not only with fire but with bread. Hunger bites King's Landing hard, and Rhaenyra and Mysaria answer it by feeding the city from black ships, so that the smallfolk begin, dangerously for the greens, to love the queen who feeds them over the king who hangs their fathers. It is the White Worm's finest work — turning a blockade's cruelty into a queen's mercy — and the first sign that Rhaenyra has weapons Aemond's council never thinks to count.",
      "The hour's turn is on a Dragonstone slope, and it rewrites the war's rules. Ser Steffon Darklyn dies in fire trying to claim the riderless Seasmoke with pedigree and a knight's nerve — and then Seasmoke does its own choosing, hunting down the baseborn Addam of Hull and taking him alive into the sky. A dragon has chosen a bastard over a knight, and the implication is enormous: the blood of old Valyria ran wider than the great houses ever admitted, and it is riding fishing boats and working forges all over the realm. Aemond answers the blockade the only way he knows, burning black-sworn towns along the coast, while Daemon learns in the riverlands that terror recruits enemies faster than it recruits banners.",
    ],
  },
  "episode:2-7": {
    paras: [
      "Addam's claiming becomes a strategy, and the strategy has a body count. Rhaenyra summons the realm's Targaryen bastards and dragon-blooded smallfolk out of every brothel and shipyard and looses the old dragon Vermithor among them — the Red Sowing, in which dozens burn so that two may rise. The hour does not flinch from the arithmetic: the slopes of Dragonstone are a slaughter of hopefuls, and the two who walk out of the fire are not the two anyone would have chosen — Hugh Hammer, a blacksmith's bastard, mastering the Bronze Fury second only to Vhagar, and Ulf the White stumbling drunk onto Silverwing.",
      "The Sowing wins Rhaenyra the war's central resource and unsettles everything else. She now commands more dragons than the greens can ever answer, and the balance that has defined the Dance since Rook's Rest tips hard toward the blacks. But Jacaerys watches smallfolk mount the beasts that were supposed to make his family gods and feels his own claim thinning by the hour — if a tavern boaster can ride a dragon, what exactly is a prince? Aemond, outnumbered in the sky for the first time since he burned his brother, torches Sharp Point rather than let it feed the blacks and finds Rhaenyra's new riders already wheeling over the bay. The war has changed shape, and not in his favor.",
    ],
  },
  "episode:2-8": {
    paras: [
      "The finale is a held breath — every piece moved into place for battles the season deliberately declines to fight yet. The realm draws up its hosts: the Hightower army marching under Daeron, the Lannisters mustering in the west, Cregan's northmen starting their long cold road south, and the Velaryon fleet massing for the Gullet. In Essos, Tyland Lannister wins the Triarchy's ninety ships for the greens with statecraft and a mud-wrestling match, and Admiral Sharako Lohar's fleet turns to break the blockade. The war is about to stop being a series of shocks and become a grinding, continent-wide machine.",
      "Two quieter turns carry the emotional weight. At Harrenhal, Daemon's visions finally reach the one that matters — the Song of Ice and Fire, the dream his brother died murmuring — and when Rhaenyra lands, the rogue prince who spent a lifetime circling other people's thrones kneels to hers, her king consort and her army both, done running at last. And Alicent crosses the water alone to Dragonstone to offer her enemy the war's last off-ramp: take the city, take the crown, spare Aegon. Rhaenyra's answer — 'and what of Aemond?' — closes the season on the truth both women already know: there is no version of this peace that does not still have to be paid for in fire.",
    ],
  },

});
