/* House of the Dragon wiki — houses & orders archive. Original prose. */
Object.assign(WIKI_EXTRA, {

  // ================= the great houses =================
  "house:targaryen": {
    paras: [
      "By the time this story opens, House Targaryen has spent a hundred years being the exception that swallowed the rule. Dragonlords of Valyria who moved their seat to lonely Dragonstone a generation before the Doom, they crossed the narrow sea with three dragons and an army too small to matter, and conquered six kingdoms that had never faced something that could burn an army from the sky. What followed was not merely a dynasty but a monopoly: for a century no other house in Westeros owns a dragon, and the Old King’s long peace rests on that single, terrible fact as much as on any treaty.",
      "The peace has a flaw its own founders built into it, and the Great Council of 101 AC is where the realm first has to look at it directly. Offered a choice between a granddaughter with the better blood claim and a grandson with the accepted one, the assembled lords choose Viserys — a decent, unwarlike man built for feasts rather than fire — and pass over Rhaenys twice in the same afternoon, once for her sex and once for the precedent nobody wants to set. The question is not closed by the vote. It is postponed, and it comes due on his own daughter a generation later, at a cost the council never priced in.",
      "Viserys’s reign is where the crack becomes a fault line: an heir named against custom, a second marriage that gives that heir half-siblings with their own claim, and twenty years of a king refusing to choose between the daughter he swore the realm to and the wife whose sons make that oath look, to her family, like an insult that can still be undone. He dies still refusing to choose out loud, and the ambiguity of his last words is exactly wide enough for two coronations to both claim they were the one he meant.",
      "What the Dance actually does to House Targaryen is worse than losing a war — it is a house discovering that dragonfire respects no bloodline once it is loosed on its own kin. Meleys falls to two dragons at once over Rook’s Rest; Arrax is run down by Vhagar over Shipbreaker Bay in a boy’s first and only real flight; Vermithor and Silverwing change hands to riders with no name to speak of, because a saddle does not ask after lineage. By the time Daemon and Aemond meet above the Gods Eye, the war has stopped being a succession dispute and become a species eating itself, and the lake keeps both riders and gives back neither.",
      "The reckoning left behind is arithmetic, not verdict. A boy-king is crowned over a capital that stormed its own Dragonpit and slaughtered every dragon too young or too tame to fight back; the eggs that hatch afterward are fewer, smaller, and slower to grow than any Targaryen clutch before them. Every dragonlord who follows, all the way to the last Targaryen queen to cross the narrow sea with dragons of her own, inherits a house that has already spent its monopoly and never gets it back at full strength — the Dance is the bill for a hundred years of assuming fire could only ever point outward.",
    ],
    vs: [
      "The most distinctive divergence isn’t a scene or a death, it’s a structure: Fire & Blood is written as history reconstructed from disagreeing sources — the gossiping, court-adjacent fool Mushroom; the pious, sanitizing Grand Maester Munkun; the careful, hedging Septon Eustace — and the book routinely gives two or three competing versions of the same event, some flattering the Blacks, some the Greens, none fully trusted. The show has to pick one version to film, and mostly picks the darker, more dramatic reading; watchers get certainty the book deliberately withholds, and readers meeting the same events on the page are often startled to find George R. R. Martin refusing to say, definitively, what actually happened.",
    ],
  },

  "house:velaryon": {
    paras: [
      "House Velaryon reached Westeros before the dragons did — an old Valyrian seafaring line that settled Driftmark generations ahead of Aegon’s own ancestors, and never forgot the seniority. By the Dance their words, The Old, the True, the Brave, read less like a boast than an itemized résumé: oldest continuous Valyrian blood outside the royal line, truest allies a Targaryen king could ask for, and — under the lord who currently holds High Tide — the bravest voyagers the Sunset Sea has produced in living memory.",
      "That lord is Corlys Velaryon, the Sea Snake, and his nine great voyages to Yi Ti, Asshai and the frozen Thousand Islands made him the richest man in Westeros before the war ever starts, richer even than Casterly Rock. His marriage to Rhaenys — the Queen Who Never Was, twice denied a throne her blood earned — joins the realm’s deepest purse to its most publicly wronged claim, and Corlys spends the rest of his life on one unfinished project: seeing Velaryon blood, however it has to get there, seated somewhere that matters.",
      "The project’s cost is the family itself. Laena dies at Dragonstone birthing twins Vhagar’s saddle will later carry to war; Laenor’s death is staged rather than mourned, a disappearance dressed as a murder so a son with no taste for the succession can vanish from it entirely; and when Corlys’s own dying wish names Rhaenyra’s son heir to Driftmark, his brother Vaemond calls the boy’s parentage a lie to the queen’s own face and loses his head to Dark Sister for it, in a throne room already too used to paying its debts in blood.",
      "In the war itself the Velaryon fleet is the Blacks’ one true advantage the Greens can never match — command of the seas around Dragonstone and the narrow sea both, a navy old enough and large enough that the green council has to go hire the Triarchy just to contest it. Even grief does not slow the house down: shipwrights’ bastards out of Hull, unacknowledged Velaryon blood a generation removed from any title, come forward at the Red Sowing to claim Seasmoke and prove the family line runs wider and further from the legitimate branch than anyone at High Tide had cared to notice before the war made it useful.",
      "Corlys himself outlasts nearly everyone the war costs him — queen, children, a war he backed to the hilt — and the books grant him, almost as an afterthought, the best ending on offer: a seat on the regency council for the boy king who survives, and a death at sea, in his own bed, every horizon he ever sailed finally behind him rather than ahead.",
    ],
    vs: [
      "Laenor Velaryon’s fate is the sharpest fork between the two tellings. Fire & Blood keeps the ambiguity Mushroom’s account first suggests — a staged death, a lover named Qarl Correy, a disappearance across the narrow sea that the chronicle can only shrug at — while the show plays the same beats more plainly on screen, letting the audience watch the fabrication happen rather than reconstruct it after the fact from conflicting testimony. Both versions leave Laenor alive somewhere the story simply stops looking; only the book insists on reminding you it isn’t sure.",
    ],
  },

  "house:hightower": {
    paras: [
      "Oldtown answered to House Hightower before the Seven Kingdoms had a name for themselves, and the tower that gives the house its words — We Light the Way — has stood over the mouth of the Honeywine since long before Aegon’s dragons crossed the narrow sea. Patrons of the Citadel and the Faith of the Seven both, the Hightowers rule the oldest and richest city in Westeros without needing a crown to do it, which makes their eventual reach for one, through marriage rather than conquest, all the more calculated.",
      "Otto Hightower serves as Hand of the King twice, and both terms are studies in the same instinct: send his daughter to comfort a grieving widower, watch the comfort become a marriage, and quietly ensure the Hightower name is never more than one funeral away from the throne room again. Dismissed once by Viserys for pressing his family’s advantage too openly, Otto is recalled soon enough — and it is Otto, more than any single soldier in the war to come, who turns a king’s ambiguous deathbed murmur into a coronation before the rival claimant even hears her father is dead.",
      "That coronation is why the war carries the house’s own heraldry as its name. The Greens are the Greens because Alicent Hightower wore her family’s color to a council convened to discuss her own succession, and the Dance is fought, from the crownlands to the Reach, under the memory of that single wardrobe choice as much as under any dragon banner — a house of scholars and lighthouse-keepers finding itself, almost by accident of fashion, giving its name to a civil war.",
      "The house pays for the throne it built. Ormund Hightower marches west with the Reach’s levies to relieve the capital and does not come home from it; Gwayne holds what Oldtown can still send after; and Otto himself, once King’s Landing falls to the queen he spent a reign undermining, does not survive being caught inside it — the architect of the Greens’ coronation outlived by the war he started, put to the same account he had spent a lifetime keeping for other people.",
      "What outlasts the fighting is the city itself, untouched by siege for the whole of the war, and a queen dowager who becomes the conflict’s most complicated survivor — imprisoned in the keep she once ran, outliving both the husband whose crown she helped choose and the sons she chose it for, the last Hightower standing in a story her own family did more than anyone to start.",
    ],
    vs: [
      "Fire & Blood keeps Viserys’s dying words to Alicent maddeningly ambiguous — a murmur about Aegon that Mushroom and Munkun record differently, and that the text lets the reader weigh rather than resolve, since it may refer to the infant king she bore him or to the ancient prophecy of a prince who was promised. The show dramatizes the same scene with a specific camera-led interpretation, giving the audience Viserys’s intent more legibly than the chronicle ever commits to on the page — one of several places where the show quietly resolves an argument the book is still content to let its own in-world historians lose.",
    ],
  },

  "house:stark": {
    paras: [
      "The Starks of this era carry eight thousand years of Kings of Winter behind them and, for most of the Dance, keep to the old northern habit of watching the south burn itself from a safe distance. Winterfell is a week’s hard riding from anything that matters to the succession crisis brewing in King’s Landing, and Lord Cregan Stark, young and untested when the war begins, has every practical reason to let it stay that way.",
      "He does not, in the end, and the reason is older than the war itself: a friendship, and by some accounts a courtship, formed years earlier when a young Cregan traveled south and came to know Rhaenyra before her marriage to Laenor Velaryon settled her future elsewhere. What survives that disappointment is loyalty rather than resentment — Cregan declares for the Blacks when the crown is stolen, and seals the alliance the old northern way, with a marriage-pact rather than a mere promise, binding Stark children to Targaryen ones so the North’s word outlasts any single lord’s lifetime.",
      "For most of the fighting that pact is a promise on parchment rather than swords in the field — the North is too far and too slow to reach any battle that matters while it is happening, and Winterfell’s contribution to the war’s early and middle years is patience more than muscle. What the North does supply, when it finally moves, is decisive rather than symbolic: a full northern host marching south in the war’s last winter, arriving with the Riverlands’ levies and the Vale’s ships at almost the same hour, three armies converging on a capital that both rival kings have, by then, stopped being able to hold.",
      "What Cregan does with the six days he effectively rules the capital is the chapter the North remembers best — a swift, cold accounting of the war’s remaining traitors and turncloaks, justice dispensed without spectacle, and then, with the boy king’s regency council assembled and the crown settled on a head too young to have started any of it, a march home without a single request for reward. The chroniclers name the episode the Hour of the Wolf, and it is, in miniature, the entire Stark ethic: absolute power taken cleanly, used briefly, and handed back before it can spoil.",
    ],
    vs: [
      "Fire & Blood treats Cregan Stark’s intervention as a matter of historical record — a chronicle entry, briskly summarized, with the Hour of the Wolf itself covering barely a page. The show, needing him as a character rather than a citation, gives him screen time and dialogue the book never affords him, most notably an invented meeting with Jacaerys Velaryon at Winterfell to court northern support in person — a scene the text never stages, since Fire & Blood’s narrator was never in the room for private conversations, only for the treaties they produced.",
    ],
  },

  "house:arryn": {
    paras: [
      "The Arryns hold the Vale from an eyrie no army has ever taken by force, purest Andal blood in the Seven Kingdoms by their own reckoning, and their words — As High As Honor — describe both the fortress’s elevation and the family’s opinion of itself with equal literalness. By the Dance the house’s influence on the crown is already older than the war: Aemma Arryn was Viserys’s first queen, dead in the birthing bed that opened the succession question in the first place, which makes every Targaryen claimant in this conflict at least partly Arryn by blood, whether the Vale ever raises a sword for either side or not.",
      "The Vale itself is ruled, through the whole of the crisis, by Jeyne Arryn — the Maiden of the Vale, unmarried for decades against the wishes of cousins who assume a woman cannot hold a mountain seat any longer than it takes to marry her off it. She proves them wrong for the length of an entire reign, and her example sits in the background of the whole war like an argument already half-won: a woman can rule, has been ruling, and the realm’s great quarrel over whether a queen can sit the Iron Throne is one the Eyrie settled quietly, without a single dragon, years before it ever came to Dragonstone’s attention.",
      "Jeyne declares for the Blacks early and lends the cause more than swords — the Vale becomes a place to send what the war cannot risk losing, sheltering exiled or endangered Targaryen children behind mountains no enemy can easily climb, dragon and rider both kept out of reach of a capital that has already proven it will burn its own nurseries.",
      "When the war’s final reckoning comes, it is Vale ships out of Gulltown, commanded in Jeyne’s name, that reach King’s Landing at nearly the same hour as the northern host and the riverlands’ levies — three loyalties that spent the whole war looking like separate stories converging, in the end, on the same tide. Jeyne outlives the fighting to sit among the small council of regents that steadies the realm for its boy king, proof by administration rather than argument of the very question the war was fought to decide.",
    ],
    vs: [
      "The Vale’s role in the show leans more visibly on Rhaena Targaryen’s time there than the book’s comparatively brief treatment allows — a dramatized hunt through the Vale’s high passes for a wild dragon to claim, expanded for the screen into its own subplot with tension and set-pieces the chronicle format of Fire & Blood was never built to sustain. Jeyne Arryn herself receives considerably less spoken dialogue on screen than her long, quietly consequential rule earns her on the page.",
    ],
  },

  "house:lannister": {
    paras: [
      "Casterly Rock is still, at the Dance’s opening, one of the two or three wealthiest seats in Westeros — gold enough under the hill to have bankrolled the realm more than once — though the house that mines it has recently had to watch a sea lord out-earn it for the first time in living memory. Hear Me Roar is the sigil’s boast; a Lannister always pays his debts is the saying with the sharper edge, and this generation is about to learn how it feels to be the one collecting rather than paying.",
      "The Rock is ruled in this era by twin lords, Jason and Tyland, who divide the house’s ambitions neatly between them: Jason wants a crown of his own reflected glory, a marriage into the royal line and a war that lets the West prove its worth in the field; Tyland wants the ledgers, and takes the office of master of ships and coin in the green council itself, fighting the war from behind a desk in King’s Landing rather than from a saddle.",
      "Jason gets his field and loses everything to it. He marches the western host east to link with the green armies gathering in the riverlands, meets Daemon Targaryen’s coalition of rivermen at the Red Fork, and dies there when his own line breaks — cut down, in the chronicle’s telling, by an unheralded squire the smallfolk immediately nickname Longleaf the Lionslayer, an ignoble end for a lord who wanted nothing more than a glorious one.",
      "His death leaves the Westerlands leaderless at the worst possible hour, and Dalton Greyjoy’s ironborn — bought by the Blacks and unbothered by irony — take the opening, running their longships along an undefended coast and sacking Lannisport itself while the Rock’s heir is still a child too young to answer. For once in the story, the lions are the ones being reaved rather than doing the reaving.",
      "Tyland’s war is quieter and, in the end, crueler: captured when the capital falls to Rhaenyra, he is handed to torturers hunting for the crown’s hidden treasury and kept in the dungeons through the worst of the war’s reversals, released only when the tide turns again — scarred badly enough that the marks outlast the war itself, and restored, eventually, to enough trust that he ends his career as Hand of the King, a Lannister who paid a debt the house never agreed to owe and collected on it anyway.",
    ],
    vs: [
      "Jason Lannister’s death changes killers between page and screen — Fire & Blood credits an obscure squire, Pate of Longleaf, with the kill and the mocking epithet that follows him, while the show hands the moment to Cregan Stark’s northmen instead, folding the West’s humiliation into the North’s growing role in the story rather than leaving it to an anonymous foot soldier the book never mentions again.",
    ],
  },

  "house:tully": {
    paras: [
      "Riverrun is a young seat by the standards of the houses around it — raised to rule the Trident only after Aegon’s Conquest, rather than descending from any line of river kings — and Family, Duty, Honor reads less like an ancient boast than a founding instruction manual for a house that had to learn quickly how to hold ground everyone else in Westeros keeps marching across. The silver trout on red and blue guards the richest, most fertile, and most fought-over crossroads in the Seven Kingdoms, precisely because every army moving between the crownlands and anywhere else eventually has to cross a Tully ford to get there.",
      "By the Dance, that guardianship rests in hands too old to hold it firmly. Lord Grover Tully is ancient and ailing, more a name invoked for legitimacy than a lord actually issuing commands, and the gap between his nominal authority and his actual capacity is exactly the kind of opening the riverlands’ more quarrelsome bannermen have been waiting for — a liege lord too soft-gripped to tell the Brackens and Blackwoods, or the Freys at the Twins, that their private arithmetic has to wait on his.",
      "The Trident becomes, as a direct result, the single most fought-over stretch of ground in the entire war — not because Riverrun commands a great host into the field, but because everyone else’s host has to pass through, over, or beside its lands to reach anywhere that matters. Daemon Targaryen makes Harrenhal his own base of operations within the riverlands almost as soon as the war begins, and the Battle of the Red Fork, which costs Jason Lannister his life and the Westerlands its leadership, is fought on Tully soil between armies that barely bothered to ask Riverrun’s opinion first.",
      "What actually holds the Tully banner to the Blacks through the fighting is not Grover but the grandson increasingly acting in his stead, Elmo Tully — a steadier hand than his grandfather’s failing one, and the man who eventually musters what the riverlands can still put in the field for the war’s final push, after two years of other people’s armies tearing up the ground he is supposed to be lording over.",
      "That push arrives at King’s Landing in the war’s last act, a riverlands host under Elmo converging on the capital in the same narrow window as Cregan Stark’s northmen and Jeyne Arryn’s ships out of Gulltown — three loyalties, three separate roads south, meeting at almost the same hour outside a city that has, by then, run out of anyone left to defend it. Riverrun ends the Dance scarred by more marching feet than any other great seat in the war, on the winning side of a fight it spent most of two years merely absorbing rather than commanding.",
    ],
    vs: [
      "The show leans on Daemon’s occupation of Harrenhal, staged at length on screen, to carry most of the riverlands’ presence in the war, while giving Lord Grover Tully’s incapacity and Elmo Tully’s quiet rise to actual command comparatively little airtime by comparison — a chronicle-level detail Fire & Blood spells out plainly but that the screen version mostly leaves implied. As of its current run, the show has also not yet dramatized the war’s final convergence on the capital that the book credits jointly to Elmo Tully, Cregan Stark and Jeyne Arryn, so the riverlands’ part in that closing act remains, for now, a page-only chapter.",
    ],
  },

  "house:baratheon": {
    paras: [
      "The Baratheons of Storm’s End are, even by the Dance’s standards, a house that has learned to let other people’s wars come to it rather than the reverse — Ours Is the Fury sits over a fortress that has never fallen to siege or storm, and Lord Borros Baratheon intends to keep both records intact by making the crisis over the Iron Throne someone else’s problem for as long as the crown’s two halves are willing to bid for the privilege of asking.",
      "That bidding is the house’s whole role in the opening act of the war. Borros has four daughters and one young son — the Four Storms, the court calls the girls, Cassandra, Maris, Ellyn and Floris — and a marriage into any of them is worth an army the crown badly needs. Both sides know it, and both send a Targaryen prince south to Storm’s End to ask.",
      "Aemond arrives first, or arrives better, and leaves betrothed to Floris — sealing Storm’s End for the Greens in the same season that Lucerys Velaryon, sent south on the same errand for his mother, meets Aemond’s dragon over Shipbreaker Bay instead of a wedding contract, and never completes the journey home. Whatever chance the Blacks had at Storm’s End dies with him, at almost the same hour the pact that closes it off is signed.",
      "Even bought, the Baratheons fight cautiously — Borros holds his own counsel about how hard to commit, and the stormlands’ levies arrive to the war’s later campaigns more as a slow reinforcement than a decisive strike, a house content to have picked a side without betting its whole strength on the outcome.",
      "The caution pays off in the ledger that matters most to a great house: survival. Where Velaryon and Targaryen both come out of the Dance gutted, Storm’s End comes through with its line and its castle both intact, a rare great house that gambles on a marriage instead of a battlefield and finds the smaller wager the wiser one.",
    ],
    vs: [
      "The chronicle behind Fire & Blood is openly unsure whether Lucerys’s death over Shipbreaker Bay was murder or a fatal accident of storm and temper — Mushroom’s account and the more measured chroniclers disagree on how much Aemond intended, and the text preserves the disagreement rather than settling it. The show removes the ambiguity almost entirely, staging the pursuit and its outcome with enough visual clarity that Aemond’s intent, however conflicted in the moment, reads as considerably less accidental on screen than the competing sources ever let the page confirm.",
    ],
  },

  "house:greyjoy": {
    paras: [
      "The Iron Islands keep their own counsel through most quarrels that do not touch salt water, and the ironborn’s relationship to the Dance is characteristically transactional: We Do Not Sow means, among other things, that Pyke has no intention of planting itself firmly in either camp until it is clear which crown is worth the planting.",
      "Lord Dalton Greyjoy is courted by both sides for the same reason — a fleet that could contest the Velaryon navy’s command of the western waters is worth more to whichever crown secures it than almost any land army on offer. The Greens move first, dangling the mastership of ships and the admiralty itself if Dalton will bring the Iron Fleet around to fight Corlys Velaryon directly. Dalton, characteristically, waits to hear the other offer before answering either.",
      "It is Daemon Targaryen, reading the Red Kraken’s temperament better than the green council manages to, who suggests the winning approach is not an office but an appetite — appeal to what Dalton actually wants, which is plunder rather than rank, and the Blacks close the deal. Rather than risk his ships in a fleet action against Velaryon’s navy, Dalton turns the Iron Fleet loose on an undefended coast instead, at exactly the moment Jason Lannister’s death leaves the Westerlands without a lord capable of answering him.",
      "The raids that follow — Lannisport sacked, gold and captives both taken, a rich coastline picked clean while its garrison is still arguing over who commands it — serve no grand strategy beyond Pyke’s own enrichment, and that is rather the point. The Iron Islands emerge from a mainland civil war richer, unsieged, and entirely unbothered by which crown eventually wins it, the purest demonstration in the whole Dance of an old ironborn instinct: why sow a crop you can simply take from someone else’s harvest.",
    ],
    vs: [
      "The negotiation between Dalton Greyjoy and both crowns is largely a matter of chronicle summary in Fire & Blood — offers made and weighed off the page, reported after the fact rather than dramatized as they happen. The show has more room to let Dalton’s calculating, opportunistic character play out in scene rather than in retrospect, giving him a more immediate, personality-driven presence than the source material, which mostly tracks him through the consequences of his choices rather than the choices themselves.",
    ],
  },

  "house:tyrell": {
    paras: [
      "Highgarden enters the Dance in an unusual position for the Reach’s ruling house: its lord is an infant, too young to hold a council seat let alone command an army, and the regency governing in his name has exactly one overriding priority — protect the child’s inheritance, whichever crown eventually wins the war raging around it.",
      "That leaves Growing Strong without a voice loud enough to commit the whole of the Reach to either banner, and the vacuum does not sit empty for long. Individual Reach lords, cities and houses make their own arrangements rather than wait for a decree Highgarden is in no position to issue — Oldtown and the Hightowers most visibly, bound to the Greens by blood rather than by any Tyrell instruction, but plenty of smaller Reach banners besides, each calculating its own odds independently of the golden rose.",
      "The practical effect is a Reach that never arrives at the war as the single overwhelming force its granaries and manpower could, in theory, have made it — fragments of Reach strength show up on both sides of several campaigns, but the bloc vote that could plausibly have ended the Dance in a season simply never assembles, because there is no one at Highgarden with the standing to call for it.",
      "What the regency buys with its caution is exactly what it intended: Highgarden reaches the war’s end essentially untouched, its granaries full, its child lord alive and inheriting a Reach that other houses bled to hold while his own sat the fighting out almost entirely.",
    ],
    vs: [
      "House Tyrell’s Dance-era abstention is treated almost identically by both tellings — which is to say, barely treated at all. Fire & Blood gives Highgarden’s neutrality a few explanatory lines and moves on; the show, built around characters who can appear on screen, has essentially no Reach politics to dramatize at all during this period, making the Tyrells one of the rare great houses where page and screen actually agree by mutual, near-total silence.",
    ],
  },

  "house:martell": {
    paras: [
      "It is worth stating plainly what the era itself makes obvious and later centuries tend to blur: during the Dance, Dorne is not part of the Seven Kingdoms at all. The marriage that eventually binds Sunspear to the Iron Throne is still decades in the future, and the Princes of Dorne who watch this war unfold do so as rulers of a fully sovereign country, owing King’s Landing nothing — not troops, not taxes, not so much as an opinion.",
      "That sovereignty was purchased the hard way, against dragons rather than alongside them — Aegon’s own attempts to add Dorne to his conquest broke against its deserts and its refusal to fight the war Targaryen strategy expected, costing the dynasty dragons of its own in the process. A Targaryen civil war two generations later reads, from Sunspear, less like a crisis to be weighed in than like a debt finally coming due on its own account, with no help required from the far side of the Red Mountains to collect it.",
      "So Dorne does exactly what its history taught it to do when Targaryens turn violent among themselves: nothing, deliberately and at length. No Dornish banner marches for either crown, no Dornish port opens to either fleet, and every dragon spent burning a fellow dragon over the Gods Eye or Shipbreaker Bay is one more dragon that will never again threaten a Dornish garden — an outcome Sunspear can only regard as, at minimum, no great loss.",
      "The policy holds because it costs Dorne nothing to hold it. Unbowed, Unbent, Unbroken is not a wartime slogan improvised for this crisis; it is simply the settled, generations-old Martell answer to any Targaryen quarrel, and the Dance changes that answer not at all — the union with the Iron Throne that finally arrives will come from a marriage bed a lifetime later, not from anything decided in this war.",
    ],
    vs: [
      "Here too the tellings converge by omission rather than by contradiction. Fire & Blood affords Dorne’s Dance-era neutrality only passing mention, consistent with a kingdom that has deliberately made itself peripheral to Targaryen affairs; the show, with no Dornish characters or plotlines active in this period at all, simply leaves Sunspear off the map entirely — the rare case where a house’s absence from the screen is not really a divergence, since the book was never planning to linger there either.",
    ],
  },

  "house:frey": {
    paras: [
      "The Freys are, by the standards of the Riverlands’ old blood, embarrassingly new money — a house that grew rich on tolls rather than conquest, holding the only crossing of the Green Fork and taxing every cart, army and rumor that needs to use it. We Stand Together is the motto; what the house actually stands on, more precisely, is the bridge, and the family has never pretended otherwise.",
      "Nominally the Freys answer to Riverrun, but old Lord Grover Tully’s grip has gone soft by the time the war reaches the riverlands, and a house that has spent generations being condescended to by its social betters is not about to let a weakened liege dictate its wartime loyalties without extracting something for the privilege.",
      "What the Blacks extract in return for that loyalty is speed: rather than wait for a courier and a treaty, Daemon Targaryen flies to the Twins himself, Caraxes landing at the one crossing that can make or break every riverlands campaign to come, and secures the bridge in person with promises rather than swords — favor, marriage, advancement, the currency a house of this pedigree wants most and has the least of on its own.",
      "The bridge stays friendly for the length of the war, and the value of that single decision compounds with every army that crosses it unopposed — riverlands levies, and eventually the northern host and Vale ships converging on King’s Landing in the war’s final act, all of them owing the Freys nothing more than a toll they were only too glad to collect. Readers who know what this family becomes a century of grievance later may find the promises Daemon leaves at the Twins land rather differently than they were meant to.",
    ],
    vs: [
      "Daemon’s personal visit to secure the crossing is a moment the show can simply stage — dragon, bridge, bargain, in a single scene — while Fire & Blood reports the same alliance more as settled fact than dramatized negotiation, the kind of transaction the chronicle records in a sentence because no one thought to write down exactly what was promised in the room. The gap is less a contradiction than the usual difference between a history book and the camera that has to put someone inside it.",
    ],
  },

  // ================= courts, orders & factions =================
  "group:blacks": {
    paras: [
      "The Blacks take their name, and much of their identity, from a single afternoon: the black gown Rhaenyra is said to have worn to a council convened to discuss the very question of her own succession, set against the green her rival wore to the same room. Grand Maester Munkun’s chronicle turns the color into shorthand for the whole faction almost immediately, and by the time the war is a year old, black has stopped being a wardrobe choice and become a banner.",
      "What the color organizes is, in practice, the bulk of the realm’s naval and outlying strength: the Velaryon fleet that Corlys built into the richest navy in Westeros, the Vale’s ships and mountain refuge under Jeyne Arryn, the North’s eventual weight under Cregan Stark, and riverlords like the Blackwoods who see in Rhaenyra’s cause a chance to settle older, more local scores under royal cover. It is a coalition assembled from the edges of the map inward, in contrast to a rival faction rooted in the crownlands and the Reach.",
      "The faction’s defining gamble is the Red Sowing at Dragonstone — a desperate call for any claimant with a drop of Valyrian blood, highborn or not, to try the three dragons left riderless by the war’s early losses. It costs lives, burns several hopefuls outright, and produces, against every rule the Targaryens had quietly kept for a century, dragonriders with no family name worth mentioning — a wager that changes what a dragon rider is allowed to look like, permanently, whether the Greens like it or not.",
      "By the war’s last year the Blacks are less a single court than a coalition running on momentum and grief — a queen dead, a king dead, and armies converging on King’s Landing more out of accumulated obligation than any single living leader’s command. That the coalition still wins the crown for a Targaryen line, if not for the queen it started the war to crown, says as much about the strength of what Rhaenyra built as it does about what the fighting cost her personally.",
    ],
    vs: [
      "The show renders the black-versus-green council scene as the war’s clean point of origin — two dresses, two colors, a single afternoon that explains everything after it. Fire & Blood is less tidy about it: the color-coding is explicit at that one council and then applied more loosely and retroactively by the chroniclers describing everything that follows, which means the book’s Dance feels, on the page, considerably messier and less choreographed than the visually clean binary the screen version commits to from its opening scenes onward.",
    ],
  },

  "group:greens": {
    paras: [
      "The Greens are named for the same afternoon that names their rivals — Alicent Hightower’s green gown at the council following Viserys’s death — and the color sticks to a faction built around a different center of gravity entirely: the crownlands court itself, plus the great western and southern houses whose loyalty runs through marriage and office rather than distance and old grudges.",
      "Otto Hightower supplies the faction’s strategy and Criston Cole its sword arm, and between them they move faster than their rivals at the one moment speed matters most — Aegon crowned in the Dragonpit before Rhaenyra, still at Dragonstone, has even confirmed her father is dead. That head start defines the whole first half of the war: the Greens hold the capital, the machinery of government, and the initiative, while the Blacks spend the opening act simply trying to catch up to a coronation that has already happened.",
      "What the faction has to spend that advantage on is blood it can less easily replace than its rivals — Aemond and Vhagar carry most of the Greens’ dragon strength alone for long stretches of the war, Ormund Hightower’s death costs the Reach’s relief column its commander, and a king who never wanted the crown in the first place proves, on the whole, a less effective wartime leader than the men who put him there assumed he would be.",
      "By the war’s final reckoning the Greens hold the throne on paper and very little else — a capital gutted by its own mob, a king ruling in constant pain over ashes, and a faction whose founding coronation, so swift and so decisive at the start, buys it barely more time on the Iron Throne than the rival claimant it was designed to preempt.",
    ],
    vs: [
      "The competing chroniclers behind Fire & Blood disagree more openly about the Greens than about almost any other faction in the war — Mushroom’s account is frequently hostile to Aegon II and Alicent both, while Munkun’s is comparatively more sympathetic to the crown that eventually commissioned histories of its own reign. The show, needing one consistent read for a continuing cast, largely resolves that argument in the more sympathetic direction as the war wears on, particularly for Aegon himself, in a way the book’s dueling, unreconciled sources never fully commit to.",
    ],
  },

  "group:kingsguard": {
    paras: [
      "Sworn for life is the order’s whole premise — seven knights in white cloaks, oaths that outlast any single reign, loyalty meant to sit above politics rather than inside it. Aegon the Conqueror founded the order on the assumption that there would only ever be one king to protect at a time; the Dance is the first crisis in the dynasty’s history to test what happens when that assumption simply stops being true.",
      "It fails the test the same night Viserys dies. Ser Criston Cole throws his white cloak behind Aegon’s coronation and becomes the Greens’ most effective sword; other members of the order stay with Rhaenyra rather than the crown that has just changed hands out from under her, an act the chronicles struggle to even name cleanly, since a Kingsguard sworn to a queen who has not yet been crowned exists in a gap the order’s own vows never anticipated.",
      "No single episode captures the order’s collapse more starkly than the Cargyll twins — Erryk and Arryk, indistinguishable in white cloaks and near-identical faces, ending up on opposite sides of the same war and meeting, at last, in single combat neither one survives, each killed by the brother he was raised beside rather than by any enemy either of them chose. Steffon Darklyn, for his part, carries Viserys’s own crown to Rhaenyra at Dragonstone as an act of loyalty the split order can still occasionally manage, before dying defending her cause when the Dragonpit itself is stormed by a mob that answers to neither white cloak nor black banner.",
      "What the order looks like by the war’s end is less a single sworn brotherhood than a scattering of individual, contradictory oaths — proof that sworn for life was always a promise about duration, never about which king, or queen, a given knight would end up dying for.",
    ],
    vs: [
      "The Cargyll twins’ duel is staged directly on screen in the show, choreographed and unambiguous, brother killing brother in a corridor with the audience given every blow. Fire & Blood’s account is secondhand and reconstructed after the fact — no chronicler was in the room, and the book has to describe two men found dead together rather than show the fight that killed them, leaving the duel’s exact particulars, like so much else in the source material, a matter of informed reconstruction rather than eyewitness record.",
    ],
  },

  "group:city-watch": {
    paras: [
      "The gold cloaks exist, in this era, largely because Daemon Targaryen decided King’s Landing’s law needed teeth rather than a ledger — two thousand men recruited, armed and paid to actually enforce the crown’s law in a city that had mostly been policing itself by neglect, a project Daemon treated as seriously as any military command he ever held and considerably more personally than most.",
      "Command passes, after Daemon, to Harwin Strong — Breakbones, whose nickname the Watch takes rather literally as a statement of intent — and under Strong the gold cloaks become as much a political instrument as a police force, an army inside the capital’s walls that answers, in practice, to whoever currently holds its captain’s loyalty rather than to the crown in the abstract.",
      "That is precisely the vulnerability the Dance exposes. Once Daemon is gone from the city and Harwin Strong is sent away from it, the Watch’s loyalty stops being a settled question and becomes a running negotiation — two thousand armed men in a capital that changes hands more than once during the war, and a force whose willingness to hold the streets, or open them, ends up mattering as much to who actually controls King’s Landing at any given hour as any army approaching from outside it.",
    ],
    vs: [
      "The show dramatizes the Watch’s founding directly, with Daemon personally arming and drilling the recruits in a sequence built for the screen; Fire & Blood treats the same reform more as an administrative fact of Daemon’s early career, worth a paragraph rather than a set piece, consistent with a source that generally prefers to summarize institutions rather than watch them being built.",
    ],
  },

  "group:dragonseeds": {
    paras: [
      "The Red Sowing is the Blacks’ answer to a problem no amount of ships or riverlords could solve on their own: three dragons at Dragonstone with no rider, and a war being decided, increasingly, by whoever has more of them in the air. Rhaenyra’s solution breaks a rule the dynasty had quietly kept for a century — that dragons answer to Valyrian blood of acknowledged, legitimate descent — by throwing the call open to anyone in the city who can claim so much as a rumor of dragon ancestry, highborn or gutter-born alike.",
      "The Sowing is less a ceremony than a culling. Dozens come forward to try Vermithor and Silverwing, dragons old enough and short-tempered enough to kill outright rather than merely refuse a rider, and several candidates burn in front of the whole assembled crowd before anyone succeeds — a public, repeated demonstration that dragon blood is not a courtesy title but a physical fact some claimants simply do not possess.",
      "The ones who do succeed change the war’s arithmetic and its politics at the same time: Hugh Hammer claims Vermithor, the Bronze Fury, second-oldest living dragon in the world; Ulf White claims Silverwing; and Addam of Hull, a shipwright’s son with more claim to Velaryon blood than anyone had previously bothered to acknowledge, claims Seasmoke. None of the three had a title worth mentioning a season earlier, and all three are, by the Sowing’s end, riders of dragons great lords would have killed for.",
      "Outside the Sowing’s official roll entirely, a young woman known only as Nettles claims the wild dragon Sheepstealer near Driftmark on her own initiative, unsanctioned and unexpected — proof, alongside the Sowing itself, that the war’s single greatest disruption to a century of Targaryen orthodoxy was simply discovering how many people the old rules had been quietly excluding all along.",
    ],
    vs: [
      "Nettles’s fate afterward is one of Fire & Blood’s most openly disputed episodes — Mushroom’s account has Daemon killing her in a fit of jealous rage after suspecting an affair with the dragon rather than the woman, while other sources have her simply flying away from the war entirely and surviving it, unresolved. The show has to commit to a single version for its ending; the book, characteristically, refuses to tell you which chronicler to believe.",
    ],
  },

  "group:triarchy": {
    paras: [
      "The Triarchy predates the Dance by a generation — an alliance of Lys, Myr and Tyrosh formed to run the Stepstones’ shipping tolls under a single, profitable authority, until a mercenary captain called the Crabfeeder turned that authority into a reign of terror over every vessel trying to pass. It took Daemon Targaryen and Corlys Velaryon years of grinding campaign to break the Crabfeeder’s hold on the rocks, a war that made Daemon’s reputation for violence and impatience in equal measure, long before he had a civil war of his own to fight.",
      "By the time the Dance itself begins, the original Triarchy has splintered, but the alliance’s name and its ships have not entirely left the story — reconstituted, in this era, as a hired fleet under the command of Sharako Lohar, ninety warships strong, engaged not out of any old loyalty to the Stepstones but as paid muscle for whichever crown can afford the toll.",
      "It is the green council, and Otto Hightower’s treasury in particular, that meets the price — buying a fleet the Greens cannot otherwise match against Velaryon seapower, and putting a mercenary admiral’s ships between the black queen’s navy and whatever coastline the Greens most need protected. The Three Daughters end the war as they entered the Stepstones generations earlier: for hire, and loyal exactly as long as the money holds.",
    ],
  },

  "group:strong": {
    paras: [
      "House Strong holds Harrenhal in this generation more by royal appointment than by ancient right — able administrators rather than old blood, and Lyonel Strong’s service as Hand of the King under Viserys is the kind of quiet, competent loyalty that makes the family briefly indispensable to a crown that has never quite trusted the old riverlands houses around them.",
      "That competence runs in the family unevenly. Harwin, called Breakbones, commands the City Watch with real ability and becomes, almost as a side effect of his closeness to the royal household, the center of the paternity rumor that will eventually poison the succession — the whispered suggestion that Rhaenyra’s sons owe their dark hair to Harrenhal rather than to Laenor Velaryon, a rumor the family can neither confirm nor kill.",
      "Larys, called Clubfoot for a lame leg that keeps him out of every hall’s notice until it suits him not to be, inherits Harrenhal by the ugliest method available — a fire that kills his own father and brother in what is recorded, with visible discomfort, as an accident — and spends the war that follows as Alicent and then Aegon’s master of whisperers, trading secrets to whichever side of the conflict currently needs them most, a man who wins by making sure no one in the room ever quite knows what he already knows.",
      "Alys Rivers, a bastard of the house with a claim on Harrenhal’s blood but none on its name, becomes one of the war’s stranger footnotes — associated in its later stages with Aemond’s occupation of the castle, and with a reputation for knowledge the smallfolk are inclined to call witchcraft rather than anything so ordinary as intelligence.",
    ],
    vs: [
      "Larys Strong’s ultimate fate is treated with more finality on screen than in the chronicle, which loses track of him in the war’s later confusion rather than closing his story outright; the show similarly gives Alys Rivers a more direct, dramatized relationship to Aemond, including implications the book leaves considerably vaguer, consistent with a text more interested in what Harrenhal’s secrets did to the war than in settling every private arrangement that produced them.",
    ],
  },

  "group:royce": {
    paras: [
      "The Royces of Runestone carry First Men blood older than the Andals who eventually settled the Vale around them, bronze-armored and proud of a pedigree that predates most of the mountain lords who now nominally rank above them — We Remember is not sentiment so much as a standing claim to seniority.",
      "The house’s entanglement with this era’s great quarrel runs through a single unhappy marriage: Rhea Royce, heiress of Runestone, wed to Daemon Targaryen at a point in his career when a rich bride was worth more to him than a happy one, and a match neither party pretended to want. She rules Runestone in her own right for years afterward while her husband is elsewhere, entirely unbothered by his absence and, by most accounts, glad of it.",
      "Rhea dies before the Dance itself begins, in a riding accident at Runestone that frees Daemon to marry first Laena Velaryon and later Rhaenyra — a death convenient enough, at exactly the moment it happens, that suspicion follows Daemon for the rest of the story regardless of what actually happened on that mountainside, whispered about by enemies who need no proof and believed by no one who ever much liked him to begin with.",
    ],
    vs: [
      "Fire & Blood keeps Rhea Royce’s death technically accidental and leaves the suspicion around it as background rumor, one more unproven accusation in a long list Daemon accumulates over his career. The show stages the scene with enough visual suggestion — Daemon present, the fall convenient, his reaction more calculating than grieved — that the audience is nudged considerably closer to certainty of his guilt than the book’s more deliberately unresolved version ever allows.",
    ],
  },

  "group:blackwood": {
    paras: [
      "Raventree Hall keeps the old gods in a riverlands that converted to the Seven generations ago, and the Blackwoods have spent nine hundred years treating that difference as a matter of pride rather than eccentricity — a house that never stopped being what the rest of the Trident used to be, feuding the entire time with the Andal-converted Brackens across the stream from them.",
      "When Daemon Targaryen comes to the riverlands looking for allies, Willem Blackwood does not need much persuading — declaring for the Blacks under the old gods’ banner is both a genuine political calculation and, more immediately satisfying, a chance to fight the Brackens with a crown’s authority behind him rather than merely a neighbor’s grudge.",
      "The house’s war, in practice, is fought as much across the stream that divides Raventree from Stone Hedge as it is against any green army proper — a national civil war providing cover and legitimacy for a much older, much more local one that neither family particularly wants to let go of, crown or no crown.",
    ],
  },

  "group:bracken": {
    paras: [
      "Stone Hedge sits across the stream from Raventree Hall and has spent nine centuries defining itself largely in opposition to the house on the other side of it — Andal-converted where the Blackwoods kept the old gods, and never inclined to let a shared liege lord at Riverrun settle an argument that predates every Tully who ever tried.",
      "When the Dance reaches the riverlands, the Brackens’ choice of the Greens has less to do with any conviction about Aegon’s claim than with a simpler arithmetic: the Blackwoods went black, and Stone Hedge has never in nine hundred years missed a chance to stand wherever Raventree is not standing.",
      "The result is a riverlands war fought on two overlapping fronts at once — the national quarrel between Blacks and Greens layered directly over a local one between Bracken and Blackwood that both houses would happily keep fighting long after either crown has been settled, one grudge using the other as cover for its own continuation.",
    ],
  },

  "group:darklyn": {
    paras: [
      "Duskendale ruled itself as an independent kingdom for centuries before King’s Landing existed as anything more than a fishing village on the Blackwater’s bank, and House Darklyn has never entirely let go of the seniority that history grants them — bent to the dragon generations ago, but proud, still, of a port that answered to no one before the Targaryens arrived to change that.",
      "Gunthor and Steffon Darklyn carry that old pride into the Blacks’ cause without hesitation, and it is Steffon who performs one of the war’s most quietly loaded gestures — retrieving Viserys’s own crown and carrying it to Rhaenyra at Dragonstone, a physical symbol of the succession the Greens had just tried to steal, delivered by a house old enough to remember when crowns in this part of the world were Darklyn property rather than Targaryen.",
      "Steffon does not survive the war his loyalty helped legitimize, killed defending the queen’s cause when the mob turns on the Dragonpit itself — a death that costs Duskendale one of its own without costing the house its standing, a port city that entered the crisis with an old grievance about who used to rule here and leaves it having proven, at least, which side its loyalty was worth.",
    ],
  },

});
