/* A KNIGHT OF THE SEVEN KINGDOMS — the people of the tale.
   house: a "primary" great-house id for the card's fallback shield (null = none).
   Family links (father/mother/spouse/children/siblings) refer to other entries by
   exact name — and are kept SPOILER-FREE: they show a person's public, first-known
   kin, never a later reveal. blurb never states a character's fate; the gated
   "Alive as of…" line and the death lists carry that. death {s,e} / bookDeath {b,ch}
   exist ONLY to drive that gated status and are never shown in the blurb.
   only: "book" hides a person from the show's telling entirely.
   Group membership lives in js/groups.js, not here. */

const CHARACTERS = {
  // ================= the hedge knight and his squire =================
  "Ser Duncan the Tall": { house: null, born: "Flea Bottom, King's Landing",
    blurb: "Dunk: a boy of Flea Bottom who grew nearly seven feet tall, squire to old Ser Arlan of Pennytree since childhood. Slow to anger, honest to a fault, and armed with the old man's sword, shield, and lessons — 'sworn shield of the weak, protector of the innocent,' whether he ever heard the words said over him or not." },
  "Egg": { house: "targaryen", born: "Summerhall", father: "Prince Maekar Targaryen",
    siblings: ["Aerion Brightflame", "Daeron Targaryen", "Aemon Targaryen"],
    blurb: "A bald, sharp-tongued little stableboy who attaches himself to the tallest knight he can find — and squires far too well for a stableboy. His head is shaved for an excellent reason: hair like his would name him to every man in Westeros." },
  "Ser Arlan of Pennytree": { house: null, born: "Pennytree",
    blurb: "The old man: a hedge knight of the riverlands who served half a hundred lords and kept his honor through all of it. He took a starved Flea Bottom boy as his squire and taught him everything — the lance, the sword, and what a knight is for.",
    death: { s: 1, e: 1, how: "Died of a chill on the road to Ashford" },
    bookDeath: { b: 1, ch: 1, how: "Died of a chill on the road to Ashford" } },

  // ================= House Targaryen =================
  "King Daeron II Targaryen": { house: "targaryen", born: "King's Landing",
    children: ["Baelor Breakspear", "Aerys I Targaryen", "Prince Maekar Targaryen"],
    blurb: "Daeron the Good: the king who joined Dorne to the realm with marriages instead of armies, and paid for it with the Blackfyre Rebellion. Bookish, mild, and stronger than his enemies ever understood — the peace of the age is his making.",
    bookDeath: { b: 2, ch: 1, how: "Taken by the Great Spring Sickness" } },
  "Baelor Breakspear": { house: "targaryen", born: "King's Landing", father: "King Daeron II Targaryen",
    siblings: ["Aerys I Targaryen", "Prince Maekar Targaryen"], children: ["Valarr Targaryen"],
    blurb: "Prince of Dragonstone, Hand of the King, heir to the Iron Throne — and the man who broke Daemon Blackfyre's charge at Redgrass Field. Dark-haired like his Dornish mother, and reckoned the finest knight and best man in the realm.",
    death: { s: 1, e: 6, how: "Died of his brother's mace blow after the trial of seven" },
    bookDeath: { b: 1, ch: 10, how: "Died of his brother's mace blow after the trial of seven" } },
  "Valarr Targaryen": { house: "targaryen", born: "King's Landing", father: "Baelor Breakspear",
    blurb: "The Young Prince: Baelor's elder son, brown-haired with a silver streak, courteous and unremarkable — a champion at Ashford by birth more than by lance.",
    bookDeath: { b: 2, ch: 1, how: "Taken by the Great Spring Sickness" } },
  "Aerys I Targaryen": { house: "targaryen", born: "King's Landing", father: "King Daeron II Targaryen",
    siblings: ["Baelor Breakspear", "Prince Maekar Targaryen"],
    blurb: "The king's second son: bookish beyond even his father, more interested in dusty prophecies than in ruling or fathering heirs. The age will ask more of him than he ever wanted to give." },
  "Prince Maekar Targaryen": { house: "targaryen", born: "King's Landing", father: "King Daeron II Targaryen",
    siblings: ["Baelor Breakspear", "Aerys I Targaryen"],
    children: ["Aerion Brightflame", "Daeron Targaryen", "Aemon Targaryen", "Egg"],
    blurb: "The king's fourth son, Prince of Summerhall: hard, proud, and forever in his brother Baelor's shadow. He commanded the second line at Redgrass Field; the realm gave Baelor the glory. His sons are his pride and his grief in equal measure." },
  "Aerion Brightflame": { house: "targaryen", born: "Summerhall", father: "Prince Maekar Targaryen",
    siblings: ["Daeron Targaryen", "Aemon Targaryen", "Egg"],
    blurb: "Maekar's second son, beautiful as a dream and cruel as a nightmare, who half believes he is a dragon in human skin. Wine, vanity, and viciousness — and a prince's immunity, almost always." },
  "Daeron Targaryen": { house: "targaryen", born: "Summerhall", father: "Prince Maekar Targaryen",
    siblings: ["Aerion Brightflame", "Aemon Targaryen", "Egg"],
    blurb: "Daeron the Drunken: Maekar's eldest, a soft, amiable man who wants nothing to do with swords or crowns — only a full cup. His dreams, though, have an unsettling way of coming true; he dreamed a dragon fell at Ashford." },
  "Aemon Targaryen": { house: "targaryen", born: "Summerhall", father: "Prince Maekar Targaryen",
    siblings: ["Aerion Brightflame", "Daeron Targaryen", "Egg"],
    blurb: "Maekar's third son, gentle and clever, sent to the Citadel to forge a maester's chain of his own free will. A very long road is ahead of him — most of it, one day, in black." },
  "Brynden Rivers": { house: "targaryen", born: "King's Landing",
    blurb: "Bloodraven: a legitimized bastard of King Aegon the Unworthy and a Blackwood mother — albino, red-marked, and a sorcerer if the smallfolk are believed. Master of whisperers and, under King Aerys, Hand: a thousand eyes, and one. It was his weirwood arrow that ended Daemon Blackfyre at Redgrass Field." },

  // ================= House Blackfyre & its cause =================
  "Daemon II Blackfyre": { only: "book", house: "blackfyre", born: "In exile",
    blurb: "Third son of Daemon Blackfyre the pretender, raised in Tyrosh under Bittersteel's eye. A dreamer of dreams who believes prophecy will do a rebellion's work for it — golden, charming, and better with a fiddle metaphor than an army." },
  "John the Fiddler": { only: "book", house: "blackfyre", born: "Somewhere golden",
    blurb: "A laughing, open-handed mystery knight bound for Lord Butterwell's wedding, who jousts like a lord and claims to dream true dreams — including one with Dunk in it, wearing a white cloak. There is rather more to him than the fiddle." },
  "Lord Gormon Peake": { only: "book", house: "peake", born: "Starpike",
    blurb: "Lord of Starpike — and, he would tell you, rightfully of Dunstonbury and Whitegrove too, forfeited when the Peakes backed the black dragon. Sour, scheming, and convinced one more throw of the dice will win his castles back." },
  "Black Tom Heddle": { only: "book", house: null, born: "The riverlands",
    blurb: "Lord Butterwell's grim good-son, a black-bearded knight with a dark reputation and a sword always half-drawn. Whatever is rotten at Whitewalls, he is near the middle of it.",
    bookDeath: { b: 3, ch: 11, how: "Cut down by Dunk at the gates of Whitewalls" } },
  "Ser Alyn Cockshaw": { only: "book", house: null, born: "The Reach",
    blurb: "A plump, well-born knight in the Fiddler's company, whose courtesy curdles wherever a certain hedge knight is concerned. Jealousy is an underrated poison.",
    bookDeath: { b: 3, ch: 8, how: "Went down a well at Whitewalls, with help" } },
  "Lord Ambrose Butterwell": { only: "book", house: "butterwell", born: "Whitewalls",
    blurb: "Lord of the Milkhouse, briefly and badly Hand of the King under Daeron II. Rich as cream, timid as milk — a man who wants the rewards of treason without the risks, and hosts a wedding that serves him neither." },

  // ================= the tourney at Ashford =================
  "Tanselle": { house: null, born: "Dorne",
    blurb: "Tanselle Too-Tall, a Dornish puppeteer with a quick brush and quicker strings, who paints an elm and a shooting star on a hedge knight's shield. Not too tall by half, in Dunk's considered opinion." },
  "Steely Pate": { house: null, born: "The Reach",
    blurb: "Master armorer of Ashford Meadow: gruff, fair-dealing, and proud of his steel. He arms the tall hedge knight properly — and stands by his work when it matters." },
  "Lord Ashford": { house: "ashford", born: "Ashford",
    blurb: "Lord of Ashford on the Cockleswhent, who calls the great tourney of 209 in his thirteen-year-old daughter's honor — and finds his field of games turned into the stage for a royal tragedy." },
  "Ser Humfrey Hardyng": { house: null, born: "The Vale",
    blurb: "A knight of skill and iron nerve, one of the five champions of Ashford Meadow — a man who answers treachery by demanding the right to face it in the lists.",
    death: { s: 1, e: 6, how: "Died of wounds from the trial of seven" },
    bookDeath: { b: 1, ch: 10, how: "Died of wounds from the trial of seven" } },
  "Ser Humfrey Beesbury": { house: null, born: "Honeyholt",
    blurb: "A bold young knight of Honeyholt, three-and-twenty, with the black-and-yellow stripes of his house on his shield and no patience for injustice.",
    death: { s: 1, e: 5, how: "Slain in the trial of seven" },
    bookDeath: { b: 1, ch: 9, how: "Slain in the trial of seven" } },
  "Ser Lyonel Baratheon": { house: "baratheon", born: "Storm's End",
    blurb: "The Laughing Storm: heir to Storm's End and one of the great fighters of the age, who bellows with mirth as he unhorses men. Fury and laughter, in House Baratheon, turn out to be the same thing." },
  "Ser Tybolt Lannister": { house: "lannister", born: "Casterly Rock",
    blurb: "A lion of Casterly Rock and a champion at Ashford Meadow — proof the West still sends its best to the lists even while krakens burn its coast." },
  "Raymun Fossoway": { house: "fossoway", born: "Cider Hall",
    blurb: "A squire of Cider Hall with a better heart than his knighted cousin — the sort of man who is embarrassed by other men's dishonor. The green-apple Fossoways begin with him." },
  "Ser Steffon Fossoway": { house: "fossoway", born: "Cider Hall",
    blurb: "A knight of Cider Hall, ambitious as a weed: quick to promise his sword, quicker to sell it where advancement grows. The red apple, and the reason the tree splits." },
  "Ser Robyn Rhysling": { house: null, born: "The Reach",
    blurb: "A grizzled one-eyed knight who lost the eye to a splintered lance and never missed it — one of the six who stand with a hedge knight when it counts." },
  "Ser Manfred Dondarrion": { house: null, born: "Blackhaven",
    blurb: "A marcher knight of the purple lightning, proud as his mountains — he takes the field at Ashford, and looks straight through a hedge knight who begs him to vouch for his name." },
  "Ser Roland Crakehall": { house: null, born: "Crakehall",
    blurb: "A knight of the Kingsguard, sworn white cloak to King Daeron — big, blunt, and bound by oath to stand wherever the blood royal points him, even in a trial of seven." },
  "Ser Donnel of Duskendale": { house: null, born: "Duskendale",
    blurb: "A knight of the Kingsguard under King Daeron the Good — his white cloak claimed for Aerion's seven, whatever his own heart thought of it." },
  "Ser Willem Wylde": { house: null, born: "The stormlands",
    blurb: "A knight of the Kingsguard under King Daeron the Good, sworn to shield the royal blood — and so to fight for it, even against six men in the right." },

  // ================= the Sworn Sword =================
  "Ser Eustace Osgrey": { only: "book", house: "osgrey", born: "Standfast",
    blurb: "The chequy lion of Standfast: an old knight rich in pride, poor in everything else, who can recite a thousand years of Osgrey glories and cannot stop living in one particular battle. His sons are graves; his lands are three fields and a dry wood." },
  "Lady Rohanne Webber": { only: "book", house: "webber", born: "Coldmoat",
    blurb: "The Red Widow of Coldmoat: small, freckled, red-braided, and sharper than half the swords in the Reach. Four husbands buried — the whispers say she helped — a castle held in her own right, and a father's will with a deadline in it." },
  "Ser Lucas Inchfield": { only: "book", house: null, born: "The Reach",
    blurb: "The Longinch: castellan of Coldmoat, tall, humorless, and hungry for the hand of the lady he serves — certain a hedge knight ranks somewhere below his boot.",
    bookDeath: { b: 2, ch: 9, how: "Drowned in the Chequy Water in trial by combat" } },
  "Septon Sefton": { only: "book", house: null, born: "The Reach",
    blurb: "Coldmoat's fat septon: shrewd, kindly, and generous with wine and news alike. Half the tale's history of the age arrives with his dinner conversation." },
  "Ser Bennis of the Brown Shield": { only: "book", house: null, born: "Nowhere in particular",
    blurb: "A sour, snaggle-toothed hedge knight in Ser Eustace's service, brown of shield, cloak, and disposition. Free with other men's blood and careful with his own skin." },

  // ================= the Mystery Knight =================
  "Ser Glendon Ball": { only: "book", house: null, born: "The riverlands",
    blurb: "The Knight of the Pussywillows: son of Quentyn Ball, the Fireball who shattered armies at Redgrass Field. Poor, furious, and magnificently proud of his blood — with a lance that backs every word of it." },
  "Ser Maynard Plumm": { only: "book", house: null, born: "Who can say",
    blurb: "A lean, mocking knight of the Fiddler's wedding party who sees through hoods, walls, and plots, and always happens to be standing exactly where he is needed. Almost as if somebody were watching through him." },
  "Ser Uthor Underleaf": { only: "book", house: null, born: "The Reach",
    blurb: "The Snail: a plain, balding knight who jousts for a living, not for glory — takes his falls where they pay and his victories where they're bought cheap. Business, he'd tell you, is good." },
  "Ser Kyle the Cat": { only: "book", house: null, born: "Misty Moor",
    blurb: "Ser Kyle the Cat of Misty Moor: a good-natured, threadbare hedge knight of Dunk and Egg's road, hoping a gift of a cat to Lord Butterwell will land him a place. Hedge knights hope; it is most of what they own." },
};
