/* A KNIGHT OF THE SEVEN KINGDOMS — world data, keyed to the ASOIAF map image (5652 × 3682 px).
   The tale of Dunk & Egg, ninety years before A Game of Thrones: the reigns of
   Daeron II the Good and Aerys I, when the wounds of the first Blackfyre
   Rebellion are still raw and a hedge knight's honor is worth more than gold.
   Every location below is a labeled dot on the map; x/y are image pixels.
   Story scope: Season One of the show (The Hedge Knight) and the three novellas.

   Row format: [name, x, y, type, region, rank, subtitle, description]
     type:  castle | city | town | ruin | landmark
     rank:  1 = always labeled · 2 = labeled when zoomed in · 3 = close zoom only */

const LOCATION_ROWS = [
  // ---------------- The Reach: the heart of the tale ----------------
  ["Ashford", 1147, 2421, "castle", "the-reach", 1, "Seat of House Ashford",
    "A castle and market town on the Cockleswhent, where Lord Ashford calls a great tourney in honor of his daughter — the field where a hedge knight's whole life turns."],
  ["Ashford Meadow", 1120, 2400, "landmark", "the-reach", 2, "The tourney grounds",
    "The broad meadow across the river from Ashford castle, white with pavilions for the great tourney of 209 — silk tents, painted shields, and the viewing stand where princes sit."],
  ["Standfast", 995, 2268, "castle", "the-reach", 2, "Towerhouse of House Osgrey",
    "A crumbling towerhouse on a hill, all that remains to the chequy lions who were once Marshals of the Northmarch and lords of all the land between Highgarden and the sea."],
  ["Coldmoat", 936, 2232, "castle", "the-reach", 2, "Seat of House Webber",
    "A fine moated castle an easy ride from Standfast, held by the Red Widow — Lady Rohanne Webber, four times wed and four times widowed, if the tales are to be believed."],
  ["Wat's Wood", 966, 2250, "landmark", "the-reach", 3, "The Osgreys' wood",
    "A parched old wood between Standfast and Coldmoat, tinder-dry in the great drought — Ser Eustace's pride, and the first thing the summer takes from him."],
  ["Cider Hall", 1035, 2387, "castle", "the-reach", 2, "Seat of House Fossoway",
    "The apple-sigiled Fossoways' seat at the meeting of the Mander and the Cockleswhent — soon to be two houses, red apples and green, over a quarrel born at Ashford Meadow."],
  ["Starpike", 1058, 2492, "castle", "the-reach", 3, "Seat of House Peake",
    "Chief seat of proud House Peake of the three castles, who once held three and now hold one — a grievance Lord Gormon nurses like a fire."],
  ["Highgarden", 912, 2457, "castle", "the-reach", 1, "Seat of House Tyrell",
    "A castle of white towers and climbing roses above the Mander, seat of Lord Leo Tyrell, called Longthorn — Warden of the South and liege lord of half the tale's small houses."],
  ["Goldengrove", 914, 2297, "castle", "the-reach", 3, "Seat of House Rowan",
    "The Rowans' golden-treed seat in the northern Reach, liege lords over Standfast and Coldmoat both — the court of last resort for their quarrels."],
  ["Old Oak", 705, 2307, "castle", "the-reach", 3, "Seat of House Oakheart",
    "An ancient seat by the sea road north of Highgarden."],
  ["Bitterbridge", 1142, 2278, "castle", "the-reach", 3, "Seat of House Caswell",
    "Where the roseroad crosses the Mander over an ancient stone bridge."],
  ["Tumbleton", 1305, 2176, "town", "the-reach", 3, "Town on the Mander",
    "A market town on the upper Mander, remembered for an old dance of dragons."],
  ["Honeyholt", 749, 2598, "castle", "the-reach", 3, "Seat of House Beesbury",
    "The Beesburys' seat amid orchards and hives on the Honeywine — home of young Ser Humfrey, who stands with Dunk at Ashford."],
  ["Horn Hill", 957, 2546, "castle", "the-reach", 3, "Seat of House Tarly",
    "The Tarlys' seat beneath the foothills of the Red Mountains."],
  ["Brightwater Keep", 740, 2548, "castle", "the-reach", 3, "Seat of House Florent",
    "Seat of the fox-eared Florents, forever insisting Highgarden should be theirs."],
  ["Oldtown", 720, 2668, "city", "the-reach", 1, "City of the Citadel",
    "The oldest city in Westeros, where the maesters forge their chains beneath the Hightower's beacon — where Egg's brother Aemon studies for his own chain."],

  // ---------------- The Stormlands ----------------
  ["Storm's End", 1654, 2358, "castle", "the-stormlands", 1, "Seat of House Baratheon",
    "A drum-towered castle whose walls have never fallen to storm or siege — seat of Ser Lyonel Baratheon, the Laughing Storm, who fights with a roar of mirth."],
  ["Summerhall", 1440, 2383, "castle", "the-stormlands", 1, "Summer palace of House Targaryen",
    "The dragons' pleasure palace in the Dornish Marches, lightly walled and full of music — Prince Maekar's seat, and the home Egg slipped away from. Its sad fire is still fifty years away."],
  ["Blackhaven", 1300, 2508, "castle", "the-stormlands", 3, "Seat of House Dondarrion",
    "The Dondarrions' marcher seat of black basalt, its banner a purple lightning bolt. Ser Manfred Dondarrion takes Dunk's service at Ashford — but will not vouch for him."],
  ["Nightsong", 1115, 2582, "castle", "the-stormlands", 3, "Seat of House Caron",
    "The marcher seat of the Carons, lords of the nightingales, where the Boneway climbs into the mountains."],
  ["Evenfall Hall", 1811, 2323, "castle", "the-stormlands", 3, "Seat of House Tarth",
    "Seat of the Tarths on the Sapphire Isle, said to be the loveliest island in the narrow sea."],

  // ---------------- The Crownlands ----------------
  ["King's Landing", 1535, 2057, "city", "the-crownlands", 1, "Capital of the Seven Kingdoms",
    "Aegon's city on Blackwater Bay, where good King Daeron keeps a court of maesters and septons — and where Bloodraven's thousand eyes see everything, and one."],
  ["Dragonstone", 1758, 1932, "castle", "the-crownlands", 1, "Seat of the Prince of Dragonstone",
    "The old island fortress of the Targaryens, seat of the heir to the Iron Throne — Prince Baelor Breakspear's own, and after him the sickly Valarr's."],
  ["Duskendale", 1585, 1955, "town", "the-crownlands", 3, "Port town of House Darklyn",
    "An old port town north of the capital, once seat of kings — Ser Donnel of Duskendale wears Kingsguard white at Ashford."],
  ["Rosby", 1513, 1967, "castle", "the-crownlands", 3, "Seat of House Rosby",
    "A small castle astride the road from Duskendale to the capital."],
  ["Antlers", 1482, 1913, "castle", "the-crownlands", 3, "Seat of House Buckwell",
    "A modest seat in the hills north of King's Landing."],

  // ---------------- The Riverlands ----------------
  ["Whitewalls", 1352, 1818, "castle", "the-riverlands", 1, "Seat of House Butterwell",
    "A palace-castle of milk-white marble hard by the Gods Eye, new-built with the gold of the dairy lords — called the Milkhouse, and soon to host a wedding, a tourney, and a treason."],
  ["Harrenhal", 1295, 1807, "castle", "the-riverlands", 2, "Seat of House Lothston",
    "The greatest castle ever raised and a ruin since Aegon's dragons melted its towers — held in this age by the ill-rumored Lothstons, mad Danelle of the black bat last of all."],
  ["Pennytree", 1120, 1728, "town", "the-riverlands", 2, "Village of the penny tree",
    "A small village on the Red Fork, its great oak nailed with pennies for luck — the place old Ser Arlan named himself for, and all the home Dunk's master ever had."],
  ["Riverrun", 1088, 1765, "castle", "the-riverlands", 1, "Seat of House Tully",
    "A three-sided castle at the meeting of the Tumblestone and the Red Fork, ancestral seat of House Tully, Lords Paramount of the Trident."],
  ["Raventree Hall", 1089, 1708, "castle", "the-riverlands", 3, "Seat of House Blackwood",
    "Seat of the old-gods-keeping Blackwoods — kin to Bloodraven, whose mother was a Blackwood, and forever feuding with the Brackens across the river."],
  ["Stone Hedge", 1178, 1753, "castle", "the-riverlands", 3, "Seat of House Bracken",
    "The Brackens' seat on the Red Fork — kin to Bittersteel, whose mother was a Bracken, and forever feuding with the Blackwoods across the river."],
  ["Stoney Sept", 1142, 1945, "town", "the-riverlands", 2, "Town of the bells",
    "A market town of the southern riverlands, where Dunk and Egg watch the hanging of the Wyl brigands before the road takes them north toward Whitewalls."],
  ["Acorn Hall", 1154, 1829, "castle", "the-riverlands", 3, "Seat of House Smallwood",
    "A snug forest keep in the foothills south of the Trident."],
  ["Maidenpool", 1533, 1860, "town", "the-riverlands", 3, "Town of House Mooton",
    "A port town on the Bay of Crabs where Florian first saw Jonquil bathing, if the songs are true."],
  ["The Twins", 1143, 1452, "castle", "the-riverlands", 2, "Seat of House Frey",
    "Two matched castles bridging the Green Fork. Lord Frey of the Crossing brings his daughter to Whitewalls to wed Lord Butterwell — and his sharp-tongued little heir along with her."],
  ["Seagard", 1105, 1529, "castle", "the-riverlands", 3, "Seat of House Mallister",
    "A fortified port raised to guard the coast against ironborn raiders — busier than ever, with Dagon Greyjoy reaving the western seas."],
  ["High Heart", 1170, 1809, "landmark", "the-riverlands", 3, "Sacred hill of the First Men",
    "A high bald hill ringed by weirwood stumps, holy to the children of the forest — and said to be haunted still."],

  // ---------------- The Vale ----------------
  ["The Eyrie", 1587, 1593, "castle", "the-vale", 1, "Seat of House Arryn",
    "A castle of white stone atop the Giant's Lance, reached by a goat path and defended by the sky itself."],
  ["Gulltown", 1800, 1642, "city", "the-vale", 2, "Port city of the Vale",
    "The Vale's harbor city, held by House Grafton for the Arryns."],
  ["Runestone", 1836, 1608, "castle", "the-vale", 3, "Seat of House Royce",
    "Ancient seat of the Royces, whose bronze armor is graven with runes older than the Andals."],

  // ---------------- The Westerlands ----------------
  ["Casterly Rock", 740, 1956, "castle", "the-westerlands", 1, "Seat of House Lannister",
    "A fortress carved into a golden rock above the Sunset Sea, seat of the wealthiest house in the Seven Kingdoms. Ser Tybolt Lannister rides as a champion at Ashford."],
  ["Lannisport", 732, 1973, "city", "the-westerlands", 2, "City of the Lannisters",
    "A walled port city in the shadow of the Rock — sacked in living memory by Dagon Greyjoy's longships, to the west's lasting shame."],
  ["Golden Tooth", 948, 1858, "castle", "the-westerlands", 3, "Gate of the Westerlands",
    "The small strong castle that locks the hill road between the Riverlands and the West."],
  ["Crakehall", 660, 2186, "castle", "the-westerlands", 3, "Seat of House Crakehall",
    "Seat of the boar-sigiled Crakehalls — Ser Roland Crakehall wears the white cloak of the Kingsguard at Ashford."],

  // ---------------- The North ----------------
  ["Winterfell", 1207, 745, "castle", "the-north", 1, "Seat of House Stark",
    "The ancient stronghold of the Kings of Winter, held in this age by Lord Beron Stark — far from the tale's tourneys, busy driving Dagon Greyjoy's reavers from his shores."],
  ["White Harbor", 1361, 1059, "city", "the-north", 2, "City of House Manderly",
    "The North's only true city, a clean white port at the mouth of the White Knife."],
  ["Moat Cailin", 1228, 1120, "ruin", "the-north", 3, "Ruined guard of the Neck",
    "Three crumbling towers commanding the causeway through the swamps of the Neck — the ancient lock on the door to the North."],
  ["Castle Black", 1424, 258, "castle", "the-north", 2, "Stronghold of the Night's Watch",
    "The chief fortress of the Night's Watch at the foot of the Wall — where, in the end, both a hedge knight's squire's brother and stranger things will one day serve."],

  // ---------------- The Iron Islands ----------------
  ["Pyke", 743, 1630, "castle", "iron-islands", 1, "Seat of House Greyjoy",
    "A castle of black stone strung across sea-stacks and rope bridges — seat of Dagon Greyjoy, whose longships reave the sunset sea while the dragons' peace holds everywhere else."],

  // ---------------- Dorne ----------------
  ["Sunspear", 1798, 2863, "castle", "dorne", 1, "Seat of House Martell",
    "The winding-walled seat of House Martell, joined to the realm at last by marriage — Daeron's queen is a Martell, and his sister wed the Prince of Dorne."],
  ["Yronwood", 1328, 2719, "castle", "dorne", 2, "Seat of House Yronwood",
    "Seat of the proudest house in Dorne after the Martells — 'The Bloodroyal', wardens of the Boneway."],
  ["Starfall", 964, 2757, "castle", "dorne", 2, "Seat of House Dayne",
    "The Daynes' seat on the Torentine, home of the sword Dawn and its long line of Swords of the Morning."],
  ["Vaith", 1422, 2869, "castle", "dorne", 3, "Seat of House Vaith",
    "A river seat amid the red sands, on the road Dunk and Egg mean to travel."],
  ["Wyl", 1361, 2586, "castle", "dorne", 3, "Seat of House Wyl",
    "A marcher seat in the Boneway, old in border blood — home country of the brigands hanged at Stoney Sept."],

  // ---------------- Across the narrow sea ----------------
  ["Tyrosh", 2059, 2531, "city", "free-cities", 1, "City of dyes — and exiles",
    "An island Free City of bright-dyed beards and hired swords, where Bittersteel and the sons of Daemon Blackfyre wait across the water, and the black dragon's cause never quite dies."],
  ["Lys", 2221, 2898, "city", "free-cities", 2, "City of pleasure",
    "An island Free City of perfumed gardens — where Prince Aerion Brightflame is sent in gilded exile after Ashford, to Lys's misfortune."],
  ["Pentos", 2215, 2070, "city", "free-cities", 3, "Free City of merchant princes",
    "A wealthy Free City of canals and colored domes, where magisters grow rich and keep their daggers hidden."],
  ["Braavos", 2201, 1413, "city", "free-cities", 3, "The Secret City",
    "Greatest of the Free Cities, hidden in a fog-bound lagoon behind its Titan."],
];

/* Minor Westerosi houses: canonical field colors for the small map banners.
   colors: [field, second tincture] · div: how the shield is divided
   Where a matching drawn shield exists (Wikimedia Commons), img overrides. */
const MINOR_ARMS = {
  "goldengrove":     { house: "House Rowan", colors: ["#c9c9c9", "#c9a15a"], div: "plain", img: "minor/goldengrove.png" },
  "old-oak":         { house: "House Oakheart", colors: ["#e0c060", "#3f6b3a"], div: "fess" },
  "bitterbridge":    { house: "House Caswell", colors: ["#e8e8e8", "#c9a15a"], div: "fess" },
  "honeyholt":       { house: "House Beesbury", colors: ["#1b1b1b", "#e0c060"], div: "fess" },
  "horn-hill":       { house: "House Tarly", colors: ["#4a6741", "#c93a2e"], div: "plain", img: "tarly.svg" },
  "brightwater-keep":{ house: "House Florent", colors: ["#e8e8e8", "#c9702e"], div: "plain" },
  "oldtown":         { house: "House Hightower", colors: ["#e8e8e8", "#c93a2e"], div: "plain", img: "hightower.png" },
  "blackhaven":      { house: "House Dondarrion", colors: ["#1b1b24", "#7a5cc9"], div: "plain" },
  "nightsong":       { house: "House Caron", colors: ["#e0c060", "#1b1b1b"], div: "fess", img: "minor/nightsong.png" },
  "evenfall-hall":   { house: "House Tarth", colors: ["#7fa8c9", "#d8a0b0"], div: "quarter" },
  "duskendale":      { house: "House Darklyn", colors: ["#1b1b1b", "#e0c060"], div: "quarter" },
  "rosby":           { house: "House Rosby", colors: ["#e8e8e8", "#8f1d2c"], div: "pale", img: "minor/rosby.png" },
  "antlers":         { house: "House Buckwell", colors: ["#4a6741", "#c9a15a"], div: "plain" },
  "harrenhal":       { house: "House Lothston", colors: ["#c9c9c9", "#1b1b1b"], div: "plain" },
  "raventree-hall":  { house: "House Blackwood", colors: ["#1b1b1b", "#e8e8e8"], div: "plain", img: "minor/raventree-hall.png" },
  "stone-hedge":     { house: "House Bracken", colors: ["#c9a15a", "#8f1d2c"], div: "plain", img: "minor/stone-hedge.png" },
  "acorn-hall":      { house: "House Smallwood", colors: ["#e0c060", "#5a3a1a"], div: "fess" },
  "maidenpool":      { house: "House Mooton", colors: ["#e8e8e8", "#c93a2e"], div: "fess", img: "minor/maidenpool.png" },
  "the-twins":       { house: "House Frey", colors: ["#7a8699", "#2d3a6b"], div: "plain" },
  "seagard":         { house: "House Mallister", colors: ["#2d3a6b", "#d8d8d8"], div: "plain" },
  "gulltown":        { house: "House Grafton", colors: ["#7a7a7a", "#c93a2e"], div: "fess" },
  "runestone":       { house: "House Royce", colors: ["#8a6d3b", "#2b2015"], div: "plain" },
  "golden-tooth":    { house: "House Lefford", colors: ["#e0c060", "#3a5f8a"], div: "fess" },
  "crakehall":       { house: "House Crakehall", colors: ["#7a5c3a", "#e8e8e8"], div: "fess", img: "minor/crakehall.png" },
  "white-harbor":    { house: "House Manderly", colors: ["#3d6b6b", "#e8e8e8"], div: "fess" },
  "yronwood":        { house: "House Yronwood", colors: ["#d8c9a0", "#1b1f24"], div: "plain" },
  "starfall":        { house: "House Dayne", colors: ["#4a3a7a", "#e8e8e8"], div: "plain" },
  "vaith":           { house: "House Vaith", colors: ["#d8a0b0", "#1b1f24"], div: "fess" },
  "wyl":             { house: "House Wyl", colors: ["#e0c060", "#1b1f24"], div: "plain" },
};

/* Seats whose canon fan-heraldry shield was sourced from Wikimedia Commons
   (assets/sigils/minor/<location-id>.png). All others use the drawn arms. */
const CANON_MINOR_SHIELDS = new Set([
  "white-harbor", "seagard", "runestone", "gulltown", "golden-tooth",
  "old-oak", "bitterbridge", "brightwater-keep", "honeyholt", "blackhaven",
  "wyl", "yronwood", "starfall",
]);

/* which locations are the seats shown when House Banners are toggled on */
const HOUSE_SEATS = {
  "kings-landing": "targaryen",
  "dragonstone": "targaryen",
  "summerhall": "targaryen",
  "storms-end": "baratheon",
  "highgarden": "tyrell",
  "casterly-rock": "lannister",
  "winterfell": "stark",
  "the-eyrie": "arryn",
  "riverrun": "tully",
  "pyke": "greyjoy",
  "sunspear": "martell",
  "ashford": "ashford",
  "standfast": "osgrey",
  "coldmoat": "webber",
  "whitewalls": "butterwell",
  "cider-hall": "fossoway",
  "starpike": "peake",
};

/* Season 1 chronicle entries for major places (shown under "This season" in the info panel) */
const SEASON_LORE = {
  "ashford": "Lord Ashford calls a tourney in his daughter's honor, and half the chivalry of the Reach answers — along with three princes, a puppet show, and a hedge knight seven feet tall.",
  "ashford-meadow": "The heart of the season: the pavilions rise, the champions hold the field, a prince breaks a puppet — and thirteen men fight a trial of seven to decide a hedge knight's hand.",
  "kings-landing": "Good King Daeron keeps his peace from here — a peace bought at Redgrass Field twelve years past, and dearer to him than any son.",
  "summerhall": "Prince Maekar's seat in the marches, where a bald little princeling decided he would rather squire in secret than be one of the Drunken's whipping boys.",
  "dragonstone": "The seat of Baelor Breakspear, Prince of Dragonstone, Hand of the King, and heir to the Iron Throne — the finest knight and best man in the realm, men say.",
  "pennytree": "Ser Arlan took his name from this village and its coin-nailed oak. He served half a lifetime for hearth and bread — and Dunk carries his shield, his horse, and his lessons.",
  "stoney-sept": "The old man and the boy passed this way many a season. Every inn between here and Ashford knows the tall lad who was Ser Arlan's squire.",
  "blackhaven": "Ser Manfred Dondarrion takes the tourney field at Ashford — and when a hedge knight begs him to vouch for his knighthood, looks straight through him.",
  "honeyholt": "Young Ser Humfrey Beesbury rides from here to Ashford Meadow — and stands with a hedge knight in the trial of seven, to his house's everlasting honor.",
  "cider-hall": "Ser Steffon Fossoway rides to Ashford to make his name; his cousin Raymun rides with him to carry his shield. Only one of them comes home fit to be called a knight.",
  "highgarden": "Lord Leo Longthorn does not trouble himself with Lord Ashford's tourney — but every knight on the meadow knows the rose of Highgarden outranks the field.",
  "storms-end": "Ser Lyonel Baratheon, the Laughing Storm, brings his roar to Ashford Meadow — and answers a hedge knight's plea when it matters most.",
  "casterly-rock": "Ser Tybolt Lannister rides from the Rock to Ashford and holds the field as a champion — the lion's gold in a season that belongs to the dragons.",
  "oldtown": "Egg's eldest brother Aemon is here, forging a maester's chain of his own free will — the rarest thing a prince ever did, until his little brother took up squiring.",
  "sunspear": "Where the season ends pointing: Dunk takes service with no lord at all and turns Thunder's head toward Dorne, with a prince polishing his kettle helm behind him.",
  "lys": "Prince Aerion Brightflame's punishment for Ashford is exile here in silk — the realm's relief, and Lys's problem, for a few years at least.",
  "tyrosh": "Across the narrow sea, Bittersteel and the sons of Daemon Blackfyre keep the black dragon's cause warm — the shadow behind every uneasy peace of the age.",
  "whitewalls": "The tale has not come to the Milkhouse yet — but a wedding, a tourney, and a dragon's egg are waiting there, a few years down the road.",
  "standfast": "The tale has not come here yet — but a dry summer, a dammed stream, and a chequy lion's last war are waiting for Dunk beyond the season's end.",
  "coldmoat": "The tale has not come here yet — but the Red Widow's moat, her spotted spider banners, and a certain trial by combat wait beyond the season's end.",
  "winterfell": "Far from the season's tourneys, Lord Beron Stark gathers swords to drive Dagon Greyjoy's longships from his shores.",
  "pyke": "Dagon Greyjoy rules here in this age, and his longships trouble every western shore — the one war the king's peace cannot quite put down.",
};

const WORLD = {
  regions: [
    { id: "the-reach", name: "The Reach",
      description: "The garden of Westeros — the most fertile and populous of the kingdoms, ruled by House Tyrell from Highgarden. Its chivalry is the finest in the realm, its tourneys the grandest, and its small houses the proudest and quarrelsomest.",
      season: "The season lives here: Lord Ashford's tourney draws the princes of the realm to a meadow on the Cockleswhent, and a hedge knight's fate turns on it." },
    { id: "the-stormlands", name: "The Stormlands",
      description: "Rain-lashed coasts and oak forests between King's Landing and Dorne, the lands of House Baratheon of Storm's End — and of Summerhall, the dragons' summer palace in the marches.",
      season: "Summerhall sends the season its truest gift: a bald little runaway prince with a stubborn streak and his grandfather's name." },
    { id: "the-crownlands", name: "The Crownlands",
      description: "The king's own lands around Blackwater Bay, ruled directly from the Iron Throne. King Daeron II keeps his court at King's Landing; his heir Baelor keeps Dragonstone.",
      season: "The court rides out this season — Baelor Breakspear and Maekar both come to Ashford, and the realm's future is decided on a tourney field." },
    { id: "the-riverlands", name: "The Riverlands",
      description: "Fertile country threaded by the forks of the Trident, seat of House Tully at Riverrun — dotted with the seats of Blackwood and Bracken, whose feud gave the realm both Bloodraven and Bittersteel.",
      season: "Quiet this season, but the roads Dunk and Egg will ride run through it — past Pennytree, Stoney Sept, and a milk-white castle by the Gods Eye." },
    { id: "dorne", name: "Dorne",
      description: "The sun-scorched south beyond the Red Mountains, ruled by House Martell from Sunspear — joined to the realm at last by King Daeron's marriages, not his armies.",
      season: "Where the season ends pointing: Dunk turns his horse south for the Prince's Pass with a new squire at his heel." },
    { id: "the-westerlands", name: "The Westerlands",
      description: "Gold-veined hills ruled by House Lannister from Casterly Rock — the richest house in the Seven Kingdoms, licking the wound of Dagon Greyjoy's sack of Lannisport.",
      season: "Ser Tybolt Lannister holds the field at Ashford Meadow as a champion of the tourney." },
    { id: "the-vale", name: "The Vale",
      description: "A green land walled in by the Mountains of the Moon, ruled by House Arryn from the Eyrie. Its knights are famed, and its passes are held by hill tribes who bow to no lord.",
      season: "The Vale keeps to itself this season — its knights have tourneys of their own." },
    { id: "the-north", name: "The North",
      description: "The largest of the Seven Kingdoms and the coldest, ruled from Winterfell by House Stark. In this age Lord Beron Stark holds it — with Dagon Greyjoy's reavers gnawing his western shore.",
      season: "Far from the tale — but Lord Beron gathers swords against the krakens, the one war the king's peace cannot end." },
    { id: "iron-islands", name: "The Iron Islands",
      description: "Bleak isles in the Sunset Sea whose people reave and pay the iron price, ruled in this age by Dagon Greyjoy from Pyke — the Old Way come again, while the greenlands look east.",
      season: "Dagon Greyjoy reaves from Fair Isle to the Stony Shore this age, and no king's peace reaches him." },
    { id: "free-cities", name: "The Free Cities",
      description: "Nine merchant cities across the Narrow Sea, daughters of old Valyria — and in this age, the refuge of the black dragon: Bittersteel and the exiled sons of Daemon Blackfyre.",
      season: "Aerion Brightflame ends the season exiled to Lys — and in Tyrosh, the Blackfyre cause waits for its moment." },
  ],

  houses: [
    { id: "targaryen", name: "House Targaryen", seat: "kings-landing", region: "the-crownlands",
      words: "Fire and Blood", sigil: "Three-Headed Dragon", colors: ["#e05c5c", "#1a1a1a"],
      description: "The dragonlords of old Valyria, kings of Westeros for near two hundred years — though the last dragon died a generation ago. Good King Daeron II rules a realm at peace; his brood of sons and grandsons — Baelor, Aerys, Rhaegel, Maekar, and theirs — crowd the succession, and the realm counts on the best of them." },
    { id: "blackfyre", name: "House Blackfyre", seat: "tyrosh", region: "free-cities",
      words: "Fire and Blood", sigil: "The Black Dragon", colors: ["#1a1a1a", "#8f1d2c"],
      description: "The dragon reversed: the line of Daemon Blackfyre, King Aegon the Unworthy's legitimized bastard, who took the conqueror's sword for his name and half the realm to war for his claim. Daemon died at Redgrass Field twelve years past — but his sons live on in Tyrosh under Bittersteel's hard eye, and half the disappointed men of Westeros still drink to the black dragon." },
    { id: "baratheon", name: "House Baratheon", seat: "storms-end", region: "the-stormlands",
      words: "Ours Is the Fury", sigil: "Crowned Stag", colors: ["#caa23a", "#1b1b1b"],
      description: "Lords of Storm's End since Orys Baratheon took the castle, the girl, and the words. The house's great man of the age is Ser Lyonel, the Laughing Storm, who bellows with mirth as he fights — and fights better than nearly anyone alive." },
    { id: "tyrell", name: "House Tyrell", seat: "highgarden", region: "the-reach",
      words: "Growing Strong", sigil: "Golden Rose", colors: ["#e8c368", "#3f6b3a"],
      description: "Wardens of the South and Lords of Highgarden, stewards risen to rule the vast, fertile Reach. Lord Leo Tyrell, called Longthorn, is reckoned one of the finest lances of the age when he deigns to ride — and liege lord over most of the tale's quarreling small houses." },
    { id: "lannister", name: "House Lannister", seat: "casterly-rock", region: "the-westerlands",
      words: "Hear Me Roar", sigil: "Lion", colors: ["#e8c368", "#8f1d2c"],
      description: "The richest house in the Seven Kingdoms, lords of Casterly Rock and the gold beneath it — stung in this age by Dagon Greyjoy's sack of Lannisport, which no amount of gold has yet avenged. Ser Tybolt Lannister rides as a champion at Ashford." },
    { id: "stark", name: "House Stark", seat: "winterfell", region: "the-north",
      words: "Winter Is Coming", sigil: "Direwolf", colors: ["#c9c9c9", "#20242b"],
      description: "Wardens of the North for eight thousand years. Lord Beron Stark rules from Winterfell in this age, gathering swords to drive Dagon Greyjoy's reavers from the Stony Shore — a war the tourney-goers of the south barely hear of." },
    { id: "arryn", name: "House Arryn", seat: "the-eyrie", region: "the-vale",
      words: "As High as Honor", sigil: "Moon-and-Falcon", colors: ["#dfe8f0", "#5a7a9c"],
      description: "The purest blood of Andal kings, Wardens of the East, enthroned in the Eyrie above the Vale. They keep their own counsel in this age, as in most." },
    { id: "tully", name: "House Tully", seat: "riverrun", region: "the-riverlands",
      words: "Family, Duty, Honor", sigil: "Leaping Trout", colors: ["#c9d4e0", "#3a5f8a"],
      description: "Lords of Riverrun and Lords Paramount of the Trident, ruling the fertile, much-fought-over riverlands — including the feuding Blackwoods and Brackens, whom no Tully has ever fully reconciled." },
    { id: "greyjoy", name: "House Greyjoy", seat: "pyke", region: "iron-islands",
      words: "We Do Not Sow", sigil: "Golden Kraken", colors: ["#c9a15a", "#1b1f24"],
      description: "Ironborn lords of Pyke. In this age Dagon Greyjoy rules the isles and reaves the western seas in the Old Way — sacking Lannisport and raiding the Stony Shore while the Iron Throne's eyes are on the black dragon across the narrow sea." },
    { id: "martell", name: "House Martell", seat: "sunspear", region: "dorne",
      words: "Unbowed, Unbent, Unbroken", sigil: "Spear-Pierced Sun", colors: ["#e8c368", "#b0563a"],
      description: "Princes of Dorne, joined to the Iron Throne at last — not by conquest but by King Daeron's two marriages: his Myriah for the realm, his sister Daenerys for Prince Maron. Half the realm's grumblers call the king half-Dornish for it, and drank to Daemon Blackfyre once because of it." },
    { id: "ashford", name: "House Ashford", seat: "ashford", region: "the-reach",
      words: "Our Sun Shines Bright", sigil: "White Sun-and-Chevron", colors: ["#c9702e", "#f2ead8"],
      description: "Lords of the castle and market town on the Cockleswhent, bannermen to Highgarden. Lord Ashford's great tourney of 209, held in his fair daughter's honor, draws three princes and half the chivalry of the Reach — and becomes the most consequential tourney of the age for none of the reasons he planned." },
    { id: "osgrey", name: "House Osgrey", seat: "standfast", region: "the-reach",
      words: "The Lion Still Stands", sigil: "Chequy Lion", colors: ["#3f6b3a", "#e0c060"],
      description: "The chequy lions of Standfast, Marshals of the Northmarch a thousand years ago, lords of dozens of villages and keeps — and now masters of one old towerhouse, three fields, and a dry wood. Old Ser Eustace remembers every inch of what his house has lost, including what it lost at Redgrass Field." },
    { id: "webber", name: "House Webber", seat: "coldmoat", region: "the-reach",
      words: "In Our Web", sigil: "Spotted Spider", colors: ["#f2f2ee", "#8f1d2c"],
      description: "Lords of Coldmoat, whose banners bear a spotted spider on a silver web. Lady Rohanne — the Red Widow, four times wed and four times widowed — holds the castle in her own right, with a long red braid, a longer memory, and a deadline in her father's will." },
    { id: "butterwell", name: "House Butterwell", seat: "whitewalls", region: "the-riverlands",
      words: "In Cream and Amber", sigil: "Undy Green, White & Yellow", colors: ["#4a6741", "#e0c060"],
      description: "Dairy lords grown rich enough to raise Whitewalls, the milk-white marble palace by the Gods Eye that men call the Milkhouse. Lord Ambrose Butterwell was Hand of the King once, briefly and badly — and his second wedding gathers every disappointed lord in the riverlands under one gleaming roof." },
    { id: "fossoway", name: "House Fossoway", seat: "cider-hall", region: "the-reach",
      words: "A Taste of Glory", sigil: "The Red Apple", colors: ["#e0c060", "#c93a2e"],
      description: "The apple knights of Cider Hall. At Ashford Meadow the house splits at the stem: Ser Steffon sells his sword's honor for advantage, his cousin Raymun is knighted on the field to stand against him — and the green-apple Fossoways are born of the difference." },
    { id: "peake", name: "House Peake", seat: "starpike", region: "the-reach",
      words: "Three Castles, One Due", sigil: "Three Black Castles", colors: ["#c9702e", "#1b1b1b"],
      description: "Proud marcher lords who once held three castles — Starpike, Dunstonbury, and Whitegrove — and lost two for backing the black dragon at Redgrass Field. Lord Gormon Peake counts that debt daily, and means to collect it at Whitewalls with another man's crown." },
  ],

  journeys: [
    { id: "dunk", character: "Ser Duncan the Tall", initial: "D",
      color: "#5b7d9c", summary: "A roadside grave → Ashford Meadow → the road to Dorne · 4 stops",
      stops: [
        { at: [1190, 2330], name: "A grave by the roseroad", episode: 1, epTitle: "The Hedge Knight",
          note: "Dunk digs the old man's grave with the old man's sword-belt still too big for him. Ser Arlan of Pennytree gets a hillside; his squire gets a horse, a sword, and a shield that isn't his." },
        { at: [1172, 2394], name: "The inn by the Cockleswhent", episode: 1, epTitle: "The Hedge Knight",
          note: "An ale, a plan, and a bald-headed stableboy who washes up in a bucket and talks back like a lord. Dunk rides for Ashford with a squire he never asked for." },
        { location: "ashford-meadow", episode: 2, epTitle: "Ashford Meadow",
          note: "Pavilions white as milk, a puppet show with a wooden dragon, and Steely Pate's good armor bought with everything Dunk owns. The hedge knight takes the field — and everything after follows." },
        { at: [1235, 2492], name: "The road to Dorne", episode: 6, epTitle: "A Knight of the Seven Kingdoms",
          note: "No lord's service, no lord's leash. Dunk turns Thunder south for the Prince's Pass with Egg at his heel — a hedge knight and a prince, off to see what the realm is made of." },
      ] },
    { id: "egg", character: "Egg (Aegon Targaryen)", initial: "E",
      color: "#c25353", summary: "Summerhall → Ashford Meadow → the road to Dorne · 4 stops",
      stops: [
        { location: "summerhall", episode: 1, epTitle: "The Hedge Knight",
          note: "The fourth son of a fourth son shaves his silver-gold head and slips his father's palace, sooner than squire for his brother Daeron and be within reach of his brother Aerion." },
        { at: [1172, 2394], name: "The inn by the Cockleswhent", episode: 1, epTitle: "The Hedge Knight",
          note: "A stableboy with no hair, sharp manners, and a sharper tongue attaches himself to the largest knight he can find. The knight never stood a chance." },
        { location: "ashford-meadow", episode: 2, epTitle: "Ashford Meadow",
          note: "Egg holds Dunk's horse, shines Dunk's mail, and keeps his hood up — because half the men on this field would know that bald head, and both his brothers are in the lists." },
        { at: [1235, 2492], name: "The road to Dorne", episode: 6, epTitle: "A Knight of the Seven Kingdoms",
          note: "Prince Maekar lets his son go — to learn the realm the way no prince ever learns it, squiring for a hedge knight who thinks with his heart." },
      ] },
    { id: "baelor", character: "Baelor Breakspear", initial: "B",
      color: "#a08549", summary: "King's Landing → Ashford Meadow · 3 stops",
      stops: [
        { location: "kings-landing", episode: 1, epTitle: "The Hedge Knight",
          note: "The Hand of the King and heir to the Iron Throne — the man who broke Daemon Blackfyre's host at Redgrass Field — rides out for a country tourney on the Cockleswhent." },
        { location: "ashford-meadow", episode: 3, epTitle: "The Lists",
          note: "Baelor watches the lists his sons ride in — and remembers an old hedge knight named Arlan of Pennytree who once unhorsed him. He does not forget debts like that." },
        { location: "ashford-meadow", episode: 5, epTitle: "The Judgment of the Gods",
          note: "When no other man will make a hedge knight's seven, the Prince of Dragonstone takes up his shield: 'It seems my helm is dusty.' The realm turns on the blow that follows." },
      ] },
    { id: "aerion", character: "Aerion Brightflame", initial: "A",
      color: "#b0563a", summary: "Ashford Meadow → exile in Lys · 2 stops",
      stops: [
        { location: "ashford-meadow", episode: 2, epTitle: "Ashford Meadow",
          note: "Prince Aerion, who dreams he is a dragon in a man's skin, comes to Ashford to shine — and finds a puppet dragon, a Dornish puppeteer, and a hedge knight's fists instead." },
        { location: "lys", episode: 6, epTitle: "A Knight of the Seven Kingdoms",
          note: "His father's judgment: exile across the narrow sea, gilded and unmistakable. Lys is welcome to him." },
      ] },
  ],
};

/* ---------------- Season One, episode by episode ----------------
   The show's first season tells The Hedge Knight: the tourney at Ashford
   Meadow in 209 AC. (Episode titles here follow the novella's beats — rename
   them to the aired titles if they differ.)
   throne: who sits it, which house, who serves as Hand
   people: j = journey id (traceable on the map) · loc = where they are
   power:  house strength 1–10 as of this episode
   deaths: named characters who die IN this episode */

const EPISODES = [
  { n: 1, title: "The Hedge Knight",
    throne: { king: "Daeron II Targaryen, the Good", house: "targaryen", hand: "Prince Baelor Breakspear" },
    events: [
      "On a hillside by the roseroad, a squire buries the old hedge knight he served since boyhood — and decides the grave needn't take the knighthood too.",
      "Dunk takes Ser Arlan's arms, armor, and horses, and rides for Ashford Meadow, where Lord Ashford has called a great tourney.",
      "At an inn on the Cockleswhent he meets a bald, sharp-tongued stableboy who follows him out the door and will not be sent back.",
      "The boy calls himself Egg. He is a better squire than any stableboy has a right to be, and he keeps his hood up around highborn men.",
      "Ashford Meadow opens before them: a hundred pavilions, a painted viewing stand, and the fair maid of Ashford's five champions to come.",
    ],
    people: [
      { name: "Ser Duncan the Tall", j: "dunk", note: "Digs a grave, keeps a sword, and aims his whole life at one tourney." },
      { name: "Egg", j: "egg", note: "A stableboy with suspiciously fine manners and no hair at all." },
      { name: "Ser Arlan of Pennytree", loc: "roseroad-grave", note: "The old man of Pennytree, gone to whatever field the good knights go to." },
      { name: "Baelor Breakspear", j: "baelor", note: "The Hand rides out from King's Landing for a country tourney." },
      { name: "King Daeron II Targaryen", loc: "kings-landing", note: "The Good: bookish, peaceable, and better at ruling than any warrior king." },
    ],
    power: { targaryen: 10, blackfyre: 2, baratheon: 7, tyrell: 8, lannister: 7, stark: 6, martell: 6, ashford: 4, fossoway: 3, peake: 3 },
    deaths: [
      { name: "Ser Arlan of Pennytree", note: "A chill, a cough, and a quiet end by the road — after a lifetime of other men's battles." },
    ] },
  { n: 2, title: "Ashford Meadow",
    throne: { king: "Daeron II Targaryen, the Good", house: "targaryen", hand: "Prince Baelor Breakspear" },
    events: [
      "Dunk pitches his camp beneath an elm and walks the meadow: banners, merchants, puppeteers — and a Dornish girl named Tanselle painting a wooden dragon.",
      "Steely Pate the armorer takes Dunk's measure and most of his coin; the shield gets new paint from Tanselle's brush — a shooting star above an elm.",
      "The champions take the field: Lord Ashford's two sons, Ser Humfrey Hardyng, Ser Tybolt Lannister, and Prince Valarr Targaryen, the Young Prince.",
      "The princes of the realm arrive in force — Baelor, Maekar and his sons: Aerion the Bright Flame, Daeron the Drunken, and somewhere unseen, a missing fourth son.",
      "Dunk learns his new squire dodges every question about where he came from — and squires better than boys twice-trained.",
    ],
    people: [
      { name: "Ser Duncan the Tall", j: "dunk", note: "Sells everything he owns for armor that fits a man his size." },
      { name: "Egg", j: "egg", note: "Keeps his hood up. There are two very good reasons on this field." },
      { name: "Tanselle", loc: "ashford-meadow", note: "Tanselle Too-Tall, the Dornish puppeteer — not too tall by half, says Dunk." },
      { name: "Steely Pate", loc: "ashford-meadow", note: "The master armorer of the meadow: gruff, fair, and good at his work." },
      { name: "Baelor Breakspear", j: "baelor", note: "Remembers being unhorsed, once, by a hedge knight named Arlan." },
      { name: "Aerion Brightflame", j: "aerion", note: "Beautiful, cruel, and sure he is a dragon wearing a man." },
      { name: "Valarr Targaryen", loc: "ashford-meadow", note: "The Young Prince: Baelor's heir, a champion by birth more than by lance." },
      { name: "Prince Maekar Targaryen", loc: "ashford-meadow", note: "The king's fourth son, hard and proud, with a missing son of his own." },
      { name: "Daeron Targaryen", loc: "ashford-meadow", note: "The Drunken: Maekar's heir, who dreams true and drinks truer." },
    ],
    power: { targaryen: 10, blackfyre: 2, baratheon: 7, tyrell: 8, lannister: 7, stark: 6, martell: 6, ashford: 5, fossoway: 3, peake: 3 },
    deaths: [] },
  { n: 3, title: "The Lists",
    throne: { king: "Daeron II Targaryen, the Good", house: "targaryen", hand: "Prince Baelor Breakspear" },
    events: [
      "The tourney opens in splendor: the five champions hold the field against all comers, and the Laughing Storm's bellow rolls over the meadow.",
      "Ser Humfrey Hardyng unhorses Aerion Brightflame — and Aerion's answer is a lance through his horse's neck, leaving Hardyng broken-legged under a dying animal.",
      "That night Aerion finds the puppet show: the wooden dragon offends the Bright Flame, and he breaks Tanselle's fingers for it.",
      "Dunk hears her scream — and a hedge knight of no name knocks a prince of the blood into the dirt and kicks the pride out of him.",
      "Egg's hood falls back. The stableboy is Aegon Targaryen, Aerion's own brother — and Dunk is dragged to a cell to wait on the king's justice.",
    ],
    people: [
      { name: "Ser Duncan the Tall", j: "dunk", note: "A knight remembers the day he learned what his fists are for." },
      { name: "Egg", j: "egg", note: "\"He was hurting her!\" — the hood is off, and the prince is out." },
      { name: "Aerion Brightflame", j: "aerion", note: "Breaks a girl's fingers over a wooden dragon; meets a real one in a hedge knight." },
      { name: "Tanselle", loc: "ashford-meadow", note: "Her scream is the hinge the whole tale turns on." },
      { name: "Ser Humfrey Hardyng", loc: "ashford-meadow", note: "A champion unhorsed by treachery — his leg crushed under his dying horse." },
      { name: "Ser Lyonel Baratheon", loc: "ashford-meadow", note: "The Laughing Storm, unhorsing men with a roar of mirth." },
      { name: "Baelor Breakspear", j: "baelor", note: "Watches, weighs, and says little. The Hand misses nothing." },
      { name: "Prince Maekar Targaryen", loc: "ashford-meadow", note: "Finds his missing son at last — squiring for the man who beat his other one." },
    ],
    power: { targaryen: 10, blackfyre: 2, baratheon: 7, tyrell: 8, lannister: 7, stark: 6, martell: 6, ashford: 5, fossoway: 3, peake: 3 },
    deaths: [] },
  { n: 4, title: "A Trial of Seven",
    throne: { king: "Daeron II Targaryen, the Good", house: "targaryen", hand: "Prince Baelor Breakspear" },
    events: [
      "Aerion demands a trial by combat — and names it a trial of seven, the old Andal way: seven against seven, and Dunk must find six men to die for a hedge knight's honor.",
      "The price of losing is a hand and a foot, the parts that struck the prince. The price of asking men to stand: everything they have to lose.",
      "Raymun Fossoway shames his cousin Steffon into promising help; Steffon sells his promise to Aerion instead by morning — and Raymun is knighted on the spot to take his place.",
      "Ser Humfrey Hardyng, broken leg and all, demands a place against the prince who killed his horse. Ser Humfrey Beesbury and Ser Robyn Rhysling stand with him.",
      "One man short at the horn's blowing — until the Prince of Dragonstone takes up a plain shield: 'It seems my helm is dusty.'",
    ],
    people: [
      { name: "Ser Duncan the Tall", j: "dunk", note: "Begs half the meadow for champions and learns what men's oaths weigh." },
      { name: "Egg", j: "egg", note: "Aegon Targaryen, revealed — and it is his word that makes the trial possible at all." },
      { name: "Baelor Breakspear", j: "baelor", note: "The seventh man. The best man in the realm, on a hedge knight's side." },
      { name: "Raymun Fossoway", loc: "ashford-meadow", note: "Knighted at dawn by the Laughing Storm — the first green-apple Fossoway." },
      { name: "Ser Steffon Fossoway", loc: "ashford-meadow", note: "Sells his cousin's cause for a promise of advancement. The red apple, rotten." },
      { name: "Ser Lyonel Baratheon", loc: "ashford-meadow", note: "\"Ours is the fury\" — laughing, he takes his place in Dunk's seven." },
      { name: "Ser Humfrey Hardyng", loc: "ashford-meadow", note: "Carried to the lists rather than miss his answer to Aerion." },
      { name: "Ser Humfrey Beesbury", loc: "ashford-meadow", note: "Young, bold, and unwilling to let injustice stand." },
      { name: "Aerion Brightflame", j: "aerion", note: "Assembles his seven from Kingsguard white and bought apples." },
      { name: "Prince Maekar Targaryen", loc: "ashford-meadow", note: "Stands with his sons against his son's squire's knight. Blood before justice." },
    ],
    power: { targaryen: 10, blackfyre: 2, baratheon: 7, tyrell: 8, lannister: 7, stark: 6, martell: 6, ashford: 5, fossoway: 4, peake: 3 },
    deaths: [] },
  { n: 5, title: "The Judgment of the Gods",
    throne: { king: "Daeron II Targaryen, the Good", house: "targaryen", hand: "Prince Baelor Breakspear" },
    events: [
      "Seven against seven before the eyes of gods and men: Dunk's ragged seven against three princes, three Kingsguard, and a bought apple.",
      "The lances shatter and the melee closes in. The Laughing Storm bellows; Raymun finds his cousin Steffon and pays the family debt in steel.",
      "Ser Humfrey Beesbury dies in the press; Ser Humfrey Hardyng takes wounds no broken-legged man should bear.",
      "Aerion drives Dunk to the river's edge — and Dunk, remembering he was a boy of Flea Bottom before he was a knight, drops his sword and beats the yield out of him with his hands.",
      "Aerion recants. The trial is won — but across the field Prince Maekar's mace has found his brother Baelor's helm, and the Hand of the King is swaying in the saddle.",
    ],
    people: [
      { name: "Ser Duncan the Tall", j: "dunk", note: "Wins his hand, his foot, and his name — at a price no one would pay willingly." },
      { name: "Egg", j: "egg", note: "Watches his family fight itself over the knight he chose." },
      { name: "Baelor Breakspear", j: "baelor", note: "Takes a mace blow meant for no one and shrugs it off. For now." },
      { name: "Prince Maekar Targaryen", loc: "ashford-meadow", note: "His mace, his brother's helm — a blow no one saw land clean." },
      { name: "Aerion Brightflame", j: "aerion", note: "Recants his accusation with Dunk's fist as his conscience." },
      { name: "Ser Lyonel Baratheon", loc: "ashford-meadow", note: "Fights through the seven with a storm's own laughter." },
      { name: "Raymun Fossoway", loc: "ashford-meadow", note: "Green apple against red: he settles it with his cousin directly." },
      { name: "Tanselle", loc: "ashford-meadow", note: "Gone from the meadow before the trial ends — Dunk never finds her to say farewell." },
    ],
    power: { targaryen: 9, blackfyre: 2, baratheon: 7, tyrell: 8, lannister: 7, stark: 6, martell: 6, ashford: 5, fossoway: 4, peake: 3 },
    deaths: [
      { name: "Ser Humfrey Beesbury", note: "Died in the trial of seven, standing for a hedge knight's honor." },
    ] },
  { n: 6, title: "A Knight of the Seven Kingdoms",
    throne: { king: "Daeron II Targaryen, the Good", house: "targaryen", hand: "Vacant — the realm mourns Prince Baelor" },
    events: [
      "The blow that seemed nothing was everything: Baelor Breakspear, Prince of Dragonstone, Hand of the King, dies of a broken skull — killed by his brother's mace in a hedge knight's quarrel.",
      "The realm's future dies with him: the succession now runs through sickly Valarr, and the good years of Daeron's reign begin their long ending.",
      "Ser Humfrey Hardyng succumbs to his wounds; the meadow that hosted a wedding-feast tourney buries its dead instead.",
      "Prince Maekar comes to Dunk not with vengeance but a question — and an offer: take Aegon as your squire; show him the realm his brothers will never see.",
      "Aerion is packed off to Lys, Daeron to a watch he'll drink through. And a hedge knight rides south for Dorne with a prince shining his kettle helm — Ser Duncan the Tall, of no house, of the Seven Kingdoms.",
    ],
    people: [
      { name: "Ser Duncan the Tall", j: "dunk", note: "Wonders forever whether one good man's life was worth his foot and his hand." },
      { name: "Egg", j: "egg", note: "A prince apprenticed to the realm itself, one muddy road at a time." },
      { name: "Prince Maekar Targaryen", loc: "ashford-meadow", note: "Carries his brother's death in his hand for the rest of his days." },
      { name: "Valarr Targaryen", loc: "kings-landing", note: "The Young Prince inherits Dragonstone — and none of his father's greatness." },
      { name: "Aerion Brightflame", j: "aerion", note: "Exiled to Lys, where the wine is stronger and the patience shorter." },
      { name: "King Daeron II Targaryen", loc: "kings-landing", note: "Buries his best son and keeps his peace. The peace is all he has left." },
    ],
    power: { targaryen: 8, blackfyre: 3, baratheon: 7, tyrell: 8, lannister: 7, stark: 6, martell: 6, ashford: 4, fossoway: 4, peake: 3 },
    deaths: [
      { name: "Baelor Breakspear", note: "The best man in the realm, dead of his brother's mace — the price of a hedge knight's honor." },
      { name: "Ser Humfrey Hardyng", note: "Died of his wounds from the trial of seven, unbowed to the last." },
    ] },
];

/* expand rows into location objects */
WORLD.locations = LOCATION_ROWS.map(([name, x, y, type, region, rank, subtitle, description]) => {
  const id = name.toLowerCase().replace(/[''’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const minorArms = MINOR_ARMS[id] ? { ...MINOR_ARMS[id] } : null;
  if (minorArms && CANON_MINOR_SHIELDS.has(id)) minorArms.img = `minor/${id}.png`;
  return {
    id, name, x, y, type, region, rank, subtitle, description,
    lore: SEASON_LORE[id] || null,
    house: HOUSE_SEATS[id] || null,
    minorArms,
  };
});
