/* A KNIGHT OF THE SEVEN KINGDOMS WIKI — hand-written long-form articles.
   Keys: a character's exact name, "house:<id>", or "loc:<id>".
   Values: an array of paragraphs (original text — never copied from any wiki). */

const WIKI_EXTRA = {

  "Ser Duncan the Tall": [
    "Dunk begins as a rumor about himself: a gutter-born boy of Flea Bottom, taken up by an old hedge knight for his size and his willingness to work, who buries his master by a roadside and decides — with a grave-digger's practicality — that the knighthood need not go in the hole too. Whether Ser Arlan ever actually knighted him is a question Dunk is careful not to examine; what he does with the name is the answer that matters.",
    "At Ashford Meadow he commits the truest act of knighthood in the entire saga: he sees a prince of the blood breaking a puppeteer's fingers and hits him, knowing exactly what hitting a Targaryen costs. The trial of seven that follows — where the realm's best men must decide, with their bodies, whether a hedge knight's honor is worth dying for — buys his name at the price of Prince Baelor's life, a debt Dunk carries in his kettle helm forever after. He wins his hand, his foot, and a squire: a bald princeling who chose him, not the other way round.",
    "The tales that follow — the drought at Standfast, the wedding at Whitewalls — are Dunk learning what the songs leave out: that oaths bind hardest when the lord is a fool, that treason smells like a wedding feast, and that thinking with your heart is a strategy with a body count and a conscience worth keeping anyway. History knows where the road ends: Ser Duncan the Tall, Lord Commander of the Kingsguard to the boy he taught to shine boots — and a shooting star over an elm on the arms of a house that began in Flea Bottom.",
  ],
  "Egg": [
    "Aegon Targaryen, fourth son of a fourth son, works out early that the realm has no particular use for him — which he converts, with a boy's ruthlessness, into freedom. He shaves the head that would name him in any market square, talks his way into a hedge knight's service, and gets the education no prince before him ever had: the realm from below, at stable-muck level, where the knights of the songs are the same men who ride you down at tourney.",
    "Egg's boot holds the tale's best-kept secret — his father's signet, worth armies, spent exactly once at Whitewalls to buy a fair trial for a knight nobody else would stand for. That instinct, princes exist to be spent on justice, is Dunk's lesson taking root; the realm will hear from it. For history remembers the bald little squire by another name: King Aegon V, the Unlikely, the one king in the dynasty's history who tried to give the smallfolk the law — and whose reign began on a muddy road, holding a hedge knight's horse.",
  ],
  "Baelor Breakspear": [
    "Baelor Targaryen is what the realm believes princes are supposed to be and almost never are: heir to the Iron Throne, hero of the Redgrass Field where his hammer-and-anvil broke the black dragon's host, Hand of the King to his father's peace — and a man so unspoiled by all of it that he goes to a country tourney and notices a hedge knight's honor as something worth his own life. His dark Dornish coloring, the grumblers' favorite complaint, is the outward sign of the marriage-made peace he embodies.",
    "At Ashford he does the thing the tales cannot stop turning over: when Dunk's trial of seven stands one champion short and every knight on the meadow finds his helm suddenly interesting, the Prince of Dragonstone takes up a plain shield — 'it seems my helm is dusty' — and fights against his own brother and nephews for a stranger's justice. The mace blow that cracks his skull comes from Maekar's hand but belongs to the whole realm's arithmetic: the best man in Westeros, traded for a hedge knight's hand and foot. Every year of the bad half-century that follows is a reminder of the price.",
  ],
  "Brynden Rivers": [
    "Brynden Rivers is the Great Bastard who chose the throne: albino, wine-stain birthmark, a thousand livres of rumor, legitimized in the same stroke as the half-brother he would spend his life fighting. At the Redgrass Field his weirwood bow and his Raven's Teeth ended Daemon Blackfyre and his sons on the spot where the grass turned red — and took Bittersteel's hatred, an eye, and the realm's permanent unease as his wages.",
    "As Hand and master of whisperers under Aerys I, Bloodraven runs the realm the way a spider runs a web: taxes, ravens, informers, and the useful legend that he sees every deed in the Seven Kingdoms from a thousand eyes and one. Whitewalls is his masterpiece — a rebellion gathered, watched, and harvested without a battle. The saga gives him one of its strangest codas: sent to the Wall for breaking a guest-peace the realm publicly required him to break, he vanishes beyond it, and readers of the main tale meet him again grown into a weirwood throne — the three-eyed crow who teaches a broken Stark boy to fly.",
  ],
  "Lady Rohanne Webber": [
    "The Red Widow of Coldmoat has buried four husbands and the neighborhood's good opinion, and runs the finest holding in the marches anyway — the accounts, the levies, the dam that starts a war. The whispers that she poisoned her way to widowhood are the price a competent woman pays in an age that lacks a better explanation; her father's will, which strips her of Coldmoat unless she weds again within the year, is the cage all that competence lives in.",
    "The Sworn Sword gives her the saga's best small war and its best small peace: a dammed stream, a burned wood, a trial in the water she claimed — and a resolution made the old way, wedding the ancient enemy at his own gate with the dowry both of them actually wanted, which was an end to counting graves. The lock of a certain hedge knight's hair she takes as her fee travels further in the histories than anyone at Coldmoat guessed: by way of her later marriage, Rohanne Webber becomes grandmother to the Lannisters of the main tale's age — the Red Widow's red hair running to Casterly Rock.",
  ],
  "house:targaryen": [
    "The dragons of Dunk and Egg's age are a house between catastrophes: the last dragon two generations dead, the Blackfyre wound still draining, and the throne held together by Daeron the Good's unfashionable competence. The family's problem is arithmetic — too many princes, too little for them to do — and the story of the era is the succession shaking itself out through fever, mischance and one mace blow at Ashford, until the crown lands on the heads nobody bet on.",
    "It is the age that explains the later ones. Aerion's cruelty and wildfire death, Aemon's chain and refusal, Egg's smallfolk laws, Summerhall's fire on the day of Rhaegar's birth — every legend the main tale inherits is planted here, on muddy roads and tourney meadows, mostly within earshot of a very tall hedge knight trying to keep his squire out of trouble.",
  ],
  "loc:ashford-meadow": [
    "A water-meadow on the Cockleswhent opposite Lord Ashford's castle, white with pavilions for one fortnight in 209 AC — and the hinge on which the dynasty's whole century turns. Lord Ashford's tourney in his daughter's honor draws three princes, five champions and half the chivalry of the Reach; it also draws a hedge knight with a borrowed shield, a puppeteer with a wooden dragon, and a stableboy with no hair.",
    "What happens on the meadow — a prince beaten in the mud for breaking a girl's fingers, a trial of seven fought over a nobody's honor, Baelor Breakspear dying of his brother's mace — rearranges the succession and the realm's conscience in one afternoon. The tales' quiet joke is that nobody won the tourney: the melee was never finished, the fair maid wed none of her champions, and the only prize anyone remembers is a hedge knight keeping his hand and his foot.",
  ],
  "loc:whitewalls": [
    "The Milkhouse rose on the Gods Eye's shore as the boast of the dairy-rich Butterwells — marble walls the color of cream, a sept with windows of colored glass, and a hall built to hold more ambition than its lord could safely digest. It stands for one generation. Lord Ambrose's second wedding fills it with every man who ever toasted the black dragon, a dragon's egg for a tourney prize, and a fiddler who dreams of crowns.",
    "The Second Blackfyre Rebellion begins and ends under its roof without a battle: the pretender unmasked, the egg vanished, Bloodraven's army around the walls by dawn. The crown's sentence is the age's coldest architecture criticism — Whitewalls is attainted, emptied, and pulled down stone by stone, so that no seat remains to gather treason. Travelers on the lakeshore road knew it afterward only as a scatter of pale rubble the smallfolk quarried for barns.",
  ],
};
