/* SIGIL MATCH — house/banner pool.
   { id, name, img, words?, d: 1 easy (great houses) | 3 hard (noble & minor houses), desc }
   Every entry's `img` is a real heraldry file already on disk (no procedural-only shields —
   those exist only as in-JS color specs on the maps and have no image file to show here).
   Descriptions are reused verbatim from the existing house/location data (WORLD.houses
   descriptions, or the matching LOCATION_ROWS blurb for that seat) wherever that text already
   exists site-wide — only the handful of houses with no prior prose got a new one-liner here.
   No saga picker and no spoiler shield for this game — heraldry isn't plot. */
window.SIGILS = [

  // ================= EASY — the Great Houses =================
  { id: "stark", name: "House Stark", img: "../assets/sigils/new/stark.webp", words: "Winter Is Coming", d: 1,
    desc: "Kings of Winter turned Wardens of the North, the Starks have ruled from Winterfell for eight thousand years — since the Age of Heroes and Bran the Builder. Grey direwolves on white ice, they keep the old gods and the First Men's ways, ruling the largest and coldest of the Seven Kingdoms with a hard, plain northern honor." },
  { id: "lannister", name: "House Lannister", img: "../assets/sigils/lannister.svg", words: "Hear Me Roar", d: 1,
    desc: "The richest house in the Seven Kingdoms, lords of Casterly Rock and the gold mines beneath it, whose true motto is said to be 'A Lannister always pays his debts.' A golden lion on crimson, descended from Lann the Clever, they hold the Westerlands and command wealth enough to buy armies, crowns, and kings." },
  { id: "baratheon", name: "House Baratheon", img: "../assets/sigils/baratheon.svg", words: "Ours Is the Fury", d: 1,
    desc: "The youngest of the great houses, sprung from an Orys Baratheon who was rumored a Targaryen's bastard brother, seated at storm-battered Storm's End on the narrow sea. A crowned black stag on gold — strong, proud, and famously stubborn lords of the Stormlands." },
  { id: "targaryen", name: "House Targaryen", img: "../assets/sigils/new/targaryen.webp", words: "Fire and Blood", d: 1,
    desc: "The dragonlords of old Valyria, silver-haired and violet-eyed, who alone survived the Doom and conquered the Seven Kingdoms astride dragons. A three-headed red dragon on black, they ruled from the Iron Throne for near three hundred years before the rebellion cast the last of them into exile across the narrow sea." },
  { id: "tully", name: "House Tully", img: "../assets/sigils/tully.svg", words: "Family, Duty, Honor", d: 1,
    desc: "Lords of Riverrun and Lords Paramount of the Trident, raised to rule the fertile, much-fought-over Riverlands after Aegon's Conquest. A silver trout leaping on a field of red and blue, the Tullys are known for binding themselves to greater houses through marriage — and for their words, which name what they hold dearest." },
  { id: "arryn", name: "House Arryn", img: "../assets/sigils/arryn.svg", words: "As High as Honor", d: 1,
    desc: "The purest blood of the First Men and the Andal kings, Wardens of the East, enthroned in the Eyrie high in the Mountains of the Moon above the rich and sheltered Vale of Arryn. A white moon-and-falcon on sky blue, their mountain seat is reckoned impregnable, reached only through the Bloody Gate and a chain of castles." },
  { id: "greyjoy", name: "House Greyjoy", img: "../assets/sigils/new/greyjoy.webp", words: "We Do Not Sow", d: 1,
    desc: "Ironborn lords of Pyke and the bleak Iron Islands, who follow the Drowned God and the Old Way of reaving, taking their wealth and their salt wives at the point of a sword. A golden kraken on black, they hold that 'What is dead may never die,' and bow to the green lands only when they must." },
  { id: "frey", name: "House Frey", img: "../assets/sigils/frey.svg", words: "We Stand Together", d: 1,
    desc: "Upjumped and enormously numerous, the Freys have held the only bridge across the Green Fork for six hundred years, growing rich on the tolls of the Twins. Two blue towers joined by a bridge on grey, they are bannermen to the Tullys — resented for their new blood and their habit of arriving late to every battle." },
  { id: "tyrell", name: "House Tyrell", img: "../assets/sigils/tyrell.svg", words: "Growing Strong", d: 1,
    desc: "Wardens of the South and Lords of Highgarden, stewards risen to rule the vast, fertile Reach — second only to the Lannisters in wealth and first in men. A golden rose on green, they command the largest armies in the realm and the deepest granaries, and cultivate influence as carefully as their famous gardens." },
  { id: "martell", name: "House Martell", img: "../assets/sigils/new/martell.webp", words: "Unbowed, Unbent, Unbroken", d: 1,
    desc: "Princes of Dorne, the last kingdom to bow to the dragons — and only by marriage, never by conquest. A red sun pierced by a golden spear, the Martells rule the hot southern deserts from Sunspear by Rhoynish law and custom, patient, proud, and long of memory." },

  // ================= HARD — Noble Houses =================
  { id: "bolton", name: "House Bolton", img: "../assets/sigils/bolton.svg", words: "Our Blades Are Sharp", d: 3,
    desc: "Grim seat of the Boltons at the Dreadfort, whose banner is a flayed man and whose loyalty is a knife held politely." },
  { id: "clegane", name: "House Clegane", img: "../assets/sigils/clegane.svg", d: 3,
    desc: "The modest towerhouse of the Cleganes — kennelmasters raised to knighthood, whose sons grew anything but modest." },
  { id: "mormont", name: "House Mormont", img: "../assets/sigils/mormont.svg", words: "Here We Stand", d: 3,
    desc: "A cold island of woods and fisherfolk in the Bay of Ice, seat of House Mormont — poor in gold, rich in axes, and stubborn beyond all sense." },
  { id: "tarly", name: "House Tarly", img: "../assets/sigils/tarly.svg", words: "First in Battle", d: 3,
    desc: "The Tarlys' seat beneath the foothills of the Red Mountains — the home Samwell Tarly was made to renounce at spearpoint." },
  { id: "karstark", name: "House Karstark", img: "../assets/sigils/karstark.svg", words: "The Sun of Winter", d: 3,
    desc: "Eastern seat of the Karstarks, kin to the Starks of old, sworn to Winterfell since a younger son first rode east to claim it." },
  { id: "seaworth", name: "House Seaworth", img: "../assets/sigils/seaworth.svg", d: 3,
    desc: "A smuggler-turned-knight's new house, raised from nothing by Stannis Baratheon for service beyond the call of birth — its sigil an onion and a black ship, in memory of both." },
  { id: "baelish", name: "House Baelish", img: "../assets/sigils/baelish.svg", d: 3,
    desc: "The smallest lordship in the Vale, four stony peninsulas of sheep pellets and salt wind — whose most famous son named himself for it and climbed all the way to the king's council." },
  { id: "reed", name: "House Reed", img: "../assets/sigils/reed.svg", d: 3,
    desc: "A crannogman house of Greywater Watch, a castle in the Neck's bogs said to move with the seasons and never be found by those not welcome." },
  { id: "tarth", name: "House Tarth", img: "../assets/sigils/tarth.svg", d: 3,
    desc: "Seat of the Tarths at Evenfall Hall on the Sapphire Isle, said to be the loveliest island in the narrow sea." },

  // ================= HARD — Minor Houses (the North) =================
  { id: "umber", name: "House Umber", img: "../assets/sigils/minor/last-hearth.png", d: 3,
    desc: "Home of the Greatjon and his enormous kin, the last hearth before the Gift and the Wall." },
  { id: "hornwood", name: "House Hornwood", img: "../assets/sigils/minor/hornwood.png", d: 3,
    desc: "A modest forest seat between the Dreadfort and White Harbor." },
  { id: "tallhart", name: "House Tallhart", img: "../assets/sigils/minor/torrhens-square.png", d: 3,
    desc: "A square towered keep at Torrhen's Square, named for the King Who Knelt." },
  { id: "cerwyn", name: "House Cerwyn", img: "../assets/sigils/minor/castle-cerwyn.png", d: 3,
    desc: "Half a day's ride from Winterfell, home of the Starks' nearest bannermen." },
  { id: "dustin", name: "House Dustin", img: "../assets/sigils/minor/barrowton.png", d: 3,
    desc: "A wooden town raised around the Great Barrow of the First King, ruled by House Dustin." },
  { id: "flint-widows-watch", name: "House Flint", img: "../assets/sigils/minor/widows-watch.png", d: 3,
    desc: "A lonely watch upon the easternmost point of the North, staring out over the Shivering Sea." },
  { id: "manderly", name: "House Manderly", img: "../assets/sigils/minor/white-harbor.png", d: 3,
    desc: "The North's only true city, a clean white port at the mouth of the White Knife, held by House Manderly for the Starks." },
  { id: "locke", name: "House Locke", img: "../assets/sigils/minor/oldcastle.png", d: 3,
    desc: "An old grey seat where the Bite gnaws at the shore." },
  { id: "flint-finger", name: "House Flint of the Finger", img: "../assets/sigils/minor/flints-finger.png", d: 3,
    desc: "A stony seat on the cape above Blazewater Bay." },

  // ================= HARD — Minor Houses (the Riverlands) =================
  { id: "mallister", name: "House Mallister", img: "../assets/sigils/minor/seagard.png", d: 3,
    desc: "A fortified port raised to guard the coast against ironborn raiders, seat of House Mallister." },
  { id: "blackwood", name: "House Blackwood", img: "../assets/sigils/minor/raventree-hall.png", d: 3,
    desc: "Seat of the old-gods-keeping Blackwoods, forever feuding with the Brackens across the river." },
  { id: "bracken", name: "House Bracken", img: "../assets/sigils/minor/stone-hedge.png", d: 3,
    desc: "The Brackens' seat on the Red Fork, across an ancient grudge from Raventree Hall." },
  { id: "whent", name: "House Whent", img: "../assets/sigils/minor/harrenhal.png", d: 3,
    desc: "The greatest castle ever raised — and a ruin since Aegon's dragons melted its towers. Every house that holds it comes to grief." },
  { id: "piper", name: "House Piper", img: "../assets/sigils/minor/pinkmaiden.png", d: 3,
    desc: "The Pipers' seat at Pinkmaiden, on the upper Red Fork." },

  // ================= HARD — Minor Houses (the Vale) =================
  { id: "royce", name: "House Royce", img: "../assets/sigils/minor/runestone.png", d: 3,
    desc: "Ancient seat of the Royces, whose bronze armor is graven with runes older than the Andals." },
  { id: "grafton", name: "House Grafton", img: "../assets/sigils/minor/gulltown.png", d: 3,
    desc: "The Vale's harbor city, held by House Grafton for the Arryns." },
  { id: "waxley", name: "House Waxley", img: "../assets/sigils/minor/wickendon.png", d: 3,
    desc: "A quiet seat on Crackclaw Point, south of the Vale's mountains." },

  // ================= HARD — Minor Houses (the Westerlands) =================
  { id: "farman", name: "House Farman", img: "../assets/sigils/minor/faircastle.png", d: 3,
    desc: "The seat of House Farman on Fair Isle, whose shores shelter the western coast." },
  { id: "westerling", name: "House Westerling", img: "../assets/sigils/minor/the-crag.png", d: 3,
    desc: "A half-ruined seat above the sea, rich in honor and poor in gold." },
  { id: "marbrand", name: "House Marbrand", img: "../assets/sigils/minor/ashemark.png", d: 3,
    desc: "The Marbrands' seat at the edge of the western hills." },
  { id: "lefford", name: "House Lefford", img: "../assets/sigils/minor/golden-tooth.png", d: 3,
    desc: "The small strong castle that locks the hill road between the Riverlands and the West." },
  { id: "lydden", name: "House Lydden", img: "../assets/sigils/minor/deep-den.png", d: 3,
    desc: "A den-like seat in the hills along the goldroad." },
  { id: "swyft", name: "House Swyft", img: "../assets/sigils/minor/cornfield.png", d: 3,
    desc: "The Swyfts' seat amid the southern fields of the West." },
  { id: "crakehall", name: "House Crakehall", img: "../assets/sigils/minor/crakehall.png", d: 3,
    desc: "Seat of the boar-sigiled Crakehalls, big men with big appetites." },

  // ================= HARD — Minor Houses (the Crownlands) =================
  { id: "mooton", name: "House Mooton", img: "../assets/sigils/minor/maidenpool.png", d: 3,
    desc: "A port town on the Bay of Crabs where Florian first saw Jonquil bathing, if the songs are true." },
  { id: "rosby", name: "House Rosby", img: "../assets/sigils/minor/rosby.png", d: 3,
    desc: "A small castle astride the road from Duskendale to the capital." },
  { id: "celtigar", name: "House Celtigar", img: "../assets/sigils/minor/claw-isle.png", d: 3,
    desc: "Island seat of the Celtigars, old Valyrian blood sworn to Dragonstone." },

  // ================= HARD — Minor Houses (the Reach) =================
  { id: "oakheart", name: "House Oakheart", img: "../assets/sigils/minor/old-oak.png", d: 3,
    desc: "An ancient seat by the sea road north of Highgarden." },
  { id: "crane", name: "House Crane", img: "../assets/sigils/minor/red-lake.png", d: 3,
    desc: "The Cranes' castle on the shore of its namesake lake." },
  { id: "rowan", name: "House Rowan", img: "../assets/sigils/minor/goldengrove.png", d: 3,
    desc: "The Rowans' golden-treed seat in the northern Reach." },
  { id: "caswell", name: "House Caswell", img: "../assets/sigils/minor/bitterbridge.png", d: 3,
    desc: "Where the roseroad crosses the Mander over an ancient stone bridge." },
  { id: "meadows", name: "House Meadows", img: "../assets/sigils/minor/grassy-vale.png", d: 3,
    desc: "A green seat at the eastern edge of the Reach." },
  { id: "merryweather", name: "House Merryweather", img: "../assets/sigils/minor/long-table.png", d: 3,
    desc: "A seat famed for its groaning boards and generous lords." },
  { id: "florent", name: "House Florent", img: "../assets/sigils/minor/brightwater-keep.png", d: 3,
    desc: "Seat of the fox-eared Florents, forever insisting Highgarden should be theirs." },
  { id: "blackbar", name: "House Blackbar", img: "../assets/sigils/minor/bandallon.png", d: 3,
    desc: "A coastal seat overlooking the Redwyne Straits." },
  { id: "beesbury", name: "House Beesbury", img: "../assets/sigils/minor/honeyholt.png", d: 3,
    desc: "The Beesburys' seat amid orchards and hives on the Honeywine." },
  { id: "bulwer", name: "House Bulwer", img: "../assets/sigils/minor/blackcrown.png", d: 3,
    desc: "A seat at the western tip of the Reach, south of Oldtown." },
  { id: "mullendore", name: "House Mullendore", img: "../assets/sigils/minor/uplands.png", d: 3,
    desc: "A hillside seat above the Honeywine's valley." },
  { id: "costayne", name: "House Costayne", img: "../assets/sigils/minor/three-towers.png", d: 3,
    desc: "Three joined towers on the Whispering Sound's southern arm." },
  { id: "cuy", name: "House Cuy", img: "../assets/sigils/minor/sun-house.png", d: 3,
    desc: "A sunny coastal seat on the Reach's southern shore." },
  { id: "prester", name: "House Prester", img: "../assets/sigils/minor/feastfires.png", d: 3,
    desc: "A headland seat looking out over the Sunset Sea." },
  { id: "ashford", name: "House Ashford", img: "../knight/assets/sigils/ashford.svg", words: "", d: 3,
    desc: "Lords of the castle and market town on the Cockleswhent, bannermen to Highgarden — best remembered for a tourney that drew three princes and half the chivalry of the Reach." },
  { id: "hightower", name: "House Hightower", img: "../hotd/assets/sigils/hightower.svg", words: "We Light the Way", d: 3,
    desc: "Lords of Oldtown since before memory, keepers of the great lighthouse tower that gives them their name and their words. A white stone tower crowned with fire on smoke grey, patrons of the Citadel and the Faith both." },

  // ================= HARD — Minor Houses (the Stormlands) =================
  { id: "wylde", name: "House Wylde", img: "../assets/sigils/minor/rain-house.png", d: 3,
    desc: "A rain-lashed castle at the wet edge of Cape Wrath." },
  { id: "swann", name: "House Swann", img: "../assets/sigils/minor/stonehelm.png", d: 3,
    desc: "The Swanns' seat above the Slayne in the Red Watch." },
  { id: "connington", name: "House Connington", img: "../assets/sigils/minor/griffins-roost.png", d: 3,
    desc: "A red-stone seat on a headland shaped like a griffin's beak." },
  { id: "dondarrion", name: "House Dondarrion", img: "../assets/sigils/minor/blackhaven.png", d: 3,
    desc: "The Dondarrions' marcher seat, its banner a purple lightning bolt on black." },
  { id: "caron", name: "House Caron", img: "../assets/sigils/minor/nightsong.png", d: 3,
    desc: "The marcher seat of the Carons, lords of the nightingales." },

  // ================= HARD — Minor Houses (Dorne) =================
  { id: "manwoody", name: "House Manwoody", img: "../assets/sigils/minor/kingsgrave.png", d: 3,
    desc: "A mountain seat named for a king slain at its gates." },
  { id: "blackmont", name: "House Blackmont", img: "../assets/sigils/minor/blackmont.png", d: 3,
    desc: "A western Dornish seat above the Torentine." },
  { id: "qorgyle", name: "House Qorgyle", img: "../assets/sigils/minor/sandstone.png", d: 3,
    desc: "A sand-scoured seat deep in the Dornish desert." },
  { id: "jordayne", name: "House Jordayne", img: "../assets/sigils/minor/the-tor.png", d: 3,
    desc: "A seaside seat on the Sea of Dorne." },
  { id: "yronwood", name: "House Yronwood", img: "../assets/sigils/minor/yronwood.png", d: 3,
    desc: "Seat of the proudest house in Dorne after the Martells — 'the Bloodroyal', wardens of the Boneway." },
  { id: "dayne", name: "House Dayne", img: "../assets/sigils/minor/starfall.png", d: 3,
    desc: "The Daynes' seat on the Torentine, home of the sword Dawn and the memory of Ser Arthur, the Sword of the Morning." },
  { id: "wyl", name: "House Wyl", img: "../assets/sigils/minor/wyl.png", d: 3,
    desc: "A marcher seat in the Boneway, old in border blood." },
  { id: "dalt", name: "House Dalt", img: "../assets/sigils/minor/lemonwood.png", d: 3,
    desc: "A lemon-orcharded seat near the mouth of the Greenblood." },
  { id: "gargalen", name: "House Gargalen", img: "../assets/sigils/minor/salt-shore.png", d: 3,
    desc: "A southern coastal seat on the Summer Sea." },

  // ================= HARD — House of the Dragon exclusives =================
  { id: "velaryon", name: "House Velaryon", img: "../hotd/assets/sigils/velaryon.svg", words: "The Old, the True, the Brave", d: 3,
    desc: "An old Valyrian house that came to Westeros before the dragonlords themselves, seated at High Tide on the island of Driftmark. A silver seahorse on sea green, they are the realm's masters of ship and salt, their blood joined to the dragon's by marriage twice over." },
  { id: "strong", name: "House Strong", img: "../hotd/assets/sigils/strong.svg", d: 3,
    desc: "A river lord's family raised to the lordship of Harrenhal by King Viserys I — and later whispered, scandalously, to be the true fathers of Queen Rhaenyra's sons." },

  // ================= HARD — A Knight of the Seven Kingdoms exclusives =================
  { id: "blackfyre", name: "House Blackfyre", img: "../knight/assets/sigils/blackfyre.svg", words: "Fire and Blood", d: 3,
    desc: "The dragon reversed: the line of Daemon Blackfyre, King Aegon the Unworthy's legitimized bastard, who took the Conqueror's sword for his name and half the realm to war for his claim. Daemon died at Redgrass Field — but his sons live on in exile, and plenty of disappointed men still drink to the black dragon." },
  { id: "osgrey", name: "House Osgrey", img: "../knight/assets/sigils/osgrey.svg", words: "The Lion Still Stands", d: 3,
    desc: "The chequy lions of Standfast, once Marshals of the Northmarch and lords of all the land between Highgarden and the sea — now masters of one old towerhouse, three fields, and a dry wood." },
  { id: "webber", name: "House Webber", img: "../knight/assets/sigils/webber.svg", words: "In Our Web", d: 3,
    desc: "Lords of Coldmoat, whose banner is a spotted spider on a silver web. Lady Rohanne — the Red Widow, four times wed and four times widowed — holds the castle in her own right." },
  { id: "butterwell", name: "House Butterwell", img: "../knight/assets/sigils/butterwell.svg", words: "In Cream and Amber", d: 3,
    desc: "Dairy lords grown rich enough to raise Whitewalls, the milk-white marble palace by the Gods Eye that men call the Milkhouse." },
  { id: "peake", name: "House Peake", img: "../knight/assets/sigils/peake.svg", words: "Three Castles, One Due", d: 3,
    desc: "Proud marcher lords who once held three castles and lost two for backing the black dragon at Redgrass Field — a debt their lord counts daily, and means to collect." },
  { id: "fossoway", name: "House Fossoway", img: "../knight/assets/sigils/fossoway.svg", words: "A Taste of Glory", d: 3,
    desc: "The apple knights of Cider Hall — a single house that would soon split at the stem into rival red-apple and green-apple branches over a quarrel born at a tourney." },
];
