/* THE KNOWN WORLD — world data, keyed to the ASOIAF map image (5652 × 3682 px).
   Every location below is a labeled dot on the map; x/y are image pixels.
   Story scope: Season One of the show only.

   Row format: [name, x, y, type, region, rank, subtitle, description]
     type:  castle | city | town | ruin | landmark
     rank:  1 = always labeled · 2 = labeled when zoomed in · 3 = close zoom only */

const LOCATION_ROWS = [
  // ---------------- The North & the Wall ----------------
  ["Winterfell", 1207, 745, "castle", "the-north", 1, "Seat of House Stark",
    "The ancient stronghold of the Kings of Winter, built over hot springs ten thousand years ago. Its granite walls have never been taken by storm."],
  ["Castle Black", 1424, 258, "castle", "the-north", 1, "Stronghold of the Night's Watch",
    "The chief fortress of the Night's Watch, a grim huddle of keeps at the foot of the Wall with seven hundred feet of ice at its back."],
  ["The Shadow Tower", 1286, 245, "castle", "the-north", 3, "Western castle of the Watch",
    "Westernmost manned castle of the Night's Watch, guarding the mountain end of the Wall."],
  ["Eastwatch-by-the-Sea", 1546, 255, "castle", "the-north", 3, "Eastern castle of the Watch",
    "The Watch's port castle at the eastern end of the Wall, where its few ships put to sea."],
  ["Craster's Keep", 1351, 187, "landmark", "the-north", 3, "A wildling's hall beyond the Wall",
    "The daubed hall of Craster, a free folk man who keeps his daughters as wives and stays on cold terms with harder things."],
  ["White Tree", 1392, 224, "landmark", "the-north", 3, "Wildling village",
    "A tiny free folk village beyond the Wall, named for the great weirwood at its heart."],
  ["Fist of the First Men", 1252, 128, "ruin", "the-north", 3, "Ancient ringfort",
    "A bare hill crowned by a ringwall of the First Men, older than any song."],
  ["Hardhome", 1585, 115, "ruin", "the-north", 3, "Ruined haven of the free folk",
    "The only thing like a town the free folk ever raised, on the sheltered bay of Storrold's Point — emptied six hundred years ago in a night of fire no one can explain, and shunned ever since."],
  ["Bear Island", 930, 415, "castle", "the-north", 3, "Seat of House Mormont",
    "A cold island of woods and fisherfolk in the Bay of Ice, seat of House Mormont — poor in gold, rich in axes, and stubborn beyond all sense."],
  ["Queenscrown", 1338, 310, "ruin", "the-north", 3, "Abandoned holdfast",
    "A deserted tower in a lake in the New Gift, its gilded merlons remembered in its name."],
  ["Last Hearth", 1494, 495, "castle", "the-north", 2, "Seat of House Umber",
    "Home of the Greatjon and his enormous kin, the last hearth before the Gift and the Wall."],
  ["Karhold", 1726, 559, "castle", "the-north", 2, "Seat of House Karstark",
    "Eastern seat of the Karstarks, kin to the Starks of old. Lord Rickard rides south with Robb this season."],
  ["The Dreadfort", 1522, 692, "castle", "the-north", 2, "Seat of House Bolton",
    "Grim seat of the Boltons, whose banner is a flayed man and whose loyalty is a knife held politely."],
  ["Hornwood", 1463, 828, "castle", "the-north", 3, "Seat of House Hornwood",
    "A modest forest seat between the Dreadfort and White Harbor."],
  ["Torrhen's Square", 999, 865, "castle", "the-north", 3, "Seat of House Tallhart",
    "A square towered keep named for the King Who Knelt."],
  ["Castle Cerwyn", 1202, 874, "castle", "the-north", 3, "Seat of House Cerwyn",
    "Half a day's ride from Winterfell, home of the Starks' nearest bannermen."],
  ["Barrowton", 962, 1047, "town", "the-north", 3, "Town of House Dustin",
    "A wooden town raised around the Great Barrow of the First King, ruled by House Dustin."],
  ["Ramsgate", 1602, 995, "castle", "the-north", 3, "Holdfast of the eastern shore",
    "A small seat on the White Knife's eastern shore, sworn to White Harbor."],
  ["Widow's Watch", 1780, 1016, "castle", "the-north", 3, "Seat of House Flint",
    "A lonely watch upon the easternmost point of the North, staring out over the Shivering Sea."],
  ["White Harbor", 1361, 1059, "city", "the-north", 2, "City of House Manderly",
    "The North's only true city, a clean white port at the mouth of the White Knife, held by House Manderly for the Starks."],
  ["Oldcastle", 1406, 1161, "castle", "the-north", 3, "Seat of House Locke",
    "An old grey seat where the Bite gnaws at the shore."],
  ["Moat Cailin", 1228, 1120, "ruin", "the-north", 2, "Ruined guard of the Neck",
    "Three crumbling towers commanding the causeway through the swamps of the Neck — the ancient lock on the door to the North."],
  ["Flint's Finger", 765, 1242, "castle", "the-north", 3, "Seat of House Flint of the Finger",
    "A stony seat on the cape above Blazewater Bay."],

  // ---------------- The Iron Islands ----------------
  ["Pyke", 743, 1630, "castle", "iron-islands", 1, "Seat of House Greyjoy",
    "A castle of black stone strung across sea-stacks and rope bridges, battered by the Sunset Sea."],
  ["Faircastle", 700, 1839, "castle", "the-westerlands", 3, "Seat of House Farman",
    "The seat of House Farman on Fair Isle, whose shores shelter the western coast."],

  // ---------------- The Riverlands ----------------
  ["The Twins", 1143, 1452, "castle", "the-riverlands", 1, "Seat of House Frey",
    "Two matched castles bridging the Green Fork, whose tolls have made cranky old Walder Frey rich and proud."],
  ["Seagard", 1105, 1529, "castle", "the-riverlands", 2, "Seat of House Mallister",
    "A fortified port raised to guard the coast against ironborn raiders, seat of House Mallister."],
  ["Wendish Town", 1110, 1636, "town", "the-riverlands", 3, "River village",
    "A small riverside town in the Mallister lands — the kind of place armies burn on their way somewhere else."],
  ["Raventree Hall", 1089, 1708, "castle", "the-riverlands", 3, "Seat of House Blackwood",
    "Seat of the old-gods-keeping Blackwoods, forever feuding with the Brackens across the river."],
  ["Riverrun", 1088, 1765, "castle", "the-riverlands", 1, "Seat of House Tully",
    "A three-sided castle at the meeting of the Tumblestone and the Red Fork, ancestral seat of House Tully."],
  ["Stone Hedge", 1178, 1753, "castle", "the-riverlands", 3, "Seat of House Bracken",
    "The Brackens' seat on the Red Fork, across an ancient grudge from Raventree Hall."],
  ["High Heart", 1170, 1809, "landmark", "the-riverlands", 3, "Sacred hill of the First Men",
    "A high bald hill ringed by weirwood stumps, holy to the children of the forest — and said to be haunted still."],
  ["Acorn Hall", 1154, 1829, "castle", "the-riverlands", 3, "Seat of House Smallwood",
    "A snug forest keep in the foothills south of the Trident."],
  ["Harrenhal", 1295, 1807, "castle", "the-riverlands", 1, "The burned giant",
    "The greatest castle ever raised — and a ruin since Aegon's dragons melted its towers. Every house that holds it comes to grief."],
  ["Pinkmaiden", 1068, 1867, "castle", "the-riverlands", 3, "Seat of House Piper",
    "The Pipers' seat on the upper Red Fork."],
  ["Stoney Sept", 1142, 1945, "town", "the-riverlands", 2, "Town of the bells",
    "The town where Robert hid before the Battle of the Bells in his rebellion — its ringing saved his life."],

  // ---------------- The Vale ----------------
  ["The Eyrie", 1587, 1593, "castle", "the-vale", 1, "Seat of House Arryn",
    "A castle of white stone atop the Giant's Lance, reached by a goat path and defended by the sky itself."],
  ["The Bloody Gate", 1514, 1627, "landmark", "the-vale", 3, "Gate of the Vale",
    "The narrow pass where the Knight of the Gate asks who would enter the Vale — and armies die asking."],
  ["Runestone", 1836, 1608, "castle", "the-vale", 3, "Seat of House Royce",
    "Ancient seat of the Royces, whose bronze armor is graven with runes older than the Andals."],
  ["Gulltown", 1800, 1642, "city", "the-vale", 2, "Port city of the Vale",
    "The Vale's harbor city, held by House Grafton for the Arryns."],
  ["Wickendon", 1597, 1791, "castle", "the-crownlands", 3, "Seat of House Waxley",
    "A quiet seat on Crackclaw Point, south of the Vale's mountains."],

  // ---------------- The Westerlands ----------------
  ["Casterly Rock", 740, 1956, "castle", "the-westerlands", 1, "Seat of House Lannister",
    "A fortress carved into a golden rock above the Sunset Sea, seat of the wealthiest house in the Seven Kingdoms."],
  ["Lannisport", 732, 1973, "city", "the-westerlands", 2, "City of the Lannisters",
    "A walled port city in the shadow of the Rock, home of the Lannister fleet."],
  ["The Crag", 776, 1778, "castle", "the-westerlands", 3, "Seat of House Westerling",
    "A half-ruined seat above the sea, rich in honor and poor in gold."],
  ["Ashemark", 848, 1825, "castle", "the-westerlands", 3, "Seat of House Marbrand",
    "The Marbrands' seat at the edge of the western hills."],
  ["Golden Tooth", 948, 1858, "castle", "the-westerlands", 2, "Gate of the Westerlands",
    "The small strong castle that locks the hill road between the Riverlands and the West — the Lannister armies march past it this season."],
  ["Hornvale", 1010, 1897, "castle", "the-westerlands", 3, "Seat of House Brax",
    "A valley seat in the eastern hills of the West."],
  ["Deep Den", 975, 1999, "castle", "the-westerlands", 3, "Seat of House Lydden",
    "A den-like seat in the hills along the goldroad."],
  ["Silverhill", 934, 2100, "castle", "the-westerlands", 3, "Seat of House Serrett",
    "A silver-veined hill seat of the Serretts."],
  ["Cornfield", 785, 2118, "castle", "the-westerlands", 3, "Seat of House Swyft",
    "The Swyfts' seat amid the southern fields of the West."],
  ["Crakehall", 660, 2186, "castle", "the-westerlands", 3, "Seat of House Crakehall",
    "Seat of the boar-sigiled Crakehalls, big men with big appetites."],
  ["Feastfires", 601, 1973, "castle", "the-westerlands", 3, "Seat of House Prester",
    "A headland seat looking out over the Sunset Sea."],

  // ---------------- The Crownlands ----------------
  ["King's Landing", 1535, 2057, "city", "the-crownlands", 1, "Capital of the Seven Kingdoms",
    "Aegon's city on Blackwater Bay, half a million souls beneath the Red Keep and the Great Sept of Baelor."],
  ["Maidenpool", 1533, 1860, "town", "the-crownlands", 2, "Town of House Mooton",
    "A port town on the Bay of Crabs where Florian first saw Jonquil bathing, if the songs are true."],
  ["Antlers", 1482, 1913, "castle", "the-crownlands", 3, "Seat of House Buckwell",
    "A modest seat in the hills north of King's Landing."],
  ["Rosby", 1513, 1967, "castle", "the-crownlands", 3, "Seat of House Rosby",
    "A small castle astride the road from Duskendale to the capital."],
  ["Dragonstone", 1758, 1932, "castle", "the-crownlands", 1, "Island seat of the old blood",
    "A brooding fortress of black stone shaped like dragons, raised by Valyrian art on a smoking island."],
  ["Claw Isle", 1830, 1816, "castle", "the-crownlands", 3, "Seat of House Celtigar",
    "Island seat of the Celtigars, old Valyrian blood sworn to Dragonstone."],

  // ---------------- The Reach ----------------
  ["Highgarden", 912, 2457, "castle", "the-reach", 1, "Seat of House Tyrell",
    "A castle of white towers and climbing roses above the Mander, heart of the garden of Westeros."],
  ["Old Oak", 705, 2307, "castle", "the-reach", 3, "Seat of House Oakheart",
    "An ancient seat by the sea road north of Highgarden."],
  ["Red Lake", 845, 2294, "castle", "the-reach", 3, "Seat of House Crane",
    "The Cranes' castle on the shore of its namesake lake."],
  ["Goldengrove", 914, 2297, "castle", "the-reach", 3, "Seat of House Rowan",
    "The Rowans' golden-treed seat in the northern Reach."],
  ["Tumbleton", 1305, 2176, "town", "the-reach", 3, "Town on the Mander",
    "A market town on the upper Mander, remembered for an old dance of dragons."],
  ["Bitterbridge", 1142, 2278, "castle", "the-reach", 3, "Seat of House Caswell",
    "Where the roseroad crosses the Mander over an ancient stone bridge."],
  ["Grassy Vale", 1270, 2283, "castle", "the-reach", 3, "Seat of House Meadows",
    "A green seat at the eastern edge of the Reach."],
  ["Long Table", 1108, 2331, "castle", "the-reach", 3, "Seat of House Merryweather",
    "A seat famed for its groaning boards and generous lords."],
  ["Cider Hall", 1035, 2387, "castle", "the-reach", 3, "Seat of House Fossoway",
    "The apple-sigiled Fossoways' seat at the meeting of the Mander and the Cockleswhent."],
  ["Ashford", 1147, 2421, "castle", "the-reach", 3, "Seat of House Ashford",
    "A castle and market town on the Cockleswhent, once host to a famous tourney."],
  ["Brightwater Keep", 740, 2548, "castle", "the-reach", 3, "Seat of House Florent",
    "Seat of the fox-eared Florents, forever insisting Highgarden should be theirs."],
  ["Bandallon", 640, 2551, "castle", "the-reach", 3, "Seat of House Blackbar",
    "A coastal seat overlooking the Redwyne Straits."],
  ["Honeyholt", 749, 2598, "castle", "the-reach", 3, "Seat of House Beesbury",
    "The Beesburys' seat amid orchards and hives on the Honeywine."],
  ["Horn Hill", 957, 2546, "castle", "the-reach", 2, "Seat of House Tarly",
    "The Tarlys' seat beneath the foothills of the Red Mountains — the home Samwell Tarly was made to renounce at spearpoint."],
  ["Oldtown", 720, 2668, "city", "the-reach", 1, "City of the Citadel",
    "The oldest city in Westeros, where the maesters forge their chains at the Citadel beneath the Hightower's beacon."],
  ["Blackcrown", 629, 2713, "castle", "the-reach", 3, "Seat of House Bulwer",
    "A seat at the western tip of the Reach, south of Oldtown."],
  ["Uplands", 830, 2669, "castle", "the-reach", 3, "Seat of House Mullendore",
    "A hillside seat above the Honeywine's valley."],
  ["Three Towers", 662, 2768, "castle", "the-reach", 3, "Seat of House Costayne",
    "Three joined towers on the Whispering Sound's southern arm."],
  ["Sun House", 810, 2861, "castle", "the-reach", 3, "Seat of House Cuy",
    "A sunny coastal seat on the Reach's southern shore."],

  // ---------------- The Stormlands ----------------
  ["Storm's End", 1654, 2358, "castle", "the-stormlands", 1, "Seat of House Baratheon",
    "A drum-towered castle whose walls have never fallen to storm or siege, ancestral seat of House Baratheon."],
  ["Griffin's Roost", 1608, 2411, "castle", "the-stormlands", 3, "Seat of House Connington",
    "A red-stone seat on a headland shaped like a griffin's beak."],
  ["Rain House", 1840, 2447, "castle", "the-stormlands", 3, "Seat of House Wylde",
    "A rain-lashed castle at the wet edge of Cape Wrath."],
  ["Stonehelm", 1515, 2508, "castle", "the-stormlands", 3, "Seat of House Swann",
    "The Swanns' seat above the Slayne in the Red Watch."],
  ["Mistwood", 1672, 2541, "castle", "the-stormlands", 3, "Seat of House Mertyns",
    "A seat deep in the misty rainwood."],
  ["Blackhaven", 1300, 2508, "castle", "the-stormlands", 3, "Seat of House Dondarrion",
    "The Dondarrions' marcher seat, its banner a purple lightning bolt — carried this season by Ser Beric, sent to arrest the Mountain."],
  ["Haystack Hall", 1635, 2259, "castle", "the-stormlands", 3, "Seat of House Errol",
    "A homely seat amid the fields north of Storm's End."],
  ["Felwood", 1472, 2265, "castle", "the-stormlands", 3, "Seat of House Fell",
    "A woodland keep in the kingswood's shadow."],
  ["Bronzegate", 1630, 2301, "castle", "the-stormlands", 3, "Seat of House Buckler",
    "A bronze-gated castle on the road from King's Landing to Storm's End."],
  ["Evenfall Hall", 1811, 2323, "castle", "the-stormlands", 3, "Seat of House Tarth",
    "Seat of the Tarths on the Sapphire Isle, said to be the loveliest island in the narrow sea."],

  // ---------------- Dorne ----------------
  ["Sunspear", 1798, 2863, "castle", "dorne", 1, "Seat of House Martell",
    "The winding-walled seat of House Martell at the edge of the eastern sea, shaded and slow to anger."],
  ["Nightsong", 1115, 2582, "castle", "the-stormlands", 3, "Seat of House Caron",
    "The marcher seat of the Carons, lords of the nightingales."],
  ["Vulture's Roost", 1294, 2572, "ruin", "dorne", 3, "Ruin in the Red Mountains",
    "An abandoned mountain hold where outlaw 'vulture kings' once nested."],
  ["Wyl", 1361, 2586, "castle", "dorne", 3, "Seat of House Wyl",
    "A marcher seat in the Boneway, old in border blood."],
  ["Kingsgrave", 1169, 2643, "castle", "dorne", 3, "Seat of House Manwoody",
    "A mountain seat named for a king slain at its gates."],
  ["Blackmont", 992, 2687, "castle", "dorne", 3, "Seat of House Blackmont",
    "A western Dornish seat above the Torentine."],
  ["Skyreach", 1163, 2718, "castle", "dorne", 3, "Seat of House Fowler",
    "The Fowlers' eyrie in the Prince's Pass."],
  ["Yronwood", 1328, 2719, "castle", "dorne", 2, "Seat of House Yronwood",
    "Seat of the proudest house in Dorne after the Martells — 'The Bloodroyal', wardens of the Boneway."],
  ["Starfall", 964, 2757, "castle", "dorne", 2, "Seat of House Dayne",
    "The Daynes' seat on the Torentine, home of the sword Dawn and the memory of Ser Arthur, the Sword of the Morning."],
  ["Hellholt", 1199, 2852, "castle", "dorne", 3, "Seat of House Uller",
    "A grim seat on the Brimstone, half of whose lords are said to be mad."],
  ["Sandstone", 1072, 2872, "castle", "dorne", 3, "Seat of House Qorgyle",
    "A sand-scoured seat deep in the Dornish desert."],
  ["The Tor", 1535, 2755, "castle", "dorne", 3, "Seat of House Jordayne",
    "A seaside seat on the Sea of Dorne."],
  ["Ghost Hill", 1764, 2744, "castle", "dorne", 3, "Seat of House Toland",
    "A chalk-white hill seat above the Sea of Dorne."],
  ["Godsgrace", 1571, 2840, "castle", "dorne", 3, "Seat of House Allyrion",
    "A fertile seat at the joining of the Greenblood's branches."],
  ["Vaith", 1422, 2869, "castle", "dorne", 3, "Seat of House Vaith",
    "A river seat amid the red sands."],
  ["Lemonwood", 1723, 2899, "castle", "dorne", 3, "Seat of House Dalt",
    "A lemon-orcharded seat near the mouth of the Greenblood."],
  ["Salt Shore", 1535, 2922, "castle", "dorne", 3, "Seat of House Gargalen",
    "A southern coastal seat on the Summer Sea."],

  // ---------------- Essos: the Free Cities & the Rhoyne ----------------
  ["Braavos", 2201, 1413, "city", "free-cities", 1, "The Secret City",
    "Greatest of the Free Cities, hidden in a fog-bound lagoon behind its Titan, ruled by the Sealord and famed for its water dancers."],
  ["Pentos", 2215, 2070, "city", "free-cities", 1, "Free City of merchant princes",
    "A wealthy Free City of canals and colored domes, where magisters grow rich and keep their daggers hidden."],
  ["Norvos", 2602, 1830, "city", "free-cities", 2, "City of the bearded priests",
    "A hill city of bells and bearded priests above the Noyne."],
  ["Qohor", 2890, 1760, "city", "free-cities", 2, "City of sorcerers",
    "The Free City at the edge of its great forest, famed for dark arts and smiths who can rework Valyrian steel."],
  ["Myr", 2337, 2514, "city", "free-cities", 2, "City of crafts",
    "A Free City famed for lace, lenses, and green-eyed slavers."],
  ["Tyrosh", 2059, 2531, "city", "free-cities", 2, "City of dyes",
    "An island Free City of bright-dyed beards, pear brandy, and hired swords."],
  ["Lys", 2221, 2898, "city", "free-cities", 2, "City of pleasure",
    "An island Free City of perfumed gardens, famed for its pleasure houses and its poisons."],
  ["Selhorys", 2725, 2658, "town", "free-cities", 3, "River town of the Rhoyne",
    "A walled river town on the Rhoyne, tributary to Volantis."],
  ["Valysar", 2741, 2755, "town", "free-cities", 3, "River town of the Rhoyne",
    "A Volantene river town on the great Rhoyne."],
  ["Volon Therys", 2803, 2861, "town", "free-cities", 3, "River town of the Rhoyne",
    "A river town on the lower Rhoyne, under the sway of Volantis."],
  ["Sar Mell", 2802, 2834, "ruin", "free-cities", 3, "Ruin of the Rhoynar",
    "A Rhoynish town broken in the old wars with Valyria."],
  ["Ny Sar", 2616, 2168, "ruin", "free-cities", 3, "Ruin of the Rhoynar",
    "The drowned palace-city of Princess Nymeria's people, at the meeting of Rhoyne and Noyne."],
  ["Volantis", 2838, 2925, "city", "free-cities", 2, "Oldest of the Free Cities",
    "The first daughter of Valyria, sprawled across the mouth of the Rhoyne behind its Black Walls — a city of tiger cloaks and red priests, where slaves outnumber the free five to one."],

  // ---------------- Essos: the Dothraki sea & the east ----------------
  ["Vaes Dothrak", 4754, 1800, "city", "dothraki-sea", 1, "City of the horselords",
    "The Dothraki's only city — no walls, no buildings but stolen monuments, watched over by the Mother of Mountains."],
  ["Village of the Lhazareen", 4282, 2500, "town", "dothraki-sea", 2, "Village of the lamb men",
    "A mud-walled village of the peaceful Lhazareen, herders whom the Dothraki raid for slaves."],
  ["Bayasabhad", 5247, 2688, "city", "dothraki-sea", 3, "City of the Bone Mountains",
    "A far eastern city guarding a pass through the Bones."],
  ["Samyrian", 5199, 2246, "city", "dothraki-sea", 3, "City of the Bone Mountains",
    "An eastern pass-city above the Dothraki sea."],
  ["Qarth", 5283, 3186, "city", "dothraki-sea", 1, "The greatest city that ever was or will be",
    "The queen of cities on the Jade Gates, ringed by triple walls — so its merchants never tire of saying."],

  // ---------------- Essos: Slaver's Bay & old Valyria ----------------
  ["Meereen", 4113, 2612, "city", "slavers-bay", 1, "Great city of Slaver's Bay",
    "The largest of the slave cities, a city of colored brick beneath its Great Pyramid."],
  ["Yunkai", 4035, 2703, "city", "slavers-bay", 2, "The Yellow City",
    "A slaver city of yellow brick, breeder of bed slaves."],
  ["Astapor", 4010, 2940, "city", "slavers-bay", 2, "The Red City",
    "The southernmost of the slave cities, red brick and dust at the mouth of the Worm, where the Good Masters train and sell the Unsullied."],
  ["Old Ghis", 4033, 3257, "ruin", "slavers-bay", 3, "Ruin of the Ghiscari Empire",
    "The mother city of the old empire the dragons of Valyria burned five thousand years ago."],
  ["New Ghis", 4090, 3520, "city", "slavers-bay", 3, "Island city of the Ghiscari",
    "An island city where the old empire's descendants drill iron legions."],
  ["Tolos", 3613, 2828, "city", "slavers-bay", 3, "City of slingers",
    "A slaver city on the Gulf of Grief, famed for its slingers."],
  ["Elyria", 3524, 2860, "city", "slavers-bay", 3, "Island city",
    "An island city of the Gulf of Grief."],
  ["Mantarys", 3448, 2713, "city", "slavers-bay", 3, "City on the demon road",
    "An ill-omened city whose people are said to be born twisted, on the haunted road to Valyria."],
  ["Bhonash", 3804, 2622, "town", "slavers-bay", 3, "Waystation of the east",
    "A dusty town on the caravan roads north of Slaver's Bay."],
  ["Oros", 3416, 3183, "ruin", "slavers-bay", 3, "Dead city of Valyria",
    "A Valyrian city drowned and broken in the Doom."],
  ["Tyria", 3335, 3318, "ruin", "slavers-bay", 3, "Dead city of Valyria",
    "A sister city of old Valyria, lost in the Doom."],
  ["Valyria", 3321, 3423, "ruin", "slavers-bay", 2, "The Doom that came",
    "The shattered heart of the greatest civilization the world has known, where the sea still smokes and demons are said to walk."],
  // ---------------- added for the Dance of the Dragons ----------------
  ["Driftmark", 1732, 2056, "castle", "the-crownlands", 1, "Seat of House Velaryon",
    "The island of the sea horse, settled by Valyrians before the dragonlords came. From the new castle of High Tide, Corlys the Sea Snake commands a fleet greater than the crown's and wealth greater than the Rock's."],
  ["Duskendale", 1585, 1955, "town", "the-crownlands", 2, "Port town of House Darklyn",
    "An old harbor town on the north shore of Blackwater Bay, seat of House Darklyn, who were petty kings here before the dragons came."],
  ["Rook's Rest", 1663, 1924, "castle", "the-crownlands", 2, "Seat of House Staunton",
    "A modest castle on the bay's north coast between Duskendale and Crackclaw Point — two days from King's Landing by road, far less by wing."],
  ["The Stepstones", 2000, 2740, "landmark", "free-cities", 2, "Broken isles of pirates and toll-takers",
    "The drowned mountain chain between Dorne and the Disputed Lands. Whoever holds these rocks taxes the narrow sea's trade — pirates, the Triarchy of the Free Cities, or a rogue prince with a driftwood crown."],
];

/* Minor Westerosi houses: canonical field colors for the small map banners.
   colors: [field, second tincture] · div: how the shield is divided
   Where a matching drawn shield exists (Wikimedia Commons), img overrides. */
const MINOR_ARMS = {
  "last-hearth":     { house: "House Umber", colors: ["#8a3b2a", "#c9c9c9"], div: "plain", img: "minor/last-hearth.svg" },
  "karhold":         { house: "House Karstark", colors: ["#1b1b1b", "#e8e8e8"], div: "plain" },
  "the-dreadfort":   { house: "House Bolton", colors: ["#d8a0a0", "#8f1d2c"], div: "plain", img: "bolton.svg" },
  "hornwood":        { house: "House Hornwood", colors: ["#c9702e", "#5a3a1a"], div: "fess" },
  "torrhens-square": { house: "House Tallhart", colors: ["#7a5c3a", "#3f6b3a"], div: "fess" },
  "castle-cerwyn":   { house: "House Cerwyn", colors: ["#c9c9c9", "#1b1b1b"], div: "plain" },
  "barrowton":       { house: "House Dustin", colors: ["#1b1f24", "#8a6d3b"], div: "fess", img: "minor/barrowton.svg" },
  "widows-watch":    { house: "House Flint", colors: ["#3a5f8a", "#c9c9c9"], div: "fess" },
  "white-harbor":    { house: "House Manderly", colors: ["#3d6b6b", "#e8e8e8"], div: "fess" },
  "oldcastle":       { house: "House Locke", colors: ["#5a4a7a", "#c9a15a"], div: "pale" },
  "flints-finger":   { house: "House Flint of the Finger", colors: ["#3a5f8a", "#c9c9c9"], div: "plain" },
  "seagard":         { house: "House Mallister", colors: ["#2d3a6b", "#d8d8d8"], div: "plain" },
  "raventree-hall":  { house: "House Blackwood", colors: ["#1b1b1b", "#e8e8e8"], div: "plain", img: "minor/raventree-hall.svg" },
  "stone-hedge":     { house: "House Bracken", colors: ["#c9a15a", "#8f1d2c"], div: "plain", img: "minor/stone-hedge.svg" },
  "acorn-hall":      { house: "House Smallwood", colors: ["#e0c060", "#5a3a1a"], div: "fess" },
  "harrenhal":       { house: "House Strong", colors: ["#8a8f98", "#1b1b1b"], div: "plain", img: "strong.svg" },
  "pinkmaiden":      { house: "House Piper", colors: ["#3a5f8a", "#d8a0b0"], div: "fess", img: "minor/pinkmaiden.svg" },
  "runestone":       { house: "House Royce", colors: ["#8a6d3b", "#2b2015"], div: "plain" },
  "gulltown":        { house: "House Grafton", colors: ["#7a7a7a", "#c93a2e"], div: "fess" },
  "wickendon":       { house: "House Waxley", colors: ["#5a7a9c", "#e8e8d0"], div: "fess" },
  "faircastle":      { house: "House Farman", colors: ["#3a5f8a", "#e8e8e8"], div: "pale" },
  "feastfires":      { house: "House Prester", colors: ["#e8e8e8", "#8f1d2c"], div: "fess" },
  "the-crag":        { house: "House Westerling", colors: ["#d8c9a0", "#e8e8e8"], div: "fess" },
  "ashemark":        { house: "House Marbrand", colors: ["#6b6b6b", "#c9702e"], div: "fess", img: "minor/ashemark.svg" },
  "golden-tooth":    { house: "House Lefford", colors: ["#e0c060", "#3a5f8a"], div: "fess" },
  "hornvale":        { house: "House Brax", colors: ["#c9c9c9", "#5a3a7a"], div: "plain" },
  "cleganes-keep":   { house: "House Clegane", colors: ["#e0c060", "#1b1b1b"], div: "plain", img: "clegane.svg" },
  "deep-den":        { house: "House Lydden", colors: ["#4a6741", "#e8e8e8"], div: "fess" },
  "silverhill":      { house: "House Serrett", colors: ["#e8e0c0", "#3f6b8a"], div: "fess" },
  "cornfield":       { house: "House Swyft", colors: ["#e0c060", "#2d4a8a"], div: "plain", img: "minor/cornfield.svg" },
  "crakehall":       { house: "House Crakehall", colors: ["#7a5c3a", "#e8e8e8"], div: "fess", img: "minor/crakehall.svg" },
  "maidenpool":      { house: "House Mooton", colors: ["#e8e8e8", "#c93a2e"], div: "fess", img: "minor/maidenpool.svg" },
  "antlers":         { house: "House Buckwell", colors: ["#4a6741", "#c9a15a"], div: "plain" },
  "rosby":           { house: "House Rosby", colors: ["#e8e8e8", "#8f1d2c"], div: "pale", img: "minor/rosby.svg" },
  "claw-isle":       { house: "House Celtigar", colors: ["#e8e8e8", "#c93a2e"], div: "plain" },
  "old-oak":         { house: "House Oakheart", colors: ["#e0c060", "#3f6b3a"], div: "fess" },
  "red-lake":        { house: "House Crane", colors: ["#7fa8c9", "#e8e8e8"], div: "fess" },
  "goldengrove":     { house: "House Rowan", colors: ["#c9c9c9", "#c9a15a"], div: "plain", img: "minor/goldengrove.svg" },
  "bitterbridge":    { house: "House Caswell", colors: ["#e8e8e8", "#c9a15a"], div: "fess" },
  "grassy-vale":     { house: "House Meadows", colors: ["#6b8f4a", "#e8e8e8"], div: "plain" },
  "long-table":      { house: "House Merryweather", colors: ["#e8e0c0", "#c9702e"], div: "fess" },
  "cider-hall":      { house: "House Fossoway", colors: ["#e0c060", "#c93a2e"], div: "plain" },
  "ashford":         { house: "House Ashford", colors: ["#c9702e", "#e8e8e8"], div: "fess" },
  "brightwater-keep":{ house: "House Florent", colors: ["#e8e8e8", "#c9702e"], div: "plain" },
  "bandallon":       { house: "House Blackbar", colors: ["#c9c9c9", "#1b1b1b"], div: "pale", img: "minor/bandallon.svg" },
  "honeyholt":       { house: "House Beesbury", colors: ["#1b1b1b", "#e0c060"], div: "fess" },
  "horn-hill":       { house: "House Tarly", colors: ["#4a6741", "#c93a2e"], div: "plain", img: "tarly.svg" },
  "oldtown":         { house: "House Hightower", colors: ["#e8e8e8", "#c93a2e"], div: "plain", img: "hightower.png" },
  "blackcrown":      { house: "House Bulwer", colors: ["#8f1d2c", "#e8e8e8"], div: "plain" },
  "uplands":         { house: "House Mullendore", colors: ["#e8e8e8", "#1b1b1b"], div: "fess" },
  "three-towers":    { house: "House Costayne", colors: ["#1b1f24", "#c9c9c9"], div: "pale" },
  "sun-house":       { house: "House Cuy", colors: ["#3a5f8a", "#e0c060"], div: "fess" },
  "griffins-roost":  { house: "House Connington", colors: ["#c93a2e", "#e8e8e8"], div: "pale" },
  "rain-house":      { house: "House Wylde", colors: ["#e0c060", "#3d6b6b"], div: "fess", img: "minor/rain-house.svg" },
  "stonehelm":       { house: "House Swann", colors: ["#1b1b1b", "#e8e8e8"], div: "pale", img: "minor/stonehelm.svg" },
  "mistwood":        { house: "House Mertyns", colors: ["#6b6b6b", "#e8e8e8"], div: "fess" },
  "blackhaven":      { house: "House Dondarrion", colors: ["#1b1b24", "#7a5cc9"], div: "plain" },
  "haystack-hall":   { house: "House Errol", colors: ["#8a5c3a", "#e0c060"], div: "fess" },
  "felwood":         { house: "House Fell", colors: ["#4a6741", "#e8e8e8"], div: "fess" },
  "bronzegate":      { house: "House Buckler", colors: ["#3a5f8a", "#c9a15a"], div: "plain" },
  "evenfall-hall":   { house: "House Tarth", colors: ["#7fa8c9", "#d8a0b0"], div: "quarter" },
  "nightsong":       { house: "House Caron", colors: ["#e0c060", "#1b1b1b"], div: "fess", img: "minor/nightsong.svg" },
  "wyl":             { house: "House Wyl", colors: ["#e0c060", "#1b1f24"], div: "plain" },
  "kingsgrave":      { house: "House Manwoody", colors: ["#1b1b1b", "#e8e8e8"], div: "plain", img: "minor/kingsgrave.svg" },
  "blackmont":       { house: "House Blackmont", colors: ["#e0c060", "#1b1b1b"], div: "fess", img: "minor/blackmont.svg" },
  "skyreach":        { house: "House Fowler", colors: ["#2d4a8a", "#c9c9c9"], div: "plain" },
  "yronwood":        { house: "House Yronwood", colors: ["#d8c9a0", "#1b1f24"], div: "plain" },
  "starfall":        { house: "House Dayne", colors: ["#4a3a7a", "#e8e8e8"], div: "plain" },
  "hellholt":        { house: "House Uller", colors: ["#c93a2e", "#e0c060"], div: "fess" },
  "sandstone":       { house: "House Qorgyle", colors: ["#8f1d2c", "#1b1b1b"], div: "fess", img: "minor/sandstone.svg" },
  "the-tor":         { house: "House Jordayne", colors: ["#e0c060", "#5a4c38"], div: "fess", img: "minor/the-tor.svg" },
  "ghost-hill":      { house: "House Toland", colors: ["#e0c060", "#3f6b3a"], div: "plain" },
  "godsgrace":       { house: "House Allyrion", colors: ["#8f1d2c", "#c9a15a"], div: "quarter" },
  "vaith":           { house: "House Vaith", colors: ["#d8a0b0", "#1b1f24"], div: "fess" },
  "lemonwood":       { house: "House Dalt", colors: ["#e0c060", "#5a3a7a"], div: "plain", img: "minor/lemonwood.svg" },
  "salt-shore":      { house: "House Gargalen", colors: ["#e0c060", "#c93a2e"], div: "fess" },
};

/* Seats whose canon fan-heraldry shield was sourced from Wikimedia Commons
   (assets/sigils/minor/<location-id>.png). All others use the drawn arms. */
const CANON_MINOR_SHIELDS = new Set([
  "karhold", "castle-cerwyn", "torrhens-square", "hornwood", "white-harbor",
  "oldcastle", "widows-watch", "flints-finger", "seagard", "runestone",
  "gulltown", "wickendon", "faircastle", "feastfires", "the-crag",
  "golden-tooth", "deep-den", "claw-isle", "old-oak", "red-lake", "grassy-vale",
  "long-table", "cider-hall", "ashford", "brightwater-keep", "honeyholt",
  "blackcrown", "uplands", "three-towers", "sun-house", "bitterbridge",
  "griffins-roost", "evenfall-hall", "blackhaven", "wyl", "yronwood", "starfall",
]);

/* which locations are the seats shown when House Banners are toggled on */
const HOUSE_SEATS = {
  "kings-landing": "targaryen",
  "dragonstone": "targaryen",
  "driftmark": "velaryon",
  "oldtown": "hightower",
  "harrenhal": "strong",
  "winterfell": "stark",
  "casterly-rock": "lannister",
  "storms-end": "baratheon",
  "riverrun": "tully",
  "the-eyrie": "arryn",
  "pyke": "greyjoy",
  "the-twins": "frey",
  "highgarden": "tyrell",
  "sunspear": "martell",
};

/* Season 1 chronicle entries for major places (shown under "This season" in the info panel) */
const SEASON_LORE = {
  "winterfell": "Here the season begins: a deserter's execution, five direwolf pups, a king's visit — and a boy pushed from a tower window for what he saw.",
  "castle-black": "Jon Snow takes the black among thieves and poachers, finds a brother in Samwell Tarly — and a dead man's eyes open blue in the night.",
  "crasters-keep": "The rangings that pass Craster's hall this season bring back only rumors — of villages empty, and of the dead that walk.",
  "the-twins": "Robb's army can only cross the Green Fork here. Catelyn bargains with Lord Walder for the bridge — a bargain paid in promises of marriage.",
  "riverrun": "Catelyn Stark's birthplace. By season's end the northern host camps beneath its walls — and lifts Robb Stark up as King in the North.",
  "harrenhal": "Spoken of at court with a shudder — the cursed prize Lord Whent can barely afford to keep. Its melted towers loom over the God's Eye.",
  "the-eyrie": "Lysa Arryn nurses her son and her grievances here. Tyrion beats the sky cells with his tongue: a trial by combat, and Bronn's sword.",
  "casterly-rock": "Tywin Lannister rules from here in all but name — and when his son is taken hostage, the West empties its barracks.",
  "golden-tooth": "The Lannister host under Ser Jaime pours past the Golden Tooth this season to put the Riverlands to the sword.",
  "kings-landing": "Ned Stark serves as Hand here and pulls one thread too many. It ends on the steps of the Great Sept, with Ice in a stranger's hands.",
  "dragonstone": "The Targaryens' last seat in Westeros, held now by Stannis Baratheon — a name Ned Stark writes in a letter he never gets to send.",
  "storms-end": "Robert's birthright, spoken of at court — while his brother Renly slips out of the capital with a different crown in mind.",
  "highgarden": "Unvisited this season, but its favorite son Ser Loras — the Knight of Flowers — unhorses the Mountain at the Hand's tourney.",
  "oldtown": "Every grey-robed maester at every castle this season — Luwin, Aemon, Pycelle — earned his chain in this city.",
  "horn-hill": "Sam's father gave him a choice beneath these hills: take the black, or have a hunting accident. The Watch got its most loyal steward.",
  "sunspear": "Dorne keeps its distance this season — but the name of Elia Martell, wife of the last dragon prince, is not spoken lightly at court.",
  "blackhaven": "Its lord's banner rides out this season: Ned sends Beric Dondarrion to bring the Mountain to justice — an errand that outlives the man who gave it.",
  "moat-cailin": "Robb Stark's host masses here on its march south, where a handful of men can hold back an army.",
  "white-harbor": "Never shown this season, but its lords answer when Robb Stark calls the banners of the North.",
  "pyke": "Unvisited this season — but Theon Greyjoy has not seen it since the Starks took him as ward and hostage nine years ago.",
  "braavos": "Never visited — but Syrio Forel, First Sword of Braavos, teaches Arya what a girl says to the god of death: not today.",
  "pentos": "Under Illyrio Mopatis's roof, Viserys sells his sister to a khal for the promise of an army. Daenerys's story begins on this shore.",
  "vaes-dothrak": "Daenerys eats the stallion's heart here and the crones proclaim her son. Viserys demands his crown at swordpoint — and gets one of molten gold.",
  "village-of-the-lhazareen": "Drogo's khalasar sacks the lamb men for the ships Viserys was promised. Daenerys claims the godswife Mirri Maz Duur — a healer with her own accounting.",
  "qarth": "Beyond this season's story — but east of the red waste it waits, the greatest city that ever was or will be.",
  "summerhall": "The ruin where the Targaryen dream burned. Old Maester Aemon, who lost his family there, keeps his vigil at the Wall this season.",
  "stoney-sept": "Robert liked to retell it this season at Winterfell: the town whose ringing bells once hid a fugitive stag.",
  "lannisport": "The Lannister fleet rides at anchor here while the lions do their season's fighting on land.",
  "gulltown": "The Vale's port stays quiet — Lysa Arryn keeps her knights home no matter who writes to her.",
  "meereen": "Far beyond this season's horizon, the slave cities go on as they have for a thousand years — for now.",
  "valyria": "The Doom is a story this season — the story Viserys tells to explain the eggs, and the steel, and the name Targaryen.",
};

const WORLD = {
  regions: [
    { id: "the-north", name: "The North",
      description: "The largest of the Seven Kingdoms and the coldest, ruled from Winterfell by House Stark for eight thousand years. Its people are hard, its gods are old, and its memory is long.",
      season: "Far from the Dance — but Cregan Stark remembers oaths: Jacaerys flies to Winterfell, and the Pact of Ice and Fire is sworn in the snow." },
    { id: "the-vale", name: "The Vale",
      description: "A green land walled in by the Mountains of the Moon, ruled by House Arryn from the Eyrie. Its knights are famed, and its passes are held by hill tribes who bow to no lord.",
      season: "Jeyne Arryn, the Maiden of the Vale, holds the Eyrie for Rhaenyra — and at Runestone a lady dies of a fall the Vale never quite believes." },
    { id: "the-riverlands", name: "The Riverlands",
      description: "Fertile country threaded by the forks of the Trident, seat of House Tully at Riverrun. Every war in Westeros seems to be fought across its fords and crossings.",
      season: "The Dance's cockpit: Daemon takes Harrenhal without a blow, Bracken and Blackwood bleed at the Burning Mill, and the river lords go black." },
    { id: "iron-islands", name: "The Iron Islands",
      description: "Bleak isles in the Sunset Sea whose people reave and pay the iron price, ruled by House Greyjoy from Pyke since their rebellion was broken.",
      season: "Dalton Greyjoy, the Red Kraken, reads a realm at war as an invitation — his longships wait for the first undefended coast." },
    { id: "the-westerlands", name: "The Westerlands",
      description: "Gold-veined hills ruled by House Lannister from Casterly Rock — the richest house in the Seven Kingdoms, and the one to whom the Crown owes the most.",
      season: "Jason Lannister raises the west for King Aegon while his twin Tyland counts the crown's gold — half of it quietly missing." },
    { id: "the-crownlands", name: "The Crownlands",
      description: "The king's own lands around Blackwater Bay, ruled directly from the Iron Throne. Dragonstone, the old Targaryen seat, guards the bay's mouth.",
      season: "The heart of the Dance: a king dies whispering of a dream, a son is crowned in the Dragonpit, a daughter on Dragonstone — and Rook's Rest burns between them." },
    { id: "the-reach", name: "The Reach",
      description: "The garden of Westeros — the most fertile and populous of the kingdoms, ruled by House Tyrell from Highgarden. Oldtown, seat of the Citadel, is its ancient city.",
      season: "The Hightowers light the way to war: Oldtown anoints the green king, and Ser Criston's host marches while Highgarden's babe of a lord sits it out." },
    { id: "the-stormlands", name: "The Stormlands",
      description: "Rain-lashed coasts and oak forests between King's Landing and Dorne, the ancestral lands of House Baratheon at Storm's End.",
      season: "Borros Baratheon weighs two crowns' letters at Storm's End — and above Shipbreaker Bay, Vhagar hunts a boy's dragon through the storm." },
    { id: "dorne", name: "Dorne",
      description: "The sun-scorched south beyond the Red Mountains, ruled by House Martell from Sunspear. Dorne bows to the Iron Throne but was never conquered by it.",
      season: "Unbowed and uninvolved: Dorne is no part of the Seven Kingdoms, and watches the dragons kill one another with professional interest." },
    { id: "free-cities", name: "The Free Cities",
      description: "Nine merchant cities across the Narrow Sea, daughters of old Valyria — Braavos, Pentos, Myr and their sisters — where exiles scheme and sellswords wait.",
      season: "Pentos hosts Daemon and Laena as honored guests for ten years; in the Stepstones, the Triarchy's toll-takers test the narrow sea again." },
    { id: "dothraki-sea", name: "The Dothraki Sea & the East",
      description: "An ocean of grass in the heart of Essos, crossed only by the khalasars of the horselords — and beyond it, the red waste and the distant splendor of Qarth.",
      season: "Beyond the Dance entirely — the grass sea keeps its own counsel this century." },
    { id: "slavers-bay", name: "Slaver's Bay & Old Valyria",
      description: "The slave cities of the old Ghiscari coast — Meereen, Yunkai, and their kin — and south of them the smoking ruin of Valyria itself.",
      season: "The old cities trade on as ever — though every dragon in this war hatched from eggs laid under Valyria's shadow." },
  ],

  houses: [
    { id: "targaryen", name: "House Targaryen", seat: "kings-landing", region: "the-crownlands",
      words: "Fire and Blood", sigil: "Three-Headed Dragon", colors: ["#e05c5c", "#1a1a1a"],
      description: "The dragonlords of old Valyria, silver-haired and violet-eyed, who alone survived the Doom and conquered six of the Seven Kingdoms astride dragons. A three-headed red dragon on black, they have ruled from the Iron Throne for over a century of peace under the Old King and his heirs — a peace that dies with Viserys the First, when green and black both claim the dragon's crown." },
    { id: "velaryon", name: "House Velaryon", seat: "driftmark", region: "the-crownlands",
      words: "The Old, the True, the Brave", sigil: "Silver Seahorse", colors: ["#9fd8dc", "#123644"],
      description: "An old Valyrian house that came to Westeros before the dragonlords themselves, seated at High Tide on the island of Driftmark. A silver seahorse on sea green, they are the realm's masters of ship and salt — and under Corlys the Sea Snake, the richest house in Westeros, richer even than the lions of the Rock. Their blood is joined to the dragon's by marriage twice over." },
    { id: "hightower", name: "House Hightower", seat: "oldtown", region: "the-reach",
      words: "We Light the Way", sigil: "The Hightower", colors: ["#e8e4d4", "#6e7a84"],
      description: "Lords of Oldtown since before memory, keepers of the great lighthouse tower that gives them their name and their words. A white stone tower crowned with fire on smoke grey, they rule the oldest and richest city in Westeros, patrons of the Citadel and the Faith both — and through Queen Alicent and Ser Otto, the green half of the realm's great quarrel." },
    { id: "stark", name: "House Stark", seat: "winterfell", region: "the-north",
      words: "Winter Is Coming", sigil: "Direwolf", colors: ["#c9c9c9", "#20242b"],
      description: "Kings of Winter turned Wardens of the North, the Starks have ruled from Winterfell for eight thousand years — since the Age of Heroes and Bran the Builder. Grey direwolves on white ice, they keep the old gods and the First Men's ways, ruling the largest and coldest of the Seven Kingdoms with a hard, plain northern honor." },
    { id: "arryn", name: "House Arryn", seat: "the-eyrie", region: "the-vale",
      words: "As High as Honor", sigil: "Moon-and-Falcon", colors: ["#dfe8f0", "#5a7a9c"],
      description: "The purest blood of the Andal kings, Wardens of the East, enthroned in the Eyrie high in the Mountains of the Moon above the rich and sheltered Vale of Arryn. A white moon-and-falcon on sky blue, their mountain seat is reckoned impregnable — and their lady this generation, Jeyne the Maiden of the Vale, holds it against every cousin who thinks a woman cannot." },
    { id: "lannister", name: "House Lannister", seat: "casterly-rock", region: "the-westerlands",
      words: "Hear Me Roar", sigil: "Lion", colors: ["#e8c368", "#8f1d2c"],
      description: "The richest house of the sunset kingdoms until the Sea Snake sailed, lords of Casterly Rock and the gold beneath it. A golden lion on crimson, descended from Lann the Clever, they hold the Westerlands and command wealth enough to buy armies — this generation led by twins: Jason, who raises the banners, and Tyland, who counts the crown's coin." },
    { id: "tully", name: "House Tully", seat: "riverrun", region: "the-riverlands",
      words: "Family, Duty, Honor", sigil: "Leaping Trout", colors: ["#c9d4e0", "#3a5f8a"],
      description: "Lords of Riverrun and Lords Paramount of the Trident, raised to rule the fertile, much-fought-over Riverlands after Aegon's Conquest. A silver trout leaping on a field of red and blue — though old Lord Grover's grip has gone soft, and it is his quarrelsome bannermen, Bracken and Blackwood first among them, who will decide which dragon the rivers follow." },
    { id: "baratheon", name: "House Baratheon", seat: "storms-end", region: "the-stormlands",
      words: "Ours Is the Fury", sigil: "Crowned Stag", colors: ["#caa23a", "#1b1b1b"],
      description: "The youngest of the great houses, sprung from Orys Baratheon, the Conqueror's rumored bastard brother, seated at storm-battered Storm's End on Shipbreaker Bay. A crowned black stag on gold — strong, proud, and famously stubborn, and courted by both crowns the moment the Old King's peace breaks." },
    { id: "greyjoy", name: "House Greyjoy", seat: "pyke", region: "iron-islands",
      words: "We Do Not Sow", sigil: "Golden Kraken", colors: ["#c9a15a", "#1b1f24"],
      description: "Ironborn lords of Pyke and the bleak Iron Islands, who follow the Drowned God and the Old Way of reaving. A golden kraken on black — and in Dalton Greyjoy, the Red Kraken, a lord who reads a realm at war as an open invitation to take the iron price along every undefended coast." },
    { id: "tyrell", name: "House Tyrell", seat: "highgarden", region: "the-reach",
      words: "Growing Strong", sigil: "Golden Rose", colors: ["#e8c368", "#3f6b3a"],
      description: "Wardens of the South and Lords of Highgarden, stewards risen to rule the vast, fertile Reach. A golden rose on green, commanding the deepest granaries in the realm — but with a babe for a lord this generation, Highgarden sits the Dance out while its bannermen choose dragons for themselves." },
    { id: "martell", name: "House Martell", seat: "sunspear", region: "dorne",
      words: "Unbowed, Unbent, Unbroken", sigil: "Spear-Pierced Sun", colors: ["#e8c368", "#b0563a"],
      description: "Princes of Dorne, who alone of all Westeros never bowed to the dragons. A red sun pierced by a golden spear, ruling the hot southern deserts from Sunspear by Rhoynish law and custom — and wise enough, when the dragons dance, to watch from behind the Red Mountains." },
    { id: "frey", name: "House Frey", seat: "the-twins", region: "the-riverlands",
      words: "We Stand Together", sigil: "The Twin Towers", colors: ["#b8c4d0", "#3d4a5c"],
      description: "Upjumped and numerous, the Freys hold the only bridge across the Green Fork, growing rich on the tolls of the Twins. Two blue towers joined by a bridge on grey, bannermen to the Tullys — and in this war, bought early: the black prince flies to their bridge himself to pay the toll in promises." },
  ],

  journeys: [
    { id: "daemon", character: "Daemon Targaryen", initial: "D",
      color: "#8a2f3d", summary: "King's Landing → Dragonstone · the rogue prince's long road",
      stops: [
        { location: "kings-landing", episode: 1, epTitle: "The Heirs of the Dragon",
          note: "Commander of the City Watch, heir presumptive — until a toast to 'the heir for a day' costs him the succession and the city." },
        { location: "dragonstone", episode: 2, epTitle: "The Rogue Prince",
          note: "Squats on the family seat with a stolen dragon's egg, daring his brother to come and take it. Rhaenyra does instead." },
        { location: "the-stepstones", episode: 3, epTitle: "Second of His Name",
          note: "Three bloody years against the Crabfeeder end when Daemon feigns surrender and cuts the man in half beneath Caraxes' wings." },
        { location: "kings-landing", episode: 4, epTitle: "King of the Narrow Sea",
          note: "Returns wearing a driftwood crown, kneels to give it to his brother — and takes his niece into the streets of Flea Bottom by night." },
        { location: "runestone", episode: 5, epTitle: "We Light the Way",
          note: "Pays a last visit to his 'bronze bitch' of a wife among the Vale's stones. The Vale calls it a riding accident." },
        { location: "pentos", episode: 6, epTitle: "The Princess and the Queen",
          note: "Ten years an exile and a guest of the magisters, wed to Laena Velaryon, father to twins — until grief sends him home." },
        { location: "driftmark", episode: 7, epTitle: "Driftmark",
          note: "Buries Laena in the sea, and weds Rhaenyra on Dragonstone's shore by Valyrian rite." },
        { location: "dragonstone", episode: 10, epTitle: "The Black Queen",
          note: "Sets a crown on Rhaenyra's brow and starts counting swords, castles and dragons for the war he always wanted." },
      ] },
    { id: "rhaenyra", character: "Rhaenyra Targaryen", initial: "R",
      color: "#26221e", summary: "King's Landing → Dragonstone · from cupbearer to queen",
      stops: [
        { location: "kings-landing", episode: 1, epTitle: "The Heirs of the Dragon",
          note: "Her mother dies for a son who lives a day — and her father names her heir to the Iron Throne, first of her name." },
        { location: "driftmark", episode: 7, epTitle: "Driftmark",
          note: "At Laena's funeral she claims her own life at last: a Valyrian wedding to Daemon, and a mummer's corpse for a husband." },
        { location: "kings-landing", episode: 8, epTitle: "The Lord of the Tides",
          note: "Returns to a rotting court to defend her son's claim to Driftmark — and hears her dying father hold the throne for her one last time." },
        { location: "dragonstone", episode: 10, epTitle: "The Black Queen",
          note: "Crowned with her father's crown on the shore of Dragonstone. She holds the realm back from war — until word comes from Storm's End." },
      ] },
    { id: "lucerys", character: "Lucerys Velaryon", initial: "L",
      color: "#4a6d8c", summary: "Dragonstone → Storm's End · the flight that starts the war",
      stops: [
        { location: "kings-landing", episode: 8, epTitle: "The Lord of the Tides",
          note: "A boy who never wanted Driftmark stands before the throne while grown men argue over his blood." },
        { location: "dragonstone", episode: 10, epTitle: "The Black Queen",
          note: "Made his mother's envoy: fly to Storm's End, deliver a letter, come home. 'You will be a messenger, not a warrior.'" },
        { location: "storms-end", episode: 10, epTitle: "The Black Queen",
          note: "Finds Vhagar in the yard and Aemond waiting. Over Shipbreaker Bay, in the storm, Arrax and Lucerys fall — and the Dance begins in blood." },
      ] },
  ],
};

/* ---------------- Season One, episode by episode ----------------
   throne: who sits it, which house, who serves as Hand
   people: j = journey id (traceable on the map) · loc = where they are
   power:  house strength 1–10 as of this episode
   deaths: named characters who die IN this episode */

const EPISODES = [
  { n: 1, title: "The Heirs of the Dragon",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "The Old King's council at Harrenhal chose Viserys over Princess Rhaenys — a woman would sit no throne. The realm remembers.",
      "At the heir's tourney, Daemon fights like the war the realm hasn't had in a lifetime — while Queen Aemma dies in the birthing bed, and baby Baelon a day after her.",
      "Daemon toasts 'the heir for a day' in a pleasure house; Viserys strips him of the succession and sends him from court.",
      "Viserys tells Rhaenyra the secret every king carries — Aegon's dream, the Song of Ice and Fire — and names her heir.",
      "The lords of the realm, Corlys and Rhaenys among them, kneel and swear to Rhaenyra Targaryen, first of her name.",
    ],
    people: [
      { name: "Viserys I Targaryen", loc: "kings-landing", note: "A good man asked to be a king; the difference will kill him slowly." },
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Cupbearer, dragonrider, and — by episode's end — heir to the Iron Throne." },
      { name: "Daemon Targaryen", j: "daemon", note: "Gold cloaks at his back, a crown in his eye, and a toast he will never live down." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Sent by her father to comfort a grieving king in his chambers. She is fifteen." },
      { name: "Otto Hightower", loc: "kings-landing", note: "The Hand who moves his daughter like a cyvasse piece." },
      { name: "Corlys Velaryon", loc: "kings-landing", note: "The Sea Snake — richest man in the realm, and married to the queen who should have been." },
      { name: "Rhaenys Targaryen", loc: "kings-landing", note: "'The Queen Who Never Was.' She has made her peace with it. Mostly." },
    ],
    power: { targaryen: 10, velaryon: 8, hightower: 7, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Queen Aemma Arryn", note: "Cut open on the maesters' counsel to save a son. Neither survives the choice." },
      { name: "Prince Baelon Targaryen", note: "The heir for a day — Viserys's longed-for son, dead within hours of his mother." },
    ] },
  { n: 2, title: "The Rogue Prince",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "Daemon takes Dragonstone with his gold cloaks and steals a dragon's egg — the one meant for Baelon's cradle.",
      "Otto leads a party to the island; steel is bared on the bridge until Rhaenyra lands Syrax and dares her uncle to kill her.",
      "Corlys and Rhaenys offer Viserys their daughter Laena, aged twelve; the king chooses Alicent Hightower instead, and the Sea Snake leaves court cold.",
      "The Crabfeeder, backed by the Triarchy, nails Westerosi sailors to posts in the Stepstones — and the crown does nothing.",
      "Spurned by the throne, Corlys brings his fleet to Daemon: a war for the Stepstones, fought without the king's leave.",
    ],
    people: [
      { name: "Daemon Targaryen", j: "daemon", note: "Steals an island, an egg, and every scene." },
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Ends a standoff by putting a dragon between the swords." },
      { name: "Viserys I Targaryen", loc: "kings-landing", note: "Cuts himself on the throne; the throne never forgives." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "A girl who read to a king becomes his betrothed." },
      { name: "Corlys Velaryon", loc: "driftmark", note: "Twice insulted — his daughter refused, his sea ignored." },
      { name: "Otto Hightower", loc: "kings-landing", note: "Wins the queen's chair for his blood and calls it duty." },
    ],
    power: { targaryen: 9, velaryon: 8, hightower: 8, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [] },
  { n: 3, title: "Second of His Name",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "Three years on: Aegon, Alicent's son, has his second nameday hunt in the kingswood — and half the court hints he should be heir.",
      "Rhaenyra rides out angry, kills a boar in the dark with Ser Criston, and watches a white hart — the king's omen — walk away unkinged.",
      "In the Stepstones the war goes badly: Craghas Crabfeeder bleeds the Velaryon host from his caves while the Triarchy holds the tides.",
      "Viserys finally sends aid; the letter's arrival shames Daemon into fury — he beats the messenger with his helm.",
      "Daemon rows to the Crabfeeder's line under a peace banner, feigns surrender, and butchers a path until Craghas is cut in half beneath Caraxes.",
    ],
    people: [
      { name: "Daemon Targaryen", j: "daemon", note: "Wins a three-year war with one unforgivable, unbeatable lie." },
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Blood to the elbow at the hunt — and still not son enough for the court." },
      { name: "Viserys I Targaryen", loc: "kings-landing", note: "Drunk at his son's hunt, haunted by his daughter's claim." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "A queen at seventeen with a son the realm wants crowned." },
      { name: "Corlys Velaryon", loc: "the-stepstones", note: "Pays in Velaryon blood for a war the crown disowned." },
      { name: "Criston Cole", loc: "kings-landing", note: "The Dornish marches' finest sword, sworn to the princess's side." },
    ],
    power: { targaryen: 9, velaryon: 7, hightower: 8, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Craghas Drahar, the Crabfeeder", note: "The Myrish prince-admiral who fed the narrow sea's sailors to the crabs — halved by Dark Sister on his own beach." },
    ] },
  { n: 4, title: "King of the Narrow Sea",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "Crowned 'King of the Narrow Sea' by his victorious army, Daemon sails home — and lays the driftwood crown at his brother's feet.",
      "Rhaenyra tires of suitors counting her castles; Daemon shows her the city instead — Flea Bottom, a mummer's farce about her succession, a pleasure house.",
      "What starts in the pleasure house Daemon cannot finish; what Rhaenyra starts that night with Ser Criston, she does.",
      "Otto brings the king a whisperer's tale of his daughter and his brother; Viserys will not hear it — and sees at last whose ambition the Hand serves.",
      "Otto Hightower is stripped of the Hand's badge; Rhaenyra swears her innocence on her mother's memory — and drinks the moon tea the Grand Maester brings anyway.",
    ],
    people: [
      { name: "Daemon Targaryen", j: "daemon", note: "Gives back a crown to keep a grievance." },
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "One night in the city costs a Hand his badge and a knight his vows." },
      { name: "Viserys I Targaryen", loc: "kings-landing", note: "Finally spends his anger — on the wrong schemer." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Summons Rhaenyra by candlelight and believes her. Almost." },
      { name: "Criston Cole", loc: "kings-landing", note: "A white cloak left on the floor of a locked room." },
      { name: "Otto Hightower", loc: "oldtown", note: "Sent home to Oldtown with his ambitions folded in his baggage." },
    ],
    power: { targaryen: 9, velaryon: 7, hightower: 6, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [] },
  { n: 5, title: "We Light the Way",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Lord Lyonel Strong" },
    events: [
      "Daemon calls on his wife at Runestone. Lady Rhea Royce falls from her horse; the stone that ends her is in her husband's hand.",
      "Viserys sails to Driftmark to mend the realm's two dragon houses: Rhaenyra will wed Laenor Velaryon, and their sons will sit the throne.",
      "Rhaenyra and Laenor strike a private bargain — a marriage of duty, with room for what each of them actually wants.",
      "At the betrothal feast Ser Criston, refused as a paramour and half mad with broken vows, beats Laenor's lover Ser Joffrey Lonmouth to death on the floor.",
      "Alicent arrives late — in Hightower green, the color of Oldtown's beacon when it calls its banners to war. Everyone understands.",
    ],
    people: [
      { name: "Daemon Targaryen", j: "daemon", note: "Widowed by his own hand, and refused a Velaryon bride for his trouble." },
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Weds the realm's most eligible man on the realm's saddest wedding day." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Stops being the king's wife and becomes her father's daughter — in green." },
      { name: "Laenor Velaryon", loc: "driftmark", note: "A dragonrider of the Stepstones, wed to a princess, in love with a knight." },
      { name: "Criston Cole", loc: "kings-landing", note: "Confesses to the queen and finds a protector where he sought a headsman." },
      { name: "Viserys I Targaryen", loc: "kings-landing", note: "Collapses at the feast; the ruling is done, the rotting is not." },
    ],
    power: { targaryen: 9, velaryon: 8, hightower: 6, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Lady Rhea Royce", note: "Daemon's 'bronze bitch' of Runestone — thrown from her horse, then finished. The Vale suspects; the Vale cannot prove." },
      { name: "Ser Joffrey Lonmouth", note: "The Knight of Kisses, Laenor's lover — beaten faceless by Ser Criston Cole at the betrothal feast." },
    ] },
  { n: 6, title: "The Princess and the Queen",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Lord Lyonel Strong" },
    events: [
      "Ten years pass. Rhaenyra births her third son, Joffrey — and carries him, still bloody, across the castle because the queen commanded a look at him.",
      "Every Velaryon prince has brown hair and a plain face; the court whispers Harwin Strong, and Alicent says it out loud.",
      "Ser Harwin breaks his fist on Ser Criston's face defending his... the princess's sons, and is dismissed from the Watch to Harrenhal.",
      "In Pentos, Laena Velaryon's second labor goes the way of Aemma's — she walks to Vhagar instead and commands her own pyre: 'Dracarys.'",
      "Larys Strong arranges a fire at Harrenhal: his father the Hand and his brother Harwin burn, and no one owes him anything he can't collect.",
      "Rhaenyra sees the court for what it is and removes her family to Dragonstone.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Offers the queen a marriage pact for peace; gets a decade of cold war instead." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Done being patient. The green council starts here, in a decade of small cuts." },
      { name: "Daemon Targaryen", j: "daemon", note: "A husband and father in Pentos, almost at peace — until the pyre." },
      { name: "Laena Velaryon", loc: "pentos", note: "Chooses a dragonrider's death over a mother's." },
      { name: "Harwin Strong", loc: "harrenhal", note: "Breaker of Bones, breaker of secrets — his sons will never bear his name." },
      { name: "Larys Strong", loc: "kings-landing", note: "Burns his own house to buy a queen's debt." },
    ],
    power: { targaryen: 9, velaryon: 7, hightower: 7, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Laena Velaryon", note: "Rider of Vhagar. Dying of childbed, she walked to her dragon and gave the command herself: Dracarys." },
      { name: "Lord Lyonel Strong", note: "Hand of the King, burned in his bed at Harrenhal by his younger son's design." },
      { name: "Ser Harwin Strong", note: "Breakbones — the strongest knight in the realm, and true father of Rhaenyra's boys, dead in the same fire." },
    ] },
  { n: 7, title: "Driftmark",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "Laena is given to the sea at Driftmark, all the realm's dragons and grievances gathered on one island for a funeral.",
      "In the night, Aemond climbs onto Vhagar — the greatest dragon alive answers a ten-year-old's nerve, and the realm's balance shifts.",
      "Laena's daughters and Rhaenyra's sons fall on him in the yard; knives and fists in the dark, and Lucerys cuts out Aemond's eye.",
      "Alicent demands an eye for an eye; when the king refuses, she takes the blade from his own belt and cuts Rhaenyra's arm reaching for Luke's face.",
      "'He called my sons bastards' — and Viserys, who heard, rules only that the matter never be spoken of again.",
      "Rhaenyra and Daemon wed on Dragonstone's shore in the old Valyrian way — over a fresh corpse in Laenor's clothes, while Laenor rows for Essos, alive and free.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Buries a friend, bleeds for her sons, and finally marries the man she chose at ten." },
      { name: "Daemon Targaryen", j: "daemon", note: "Grieves a wife, frees a 'dead' man, and weds the heir to the throne." },
      { name: "Alicent Hightower", loc: "driftmark", note: "The queen draws blood with the king's own dagger — and her father approves." },
      { name: "Aemond Targaryen", loc: "driftmark", note: "Traded an eye for the greatest dragon in the world, and counts it a bargain. Says so." },
      { name: "Lucerys Velaryon", j: "lucerys", note: "A child with a knife makes the war's first wound." },
      { name: "Corlys Velaryon", loc: "driftmark", note: "Buries a daughter and holds his tongue about his grandsons' hair." },
    ],
    power: { targaryen: 9, velaryon: 7, hightower: 7, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "'Laenor Velaryon'", note: "A servant's corpse burned past knowing in the hearth of High Tide. Laenor himself rows for the Free Cities, shorn and free — the realm mourns a living man." },
    ] },
  { n: 8, title: "The Lord of the Tides",
    throne: { king: "Viserys I Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "Six years on: Corlys takes a wound in the Stepstones that festers; his brother Vaemond sails to court to claim Driftmark over the 'strong boys.'",
      "Rhaenyra and Daemon come back to a changed Red Keep — Otto restored as Hand, Alicent ruling a king kept swimming in milk of the poppy.",
      "Viserys drags himself to the Iron Throne, half a face and half a body, to hold the succession for his daughter one last time; Daemon picks up the fallen crown.",
      "Vaemond names Rhaenyra a whore and her sons bastards before the throne — Daemon takes his head off mid-sentence. 'He can keep his tongue.'",
      "One last supper: the family almost heals. Then Viserys, dying, mistakes Alicent for Rhaenyra and whispers Aegon's dream — the prince that was promised — into the wrong ears.",
    ],
    people: [
      { name: "Viserys I Targaryen", loc: "kings-landing", note: "One last climb to the throne, one fatal whisper off it." },
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Wins Driftmark for her son and loses her father by morning." },
      { name: "Daemon Targaryen", j: "daemon", note: "Crowns his brother with his own hands; uncrowns Vaemond with Dark Sister." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Hears 'Aegon' from a dying king and believes what she needs to." },
      { name: "Vaemond Velaryon", loc: "kings-landing", note: "Says the quiet part before the throne. Briefly." },
      { name: "Rhaenys Targaryen", loc: "kings-landing", note: "Backs Rhaenyra's sons for Driftmark — for Laena's daughters' sake." },
    ],
    power: { targaryen: 9, velaryon: 7, hightower: 8, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Ser Vaemond Velaryon", note: "The Sea Snake's brother, beheaded crown-to-jaw by Dark Sister before the Iron Throne — his tongue, as promised, untouched." },
      { name: "King Viserys I Targaryen", note: "The fifth Targaryen king, dead in his bed at last — 'my love' — leaving a dream in the wrong ears and a realm with two heirs." },
    ] },
  { n: 9, title: "The Green Council",
    throne: { king: "Aegon II Targaryen", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "The king is dead, and only the greens know. The Red Keep is sealed while Otto's council — planning this for years — moves to crown Aegon.",
      "Old Lord Beesbury alone objects that this is treason; Ser Criston opens his throat on the council table.",
      "Aegon is nowhere: a hunt through Flea Bottom finds the heir hiding from his own crown, dragged out by the White Worm's price.",
      "Rhaenys is locked in her chambers, courted for Meleys — and escapes with Ser Erryk through the crowds being herded to the Dragonpit.",
      "Aegon II is crowned before the mob with the Conqueror's crown and blade — until Meleys bursts through the pit floor, and Rhaenys, with the greens at her mercy, spares them and flies to Dragonstone.",
    ],
    people: [
      { name: "Alicent Hightower", loc: "kings-landing", note: "Discovers her father planned a usurpation while she planned a mercy." },
      { name: "Otto Hightower", loc: "kings-landing", note: "Twenty years of moves, one morning of checkmate." },
      { name: "Aegon II Targaryen", loc: "kings-landing", note: "Found in a sept, crowned in a pit, wanted by no one — least of all himself. Until the crowd roars." },
      { name: "Aemond Targaryen", loc: "kings-landing", note: "Hunts his brother through the gutters and would rather keep what he finds." },
      { name: "Criston Cole", loc: "kings-landing", note: "Kingmaker now, by his own hand and an old man's blood." },
      { name: "Rhaenys Targaryen", loc: "kings-landing", note: "Has the whole green court under Meleys' jaws — and chooses not to start the war herself." },
    ],
    power: { targaryen: 8, velaryon: 7, hightower: 9, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 5, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Lord Lyman Beesbury", note: "Master of coin for three kings — the only man at the green council to say the word 'treason,' and the Dance's first death, opened on the table by Ser Criston Cole." },
    ] },
  { n: 10, title: "The Black Queen",
    throne: { king: "Aegon II Targaryen — and Rhaenyra, crowned in defiance", house: "targaryen", hand: "Ser Otto Hightower — for the greens; Daemon speaks for the blacks" },
    events: [
      "Word of the usurpation reaches Dragonstone; the shock sends Rhaenyra into early labor, and she buries a daughter, Visenya, the same day.",
      "Ser Erryk Cargyll arrives with a stolen crown; Daemon sets Viserys's crown on Rhaenyra's head on the shore of Dragonstone.",
      "The painted table counts its strength: the Vale, the North, the riverlands to win; thirteen dragons to the greens' four — and Daemon wants them flying now.",
      "Otto comes under the peace banner with terms; Rhaenyra answers with the words of a queen, not a rebel — and holds Daemon's war back.",
      "Jacaerys flies for the Eyrie and Winterfell, Lucerys for Storm's End — envoys, not warriors. At Storm's End waits Vhagar.",
      "Above Shipbreaker Bay, Aemond's game stops being a game: Vhagar takes Arrax and Lucerys both — and Rhaenyra's face, hearing it, ends the peace.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", j: "rhaenyra", note: "Crowned, bereaved twice over, and — in the last shot of the season — done with restraint." },
      { name: "Daemon Targaryen", j: "daemon", note: "Chokes his queen over a dream he was never told, then brings her the worst news in the world." },
      { name: "Jacaerys Velaryon", loc: "dragonstone", note: "Sworn to win his mother the mountain and the snow." },
      { name: "Lucerys Velaryon", j: "lucerys", note: "A messenger, not a warrior. It doesn't save him." },
      { name: "Aemond Targaryen", loc: "storms-end", note: "Wanted to frighten the boy, not kill him. Vhagar had her own opinion. 'One eye for a kingdom.'" },
      { name: "Corlys Velaryon", loc: "dragonstone", note: "Rises from his sickbed to lay the Velaryon fleet at the black queen's feet." },
      { name: "Rhaenys Targaryen", loc: "dragonstone", note: "Holds the Gullet for Rhaenyra — the realm's finest admiral answers to a queen at last." },
    ],
    power: { targaryen: 8, velaryon: 8, hightower: 8, stark: 5, lannister: 6, arryn: 5, tully: 5, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Princess Visenya Targaryen", note: "Rhaenyra's daughter, born too soon in the shock of the usurpation, and buried on Dragonstone the day of her birth." },
      { name: "Prince Lucerys Velaryon", note: "Taken with his young dragon Arrax in Vhagar's jaws above Shipbreaker Bay. The war's first royal blood — and its point of no return." },
    ] },
];

/* expand rows into location objects */
WORLD.locations = LOCATION_ROWS.map(([name, x, y, type, region, rank, subtitle, description]) => {
  const id = name.toLowerCase().replace(/[''’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const minorArms = MINOR_ARMS[id] ? { ...MINOR_ARMS[id] } : null;
  if (minorArms && CANON_MINOR_SHIELDS.has(id)) minorArms.img = `minor/${id}.png`;
  return {
    id, name, x, y, type, region, rank, subtitle, description,
    lore: SEASON_LORE[id] || null,
    house: HOUSE_SEATS[id] || null,
    minorArms,
  };
});
