/* HOUSE OF THE DRAGON - character portraits (in-costume show stills, square-cropped).
   Keys are the exact display names used in episode/book people lists, journeys,
   and house rosters; several honorific aliases point at the same file. */
const PEOPLE_IMGS = {
  // ---- the royal line ----
  "Viserys I Targaryen": "viserys-i.jpg",
  "King Viserys I Targaryen": "viserys-i.jpg",
  "Rhaenyra Targaryen": "rhaenyra-targaryen.jpg",
  "Queen Rhaenyra Targaryen": "rhaenyra-targaryen.jpg",
  "Daemon Targaryen": "daemon-targaryen.jpg",
  "Prince Daemon Targaryen": "daemon-targaryen.jpg",
  "Alicent Hightower": "alicent-hightower.jpg",
  "Queen Alicent Hightower": "alicent-hightower.jpg",
  "Aegon II Targaryen": "aegon-ii.jpg",
  "King Aegon II Targaryen": "aegon-ii.jpg",
  "Helaena Targaryen": "helaena-targaryen.jpg",
  "Queen Helaena Targaryen": "helaena-targaryen.jpg",
  "Aemond Targaryen": "aemond-targaryen.jpg",
  "Prince Aemond Targaryen": "aemond-targaryen.jpg",
  "Jaehaerys Targaryen": "jaehaerys-targaryen.jpg",
  "Prince Jaehaerys Targaryen": "jaehaerys-targaryen.jpg",
  "Jaehaera Targaryen": "jaehaera-targaryen.jpg",
  "Aegon the Younger": "aegon-the-younger.jpg",
  "Viserys the Younger": "viserys-the-younger.jpg",
  "Aemma Arryn": "aemma-arryn.jpg",
  "Queen Aemma Arryn": "aemma-arryn.jpg",
  "Rhaenys Targaryen": "rhaenys-targaryen.jpg",
  "Princess Rhaenys Targaryen": "rhaenys-targaryen.jpg",
  "Baela Targaryen": "baela-targaryen.jpg",
  "Rhaena Targaryen": "rhaena-targaryen.jpg",

  // ---- House Velaryon ----
  "Corlys Velaryon": "corlys-velaryon.jpg",
  "Laena Velaryon": "laena-velaryon.jpg",
  "Laenor Velaryon": "laenor-velaryon.jpg",
  "Ser Laenor Velaryon": "laenor-velaryon.jpg",
  "Vaemond Velaryon": "vaemond-velaryon.jpg",
  "Ser Vaemond Velaryon": "vaemond-velaryon.jpg",
  "Jacaerys Velaryon": "jacaerys-velaryon.jpg",
  "Prince Jacaerys Velaryon": "jacaerys-velaryon.jpg",
  "Lucerys Velaryon": "lucerys-velaryon.jpg",
  "Prince Lucerys Velaryon": "lucerys-velaryon.jpg",
  "Joffrey Velaryon": "joffrey-velaryon.jpg",
  "Prince Joffrey Velaryon": "joffrey-velaryon.jpg",
  "Alyn of Hull": "alyn-of-hull.jpg",
  "Addam of Hull": "addam-of-hull.jpg",
  "Ser Addam Velaryon": "addam-of-hull.jpg",

  // ---- the greens ----
  "Otto Hightower": "otto-hightower.jpg",
  "Ser Otto Hightower": "otto-hightower.jpg",
  "Gwayne Hightower": "gwayne-hightower.jpg",
  "Criston Cole": "criston-cole.jpg",
  "Ser Criston Cole": "criston-cole.jpg",
  "Larys Strong": "larys-strong.jpg",
  "Lyman Beesbury": "lyman-beesbury.jpg",
  "Lord Lyman Beesbury": "lyman-beesbury.jpg",
  "Arryk Cargyll": "arryk-cargyll.jpg",
  "Ser Arryk Cargyll": "arryk-cargyll.jpg",
  "Erryk Cargyll": "erryk-cargyll.jpg",
  "Ser Erryk Cargyll": "erryk-cargyll.jpg",

  // ---- House Strong & Harrenhal ----
  "Lyonel Strong": "lyonel-strong.jpg",
  "Lord Lyonel Strong": "lyonel-strong.jpg",
  "Harwin Strong": "harwin-strong.jpg",
  "Ser Harwin Strong": "harwin-strong.jpg",
  "Simon Strong": "simon-strong.jpg",
  "Alys Rivers": "alys-rivers.jpg",

  // ---- the queen's court & the realm ----
  "Mysaria": "mysaria.jpg",
  "Rhea Royce": "rhea-royce.jpg",
  "Lady Rhea Royce": "rhea-royce.jpg",
  "Joffrey Lonmouth": "joffrey-lonmouth.jpg",
  "Ser Joffrey Lonmouth": "joffrey-lonmouth.jpg",
  "Craghas Drahar": "craghas-drahar.jpg",
  "Craghas Drahar, the Crabfeeder": "craghas-drahar.jpg",
  "Steffon Darklyn": "steffon-darklyn.jpg",
  "Ser Steffon Darklyn": "steffon-darklyn.jpg",
  "Gunthor Darklyn": "gunthor-darklyn.jpg",
  "Lord Gunthor Darklyn": "gunthor-darklyn.jpg",
  "Hugh Hammer": "hugh-hammer.jpg",
  "Ulf the White": "ulf-the-white.jpg",
  "Cregan Stark": "cregan-stark.jpg",
  "Jeyne Arryn": "jeyne-arryn.jpg",
  "Jason Lannister": "jason-lannister.jpg",
  "Tyland Lannister": "tyland-lannister.jpg",
  "Borros Baratheon": "borros-baratheon.jpg",
  "Willem Blackwood": "willem-blackwood.jpg",
  "Sharako Lohar": "sharako-lohar.jpg",
};
