/* HOUSE OF THE DRAGON — Season Two, episode by episode.
   Same format as Season One's EPISODES (js/data.js). Journey traces (j:) exist
   only for Season One's presets; later episodes anchor people to locations. */

const SEASONS_LATER = [

// ==================== SEASON TWO ====================
{ n: 2, name: "Season Two", episodes: [
  { n: 1, title: "A Son for a Son",
    throne: { king: "Aegon II Targaryen — Rhaenyra unbowed on Dragonstone", house: "targaryen", hand: "Ser Otto Hightower" },
    events: [
      "Jacaerys treats with Cregan Stark on the Wall itself: the North remembers its oath, and the Pact of Ice and Fire is sworn.",
      "Rhaenyra combs the shores of Shipbreaker Bay until she finds a wing of Arrax — and speaks her first words in an episode of grief: 'I want Aemond Targaryen.'",
      "Corlys's blockade closes the Gullet; King's Landing begins to feel the first pinch of hunger.",
      "Daemon buys two ratcatchers — Blood and Cheese — and sends them into the Red Keep for 'a son for a son.'",
      "Unable to find Aemond, they take the head of Helaena's boy Jaehaerys while his mother watches: the green court's grief now matches the black's.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", loc: "storms-end", note: "Searches the wreck-strewn coast for what Vhagar left of her son." },
      { name: "Daemon Targaryen", loc: "kings-landing", note: "Buys vengeance in the city he once policed — and doesn't specify enough." },
      { name: "Jacaerys Velaryon", loc: "castle-black", note: "Wins the North with honesty, then hears about Luke." },
      { name: "Cregan Stark", loc: "castle-black", note: "The Wolf of the North shows a southern prince what oaths mean up here." },
      { name: "Helaena Targaryen", loc: "kings-landing", note: "Asked by killers to choose which son. She pays for the war's madness first." },
      { name: "Aegon II Targaryen", loc: "kings-landing", note: "Plays at kingship on his father's throne until grief comes to his own nursery." },
    ],
    power: { targaryen: 8, velaryon: 8, hightower: 8, stark: 6, lannister: 6, arryn: 5, tully: 5, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Prince Jaehaerys Targaryen", note: "Aegon and Helaena's small son, beheaded in his bed by Blood and Cheese — a son for a son, and a war past all mending." },
    ] },
  { n: 2, title: "Rhaenyra the Cruel",
    throne: { king: "Aegon II Targaryen — Rhaenyra unbowed on Dragonstone", house: "targaryen", hand: "Ser Otto Hightower, then Ser Criston Cole" },
    events: [
      "Otto turns Jaehaerys's funeral into a procession through the streets — grief as statecraft, 'Rhaenyra the Cruel' on every crier's lips.",
      "Aegon rages past his grandsire's counsel; Otto is stripped of the Hand's badge for the second time in his life, and Criston Cole takes it.",
      "The ratcatcher Blood is caught and broken; Aegon hangs every ratcatcher in the city, guilty and innocent alike, on the walls.",
      "Ser Arryk Cargyll is sent to Dragonstone wearing his twin's face; Ser Erryk finds him at Rhaenyra's door.",
      "Twin kills twin in the black queen's hall — and Erryk, having slain his brother, falls on his own sword for the shame of it.",
    ],
    people: [
      { name: "Otto Hightower", loc: "kings-landing", note: "Loses the badge to a king who prefers rage to chess." },
      { name: "Aegon II Targaryen", loc: "kings-landing", note: "Answers one murdered child with twenty hanged fathers." },
      { name: "Criston Cole", loc: "kings-landing", note: "Hand of the King now — and author of the war's stupidest gambit." },
      { name: "Rhaenyra Targaryen", loc: "dragonstone", note: "Wakes to steel in her own chamber and two dead men who shared one face." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Shares a bed with the Hand and a conscience with no one." },
      { name: "Mysaria", loc: "dragonstone", note: "The White Worm, traded to Dragonstone — where her worth is finally seen." },
    ],
    power: { targaryen: 8, velaryon: 8, hightower: 8, stark: 6, lannister: 6, arryn: 5, tully: 5, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Ser Arryk Cargyll", note: "Sent in his twin's likeness to murder Rhaenyra — cut down by his own brother in her hall." },
      { name: "Ser Erryk Cargyll", note: "Slew the brother he loved for the queen he chose, then fell on his sword weeping." },
      { name: "Blood", note: "The butcher of Prince Jaehaerys, broken by the king's questioners and hanged." },
    ] },
  { n: 3, title: "The Burning Mill",
    throne: { king: "Aegon II Targaryen — Rhaenyra unbowed on Dragonstone", house: "targaryen", hand: "Ser Criston Cole" },
    events: [
      "The riverlands catch first: Blackwood boys and Bracken boys turn a quarrel of stones into the Battle of the Burning Mill — fields of dead over old grudges wearing new crowns.",
      "Daemon flies Caraxes to Harrenhal and takes the greatest castle in Westeros without a blow; Ser Simon Strong yields it with supper.",
      "Criston Cole marches out with the green host, bending black-sworn Rosby and Stokeworth into line — and Baela hunts him from dragonback.",
      "Rhaenyra slips into King's Landing in a septa's robes to ask Alicent, face to face, if war is truly past stopping. It is.",
      "Alicent knows the truth now — 'the prince that was promised' was never her Aegon — and lets the war continue anyway.",
    ],
    people: [
      { name: "Daemon Targaryen", loc: "harrenhal", note: "Wins Harrenhal with a landing, then starts losing to the castle itself." },
      { name: "Rhaenyra Targaryen", loc: "kings-landing", note: "Risks everything on one last conversation in the sept. It buys nothing." },
      { name: "Criston Cole", loc: "rosby", note: "The Hand marches — a kingmaker learning what kings cost." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Hears the dead king's words rightly at last, and swallows them." },
      { name: "Baela Targaryen", loc: "rooks-rest", note: "Moondancer's rider shadows the green host from the clouds." },
      { name: "Willem Blackwood", loc: "raventree-hall", note: "Kneels to Daemon for leave to settle nine hundred years of Bracken scores." },
    ],
    power: { targaryen: 8, velaryon: 8, hightower: 8, stark: 6, lannister: 6, arryn: 5, tully: 6, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "The sons of Raventree and Stone Hedge", note: "Blackwood and Bracken dead heaped around a burned mill on the Red Fork — the first battle of the Dance, fought over dragons by boys without any." },
    ] },
  { n: 4, title: "The Red Dragon and the Gold",
    throne: { king: "Aegon II Targaryen — Rhaenyra unbowed on Dragonstone", house: "targaryen", hand: "Ser Criston Cole" },
    events: [
      "Daemon holds a ghost-ridden Harrenhal, dosed by Alys Rivers's draughts, dreaming of everything he broke.",
      "Criston Cole takes Duskendale — Lord Darklyn keeps his loyalty and loses his head — then marches on Rook's Rest by night.",
      "Rhaenys and Meleys answer Rook's Rest; the trap closes: Aegon comes half-drunk on Sunfyre, and Aemond brings Vhagar for both dragons.",
      "Aemond's fire takes king and enemy alike — Sunfyre and Aegon fall broken into the wood.",
      "Rhaenys, clear of the fight, turns Meleys back into Vhagar's teeth rather than run. The Queen Who Never Was dies a queen's death.",
    ],
    people: [
      { name: "Rhaenys Targaryen", loc: "rooks-rest", note: "Flies to a small castle's defense and into the war's first dragon-fall." },
      { name: "Aegon II Targaryen", loc: "rooks-rest", note: "Rides to his own battle unannounced to feel like a king. Carried home in pieces." },
      { name: "Aemond Targaryen", loc: "rooks-rest", note: "Burns the enemy and the brother in one pass, and walks away regent in all but name." },
      { name: "Criston Cole", loc: "rooks-rest", note: "His trap works — at the cost of a king he'll now have to explain." },
      { name: "Daemon Targaryen", loc: "harrenhal", note: "Fights the only enemy Caraxes can't burn: Harrenhal, and himself." },
      { name: "Corlys Velaryon", loc: "dragonstone", note: "Waits at the heart of the blockade for a wife who doesn't come home." },
    ],
    power: { targaryen: 7, velaryon: 7, hightower: 9, stark: 6, lannister: 6, arryn: 5, tully: 6, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Princess Rhaenys Targaryen", note: "The Queen Who Never Was, with her Red Queen Meleys — turned back into a hopeless fight at Rook's Rest and died refusing to run from it." },
      { name: "Lord Gunthor Darklyn", note: "Master of Duskendale, beheaded by the Hand for keeping the oath he swore to Rhaenyra." },
    ] },
  { n: 5, title: "Regent",
    throne: { king: "Aegon II Targaryen, burned and senseless — Aemond rules as regent", house: "targaryen", hand: "Ser Criston Cole" },
    events: [
      "Aegon lives — barely: burned, broken, and drowned in milk of the poppy. The green council passes the rule to Aemond, not Alicent.",
      "Meleys's head is dragged through King's Landing as a trophy; the smallfolk see only proof that dragons can die, and begin to slip out of the city.",
      "On Driftmark, Alyn of Hull — the sailor who pulled the Sea Snake from the waves — is owed more than wages, and Corlys knows it.",
      "Rhaenyra sends Rhaena to the Vale with the youngest children and a clutch of dragon eggs; Jace chafes at being an heir kept from the war.",
      "Daemon's Harrenhal dreams deepen; the riverlords test him, and Willem Blackwood's brutality against the Brackens does his recruiting.",
    ],
    people: [
      { name: "Aemond Targaryen", loc: "kings-landing", note: "Prince regent — the realm in the hand that burned its king." },
      { name: "Alicent Hightower", loc: "kings-landing", note: "Passed over by her own council for the son she can least restrain." },
      { name: "Corlys Velaryon", loc: "driftmark", note: "Made Rhaenyra's Hand — and faced at the docks by his unclaimed blood." },
      { name: "Alyn of Hull", loc: "driftmark", note: "Saved his father's life and wants nothing for it, which is the problem." },
      { name: "Rhaena Targaryen", loc: "the-eyrie", note: "Sent to safety with the eggs — a dragonless Targaryen minding the future." },
      { name: "Daemon Targaryen", loc: "harrenhal", note: "Crowns himself in dreams while the rivers wait for him to wake." },
    ],
    power: { targaryen: 7, velaryon: 7, hightower: 8, stark: 6, lannister: 6, arryn: 5, tully: 6, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [] },
  { n: 6, title: "Smallfolk",
    throne: { king: "Aegon II Targaryen, senseless — Aemond Targaryen, Prince Regent", house: "targaryen", hand: "Ser Criston Cole" },
    events: [
      "Hunger bites King's Landing; Rhaenyra and Mysaria feed the city from black ships, and the smallfolk begin to love the queen who feeds them.",
      "Ser Steffon Darklyn dies in fire on Dragonstone's slopes, trying to claim the riderless Seasmoke for the blacks.",
      "Seasmoke does his own choosing: he hunts down Addam of Hull on Driftmark and takes him into the sky alive.",
      "In the riverlands, Daemon lets the Blackwoods loose on Bracken lands — and learns that terror recruits enemies faster than banners.",
      "Aemond answers the blockade's noose the only way he knows: Vhagar burns black-sworn towns along the crownlands coast.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", loc: "dragonstone", note: "Discovers her sharpest weapon is bread with a queen's seal on it." },
      { name: "Mysaria", loc: "dragonstone", note: "The White Worm turns the city's hunger into the black queen's love." },
      { name: "Addam of Hull", loc: "driftmark", note: "Ran from a dragon and got chosen anyway — the first of the seeds." },
      { name: "Corlys Velaryon", loc: "driftmark", note: "Watches a bastard son rise on a dragon he never dared acknowledge." },
      { name: "Aemond Targaryen", loc: "kings-landing", note: "A regent who answers arithmetic with fire." },
      { name: "Larys Strong", loc: "kings-landing", note: "Begins quietly packing the king he may need later." },
    ],
    power: { targaryen: 7, velaryon: 7, hightower: 8, stark: 6, lannister: 6, arryn: 5, tully: 6, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "Ser Steffon Darklyn", note: "Lord commander of the queen's guard, burned and fallen on Dragonstone's slopes trying to claim Seasmoke with pedigree instead of blood." },
    ] },
  { n: 7, title: "The Red Sowing",
    throne: { king: "Aegon II Targaryen, senseless — Aemond Targaryen, Prince Regent", house: "targaryen", hand: "Ser Criston Cole" },
    events: [
      "Addam's claiming shows the way: Rhaenyra summons Targaryen bastards and dragon-blooded smallfolk from every brothel and shipyard — the Red Sowing.",
      "Vermithor is loosed among the claimants; dozens burn so that two may rise.",
      "Hugh Hammer, a blacksmith's bastard, masters Vermithor, the Bronze Fury — second only to Vhagar; Ulf the White stumbles drunk onto Silverwing.",
      "Jace watches smallfolk mount dragons and feels his own claim thin; Rhaenyra now commands more dragons than the greens can ever answer.",
      "Aemond burns Sharp Point rather than see it feed the blacks — and finds Rhaenyra's new riders already in the sky over the bay.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", loc: "dragonstone", note: "Trades pure blood for airpower and wins the arithmetic of the war." },
      { name: "Hugh Hammer", loc: "dragonstone", note: "A smith who asked the crown for back pay now rides the Bronze Fury." },
      { name: "Ulf the White", loc: "dragonstone", note: "A tavern boaster whose one true story got him a dragon." },
      { name: "Jacaerys Velaryon", loc: "dragonstone", note: "Won the North with his name; watches the name matter less by the hour." },
      { name: "Aemond Targaryen", loc: "kings-landing", note: "For the first time since Rook's Rest — outnumbered in the sky." },
      { name: "Baela Targaryen", loc: "dragonstone", note: "Flies patrol over a fleet her grandfather built and her family finally uses." },
    ],
    power: { targaryen: 7, velaryon: 8, hightower: 7, stark: 6, lannister: 6, arryn: 5, tully: 6, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [
      { name: "The burned claimants of the Sowing", note: "Dozens of dragon-blooded hopefuls, cooked in Vermithor's fire on Dragonstone's slopes — the price of two new riders." },
    ] },
  { n: 8, title: "The Queen Who Ever Was",
    throne: { king: "Aegon II Targaryen, spirited from the city — Aemond Targaryen, Prince Regent", house: "targaryen", hand: "Ser Criston Cole" },
    events: [
      "The realm draws up for the battles to come: the Hightower host under Daeron, the Lannisters from the west, Cregan's northmen marching south, the Velaryon fleet massing for the Gullet.",
      "In Essos, Tyland Lannister wins the Triarchy's ninety ships for the greens — Admiral Lohar's fleet will sail to break the blockade.",
      "At Harrenhal, Daemon's visions end in the one that matters — the Song of Ice and Fire — and when Rhaenyra lands, he kneels: her king consort, her army, hers.",
      "Larys Strong smuggles the broken Aegon out of King's Landing before Rhaenyra's dragons can find him.",
      "Alicent comes alone to Dragonstone: take the city, take the crown, spare Aegon — 'and what of Aemond?' The season ends with every piece in motion and the Gullet waiting.",
    ],
    people: [
      { name: "Rhaenyra Targaryen", loc: "dragonstone", note: "Hears her enemy's mother offer her King's Landing — and knows the price will be paid in fire anyway." },
      { name: "Daemon Targaryen", loc: "harrenhal", note: "Sees the dream at last, and kneels to it — the rogue prince, done running." },
      { name: "Alicent Hightower", loc: "dragonstone", note: "Crosses the water to end what her father started, one son too late." },
      { name: "Aemond Targaryen", loc: "kings-landing", note: "Regent of a city his enemies feed and his allies flee." },
      { name: "Tyland Lannister", loc: "the-stepstones", note: "Wins a fleet with statecraft and a mud-wrestling match." },
      { name: "Otto Hightower", loc: "kings-landing", note: "In a black cell, watching his life's work run out of his family's hands." },
      { name: "Cregan Stark", loc: "winterfell", note: "The Wolf of the North starts his long cold march." },
    ],
    power: { targaryen: 7, velaryon: 8, hightower: 8, stark: 7, lannister: 7, arryn: 5, tully: 6, baratheon: 6, greyjoy: 3, tyrell: 5, martell: 4, frey: 3 },
    deaths: [] },
] },
];
