/* HOUSE OF THE DRAGON WIKI — hand-written long-form articles ("The fuller tale").
   Keys: a character's exact name, "house:<id>", or "loc:<id>".
   Values: an array of paragraphs (original text — never copied from any wiki). */

const WIKI_EXTRA = {

  "Rhaenyra Targaryen": [
    "Rhaenyra is raised as the Realm's Delight — cupbearer to her father's court, rider of Syrax, the princess the songs are polite to. Everything changes when King Viserys, grieving a wife and a son lost in one terrible day, does the unthinkable: he names his daughter heir to the Iron Throne and makes every lord in the realm kneel to swear it. The oaths are given; the story is about how much oaths weigh once the man who demanded them is gone.",
    "Her middle years are a war fought with reputations before it is fought with dragons. Her sons' parentage becomes the court's favorite whisper, her friendship with Alicent curdles into the realm's defining feud, and her marriage to Daemon binds the family's two sharpest blades to one cause. Exiled in all but name to Dragonstone, she builds the court her father's court never let her have — and waits, as heirs must, while the greens gather around the king's failing bed.",
    "When the crown is stolen at her father's death, Rhaenyra's war begins with a funeral: word of Lucerys' death over Shipbreaker Bay arrives as her stillborn daughter is laid to rest, and the queen who wanted to be crowned in peace is remade by grief. The Dance that follows costs her everything the crown was supposed to be for — her sons, her city, her house's dragons, and at the last, on the shores of her own island, her life. The books' bleak accounting gives her the throne for half a year and the history books to her enemies; the story gives her the truth of it — she was the heir, and the realm broke its word.",
  ],
  "Daemon Targaryen": [
    "Daemon is the sword the dynasty keeps drawing and regretting: brother to the king, commander of the City Watch (which he arms with gold cloaks and teaches to break bones), heir presumptive whenever Viserys is between sons, and exile whenever his tongue outruns his welcome. He grieves in brothels, jokes at funerals, and loves his brother with a violence indistinguishable, on bad days, from rivalry. The court calls him dangerous, which is fair, and simple, which is not.",
    "His wars make him. In the Stepstones he spends years burning the Triarchy's pirates off the rocks half for the realm and half for the insult of being replaced, and takes a crown of driftwood he immediately hands away — the most Daemon gesture in the canon. His marriages trace the age: Rhea Royce, unloved and unlucky; Laena Velaryon, who chose a dragonrider's death; and at last Rhaenyra, his brother's heir, the match the court dreaded and the one that finally gives his loyalty a fixed address.",
    "In the Dance, Daemon is the black council's edge — taker of Harrenhal, orchestrator of the war's darkest bargain (a son for a son, paid by Blood and Cheese in the Red Keep's nursery), and finally the realm's last word on what a dragonrider is. Above the Gods Eye he meets Aemond and Vhagar in the war's most famous duel, leaps from Caraxes with Dark Sister in hand, and takes his nephew into the lake with him. The song says neither body was ever found — which the fishermen of the Gods Eye, and the books themselves, decline to entirely believe.",
  ],
  "Alicent Hightower": [
    "Alicent enters the story as a girl doing as she is told: her father Otto sends her to comfort a grieving king with readings and conversation, and the comfort ends in a marriage that makes her queen before she is out of girlhood. Her friendship with Rhaenyra — real, close, the last unguarded thing either of them owns — becomes the war's first casualty, traded away in increments of duty, jealousy and a green dress worn like a declaration.",
    "For twenty years she is the realm's most disciplined woman: bearing the king's children, managing his decline, holding the Hightower faction together while insisting to herself it is not a faction. Her sons are her cause and her sentence — Aegon, whom she must make a king out of a tavern crawl; Aemond, whose losses she cannot mend; Helaena, whose gifts no one in the family knows how to hear. Every sacrifice is made for children who mostly needed her to stop sacrificing.",
    "The succession is her tragedy in miniature: hearing a dying man's rambling about a prince that was promised, she believes — or chooses to believe — that Viserys named Aegon at the last, and the machinery of the green council does the rest. The war she helped light burns past all her attempts to bank it: she outlives her husband, her sons, and her power, ending as a prisoner of the peace in the keep she once ruled. The books leave her at a window; the story leaves the question open — how much did she know, and how much did she need not to.",
  ],
  "Viserys I Targaryen": [
    "Viserys inherits the realm at its zenith and wants, sincerely, to be worthy of it: chosen by the Great Council over Rhaenys' better claim, he is a king of feasts, models and peace — a decent man in a chair built for conquerors. His reign's great wound is domestic: the death of Queen Aemma in a birthing bed he chose to make bloody, buying an heir who lives a day. What follows — naming Rhaenyra heir, marrying Alicent, refusing for decades to unmake either decision — is a good man's stubbornness doing a bad king's damage.",
    "His long dying is the story's slow fuse. As the greens and blacks form around his failing body, Viserys keeps the peace by declining to notice the war, rising once, ruined and half-masked, to drag himself the length of the throne room in the crown he never wanted to fight for — the reign's one unanswerable act of majesty. He dies asking Aemma's forgiveness and murmuring of Aegon's dream, and the wrong ears take the wrong meaning: the peace he kept alive by hand dies with him, the same night.",
  ],
  "Aegon II Targaryen": [
    "Aegon the Elder never asked for the crown — that much of his defense is true. A tavern prince with a cruel streak and an aching need to be loved by a father who barely saw him, he is dragged from hiding on usurpation morning and crowned in the Dragonpit by a faction that wants his name, not his opinions. Sunfyre, the most beautiful dragon in the world, is the one thing in his life that chose him.",
    "His war is a catalogue of costs: his son Jaehaerys murdered in the nursery as payment for Lucerys, his own body broken at Rook's Rest by a trap that also cost his sister Rhaenys, his twins and his dragon spent one by one. He ends the Dance technically victorious — his rival fed to his dragon on Dragonstone's shore while he watched — and reigns over ashes for half a year, broken, in constant pain, and increasingly alone. The poison in his wine is history's least mysterious murder; the peace requires him gone, and everyone, including perhaps Aegon, knows it.",
  ],
  "Aemond Targaryen": [
    "Aemond is the second son who did everything harder: mocked as the last dragonless prince, he answers by claiming Vhagar herself — the oldest, vastest living thing in the world — at ten years old, hours after her rider's funeral. The price is an eye, taken by Lucerys' dagger in the brawl that follows, and the exchange rate defines him: a dragon for an eye, and a sapphire in the socket to make sure no one forgets the debt.",
    "He is the greens' best sword and worst counselor — disciplined where Aegon is dissolute, learned where Criston is blunt, and carrying a grievance so well-tended it has a name and an address. Over Shipbreaker Bay he chases Lucerys into the storm, and whether the kill was intended or Vhagar stopped listening, the war stops being political that instant. His occupation of Harrenhal, alone with Alys Rivers and the castle's ghosts, is the strangest chapter in the Dance — and it ends above the Gods Eye, where he meets Daemon knowing exactly how the song will go, and flies to meet it anyway.",
  ],
  "Rhaenys Targaryen": [
    "Rhaenys Targaryen carries the title the realm gave her like a blade worn openly: the Queen Who Never Was. Passed over twice — for her cousin at the Great Council, for being a woman both times — she declines to curdle. With Corlys she builds Driftmark into a power that rivals the crown, raises dragonriding children, and delivers the story's coldest counsel with the calm of a woman who has already survived the worst insult available.",
    "Her hour comes at Rook's Rest, answering the greens' trap so the queen she once resented need not fly into it. Old Meleys against two dragons is arithmetic Rhaenys can do better than anyone — she goes anyway, takes Aegon and Sunfyre out of the war's first half, and falls fighting Vhagar, the death she chose over every softer ending on offer. The Queen Who Never Was is, by the accounting of both colors, the best king the Dance never had.",
  ],
  "Corlys Velaryon": [
    "Corlys Velaryon built what the dragonlords inherited. Nine great voyages to the edges of the maps — Yi Ti, Asshai, the frozen Thousand Islands — made the Sea Snake the richest man in Westeros and Driftmark's High Tide a court to rival any king's. His marriage to Rhaenys joined the realm's greatest sailor to its most wronged royal, and his life's project is simple and enormous: that the blood of the sea horse should sit every throne worth sitting.",
    "The project costs him everything it touches — Laena to a birthing bed, Laenor to a staged death he never learns the truth of, his brother Vaemond to a word said too loudly, and his grandsons' legitimacy to a whisper he must break men for repeating. In the Dance his fleets are the black queen's spine, and his politics her conscience of last resort. The books give him the age's best ending anyway: the Sea Snake outlives the war, serves the boy king's regency, and dies at sea in his bed — every horizon sailed, the hull finally at rest.",
  ],
  "house:targaryen": [
    "In the Dance's century the Targaryens are not a dynasty so much as a weather system: seventeen dragons, two courts, and a family tree pruned entirely with swords. The Old King's peace lasted two generations; the question he settled at the Great Council — can a woman inherit the Iron Throne — turns out to have been postponed, not answered, and his grandchildren litigate it with fire.",
    "The Dance is the house burning its own foundations. Dragon kills dragon over the Gods Eye and Shipbreaker Bay; the smallfolk storm the Dragonpit and butcher the gods they used to cheer; and when the music stops, the creatures that conquered Westeros are reduced to a handful of hatchlings that dwindle to none. Every Targaryen who follows — to Aerys, to Daenerys — inherits the Dance's true legacy: a throne with no dragons under it, held together by a name and the memory of fear.",
  ],
};
